classdef ReportDataBuilder
    %REPORTDATABUILDER Builds reportData from a completed ReverseGnssSimulation.
    %
    % This class owns the mapping from simulation state/history/results into
    % the reportData struct consumed by generateReport.m. It should not create
    % final report tables or figures.

    methods (Static)
        function reportData = fromSimulation(sim)
            xHist = sim.history.x;
            truthHist = sim.history.truth;
            Pdiag = sim.history.covariance_diag;

            reportData = struct();
            reportData.error_budget_status = ...
                ResultBuilder.errorBudgetStatus(sim);

            reportData.time_vec = sim.time_s;
            reportData.total_time_hours = max(sim.time_s) / 3600.0;
            reportData.dt = sim.dt;
            reportData.c = sim.c;
            reportData.num_towers = sim.numTowers;
            reportData.R_earth = sim.constants.earthRadius_m;
            reportData.oscillators = sim.simConfig.clockLibrary;
            reportData.towers = ReportDataBuilder.reportTowers(sim);
            reportData.tower_names = sim.towerNames;
            reportData.receiver_names = sim.receiverNames;

            % Raw inputs used by generateReport.m to build report-specific tables.
            reportData.asset_name = string(sim.assetConfig.name);
            reportData.state_names = StateIndexFactory.stateNames( ...
                sim.towerNames, GroundTimingNetwork.towerClockEkfEnabled(sim.cfg));
            reportData.state_dim = sim.stateDim;
            reportData.state_index = sim.idx;
            reportData.enable_tower_clock_ekf = GroundTimingNetwork.towerClockEkfEnabled(sim.cfg);
            reportData.num_receivers = sim.numReceivers;
            reportData.receiver_offsets_body_m = sim.receiverOffsetsBody_m;
            reportData.initial_truth_position_eci_m = sim.initialTruth0(sim.idx.pos);
            reportData.initial_est_position_eci_m = sim.initialX0(sim.idx.pos);
            reportData.observability_normal_matrix = sim.observabilityNormalMatrix;

            reportData.ekf_pos_error_m = xHist(sim.idx.pos, :) - truthHist(sim.idx.pos, :);
            reportData.ekf_pos_sigma_m = sqrt(max(Pdiag(sim.idx.pos, :), 0));
            reportData.ekf_clock_error_ps = ...
                (xHist(sim.idx.rxClockBias, :) - truthHist(sim.idx.rxClockBias, :)) ./ sim.c .* 1e12;
            reportData.ekf_clock_sigma_ps = ...
                sqrt(max(Pdiag(sim.idx.rxClockBias, :), 0)) ./ sim.c .* 1e12;
            reportData.true_clock_bias_ps = truthHist(sim.idx.rxClockBias, :) ./ sim.c .* 1e12;
            reportData.est_clock_bias_ps = xHist(sim.idx.rxClockBias, :) ./ sim.c .* 1e12;

            if GroundTimingNetwork.towerClockEkfEnabled(sim.cfg)
                reportData.est_tower_clock_bias_ps = ...
                    xHist(sim.idx.towerClockBias, :) ./ sim.c .* 1e12;

                reportData.true_tower_clock_bias_ps = ...
                    truthHist(sim.idx.towerClockBias, :) ./ sim.c .* 1e12;

                reportData.est_tower_clock_drift_psps = ...
                    xHist(sim.idx.towerClockDrift, :) ./ sim.c .* 1e12;

                reportData.true_tower_clock_drift_psps = ...
                    truthHist(sim.idx.towerClockDrift, :) ./ sim.c .* 1e12;
            end

            reportData.innovation_rms_m = sim.history.innovation_rms_m;
            reportData.postfit_innovation_rms_m = sim.history.postfit_innovation_rms_m;
            reportData.nis_history = sim.history.nis_history;
            reportData.nis_degrees_of_freedom = sim.history.measurement_count;
            reportData.innovation_covariance_mean_variance_m2 = ...
                sim.history.innovation_covariance_mean_variance_m2;

            reportData.innovation_covariance_min_variance_m2 = ...
                sim.history.innovation_covariance_min_variance_m2;

            reportData.innovation_covariance_max_variance_m2 = ...
                sim.history.innovation_covariance_max_variance_m2;

            reportData.innovation_covariance_mean_sigma_m = ...
                sqrt(max(reportData.innovation_covariance_mean_variance_m2, 0.0));

            reportData.innovation_covariance_min_sigma_m = ...
                sqrt(max(reportData.innovation_covariance_min_variance_m2, 0.0));

            reportData.innovation_covariance_max_sigma_m = ...
                sqrt(max(reportData.innovation_covariance_max_variance_m2, 0.0));

            reportData.nis_per_degree_of_freedom = ...
                sim.history.nis_per_degree_of_freedom;
            reportData.measurement_covariance_range_mean_variance_m2 = ...
                sim.history.measurement_covariance_range_mean_variance_m2;
            reportData.measurement_covariance_range_max_offdiag_m2 = ...
                sim.history.measurement_covariance_range_max_offdiag_m2;
            reportData.measurement_covariance_range_dimension = ...
                sim.history.measurement_covariance_range_dimension;

            reportData.measurement_covariance_update_mean_variance_m2 = ...
                sim.history.measurement_covariance_update_mean_variance_m2;
            reportData.measurement_covariance_update_max_offdiag_m2 = ...
                sim.history.measurement_covariance_update_max_offdiag_m2;
            reportData.measurement_covariance_update_dimension = ...
                sim.history.measurement_covariance_update_dimension;
            reportData.normalized_innovation_rms = ...
                sim.history.normalized_innovation_rms;
            reportData.sat_pos_history_m = sim.history.sat_pos_history_m;
            reportData.towers_eci_first_m = sim.towersEciFirst_m;
            reportData.final_position_error_m = norm(reportData.ekf_pos_error_m(:, end));
            reportData.final_clock_error_ps = reportData.ekf_clock_error_ps(end);
            reportData.final_innovation_rms_m = sim.history.innovation_rms_m(end);

            reportData.attitude_truth_deg = rad2deg(truthHist(sim.idx.att, :));
            reportData.attitude_est_deg = rad2deg(xHist(sim.idx.att, :));
            reportData.attitude_error_deg = rad2deg( ...
                FrameGeometry.wrapToPi(xHist(sim.idx.att, :) - truthHist(sim.idx.att, :)));
            reportData.attitude_sigma_deg = rad2deg(sqrt(max(Pdiag(sim.idx.att, :), 0)));
            reportData.attitude_state_names = ["roll"; "pitch"; "yaw"];
            reportData.attitude_frame = "body-to-ECI Euler view of q_BI";

            reportData.angular_velocity_truth_degps = rad2deg(truthHist(sim.idx.omega, :));
            reportData.angular_velocity_est_degps = rad2deg(xHist(sim.idx.omega, :));
            reportData.angular_velocity_error_degps = ...
                rad2deg(xHist(sim.idx.omega, :) - truthHist(sim.idx.omega, :));
            reportData.angular_velocity_sigma_degps = ...
                rad2deg(sqrt(max(Pdiag(sim.idx.omega, :), 0)));
            reportData.angular_velocity_state_names = ["omega_x"; "omega_y"; "omega_z"];
            reportData.final_attitude_error_norm_deg = norm(reportData.attitude_error_deg(:, end));
            reportData.final_angular_velocity_error_norm_degps = ...
                norm(reportData.angular_velocity_error_degps(:, end));

            reportData.final_H_pos_rank = sim.history.H_pos_rank_history(end);
            reportData.final_H_att_rank = sim.history.H_att_rank_history(end);
            reportData.final_H_pos_att_clock_rank = sim.history.H_pos_att_clock_rank_history(end);
            reportData.final_H_pos_column_norm = sim.history.H_pos_column_norm_history(:, end);
            reportData.final_H_att_column_norm = sim.history.H_att_column_norm_history(:, end);
            reportData.final_H_rx_clock_bias_column_norm = ...
                sim.history.H_rx_clock_bias_column_norm_history(end);

            reportData.H_rank_history = sim.history.H_rank_history;
            reportData.H_pos_rank_history = sim.history.H_pos_rank_history;
            reportData.H_att_rank_history = sim.history.H_att_rank_history;
            reportData.H_pos_att_clock_rank_history = sim.history.H_pos_att_clock_rank_history;
            reportData.H_rx_clock_bias_column_norm_history = ...
                sim.history.H_rx_clock_bias_column_norm_history;
            reportData.pseudorange_measurement_count = sim.history.pseudorange_measurement_count;

            reportData.final_H_rank = sim.history.H_rank_history(end);
            reportData.H_row_count_history = sim.history.measurement_count;
            reportData.H_column_count_history = sim.stateDim * ones(1, sim.numSteps);
            reportData.H_rank_to_state_dim_history = ...
                sim.history.H_rank_history ./ max(sim.stateDim, 1);
            reportData.H_state_deficiency_history = ...
                sim.stateDim - sim.history.H_rank_history;
            reportData.final_H_rows = sim.history.measurement_count(end);
            reportData.final_H_columns = sim.stateDim;
            reportData.final_H_rank_to_state_dim = reportData.final_H_rank / max(sim.stateDim, 1);
            reportData.final_H_state_deficiency = sim.stateDim - reportData.final_H_rank;

            reportData.true_ground_clock_bias_ps = sim.history.ground_clock_true_m ./ sim.c .* 1e12;
            reportData.tower_clock_correction_s = sim.history.ground_clock_correction_m ./ sim.c;
            reportData.tower_clock_correction_residual_s = ...
                sim.history.ground_clock_residual_m ./ sim.c;
            reportData.tower_clock_correction_sigma_s = ...
                ones(sim.numTowers, sim.numSteps) .* ...
                sqrt(GroundTimingNetwork.residualVariance_m2(sim.cfg, sim.c)) ./ sim.c;

            reportData.prefit_residual_by_receiver_tower_m = ...
                sim.history.prefit_residual_by_receiver_tower_m;
            reportData.postfit_residual_by_receiver_tower_m = ...
                sim.history.postfit_residual_by_receiver_tower_m;
            reportData.pseudorange_by_receiver_tower_m = ...
                sim.history.pseudorange_by_receiver_tower_m;
            reportData.true_range_by_receiver_tower_m = ...
                sim.history.true_range_by_receiver_tower_m;

            reportData.atmosphere = sim.history.atmosphere;
            reportData.propagation = sim.history.propagation;
            if isfield(sim.history, 'non_atmospheric')
                reportData.non_atmospheric = sim.history.non_atmospheric;
            end
            reportData.atmosphere_truth_delay_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_delay_by_receiver_tower_m;
            reportData.atmosphere_truth_residual_by_tower_m = ...
                sim.history.atmosphere_truth_residual_by_tower_m;
            reportData.atmosphere_truth_total_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_total_by_receiver_tower_m;
            reportData.atmosphere_truth_troposphere_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_troposphere_by_receiver_tower_m;
            reportData.atmosphere_truth_ionosphere_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_ionosphere_by_receiver_tower_m;
            reportData.atmosphere_truth_ionosphere_ipp_lat_deg_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_ipp_lat_deg_by_receiver_tower;
            reportData.atmosphere_truth_ionosphere_ipp_lon_deg_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_ipp_lon_deg_by_receiver_tower;
            reportData.atmosphere_truth_ionosphere_vtec_TECU_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_vtec_TECU_by_receiver_tower;
            reportData.atmosphere_truth_ionosphere_stec_TECU_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_stec_TECU_by_receiver_tower;
            reportData.atmosphere_truth_ionosphere_mapping_factor_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_mapping_factor_by_receiver_tower;

            reportData.atmosphere_truth_ionosphere_frequency_Hz_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_frequency_Hz_by_receiver_tower;
            reportData.atmosphere_truth_troposphere_pressure_hPa_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_pressure_hPa_by_receiver_tower;

            reportData.atmosphere_truth_troposphere_temperature_K_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_temperature_K_by_receiver_tower;

            reportData.atmosphere_truth_troposphere_relative_humidity_fraction_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_relative_humidity_fraction_by_receiver_tower;

            reportData.atmosphere_truth_troposphere_water_vapor_pressure_hPa_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_water_vapor_pressure_hPa_by_receiver_tower;

            reportData.atmosphere_truth_troposphere_zhd_m_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_zhd_m_by_receiver_tower;

            reportData.atmosphere_truth_troposphere_zwd_m_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_zwd_m_by_receiver_tower;

            reportData.atmosphere_truth_troposphere_mapping_hydrostatic_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_mapping_hydrostatic_by_receiver_tower;

            reportData.atmosphere_truth_troposphere_mapping_wet_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_mapping_wet_by_receiver_tower;

            reportData.atmosphere_truth_troposphere_slant_hydrostatic_m_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_slant_hydrostatic_m_by_receiver_tower;

            reportData.atmosphere_truth_troposphere_slant_wet_m_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_slant_wet_m_by_receiver_tower;
            reportData.atmosphere_truth_troposphere_residual_by_tower_m = ...
                sim.history.atmosphere_truth_troposphere_residual_by_tower_m;
            reportData.atmosphere_truth_ionosphere_residual_by_tower_m = ...
                sim.history.atmosphere_truth_ionosphere_residual_by_tower_m;
            reportData.atmosphere_truth_troposphere_total_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_troposphere_total_by_receiver_tower_m;
            reportData.atmosphere_truth_ionosphere_total_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_ionosphere_total_by_receiver_tower_m;
            reportData.truth_atmosphere_residual_mean_m = ...
                mean(reportData.atmosphere_truth_residual_by_tower_m(:), ...
                'omitnan');

            reportData.truth_atmosphere_residual_std_m = ...
                std(reportData.atmosphere_truth_residual_by_tower_m(:), ...
                0, ...
                'omitnan');

            reportData.truth_atmosphere_residual_rms_m = ...
                sqrt(mean( ...
                reportData.atmosphere_truth_residual_by_tower_m(:).^2, ...
                'omitnan'));

            reportData.truth_atmosphere_residual_max_abs_m = ...
                max(abs(reportData.atmosphere_truth_residual_by_tower_m(:)), ...
                [], ...
                'omitnan');

            reportData.truth_troposphere_residual_mean_m = ...
                mean(reportData.atmosphere_truth_troposphere_residual_by_tower_m(:), ...
                'omitnan');

            reportData.truth_troposphere_residual_std_m = ...
                std(reportData.atmosphere_truth_troposphere_residual_by_tower_m(:), ...
                0, ...
                'omitnan');

            reportData.truth_troposphere_residual_rms_m = ...
                sqrt(mean( ...
                reportData.atmosphere_truth_troposphere_residual_by_tower_m(:).^2, ...
                'omitnan'));

            reportData.truth_troposphere_residual_max_abs_m = ...
                max(abs(reportData.atmosphere_truth_troposphere_residual_by_tower_m(:)), ...
                [], ...
                'omitnan');

            reportData.truth_ionosphere_residual_mean_m = ...
                mean(reportData.atmosphere_truth_ionosphere_residual_by_tower_m(:), ...
                'omitnan');

            reportData.truth_ionosphere_residual_std_m = ...
                std(reportData.atmosphere_truth_ionosphere_residual_by_tower_m(:), ...
                0, ...
                'omitnan');

            reportData.truth_ionosphere_residual_rms_m = ...
                sqrt(mean( ...
                reportData.atmosphere_truth_ionosphere_residual_by_tower_m(:).^2, ...
                'omitnan'));

            reportData.truth_ionosphere_residual_max_abs_m = ...
                max(abs(reportData.atmosphere_truth_ionosphere_residual_by_tower_m(:)), ...
                [], ...
                'omitnan');

            reportData.truth_troposphere_residual_config_sigma_m = ...
                double(sim.truthAtmosphere.residualTroposphereSigma_m) * ...
                double(sim.truthAtmosphere.enableTroposphere);

            reportData.truth_ionosphere_residual_config_sigma_m = ...
                double(sim.truthAtmosphere.residualIonosphereSigma_m) * ...
                double(sim.truthAtmosphere.enableIonosphere);

            reportData.truth_total_residual_config_sigma_m = hypot( ...
                reportData.truth_troposphere_residual_config_sigma_m, ...
                reportData.truth_ionosphere_residual_config_sigma_m);
            reportData.atmosphere_model_delay_by_receiver_tower_m = ...
                sim.history.atmosphere_model_delay_by_receiver_tower_m;
            reportData.atmosphere_model_troposphere_by_receiver_tower_m = ...
                sim.history.atmosphere_model_troposphere_by_receiver_tower_m;
            reportData.atmosphere_model_ionosphere_by_receiver_tower_m = ...
                sim.history.atmosphere_model_ionosphere_by_receiver_tower_m;
            reportData.atmosphere_model_ionosphere_ipp_lat_deg_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_ipp_lat_deg_by_receiver_tower;
            reportData.atmosphere_model_ionosphere_ipp_lon_deg_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_ipp_lon_deg_by_receiver_tower;
            reportData.atmosphere_model_ionosphere_vtec_TECU_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_vtec_TECU_by_receiver_tower;
            reportData.atmosphere_model_ionosphere_stec_TECU_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_stec_TECU_by_receiver_tower;
            reportData.atmosphere_model_ionosphere_mapping_factor_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_mapping_factor_by_receiver_tower;

            reportData.atmosphere_model_ionosphere_frequency_Hz_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_frequency_Hz_by_receiver_tower;
            reportData.atmosphere_model_troposphere_pressure_hPa_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_pressure_hPa_by_receiver_tower;

            reportData.atmosphere_model_troposphere_temperature_K_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_temperature_K_by_receiver_tower;

            reportData.atmosphere_model_troposphere_relative_humidity_fraction_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_relative_humidity_fraction_by_receiver_tower;

            reportData.atmosphere_model_troposphere_water_vapor_pressure_hPa_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_water_vapor_pressure_hPa_by_receiver_tower;

            reportData.atmosphere_model_troposphere_zhd_m_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_zhd_m_by_receiver_tower;

            reportData.atmosphere_model_troposphere_zwd_m_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_zwd_m_by_receiver_tower;

            reportData.atmosphere_model_troposphere_mapping_hydrostatic_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_mapping_hydrostatic_by_receiver_tower;

            reportData.atmosphere_model_troposphere_mapping_wet_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_mapping_wet_by_receiver_tower;

            reportData.atmosphere_model_troposphere_slant_hydrostatic_m_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_slant_hydrostatic_m_by_receiver_tower;

            reportData.atmosphere_model_troposphere_slant_wet_m_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_slant_wet_m_by_receiver_tower;
            reportData.atmosphere_residual_by_receiver_tower_m = ...
                sim.history.atmosphere.residual.total_m;
            reportData.atmosphere_troposphere_residual_by_receiver_tower_m = ...
                sim.history.atmosphere.residual.troposphere_m;

            reportData.atmosphere_ionosphere_residual_by_receiver_tower_m = ...
                sim.history.atmosphere.residual.ionosphere_m;
            reportData.mean_truth_atmosphere_delay_m = mean( ...
                sim.history.atmosphere_truth_total_by_receiver_tower_m(:), ...
                'omitnan');

            reportData.mean_model_atmosphere_delay_m = mean( ...
                sim.history.atmosphere_model_delay_by_receiver_tower_m(:), ...
                'omitnan');

            reportData.mean_atmosphere_model_residual_m = mean( ...
                reportData.atmosphere_residual_by_receiver_tower_m(:), ...
                'omitnan');

            reportData.model_atmosphere_residual_sigma_m = ...
                sim.measurementModel.modelAtmosphere.residualCodeSigma_m();

            reportData.truth_atmosphere_residual_sigma_m = ...
                sim.measurementModel.truthAtmosphere.residualCodeSigma_m();

            reportData.mean_deterministic_atmosphere_model_residual_m = ...
                mean(sim.history.atmosphere.residual.deterministic_total_m(:), ...
                'omitnan');

            reportData.model_atmosphere_residual_variance_m2 = ...
                mean(sim.history.atmosphere.covariance.totalVariance_m2(:), ...
                'omitnan');

            reportData.model_atmosphere_covariance_structure = ...
                string(sim.history.atmosphere.covariance.correlation_model);
            reportData.atmosphere_summary_table = ...
                ReportDataBuilder.buildAtmosphereSummaryTable(sim, reportData);
            reportData.stochastic_truth_residual_summary_table = ...
                ReportDataBuilder.buildStochasticTruthResidualSummaryTable( ...
                reportData);
            reportData.ionosphere_map_summary_table = ...
                ReportDataBuilder.buildIonosphereMapSummaryTable(sim, reportData);
            reportData.troposphere_profile_summary_table = ...
                ReportDataBuilder.buildTroposphereProfileSummaryTable(sim, reportData);
            reportData.los_unit_eci_by_receiver_tower = ...
                sim.history.los_unit_eci_by_receiver_tower;
            reportData.pseudorange_error_by_receiver_tower_m = ...
                sim.history.pseudorange_by_receiver_tower_m - ...
                sim.history.true_range_by_receiver_tower_m;

            reportData.receiver_offset_body_by_receiver_m = sim.receiverOffsetsBody_m;
            reportData.covariance_condition_number = sim.history.covariance_condition_number;
            reportData.innovation_condition_number = sim.history.innovation_condition_number;

            reportData.visible_tower_count = sim.history.visible_tower_count;
            reportData.used_tower_count = sim.history.visible_tower_count;
            reportData.measurementNoiseEnabled = sim.measurementModel.measurementNoiseEnabled();
            reportData.numerical_measurement_sigma_floor_m = ...
                sim.measurementModel.effectiveNumericalMeasurementSigma_m();
            reportData.enableElevationMask = sim.measurementModel.elevationMaskEnabled();
            reportData.elevationMask_deg = sim.measurementModel.elevationMaskDeg();

            if GroundTimingNetwork.towerClockEkfEnabled(sim.cfg)
                reportData.clockGaugeMode = "towerClockEKF_meanGroundClockGauge";
                reportData.referenceTowerName = "Mean ground-network clock";
                reportData.clock_estimation_mode = 'spacecraftReceiverClockPlusTowerClockEKF';
            else
                if GroundTimingNetwork.groundClockCorrectionEnabled(sim.cfg)
                    reportData.clockGaugeMode = "externalTowerCorrections";
                    reportData.referenceTowerName = "External ground timing product";
                else
                    reportData.clockGaugeMode = "groundClockResidualsGeneratedButNotEstimated";
                    reportData.referenceTowerName = "";
                end

                reportData.clock_estimation_mode = 'spacecraftReceiverClockOnly';
            end

            reportData.ekf_clock_state_units = 'metres and metres per second';
            reportData.receiver_architecture_note = sprintf( ...
                'N=%d onboard receiver phase centres share one receiver oscillator. Lever arms are Body-frame vectors rotated by q_BI into ECI.', ...
                sim.numReceivers);

            if GroundTimingNetwork.towerClockEkfEnabled(sim.cfg)
                reportData.signal_model_note = [ ...
                    'Truth code pseudorange: P = rho(r_sc_I + C_BI l_a_B, r_g_I) + b_rx_true - b_g_true + d_truth + noise. ' ...
                    'Estimator prediction: P_hat = rho(rhat_sc_I + Chat_BI l_a_B, r_g_I) + bhat_rx - bhat_g + d_model. ' ...
                    'Tower clocks are EKF states and the mean ground-network clock defines the time gauge.'];
            else
                reportData.signal_model_note = [ ...
                    'Truth code pseudorange: P = rho(r_sc_I + C_BI l_a_B, r_g_I) + b_rx_true - b_g_res_true + d_truth + noise. ' ...
                    'Estimator prediction: P_hat = rho(rhat_sc_I + Chat_BI l_a_B, r_g_I) + bhat_rx + d_model. ' ...
                    'In spacecraftReceiverClockOnly mode, b_g_res is not an EKF state and d_model is supplied by the configured estimator atmosphere model.'];
            end

            reportData.attitude_observability_note = ...
                ['Attitude remains in the EKF for every receiver count. Its pseudorange sensitivity is ' ...
                 '-g^T C_BI skew(l_a_B), where g = u + grad_r(d_model); zero lever arms produce zero attitude sensitivity naturally.'];
            reportData.attitude_filter_note = ...
                'MEKF-style attitude update uses a body-frame small-angle error injected multiplicatively into q_BI.';
            reportData.propagation_frame_note = sprintf( ...
                ['Range geometry frame: %s. Current geometry uses ECI ', ...
                 'transmitter and receiver positions evaluated at the receiver epoch; ', ...
                 'inertial iterative light-time is guarded but not implemented.'], ...
                char(sim.measurementModel.propagationFrame));
            reportData.relativity_note = ...
                ['Relativistic path delay and relativistic clock correction are explicit ', ...
                 'zero-valued diagnostics when disabled. Enabling either flag currently ', ...
                 'raises an error until a physical path/clock implementation is added.'];

            reportData.measurement_model_equation = [ ...
                "\begin{aligned}"; ...
                "P_{g,a}^{truth}"; ...
                "&= \left\| \mathbf{r}_{sc,I} + \mathbf{C}_{BI}\mathbf{l}_{a,B} - \mathbf{r}_{g,I} \right\|"; ...
                "&= + b_{rx}^{true} - b_{g,res}^{true} + d_{truth} + \nu \\"; ...
                "\hat{P}_{g,a}"; ...
                "&= \left\| \hat{\mathbf{r}}_{sc,I} + \hat{\mathbf{C}}_{BI}\mathbf{l}_{a,B} - \mathbf{r}_{g,I} \right\|"; ...
                "&= + \hat{b}_{rx} + d_{model}"; ...
                "\end{aligned}" ...
                ];

            reportData.observation_matrix_equation = [...
                "\begin{aligned}"; ...
                "\mathbf{g} = \mathbf{u} + \nabla_{\mathbf{r}_{rx,I}} d_{model}, \qquad H_{g,a}";...
                " &= \left[ \mathbf{g}^{T} \quad \mathbf{0}_{1\times3} \quad \mathbf{g}^{T}(-\mathbf{C}_{BI}" + ...
                " \mathbf{l}_{a,B}]_{\times}) \quad \mathbf{0}_{1\times3} \quad 1 \quad 0 \right]";...
                "\end{aligned}" ...
                ];
            prefitByTower = squeeze(mean(sim.history.prefit_residual_by_receiver_tower_m, 1));
            postfitByTower = squeeze(mean(sim.history.postfit_residual_by_receiver_tower_m, 1));
            reportData.prefit_residual_by_tower_m = prefitByTower;
            reportData.postfit_residual_by_tower_m = postfitByTower;

            nRows = sim.numReceivers * sim.numTowers;
            receiverR2 = sim.cfg.measurement.pseudorangeSigma_m^2 * ...
                double(sim.measurementModel.measurementNoiseEnabled());
            groundR2 = GroundTimingNetwork.residualVariance_m2(sim.cfg, sim.c);

            if GroundTimingNetwork.towerClockEkfEnabled(sim.cfg)
                appliedGroundR2 = 0.0;
            else
                appliedGroundR2 = groundR2;
            end

            atmosphereR2 = sim.measurementModel.atmosphereResidualVariance_m2();

            actualR2 = sim.measurementModel.measurementVariance( ...
                GroundTimingNetwork.towerClockEkfEnabled(sim.cfg), ...
                GroundTimingNetwork.residualVariance_m2(sim.cfg, sim.c));

            reportData.R_receiver_m2 = ones(nRows, sim.numSteps) * receiverR2;
            reportData.R_tower_clock_m2 = ones(nRows, sim.numSteps) * appliedGroundR2;
            reportData.R_atmosphere_m2 = ones(nRows, sim.numSteps) * atmosphereR2;
            reportData.R_hardware_m2 = zeros(nRows, sim.numSteps);
            reportData.R_multipath_m2 = zeros(nRows, sim.numSteps);
            reportData.R_numerical_regularization_m2 = ...
                ones(nRows, sim.numSteps) * ...
                max(actualR2 - receiverR2 - appliedGroundR2 - atmosphereR2, 0.0);

            reportData.R_total_m2 = reportData.R_receiver_m2 + ...
                reportData.R_tower_clock_m2 + ...
                reportData.R_atmosphere_m2 + ...
                reportData.R_numerical_regularization_m2;
            reportData.innovation_covariance_summary_table = ...
                ReportDataBuilder.buildInnovationCovarianceSummaryTable(reportData);
            obs = ObservabilityAnalyzer.analyzeNormalMatrix( ...
                sim.observabilityNormalMatrix, reportData.state_names);
            reportData.final_observability_rank = obs.rank;
            reportData.weak_observability_state_names = obs.weakStateNames;
            reportData.observability_note = sprintf( ...
                'Column-normalized accumulated pseudorange observability rank is %d of %d states. Weak states: %s.', ...
                obs.rank, sim.stateDim, strjoin(string(obs.weakStateNames), ', '));

            selectedOsc = sim.simConfig.clockLibrary.(char(sim.assetConfig.clock.clockType));
            selectedClock = Clock(selectedOsc.h0, selectedOsc.hm1, selectedOsc.hm2, sim.dt);
            nAllan = floor(sim.simConfig.validation.allanValidationSamples);

            reportData.tau_profile_s = ReportDataBuilder.validTauForSamples( ...
                sim.simConfig.validation.tauProfile_s, sim.dt, nAllan);

            clockValidationList = [{selectedClock}, GroundNode.clocks(sim.towers)];
            clockNames = ["SpaceAsset RX", sim.towerNames];
            nClock = numel(clockValidationList);
            clockAdev1s = NaN(1, nClock);

            for idxClock = 1:nClock
                [tauThis_s, adevThis, sigmaThis, edfThis] = ...
                    ReportDataBuilder.runClockAllanValidation( ...
                    clockValidationList{idxClock}, ...
                    sim.simConfig.validation.tauSimulation_s, ...
                    sim.dt, nAllan, sim.validationClockStream);

                if idxClock == 1
                    reportData.tau_sim_s = tauThis_s;
                    reportData.sim_adev = adevThis;
                    reportData.sim_adev_sigma = sigmaThis;
                    reportData.sim_adev_edf = edfThis;
                    simAdevByClock = NaN(nClock, numel(tauThis_s));
                end

                simAdevByClock(idxClock, :) = adevThis;
                clockAdev1s(idxClock) = ...
                    clockValidationList{idxClock}.theoreticalAllanDeviation(1.0);
            end

            reportData.selected_allan_deviation_1s = ...
                selectedClock.theoreticalAllanDeviation(1.0);
            reportData.clock_allan_names = clockNames;
            reportData.clock_allan_deviation_1s = clockAdev1s;
            reportData.sim_adev_by_clock = simAdevByClock;
            reportData.seedConfig = sim.seedConfig;
            reportData.source_references = {sprintf('Generated by %s.', sim.entryPointName)};
        end
    end

    methods (Static, Access = private)
        
        function tableOut = buildInnovationCovarianceSummaryTable(reportData)
            Quantity = [ ...
                "Mean pre-fit innovation RMS [m]"; ...
                "Mean post-fit innovation RMS [m]"; ...
                "Mean innovation covariance sigma [m]"; ...
                "Minimum innovation covariance sigma [m]"; ...
                "Maximum innovation covariance sigma [m]"; ...
                "Mean NIS [-]"; ...
                "Mean NIS per degree of freedom [-]"; ...
                "Mean normalised innovation RMS [-]"; ...
                "Mean receiver-noise R contribution sigma [m]"; ...
                "Mean tower-clock R contribution sigma [m]"; ...
                "Mean atmosphere R contribution sigma [m]"; ...
                "Mean numerical-regularisation R contribution sigma [m]"; ...
                "Mean total diagonal R contribution sigma [m]" ...
                ];

            Value = [ ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.innovation_rms_m(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.postfit_innovation_rms_m(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.innovation_covariance_mean_sigma_m(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.innovation_covariance_min_sigma_m(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.innovation_covariance_max_sigma_m(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.nis_history(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.nis_per_degree_of_freedom(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.normalized_innovation_rms(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(sqrt(mean( ...
                    reportData.R_receiver_m2(:), ...
                    'omitnan'))); ...
                ReportDataBuilder.scalarText(sqrt(mean( ...
                    reportData.R_tower_clock_m2(:), ...
                    'omitnan'))); ...
                ReportDataBuilder.scalarText(sqrt(mean( ...
                    reportData.R_atmosphere_m2(:), ...
                    'omitnan'))); ...
                ReportDataBuilder.scalarText(sqrt(mean( ...
                    reportData.R_numerical_regularization_m2(:), ...
                    'omitnan'))); ...
                ReportDataBuilder.scalarText(sqrt(mean( ...
                    reportData.R_total_m2(:), ...
                    'omitnan'))) ...
                ];

            tableOut = table(Quantity, Value);
        end
        
        function tableOut = buildStochasticTruthResidualSummaryTable(reportData)
            Quantity = [ ...
                "Configured truth troposphere residual sigma [m]"; ...
                "Configured truth ionosphere residual sigma [m]"; ...
                "Configured truth total residual sigma [m]"; ...
                "Sample mean total truth residual [m]"; ...
                "Sample std total truth residual [m]"; ...
                "Sample RMS total truth residual [m]"; ...
                "Sample max abs total truth residual [m]"; ...
                "Sample mean troposphere truth residual [m]"; ...
                "Sample std troposphere truth residual [m]"; ...
                "Sample RMS troposphere truth residual [m]"; ...
                "Sample max abs troposphere truth residual [m]"; ...
                "Sample mean ionosphere truth residual [m]"; ...
                "Sample std ionosphere truth residual [m]"; ...
                "Sample RMS ionosphere truth residual [m]"; ...
                "Sample max abs ionosphere truth residual [m]" ...
                ];

            Value = [ ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_troposphere_residual_config_sigma_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_ionosphere_residual_config_sigma_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_total_residual_config_sigma_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_atmosphere_residual_mean_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_atmosphere_residual_std_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_atmosphere_residual_rms_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_atmosphere_residual_max_abs_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_troposphere_residual_mean_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_troposphere_residual_std_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_troposphere_residual_rms_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_troposphere_residual_max_abs_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_ionosphere_residual_mean_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_ionosphere_residual_std_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_ionosphere_residual_rms_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.truth_ionosphere_residual_max_abs_m) ...
                ];

            tableOut = table(Quantity, Value);
        end
        
        function tableOut = buildAtmosphereSummaryTable(sim, reportData)
            Quantity = [ ...
                "Truth troposphere enabled"; ...
                "Truth troposphere model"; ...
                "Truth ionosphere enabled"; ...
                "Truth ionosphere model"; ...
                "Estimator troposphere enabled"; ...
                "Estimator troposphere model"; ...
                "Estimator ionosphere enabled"; ...
                "Estimator ionosphere model"; ...
                "Truth constant troposphere delay [m]"; ...
                "Truth constant ionosphere delay [m]"; ...
                "Estimator constant troposphere delay [m]"; ...
                "Estimator constant ionosphere delay [m]"; ...
                "Mean truth atmosphere total [m]"; ...
                "Mean estimator atmosphere correction [m]"; ...
                "Mean truth minus model atmosphere [m]"; ...
                "Mean deterministic truth minus model atmosphere [m]"; ...
                "Stochastic truth residual enabled"; ...
                "Truth atmosphere residual sigma [m]"; ...
                "Truth residual troposphere sigma [m]"; ...
                "Truth residual ionosphere sigma [m]"; ...
                "Estimator atmosphere residual sigma [m]"; ...
                "Estimator residual troposphere sigma [m]"; ...
                "Estimator residual ionosphere sigma [m]"; ...
                "Estimator residual variance in R [m^2]"; ...
                "R covariance structure" ...
                ];

            Value = [ ...
                string(sim.truthAtmosphere.enableTroposphere); ...
                string(sim.truthAtmosphere.troposphereModel); ...
                string(sim.truthAtmosphere.enableIonosphere); ...
                string(sim.truthAtmosphere.ionosphereModel); ...
                string(sim.modelAtmosphere.enableTroposphere); ...
                string(sim.modelAtmosphere.troposphereModel); ...
                string(sim.modelAtmosphere.enableIonosphere); ...
                string(sim.modelAtmosphere.ionosphereModel); ...
                ReportDataBuilder.scalarText( ...
                    sim.truthAtmosphere.constantTroposphereDelay_m); ...
                ReportDataBuilder.scalarText( ...
                    sim.truthAtmosphere.constantIonosphereDelay_m); ...
                ReportDataBuilder.scalarText( ...
                    sim.modelAtmosphere.constantTroposphereDelay_m); ...
                ReportDataBuilder.scalarText( ...
                    sim.modelAtmosphere.constantIonosphereDelay_m); ...
                ReportDataBuilder.scalarText(reportData.mean_truth_atmosphere_delay_m); ...
                ReportDataBuilder.scalarText(reportData.mean_model_atmosphere_delay_m); ...
                ReportDataBuilder.scalarText(reportData.mean_atmosphere_model_residual_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.mean_deterministic_atmosphere_model_residual_m); ...
                string( ...
                    (sim.truthAtmosphere.enableTroposphere && ...
                    sim.truthAtmosphere.residualTroposphereSigma_m > 0.0) || ...
                    (sim.truthAtmosphere.enableIonosphere && ...
                    sim.truthAtmosphere.residualIonosphereSigma_m > 0.0)); ...
                ReportDataBuilder.scalarText(reportData.truth_atmosphere_residual_sigma_m); ...
                ReportDataBuilder.scalarText( ...
                    sim.truthAtmosphere.residualTroposphereSigma_m); ...
                ReportDataBuilder.scalarText( ...
                    sim.truthAtmosphere.residualIonosphereSigma_m); ...
                ReportDataBuilder.scalarText(reportData.model_atmosphere_residual_sigma_m); ...
                ReportDataBuilder.scalarText( ...
                    sim.modelAtmosphere.residualTroposphereSigma_m); ...
                ReportDataBuilder.scalarText( ...
                    sim.modelAtmosphere.residualIonosphereSigma_m); ...
                ReportDataBuilder.scalarText( ...
                    reportData.model_atmosphere_residual_variance_m2); ...
                reportData.model_atmosphere_covariance_structure ...
                ];

            tableOut = table(Quantity, Value);
        end

        function tableOut = buildIonosphereMapSummaryTable(sim, reportData)
            Quantity = [ ...
                "Truth ionosphere provider"; ...
                "Estimator ionosphere provider"; ...
                "Mean truth IPP latitude [deg]"; ...
                "Mean truth IPP longitude [deg]"; ...
                "Mean truth VTEC [TECU]"; ...
                "Mean truth STEC [TECU]"; ...
                "Mean truth mapping factor"; ...
                "Mean truth frequency [Hz]"; ...
                "Mean estimator IPP latitude [deg]"; ...
                "Mean estimator IPP longitude [deg]"; ...
                "Mean estimator VTEC [TECU]"; ...
                "Mean estimator STEC [TECU]"; ...
                "Mean estimator mapping factor"; ...
                "Mean estimator frequency [Hz]" ...
                ];

            Value = [ ...
                string(sim.truthAtmosphere.ionosphereProviderType); ...
                string(sim.modelAtmosphere.ionosphereProviderType); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_ionosphere_ipp_lat_deg_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_ionosphere_ipp_lon_deg_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_ionosphere_vtec_TECU_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_ionosphere_stec_TECU_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_ionosphere_mapping_factor_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_ionosphere_frequency_Hz_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_ionosphere_ipp_lat_deg_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_ionosphere_ipp_lon_deg_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_ionosphere_vtec_TECU_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_ionosphere_stec_TECU_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_ionosphere_mapping_factor_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_ionosphere_frequency_Hz_by_receiver_tower(:), ...
                    'omitnan')) ...
                ];

            tableOut = table(Quantity, Value);
        end
        
        function tableOut = buildTroposphereProfileSummaryTable(sim, reportData)
            Quantity = [ ...
                "Truth troposphere provider"; ...
                "Estimator troposphere provider"; ...
                "Truth mapping function"; ...
                "Estimator mapping function"; ...
                "Mean truth pressure [hPa]"; ...
                "Mean truth temperature [K]"; ...
                "Mean truth relative humidity [-]"; ...
                "Mean truth water vapour pressure [hPa]"; ...
                "Mean truth ZHD [m]"; ...
                "Mean truth ZWD [m]"; ...
                "Mean truth slant hydrostatic [m]"; ...
                "Mean truth slant wet [m]"; ...
                "Mean estimator pressure [hPa]"; ...
                "Mean estimator temperature [K]"; ...
                "Mean estimator relative humidity [-]"; ...
                "Mean estimator water vapour pressure [hPa]"; ...
                "Mean estimator ZHD [m]"; ...
                "Mean estimator ZWD [m]"; ...
                "Mean estimator slant hydrostatic [m]"; ...
                "Mean estimator slant wet [m]" ...
                ];

            Value = [ ...
                string(sim.truthAtmosphere.troposphereProviderType); ...
                string(sim.modelAtmosphere.troposphereProviderType); ...
                string(sim.truthAtmosphere.troposphereMappingFunction); ...
                string(sim.modelAtmosphere.troposphereMappingFunction); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_troposphere_pressure_hPa_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_troposphere_temperature_K_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_troposphere_relative_humidity_fraction_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_troposphere_water_vapor_pressure_hPa_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_troposphere_zhd_m_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_troposphere_zwd_m_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_troposphere_slant_hydrostatic_m_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_truth_troposphere_slant_wet_m_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_troposphere_pressure_hPa_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_troposphere_temperature_K_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_troposphere_relative_humidity_fraction_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_troposphere_water_vapor_pressure_hPa_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_troposphere_zhd_m_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_troposphere_zwd_m_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_troposphere_slant_hydrostatic_m_by_receiver_tower(:), ...
                    'omitnan')); ...
                ReportDataBuilder.scalarText(mean( ...
                    reportData.atmosphere_model_troposphere_slant_wet_m_by_receiver_tower(:), ...
                    'omitnan')) ...
                ];

            tableOut = table(Quantity, Value);
        end
        
        function textValue = scalarText(value)
            value = double(value);

            if ~isfinite(value)
                textValue = "not available";
            else
                textValue = string(sprintf("%.6g", value));
            end
        end

        function towers = reportTowers(sim)
            towers = repmat( ...
                struct('name', '', 'lat_deg', 0, 'lon_deg', 0, 'alt_m', 0, 'enabled', true), ...
                1, sim.numTowers);

            for k = 1:sim.numTowers
                towers(k).name = char(sim.towerNames(k));
                towers(k).lat_deg = sim.activeTowerConfig(k).lat_deg;
                towers(k).lon_deg = sim.activeTowerConfig(k).lon_deg;
                towers(k).alt_m = sim.activeTowerConfig(k).alt_m;
                towers(k).enabled = true;
            end
        end

        function tauOut = validTauForSamples(tauIn, dt, n)
            m = unique(round(tauIn(:).' ./ dt));
            m = m(isfinite(m) & m >= 1 & 2 .* m < n);
            tauOut = m .* dt;

            if isempty(tauOut)
                tauOut = dt;
            end
        end

        function [tauValid_s, adev, adevSigma, edf] = runClockAllanValidation( ...
                clockTemplate, tauRequested_s, dt, nSamples, validationClockStream)

            nSamples = max(3, floor(double(nSamples)));
            tauValid_s = ReportDataBuilder.validTauForSamples(tauRequested_s, dt, nSamples);

            validationClock = Clock( ...
                clockTemplate.h_0, ...
                clockTemplate.h_minus_1, ...
                clockTemplate.h_minus_2, ...
                dt);

            validationClock.randomStream = validationClockStream;

            phase_s = NaN(nSamples, 1);
            phase_s(1) = validationClock.total_bias_sec;

            for k = 2:nSamples
                validationClock.update(dt);
                phase_s(k) = validationClock.total_bias_sec;
            end

            adev = NaN(1, numel(tauValid_s));
            adevSigma = NaN(1, numel(tauValid_s));
            edf = NaN(1, numel(tauValid_s));

            for k = 1:numel(tauValid_s)
                [adev(k), ~, edf(k), adevSigma(k)] = ...
                    Clock.computeOverlappingAllanDeviation(phase_s, tauValid_s(k), dt);
            end
        end

        function value = getFieldOrDefault(s, fieldName, defaultValue)
            if isstruct(s) && isfield(s, fieldName)
                value = s.(fieldName);
            else
                value = defaultValue;
            end
        end

        function value = getScalarField(s, fieldName, defaultValue)
            if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
                value = double(s.(fieldName));
            else
                value = double(defaultValue);
            end
        end
    end
end
