classdef HistoryRecorder
    %HISTORYRECORDER Allocates and records Reverse-GNSS simulation history.
    %
    % This class owns history struct shape and per-epoch logging. It does not
    % run simulation dynamics, generate measurements, update the EKF, or create
    % reports.

    methods (Static)
        function history = initialize(sim)
            history = struct();

            history.x = NaN(sim.stateDim, sim.numSteps);
            history.truth = NaN(sim.stateDim, sim.numSteps);
            history.covariance_diag = NaN(sim.stateDim, sim.numSteps);

            history.innovation_rms_m = NaN(1, sim.numSteps);
            history.postfit_innovation_rms_m = NaN(1, sim.numSteps);
            history.nis_history = NaN(1, sim.numSteps);
            history.covariance_condition_number = NaN(1, sim.numSteps);
            history.innovation_condition_number = NaN(1, sim.numSteps);
            history.innovation_covariance_mean_variance_m2 = ...
                NaN(1, sim.numSteps);

            history.innovation_covariance_min_variance_m2 = ...
                NaN(1, sim.numSteps);

            history.innovation_covariance_max_variance_m2 = ...
                NaN(1, sim.numSteps);

            history.nis_per_degree_of_freedom = ...
                NaN(1, sim.numSteps);

            history.normalized_innovation_rms = ...
                NaN(1, sim.numSteps);

            history.H_row_count_history = NaN(1, sim.numSteps);
            history.H_column_count_history = NaN(1, sim.numSteps);
            history.H_rank_to_state_dim_history = NaN(1, sim.numSteps);
            history.H_state_deficiency_history = NaN(1, sim.numSteps);

            history.H_pos_rank_history = NaN(1, sim.numSteps);
            history.H_att_rank_history = NaN(1, sim.numSteps);
            history.H_pos_att_clock_rank_history = NaN(1, sim.numSteps);
            history.H_pos_column_norm_history = NaN(3, sim.numSteps);
            history.H_att_column_norm_history = NaN(3, sim.numSteps);
            history.H_rx_clock_bias_column_norm_history = NaN(1, sim.numSteps);

            history.measurement_count = zeros(1, sim.numSteps);
            history.pseudorange_measurement_count = zeros(1, sim.numSteps);
            history.visible_tower_count = zeros(1, sim.numSteps);

            history.sat_pos_history_m = NaN(3, sim.numSteps);
            history.receiver_eci_by_receiver = NaN(3, sim.numReceivers, sim.numSteps);
            history.tower_eci_by_tower = NaN(3, sim.numTowers, sim.numSteps);

            history.ground_clock_true_m = NaN(sim.numTowers, sim.numSteps);
            history.ground_clock_correction_m = NaN(sim.numTowers, sim.numSteps);
            history.ground_clock_residual_m = NaN(sim.numTowers, sim.numSteps);
            history.clock_phase_history_s = NaN(1, sim.numSteps);

            history.prefit_residual_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.postfit_residual_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.pseudorange_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.true_range_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.los_unit_eci_by_receiver_tower = ...
                NaN(3, sim.numReceivers, sim.numTowers, sim.numSteps);
            history.visibility_mask_by_receiver_tower = ...
                false(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.elevation_deg_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            
            history.atmosphere_truth_delay_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.atmosphere_truth_troposphere_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_ionosphere_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_residual_by_tower_m = ...
                NaN(sim.numTowers, sim.numSteps);
            history.atmosphere_truth_troposphere_residual_by_tower_m = ...
                NaN(sim.numTowers, sim.numSteps);

            history.atmosphere_truth_ionosphere_residual_by_tower_m = ...
                NaN(sim.numTowers, sim.numSteps);

            history.atmosphere_truth_ionosphere_ipp_lat_deg_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_ionosphere_ipp_lon_deg_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_ionosphere_vtec_TECU_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_ionosphere_stec_TECU_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_ionosphere_mapping_factor_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_ionosphere_frequency_Hz_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.atmosphere_truth_troposphere_pressure_hPa_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_troposphere_temperature_K_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_troposphere_relative_humidity_fraction_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_troposphere_water_vapor_pressure_hPa_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_troposphere_zhd_m_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_troposphere_zwd_m_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_troposphere_mapping_hydrostatic_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_troposphere_mapping_wet_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_troposphere_slant_hydrostatic_m_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_troposphere_slant_wet_m_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.atmosphere_truth_total_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.atmosphere_truth_troposphere_total_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_truth_ionosphere_total_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.atmosphere_model_delay_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.atmosphere_model_troposphere_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_ionosphere_by_receiver_tower_m = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.atmosphere_model_ionosphere_ipp_lat_deg_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_ionosphere_ipp_lon_deg_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_ionosphere_vtec_TECU_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_ionosphere_stec_TECU_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_ionosphere_mapping_factor_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_ionosphere_frequency_Hz_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);
            history.atmosphere_model_troposphere_pressure_hPa_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_troposphere_temperature_K_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_troposphere_relative_humidity_fraction_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_troposphere_water_vapor_pressure_hPa_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_troposphere_zhd_m_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_troposphere_zwd_m_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_troposphere_mapping_hydrostatic_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_troposphere_mapping_wet_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_troposphere_slant_hydrostatic_m_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere_model_troposphere_slant_wet_m_by_receiver_tower = ...
                NaN(sim.numReceivers, sim.numTowers, sim.numSteps);

            history.atmosphere = ...
                HistoryRecorder.initializeAtmosphereBudgetHistory(sim);

            history.propagation = ...
                HistoryRecorder.initializePropagationHistory(sim);

            history.non_atmospheric = ...
                HistoryRecorder.initializeNonAtmosphericBudgetHistory(sim);
        end

        function [history, observabilityNormalMatrix] = record( ...
                sim, history, observabilityNormalMatrix, ...
                estimateVector, truthVector, covarianceDiag, covarianceMatrix, ...
                k, y, innovation, postfit, S, H, nisValue, ...
                trueRangeRt, losRt, receiverEci, towersEci, ...
                groundResidual_m, groundTrue_m, groundCorrection_m, ...
                visibilityMask, elevationRt_deg, ...
                atmosphereTruthDelayRt_m, ...
                atmosphereTruthTroposphereRt_m, ...
                atmosphereTruthIonosphereRt_m, ...
                atmosphereTruthResidualByTower_m, ...
                atmosphereTruthTroposphereResidualByTower_m, ...
                atmosphereTruthIonosphereResidualByTower_m, ...
                atmosphereTruthTroposphereDiagnostics, ...
                atmosphereTruthIonosphereDiagnostics, ...
                atmosphereModelDelayRt_m, ...
                atmosphereModelTroposphereRt_m, ...
                atmosphereModelIonosphereRt_m, ...
                atmosphereModelTroposphereDiagnostics, ...
                atmosphereModelIonosphereDiagnostics)

            history.x(:, k) = estimateVector;
            history.truth(:, k) = truthVector;
            history.covariance_diag(:, k) = covarianceDiag;

            history.innovation_rms_m(k) = HistoryRecorder.computeRms(innovation);
            history.postfit_innovation_rms_m(k) = HistoryRecorder.computeRms(postfit);
            history.nis_history(k) = nisValue;
            history.covariance_condition_number(k) = cond(covarianceMatrix);

            if isempty(S)
                history.innovation_condition_number(k) = NaN;
            else
                history.innovation_condition_number(k) = cond(S);
            end
            if isempty(S)
                innovationCovarianceDiagonal_m2 = [];
            else
                innovationCovarianceDiagonal_m2 = diag(S);
                innovationCovarianceDiagonal_m2 = ...
                    innovationCovarianceDiagonal_m2( ...
                    isfinite(innovationCovarianceDiagonal_m2) & ...
                    innovationCovarianceDiagonal_m2 >= 0.0);
            end

            if isempty(innovationCovarianceDiagonal_m2)
                history.innovation_covariance_mean_variance_m2(k) = NaN;
                history.innovation_covariance_min_variance_m2(k) = NaN;
                history.innovation_covariance_max_variance_m2(k) = NaN;
            else
                history.innovation_covariance_mean_variance_m2(k) = ...
                    mean(innovationCovarianceDiagonal_m2, 'omitnan');

                history.innovation_covariance_min_variance_m2(k) = ...
                    min(innovationCovarianceDiagonal_m2, [], 'omitnan');

                history.innovation_covariance_max_variance_m2(k) = ...
                    max(innovationCovarianceDiagonal_m2, [], 'omitnan');
            end

            innovationDof = size(S, 1);

            if isfinite(nisValue) && innovationDof > 0
                history.nis_per_degree_of_freedom(k) = ...
                    nisValue / innovationDof;

                history.normalized_innovation_rms(k) = ...
                    sqrt(max(history.nis_per_degree_of_freedom(k), 0.0));
            else
                history.nis_per_degree_of_freedom(k) = NaN;
                history.normalized_innovation_rms(k) = NaN;
            end
            if isempty(H)
                hRank = 0;
                hRows = 0;
                hCols = sim.stateDim;
            else
                hRank = rank(H);
                hRows = size(H, 1);
                hCols = size(H, 2);
            end

            history.H_rank_history(k) = hRank;
            history.H_row_count_history(k) = hRows;
            history.H_column_count_history(k) = hCols;
            history.H_rank_to_state_dim_history(k) = hRank / max(hCols, 1);
            history.H_state_deficiency_history(k) = hCols - hRank;

            if isempty(H)
                history.H_pos_rank_history(k) = 0;
                history.H_att_rank_history(k) = 0;
                history.H_pos_att_clock_rank_history(k) = 0;
                history.H_pos_column_norm_history(:, k) = 0;
                history.H_att_column_norm_history(:, k) = 0;
                history.H_rx_clock_bias_column_norm_history(k) = 0;
            else
                Hpos = H(:, sim.idx.pos);
                Hatt = H(:, sim.idx.att);
                Hclk = H(:, sim.idx.rxClockBias);

                history.H_pos_rank_history(k) = rank(Hpos);
                history.H_att_rank_history(k) = rank(Hatt);
                history.H_pos_att_clock_rank_history(k) = rank([Hpos, Hatt, Hclk]);

                history.H_pos_column_norm_history(:, k) = vecnorm(Hpos, 2, 1).';
                history.H_att_column_norm_history(:, k) = vecnorm(Hatt, 2, 1).';
                history.H_rx_clock_bias_column_norm_history(k) = norm(Hclk);
            end

            observabilityNormalMatrix = observabilityNormalMatrix + ...
                (H * sim.transitionFromInitial).' * (H * sim.transitionFromInitial);

            history.measurement_count(k) = size(H, 1);
            history.pseudorange_measurement_count(k) = numel(y);
            history.visible_tower_count(k) = sum(any(visibilityMask, 1));

            history.sat_pos_history_m(:, k) = sim.truthAsset.pos_ECI_m;
            history.receiver_eci_by_receiver(:, :, k) = receiverEci;
            history.tower_eci_by_tower(:, :, k) = towersEci;

            history.ground_clock_true_m(:, k) = groundTrue_m(:);
            history.ground_clock_correction_m(:, k) = groundCorrection_m(:);
            history.ground_clock_residual_m(:, k) = groundResidual_m(:);

            if ~isempty(sim.truthAsset.clock)
                history.clock_phase_history_s(k) = sim.truthAsset.clock.total_bias_sec;
            else
                history.clock_phase_history_s(k) = NaN;
            end

            history.prefit_residual_by_receiver_tower_m(:, :, k) = ...
                sim.measurementModel.vectorToReceiverTowerMatrix(innovation, visibilityMask);

            history.postfit_residual_by_receiver_tower_m(:, :, k) = ...
                sim.measurementModel.vectorToReceiverTowerMatrix(postfit, visibilityMask);

            history.pseudorange_by_receiver_tower_m(:, :, k) = ...
                sim.measurementModel.vectorToReceiverTowerMatrix(y, visibilityMask);

            history.true_range_by_receiver_tower_m(:, :, k) = trueRangeRt;
            history.los_unit_eci_by_receiver_tower(:, :, :, k) = losRt;
            history.visibility_mask_by_receiver_tower(:, :, k) = visibilityMask;
            history.elevation_deg_by_receiver_tower(:, :, k) = elevationRt_deg;
            history.atmosphere_truth_delay_by_receiver_tower_m(:, :, k) = ...
                atmosphereTruthDelayRt_m;
            history.atmosphere_truth_troposphere_by_receiver_tower_m(:, :, k) = ...
                atmosphereTruthTroposphereRt_m;

            history.atmosphere_truth_ionosphere_by_receiver_tower_m(:, :, k) = ...
                atmosphereTruthIonosphereRt_m;
            history.atmosphere_truth_ionosphere_ipp_lat_deg_by_receiver_tower(:, :, k) = ...
                atmosphereTruthIonosphereDiagnostics.ipp_lat_deg;

            history.atmosphere_truth_ionosphere_ipp_lon_deg_by_receiver_tower(:, :, k) = ...
                atmosphereTruthIonosphereDiagnostics.ipp_lon_deg;

            history.atmosphere_truth_ionosphere_vtec_TECU_by_receiver_tower(:, :, k) = ...
                atmosphereTruthIonosphereDiagnostics.vtec_TECU;

            history.atmosphere_truth_ionosphere_stec_TECU_by_receiver_tower(:, :, k) = ...
                atmosphereTruthIonosphereDiagnostics.stec_TECU;

            history.atmosphere_truth_ionosphere_mapping_factor_by_receiver_tower(:, :, k) = ...
                atmosphereTruthIonosphereDiagnostics.mapping_factor;   

            history.atmosphere_truth_ionosphere_frequency_Hz_by_receiver_tower(:, :, k) = ...
                atmosphereTruthIonosphereDiagnostics.frequency_Hz;

            history.atmosphere_truth_troposphere_pressure_hPa_by_receiver_tower(:, :, k) = ...
                atmosphereTruthTroposphereDiagnostics.pressure_hPa;

            history.atmosphere_truth_troposphere_temperature_K_by_receiver_tower(:, :, k) = ...
                atmosphereTruthTroposphereDiagnostics.temperature_K;

            history.atmosphere_truth_troposphere_relative_humidity_fraction_by_receiver_tower(:, :, k) = ...
                atmosphereTruthTroposphereDiagnostics.relative_humidity_fraction;

            history.atmosphere_truth_troposphere_water_vapor_pressure_hPa_by_receiver_tower(:, :, k) = ...
                atmosphereTruthTroposphereDiagnostics.water_vapor_pressure_hPa;

            history.atmosphere_truth_troposphere_zhd_m_by_receiver_tower(:, :, k) = ...
                atmosphereTruthTroposphereDiagnostics.zhd_m;

            history.atmosphere_truth_troposphere_zwd_m_by_receiver_tower(:, :, k) = ...
                atmosphereTruthTroposphereDiagnostics.zwd_m;

            history.atmosphere_truth_troposphere_mapping_hydrostatic_by_receiver_tower(:, :, k) = ...
                atmosphereTruthTroposphereDiagnostics.mapping_hydrostatic;

            history.atmosphere_truth_troposphere_mapping_wet_by_receiver_tower(:, :, k) = ...
                atmosphereTruthTroposphereDiagnostics.mapping_wet;

            history.atmosphere_truth_troposphere_slant_hydrostatic_m_by_receiver_tower(:, :, k) = ...
                atmosphereTruthTroposphereDiagnostics.slant_hydrostatic_m;

            history.atmosphere_truth_troposphere_slant_wet_m_by_receiver_tower(:, :, k) = ...
                atmosphereTruthTroposphereDiagnostics.slant_wet_m;
            history.atmosphere_truth_residual_by_tower_m(:, k) = ...
                atmosphereTruthResidualByTower_m(:);

            history.atmosphere_truth_troposphere_residual_by_tower_m(:, k) = ...
                atmosphereTruthTroposphereResidualByTower_m(:);

            history.atmosphere_truth_ionosphere_residual_by_tower_m(:, k) = ...
                atmosphereTruthIonosphereResidualByTower_m(:);

            history.atmosphere_model_delay_by_receiver_tower_m(:, :, k) = ...
                atmosphereModelDelayRt_m;

            history.atmosphere_model_troposphere_by_receiver_tower_m(:, :, k) = ...
                atmosphereModelTroposphereRt_m;

            history.atmosphere_model_ionosphere_by_receiver_tower_m(:, :, k) = ...
                atmosphereModelIonosphereRt_m;
            history.atmosphere_model_ionosphere_ipp_lat_deg_by_receiver_tower(:, :, k) = ...
                atmosphereModelIonosphereDiagnostics.ipp_lat_deg;

            history.atmosphere_model_ionosphere_ipp_lon_deg_by_receiver_tower(:, :, k) = ...
                atmosphereModelIonosphereDiagnostics.ipp_lon_deg;

            history.atmosphere_model_ionosphere_vtec_TECU_by_receiver_tower(:, :, k) = ...
                atmosphereModelIonosphereDiagnostics.vtec_TECU;

            history.atmosphere_model_ionosphere_stec_TECU_by_receiver_tower(:, :, k) = ...
                atmosphereModelIonosphereDiagnostics.stec_TECU;

            history.atmosphere_model_ionosphere_mapping_factor_by_receiver_tower(:, :, k) = ...
                atmosphereModelIonosphereDiagnostics.mapping_factor;

            history.atmosphere_model_ionosphere_frequency_Hz_by_receiver_tower(:, :, k) = ...
                atmosphereModelIonosphereDiagnostics.frequency_Hz;

            history.atmosphere_model_troposphere_pressure_hPa_by_receiver_tower(:, :, k) = ...
                atmosphereModelTroposphereDiagnostics.pressure_hPa;

            history.atmosphere_model_troposphere_temperature_K_by_receiver_tower(:, :, k) = ...
                atmosphereModelTroposphereDiagnostics.temperature_K;

            history.atmosphere_model_troposphere_relative_humidity_fraction_by_receiver_tower(:, :, k) = ...
                atmosphereModelTroposphereDiagnostics.relative_humidity_fraction;

            history.atmosphere_model_troposphere_water_vapor_pressure_hPa_by_receiver_tower(:, :, k) = ...
                atmosphereModelTroposphereDiagnostics.water_vapor_pressure_hPa;

            history.atmosphere_model_troposphere_zhd_m_by_receiver_tower(:, :, k) = ...
                atmosphereModelTroposphereDiagnostics.zhd_m;

            history.atmosphere_model_troposphere_zwd_m_by_receiver_tower(:, :, k) = ...
                atmosphereModelTroposphereDiagnostics.zwd_m;

            history.atmosphere_model_troposphere_mapping_hydrostatic_by_receiver_tower(:, :, k) = ...
                atmosphereModelTroposphereDiagnostics.mapping_hydrostatic;

            history.atmosphere_model_troposphere_mapping_wet_by_receiver_tower(:, :, k) = ...
                atmosphereModelTroposphereDiagnostics.mapping_wet;

            history.atmosphere_model_troposphere_slant_hydrostatic_m_by_receiver_tower(:, :, k) = ...
                atmosphereModelTroposphereDiagnostics.slant_hydrostatic_m;

            history.atmosphere_model_troposphere_slant_wet_m_by_receiver_tower(:, :, k) = ...
                atmosphereModelTroposphereDiagnostics.slant_wet_m;

            truthResidualByReceiverTower_m = repmat( ...
                atmosphereTruthResidualByTower_m(:).', ...
                sim.numReceivers, ...
                1);

            truthTroposphereResidualByReceiverTower_m = repmat( ...
                atmosphereTruthTroposphereResidualByTower_m(:).', ...
                sim.numReceivers, ...
                1);

            truthIonosphereResidualByReceiverTower_m = repmat( ...
                atmosphereTruthIonosphereResidualByTower_m(:).', ...
                sim.numReceivers, ...
                1);

            truthTotal_m = ...
                atmosphereTruthDelayRt_m + truthResidualByReceiverTower_m;

            truthTroposphereTotal_m = ...
                atmosphereTruthTroposphereRt_m + ...
                truthTroposphereResidualByReceiverTower_m;

            truthIonosphereTotal_m = ...
                atmosphereTruthIonosphereRt_m + ...
                truthIonosphereResidualByReceiverTower_m;

            history.atmosphere_truth_total_by_receiver_tower_m(:, :, k) = ...
                truthTotal_m;

            history.atmosphere_truth_troposphere_total_by_receiver_tower_m(:, :, k) = ...
                truthTroposphereTotal_m;

            history.atmosphere_truth_ionosphere_total_by_receiver_tower_m(:, :, k) = ...
                truthIonosphereTotal_m;

            history = HistoryRecorder.recordPropagationDiagnostics( ...
                sim, history, k, visibilityMask);

            history = HistoryRecorder.recordAtmosphereBudget( ...
                sim, ...
                history, ...
                k, ...
                atmosphereTruthDelayRt_m, ...
                atmosphereTruthTroposphereRt_m, ...
                atmosphereTruthIonosphereRt_m, ...
                truthResidualByReceiverTower_m, ...
                truthTroposphereResidualByReceiverTower_m, ...
                truthIonosphereResidualByReceiverTower_m, ...
                truthTotal_m, ...
                truthTroposphereTotal_m, ...
                truthIonosphereTotal_m, ...
                atmosphereModelDelayRt_m, ...
                atmosphereModelTroposphereRt_m, ...
                atmosphereModelIonosphereRt_m);
            history = HistoryRecorder.recordNonAtmosphericBudget( ...
                sim, ...
                history, ...
                k, ...
                visibilityMask, ...
                towersEci, ...
                receiverEci);
        end
    end

    methods (Static, Access = private)
        function atmosphere = initializeAtmosphereBudgetHistory(sim)
            receiverTowerSize = ...
                [sim.numReceivers, sim.numTowers, sim.numSteps];
            towerSize = [sim.numTowers, sim.numSteps];

            atmosphere = struct();

            atmosphere.truth = struct();
            atmosphere.truth.total_m = NaN(receiverTowerSize);
            atmosphere.truth.deterministic_total_m = NaN(receiverTowerSize);
            atmosphere.truth.troposphere_m = NaN(receiverTowerSize);
            atmosphere.truth.ionosphere_m = NaN(receiverTowerSize);
            atmosphere.truth.stochastic_residual_total_m = ...
                NaN(receiverTowerSize);
            atmosphere.truth.stochastic_residual_troposphere_m = ...
                NaN(receiverTowerSize);
            atmosphere.truth.stochastic_residual_ionosphere_m = ...
                NaN(receiverTowerSize);
            atmosphere.truth.stochastic_residual_total_by_tower_m = ...
                NaN(towerSize);
            atmosphere.truth.stochastic_residual_troposphere_by_tower_m = ...
                NaN(towerSize);
            atmosphere.truth.stochastic_residual_ionosphere_by_tower_m = ...
                NaN(towerSize);

            atmosphere.model = struct();
            atmosphere.model.total_m = NaN(receiverTowerSize);
            atmosphere.model.troposphere_m = NaN(receiverTowerSize);
            atmosphere.model.ionosphere_m = NaN(receiverTowerSize);

            atmosphere.residual = struct();
            atmosphere.residual.total_m = NaN(receiverTowerSize);
            atmosphere.residual.deterministic_total_m = NaN(receiverTowerSize);
            atmosphere.residual.troposphere_m = NaN(receiverTowerSize);
            atmosphere.residual.ionosphere_m = NaN(receiverTowerSize);

            atmosphere.covariance = struct();
            atmosphere.covariance.residualTroposphereSigma_m = ...
                NaN(1, sim.numSteps);
            atmosphere.covariance.residualIonosphereSigma_m = ...
                NaN(1, sim.numSteps);
            atmosphere.covariance.sigma_m = NaN(1, sim.numSteps);
            atmosphere.covariance.variance_m2 = NaN(1, sim.numSteps);
            atmosphere.covariance.totalSigma_m = NaN(1, sim.numSteps);
            atmosphere.covariance.totalVariance_m2 = NaN(1, sim.numSteps);
            atmosphere.covariance.correlation_model = "sameTower";

            atmosphere.diagnostics = struct();
            atmosphere.diagnostics.truth_model_residual_definition = ...
                "residual_m = truth.total_m - model.total_m";
            atmosphere.diagnostics.estimator_truth_residual_access = ...
                "sampled truth residuals are logged after measurement generation and are not used by prediction";
        end

        function nonAtmospheric = initializeNonAtmosphericBudgetHistory(sim)
            receiverTowerSize = ...
                [sim.numReceivers, sim.numTowers, sim.numSteps];

            componentNames = [ ...
                "total", ...
                "hardware", ...
                "antenna", ...
                "multipath", ...
                "tower_survey", ...
                "legacy_sagnac"];

            nonAtmospheric = struct();
            nonAtmospheric.truth = struct();
            nonAtmospheric.model = struct();
            nonAtmospheric.residual = struct();

            for componentIndex = 1:numel(componentNames)
                fieldName = char(componentNames(componentIndex) + "_m");

                nonAtmospheric.truth.(fieldName) = NaN(receiverTowerSize);
                nonAtmospheric.model.(fieldName) = NaN(receiverTowerSize);
                nonAtmospheric.residual.(fieldName) = NaN(receiverTowerSize);
            end

            nonAtmospheric.diagnostics = struct();
            nonAtmospheric.diagnostics.component_names = componentNames;
            nonAtmospheric.diagnostics.truth_model_residual_definition = ...
                "residual_m = truth_m - model_m";
            nonAtmospheric.diagnostics.note = ...
                "First-stage non-atmospheric budget records hardware, antenna, multipath, tower-survey scaffold, and legacy scalar Sagnac truth/model/residual terms.";
        end       
        
        function propagation = initializePropagationHistory(sim)
            receiverTowerSize = ...
                [sim.numReceivers, sim.numTowers, sim.numSteps];

            propagation = struct();
            if isfield(sim, 'measurementModel') && ...
                    ~isempty(sim.measurementModel) && ...
                    isprop(sim.measurementModel, 'propagationFrame')
                propagation.frame_used = ...
                    sim.measurementModel.propagationFrame;
            else
                propagation.frame_used = "ECI_static_receive_epoch";
            end
            propagation.light_time = struct();
            propagation.light_time.truth_m = NaN(receiverTowerSize);
            propagation.light_time.model_m = NaN(receiverTowerSize);
            propagation.light_time.residual_m = NaN(receiverTowerSize);

            propagation.sagnac = struct();
            propagation.sagnac.truth_m = NaN(receiverTowerSize);
            propagation.sagnac.model_m = NaN(receiverTowerSize);
            propagation.sagnac.residual_m = NaN(receiverTowerSize);

            propagation.relativity = struct();
            propagation.relativity.truth = struct();
            propagation.relativity.model = struct();
            propagation.relativity.residual = struct();
            propagation.relativity.truth.pathDelay_m = ...
                NaN(receiverTowerSize);
            propagation.relativity.model.pathDelay_m = ...
                NaN(receiverTowerSize);
            propagation.relativity.truth.clockCorrection_m = ...
                NaN(receiverTowerSize);
            propagation.relativity.model.clockCorrection_m = ...
                NaN(receiverTowerSize);
            propagation.relativity.residual.total_m = ...
                NaN(receiverTowerSize);

            propagation.diagnostics = struct();
            propagation.diagnostics.note = ...
                "ECI receive-epoch geometry is logged explicitly; light-time and relativity are zero scaffolds until implemented.";
        end

        function history = recordPropagationDiagnostics( ...
                sim, history, k, visibilityMask)

            diagnostics = ...
                sim.measurementModel.propagationDiagnosticsForVisibleLinks( ...
                visibilityMask);

            history.propagation.frame_used = diagnostics.frame_used;

            history.propagation.light_time.truth_m(:, :, k) = ...
                diagnostics.light_time.truth_m;
            history.propagation.light_time.model_m(:, :, k) = ...
                diagnostics.light_time.model_m;
            history.propagation.light_time.residual_m(:, :, k) = ...
                diagnostics.light_time.residual_m;

            history.propagation.sagnac.truth_m(:, :, k) = ...
                diagnostics.sagnac.truth_m;
            history.propagation.sagnac.model_m(:, :, k) = ...
                diagnostics.sagnac.model_m;
            history.propagation.sagnac.residual_m(:, :, k) = ...
                diagnostics.sagnac.residual_m;

            history.propagation.relativity.truth.pathDelay_m(:, :, k) = ...
                diagnostics.relativity.truth.pathDelay_m;
            history.propagation.relativity.model.pathDelay_m(:, :, k) = ...
                diagnostics.relativity.model.pathDelay_m;
            history.propagation.relativity.truth.clockCorrection_m(:, :, k) = ...
                diagnostics.relativity.truth.clockCorrection_m;
            history.propagation.relativity.model.clockCorrection_m(:, :, k) = ...
                diagnostics.relativity.model.clockCorrection_m;
            history.propagation.relativity.residual.total_m(:, :, k) = ...
                diagnostics.relativity.residual.total_m;
        end

        function history = recordAtmosphereBudget( ...
                sim, history, k, ...
                atmosphereTruthDelayRt_m, ...
                atmosphereTruthTroposphereRt_m, ...
                atmosphereTruthIonosphereRt_m, ...
                truthResidualByReceiverTower_m, ...
                truthTroposphereResidualByReceiverTower_m, ...
                truthIonosphereResidualByReceiverTower_m, ...
                truthTotal_m, ...
                truthTroposphereTotal_m, ...
                truthIonosphereTotal_m, ...
                atmosphereModelDelayRt_m, ...
                atmosphereModelTroposphereRt_m, ...
                atmosphereModelIonosphereRt_m)

            history.atmosphere.truth.total_m(:, :, k) = truthTotal_m;
            history.atmosphere.truth.deterministic_total_m(:, :, k) = ...
                atmosphereTruthDelayRt_m;
            history.atmosphere.truth.troposphere_m(:, :, k) = ...
                atmosphereTruthTroposphereRt_m;
            history.atmosphere.truth.ionosphere_m(:, :, k) = ...
                atmosphereTruthIonosphereRt_m;
            history.atmosphere.truth.stochastic_residual_total_m(:, :, k) = ...
                truthResidualByReceiverTower_m;
            history.atmosphere.truth.stochastic_residual_troposphere_m(:, :, k) = ...
                truthTroposphereResidualByReceiverTower_m;
            history.atmosphere.truth.stochastic_residual_ionosphere_m(:, :, k) = ...
                truthIonosphereResidualByReceiverTower_m;
            history.atmosphere.truth.stochastic_residual_total_by_tower_m(:, k) = ...
                history.atmosphere_truth_residual_by_tower_m(:, k);
            history.atmosphere.truth.stochastic_residual_troposphere_by_tower_m(:, k) = ...
                history.atmosphere_truth_troposphere_residual_by_tower_m(:, k);
            history.atmosphere.truth.stochastic_residual_ionosphere_by_tower_m(:, k) = ...
                history.atmosphere_truth_ionosphere_residual_by_tower_m(:, k);

            history.atmosphere.model.total_m(:, :, k) = ...
                atmosphereModelDelayRt_m;
            history.atmosphere.model.troposphere_m(:, :, k) = ...
                atmosphereModelTroposphereRt_m;
            history.atmosphere.model.ionosphere_m(:, :, k) = ...
                atmosphereModelIonosphereRt_m;

            history.atmosphere.residual.total_m(:, :, k) = ...
                truthTotal_m - atmosphereModelDelayRt_m;
            history.atmosphere.residual.deterministic_total_m(:, :, k) = ...
                atmosphereTruthDelayRt_m - atmosphereModelDelayRt_m;
            history.atmosphere.residual.troposphere_m(:, :, k) = ...
                truthTroposphereTotal_m - atmosphereModelTroposphereRt_m;
            history.atmosphere.residual.ionosphere_m(:, :, k) = ...
                truthIonosphereTotal_m - atmosphereModelIonosphereRt_m;

            covariance = HistoryRecorder.atmosphereCovarianceForEpoch(sim);
            history.atmosphere.covariance.residualTroposphereSigma_m(k) = ...
                covariance.residualTroposphereSigma_m;
            history.atmosphere.covariance.residualIonosphereSigma_m(k) = ...
                covariance.residualIonosphereSigma_m;
            history.atmosphere.covariance.sigma_m(k) = ...
                covariance.sigma_m;
            history.atmosphere.covariance.variance_m2(k) = ...
                covariance.variance_m2;
            history.atmosphere.covariance.totalSigma_m(k) = ...
                covariance.sigma_m;
            history.atmosphere.covariance.totalVariance_m2(k) = ...
                covariance.variance_m2;
        end

        function covariance = atmosphereCovarianceForEpoch(sim)
            covariance = struct( ...
                'residualTroposphereSigma_m', 0.0, ...
                'residualIonosphereSigma_m', 0.0, ...
                'sigma_m', 0.0, ...
                'variance_m2', 0.0);

            if isempty(sim.measurementModel) || ...
                    isempty(sim.measurementModel.modelAtmosphere)
                return;
            end

            modelAtmosphere = sim.measurementModel.modelAtmosphere;

            if modelAtmosphere.enableTroposphere
                covariance.residualTroposphereSigma_m = ...
                    double(modelAtmosphere.residualTroposphereSigma_m);
            end

            if modelAtmosphere.enableIonosphere
                covariance.residualIonosphereSigma_m = ...
                    double(modelAtmosphere.residualIonosphereSigma_m);
            end

            covariance.variance_m2 = ...
                covariance.residualTroposphereSigma_m^2 + ...
                covariance.residualIonosphereSigma_m^2;
            covariance.sigma_m = sqrt(covariance.variance_m2);
        end
        
        function history = recordNonAtmosphericBudget( ...
                sim, history, k, visibilityMask, towersEci, truthReceiverEci)

            if ~isfield(history, 'non_atmospheric') || ...
                    isempty(sim.measurementModel)
                return;
            end

            componentNames = [ ...
                "total", ...
                "hardware", ...
                "antenna", ...
                "multipath", ...
                "tower_survey", ...
                "legacy_sagnac"];

            modelAsset = sim.truthAsset;
            modelReceiverEci = truthReceiverEci;

            if isprop(sim, 'estAsset') && ~isempty(sim.estAsset)
                modelAsset = sim.estAsset;
                modelReceiverEci = sim.estAsset.receiverPositionsEci();
            end

            for rx = 1:sim.numReceivers
                for twr = 1:sim.numTowers
                    if ~visibilityMask(rx, twr)
                        continue;
                    end

                    [~, ~, truthBudget] = ...
                        sim.measurementModel.nonAtmosphericErrorBudget_m( ...
                        twr, ...
                        rx, ...
                        Clock.julianDateFromDatetime( ...
                        sim.simConfig.simulation.startUtc + ...
                        seconds(sim.time_s(k))), ...
                        towersEci(:, twr), ...
                        truthReceiverEci(:, rx), ...
                        sim.truthAsset);

                    [~, ~, modelBudget] = ...
                        sim.measurementModel.nonAtmosphericErrorBudget_m( ...
                        twr, ...
                        rx, ...
                        Clock.julianDateFromDatetime( ...
                        sim.simConfig.simulation.startUtc + ...
                        seconds(sim.time_s(k))), ...
                        towersEci(:, twr), ...
                        modelReceiverEci(:, rx), ...
                        modelAsset);

                    for componentIndex = 1:numel(componentNames)
                        componentName = componentNames(componentIndex);
                        fieldName = char(componentName + "_m");
                        budgetField = char(componentName);

                        truthValue_m = truthBudget.(budgetField).truth_m;
                        modelValue_m = modelBudget.(budgetField).model_m;

                        history.non_atmospheric.truth.(fieldName)(rx, twr, k) = ...
                            truthValue_m;
                        history.non_atmospheric.model.(fieldName)(rx, twr, k) = ...
                            modelValue_m;
                        history.non_atmospheric.residual.(fieldName)(rx, twr, k) = ...
                            truthValue_m - modelValue_m;
                    end
                end
            end
        end

        function value = computeRms(x)
            x = x(:);
            value = sqrt(mean(x.^2, 'omitnan'));
        end
    end
end
