% test_FiveTowerOneSpaceAsset_NReceivers_ReportFrames.m
% =========================================================================
% CLOCK-ONLY REVERSE-GNSS TEST SCENARIO
% =========================================================================
% Purpose:
%   Five ground towers transmit reference pseudorange signals to one GEO-like
%   SpaceAsset. The only active physical error is oscillator clock error
%   generated by the Allan-variance clock model in Clock.m. The SpaceAsset has
%   one shared onboard clock and N mounted Antenna phase centres.
%
% What to change for normal use:
%   1) Change N_RECEIVERS below to 1, 2, 3, 4, ...
%   2) Change SPACE_ASSET_CLOCK_TYPE to TCXO, StandardQuartz, OCXO1,
%      Rubidium1, Cesium1, or OCXO2.
%   3) Change RUN_TIME_HOURS and SAMPLE_TIME_S for runtime and sampling.
%   4) Change RECEIVER_BASELINE_M to open or shrink the receiver constellation
%      on the spacecraft body/LVLH frame.
%   5) Change COMPILE_PDF to false if pdflatex is not available.
%
% Active model:
%   pseudorange = geometric_range_ECI
%               + spacecraft_clock_bias_range
%               - tower_clock_bias_range
%               + optional measurement_noise
%
% Disabled for this scenario:
%   signal transmit time, light-time iteration, Sagnac correction, tower motion
%   during signal flight, Doppler, carrier phase, integrated Doppler,
%   PRN/code tracking, carrier ambiguity, group delay, active antenna phase
%   centre errors, troposphere, ionosphere, multipath, receiver tracking loops.
%
% Outputs:
%   - Standard LaTeX/PDF report from generateReport.m
%   - results .mat file from ReverseGnssSimulation.saveResults()
%   - frame_transform_diagnostics.mat
%   - frame_transform_snapshot.csv
%   - frame_transform_roundtrip_validation.csv
%
% Required files in the same folder or MATLAB path:
%   ReverseGnssSimulation.m, SimulationConfig.m, SpaceAsset.m, GroundNode.m,
%   ReceiverComponent.m, Clock.m, ExtendedKalmanFilter.m, generateReport.m

clear; clc; close all;

%% USER CONTROLS
N_RECEIVERS = 4;
SPACE_ASSET_CLOCK_TYPE = 'Cesium1';
TOWER_CLOCK_TYPE = 'Cesium1';
RUN_TIME_HOURS = 1.0;
SAMPLE_TIME_S = 1.0;
RECEIVER_BASELINE_M = 2.0;
RECEIVER_PSEUDORANGE_SIGMA_M = 0.30;
ENABLE_MEASUREMENT_NOISE = false;
COMPILE_PDF = true;
RANDOM_SEED = 20260527;

% GEO-like initial position for the validation case.
SPACE_ASSET_LAT_DEG = 0.0;
SPACE_ASSET_LON_DEG = -10.0;
SPACE_ASSET_ALTITUDE_M = 35786000.0;
TRUE_ATTITUDE_EULER321_DEG = [0.5; -0.3; 1.0];
ATTITUDE_FRAME = "LVLH";
TRUE_ANGULAR_RATE_BODY_DEGPS = [0.0; 0.0; 0.0];

% External time-transfer reference for tower-clock gauge fixing.
CLOCK_GAUGE_MODE = "externalTimeTransfer";
EXTERNAL_TIME_TRANSFER_SIGMA_PS = 50.0;
ESTIMATE_TOWER_CLOCK_BIAS = true;
ESTIMATE_TOWER_CLOCK_DRIFT = false;

%% PATH SETUP
thisFile = mfilename('fullpath');
thisDir = fileparts(thisFile);
if isempty(thisDir)
    thisDir = pwd;
end
addpath(thisDir);

fprintf('\n=== Reverse-GNSS clock-only test ===\n');
fprintf('Receivers on SpaceAsset: %d\n', N_RECEIVERS);
fprintf('SpaceAsset clock: %s\n', SPACE_ASSET_CLOCK_TYPE);
fprintf('Tower clock type: %s\n', TOWER_CLOCK_TYPE);
fprintf('Run time: %.2f h, sample time: %.3f s\n', RUN_TIME_HOURS, SAMPLE_TIME_S);

%% BUILD CONFIG OVERRIDES
antennaConfigs = buildAntennaConfigs(N_RECEIVERS, RECEIVER_BASELINE_M, RECEIVER_PSEUDORANGE_SIGMA_M);
spaceAssetConfig = buildSpaceAssetConfig(1, 'GEO-1', SPACE_ASSET_LAT_DEG, SPACE_ASSET_LON_DEG, ...
    SPACE_ASSET_ALTITUDE_M, SPACE_ASSET_CLOCK_TYPE, antennaConfigs);
spaceAssetsOverride = struct();
spaceAssetsOverride.numAssets = 1;
spaceAssetsOverride.receiverCountPerAsset = N_RECEIVERS;
spaceAssetsOverride.defaultReceiverClockMode = "sharedSpaceAssetClock";
spaceAssetsOverride.platformAttitudeTruth_deg = TRUE_ATTITUDE_EULER321_DEG;
spaceAssetsOverride.attitudeFrame = ATTITUDE_FRAME;
spaceAssetsOverride.platformAngularRateTruth_degps = TRUE_ANGULAR_RATE_BODY_DEGPS;
spaceAssetsOverride.assets = spaceAssetConfig;
spaceAssetsOverride.antennas = antennaConfigs;

simConfigOverride = struct();
simConfigOverride.randomSeed = RANDOM_SEED;
simConfigOverride.simulation.dt_s = SAMPLE_TIME_S;
simConfigOverride.simulation.totalTime_h = RUN_TIME_HOURS;
simConfigOverride.simulation.startUtc = datetime(2026, 5, 27, 23, 0, 0, 'TimeZone', 'UTC');

% Keep the global spaceAssets branch consistent for any downstream utilities.
simConfigOverride.spaceAssets = spaceAssetsOverride;

% Active scenario used by ReverseGnssSimulation.
simConfigOverride.scenarios.vsnscToReceivers.spaceAssets = spaceAssetsOverride;
simConfigOverride.scenarios.vsnscToReceivers.numReceiversToUse = N_RECEIVERS;
simConfigOverride.scenarios.vsnscToReceivers.clockGaugeMode = CLOCK_GAUGE_MODE;
simConfigOverride.scenarios.vsnscToReceivers.referenceTowerName = "Libreville";
simConfigOverride.scenarios.vsnscToReceivers.externalClockCorrectionSigma_ps = EXTERNAL_TIME_TRANSFER_SIGMA_PS;
simConfigOverride.scenarios.vsnscToReceivers.externalTimeTransfer.enableNoise = true;
simConfigOverride.scenarios.vsnscToReceivers.externalTimeTransfer.estimateTowerClockBias = ESTIMATE_TOWER_CLOCK_BIAS;
simConfigOverride.scenarios.vsnscToReceivers.externalTimeTransfer.estimateTowerClockDrift = ESTIMATE_TOWER_CLOCK_DRIFT;
simConfigOverride.scenarios.vsnscToReceivers.towerClock.clockType = TOWER_CLOCK_TYPE;
simConfigOverride.scenarios.vsnscToReceivers.measurement.pseudorangeSigma_m = RECEIVER_PSEUDORANGE_SIGMA_M;
simConfigOverride.scenarios.vsnscToReceivers.measurement.enableNoise = ENABLE_MEASUREMENT_NOISE;
simConfigOverride.scenarios.vsnscToReceivers.measurement.enableMeasurementNoise = ENABLE_MEASUREMENT_NOISE;
simConfigOverride.scenarios.vsnscToReceivers.measurement.elevationMask_deg = 0.0;
simConfigOverride.scenarios.vsnscToReceivers.measurement.sigma_numerical_floor_m = 1e-4;

simConfigOverride.scenarios.vsnscToReceivers.report.generatePdf = true;
simConfigOverride.scenarios.vsnscToReceivers.report.compilePdf = COMPILE_PDF;
simConfigOverride.scenarios.vsnscToReceivers.report.interactivePlots = false;
simConfigOverride.scenarios.vsnscToReceivers.report.enableAllanDeviationValidation = true;
simConfigOverride.scenarios.vsnscToReceivers.report.enableReceiverSubsetComparison = false;

% Explicitly preserve the clock-only architecture. These flags are carried for
% documentation and future module insertion; the active simulation does not yet
% branch on all of them.
simConfigOverride.scenarios.vsnscToReceivers.errorModels = disabledErrorRegistry();

runtimeOptions = struct();
runtimeOptions.entryPointName = mfilename;
runtimeOptions.N_RECEIVERS = N_RECEIVERS;
runtimeOptions.selected_oscillator_name = SPACE_ASSET_CLOCK_TYPE;
runtimeOptions.simConfigOverride = simConfigOverride;

%% RUN SIMULATION
sim = ReverseGnssSimulation(runtimeOptions);
sim.configure();
sim.run();
sim.saveResults();

%% FRAME TRANSFORM VALIDATION
frameDiagnostics = buildFrameTransformDiagnostics(sim);
if ~exist(char(sim.outputDir), 'dir')
    mkdir(char(sim.outputDir));
end
save(fullfile(char(sim.outputDir), 'frame_transform_diagnostics.mat'), 'frameDiagnostics');
writetable(frameDiagnostics.snapshotTable, fullfile(char(sim.outputDir), 'frame_transform_snapshot.csv'));
writetable(frameDiagnostics.roundtripTable, fullfile(char(sim.outputDir), 'frame_transform_roundtrip_validation.csv'));

fprintf('\nFrame transform validation:\n');
disp(frameDiagnostics.roundtripTable);

%% LATEX/PDF REPORT
% ReverseGnssSimulation.generateReport calls generateReport.m. The patched
% reportData contains the frame-transform tables, per-receiver diagnostics,
% tower-clock truth and EKF estimates, Allan stability diagnostics, and the
% disabled-component list.
sim.generateReport();

fprintf('\nOutputs written to:\n%s\n', char(sim.outputDir));
fprintf('Main report base name: %s_report.tex/.pdf\n', char(sim.scenarioName));

%% LOCAL FUNCTIONS
function antennas = buildAntennaConfigs(nReceivers, baseline_m, measurementSigma_m)
    if nReceivers < 1
        error('testScenario:InvalidReceiverCount', 'N_RECEIVERS must be at least 1.');
    end

    offsets = canonicalReceiverOffsets(nReceivers, baseline_m);

    template = struct( ...
        'id', 1, ...
        'parentAssetIndex', 1, ...
        'name', '', ...
        'enabled', true, ...
        'mode', "RX", ...
        'leverArmBody_m', zeros(3, 1), ...
        'offsetBody_m', zeros(3, 1), ...
        'pco_m', zeros(3, 1), ...
        'pcvMap', [], ...
        'measurementSigma_m', measurementSigma_m, ...
        'pseudorangeSigma_m', measurementSigma_m, ...
        'metadata', struct());

    antennas = repmat(template, 1, nReceivers);

    for k = 1:nReceivers
        antennas(k).id = k;
        antennas(k).parentAssetIndex = 1;
        antennas(k).name = sprintf('GEO-1-RX%02d', k);
        antennas(k).enabled = true;
        antennas(k).mode = "RX";
        antennas(k).leverArmBody_m = offsets(:, k);
        antennas(k).offsetBody_m = offsets(:, k);

        % Default zero RF phase-centre state.
        antennas(k).pco_m = zeros(3,1);
        antennas(k).pcvMap = [];

        antennas(k).measurementSigma_m = measurementSigma_m;
        antennas(k).pseudorangeSigma_m = measurementSigma_m;
        antennas(k).metadata.description = 'Clock-only mounted RX Antenna phase centre';
    end
end
function offsets = canonicalReceiverOffsets(nReceivers, baseline_m)
    base = baseline_m;
    canonical = [ ...
        0,      base,  -base,   0,      0,      0,      0,      base,  -base,   base,  -base,   base; ...
        0,      0,      0,     base,  -base,   0,      0,      base,   base,  -base,  -base,   0; ...
        0,      0,      0,      0,      0,     base,  -base,   0,      0,      0,      0,     base];

    if nReceivers <= size(canonical, 2)
        offsets = canonical(:, 1:nReceivers);
        return;
    end

    offsets = zeros(3, nReceivers);
    offsets(:, 1:size(canonical, 2)) = canonical;

    % Deterministic spherical-Fibonacci continuation for larger receiver counts.
    for k = (size(canonical, 2) + 1):nReceivers
        idx = k - size(canonical, 2);
        goldenAngle = pi * (3.0 - sqrt(5.0));
        z = 1.0 - 2.0 * (idx - 0.5) / max(1, nReceivers - size(canonical, 2));
        r = sqrt(max(0.0, 1.0 - z^2));
        phi = idx * goldenAngle;
        offsets(:, k) = base * [r * cos(phi); r * sin(phi); z];
    end
end

function asset = buildSpaceAssetConfig(id, name, lat_deg, lon_deg, altitude_m, clockType, antennas)
    asset = struct();
    asset.id = id;
    asset.name = name;
    asset.enabled = true;
    asset.startLatitude_deg = lat_deg;
    asset.startLongitude_deg = lon_deg;
    asset.geoAltitude_m = altitude_m;
    asset.enableJ2 = false;
    asset.enableRelativityClock = false;
    asset.sharedClock.clockType = char(clockType);
    asset.sharedClock.initialBias_ps = 0.0;
    asset.sharedClock.initialDrift_ps_per_s = 0.0;
    asset.antennas = antennas;
end

function errorModels = disabledErrorRegistry()
    names = { ...
        'signalTransmitTime', 'lightTimeIteration', 'sagnacCorrection', ...
        'towerMotionDuringSignalFlight', 'doppler', 'carrierPhase', ...
        'integratedDoppler', 'prnCodeTracking', 'carrierAmbiguity', ...
        'groupDelay', 'antennaPhaseCenter', 'troposphere', 'ionosphere', ...
        'multipath', 'receiverTrackingLoops'};
    errorModels = struct();
    for k = 1:numel(names)
        errorModels.(names{k}) = struct('enabled', false, 'note', 'Reserved for later implementation; disabled in clock-only test.');
    end
end

function diagnostics = buildFrameTransformDiagnostics(sim)
    epochIndex = unique([1, max(1, round(sim.numSteps / 2)), sim.numSteps]);
    rows = cell(0, 12);
    ecefRoundtripMax_m = 0.0;
    lvlhRoundtripMax_m = 0.0;

    for q = 1:numel(epochIndex)
        k = epochIndex(q);
        if k == 1
            epochLabel = "start";
        elseif k == sim.numSteps
            epochLabel = "final";
        else
            epochLabel = "mid";
        end

        jd = sim.jd0 + sim.time_s(k) / 86400.0;
        theta = GroundNode.gmstRad(jd);
        R_ecef_to_eci = rot3Local(theta);
        R_eci_to_ecef = R_ecef_to_eci.';

        state_eci = sim.history.truth(1:6, k);
        sat_eci_m = state_eci(1:3);
        R_lvlh_to_eci = SpaceAsset.lvlhToEciDcm(state_eci);
        R_eci_to_lvlh = R_lvlh_to_eci.';

        sat_ecef_m = R_eci_to_ecef * sat_eci_m;
        rows(end + 1, :) = makeFrameRow(epochLabel, "SpaceAsset", string(sim.assetTruth.name), sat_eci_m, sat_ecef_m, [0; 0; 0]); %#ok<AGROW>

        rx = sim.assetTruth.getEnabledAntennas();
        for idxRx = 1:numel(rx)
            rx_eci_m = SpaceAsset.receiverPositionFromState(rx(idxRx), state_eci, sim.history.truth(sim.idx.att, k), sim.attitudeFrame);
            rx_ecef_m = R_eci_to_ecef * rx_eci_m;
            rx_lvlh_m = R_eci_to_lvlh * (rx_eci_m - sat_eci_m);
            rows(end + 1, :) = makeFrameRow(epochLabel, "Receiver", string(rx(idxRx).name), rx_eci_m, rx_ecef_m, rx_lvlh_m); %#ok<AGROW>
            ecefRoundtripMax_m = max(ecefRoundtripMax_m, norm(R_ecef_to_eci * rx_ecef_m - rx_eci_m));
            lvlhRoundtripMax_m = max(lvlhRoundtripMax_m, norm(sat_eci_m + R_lvlh_to_eci * rx_lvlh_m - rx_eci_m));
        end

        for idxTower = 1:sim.numTowers
            tower_eci_m = sim.towers{idxTower}.getKinematicsECI(jd);
            tower_ecef_m = R_eci_to_ecef * tower_eci_m;
            tower_lvlh_m = R_eci_to_lvlh * (tower_eci_m - sat_eci_m);
            rows(end + 1, :) = makeFrameRow(epochLabel, "Tower", sim.towerNames(idxTower), tower_eci_m, tower_ecef_m, tower_lvlh_m); %#ok<AGROW>
            ecefRoundtripMax_m = max(ecefRoundtripMax_m, norm(R_ecef_to_eci * tower_ecef_m - tower_eci_m));
            lvlhRoundtripMax_m = max(lvlhRoundtripMax_m, norm(sat_eci_m + R_lvlh_to_eci * tower_lvlh_m - tower_eci_m));
        end
    end

    diagnostics = struct();
    diagnostics.snapshotTable = cell2table(rows, 'VariableNames', {'Epoch','ObjectType','Name', ...
        'ECI_X_km','ECI_Y_km','ECI_Z_km','ECEF_X_km','ECEF_Y_km','ECEF_Z_km', ...
        'LVLH_X_km','LVLH_Y_km','LVLH_Z_km'});
    diagnostics.roundtripTable = table(["ECEF_to_ECI_to_ECEF"; "ECI_to_LVLH_to_ECI"], ...
        [ecefRoundtripMax_m; lvlhRoundtripMax_m], ...
        'VariableNames', {'Transform','MaxRoundTripError_m'});
end

function row = makeFrameRow(epochLabel, objectType, objectName, eci_m, ecef_m, lvlh_m)
    row = {char(epochLabel), char(objectType), char(objectName), ...
        eci_m(1) / 1000.0, eci_m(2) / 1000.0, eci_m(3) / 1000.0, ...
        ecef_m(1) / 1000.0, ecef_m(2) / 1000.0, ecef_m(3) / 1000.0, ...
        lvlh_m(1) / 1000.0, lvlh_m(2) / 1000.0, lvlh_m(3) / 1000.0};
end

function R = rot3Local(angle_rad)
    R = [cos(angle_rad), -sin(angle_rad), 0.0; ...
         sin(angle_rad),  cos(angle_rad), 0.0; ...
         0.0,             0.0,            1.0];
end
