% test_scientific_validation_campaign_metrics  Campaign metrics use valid quantities.

testDirectory = fileparts(mfilename('fullpath'));
repositoryRoot = fileparts(testDirectory);
addpath(repositoryRoot);
addpath(fullfile(repositoryRoot, 'config'));

invalidNominalRow = consistencyRow_('nominalDualFrequency', 100);
invalidNominalRow.status = 'invalidRun';
rows = { ...
    consistencyRow_('slipInjection', 100), ...
    consistencyRow_('nominalDualFrequency', 1), ...
    consistencyRow_('nominalDualFrequency', 1), ...
    consistencyRow_('nominalDualFrequency', 6), ...
    invalidNominalRow};
consistency = revgnss.ScientificCampaignMetrics.aggregateConsistency( ...
    rows, 'nominalDualFrequency');
assert(consistency.nisCode.nIndependentRuns == 3);
assert(abs(consistency.nisCode.normalizedMean - 8 / 3) < 1e-12);
assert(strcmp(consistency.nisCode.status, 'warnHigh'));
assert(consistency.nisCode.normalizedMean < 10, ...
    'The non-nominal stress row entered the consistency aggregation.');

criteria = struct( ...
    'positionRmsPassLimit_m', 20, ...
    'clockBiasRmsPassLimit_m', 15, ...
    'positionRmsWarningLimit_m', 35, ...
    'clockBiasRmsWarningLimit_m', 40);
assert(strcmp(revgnss.ScientificCampaignMetrics. ...
    assessAccuracy(20, 15, criteria).status, 'pass'));
assert(strcmp(revgnss.ScientificCampaignMetrics. ...
    assessAccuracy(30, 30, criteria).status, 'warn'));
assert(strcmp(revgnss.ScientificCampaignMetrics. ...
    assessAccuracy(10, 41, criteria).status, 'fail'));
assert(strcmp(revgnss.ScientificCampaignMetrics. ...
    assessAccuracy(36, 10, criteria).status, 'fail'));
assert(strcmp(revgnss.ScientificCampaignMetrics. ...
    assessAccuracy(10, 10, struct()).status, 'notAssessed'));
assert(strcmp(revgnss.ScientificCampaignMetrics. ...
    assessAccuracy(NaN, 10, criteria).status, 'invalidRun'));

fixingOff = struct( ...
    'integerFixAttempted', false, ...
    'nTowers', 2, ...
    'nBaselines', 2, ...
    'nIntegerFixed', 0);
ambiguity = revgnss.ScientificCampaignMetrics. ...
    summarizeAmbiguityDecisions(fixingOff);
assert(isnan(ambiguity.acceptanceFraction));
assert(strcmp(ambiguity.status, 'notApplicableFixingDisabled'));

oneAccepted = fixingOff;
oneAccepted.integerFixAttempted = true;
oneAccepted.nIntegerFixed = 1;
ambiguity = revgnss.ScientificCampaignMetrics. ...
    summarizeAmbiguityDecisions(oneAccepted);
assert(ambiguity.nConfiguredCandidates == 4 && ambiguity.nAccepted == 1);
assert(abs(ambiguity.acceptanceFraction - 0.25) < 1e-12);
assert(strcmp(ambiguity.correctnessStatus, ...
    'notAssessedWithoutTruthComparison'));

noCandidates = oneAccepted;
noCandidates.nTowers = 0;
noCandidates.nIntegerFixed = 0;
ambiguity = revgnss.ScientificCampaignMetrics. ...
    summarizeAmbiguityDecisions(noCandidates);
assert(ambiguity.attempted && strcmp(ambiguity.status, ...
    'notAvailableNoConfiguredCandidates'));

slips = revgnss.ScientificCampaignMetrics.summarizeSlipDeclarations( ...
    struct('nConfirmedSlips', 3), 2);
assert(slips.configuredEpochCount == 2);
assert(slips.nDetectorDeclarations == 3);
assert(isnan(slips.detectionProbability));
assert(strcmp(slips.status, 'notAvailableWithoutEventAssociation'));

invalidCriteria = criteria;
invalidCriteria.positionRmsWarningLimit_m = 10;
invalidCriteriaRejected = false;
try
    revgnss.ScientificCampaignMetrics.assessAccuracy(1, 1, invalidCriteria);
catch exception
    invalidCriteriaRejected = strcmp(exception.identifier, ...
        'ScientificCampaignMetrics:invalidAccuracyCriteria');
end
assert(invalidCriteriaRejected, ...
    'Invalid criteria passed when the realized error met the pass limit.');

config = masterConfig();
assert(strcmp(config.validation.unsupportedFeaturePolicy, 'error'));
assert(isnan(config.validation.scientificCampaign.acceptanceCriteria. ...
    nominalDualFrequency.positionRmsPassLimit_m));

duplicateSeedConfig = config;
duplicateSeedConfig.validation.scientificCampaign.enable = true;
duplicateSeedConfig.validation.scientificCampaign.seedList = [7, 7];
duplicateSeedsRejected = false;
try
    revgnss.ScientificValidationCampaign.run(duplicateSeedConfig);
catch exception
    duplicateSeedsRejected = strcmp(exception.identifier, ...
        'ScientificValidationCampaign:invalidSeeds');
end
assert(duplicateSeedsRejected, ...
    'Duplicate seeds were counted as independent campaign runs.');

reportSource = fileread(fullfile(repositoryRoot, '+revgnss', 'ReportRunner.m'));
campaignPosition = strfind(reportSource, ...
    'campResult85_ = revgnss.ScientificValidationCampaign.run(cfg)');
matPosition = strfind(reportSource, '% ---- MAT: save');
assert(~isempty(campaignPosition) && ~isempty(matPosition) && ...
    campaignPosition(1) < matPosition(1), ...
    'Campaign results are computed after report persistence.');

fprintf('test_scientific_validation_campaign_metrics: PASS\n');

function row = consistencyRow_(caseName, normalizedValue)
    nisGroup = struct( ...
        'status', 'unused', ...
        'mean', 10 * normalizedValue, ...
        'nisPerDof', normalizedValue);
    neesGroup = struct( ...
        'status', 'unused', ...
        'mean', normalizedValue);
    row = struct();
    row.caseName = caseName;
    row.nisResult = struct( ...
        'available', true, ...
        'nisOverall', nisGroup, ...
        'nisCode', nisGroup, ...
        'nisCarrier', nisGroup, ...
        'nisDoppler', nisGroup, ...
        'neesPos', neesGroup, ...
        'neesVel', neesGroup, ...
        'neesClk', neesGroup, ...
        'neesAtt', neesGroup);
end
