function test_coherent_two_way_code_constant_velocity_closure()
% Moving-endpoint closure against an independent one-dimensional solution.

c = revgnss.CoherentTwoWayCodeRangingModel.SpeedOfLight_mps;
d0_m = 2.0e6;
velocityA_mps = 900;
velocityB_mps = -450;
t4_s = 1000;
turnaround_s = 3.5e-6;
clockOffset_s = 2000;

initiatorTruth = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'physicalTruth', 'spacecraft:A', [0;0;0], [velocityA_mps;0;0], 0, ...
    clockLocalTimeAtReference_s=clockOffset_s);
transponderTruth = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'physicalTruth', 'spacecraft:B', [d0_m;0;0], [velocityB_mps;0;0], 0);
physical = hardware_('physicalTruth', turnaround_s);
calibration = hardware_('calibrationProduct', turnaround_s);
metadata = metadata_();

[observation, diagnostic] = revgnss.CoherentTwoWayCodeRangingModel.simulateObservation( ...
    initiatorTruth, transponderTruth, physical, calibration, t4_s, metadata);

t3Oracle_s = ((c + velocityA_mps) * t4_s - d0_m) / (c + velocityB_mps);
t2Oracle_s = t3Oracle_s - turnaround_s;
t1Oracle_s = ((c - velocityB_mps) * t2Oracle_s - d0_m) / ...
    (c - velocityA_mps);
expectedRange_m = 0.5 * c * ((t4_s - t1Oracle_s) - turnaround_s);

assert(abs(diagnostic.t1TransmitCoordinateTime_s - t1Oracle_s) < 2e-11);
assert(abs(diagnostic.t2TransponderReceiveCoordinateTime_s - t2Oracle_s) < 2e-11);
assert(abs(diagnostic.t3TransponderTransmitCoordinateTime_s - t3Oracle_s) < 2e-11);
assert(abs(diagnostic.t4FinalReceptionCoordinateTime_s - t4_s) < eps(t4_s));
assert(abs(observation.processedValue - expectedRange_m) < 2e-3);
assert(max(abs([diagnostic.forwardLightTimeResidual_s, ...
    diagnostic.returnLightTimeResidual_s])) < 1e-11);

initiatorEstimate = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'estimatorState', 'spacecraft:A', [0;0;0], [velocityA_mps;0;0], 0, ...
    clockLocalTimeAtReference_s=clockOffset_s);
transponderEstimate = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'estimatorState', 'spacecraft:B', [d0_m;0;0], [velocityB_mps;0;0], 0);
[prediction_m, prediction] = revgnss.CoherentTwoWayCodeRangingModel.predictProcessedRange( ...
    observation, initiatorEstimate, transponderEstimate, calibration);
assert(abs(prediction_m - observation.processedValue) < 2e-3);
assert(abs(prediction.referenceCoordinateTime_s - t4_s) < 2e-12);

lateEpoch_s = 3600;
[lateObservation, lateDiagnostic] = ...
    revgnss.CoherentTwoWayCodeRangingModel.simulateObservation( ...
    initiatorTruth, transponderTruth, physical, calibration, lateEpoch_s, metadata);
[latePrediction_m, latePrediction] = ...
    revgnss.CoherentTwoWayCodeRangingModel.predictProcessedRange( ...
    lateObservation, initiatorEstimate, transponderEstimate, calibration);
assert(abs(latePrediction_m - lateObservation.processedValue) < 1e-8);
assert(abs(latePrediction.referenceCoordinateTime_s - lateEpoch_s) < 2e-12);
assert(max(abs([lateDiagnostic.forwardLightTimeResidual_s, ...
    lateDiagnostic.returnLightTimeResidual_s])) <= 1e-12);

fprintf('test_coherent_two_way_code_constant_velocity_closure: PASS\n');
end

function hardware = hardware_(source, turnaround_s)
hardware = revgnss.CoherentTwoWayCodeHardwareModel( ...
    parameterSource=source, physicalChainIdentifier='chain:A-B:S', ...
    calibrationProductIdentifier='cal:A-B:S:001', ...
    turnaroundProperTime_s=turnaround_s, codeRateTurnaroundRatio=1);
end

function metadata = metadata_()
metadata = struct( ...
    'observationIdentifier', 'obs:A-B:moving', ...
    'sessionIdentifier', 'session:A-B:moving', ...
    'signalIdentifier', 'PN1', ...
    'covarianceGroupIdentifier', 'cov:A-B:moving', ...
    'covarianceRowIndex', 1, 'covarianceBlock_m2', 0.01, ...
    'carrierToNoiseDensity_dBHz', 50, 'available', true, ...
    'qualityFlags', struct('codeLock',true), ...
    'truthDiagnosticIdentifier', 'truth:A-B:moving');
end
