% test_golden_baseline  The contract gate for the two reference scenarios.
%
%   config/golden_baseline.json        (single asset, 4 antennas)
%   config/golden_baseline_multi.json  (N = 6 federated formation, 4 antennas each)
%
% WHAT THIS TEST IS FOR. Those two files are the reference configuration every later analysis
% is compared against, and every value in them is defended in docs/golden_baseline_provenance.md.
% A defensible baseline is only defensible while the config it resolves to still matches the
% document. This test asserts the SCIENTIFIC CONTRACT -- the specific choices the provenance
% document argues for -- not merely that the files parse.
%
% It also asserts the property that makes the PAIR interpretable: the single-asset and
% multi-asset baselines must share a byte-identical error model, so that any difference between
% their results is attributable to the formation and to nothing else. Change one, change both.
%
% v2.0 (four receive antennas). The baselines moved from one antenna to four. Three groups of
% assertions exist only because of that:
%   * the two ANTENNA-SCOPE GATES. Amplitude scintillation and coloured code multipath are
%     physically common to all four phase centres and were drawn independently per antenna,
%     which averages them down by sqrt(4) for free while R shrinks to match -- invisible to
%     every consistency metric. Both gates must be on.
%   * the FOUR ANTENNAS ARE NOT AN ATTITUDE SENSOR. finalizeConfig switches
%     estimateAttitudeFromPseudorange on above one antenna and the use*Partials flags switch
%     it back off; the test pins the outcome so the decision cannot drift silently.
%   * the MULTI-ASSET FLEET IS HOMOGENEOUS. cfg.assets(2..6) carries a stale single-column
%     lever arm from MultiAssetConfig.cloneAsset_; the federated runtime rebuilds each leaf
%     from cfg.asset, so all six spacecraft really do get four antennas. That is asserted on
%     the path that actually runs, so the stale clone cannot start being read unnoticed.
%
% TWO MODES.
%   DEFAULT (fast, always runs). Resolves both scenarios and checks the contract. No simulation
%     is run, so this costs a few seconds.
%   FULL (set OO_V1_GOLDEN=1). Additionally executes both scenarios end to end at a shortened
%     120 s duration and asserts that the pipeline completes, that the row composition is the
%     one the provenance document claims, that the two-way time-transfer rows really are in the
%     filter (the one structural claim the whole covariance rests on), and that the formation's
%     relative layer produces a finite shape solution.
%
% To freeze a numeric fingerprint of a FULL-LENGTH run for later comparison:
%   out = run_oo_v1('golden_baseline_multi.json');
%   fp  = revgnss.GoldenRunFingerprint.fromRun(out, [], ...
%             fullfile('config','golden_baseline_multi.json'));
%   revgnss.GoldenRunFingerprint.write(fp, fullfile('tests','golden','golden_baseline_multi.json'));
% If that file exists this test checks the scenario SHA-256 against it, which catches the
% failure mode that makes a golden worse than useless: a scenario edited without re-cutting the
% golden, so the gate passes while measuring something else.

fprintf('== test_golden_baseline ==\n');

thisDir = fileparts(mfilename('fullpath'));
root    = fileparts(thisDir);
addpath(root);
addpath(fullfile(root, 'config'));
addpath(fullfile(root, 'config', 'internal'));

warnState = warning('query', 'ConfigFactory:rxCarrierBiasAbsorbed');
warning('off', 'ConfigFactory:rxCarrierBiasAbsorbed');
warnCleanup = onCleanup(@() warning(warnState.state, 'ConfigFactory:rxCarrierBiasAbsorbed')); %#ok<NASGU>

single_ = 'golden_baseline.json';
multi_  = 'golden_baseline_multi.json';
paths   = struct('single', fullfile(root,'config',single_), ...
                 'multi',  fullfile(root,'config',multi_));
assert(isfile(paths.single), 'Missing scenario: %s', paths.single);
assert(isfile(paths.multi),  'Missing scenario: %s', paths.multi);

% ==========================================================================================
% 1. Resolution: both files resolve, finalisation is idempotent, no leaf is silently overridden
% ==========================================================================================
[cfgS, mdS] = resolveSimulationConfig(paths.single);
[cfgM, mdM] = resolveSimulationConfig(paths.multi);

for c = {{'single', cfgS, mdS}, {'multi', cfgM, mdM}}
    nm = c{1}{1}; cfg = c{1}{2}; md = c{1}{3};
    assert(isequaln(cfg, revgnss.ConfigFactory.finalizeConfig(cfg)), ...
        '%s: configuration finalisation is not idempotent.', nm);
    changed = {};
    for i = 1:numel(md.explicitPaths)
        p = md.explicitPaths{i};
        if ~isequaln(i_get(md.preResolutionConfig, p, '<absent>'), i_get(cfg, p, '<absent>'))
            changed{end+1} = p; %#ok<AGROW>
        end
    end
    assert(isempty(changed), ...
        ['%s: resolution overrode scenario-owned leaves, so the file no longer says what it ' ...
         'does:\n  %s'], nm, strjoin(changed, sprintf('\n  ')));
    fprintf('  ok   %s: resolves, idempotent, %d explicit leaves all survive\n', ...
        nm, numel(md.explicitPaths));
end

% ==========================================================================================
% 2. The scientific contract (docs/golden_baseline_provenance.md)
% ==========================================================================================
nFail = 0;
for c = {{'single', cfgS}, {'multi', cfgM}}
    nm = c{1}{1}; cfg = c{1}{2};
    g  = @(p, d) i_get(cfg, p, d);
    chk = @(cond, msg, varargin) i_check(cond, [nm ': ' msg], varargin{:});

    % ---- geometry, timing -------------------------------------------------------------
    nFail = nFail + chk(g('scenario.nTowers',0) == 5, 'the 5-site named tower network is the baseline geometry');
    nFail = nFail + chk(g('scenario.nReceivers',0) == 4, ...
        ['FOUR receive antennas -- the flight configuration, and a requirement of this ' ...
         'baseline. It is only defensible together with the two antenna-scope gates below.']);
    nFail = nFail + chk(size(g('asset.receiverLeverArms_body_m',[]),2) == 4, ...
        ['finalizeConfig must supply the 3x4 non-coplanar antenna cross; the scenario must ' ...
         'NOT set the arms itself (finalizeConfig owns that leaf)']);
    nFail = nFail + chk(g('simulation.dt_s',0) == 1, '1 Hz observation rate');
    nFail = nFail + chk(abs(rad2deg(g('estimator.elevationMask_rad',0)) - 10) < 1e-9, ...
        '10 deg elevation mask (standard precise-GNSS policy; inert here, lowest tower 22.58 deg)');

    % ---- the two antenna-scope gates (v2.0; the whole reason 4 antennas are defensible) --
    nFail = nFail + chk(isequal(g('atmosphere.sharedAcrossAntennas.enable',false), true), ...
        ['the four antennas must SHARE one amplitude-scintillation realisation. They span ' ...
         '2.0 m = 8e-3 Fresnel scales, so the true inter-antenna correlation is ~1; drawing ' ...
         'them independently averages the LARGEST truth-only term (0.618 m rms of z-h) down ' ...
         'by sqrt(4) while R shrinks to match, which no NEES/NIS check can detect']);
    nFail = nFail + chk(isequal(g('errors.multipath.coloredGM.sharedAcrossAntennas.enable',false), true), ...
        ['the four antennas must SHARE one coloured-multipath realisation per tower. As ' ...
         'parameterised (1/sin(el) envelope on the TOWER elevation) this is a ground-station ' ...
         'term, hence transmit-end and common to every receive antenna']);

    % ---- atmosphere: physical truth, independent model, uncombined dual frequency -------
    nFail = nFail + chk(isequal(g('realism.grade',false), true), 'realism grade is on');
    nFail = nFail + chk(isequal(g('atmosphere.realistic',false), true), ...
        'the realistic atmosphere profile is selected');
    nFail = nFail + chk(strcmp(g('errors.troposphere.modelType','?'), 'localWeatherGM'), ...
        'Saastamoinen-class troposphere, not a constant offset');
    nFail = nFail + chk(strcmp(g('errors.troposphere.truth.mappingType','?'), 'niell') && ...
                        strcmp(g('errors.troposphere.model.mappingType','?'), 'niell'), ...
        'Niell mapping on both sides');
    nFail = nFail + chk(strcmp(g('errors.ionosphere.modelType','?'), 'tecGaussMarkov'), ...
        ['tecGaussMarkov -- under simpleMapped the stochastic TEC state never steps and the ' ...
         'residual degenerates to a constant a GEO cannot distinguish from clock']);
    nFail = nFail + chk(strcmp(g('errors.ionosphere.model.correction','?'), 'klobuchar'), ...
        ['the model correction is an INDEPENDENT Klobuchar climatology, not none and not a ' ...
         'scaled copy of the truth']);
    nFail = nFail + chk(strcmp(g('measurements.codeMode','?'), 'singleFrequency'), ...
        'raw uncombined dual frequency (not the 2.98x-noisier IF combination)');
    nFail = nFail + chk(isequal(g('atmosphere.ionosphereFree',true), false), ...
        'ionosphere-free combination is off');
    nFail = nFail + chk(isequal(g('atmosphere.estimateIono',true), false), ...
        ['atmosphere.estimateIono stays false: setting it forces model.correction=none inside ' ...
         'applyAtmosphereProfile and throws the Klobuchar correction away']);
    nFail = nFail + chk(strcmp(g('estimation.ionosphereMode','?'), 'perTowerSlant'), ...
        'per-tower slant-ionosphere states (uncombined PPP formulation)');
    nFail = nFail + chk(strcmp(g('estimation.troposphereMode','?'), 'perTowerZwd'), ...
        'per-tower ZWD states (the dominant covariance-honesty lever)');
    nFail = nFail + chk(g('estimation.tropoZwd.tau_s',0) == g('errors.troposphere.stochastic.tau_s',-1) && ...
                        g('estimation.tropoZwd.sigma_ss_m',0) == g('errors.troposphere.stochastic.sigmaWet_ss_m',-1), ...
        'the ZWD state process model matches the simulated wet-delay process');
    nFail = nFail + chk(isequal(g('errors.ionosphere.higherOrder.enable',false), true), ...
        '2nd/3rd-order ionosphere retained (survives first-order removal)');
    nFail = nFail + chk(strcmp(g('effects.ionosphere.mappingModel','?'), 'thinShell'), ...
        'thin-shell obliquity, not a 1/sin(el) secant');
    nFail = nFail + chk(isequal(g('errors.ionosphere.scintillation.enable',false), true) && ...
                        g('errors.ionosphere.scintillation.S4zen',0) > 0, ...
        'scintillation is live (two towers sit in the equatorial anomaly)');

    % ---- truth-only effects really are truth-only ---------------------------------------
    for e = {'errors.multipath', 'errors.hardwareDelay', 'effects.towerSurvey'}
        nFail = nFail + chk(isequal(g([e{1} '.truth.enable'],false), true) && ...
                            isequal(g([e{1} '.model.enable'],true), false), ...
            '%s is injected on the truth and NOT modelled (it must survive z - h)', e{1});
    end
    % antenna PCV is deliberately NOT in that list. RangeCorrections treats the presence of
    % effects.antenna.pcvModel as authoritative and bypasses the truth/model gate, so the same
    % PCV is applied to both sides and the residual is 2.2e-8 m. v1.0 claimed a 5 mm truth-only
    % PCV that was never in the run; v2.0 states it as a calibrated (cancelling) correction.
    nFail = nFail + chk(~strcmp(g('effects.antenna.pcvModel','none'), 'none'), ...
        ['effects.antenna.pcvModel is applied to truth AND model (a perfectly calibrated ' ...
         'antenna). Do NOT re-add effects.antennaPCV.truth/model to the scenario -- the gate ' ...
         'is bypassed and the pair would claim an injection the code cancels.']);
    nFail = nFail + chk(isequal(g('errors.multipath.coloredGM.enable',false), true) && ...
                        g('errors.multipath.coloredGM.tau_s',0) > 0, ...
        'multipath is a time-correlated process, not white noise');
    nFail = nFail + chk(isequal(g('errors.hardwareDelay.residualStochastic.enable',false), true) && ...
                        g('errors.hardwareDelay.sigma_m',0) > 0 && ...
                        g('errors.hardwareDelay.sigma_m',1) <= 0.1, ...
        'the hardware delay is CALIBRATED but not zero (<= 0.1 m residual, not the 0.5 m raw delay)');
    nFail = nFail + chk(isequal(g('effects.antennaPCO.calibrationResidual.enable',false), true), ...
        ['the PCO calibration residual is live (measured 1.97 mm rms of z-h) -- it is the ' ...
         'antenna-calibration term this configuration actually injects']);

    % ---- four antennas are PHASE CENTRES, not an attitude sensor -------------------------
    nFail = nFail + chk(isequal(g('estimator.attitude.useCodePartials',true), false) && ...
                        isequal(g('estimator.attitude.useCarrierPartials',true), false), ...
        ['attitude partials off: a 1.02 m lever against a 0.17-0.23 m code sigma carries ~1e-5 ' ...
         'of the star tracker''s per-epoch information, so enabling them would be unearned ' ...
         'information']);
    nFail = nFail + chk(isequal(g('estimator.estimateAttitudeFromPseudorange',true), false), ...
        ['finalizeConfig switches this ON above one antenna and useCodePartials switches it ' ...
         'back off -- pin the OUTCOME so the decision cannot drift silently']);
    nFail = nFail + chk(strcmp(g('estimator.attitudeCarrierMode','?'), 'off'), ...
        ['carrier attitude off. Below 2 antennas this was forced; at 4 it would survive, so it ' ...
         'is now a choice: it needs calibrated inter-antenna phase biases, which this ' ...
         'configuration explicitly declares UNcalibrated']);
    nFail = nFail + chk(strcmp(g('estimator.attitudeInitMode','none'), 'none'), ...
        'no carrier-baseline attitude initialisation (it would need >= 3 phase centres and a fix)');
    nFail = nFail + chk(g('estimator.starTracker.whiteAngularSigma_rad',0) > 0, ...
        'the star tracker noise is pinned in the scenario, not inherited silently');

    % ---- inter-antenna carrier bias: live at 4 antennas, and included --------------------
    nFail = nFail + chk(isequal(g('errors.interAntennaCarrierBias.enable',false), true), ...
        ['the inter-antenna carrier bias is ON. It was structurally dead at one antenna; at ' ...
         'four it is real hardware (measured 0.068 m rms of z-h) and omitting it would hand ' ...
         'any later inter-antenna work a zero-bias truth reference']);
    nFail = nFail + chk(isequal(g('errors.interAntennaCarrierBias.drift.enable',true), false), ...
        ['its DRIFT stays off and is a declared omission: a constant is absorbed exactly by ' ...
         'the per-receiver ambiguity, a drift is not, and nothing in R pays for it']);
    nFail = nFail + chk(isequal(g('carrierSlip.baselineDifferencedMode.enable',false), true), ...
        ['baseline-differenced slip detection is declared explicitly -- it is exactly inert at ' ...
         'one antenna and becomes live at four, so it must not be inherited silently']);

    % ---- corrections a real system applies ARE applied ----------------------------------
    dDcb = (g('biases.interFrequency.code.truth.L1_m',0) - g('biases.interFrequency.code.model.L1_m',0)) - ...
           (g('biases.interFrequency.code.truth.L2_m',0) - g('biases.interFrequency.code.model.L2_m',0));
    nFail = nFail + chk(abs(dDcb) > 0 && abs(dDcb) <= 0.06, ...
        ['the differential code bias is corrected to published-product accuracy: residual ' ...
         '%.4f m must be non-zero (a DCB exists) and <= 0.06 m = 0.2 ns (it is calibrated)'], dDcb);
    nFail = nFail + chk(isequal(g('frames.truthEop.enable',false), true) && ...
                        isequal(g('frames.eopModel.enable',false), true), ...
        'polar motion is present in the truth AND corrected by the estimator');
    dXp = abs(g('frames.truthEop.polarMotion_xp_arcsec',0) - g('frames.eopModel.polarMotion_xp_arcsec',0));
    dYp = abs(g('frames.truthEop.polarMotion_yp_arcsec',0) - g('frames.eopModel.polarMotion_yp_arcsec',0));
    nFail = nFail + chk(dXp > 0 && dYp > 0 && dXp <= 1e-3 && dYp <= 1e-3, ...
        ['the EOP residual (%.5f / %.5f arcsec) is a realistic IERS prediction error: non-zero ' ...
         '(not an oracle) and <= 1 mas (not an uncorrected pole)'], dXp, dYp);
    nFail = nFail + chk(isequal(g('effects.solidEarthTide.truth.enable',true), false), ...
        ['the solid-Earth tide is NOT injected: the implementation is truth-only, so leaving it ' ...
         'on simulates a system declining a mandatory IERS correction']);
    nFail = nFail + chk(isequal(g('physics.relativity.clock.truth.enable',false), true) && ...
                        isequal(g('physics.relativity.clock.model.enable',false), true), ...
        'the relativistic clock rate offset is present in the truth AND modelled');

    % ---- clocks and the degeneracy-breaking observable -----------------------------------
    nFail = nFail + chk(strcmp(g('asset.clockType','?'), 'CESIUM1'), ...
        'the conservative literature-anchored clock template, not the optimistic legacy table');
    nFail = nFail + chk(strcmp(g('clock.mode','?'), 'spacecraftReceiverClockOnly'), ...
        'tower clocks are corrected by a broadcast product, not estimated');
    nFail = nFail + chk(isequal(g('estimator.estimateTowerClocks',true), false), ...
        'the derived tower-clock-state flag agrees with clock.mode');
    nFail = nFail + chk(abs(g('clocks.tower.product.sigmaBias_m',0) - 0.10) < 1e-12, ...
        'IGS real-time-service class tower clock product (0.33 ns), not IGS-final');
    nFail = nFail + chk(isequal(g('measurements.twoWayTimeTransfer.enable',false), true) && ...
                        isequal(g('measurements.twoWayTimeTransfer.useInEKF',false), true), ...
        ['two-way time transfer is IN THE FILTER. Without it the GEO radial <-> clock ' ...
         'degeneracy is exact (corr -1.000000) and no radial covariance statement is honest.']);
    nFail = nFail + chk(isequal(g('measurements.twoWayTimeTransfer.conservativeProductCorrelation',false), true), ...
        'the reference-clock product correlation is treated conservatively');

    % ---- measurement noise ---------------------------------------------------------------
    nFail = nFail + chk(abs(g('measurements.doppler.sigma_mps',0) - 0.03*sqrt(2)) < 5e-4, ...
        ['the Doppler sigma carries the documented sqrt(2) inflation for the identical-L1/L2 ' ...
         'noise draw (0.03 * sqrt(2) = %.4f), got %.4f'], 0.03*sqrt(2), g('measurements.doppler.sigma_mps',0));
    nFail = nFail + chk(g('measurements.carrier.sigma_m',0) >= 0.010 - 1e-12, ...
        ['the carrier sigma is >= 10 mm because phase wind-up, phase multipath and the PCV ' ...
         'calibration residual are NOT modelled and must be paid for in R']);
    nFail = nFail + chk(g('measurement.sigmaFloor_m',0) >= 0.01 - 1e-12, ...
        'the measurement sigma floor is >= 1 cm (1 mm is sub-wavelength)');
    nFail = nFail + chk(strcmp(g('measurements.codeNoise.model','?'), 'cn0'), ...
        'C/N0-based code weighting, so a low-elevation tower is not trusted like a zenith one');

    % ---- dynamics: same force family, ONE declared parameter gap ---------------------------
    nFail = nFail + chk(isequal(g('orbit.truth.perturbations.luniSolar.enable',false), true) && ...
                        isequal(g('estimator.dynamics.perturbations.luniSolar.enable',false), true), ...
        'third-body luni-solar is in BOTH propagators (a real GEO OD filter models it)');
    nFail = nFail + chk(isequal(g('orbit.truth.perturbations.srp.enable',false), true) && ...
                        isequal(g('estimator.dynamics.perturbations.srp.enable',false), true), ...
        'SRP is in BOTH propagators');
    crT = g('orbit.truth.perturbations.srp.Cr',NaN);
    crE = g('estimator.dynamics.perturbations.srp.Cr',NaN);
    relGap = abs(crT - crE) / crT;
    nFail = nFail + chk(relGap > 0 && relGap < 0.15, ...
        ['the ONLY dynamic gap is a declared reflectivity error: |Cr_truth - Cr_ekf|/Cr = %.3f ' ...
         'must be non-zero (an honest gap) and small (a parameter error, not a missing force)'], relGap);
    nFail = nFail + chk(isequal(g('estimator.processNoise.modelMismatch.enable',true), false), ...
        ['modelMismatch stays off: sigma_accel_mps2 already covers the declared gap ~180x, and ' ...
         'charging both would count the same uncertainty twice']);
    nFail = nFail + chk(g('estimator.sigma_accel_mps2',0) > 0, ...
        'a residual-acceleration process noise is declared');

    % ---- no unearned states --------------------------------------------------------------
    nFail = nFail + chk(isequal(g('estimator.srpCoefficient.enable',true), false), ...
        'the SRP scale state is off (measured to converge to 0.748 against a truth of 1.0)');
    nFail = nFail + chk(isequal(g('estimator.empiricalAccel.enable',true), false), ...
        'empirical accelerations are off (measured NEES 25.6 -> 25.4, i.e. nothing)');
    nFail = nFail + chk(isequal(g('estimator.lambda.enable',true), false), ...
        'integer ambiguity resolution is off (unvendored external toolbox; float is honest)');
    nFail = nFail + chk(strcmp(g('estimation.ambiguityMode','?'), 'floatPerTowerReceiverSignal'), ...
        ['float carrier ambiguities per tower x receiver x signal -- the only legal mode above ' ...
         'one antenna, and what absorbs the inter-antenna carrier bias']);
end

% ---- multi-asset specific ------------------------------------------------------------------
gM = @(p, d) i_get(cfgM, p, d);
chkM = @(cond, msg, varargin) i_check(cond, ['multi: ' msg], varargin{:});
nFail = nFail + chkM(gM('scenario.nSpaceAssets',0) == 6, 'six spacecraft (chief + five secondaries)');
nFail = nFail + chkM(gM('formation.crossTrackSpread',0) == 1.0, ...
    ['crossTrackSpread must be 1.0: the planar projected-circular helix makes the crosslink ' ...
     'line-of-sight matrix RANK 2, so the filter shrinks covariance in a direction the ranges ' ...
     'carry no information about']);
nFail = nFail + chkM(isequal(gM('atmosphere.sharedAcrossFormation.enable',false), true), ...
    ['the formation must share one atmosphere: independent per-asset draws are a measured ' ...
     'artefact (single-difference atmosphere 0.954 m -> exactly 0 once re-rooted)']);
nFail = nFail + chkM(strcmp(gM('multiAsset.mode','?'), 'fast'), 'the federated runtime');
nFail = nFail + chkM(isequal(gM('multiAsset.keepIslInPerAssetEkf',true), false) && ...
                     isequal(gM('measurements.isl.enable',true), false), ...
    ['crosslink observations are used ONCE: they feed the read-only relative layer, never a ' ...
     'filter AND the relative layer']);
nFail = nFail + chkM(isequal(gM('multiAsset.twoWayISL.enable',false), true) && ...
                     gM('multiAsset.twoWayISL.sigma_m',0) >= 0.02, ...
    'the two-way crosslink layer is on at a conservative (>= 2 cm) ranging sigma');
nFail = nFail + chkM(gM('multiAsset.twoWayISL.delayCal.sigma_const_m',0) > 0, ...
    ['the per-link delay calibration is CALIBRATED BUT NOT ZERO -- it is arc-constant and is ' ...
     'therefore the floor on the relative geometry']);
nFail = nFail + chkM(strcmp(gM('multiAsset.twoWayISL.gauge.mode','?'), 'minNorm'), ...
    'minNorm gauge (radialStiff was withdrawn as a metric artefact on a truth-tuned prior)');
nFail = nFail + chkM(isequal(gM('multiAsset.federated.parallel',true), false), ...
    ['the federated fan-out runs SERIAL: a 1e-14 reordering difference was measured to flip a ' ...
     'guard and move 33 of 148 reported fields']);
for s = {'beamPointingLock','groundDifferencedRotation','jointGeometry','groundCarrier','groundCarrierProbe'}
    nFail = nFail + chkM(isequal(gM(['multiAsset.' s{1} '.enable'], true), false), ...
        'multiAsset.%s is OFF in the baseline', s{1});
end
nFail = nFail + chkM(isequal(gM('beamforming.enable',false), true), ...
    'the read-only beamforming phasor budget is reported');

% ---- THE FLEET IS HOMOGENEOUS: every spacecraft really gets four antennas -------------------
% cfg.assets(2..6) carries a stale 3x1 lever arm from MultiAssetConfig.cloneAsset_. Under
% multiAsset.mode='fast' it is never read -- each federated leaf is rebuilt from cfg.asset and
% re-finalised, and finalizeConfig regenerates the 3x4 cross from scenario.nReceivers. This
% asserts it on the path that actually runs, so a change that starts reading the clone fails here.
setupM = revgnss.IndependentFleetScenarioFactory.federatedSetup(cfgM, false);
armCols = zeros(1, setupM.N);
for ai = 1:setupM.N
    ciF = revgnss.ConfigFactory.finalizeConfig( ...
        revgnss.IndependentFleetScenarioFactory.assetConfigForIndex(setupM, ai));
    armCols(ai) = size(ciF.asset.receiverLeverArms_body_m, 2);
end
nFail = nFail + chkM(all(armCols == 4), ...
    ['every federated spacecraft must simulate FOUR phase centres; got [%s] antenna columns ' ...
     'across the six leaves. A 1 here means the stale MultiAssetConfig.cloneAsset_ single ' ...
     'column is being read and the fleet is silently heterogeneous.'], num2str(armCols));

% ---- the pair must share ONE error model ----------------------------------------------------
sharedPaths = { ...
    'scenario.nReceivers', ...
    'atmosphere.sharedAcrossAntennas.enable', ...
    'errors.multipath.coloredGM.sharedAcrossAntennas.enable', ...
    'errors.interAntennaCarrierBias.enable','errors.interAntennaCarrierBias.sigma_cycles', ...
    'errors.interAntennaCarrierBias.drift.enable', ...
    'errors.troposphere.modelType','errors.troposphere.stochastic.tau_s', ...
    'errors.troposphere.stochastic.sigmaWet_ss_m','errors.troposphere.sigma_m', ...
    'errors.ionosphere.modelType','errors.ionosphere.model.correction', ...
    'errors.ionosphere.stochastic.tau_s','errors.ionosphere.stochastic.sigmaVDelayL1_ss_m', ...
    'errors.ionosphere.truth.diurnal.vtecDay_TECU','errors.ionosphere.truth.diurnal.vtecNight_TECU', ...
    'errors.ionosphere.scintillation.S4zen','errors.ionosphere.sigma_m', ...
    'errors.multipath.coloredGM.tau_s','errors.multipath.coloredGM.sigmaCodeL1_ss_m', ...
    'errors.hardwareDelay.sigma_m','effects.towerSurvey.sigmaENU_m', ...
    'effects.antenna.pcvModel', ...
    'effects.antennaPCO.calibrationResidual.receiverOffset_body_m', ...
    'biases.interFrequency.code.truth.L1_m','biases.interFrequency.code.truth.L2_m', ...
    'biases.interFrequency.code.model.L1_m','biases.interFrequency.code.model.L2_m', ...
    'frames.truthEop.polarMotion_xp_arcsec','frames.eopModel.polarMotion_xp_arcsec', ...
    'frames.truthEop.polarMotion_yp_arcsec','frames.eopModel.polarMotion_yp_arcsec', ...
    'clocks.tower.product.sigmaBias_m','clocks.tower.product.sigmaDrift_mps', ...
    'clocks.tower.product.updateInterval_s','measurement.sigmaFloor_m', ...
    'measurements.doppler.sigma_mps','measurements.carrier.sigma_m', ...
    'measurements.codeNoise.cn0.sigmaAt45dBHz_m','measurements.twoWayTimeTransfer.sigma_m', ...
    'carrierSlip.baselineDifferencedMode.enable','carrierSlip.baselineDifferencedMode.referenceAntenna', ...
    'estimator.elevationMask_rad','estimator.sigma_accel_mps2', ...
    'estimator.attitude.useCodePartials','estimator.attitude.useCarrierPartials', ...
    'estimator.starTracker.whiteAngularSigma_rad', ...
    'estimator.imu.truth.arw_rad_per_sqrt_s','estimator.imu.truth.rrw_rad_per_s_sqrt_s', ...
    'estimator.dynamics.perturbations.srp.Cr','orbit.truth.perturbations.srp.Cr', ...
    'estimation.slantIono.tau_s','estimation.slantIono.sigma_ss_m', ...
    'estimation.tropoZwd.tau_s','estimation.tropoZwd.sigma_ss_m'};
drift = {};
for i = 1:numel(sharedPaths)
    p = sharedPaths{i};
    if ~isequaln(i_get(cfgS,p,'<absent>'), i_get(cfgM,p,'<absent>'))
        drift{end+1} = p; %#ok<AGROW>
    end
end
nFail = nFail + i_check(isempty(drift), ...
    ['the single-asset and multi-asset baselines have drifted apart on %d error-model leaf/leaves. ' ...
     'The pair is only interpretable as a controlled comparison while these match exactly:\n  %s'], ...
    numel(drift), strjoin(drift, sprintf('\n  ')));
if isempty(drift)
    fprintf('  ok   the pair shares one error model (%d leaves compared)\n', numel(sharedPaths));
end

% ==========================================================================================
% 2b. The attitude VARIANT (config/golden_baseline_attitude.json)
% ==========================================================================================
% golden_baseline.json runs four antennas that contribute nothing to attitude. That variant is
% the controlled experiment which measures what they WOULD buy. It is only a controlled
% experiment while it differs from the single-asset baseline in the three declared leaves and
% NOTHING else, so that is what this block asserts.
attFile = fullfile(root, 'config', 'golden_baseline_attitude.json');
if ~isfile(attFile)
    fprintf('  --   golden_baseline_attitude.json absent; attitude-variant contract not checked\n');
else
    [cfgA, mdA] = resolveSimulationConfig(attFile);
    gA   = @(p, d) i_get(cfgA, p, d);
    chkA = @(cond, msg, varargin) i_check(cond, ['attitude: ' msg], varargin{:});

    assert(isequaln(cfgA, revgnss.ConfigFactory.finalizeConfig(cfgA)), ...
        'attitude: configuration finalisation is not idempotent.');
    changedA = {};
    for i = 1:numel(mdA.explicitPaths)
        p = mdA.explicitPaths{i};
        if ~isequaln(i_get(mdA.preResolutionConfig, p, '<absent>'), i_get(cfgA, p, '<absent>'))
            changedA{end+1} = p; %#ok<AGROW>
        end
    end
    nFail = nFail + chkA(isempty(changedA), ...
        'resolution overrode scenario-owned leaves:\n  %s', strjoin(changedA, sprintf('\n  ')));

    nFail = nFail + chkA(strcmp(gA('estimator.attitudeCarrierMode','?'), ...
                                'calibratedDifferentialAmbiguity'), ...
        'the differential carrier-attitude path is ON (that is the whole point of the file)');
    nFail = nFail + chkA(strcmp(gA('estimator.diffAtt.referenceMode','?'), 'selfCalibrated'), ...
        ['referenceMode must be selfCalibrated -- externalInitialAttitude raises ' ...
         'externalReferenceUnavailable, and a truth-derived reference would be truth assistance']);
    nFail = nFail + chkA(isequal(gA('estimator.diffAtt.ambiguityResolution.enable',true), false), ...
        ['integer resolution on the attitude baselines stays off: with the line bias truth-only ' ...
         'the phase-bias status is notCalibratedExternalProduct and the fix is refused anyway']);
    nFail = nFail + chkA(isequal(gA('estimator.attitude.useCodePartials',true), false), ...
        'code attitude partials stay off here too (~2e-5 of the star tracker''s information)');

    % The line bias MUST be calibrated here and uncalibrated in the baseline -- the two changes
    % are one decision (see the file's _whyTheBiasMustChange).
    bA = gA('errors.interAntennaCarrierBias.sigma_cycles', NaN);
    bS = i_get(cfgS, 'errors.interAntennaCarrierBias.sigma_cycles', NaN);
    nFail = nFail + chkA(bA < bS && bA > 0, ...
        ['the inter-antenna line bias must be CALIBRATED here (%.3f cyc) and uncalibrated in ' ...
         'the baseline (%.3f cyc), and still non-zero: differential attitude reads exactly the ' ...
         'phase differences a line bias corrupts'], bA, bS);
    nFail = nFail + chkA(bA * 0.1903 < i_get(cfgS,'measurements.carrier.sigma_m',0), ...
        ['the calibrated residual (%.4f m at L1) must sit BELOW the carrier sigma -- otherwise ' ...
         'the bias is still the dominant term on the attitude baselines and nothing was gained'], ...
        bA * 0.1903);

    % Everything else must match the single-asset baseline exactly.
    attAllowed = {'errors.interAntennaCarrierBias.sigma_cycles'};
    driftA = {};
    for i = 1:numel(sharedPaths)
        p = sharedPaths{i};
        if any(strcmp(p, attAllowed)); continue; end
        if ~isequaln(i_get(cfgS,p,'<absent>'), i_get(cfgA,p,'<absent>'))
            driftA{end+1} = p; %#ok<AGROW>
        end
    end
    nFail = nFail + chkA(isempty(driftA), ...
        ['the attitude variant has drifted from the single-asset baseline on %d leaf/leaves ' ...
         'outside the declared delta, so it is no longer a controlled experiment:\n  %s'], ...
        numel(driftA), strjoin(driftA, sprintf('\n  ')));
    if isempty(driftA)
        fprintf(['  ok   attitude variant: resolves, idempotent, %d explicit leaves survive, and ' ...
                 'differs from the baseline only in the declared delta\n'], numel(mdA.explicitPaths));
    end
end

% ==========================================================================================
% 3. Frozen fingerprints, if any have been cut
% ==========================================================================================
for c = {{single_, paths.single}, {multi_, paths.multi}}
    [~, stem] = fileparts(c{1}{1});
    fpPath = fullfile(thisDir, 'golden', [stem '.json']);
    if ~isfile(fpPath)
        fprintf('  --   %s: no frozen fingerprint yet (see this file''s header for how to cut one)\n', stem);
        continue
    end
    frozen = revgnss.GoldenRunFingerprint.read(fpPath);
    sha    = revgnss.GoldenRunFingerprint.fileSha256(c{1}{2});
    if isfield(frozen,'scenarioSha256') && ~strcmp(sha, frozen.scenarioSha256)
        nFail = nFail + 1;
        fprintf(2, ['  FAIL %s: the scenario changed since the fingerprint was cut\n' ...
                    '        frozen %s\n        actual %s\n' ...
                    '        Re-run and re-cut it, recording why in tests/golden/README_golden.md.\n'], ...
            stem, frozen.scenarioSha256, sha);
    else
        fprintf('  ok   %s: frozen fingerprint matches the scenario sha256\n', stem);
    end
end

% ==========================================================================================
% 4. FULL mode: execute both scenarios (shortened) and check the load-bearing claims
% ==========================================================================================
if isempty(getenv('OO_V1_GOLDEN'))
    fprintf(['  NOTE simulations were NOT run. Set OO_V1_GOLDEN=1 to execute both baselines at\n' ...
             '       120 s and assert row composition and relative-layer output.\n']);
else
    fprintf('  running both baselines end to end at 120 s (OO_V1_GOLDEN is set)...\n');

    cfg = i_shorten(cfgS, 120);
    sim = revgnss.ReverseGNSSSimulation(cfg);
    sim.initialize();
    sim.run();
    rows = median(sim.simData.getNumMeasurementRows());
    % Derived, not hard-coded, so the expectation follows the topology:
    %   code     nT x nAnt x nSig  (both frequencies)          = 40
    %   Doppler  nT x nAnt x nSig  (both frequencies)          = 40
    %   carrier  nT x nAnt         (L1+L2 collapsed to one
    %                               ionosphere-free row/pair)  = 20
    %   two-way  nT                (does NOT scale w/ antenna) =  5
    nT_  = cfgS.scenario.nTowers;
    nA_  = cfgS.scenario.nReceivers;
    nS_  = sum(logical(cfgS.signals.enabledMask(:)));
    want = 2*nT_*nA_*nS_ + nT_*nA_ + nT_;
    nFail = nFail + i_check(rows == want, ...
        ['single: expected %g filter rows per epoch (%d code + %d Doppler + %d carrier + %d ' ...
         'two-way at nTowers=%d, nReceivers=%d, nSignals=%d), got %g. A missing block means an ' ...
         'observable this baseline claims to use is not reaching the filter.'], ...
        want, nT_*nA_*nS_, nT_*nA_*nS_, nT_*nA_, nT_, nT_, nA_, nS_, rows);
    posRms = rms(sim.simData.getPositionErrors());
    nFail = nFail + i_check(isfinite(posRms) && posRms > 0, ...
        'single: position error RMS must be finite and non-zero, got %g', posRms);
    fprintf('  ok   single: %g rows/epoch, position RMS %.3f m over 120 s\n', rows, posRms);

    cfgm = i_shorten(cfgM, 120);
    outM = revgnss.ReportRunner.runSingle(cfgm);
    nFail = nFail + i_check(isstruct(outM) && isfield(outM,'rel') && isstruct(outM.rel), ...
        'multi: the federated run produced no relative layer');
    if isstruct(outM) && isfield(outM,'rel') && isfield(outM.rel,'shapeErrSolved_m')
        s = outM.rel.shapeErrSolved_m;
        nFail = nFail + i_check(isfinite(s) && s > 0, ...
            'multi: solved shape error must be finite and non-zero, got %g', s);
        fprintf('  ok   multi: shape raw %.3f m -> solved %.3f m over 120 s\n', ...
            i_get(outM.rel,'shapeErrRaw_m',NaN), s);
    end
end

assert(nFail == 0, 'test_golden_baseline: %d contract violation(s)', nFail);
fprintf('test_golden_baseline PASSED\n');

% ==========================================================================================
function n = i_check(cond, msg, varargin)
    if cond
        n = 0;
    else
        n = 1;
        fprintf(2, '  FAIL %s\n', sprintf(msg, varargin{:}));
    end
end

function v = i_get(s, dottedPath, dflt)
    v = dflt;
    f = strsplit(dottedPath, '.');
    c = s;
    for i = 1:numel(f)
        if ~isstruct(c) || ~isfield(c, f{i}); return; end
        c = c.(f{i});
    end
    v = c;
end

function cfg = i_shorten(cfg, dur_s)
    cfg.simulation.duration_s    = dur_s;
    cfg.report.writePdf          = false;
    cfg.report.writeMat          = false;
    cfg.report.writeTex          = false;
    cfg.report.compileTex        = 'never';
    cfg.report.monteCarlo.enable = false;
    cfg.plots.enable             = false;
    cfg.plots.saveIndividualFigures = false;
    cfg.plots.savePdf            = false;
    cfg.report.reportFolder      = tempname;
    mkdir(cfg.report.reportFolder);
    cfg.report.stem              = 'golden_baseline_check';
    cfg = revgnss.ConfigFactory.finalizeConfig(cfg);
end
