% test_carrier_phase_wavelength_follows_band
%   cfg.measurements.carrierPhase.frequency_Hz/.lambda_m must follow the band the
%   scenario actually selected, not masterConfig's canonical GPS L1 seed.
%
%   masterConfig seeds both fields from revgnss.SignalDefinition.get('L1') and, before
%   this guard, nothing updated them when a scenario retuned the band. Measured across
%   config/ladder/freq/freq009..013 (licence-exempt pairs, 915 MHz to 61.25 GHz):
%   signals.L1.frequency_Hz followed the JSON in every file while
%   measurements.carrierPhase.frequency_Hz read 1575.42 MHz in ALL of them -- a 39x
%   wavelength error at the 61.25 GHz rung (4.89 mm read as 190.29 mm), silent because
%   the field is only read on the carrierMode='diagnostic' and attitude-init paths.
%
%   revgnss.SignalCatalog had the SAME defect on the live path: it returned
%   SignalDefinition.get(name), which is keyed by NAME and so handed the canonical L-band
%   back however the scenario retuned the band. That is what CarrierMeasurementBuilder
%   uses to build carrier EKF rows under carrierMode='ekfFloat' -- every ladder file --
%   against a code path that reads cfg.signals.frequencyHz(1) correctly.
%
%   Guards, in order:
%     1. the derived pair tracks the scenario band, and lambda == c / frequency exactly;
%     2. carrierPhase.lambda_m equals cfg.signals.L1.lambda_m to the bit (one source);
%     3. GOLDEN SAFETY: golden_baseline.json keeps the canonical L1, so the derived pair
%        must come out bit-identical to SignalDefinition.get('L1') -- no frozen golden moves;
%     4. a raw masterConfig handed straight to finalizeConfig (no provenance) is unmoved;
%     5. a scenario that pins carrierPhase.frequency_Hz explicitly keeps its own value;
%     6. SignalCatalog agrees with cfg.signals on BOTH carriers, and its
%        ionoScaleRelativeToL1 is the resolved (f_L1/f)^2, not the canonical GPS ratio;
%     7. GOLDEN SAFETY for the catalog: canonical L1/L2 come back bit-identical to
%        SignalDefinition, ionoScale included.

testDirectory  = fileparts(mfilename('fullpath'));
repositoryRoot = fileparts(testDirectory);
addpath(repositoryRoot);
addpath(fullfile(repositoryRoot, 'config'));
addpath(fullfile(repositoryRoot, 'config', 'internal'));

fprintf('=== test_carrier_phase_wavelength_follows_band ===\n');

C_MPS = 299792458;    % as revgnss.SignalDefinition and ConfigFactory use

warningState = warning('query', 'ConfigFactory:rxCarrierBiasAbsorbed');
warning('off', 'ConfigFactory:rxCarrierBiasAbsorbed');
warningCleanup = onCleanup(@() warning(warningState.state, ...
    'ConfigFactory:rxCarrierBiasAbsorbed'));   %#ok<NASGU>

shortRun = struct('simulation', struct('duration_s', 600));

% ---- 1+2: the band-retuning ladder rungs -----------------------------------
% freq009/011/013 span 2.45 GHz to 61.25 GHz, so a stuck 1575.42 MHz cannot pass by
% coincidence on any of them.
bandFiles = { ...
    'freq009_ism915_2450.json',    2.4500e9; ...
    'freq011_unii5200_5800.json',  5.8000e9; ...
    'freq013_ism24125_61250.json', 6.1250e10};

for k = 1:size(bandFiles, 1)
    fileName    = bandFiles{k, 1};
    expectedFHz = bandFiles{k, 2};
    cfg = resolveSimulationConfig(fileName, shortRun);

    assert(cfg.signals.L1.frequency_Hz == expectedFHz, ...
        '%s: signals.L1.frequency_Hz is %.6g Hz, expected %.6g Hz (fixture changed).', ...
        fileName, cfg.signals.L1.frequency_Hz, expectedFHz);

    cp = cfg.measurements.carrierPhase;

    assert(cp.frequency_Hz == cfg.signals.L1.frequency_Hz, ...
        ['%s: measurements.carrierPhase.frequency_Hz is %.6g Hz but the scenario ' ...
         'selected %.6g Hz. The carrier frequency must be derived from the resolved ' ...
         'signals.L1, not left at masterConfig''s canonical L1 seed.'], ...
        fileName, cp.frequency_Hz, cfg.signals.L1.frequency_Hz);

    % The headline assertion: lambda is c / (the scenario's frequency), exactly.
    expectedLambda = C_MPS / expectedFHz;
    assert(cp.lambda_m == expectedLambda, ...
        ['%s: measurements.carrierPhase.lambda_m is %.9g m, expected c/f = %.9g m ' ...
         '(ratio %.4gx). A carrier observable built at the wrong wavelength is silently ' ...
         'wrong -- nothing errors.'], ...
        fileName, cp.lambda_m, expectedLambda, cp.lambda_m / expectedLambda);

    % One source of truth: the same number the code path and iono scaling already use.
    assert(cp.lambda_m == cfg.signals.L1.lambda_m, ...
        ['%s: carrierPhase.lambda_m (%.12g) and signals.L1.lambda_m (%.12g) disagree; ' ...
         'they must come from the same resolved signal.'], ...
        fileName, cp.lambda_m, cfg.signals.L1.lambda_m);

    fprintf('  %-30s f = %10.4f MHz   lambda = %9.5f mm  OK\n', ...
        fileName, cp.frequency_Hz / 1e6, cp.lambda_m * 1e3);
end

% ---- 3: golden safety -- the canonical band must be bit-identical ----------
sigL1Canonical = revgnss.SignalDefinition.get('L1');
goldenFiles = {'golden_baseline.json', 'golden_baseline_multi.json'};
for k = 1:numel(goldenFiles)
    cfgG = resolveSimulationConfig(goldenFiles{k}, shortRun);
    cpG  = cfgG.measurements.carrierPhase;
    assert(cpG.frequency_Hz == sigL1Canonical.frequency_Hz, ...
        ['%s: carrierPhase.frequency_Hz moved to %.10g Hz; the golden uses the canonical ' ...
         'L1 (%.10g Hz) and this value must be byte-identical or the frozen goldens shift.'], ...
        goldenFiles{k}, cpG.frequency_Hz, sigL1Canonical.frequency_Hz);
    assert(cpG.lambda_m == sigL1Canonical.wavelength_m, ...
        ['%s: carrierPhase.lambda_m moved to %.17g m; canonical L1 is %.17g m. ' ...
         'Bit-identical is the requirement, not "close".'], ...
        goldenFiles{k}, cpG.lambda_m, sigL1Canonical.wavelength_m);
    fprintf('  %-30s canonical L1 preserved bit-identical  OK\n', goldenFiles{k});
end

% ---- 4: a raw masterConfig (no provenance) is unmoved ----------------------
cfgRaw = masterConfig();
cfgRaw.report.writePdf = false; cfgRaw.report.writeMat = false;
cfgRaw.report.compileTex = 'never'; cfgRaw.plots.showFigures = false;
seedFHz = cfgRaw.measurements.carrierPhase.frequency_Hz;
seedLam = cfgRaw.measurements.carrierPhase.lambda_m;
cfgRawResolved = revgnss.ConfigFactory.finalizeConfig(cfgRaw);
assert(cfgRawResolved.measurements.carrierPhase.frequency_Hz == seedFHz && ...
       cfgRawResolved.measurements.carrierPhase.lambda_m == seedLam, ...
    ['Direct finalizeConfig(masterConfig) moved carrierPhase from %.10g Hz / %.17g m ' ...
     'to %.10g Hz / %.17g m. With no scenario there is nothing to follow, so the seed ' ...
     'must survive untouched.'], seedFHz, seedLam, ...
    cfgRawResolved.measurements.carrierPhase.frequency_Hz, ...
    cfgRawResolved.measurements.carrierPhase.lambda_m);
fprintf('  raw masterConfig -> finalizeConfig: seed unmoved  OK\n');

% ---- 5: an explicitly pinned carrierPhase frequency wins -------------------
% overrides land in provenance.explicit exactly as a JSON leaf does, so this exercises
% the same scenario-ownership test the signal block uses.
pinnedFHz = 2.40e9;
cfgPin = resolveSimulationConfig('golden_baseline.json', struct( ...
    'simulation',   struct('duration_s', 600), ...
    'measurements', struct('carrierPhase', struct('frequency_Hz', pinnedFHz))));
assert(cfgPin.measurements.carrierPhase.frequency_Hz == pinnedFHz, ...
    ['An explicitly owned measurements.carrierPhase.frequency_Hz was overwritten ' ...
     '(%.10g Hz instead of %.10g Hz).'], ...
    cfgPin.measurements.carrierPhase.frequency_Hz, pinnedFHz);
assert(cfgPin.measurements.carrierPhase.lambda_m == C_MPS / pinnedFHz, ...
    ['lambda_m must be derived from the PINNED frequency (%.9g m expected, got %.9g m) ' ...
     'so the pair can never disagree.'], ...
    C_MPS / pinnedFHz, cfgPin.measurements.carrierPhase.lambda_m);
fprintf('  pinned carrierPhase.frequency_Hz respected, lambda derived from it  OK\n');

% ---- 6: SignalCatalog -- the LIVE ekfFloat path -- follows the band too ----
% CarrierMeasurementBuilder.build takes lambda and ionoScaleRelativeToL1 from this
% catalog for every carrier EKF row, so a canonical value here is not latent: it builds
% the observable at the wrong wavelength on every ladder file.
% freq009 is 2450/915 MHz and freq011 is 5800/5200 MHz -- both carriers move, and the
% two pairs have very different L1/L2 ratios, so a stuck canonical value cannot pass.
catalogFiles = { ...
    'freq009_ism915_2450.json',   2.4500e9, 9.1500e8; ...
    'freq011_unii5200_5800.json', 5.8000e9, 5.2000e9};

for k = 1:size(catalogFiles, 1)
    fileName = catalogFiles{k, 1};
    fL1      = catalogFiles{k, 2};
    fL2      = catalogFiles{k, 3};
    cfg  = resolveSimulationConfig(fileName, shortRun);
    sigs = revgnss.SignalCatalog.carrierSignalsFromConfig(cfg);

    assert(numel(sigs) == 2, ...
        '%s: expected 2 active carrier signals, got %d (fixture changed).', ...
        fileName, numel(sigs));
    assert(cfg.signals.L2.frequency_Hz == fL2, ...
        '%s: signals.L2.frequency_Hz is %.6g Hz, expected %.6g Hz (fixture changed).', ...
        fileName, cfg.signals.L2.frequency_Hz, fL2);

    expectedF   = [fL1, fL2];
    expectedLam = C_MPS ./ expectedF;
    for si = 1:2
        assert(sigs(si).frequency_Hz == expectedF(si), ...
            ['%s: SignalCatalog signal %d reports %.6g Hz but the scenario selected ' ...
             '%.6g Hz. SignalDefinition is keyed by NAME, so the catalog must overlay ' ...
             'the resolved cfg.signals band.'], ...
            fileName, si, sigs(si).frequency_Hz, expectedF(si));
        assert(sigs(si).wavelength_m == expectedLam(si), ...
            ['%s: SignalCatalog signal %d wavelength is %.9g m, expected c/f = %.9g m ' ...
             '(ratio %.4gx). This is the lambda every carrier EKF row is built with.'], ...
            fileName, si, sigs(si).wavelength_m, expectedLam(si), ...
            sigs(si).wavelength_m / expectedLam(si));
        assert(sigs(si).wavelength_m == cfg.signals.wavelength_m(si), ...
            '%s: SignalCatalog signal %d disagrees with cfg.signals.wavelength_m(%d).', ...
            fileName, si, si);
    end

    % Iono scaling must use the SCENARIO's frequency ratio. For freq011 the true L2
    % scale is (5.8/5.2)^2 = 1.2440; the canonical GPS ratio would charge 1.6469.
    assert(sigs(1).ionoScaleRelativeToL1 == 1, ...
        '%s: ionoScaleRelativeToL1 for the primary must be exactly 1, got %.12g.', ...
        fileName, sigs(1).ionoScaleRelativeToL1);
    expectedScaleL2 = (fL1 / fL2)^2;
    assert(sigs(2).ionoScaleRelativeToL1 == expectedScaleL2, ...
        ['%s: L2 ionoScaleRelativeToL1 is %.6f, expected the resolved (f_L1/f_L2)^2 = ' ...
         '%.6f. Carrying SignalDefinition''s canonical value charges the GPS L1/L2 ratio ' ...
         '%.6f instead of the band the scenario actually uses.'], ...
        fileName, sigs(2).ionoScaleRelativeToL1, expectedScaleL2, ...
        (revgnss.SignalDefinition.get('L1').frequency_Hz / ...
         revgnss.SignalDefinition.get('L2').frequency_Hz)^2);

    fprintf('  %-30s catalog L1/L2 = %8.3f / %8.3f mm, ionoScale(L2) = %.4f  OK\n', ...
        fileName, sigs(1).wavelength_m * 1e3, sigs(2).wavelength_m * 1e3, ...
        sigs(2).ionoScaleRelativeToL1);
end

% ---- 7: catalog golden safety -- canonical bands come back bit-identical ---
cfgG = resolveSimulationConfig('golden_baseline.json', shortRun);
sigsG = revgnss.SignalCatalog.carrierSignalsFromConfig(cfgG);
canonicalNames = {'L1','L2'};
for si = 1:numel(sigsG)
    ref = revgnss.SignalDefinition.get(canonicalNames{si});
    assert(sigsG(si).frequency_Hz == ref.frequency_Hz && ...
           sigsG(si).wavelength_m == ref.wavelength_m && ...
           sigsG(si).ionoScaleRelativeToL1 == ref.ionoScaleRelativeToL1, ...
        ['golden_baseline.json: SignalCatalog %s returned %.17g Hz / %.17g m / scale ' ...
         '%.17g against canonical %.17g Hz / %.17g m / scale %.17g. The golden uses the ' ...
         'canonical band, so every field must be byte-identical or the frozen goldens shift.'], ...
        canonicalNames{si}, sigsG(si).frequency_Hz, sigsG(si).wavelength_m, ...
        sigsG(si).ionoScaleRelativeToL1, ref.frequency_Hz, ref.wavelength_m, ...
        ref.ionoScaleRelativeToL1);
end
fprintf('  golden_baseline.json           catalog canonical, all %d fields bit-identical  OK\n', ...
    3 * numel(sigsG));

% The process-local setFrequencyOverride (run_oo_v1_freqbattery's mechanism) must still
% propagate: finalizeConfig builds cfg.signals from SignalDefinition.get, so the override
% is folded into the resolved arrays the catalog now reads.
overrideCleanup = onCleanup(@() revgnss.SignalDefinition.clearFrequencyOverride()); %#ok<NASGU>
revgnss.SignalDefinition.clearFrequencyOverride();
revgnss.SignalDefinition.setFrequencyOverrideGHz(8.400, 7.900);
cfgOv  = resolveSimulationConfig('golden_baseline.json', shortRun);
sigsOv = revgnss.SignalCatalog.carrierSignalsFromConfig(cfgOv);
revgnss.SignalDefinition.clearFrequencyOverride();
assert(sigsOv(1).frequency_Hz == 8.400e9 && sigsOv(2).frequency_Hz == 7.900e9, ...
    ['SignalDefinition.setFrequencyOverride no longer reaches SignalCatalog ' ...
     '(got %.6g / %.6g Hz, expected 8.4e9 / 7.9e9). run_oo_v1_freqbattery depends on it.'], ...
    sigsOv(1).frequency_Hz, sigsOv(2).frequency_Hz);
assert(sigsOv(1).wavelength_m == C_MPS / 8.400e9 && ...
       sigsOv(2).wavelength_m == C_MPS / 7.900e9, ...
    'setFrequencyOverride reached the frequency but not the wavelength.');
fprintf('  setFrequencyOverride (freqbattery mechanism) still propagates  OK\n');

fprintf('PASS: test_carrier_phase_wavelength_follows_band\n');
