function test_constant_velocity_four_event_light_time_oracle()
% Compare the iterative ranging solver with an independent quadratic oracle.

referenceTime_s = 0;
t4_s = 25;
turnaroundCoordinate_s = 27e-6;
transponderProperTimeRate = 1 - 2.5e-10;
transponderLocalClockRate = 1 + 4e-8;

rA0_m = [42164e3; -1.4e6; 0.6e6];
vA_mps = [18; 3065; -7];
rB0_m = [43520e3; -0.3e6; -0.25e6];
vB_mps = [-31; 3012; 19];
aTxOffset_m = [1.2; -0.4; 0.7];
aRxOffset_m = [-0.8; 0.9; -0.3];
bRxOffset_m = [0.35; -1.1; 0.55];
bTxOffset_m = [-1.4; 0.2; 0.85];

oracleSpec.referenceCoordinateTime_s = referenceTime_s;
oracleSpec.finalReceptionCoordinateTime_s = t4_s;
oracleSpec.coordinateTurnaroundDelay_s = turnaroundCoordinate_s;
oracleSpec.initiatorTransmit = phaseCentre_(rA0_m + aTxOffset_m, vA_mps);
oracleSpec.initiatorReceive = phaseCentre_(rA0_m + aRxOffset_m, vA_mps);
oracleSpec.transponderReceive = phaseCentre_(rB0_m + bRxOffset_m, vB_mps);
oracleSpec.transponderTransmit = phaseCentre_(rB0_m + bTxOffset_m, vB_mps);
oracle = revgnss.ConstantVelocityFourEventLightTimeOracle.solve(oracleSpec);

initiator = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'physicalTruth', 'spacecraft:A', rA0_m, vA_mps, referenceTime_s, ...
    transmitPhaseCentreOffset_body_m=aTxOffset_m, ...
    receivePhaseCentreOffset_body_m=aRxOffset_m, ...
    transmitTerminalIdentifier='A:tx', receiveTerminalIdentifier='A:rx', ...
    transmitAntennaIdentifier='A:tx-pc', ...
    receiveAntennaIdentifier='A:rx-pc');
transponder = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'physicalTruth', 'spacecraft:B', rB0_m, vB_mps, referenceTime_s, ...
    transmitPhaseCentreOffset_body_m=bTxOffset_m, ...
    receivePhaseCentreOffset_body_m=bRxOffset_m, ...
    transmitTerminalIdentifier='B:tx', receiveTerminalIdentifier='B:rx', ...
    transmitAntennaIdentifier='B:tx-pc', ...
    receiveAntennaIdentifier='B:rx-pc', ...
    localClockRate=transponderLocalClockRate, ...
    properTimeRate=transponderProperTimeRate);

turnaroundProper_s = turnaroundCoordinate_s * transponderProperTimeRate;
physical = hardware_('physicalTruth', turnaroundProper_s);
calibration = hardware_('calibrationProduct', turnaroundProper_s);
[observation, diagnostic] = revgnss.CoherentTwoWayCodeRangingModel.simulateObservation( ...
    initiator, transponder, physical, calibration, t4_s, metadata_());

differentRemoteClock = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'physicalTruth', 'spacecraft:B', rB0_m, vB_mps, referenceTime_s, ...
    transmitPhaseCentreOffset_body_m=bTxOffset_m, ...
    receivePhaseCentreOffset_body_m=bRxOffset_m, ...
    transmitTerminalIdentifier='B:tx', receiveTerminalIdentifier='B:rx', ...
    transmitAntennaIdentifier='B:tx-pc', ...
    receiveAntennaIdentifier='B:rx-pc', ...
    localClockRate=1-7e-8, ...
    properTimeRate=transponderProperTimeRate);
[remoteClockControl, remoteClockDiagnostic] = ...
    revgnss.CoherentTwoWayCodeRangingModel.simulateObservation( ...
    initiator, differentRemoteClock, physical, calibration, t4_s, metadata_());
assert(observation.processedValue == remoteClockControl.processedValue);
assert(diagnostic.t2TransponderReceiveCoordinateTime_s == ...
    remoteClockDiagnostic.t2TransponderReceiveCoordinateTime_s);

offsetInitiator = endpointA_(rA0_m,vA_mps,referenceTime_s, ...
    aTxOffset_m,aRxOffset_m,73,1);
[offsetControl,~] = revgnss.CoherentTwoWayCodeRangingModel.simulateObservation( ...
    offsetInitiator,transponder,physical,calibration,t4_s,metadata_());
assert(abs(observation.processedValue-offsetControl.processedValue) < 1e-9, ...
    'Initiator clock offset must cancel from its local round-trip interval.');

rateInitiator = endpointA_(rA0_m,vA_mps,referenceTime_s, ...
    aTxOffset_m,aRxOffset_m,0,1+3e-8);
[rateControl,~] = revgnss.CoherentTwoWayCodeRangingModel.simulateObservation( ...
    rateInitiator,transponder,physical,calibration,t4_s,metadata_());
assert(abs(observation.processedValue-rateControl.processedValue) > 1e-3, ...
    'Initiator clock rate must remain observable in the code-delay scale.');

activeTimes_s = [diagnostic.t1TransmitCoordinateTime_s, ...
    diagnostic.t2TransponderReceiveCoordinateTime_s, ...
    diagnostic.t3TransponderTransmitCoordinateTime_s, ...
    diagnostic.t4FinalReceptionCoordinateTime_s];
oracleTimes_s = [oracle.t1_s, oracle.t2_s, oracle.t3_s, oracle.t4_s];
assert(max(abs(activeTimes_s - oracleTimes_s)) < 2e-12);
assert(abs(diagnostic.forwardGeometricRange_m - oracle.forwardRange_m) < 1e-5);
assert(abs(diagnostic.returnGeometricRange_m - oracle.returnRange_m) < 1e-5);
assert(max(abs([oracle.forwardResidual_s, oracle.returnResidual_s])) < 2e-15);
assert(max(abs([diagnostic.forwardLightTimeResidual_s, ...
    diagnostic.returnLightTimeResidual_s])) < 2e-12);
assert(oracle.t1_s < oracle.t2_s && oracle.t2_s < oracle.t3_s && ...
    oracle.t3_s < oracle.t4_s);

forbiddenSource = fileread(fullfile(fileparts(mfilename('fullpath')), '..', ...
    '+revgnss', 'ConstantVelocityFourEventLightTimeOracle.m'));
assert(~contains(forbiddenSource, 'CoherentTwoWayCodeRangingModel'));
assert(~contains(forbiddenSource, 'TwoWayISLMeasurementBuilder'));

fprintf('test_constant_velocity_four_event_light_time_oracle: PASS\n');
end

function phaseCentre = phaseCentre_(position_m, velocity_mps)
phaseCentre = struct('positionAtReference_m', position_m, ...
    'velocity_mps', velocity_mps);
end

function endpoint = endpointA_(r0_m,v_mps,t0_s,txOffset_m,rxOffset_m, ...
        localReference_s,localRate)
endpoint = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'physicalTruth','spacecraft:A',r0_m,v_mps,t0_s, ...
    transmitPhaseCentreOffset_body_m=txOffset_m, ...
    receivePhaseCentreOffset_body_m=rxOffset_m, ...
    transmitTerminalIdentifier='A:tx',receiveTerminalIdentifier='A:rx', ...
    transmitAntennaIdentifier='A:tx-pc', ...
    receiveAntennaIdentifier='A:rx-pc', ...
    clockLocalTimeAtReference_s=localReference_s, ...
    localClockRate=localRate);
end

function hardware = hardware_(source, turnaroundProper_s)
hardware = revgnss.CoherentTwoWayCodeHardwareModel( ...
    parameterSource=source, physicalChainIdentifier='chain:A-B:validation', ...
    calibrationProductIdentifier='cal:A-B:validation:001', ...
    turnaroundProperTime_s=turnaroundProper_s, codeRateTurnaroundRatio=1);
end

function metadata = metadata_()
metadata = struct( ...
    'observationIdentifier', 'obs:A-B:oracle', ...
    'sessionIdentifier', 'session:A-B:oracle', ...
    'signalIdentifier', 'PN10', ...
    'covarianceGroupIdentifier', 'cov:A-B:oracle', ...
    'covarianceRowIndex', 1, 'covarianceBlock_m2', 0.01, ...
    'carrierToNoiseDensity_dBHz', 50, 'available', true, ...
    'qualityFlags', struct('codeLock',true), ...
    'truthDiagnosticIdentifier', 'truth:A-B:oracle');
end
