function beamformingPhasor(fid, cfg, summary, esc, plotPaths) %#ok<INUSL>
%BEAMFORMINGPHASOR  Coherent-beamforming phase budget of the estimated formation.
%
%   Answers "if these spacecraft transmitted coherently, what would the relative
%   position and clock error cost in gain". The answer is the phasor sum of the six
%   signals, so the section reports the array factor directly rather than only the
%   Ruze approximation of it.
%
%   Emits NOTHING unless summary.beamformingPhasor exists and is available, so
%   single-asset reports stay byte-identical to the golden .tex.

if ~isfield(summary,'beamformingPhasor'); return; end
bp = summary.beamformingPhasor;
if ~isstruct(bp) || ~isfield(bp,'available') || ~bp.available; return; end
if ~isfield(bp,'frequencies_Hz') || isempty(bp.frequencies_Hz); return; end
if nargin < 5 || ~isstruct(plotPaths); plotPaths = struct(); end

fprintf(fid, '\\section{Coherent Beamforming Phase Budget}\n\n');

fprintf(fid, ['Treats the estimated formation as a sparse transmit array focused on a ' ...
    'ground target and asks what the \\emph{relative} error costs in coherent gain. ' ...
    'For each spacecraft $i$ the residual path error toward the target $p$ is\n']);
fprintf(fid, ['\\begin{equation*}\n' ...
    'e_i = \\left(\\|p-\\hat{r}_i\\| - \\|p-r_i\\|\\right) + (\\hat{b}_i - b_i), ' ...
    '\\qquad \\psi_i = -\\frac{2\\pi e_i}{\\lambda}, \\qquad ' ...
    'AF = \\frac{1}{N}\\sum_i e^{j\\psi_i}\n' ...
    '\\end{equation*}\n']);
fprintf(fid, ['with the mean of $e_i$ removed, because a phase common to every element ' ...
    'is the beam''s overall phase and costs nothing. That mean-removal is precisely ' ...
    'why this section reads the \\emph{relative} layer and not the metre-level ' ...
    'absolute solution.\n\n']);

% --- geometry and regime -------------------------------------------------
fprintf(fid, '\\subsection*{Array geometry}\n\n');
fprintf(fid, '\\begin{tabular}{@{}lr@{}}\n\\toprule\n');
fprintf(fid, 'aperture extent $D$ (longest baseline) & %.1f m \\\\\n', bp.apertureExtent_m);
fprintf(fid, 'slant range $R$ to target & %.0f km \\\\\n', bp.slantRange_m/1000);
fprintf(fid, 'line-of-sight spread $D/R$ & %.2e rad \\\\\n', bp.losSpread_rad);
fprintf(fid, 'target placement & \\texttt{%s} \\\\\n', esc(bp.targetMode));
fprintf(fid, 'elements $N$ & %d \\\\\n', bp.nAssets);
fprintf(fid, '\\bottomrule\n\\end{tabular}\n\n');

if any(bp.nearField)
    fprintf(fid, ['\\noindent At the higher frequencies below the Fresnel distance ' ...
        '$2D^2/\\lambda$ exceeds the slant range, so the target lies in the ' ...
        '\\textbf{radiating near field} and the array must be \\emph{focused} on a ' ...
        'point rather than steered on a plane wave. Exact element-to-target ranges ' ...
        'are used throughout, so the numbers hold in either regime.\n\n']);
end

% --- error decomposition -------------------------------------------------
fprintf(fid, '\\subsection*{Where the phase error comes from}\n\n');
fprintf(fid, '\\begin{tabular}{@{}lr@{}}\n\\toprule\n');
fprintf(fid, 'total path error $\\sigma_e$ & %.4f m \\\\\n', bp.pathErrorRms_m);
fprintf(fid, '\\quad geometry contribution & %.4f m \\\\\n', bp.geometryPathErrorRms_m);
if bp.clockTermAvailable
    fprintf(fid, '\\quad clock contribution & %.4f m \\\\\n', bp.clockPathErrorRms_m);
else
    fprintf(fid, '\\quad clock contribution & \\multicolumn{1}{r}{not available} \\\\\n');
end
fprintf(fid, '\\midrule\n');
fprintf(fid, 'formation-shape term alone & %.4f m \\\\\n', bp.shapeOnlyPathErrorRms_m);
fprintf(fid, 'common translation $|d|$ & %.1f m \\\\\n', bp.commonOffset_m);
fprintf(fid, '\\quad leaked into differential path & %.4f m \\\\\n', bp.commonOffsetLeakRms_m);
fprintf(fid, '\\bottomrule\n\\end{tabular}\n\n');

fprintf(fid, ['\\noindent A common translation of the whole formation is free only in ' ...
    'the \\emph{far field}. Here the elements see the target along directions that ' ...
    'differ by $D/R = %.2e$ rad, so a common offset $|d|$ leaks differential path ' ...
    'error of order $|d|\\,D/R$. The two rows above separate that leak from genuine ' ...
    'formation-shape error, so a large common offset is not silently charged to shape.\n\n'], ...
    bp.losSpread_rad);

if ~bp.clockTermAvailable
    fprintf(fid, ['{\\footnotesize No per-spacecraft clock estimate was recoverable, so ' ...
        'the budget below counts geometry only and is therefore optimistic.}\n\n']);
end

% --- the phasor diagram itself -------------------------------------------
embedFigure_(fid, plotPaths, 'beamPhasor', ...
    ['Phasor addition of the individual signals, head to tail. The grey bar is the ' ...
     'ideal in-phase resultant of length $N$; the black arrow is the actual ' ...
     'resultant $\sum_i e^{j\psi_i}$. As $\lambda$ shrinks the chain curls and the ' ...
     'resultant collapses --- that collapse \emph{is} the gain loss.']);

% --- the loss table ------------------------------------------------------
fprintf(fid, '\\subsection*{Coherent gain loss}\n\n');
fprintf(fid, '\\begin{tabular}{@{}lrrrrr@{}}\n\\toprule\n');
fprintf(fid, ['frequency & $\\lambda$ [m] & $\\sigma_e/\\lambda$ & $|AF|$ & ' ...
    'loss [dB] & Ruze [dB] \\\\\n']);
fprintf(fid, '\\midrule\n');
for index = 1:numel(bp.frequencies_Hz)
    fprintf(fid, '%s & %.4f & %.3f & %.4f & %+.2f & %+.2f \\\\\n', ...
        frequencyLabel_(bp.frequencies_Hz(index)), ...
        bp.wavelengths_m(index), bp.sigmaOverLambda(index), ...
        bp.arrayFactorMagnitude(index), bp.coherentGainLoss_dB(index), ...
        bp.ruzeGainLoss_dB(index));
end
fprintf(fid, '\\bottomrule\n\\end{tabular}\n\n');

fprintf(fid, ['\\noindent The reported loss is the \\emph{exact} phasor sum. Ruze''s ' ...
    '$e^{-\\sigma_\\psi^2}$ is its small-error envelope and is quoted alongside only ' ...
    'for comparison: it is useful to roughly $\\sigma_\\psi<1$ rad and diverges to ' ...
    'meaningless values beyond, whereas the exact sum flattens onto the incoherent ' ...
    'floor at $10\\log_{10}(1/N) = %.2f$ dB.\n\n'], bp.incoherentFloor_dB);

if isfinite(bp.coherenceFrequency_Hz)
    fprintf(fid, ['\\noindent Taking $\\sigma_e = \\lambda/%.0f$ as the coherence ' ...
        'criterion, this formation solution supports a coherent beam up to ' ...
        '\\textbf{%s}.\n\n'], bp.coherenceCriterionLambdaFraction, ...
        frequencyLabel_(bp.coherenceFrequency_Hz));
end

% --- the honesty gate ----------------------------------------------------
switch bp.coherenceClaimStatus
    case 'claimable'
        fprintf(fid, ['\\noindent\\fbox{\\parbox{0.96\\linewidth}{\\textbf{Claim status: ' ...
            'supported.} %s}}\n\n'], esc(bp.coherenceClaimExplanation));
    otherwise
        fprintf(fid, ['\\noindent\\fbox{\\parbox{0.96\\linewidth}{\\textbf{Claim status: ' ...
            'NOT SUPPORTED (\\texttt{%s}).} %s\\\\[2pt] The loss figures above are ' ...
            'therefore a property of this particular run''s initial condition and ' ...
            'propagation, not a measured beamforming capability, and must not be ' ...
            'quoted as one.}}\n\n'], esc(bp.coherenceClaimStatus), ...
            esc(bp.coherenceClaimExplanation));
end

fprintf(fid, ['{\\footnotesize Provenance: %d physical range row(s) consumed across %d ' ...
    'link(s) against %d relative degrees of freedom; observability status ' ...
    '\\texttt{%s}.'], bp.physicalRangeRowsConsumed, bp.physicalRangeLinkCount, ...
    bp.relativePositionDof, esc(bp.rangeOnlyObservabilityStatus));
if isfinite(bp.formalToRealisedSigmaRatio)
    fprintf(fid, [' Realised relative error is %.1f$\\times$ the filter''s own ' ...
        '$\\sigma$.'], bp.formalToRealisedSigmaRatio);
end
fprintf(fid, '}\n\n');

embedFigure_(fid, plotPaths, 'beamLoss', ...
    ['Coherent gain loss against carrier frequency for this formation solution. The ' ...
     'exact phasor sum flattens onto the $1/N$ incoherent floor rather than ' ...
     'continuing downward as the Ruze approximation would.']);
embedFigure_(fid, plotPaths, 'beamPattern', ...
    ['Focused beam cut through the target, ideal against the estimated formation. ' ...
     'Phase error costs peak gain, shifts the pointing and lifts the sidelobes.']);
end

% ------------------------------------------------------------------
function embedFigure_(fid, plotPaths, field, caption)
% embedFigure_  Include a generated figure, or emit nothing if it was not produced.
if ~isfield(plotPaths, field) || isempty(plotPaths.(field)); return; end
figurePath = plotPaths.(field);
if ~isfile(figurePath); return; end
[~, name, extension] = fileparts(figurePath);
fprintf(fid, '\\begin{center}\\includegraphics[width=\\linewidth]{figures/%s}\\end{center}\n', ...
    [name extension]);
fprintf(fid, '{\\footnotesize %s}\n\n', caption);
end

% ------------------------------------------------------------------
function label = frequencyLabel_(frequency_Hz)
if frequency_Hz >= 1e9
    label = sprintf('%.2f GHz', frequency_Hz/1e9);
elseif frequency_Hz >= 1e6
    label = sprintf('%.1f MHz', frequency_Hz/1e6);
else
    label = sprintf('%.1f kHz', frequency_Hz/1e3);
end
end
