function measurementValidation(fid, plotPaths, stem, figDir)
%MEASUREMENTVALIDATION  "Measurement and Geometry Validation" report section (Phase 7).
%   Extracted verbatim from ClockExactReportBuilder.writeMeasurementValidation_ as part
%   of the C-9 report decomposition. Read-only: consumes only the precomputed plotPaths
%   + figure dir and the (now-public) ClockExactReportBuilder formatting toolkit. The
%   emitted LaTeX is byte-identical to the original method (verified by the normalized
%   .tex diff harness, tests/report/reportTexFingerprint.m).
    CE = revgnss.ClockExactReportBuilder;
    fprintf(fid, '\\section{Measurement and Geometry Validation}\n');
    fprintf(fid, ['Pre-fit residuals test the predicted measurement model before correction. ' ...
        'Post-fit residuals show how much error remains after the EKF update. ' ...
        'RMS residuals are useful diagnostics, but they are not by themselves a proof ' ...
        'of statistical consistency. ' ...
        'In deterministic or partly deterministic validation runs, NIS should be interpreted ' ...
        'as a numerical conditioning and model-coupling diagnostic.\n\n']);
    fprintf(fid, CE.plotTableHeader_());

    CE.writeRow_(fid, CE.figRef_(plotPaths,'innovRMS',figDir,stem), ...
        'Pseudorange Pre-Fit and Post-Fit Residual RMS', ...
        ['The pre-fit innovation (before EKF correction) and post-fit residual (after update) ' ...
         'are plotted separately. With noise disabled this is a deterministic geometry, ' ...
         'clock-state coupling, and estimator convergence diagnostic.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'perSrc',figDir,stem), ...
        'Error Source Contributions', ...
        ['Breakdown of the raw code error into physical contributions: ' ...
         'code (geometric and clock residual), troposphere truth-model mismatch, ' ...
         'ionosphere truth-model mismatch.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'visTowers',figDir,stem), ...
        'Tower Rows Used by the EKF', ...
        ['The number of ground towers passing the elevation mask at each epoch. ' ...
         'Elevation mask applied per-tower before including in the EKF update.']);

    CE.writeRow_(fid, '', ...
        'Measurement Covariance Contribution', ...
        ['Per-row root-variance contributions represented in the measurement covariance. ' ...
         'Receiver tracking noise, atmospheric residual, and tower-clock contributions ' ...
         'are kept separate. No plot generated in this oo\_v1 run.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'dop',figDir,stem), ...
        'Ground-to-Space Geometry (DOP Metrics)', ...
        ['GDOP, PDOP, TDOP are geometry-derived scaling factors computed from the ' ...
         'pseudorange observation matrix. Lower DOP values indicate better geometric diversity. ' ...
         'Tower network DOP near 1--2 is typical for GEO coverage.']);

    fprintf(fid, CE.plotTableFooter_());
    fprintf(fid, '\\clearpage\n');
end
