function measurementValidation(fid, plotPaths, stem, figDir, diag)
%MEASUREMENTVALIDATION  "Measurement and Geometry Validation" report section.
%   Extracted verbatim from ClockExactReportBuilder.writeMeasurementValidation_ as part
%   of the C-9 report decomposition. Read-only: consumes only the precomputed plotPaths
%   + figure dir and the (now-public) ClockExactReportBuilder formatting toolkit. The
%   emitted LaTeX is byte-identical to the original method (verified by the normalized
%   .tex diff harness, tests/report/reportTexFingerprint.m).
    CE = revgnss.ClockExactReportBuilder;
    fprintf(fid, '\\section{Measurement and Geometry Validation}\n');
    fprintf(fid, ['Pre-fit residuals test the predicted measurement model before correction. ' ...
        'Post-fit residuals show how much error remains after the EKF update. ' ...
        'RMS residuals are useful diagnostics, but they are not by themselves a proof ' ...
        'of statistical consistency. ' ...
        'In deterministic or partly deterministic validation runs, NIS should be interpreted ' ...
        'as a numerical conditioning and model-coupling diagnostic.\n\n']);
    fprintf(fid, CE.plotTableHeader_());

    CE.writeRow_(fid, CE.figRef_(plotPaths,'innovRMS',figDir,stem), ...
        'Pseudorange Pre-Fit and Post-Fit Residual RMS', ...
        ['The pre-fit innovation (before EKF correction) and post-fit residual (after update) ' ...
         'are plotted separately. With noise disabled this is a deterministic geometry, ' ...
         'clock-state coupling, and estimator convergence diagnostic.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'perSrc',figDir,stem), ...
        'Error Source Contributions', ...
        ['Breakdown of the raw code error into physical contributions: ' ...
         'code (geometric and clock residual), troposphere truth-model mismatch, ' ...
         'ionosphere truth-model mismatch.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'visTowers',figDir,stem), ...
        'Tower Rows Used by the EKF', ...
        ['The number of ground towers passing the elevation mask at each epoch. ' ...
         'Elevation mask applied per-tower before including in the EKF update.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'dop',figDir,stem), ...
        'Ground-to-Space Geometry (DOP Metrics)', ...
        ['GDOP and PDOP are geometry-derived scaling factors from the pseudorange observation ' ...
         'matrix; lower is better. For a single GEO viewing a compact cluster of ground ' ...
         'transmitters the lines of sight are nearly parallel, so the DOP is very large ' ...
         '(hundreds to thousands) and almost constant --- the curves appear as two flat lines. ' ...
         'The geometry is observable (full rank) but weak.']);

    fprintf(fid, CE.plotTableFooter_());

    % Ground-to-space geometry / DOP metrics table (always present).
    fprintf(fid, '\\subsection{Ground-to-Space Geometry and DOP Metrics}\n');
    fprintf(fid, ['Dilution-of-precision factors scale measurement noise into state uncertainty ' ...
        '(lower is better). Values are run medians computed from the pseudorange observation ' ...
        'geometry in the ECEF line-of-sight frame. This chapter is always shown, independent of ' ...
        'any pass/fail gate. A single GEO viewing a compact cluster of ground transmitters sees ' ...
        'nearly parallel lines of sight, so the DOP values are large (hundreds to thousands) and ' ...
        'nearly constant: the geometry is observable (full rank) but weak.\n\n']);
    vt = 'not available'; gd = 'not available'; pd = 'not available';
    try; v = diag.getNumVisibleTowers(); v = v(isfinite(v)); if ~isempty(v); vt = sprintf('%.1f', median(v)); end; catch; end
    try; g = diag.getGDOPLike();        g = g(isfinite(g)); if ~isempty(g); gd = sprintf('%.2f', median(g)); end; catch; end
    try; p = diag.getPDOPLike();        p = p(isfinite(p)); if ~isempty(p); pd = sprintf('%.2f', median(p)); end; catch; end
    fprintf(fid, '\\begin{center}\\small\n');
    fprintf(fid, '\\begin{tabular}{p{0.52\\textwidth}p{0.38\\textwidth}}\n\\toprule\n');
    fprintf(fid, '\\textbf{Geometry metric} & \\textbf{Value (run median)}\\\\\n\\midrule\n');
    fprintf(fid, 'Visible ground transmitters & %s\\\\\n', vt);
    fprintf(fid, 'GDOP (geometric) & %s\\\\\n', gd);
    fprintf(fid, 'PDOP (position) & %s\\\\\n', pd);
    fprintf(fid, 'HDOP / VDOP / condition number & not available\\\\\n');
    fprintf(fid, 'Geometry convention & ECEF line-of-sight; per-tower elevation mask applied\\\\\n');
    fprintf(fid, '\\bottomrule\n\\end{tabular}\n\\end{center}\n\n');
    fprintf(fid, '\\clearpage\n');
end
