function oscillatorValidation(fid, plotPaths, stem, figDir, cfg)
%OSCILLATORVALIDATION  "Oscillator Stability Validation" report section.
%   Emits oscillator validation rows. The compact mode keeps only Allan deviation.
    CE = revgnss.ClockExactReportBuilder;
    clkMode = CE.getCfgStr_(cfg, {'estimator','towerClockMode'}, 'perfectTruth');
    mode = CE.getCfgStr_(cfg, {'report','oscillatorValidationMode'}, 'full');
    allanOnly = strcmpi(mode, 'allanOnly');
    fprintf(fid, '\\section{Oscillator Stability Validation}\n');
    fprintf(fid, CE.plotTableHeader_());

    CE.writeRow_(fid, CE.figRef_(plotPaths,'allanDev',figDir,stem), ...
        'Oscillator Stability: Overlapping Allan Deviation', ...
        ['Overlapping ADEV $\sigma_y(\tau)$ computed from truth clock-bias time series. ' ...
         'Black: asset receiver clock (Brown-Hwang two-state model). ' ...
         'Coloured: tower transmitter clocks (stochastic). ' ...
         'Slope $-0.5$ indicates white frequency noise; slope $+0.5$ indicates ' ...
         'random-walk frequency; flat region indicates frequency flicker. ' ...
         'No laboratory-grade calibration; synthetic oscillator parameters only.']);

    if ~allanOnly
        CE.writeRow_(fid, CE.figRef_(plotPaths,'clkErr',figDir,stem), ...
            'Receiver Clock Bias Tracking', ...
            ['Spacecraft receiver clock bias estimation error. ' ...
             'Receiver clock sign is POSITIVE (adds to pseudorange). ' ...
             'The clock bias converges as pseudorange innovations correct the clock state.']);

        CE.writeRow_(fid, CE.figRef_(plotPaths,'clkDrift',figDir,stem), ...
            'Clock Drift / Fractional Frequency', ...
            ['Clock drift state (m/s equivalent). Brown-Hwang two-state model. ' ...
             'Fractional frequency deviation = drift / c.']);

        CE.writeRow_(fid, CE.figRef_(plotPaths,'twrClocks',figDir,stem), ...
            'Tower Clock Product Validation', ...
            ['Bar chart of per-tower clock truth bias at the final epoch. ' ...
             sprintf('Tower clock model: %s. ', CE.esc_(revgnss.ReportLabel.humanize(clkMode))) ...
             'Tower clock sign is NEGATIVE in the pseudorange model. ' ...
             'Zero bar means truth and model clock agree.']);
    end

    fprintf(fid, CE.plotTableFooter_());
    fprintf(fid, '\\clearpage\n');
end
