function perReceiverDiagnostics(fid, plotPaths, stem, figDir, nRx)
%PERRECEIVERDIAGNOSTICS  "Per-Receiver Measurement Diagnostics" report section.
%   Extracted verbatim from ClockExactReportBuilder.writePerReceiverDiagnostics_ as part
%   of the C-9 report decomposition. Read-only: consumes only the precomputed plotPaths
%   + figure dir and the (now-public) ClockExactReportBuilder formatting toolkit. The
%   emitted LaTeX is byte-identical to the original method (verified by the normalized
%   .tex diff harness, tests/report/reportTexFingerprint.m).
    CE = revgnss.ClockExactReportBuilder;
    fprintf(fid, '\\section{Per-Receiver Measurement Diagnostics}\n');
    fprintf(fid, ['Receiver rows are generated from the enabled RX phase centres ' ...
        'mounted on the SpaceAsset. This run has %d receiver phase centre(s). ' ...
        'Receiver clock, hardware delays, and attitude-derived antenna offsets ' ...
        'are included in the pseudorange model.\n\n'], nRx);
    fprintf(fid, CE.plotTableHeader_());

    CE.writeRow_(fid, '', ...
        'Per-Receiver Pre-Fit Pseudorange Residual RMS', ...
        ['Each curve is the tower-wise RMS pre-fit pseudorange residual for one receiver ' ...
         'element. No separate per-receiver diagnostic plot available in this oo\_v1 run.']);

    CE.writeRow_(fid, '', ...
        'Per-Receiver Post-Fit Pseudorange Residual RMS', ...
        ['Each curve is the tower-wise RMS post-fit pseudorange residual after the EKF update. ' ...
         'No separate per-receiver diagnostic plot available in this oo\_v1 run.']);

    CE.writeRow_(fid, '', ...
        'Per-Receiver Per-Tower Residual Heatmaps', ...
        ['Residuals by receiver and tower. ' ...
         'Blank samples are non-visible or unused tower/receiver links. ' ...
         'Not available in this oo\_v1 run.']);

    CE.writeRow_(fid, '', ...
        'Per-Receiver Pseudorange-Minus-Geometric Range', ...
        ['Pseudorange excess over geometric range per receiver. Contains clock terms. ' ...
         'Not available as a standalone diagnostic in this oo\_v1 run.']);

    fprintf(fid, CE.plotTableFooter_());
    fprintf(fid, '\\clearpage\n');
end
