function relativeFormationPairs(fid, cfg, summary, esc) %#ok<INUSL>
%RELATIVEFORMATIONPAIRS  Per-pair relative position error, every satellite pair.
%
%   Answers "how big is the error WITHIN the swarm", as opposed to each spacecraft's
%   error against the Earth. Emits one row per pair -- N*(N-1)/2 rows -- not only the
%   N-1 pairs that contain the reference asset.
%
%   Emits NOTHING unless summary.pairwiseRelativePositionError exists and is
%   available, so single-asset reports stay byte-identical to the golden .tex.

if ~isfield(summary,'pairwiseRelativePositionError'); return; end
pp = summary.pairwiseRelativePositionError;
if ~isstruct(pp) || ~isfield(pp,'available') || ~pp.available; return; end
if ~isfield(pp,'nPairs') || pp.nPairs < 1; return; end

fprintf(fid, '\\section{Inter-Satellite Relative Position Error (every pair)}\n\n');

fprintf(fid, ['Relative accuracy \\emph{inside} the formation, independent of where the ' ...
    'formation sits relative to the Earth. For each pair $(i,j)$:\n\n']);
fprintf(fid, '\\begin{itemize}\n');
fprintf(fid, ['\\item \\textbf{Relative position error} (columns 3--5) is the ' ...
    '\\emph{vector} error of the $i\\!\\to\\!j$ baseline, ' ...
    '$\\|(\\hat{r}_i-\\hat{r}_j)-(r_i-r_j)\\|$. It counts error in the ' ...
    'baseline \\emph{direction} as well as its length.\n']);
fprintf(fid, ['\\item \\textbf{Length error} (last column) is the \\emph{signed scalar} ' ...
    '$\\|\\hat{r}_i-\\hat{r}_j\\|-\\| r_i-r_j\\|$. A range observable ' ...
    'measures this component directly and is blind to error perpendicular to the ' ...
    'baseline, so it is always the smaller and more flattering of the two.\n']);
fprintf(fid, '\\end{itemize}\n\n');
fprintf(fid, ['Both are invariant to a common translation of the whole formation: a pair ' ...
    'whose two spacecraft share a common-mode position error reads small here by ' ...
    'construction. That is the intended behaviour of a swarm-internal metric.\n\n']);

fprintf(fid, ['{\\footnotesize Source: \\texttt{%s}. Grid: \\texttt{%s}, %d epochs. ' ...
    'Tail window: last %.0f\\%%. $\\sigma$ (series): \\texttt{%s}. ' ...
    '$\\sigma$ (final): \\texttt{%s}.}\n\n'], ...
    esc(pp.source), esc(pp.gridDescription), numel(pp.time_s), ...
    100*pp.tailFraction, esc(pp.sigmaSeriesSource), esc(pp.finalSigmaSource));

% The header must be emitted as a FORMAT string, never via '%s'. MATLAB does not
% process escapes in single-quoted literals -- only fprintf's format argument is
% escape-processed -- so passing it as an argument would put literal "\\" and "\n"
% characters into the .tex and pdflatex would reject the document.
fprintf(fid, '\\begin{longtable}{@{}lrrrrrr@{}}\n');
fprintf(fid, '\\toprule\n');
writePairTableHeader_(fid);
fprintf(fid, '\\midrule \\endfirsthead\n');
fprintf(fid, '\\multicolumn{7}{@{}l}{\\footnotesize (continued)}\\\\ \\toprule\n');
writePairTableHeader_(fid);
fprintf(fid, '\\midrule \\endhead\n');
fprintf(fid, '\\bottomrule \\endfoot\n');

for pairIndex = 1:pp.nPairs
    label = esc(pp.pairLabels{pairIndex});
    if pp.pairIslLinked(pairIndex); label = [label '$^{\ast}$']; end %#ok<AGROW>
    if pairIndex == pp.worstPairRow; label = ['\textbf{' label '}']; end %#ok<AGROW>
    sigmaCell = '\multicolumn{1}{c}{--}';
    if pp.finalSigmaAvailable(pairIndex) && ...
            isfinite(pp.finalRelativePositionSigma3d_m(pairIndex))
        sigmaCell = sprintf('%.3f', pp.finalRelativePositionSigma3d_m(pairIndex));
    end
    fprintf(fid, '%s & %.3f & %.3f & %.3f & %.3f & %s & %+.3f \\\\\n', ...
        label, ...
        pp.finalTruthBaselineLength_m(pairIndex)/1000, ...
        pp.finalRelativePositionError_m(pairIndex), ...
        pp.tailRmsRelativePositionError_m(pairIndex), ...
        pp.tailMaxRelativePositionError_m(pairIndex), ...
        sigmaCell, ...
        pp.finalBaselineLengthError_m(pairIndex));
end
fprintf(fid, '\\end{longtable}\n\n');

fprintf(fid, ['\\noindent Worst pair (tail RMS): \\textbf{%s} at %.4f m. ' ...
    'All-pair tail RMS: %.4f m.\n\n'], ...
    esc(pp.worstPairLabel), pp.worstPairTailRms_m, ...
    sqrt(mean(pp.tailRmsRelativePositionError_m.^2,'omitnan')));

if any(pp.pairIslLinked)
    fprintf(fid, ['{\\footnotesize $^{\\ast}$ An inter-satellite link directly ' ...
        'constrained this pair (\\texttt{%s}). Unmarked pairs are constrained only ' ...
        'indirectly, through the estimator.}\n\n'], esc(pp.pairIslLinkSource));
end

switch pp.finalSigmaSource
    case 'jointEkfExactCrossCovariance'
        fprintf(fid, ['{\\footnotesize $\\sigma_{3D}=\\sqrt{\\operatorname{tr}' ...
            '(P_{ii}+P_{jj}-P_{ij}-P_{ij}^{\\top})}$ at the final epoch, taken from ' ...
            'the estimator''s own cross-covariance. A per-epoch $\\sigma$ series ' ...
            'exists only for pairs containing the reference asset -- the filter does ' ...
            'not retain the relative covariance of the other pairs, so those are ' ...
            'honestly blank rather than approximated.}\n\n']);
    case 'none'
        fprintf(fid, ['{\\footnotesize No per-pair relative covariance is available ' ...
            'on this architecture, so no $\\sigma$ is claimed.}\n\n']);
end
end

% ------------------------------------------------------------------
function writePairTableHeader_(fid)
fprintf(fid, ['pair & truth sep. [km] & rel-pos final [m] & tail RMS [m] & ' ...
    'tail max [m] & $\\sigma_{3D}$ [m] & length err [m] \\\\\n']);
end
