function scenarioSummary(fid, cfg, summary, diag, nTwr, nRx, dur, dt, esc)
%SCENARIOSUMMARY  "Scenario Summary" report section (Phase 7).
%   Extracted verbatim from ClockExactReportBuilder.writeScenarioSummary_ as part
%   of the C-9 report decomposition. Read-only: consumes only the precomputed plotPaths
%   + figure dir and the (now-public) ClockExactReportBuilder formatting toolkit. The
%   emitted LaTeX is byte-identical to the original method (verified by the normalized
%   .tex diff harness, tests/report/reportTexFingerprint.m).
%   NOTE: writeComponentRows_ is intentionally NOT extracted (left as a public
%   method on ClockExactReportBuilder) and is invoked below via CE.writeComponentRows_.
    CE = revgnss.ClockExactReportBuilder;

    scenarioName = CE.getCfgStr_(cfg, {'asset','name'}, 'GEO-1');
    codeMode = CE.getCfgStr_(cfg, {'measurements','codeMode'},   'singleFrequency');
    carrMode = CE.getCfgStr_(cfg, {'measurements','carrierMode'}, 'diagnostic');
    clkMode  = CE.getCfgStr_(cfg, {'estimator','towerClockMode'}, 'perfectTruth');
    testLine = revgnss.ReportStatus.summaryLines();
    if isempty(testLine); testLine = {'Test status: see tests/ folder.'}; end
    testStr  = testLine{1};

    fprintf(fid, '\\section{Scenario Summary}\n');
    fprintf(fid, ['This report documents a reverse-GNSS simulation run using the oo\\_v1 ' ...
        'MATLAB simulator. ' ...
        'The ground segment transmits reverse-GNSS code, Doppler, and carrier observables to a GEO space receiver when enabled. ' ...
        'The EKF estimates spacecraft position, velocity, attitude, and receiver clock states ' ...
        'from the available observables. ' ...
        'The run length is %.2f hours (%.0f s) with %.1f s sampling and %d ground towers, ' ...
        '%d receiver phase centre(s). ' ...
        'Code mode: \\texttt{%s}. Carrier mode: \\texttt{%s}. ' ...
        'Tower clock mode: \\texttt{%s}. ' ...
        '%s\n\n'], ...
        dur/3600, dur, dt, nTwr, nRx, esc(codeMode), esc(carrMode), esc(clkMode), ...
        esc(testStr));

    % 1.1 Receiver Clock Architecture
    fprintf(fid, '\\subsection{Receiver Clock Architecture Interpretation}\n');
    fprintf(fid, ['Receiver clock bias $b_{rx}$ has a \\textbf{positive} sign ' ...
        '(adds to pseudorange). ' ...
        'Tower transmitter clock bias $b_{twr}$ has a \\textbf{negative} sign ' ...
        '(subtracts from pseudorange). ' ...
        'Troposphere delay $T$ is \\textbf{positive} for both code and carrier. ' ...
        'Ionosphere delay $I_f$ is \\textbf{positive} for code (group delay) and ' ...
        '\\textbf{negative} for carrier (phase advance). ' ...
        'Carrier ambiguity $B_\\phi$ is a float value in metres (raw L1, no integer fixing).\n\n']);
    % Clock mode / gauge summary (Stage 9: per-mode scientific narrative)
    clockMd1  = CE.getCfgStr_(cfg, {'clock','mode'}, 'spacecraftReceiverClockOnly');
    gaugeMd1  = CE.getCfgStr_(cfg, {'clock','gauge','mode'}, 'externalTowerCorrections');
    refTwr1   = CE.getCfgNum_(cfg, {'clock','gauge','referenceTowerIndex'}, 1);
    sigBias1  = CE.getCfgNum_(cfg, {'clock','gauge','sigmaBias_m'},    1e-6);
    sigDrift1 = CE.getCfgNum_(cfg, {'clock','gauge','sigmaDrift_mps'}, 1e-9);
    fprintf(fid, ['\\textbf{Clock architecture:} \\texttt{%s}. ' ...
        '\\textbf{Clock gauge:} \\texttt{%s}.\n\n'], esc(clockMd1), esc(gaugeMd1));
    if strcmp(clockMd1,'spacecraftReceiverClockOnly')
        fprintf(fid, ['Tower clock states are not included in the EKF. ' ...
            'The EKF estimates the spacecraft receiver clock only. ' ...
            'One-way pseudorange is gauge-ambiguous: $b_{rx}$ and $b_{twr}$ cannot be ' ...
            'separated without an external datum or gauge constraint; here the gauge ' ...
            'is resolved by external tower clock corrections.\n\n']);
    elseif strcmp(gaugeMd1,'fixReferenceTower')
        fprintf(fid, ['\\textbf{Gauge -- fixReferenceTower (tower %d):} ' ...
            'The selected reference tower defines the ground clock gauge. ' ...
            'Its tower clock bias and drift are constrained to zero by EKF ' ...
            'pseudo-measurement rows ($\\sigma_{bias}=%g$\\,m, ' ...
            '$\\sigma_{drift}=%g$\\,m/s). ' ...
            'All receiver and tower clock estimates are therefore relative to ' ...
            'this tower timescale. ' ...
            'Pseudo-measurement: $z=0$, $h=\\hat{b}_{twr,ref}$, ' ...
            '$H_{gauge}(b_{twr,ref})=1$, $R_{gauge}=\\sigma_{bias}^2$.\n\n'], ...
            refTwr1, sigBias1, sigDrift1);
    elseif strcmp(gaugeMd1,'meanGroundClockGauge')
        fprintf(fid, ['\\textbf{Gauge -- meanGroundClockGauge:} ' ...
            'The mean of all estimated tower clocks defines the ground clock gauge. ' ...
            'The EKF inserts zero-mean pseudo-measurement rows for tower clock bias ' ...
            '($\\sigma_{bias}=%g$\\,m) and drift ($\\sigma_{drift}=%g$\\,m/s). ' ...
            'The spacecraft receiver clock is therefore estimated relative to the ' ...
            'mean ground-clock timescale. ' ...
            'Pseudo-measurement: $z=0$, $h=\\frac{1}{N}\\sum_i \\hat{b}_{twr,i}$, ' ...
            '$H_{gauge}(b_{twr,i})=\\frac{1}{N}$, $R_{gauge}=\\sigma_{bias}^2$.\n\n'], ...
            sigBias1, sigDrift1);
    else
        fprintf(fid, ['One-way pseudorange is gauge-ambiguous: $b_{rx}$ and $b_{twr}$ ' ...
            'cannot be separated without an external datum or gauge constraint. ' ...
            'The gauge mode specifies how this datum ambiguity is resolved.\n\n']);
    end

    % 1.2 Scenario Geometry
    fprintf(fid, '\\subsection{Scenario Geometry and Receiver Architecture}\n');
    fprintf(fid, ['Truth pseudorange: ' ...
        '$P = \\|\\mathbf{r}_{sc} + \\mathbf{C}_{BI}\\mathbf{l}_{a,B} - \\mathbf{r}_{twr}\\|' ...
        '+ b_{rx}^{true} - b_{twr}^{true} + d_{truth} + \\nu$. ' ...
        'Estimator prediction: $\\hat{P} = \\|\\hat{\\mathbf{r}}_{sc} + \\hat{\\mathbf{C}}_{BI}' ...
        '\\mathbf{l}_{a,B} - \\mathbf{r}_{twr}\\| + \\hat{b}_{rx} + d_{model}$. ' ...
        'Range geometry uses ECEF positions at the receiver epoch. ' ...
        'Optional light-time and Sagnac corrections are applied when enabled.\n\n']);

    % 1.3 EKF State Vector
    fprintf(fid, '\\subsection{EKF State Vector}\n');
    fprintf(fid, ['The filter is an error-state EKF. The 14 base states are: ' ...
        'position (3), velocity (3), attitude error (3), angular rate (3), ' ...
        'receiver clock bias (1), receiver clock drift (1).\n\n']);
    fprintf(fid, '\\begin{center}\n\\scriptsize\n');
    fprintf(fid, ['\\begin{longtable}{@{}>{\\raggedright\\arraybackslash}p{0.055\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.175\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.295\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.070\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.270\\textwidth}@{}}\n']);
    fprintf(fid, '\\toprule\n');
    fprintf(fid, '\\textbf{Index} & \\textbf{Symbol} & \\textbf{Description} & \\textbf{Unit} & \\textbf{DynamicCouplingNote}\\\\\n');
    fprintf(fid, '\\midrule\n');
    stRows = { ...
        '1','$\delta r_{E,x}$','ECEF X position','m','Coupled to velocity'; ...
        '2','$\delta r_{E,y}$','ECEF Y position','m','Coupled to velocity'; ...
        '3','$\delta r_{E,z}$','ECEF Z position','m','Coupled to velocity'; ...
        '4','$\delta v_{E,x}$','ECEF X velocity','m/s','Affects future position'; ...
        '5','$\delta v_{E,y}$','ECEF Y velocity','m/s','Affects future position'; ...
        '6','$\delta v_{E,z}$','ECEF Z velocity','m/s','Affects future position'; ...
        '7','$\delta\theta_{B,x}$','Body attitude error x','rad','Observable via lever arms'; ...
        '8','$\delta\theta_{B,y}$','Body attitude error y','rad','Observable via lever arms'; ...
        '9','$\delta\theta_{B,z}$','Body attitude error z','rad','Observable via lever arms'; ...
        '10','$\delta\omega_{B,x}$','Body angular rate x','rad/s','Affects future attitude'; ...
        '11','$\delta\omega_{B,y}$','Body angular rate y','rad/s','Affects future attitude'; ...
        '12','$\delta\omega_{B,z}$','Body angular rate z','rad/s','Affects future attitude'; ...
        '13','$\delta b_{rx}$','RX clock bias (POSITIVE sign)','m','Directly estimated'; ...
        '14','$\delta\dot{b}_{rx}$','RX clock drift','m/s','Propagates to clock bias'; ...
    };
    for k = 1:size(stRows,1)
        fprintf(fid, '%s & %s & %s & %s & %s\\\\\n', stRows{k,:});
    end
    % Extended states
    doTwrClk = isfield(cfg,'estimator') && isfield(cfg.estimator,'estimateTowerClocks') ...
        && cfg.estimator.estimateTowerClocks;
    doAmb = isfield(cfg,'measurements') && isfield(cfg.measurements,'carrierMode') ...
        && strcmp(cfg.measurements.carrierMode,'ekfFloat');
    ambMode = CE.getCfgStr_(cfg, {'estimation','ambiguityMode'}, 'none');
    doZwd = isfield(cfg,'estimation') && isfield(cfg.estimation,'troposphereMode') ...
        && strcmp(cfg.estimation.troposphereMode,'perTowerZwd');
    idx = 15;
    if doTwrClk
        for k = 1:nTwr
            fprintf(fid, '%d & $\\delta b_{\\mathrm{twr},%d}$ & Tower %d clock bias (NEGATIVE sign in meas.) & m & Estimated tower bias\\\\\n', idx, k, k);
            idx = idx+1;
            fprintf(fid, '%d & $\\delta\\dot{b}_{\\mathrm{twr},%d}$ & Tower %d clock drift & m/s & Estimated tower drift\\\\\n', idx, k, k);
            idx = idx+1;
        end
    end
    if doAmb
        if strcmp(ambMode,'floatPerTowerReceiverSignal')
            for k = 1:nTwr
                for ri = 1:nRx
                    fprintf(fid, '%d & $B_{\\phi,L1,t%d,r%d}$ & L1 carrier float ambiguity, tower %d receiver %d & m & Receiver-indexed float state; no integer fixing\\\\\n', ...
                        idx, k, ri, k, ri);
                    idx = idx+1;
                end
            end
        else
            for k = 1:nTwr
                fprintf(fid, '%d & $B_{\\phi,L1,t%d}$ & L1 carrier float ambiguity, tower %d & m & Tower/signal float state; no integer fixing\\\\\n', idx, k, k);
                idx = idx+1;
            end
        end
    end
    if doZwd
        for k = 1:nTwr
            fprintf(fid, '%d & $\\mathrm{ZWD}_{\\mathrm{twr}%d}$ & Zenith wet delay, tower %d & m & Gauss-Markov; mapped by $m_w(\\mathrm{el})$\\\\\n', idx, k, k);
            idx = idx+1; %#ok<NASGU>
        end
    end
    fprintf(fid, '\\bottomrule\n\\end{longtable}\n\\normalsize\n\\end{center}\n');

    % 1.4 Measurement Model
    fprintf(fid, '\\subsection{Pseudorange Measurement Model and Observation Matrix}\n');
    % Stage 78: use SignalDefinition; no hardcoded frequency constants in builder.
    sd78_L1_ = revgnss.SignalDefinition.get('L1');
    sd78_L2_ = revgnss.SignalDefinition.get('L2');
    f1 = sd78_L1_.frequency_Hz;
    f2 = sd78_L2_.frequency_Hz;
    alpha =  f1^2 / (f1^2 - f2^2);
    beta  = -f2^2 / (f1^2 - f2^2);
    fprintf(fid, ['\\[\nP_f = \\rho + b_{rx} - b_{twr} + T + I_f + d_{\\rm code} + \\nu_P,' ...
        '\\quad I_f \\geq 0 \\;(\\text{positive for code})\n\\]\n']);
    fprintf(fid, ['\\[\n\\Phi_f = \\rho + b_{rx} - b_{twr} + T - I_f + B_\\phi + d_{\\rm phase} + \\nu_\\Phi,' ...
        '\\quad -I_f \\;(\\text{negative for carrier})\n\\]\n']);
    fprintf(fid, '\\[\\quad B_\\phi \\text{ is float ambiguity in metres (L1 only, no integer fixing)}\\]\n');
    fprintf(fid, ['\\[\nP_{\\rm IF} = \\alpha P_{L1} + \\beta P_{L2},' ...
        '\\quad \\alpha = %.6f,\\quad \\beta = %.6f\n\\]\n'], alpha, beta);

    fprintf(fid, '\\begin{center}\n\\scriptsize\n');
    fprintf(fid, ['\\begin{longtable}{@{}>{\\raggedright\\arraybackslash}p{0.273\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.273\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.273\\textwidth}@{}}\n']);
    fprintf(fid, '\\toprule\n');
    fprintf(fid, '\\textbf{Term} & \\textbf{Expression} & \\textbf{Meaning}\\\\\n');
    fprintf(fid, '\\midrule\n');
    termRows = { ...
        'geometric range', '$\rho = \|\mathbf{r}_{sc} + \mathbf{C}_{BI}\mathbf{l}_{a,B} - \mathbf{r}_{twr}\|$', 'Phase-centre to tower range'; ...
        'receiver clock', '$+b_{rx}$ [m] (POSITIVE sign)', 'Shared spacecraft RX clock bias'; ...
        'tower clock', '$-b_{twr}$ [m] (NEGATIVE sign)', 'Ground transmitter clock bias'; ...
        'troposphere', '$+T$ (code and carrier, POSITIVE)', 'Slant wet+dry delay, same sign'; ...
        'iono code', '$+I_f$ (POSITIVE for code)', 'First-order group delay'; ...
        'iono carrier', '$-I_f$ (NEGATIVE for carrier)', 'First-order phase advance'; ...
        'float ambiguity', '$+B_\phi$ [m] (L1 only)', 'L1 carrier cycle ambiguity, float'; ...
        'measurement noise', '$\nu \sim N(0, R)$', 'Code / carrier / Doppler noise'; ...
    };
    for k = 1:size(termRows,1)
        fprintf(fid, '%s & %s & %s\\\\\n', termRows{k,:});
    end
    fprintf(fid, '\\bottomrule\n\\end{longtable}\n\\normalsize\n\\end{center}\n');

    % 1.5 Starting positions
    fprintf(fid, '\\subsection{Starting Positions}\n');
    fprintf(fid, '\\begin{center}\n\\scriptsize\n');
    fprintf(fid, ['\\begin{longtable}{@{}>{\\raggedright\\arraybackslash}p{0.12\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.14\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.17\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.15\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.15\\textwidth}' ...
        '>{\\raggedright\\arraybackslash}p{0.12\\textwidth}@{}}\n']);
    fprintf(fid, '\\toprule\n');
    fprintf(fid, '\\textbf{Type} & \\textbf{Name} & \\textbf{Frame} & \\textbf{Coord 1} & \\textbf{Coord 2} & \\textbf{Coord 3}\\\\\n');
    fprintf(fid, '\\midrule\n');
    % Asset
    rGeo = zeros(3,1);
    try; rGeo = cfg.asset.r_ecef_m; catch; end
    fprintf(fid, 'SpaceAsset & %s & ECEF center of mass & X %.5g m & Y %.5g m & Z %.5g m\\\\\n', ...
        esc(scenarioName), rGeo(1), rGeo(2), rGeo(3));
    % Towers
    if isfield(cfg,'towers')
        nT = min(nTwr, numel(cfg.towers));
        for k = 1:nT
            tname = ''; lat_d = 0; lon_d = 0; alt_m = 0;
            try; tname = cfg.towers(k).name; catch; end
            try; lat_d = cfg.towers(k).lat_rad * 180/pi; catch; end
            try; lon_d = cfg.towers(k).lon_rad * 180/pi; catch; end
            try; alt_m = cfg.towers(k).alt_m; catch; end
            fprintf(fid, 'Tower & %s & Fixed geodetic & Lat %.2f deg & Lon %.2f deg & Alt %.1f m\\\\\n', ...
                esc(tname), lat_d, lon_d, alt_m);
        end
    end
    fprintf(fid, '\\bottomrule\n\\end{longtable}\n\\normalsize\n\\end{center}\n');

    % 1.6 Component Status — compact grouped multi-tables (5 categories)
    CE.writeComponentRows_(fid, cfg, esc);
    fprintf(fid, '\\clearpage\n');
end
