function stateEstimation(fid, plotPaths, stem, cfg, diag, figDir)
%STATEESTIMATION  "State Estimation Validation" report section.
%   Extracted verbatim from ClockExactReportBuilder.writeStateEstimation_ as part
%   of the C-9 report decomposition. Read-only: consumes only the precomputed plotPaths
%   + figure dir and the (now-public) ClockExactReportBuilder formatting toolkit. The
%   emitted LaTeX is byte-identical to the original method (verified by the normalized
%   .tex diff harness, tests/report/reportTexFingerprint.m).
    CE = revgnss.ClockExactReportBuilder;
    fprintf(fid, '\\section{State Estimation Validation}\n');
    fprintf(fid, ['The plots compare EKF state estimates with truth using deterministic truth ' ...
        'differencing. No measurement noise is injected unless the noise toggle is enabled. ' ...
        'Position error is shown in the RAC (radial / along-track / cross-track) orbital frame ' ...
        'as estimate minus truth. The RAC basis is built from the truth position and (inertial) ' ...
        'velocity.\n\n']);
    fprintf(fid, CE.plotTableHeader_());

    CE.writeRow_(fid, CE.figRef_(plotPaths,'posErr',figDir,stem), ...
        'Position Error --- RAC Frame (estimate minus truth)', ...
        ['Position error decomposed into radial, along-track, and cross-track components in the ' ...
         'orbital frame defined by the truth position and inertial velocity. ' ...
         'Sign convention is estimate minus truth; the y-axis unit is chosen automatically.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'posErrZoom',figDir,stem), ...
        'Position Error (RAC) --- Final Zoom', ...
        'RAC position error over the final window of simulation time. Confirms convergence.');

    CE.writeRow_(fid, CE.figRef_(plotPaths,'clkErr',figDir,stem), ...
        'Clock Synchronisation Error', ...
        ['The EKF clock-bias estimation error against the covariance envelope. ' ...
         'The clock process follows the selected oscillator power-law noise model ' ...
         '(Brown-Hwang two-state). Receiver clock sign is POSITIVE.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'clkErrZoom',figDir,stem), ...
        'Clock Bias Error — Final 120 s Zoom ($\pm3\sigma$)', ...
        'Clock bias estimation error over the final 120 s of simulation time.');

    CE.writeRow_(fid, CE.figRef_(plotPaths,'clkDrift',figDir,stem), ...
        'Clock Drift / Fractional Frequency', ...
        ['The receiver clock drift shown as fractional frequency (drift / c) in the ' ...
         'time domain (s/s, auto-scaled to ns/s, ps/s ...). ' ...
         'Brown-Hwang two-state process noise model.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'clkDriftZoom',figDir,stem), ...
        'Clock Drift Error — Final 120 s Zoom ($\pm3\sigma$)', ...
        'Clock drift estimation error over the final 120 s of simulation time.');

    CE.writeRow_(fid, CE.figRef_(plotPaths,'nis',figDir,stem), ...
        'Normalised Innovation Squared', ...
        ['NIS is a chi-square consistency diagnostic only when measurement noise is ' ...
         'stochastic, zero-mean, and correctly represented in R. ' ...
         'In deterministic validation runs NIS is a numerical conditioning diagnostic only.']);

    % Attitude rows — conditional
    doAtt = isfield(cfg,'estimator') && isfield(cfg.estimator,'estimateAttitude') ...
        && cfg.estimator.estimateAttitude;
    if doAtt
        CE.writeRow_(fid, CE.figRef_(plotPaths,'attComp',figDir,stem), ...
            'Attitude Error Components: Roll, Pitch, Yaw', ...
            ['Roll, pitch, and yaw estimation errors from diagnostic truth history. ' ...
             'If absent, attitude history or plot export was unavailable.']);
        CE.writeRow_(fid, CE.figRef_(plotPaths,'attNorm',figDir,stem), ...
            '3D Attitude Error Norm', ...
            'Euclidean norm of roll/pitch/yaw error in degrees.');
        CE.writeRow_(fid, CE.figRef_(plotPaths,'attCompZoom',figDir,stem), ...
            'Attitude Components — Final 120 s Zoom ($\pm3\sigma$)', ...
            'Roll/pitch/yaw errors over the final 120 s of simulation time.');
        CE.writeRow_(fid, CE.figRef_(plotPaths,'attSigma',figDir,stem), ...
            'Attitude Covariance Sigma', ...
            'Square-root sum of EKF Euler-angle covariance diagonal in degrees.');
    end

    fprintf(fid, CE.plotTableFooter_());
    fprintf(fid, '\\clearpage\n');
end
