function stateEstimation(fid, plotPaths, stem, cfg, diag, figDir, summary)
%STATEESTIMATION  "State Estimation Validation" report section.
%   Consumes precomputed plot paths and emits the state-estimation report rows.
%   Federated-swarm plots are added only when the summary carries that payload.
    if nargin < 7; summary = struct(); end
    CE = revgnss.ClockExactReportBuilder;
    fprintf(fid, '\\section{State Estimation Validation}\n');
    fprintf(fid, ['The plots compare EKF state estimates with truth using deterministic truth ' ...
        'differencing. No measurement noise is injected unless the noise toggle is enabled. ' ...
        'Position error is shown in the RAC (radial / along-track / cross-track) orbital frame ' ...
        'as estimate minus truth. The RAC basis is built from the truth position and (inertial) ' ...
        'velocity.\n\n']);
    fprintf(fid, CE.plotTableHeader_());

    CE.writeRow_(fid, CE.figRef_(plotPaths,'posErr',figDir,stem), ...
        'Position Error --- RAC Frame (estimate minus truth)', ...
        ['Position error decomposed into radial, along-track, and cross-track components in the ' ...
         'orbital frame defined by the truth position and inertial velocity. ' ...
         'Sign convention is estimate minus truth; the y-axis unit is chosen automatically.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'posErrZoom',figDir,stem), ...
        'Position Error (RAC) --- Final Zoom', ...
        'RAC position error over the final window of simulation time. Confirms convergence.');

    % Federated-swarm rows are emitted only when the payload is present.
    if isstruct(summary) && isfield(summary,'federatedSwarm') && ~isempty(summary.federatedSwarm)
        fs_ = summary.federatedSwarm;
        if isfield(fs_,'absFig') && ~isempty(fs_.absFig) && isfile(fullfile(figDir, fs_.absFig))
            CE.writeRow_(fid, fullfile(figDir, fs_.absFig), ...
                'Federated Swarm --- Per-Satellite Absolute Position Error', ...
                ['Each satellite estimates its own absolute state with an independent single-asset ' ...
                 'EKF (no chief, no shared covariance). Under the GEO radial--clock degeneracy every ' ...
                 'absolute solution is wall-limited (common mode), so the per-satellite errors settle ' ...
                 'at the metre level rather than to zero.']);
        end
        if isfield(fs_,'relFig') && ~isempty(fs_.relFig) && isfile(fullfile(figDir, fs_.relFig))
            relText = ['The relative panel shows raw formation diagnostics from the independent ' ...
                'per-asset estimates. Solved shape curves are emitted only when the two-way ISL ' ...
                'shape layer is enabled.'];
            try
                if isfield(fs_,'rel') && isfield(fs_.rel,'shapeGateOn') && fs_.rel.shapeGateOn
                    relText = ['The read-only two-way ISL / satellite-to-satellite time-transfer ' ...
                        'relative layer sharpens the observable formation shape and relative clocks. ' ...
                        'It is truth-free, rigid-blind, and never re-opens any per-asset absolute solution.'];
                end
            catch; end
            CE.writeRow_(fid, fullfile(figDir, fs_.relFig), ...
                'Federated Swarm --- Relative Layer (ISL Shape / Clocks)', ...
                relText);
        end
        if isfield(fs_,'kabschFig') && ~isempty(fs_.kabschFig) && isfile(fullfile(figDir, fs_.kabschFig))
            CE.writeRow_(fid, fullfile(figDir, fs_.kabschFig), ...
                'Federated Swarm --- Kabsch-Aligned Final Formation', ...
                ['Estimated and true final satellite point clouds after rigid no-scale Kabsch alignment. ' ...
                 'The plot is centred on the formation centroid, so kilometre-class separations remain visible ' ...
                 'without plotting Earth-centred coordinates. Residual links show shape error after removing ' ...
                 'only unobservable translation and rotation.']);
        end
    end

    CE.writeRow_(fid, CE.figRef_(plotPaths,'clkTruth',figDir,stem), ...
        'Receiver Clock: True Development vs EKF Estimate', ...
        ['The true receiver-clock bias (black) against the EKF-estimated/corrected clock ' ...
         '(red dashed). Under the one-way GEO radial--clock degeneracy the estimate absorbs the ' ...
         'radial common mode, so it wanders more than the (quiet) truth; that gap is the ' ...
         'clock-synchronisation error shown next.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'clkErr',figDir,stem), ...
        'Clock Synchronisation Error', ...
        ['The EKF clock-bias estimation error against the covariance envelope. ' ...
         'The clock process follows the selected oscillator power-law noise model ' ...
         '(Brown-Hwang two-state). Receiver clock sign is POSITIVE.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'clkErrZoom',figDir,stem), ...
        'Clock Bias Error — Final 120 s Zoom ($\pm3\sigma$)', ...
        'Clock bias estimation error over the final 120 s of simulation time.');

    CE.writeRow_(fid, CE.figRef_(plotPaths,'clkDrift',figDir,stem), ...
        'Clock Drift / Fractional Frequency', ...
        ['The receiver clock drift shown as fractional frequency (drift / c) in the ' ...
         'time domain (s/s, auto-scaled to ns/s, ps/s ...). ' ...
         'Brown-Hwang two-state process noise model.']);

    CE.writeRow_(fid, CE.figRef_(plotPaths,'clkDriftZoom',figDir,stem), ...
        'Clock Drift Error — Final 120 s Zoom ($\pm3\sigma$)', ...
        'Clock drift estimation error over the final 120 s of simulation time.');

    CE.writeRow_(fid, CE.figRef_(plotPaths,'nis',figDir,stem), ...
        'Normalised Innovation Squared', ...
        ['NIS is a chi-square consistency diagnostic only when measurement noise is ' ...
         'stochastic, zero-mean, and correctly represented in R. ' ...
         'In deterministic validation runs NIS is a numerical conditioning diagnostic only.']);

    % Attitude rows — conditional
    doAtt = isfield(cfg,'estimator') && isfield(cfg.estimator,'estimateAttitude') ...
        && cfg.estimator.estimateAttitude;
    if doAtt
        CE.writeRow_(fid, CE.figRef_(plotPaths,'attComp',figDir,stem), ...
            'Attitude Error Components: Roll, Pitch, Yaw', ...
            ['Roll, pitch, and yaw estimation errors from diagnostic truth history. ' ...
             'If absent, attitude history or plot export was unavailable.']);
        CE.writeRow_(fid, CE.figRef_(plotPaths,'attCompZoom',figDir,stem), ...
            'Attitude Components — Final 120 s Zoom ($\pm3\sigma$)', ...
            'Roll/pitch/yaw errors over the final 120 s of simulation time.');
        CE.writeRow_(fid, CE.figRef_(plotPaths,'attSigma',figDir,stem), ...
            'Attitude Covariance Sigma', ...
            'Square-root sum of EKF Euler-angle covariance diagonal in degrees.');
    end

    fprintf(fid, CE.plotTableFooter_());

    % Honest multi-asset swarm: per-satellite ABSOLUTE vs RELATIVE position error, full-width
    % for readability across all secondaries. Fully conditional -- the block is emitted only
    % when the swarm figures were generated (estimateMode='position', nSpaceAssets>1), so a
    % single-asset report is byte-identical (empty ref -> whole block skipped).
    swarmRef = CE.figRef_(plotPaths,'swarmPos',figDir,stem);
    if ~isempty(swarmRef) && isfile(swarmRef)
        fprintf(fid, '\\clearpage\n');
        fprintf(fid, '\\subsection*{Per-Satellite Position Error --- Honest Multi-Asset Swarm}\n');
        fprintf(fid, ['Each estimated secondary is compared to the chief. The \\textbf{absolute} panel ' ...
            'shows every satellite''s 3-D position error (solid) against the filter''s $\\pm3\\sigma$ ' ...
            'envelope (dashed): under the single-hemisphere GEO radial--clock degeneracy the error ' ...
            'escapes $3\\sigma$, so the absolute solution is honestly \\emph{overconfident}. The ' ...
            '\\textbf{relative} panel shows each satellite''s baseline error to the chief --- the ' ...
            'formation shape that two-way ISL sharpens --- which is sub-metre and trustworthy. ' ...
            'The two views are the honest answer to ``compare the position error of each satellite''''.\n\n']);
        [~, nm, ext] = fileparts(swarmRef);
        fprintf(fid, '\\begin{center}\\includegraphics[width=\\linewidth]{figures/%s}\\end{center}\n', [nm ext]);
        zoomRef = CE.figRef_(plotPaths,'swarmPosZoom',figDir,stem);
        if ~isempty(zoomRef) && isfile(zoomRef)
            fprintf(fid, '\\vspace{0.4cm}\n');
            [~, nmz, extz] = fileparts(zoomRef);
            fprintf(fid, '\\begin{center}\\includegraphics[width=\\linewidth]{figures/%s}\\end{center}\n', [nmz extz]);
        end
    end

    fprintf(fid, '\\clearpage\n');
end
