function row = requiredFixValidationCase(varargin)
% requiredFixValidationCase  Build one required-fix validation metric row.

p = inputParser;
p.addParameter('ScenarioId','',@(x)ischar(x) || isstring(x));
p.addParameter('Mode','unit',@(x)ischar(x) || isstring(x));
p.addParameter('Focus','all',@(x)ischar(x) || isstring(x));
p.addParameter('Status','pass',@(x)ischar(x) || isstring(x));
p.addParameter('Message','',@(x)ischar(x) || isstring(x));
p.addParameter('Duration_s',NaN,@isnumeric);
p.addParameter('NTowers',NaN,@isnumeric);
p.addParameter('NAssets',NaN,@isnumeric);
p.addParameter('PhysicalTowerCountDatastore',NaN,@isnumeric);
p.addParameter('ActiveMeasurementTypes','',@(x)ischar(x) || isstring(x));
p.addParameter('CodeRowCountBySignal','',@(x)ischar(x) || isstring(x));
p.addParameter('TwttRowCount',NaN,@isnumeric);
p.addParameter('PostfitResidualCountByType','',@(x)ischar(x) || isstring(x));
p.addParameter('MeanNisByType','',@(x)ischar(x) || isstring(x));
p.addParameter('NEES',NaN,@isnumeric);
p.addParameter('PositionRMS_m',NaN,@isnumeric);
p.addParameter('ClockRMS_m',NaN,@isnumeric);
p.addParameter('RelativeShapeRawRMS_m',NaN,@isnumeric);
p.addParameter('RelativeShapeSolvedRMS_m',NaN,@isnumeric);
p.addParameter('SwarmGateFlags','',@(x)ischar(x) || isstring(x));
p.addParameter('DcbActiveFlag',false,@islogical);
p.addParameter('HigherOrderIonoActiveFlag',false,@islogical);
p.parse(varargin{:});

r = p.Results;
row = struct( ...
    'scenario_id', char(r.ScenarioId), ...
    'mode', char(r.Mode), ...
    'focus', char(r.Focus), ...
    'status', char(r.Status), ...
    'duration_s', scalarOrNan_(r.Duration_s), ...
    'number_of_towers', scalarOrNan_(r.NTowers), ...
    'number_of_assets', scalarOrNan_(r.NAssets), ...
    'physical_tower_count_reported_by_datastore', scalarOrNan_(r.PhysicalTowerCountDatastore), ...
    'active_measurement_types', char(r.ActiveMeasurementTypes), ...
    'code_row_count_by_signal', char(r.CodeRowCountBySignal), ...
    'two_way_time_transfer_row_count', scalarOrNan_(r.TwttRowCount), ...
    'postfit_residual_count_by_type', char(r.PostfitResidualCountByType), ...
    'mean_NIS_by_type', char(r.MeanNisByType), ...
    'NEES', scalarOrNan_(r.NEES), ...
    'position_RMS_m', scalarOrNan_(r.PositionRMS_m), ...
    'clock_RMS_m', scalarOrNan_(r.ClockRMS_m), ...
    'relative_shape_raw_RMS_m', scalarOrNan_(r.RelativeShapeRawRMS_m), ...
    'relative_shape_solved_RMS_m', scalarOrNan_(r.RelativeShapeSolvedRMS_m), ...
    'swarm_gate_flags', char(r.SwarmGateFlags), ...
    'DCB_active_flag', logical(r.DcbActiveFlag), ...
    'higher_order_ionosphere_active_flag', logical(r.HigherOrderIonoActiveFlag), ...
    'message', char(r.Message));
end

function v = scalarOrNan_(x)
if isempty(x)
    v = NaN;
else
    v = double(x(1));
end
end
