function entries = configEnumRegistry()
%CONFIGENUMREGISTRY  Legal values for the string-valued knobs whose typo is DANGEROUS.
%
%   Returns a struct array with fields:
%       path        dotted config path, e.g. 'errors.troposphere.modelType'
%       values      cellstr of legal values
%       caseSense   true when the consumer compares case-sensitively (strcmp), false
%                   when it lower-cases first (strcmpi / switch lower(...))
%       note        one line naming the dispatch site and what an unrecognised value
%                   silently does there -- this is the reason the entry exists
%
%   WHY THIS FILE EXISTS. Almost every mode dispatch in this codebase is a switch or
%   if-chain that ends in a SILENT default branch, and nothing upstream constrains the
%   string: deepMergeConfig validates PATHS, not VALUES, and validateMasterConfig checked
%   no model name at all before 2026-08-09. So a misspelling was accepted by the merge,
%   missed every case, took the fallback, and was then PRINTED VERBATIM by the report as
%   the active model -- the PDF asserting a model the run did not use. The sharpest case:
%   'singleMapped' instead of 'simpleMapped' on errors.troposphere.modelType silently runs
%   a TROPOSPHERE-FREE simulation (EnvironmentModel.m:445 otherwise -> delay = 0).
%
%   SCOPE. This is a curated list, not an exhaustive one. An entry earns its place when
%   an unrecognised value changes PHYSICS or R rather than merely a label. Knobs that
%   already error on a bad value are deliberately absent (cfg.measurements.codeMode
%   raises ConfigFactory:invalidCodeMode; cfg.errors.ionosphere.modelType =
%   'constantVerticalTEC' raises ErrorChain:invalidModelType). Add to it as new dispatch
%   sites appear -- the cost of an entry is one line, the cost of a missing one is a
%   silently wrong run.
%
%   Every legal set below was read off the dispatch site, not from a comment.

    e = @(p, v, cs, n) struct('path', p, 'values', {v}, 'caseSense', cs, 'note', n);
    entries = [ ...
        ...% ---- Troposphere ------------------------------------------------------
        e('errors.troposphere.modelType', {'simpleMapped','localWeatherGM'}, true, ...
          ['EnvironmentModel.m:392 / ErrorChain.m:480 switch; unrecognised -> ' ...
           'otherwise at EnvironmentModel.m:445 returns delay = 0 (NO troposphere).']), ...
        e('errors.troposphere.truth.mappingType', {'simple','niell'}, true, ...
          'EnvironmentModel.m:660 switch; unrecognised -> the 1/sin(E) simple mapping, not Niell.'), ...
        e('errors.troposphere.model.mappingType', {'simple','niell'}, true, ...
          'EnvironmentModel.m:660 switch; unrecognised -> the 1/sin(E) simple mapping, not Niell.'), ...
        e('errors.troposphere.stochastic.process', {'gaussMarkov'}, false, ...
          'Only the Gauss-Markov wet process is implemented; any other value is not a model.'), ...
        e('errors.troposphere.stochastic.modelResidual.mode', ...
          {'zero','independentGM','seededTruthResidual'}, true, ...
          ['EnvironmentModel.m:264 switch; unrecognised -> otherwise at :270 sets the ' ...
           'residual to zero. NOTE ''seededTruthResidual'' is listed because ' ...
           'ScenarioPresets/geoRealWorldTruthComparisonConfig ship it, but it has NO case ' ...
           'and is therefore INERT -- it silently means ''zero''. ''sameAsTruth'' is ' ...
           'deliberately absent: EnvironmentModel.m:250 hard-errors on it as a forbidden ' ...
           'oracle read (it would copy the truth wet realisation into the model).']), ...
        e('estimation.troposphereMode', {'none','perTowerZwd'}, true, ...
          ['Compared by strcmp against ''perTowerZwd'' in ReverseGNSSEKF, TroposphereModel ' ...
           'and ErrorChain; anything else silently means "no ZWD state".']), ...
        ...% ---- Ionosphere -------------------------------------------------------
        e('errors.ionosphere.modelType', {'simpleMapped','constantVerticalDelay','tecGaussMarkov'}, true, ...
          ['EnvironmentModel.m:485 / ErrorChain.m:616 switch; unrecognised -> otherwise at ' ...
           'EnvironmentModel.m:584 returns delay = 0 (NO ionosphere).']), ...
        e('errors.ionosphere.model.correction', {'none','biasFraction','klobuchar'}, true, ...
          ['EnvironmentModel.m:554-575 if-chain; unrecognised -> the biasFraction branch, ' ...
           'so a mistyped ''klobuchar'' silently applies a constant vertical delay instead.']), ...
        e('errors.ionosphere.stochastic.process', {'gaussMarkov'}, false, ...
          'Only the Gauss-Markov TEC process is implemented.'), ...
        e('errors.ionosphere.stochastic.modelResidual.mode', ...
          {'zero','independentGM','seededTruthResidual'}, true, ...
          'Twin of the troposphere residual mode, including the inert ''seededTruthResidual''.'), ...
        e('errors.ionosphere.scintillation.model', {'conker','legacy'}, true, ...
          ['EnvironmentModel.getScintillationSigma compares with a bare strcmp against ' ...
           '''conker''; ANY other string takes the legacy 1/sqrt(sin el) branch. ' ...
           '''legacy'' is the NAMED way to ask for that branch and is shipped by the ' ...
           'single and headline goldens -- so only a third, unrecognised string is a typo.']), ...
        e('errors.ionosphere.scintillation.obliquityModel', ...
          {'simpleSecant','thinShell','matchIonoMapping'}, true, ...
          'EnvironmentModel.scintObliquity_ switch; unrecognised -> the legacy 1/sin(el) secant.'), ...
        e('errors.ionosphere.scintillation.process', {'gaussMarkov'}, false, ...
          'Only the Gauss-Markov scintillation amplitude process is implemented.'), ...
        e('effects.ionosphere.mappingModel', {'simpleSecant','thinShell'}, true, ...
          ['MappingFunctions.ionosphere switch; unrecognised -> simpleSecant, which ' ...
           'over-maps at low elevation and silently changes every slant delay.']), ...
        e('estimation.ionosphereMode', {'none','perTowerSlant'}, true, ...
          'Compared by strcmp against ''perTowerSlant''; anything else means "no slant-iono state".'), ...
        ...% ---- Measurement noise / observables -----------------------------------
        e('measurements.codeNoise.model', {'constant','elevation','cn0'}, false, ...
          ['ErrorChain.m:431 and MeasurementModelUtils.m:162 both switch on lower(model) ' ...
           'and end in an otherwise that returns the FLAT sigma0 -- so a typo silently ' ...
           'removes the elevation or C/N0 shaping from both the truth draw and R.']), ...
        e('measurements.carrierMode', {'off','none','diagnostic','ekfFloat'}, true, ...
          ['MeasurementModel.m:288 switch handles ekfFloat and diagnostic; anything else ' ...
           'produces no carrier rows at all.']), ...
        ...% ---- Clocks -----------------------------------------------------------
        e('clock.templateSource', {'legacy','jowTable2p1'}, true, ...
          'ConfigFactory.getClockTemplate_ dispatch; unrecognised -> the legacy (optimistic) table.'), ...
        e('asset.clockType', {'TCXO','OCXO','RUBIDIUM','CESIUM1','ZERO'}, false, ...
          'ConfigFactory.getClockTemplate_ switch; unrecognised h-coefficients cannot be resolved.'), ...
        e('clock.tower.clockType', {'','TCXO','OCXO','RUBIDIUM','CESIUM1','ZERO'}, false, ...
          ['Same getClockTemplate_ switch, reached via finalizeConfig''s per-tower override; a ' ...
           'typo there does NOT error at the switch, it WARNS and silently substitutes OCXO ' ...
           '(ConfigFactory.m:2443). '''' is legal and means "leave cfg.towers(k).clockType alone".']), ...
        e('towerClock.correctionMode', ...
          {'none','perfectTruth','truthHistoryProduct','truthHistoryProductNoisy', ...
           'product','productNoisy','noisyCorrection'}, ...
          true, ...
          ['ConfigFactory.finalizeConfig:759 switch ends in an otherwise that copies the ' ...
           'string VERBATIM into the derived cfg.estimator.towerClockMode, where ' ...
           'TowerClockCorrectionProvider''s own otherwise then zeroes the correction. ' ...
           '''noisyCorrection'' has no named case but IS a real, used mode ' ...
           '(ConfigFactory.clockNoiseConfig ships it): it reaches the provider through ' ...
           'exactly that verbatim passthrough.']), ...
        e('clocks.tower.product.mode', ...
          {'none','perfectTruth','truthHistoryProduct','truthHistoryProductNoisy', ...
           'product','productNoisy','noisyCorrection'}, ...
          true, 'Legacy alias mapped onto towerClock.correctionMode; same legal set.'), ...
        ...% ---- Orbit and frames --------------------------------------------------
        e('orbit.mode', {'circularAnalytic','twoBodyRk4','j2Rk4','stationaryEcef'}, false, ...
          ['OrbitPropagator.propagate names only twoBodyRk4 and j2Rk4 and FALLS THROUGH ' ...
           'to the circular-analytic loop for everything else -- a pure Kepler circle with ' ...
           'no J2, luni-solar or SRP. ''stationaryEcef'' is legal-but-inert: masterConfig ' ...
           'rewrites it to j2Rk4 at :621-626, so it never reaches the propagator.']), ...
        e('orbit.truth.mode', {'circularAnalytic','twoBodyRk4','j2Rk4','stationaryEcef'}, false, ...
          'Same set as orbit.mode, from which the propagator is actually built.'), ...
        e('estimator.dynamics.mode', ...
          {'constantVelocity','twoBody','two_body','j2','twoBodyJ2','two_body_j2'}, false, ...
          'EkfDynamicsPredictor.mode switch (case-insensitive); unrecognised warns and uses constantVelocity.'), ...
        e('perturbations.sunMoon.ephemeris', {'mg','de440'}, false, ...
          'OrbitPerturbations sun/moon source; unrecognised -> the analytic M&G series.'), ...
        e('asset.attitudePointing', {'nadir','fixed'}, false, ...
          'masterConfig:948 computes the nadir Euler only for ''nadir''; anything else keeps the fixed attitude.'), ...
        e('scenario.orbitClass', {'GEO','MEO','LEO'}, false, ...
          'orbitClassConfig dispatch; an unrecognised class silently leaves the GEO geometry in place.') ...
    ];
end
