function exceptions = scenarioResolutionExceptionRegistry()
%SCENARIORESOLUTIONEXCEPTIONREGISTRY Explicit exceptions to scenario precedence.

    exceptions = struct( ...
        'scenarioFile', {}, ...
        'path', {}, ...
        'reason', {});
end
