classdef ErrorBudget
    %ERRORBUDGET Small helpers for truth/model error budget structs.
    %
    % This class contains no spacecraft, atmosphere, or EKF physics. It only
    % normalizes component structs into the canonical budget shape used by
    % the measurement refactor.

    methods (Static)
        function budget = evaluate(context, resolvedErrors, existingModels)
            if nargin < 1 || isempty(context)
                context = struct();
            end
            if nargin < 2 || isempty(resolvedErrors)
                resolvedErrors = struct();
            end
            if nargin < 3 || isempty(existingModels)
                existingModels = struct();
            end

            components = ErrorBudget.getFieldOrDefault( ...
                context, 'components', struct());
            budget = ErrorBudget.fromComponents(components);
            budget.modelGradient_ECI = ErrorBudget.getFieldOrDefault( ...
                context, 'modelGradient_ECI', zeros(3, 1));
            budget.independentVariance_m2 = ...
                budget.independentVariance_m2 + double( ...
                ErrorBudget.getFieldOrDefault( ...
                context, 'independentVariance_m2', 0.0));
            budget.sameTowerVariance_m2 = ...
                budget.sameTowerVariance_m2 + double( ...
                ErrorBudget.getFieldOrDefault( ...
                context, 'sameTowerVariance_m2', 0.0));
            budget.resolvedErrors = resolvedErrors;
            budget.existingModels = existingModels;
        end

        function budget = fromComponents(components)
            if nargin < 1 || isempty(components)
                components = struct();
            end
            if ~isstruct(components)
                error('ErrorBudget:InvalidComponents', ...
                    'components must be a struct.');
            end

            budget = struct();
            budget.components = struct();
            budget.truthTotal_m = 0.0;
            budget.modelTotal_m = 0.0;
            budget.residualTotal_m = 0.0;
            budget.modelGradient_ECI = zeros(3, 1);
            budget.independentVariance_m2 = 0.0;
            budget.sameTowerVariance_m2 = 0.0;

            names = fieldnames(components);
            if any(strcmp(names, 'total'))
                totalComponent = ErrorBudget.normalizeComponent( ...
                    components.total);
                budget.components.total = totalComponent;
                budget.truthTotal_m = totalComponent.truth_m;
                budget.modelTotal_m = totalComponent.model_m;
                budget.residualTotal_m = totalComponent.residual_m;
                names = names(~strcmp(names, 'total'));
            end

            for idx = 1:numel(names)
                name = names{idx};
                component = ErrorBudget.normalizeComponent(components.(name));
                budget.components.(name) = component;

                if ~isfield(budget.components, 'total')
                    budget.truthTotal_m = ...
                        budget.truthTotal_m + component.truth_m;
                    budget.modelTotal_m = ...
                        budget.modelTotal_m + component.model_m;
                    budget.residualTotal_m = ...
                        budget.residualTotal_m + component.residual_m;
                end

                if component.variance_m2 > 0.0
                    if component.correlationModel == "sameTower"
                        budget.sameTowerVariance_m2 = ...
                            budget.sameTowerVariance_m2 + ...
                            component.variance_m2;
                    else
                        budget.independentVariance_m2 = ...
                            budget.independentVariance_m2 + ...
                            component.variance_m2;
                    end
                end
            end

            if ~isfield(budget.components, 'total')
                budget.components.total = ErrorBudget.withTruthModel( ...
                    ErrorBudget.emptyComponent(), ...
                    budget.truthTotal_m, ...
                    budget.modelTotal_m);
            end
        end

        function component = emptyComponent()
            component = struct();
            component.truth_m = 0.0;
            component.model_m = 0.0;
            component.residual_m = 0.0;
            component.sigma_m = 0.0;
            component.variance_m2 = 0.0;
            component.correlationModel = "independent";
            component.correlation_model = "independent";
            component.valid = true;
            component.diagnostics = struct();
        end

        function component = withTruthModel(component, truth_m, model_m)
            if nargin < 1 || isempty(component)
                component = ErrorBudget.emptyComponent();
            else
                component = ErrorBudget.normalizeComponent(component);
            end

            component.truth_m = double(truth_m);
            component.model_m = double(model_m);
            component.residual_m = component.truth_m - component.model_m;
            component.variance_m2 = component.sigma_m^2;
        end

        function component = normalizeComponent(component)
            if nargin < 1 || isempty(component)
                component = ErrorBudget.emptyComponent();
                return;
            end
            if ~isstruct(component)
                error('ErrorBudget:InvalidComponent', ...
                    'component must be a struct.');
            end

            hasLegacyCorrelation = isfield(component, 'correlation_model') && ...
                ~isempty(component.correlation_model);
            hasCanonicalCorrelation = isfield(component, 'correlationModel') && ...
                ~isempty(component.correlationModel);

            defaults = ErrorBudget.emptyComponent();
            defaultNames = fieldnames(defaults);
            for idx = 1:numel(defaultNames)
                name = defaultNames{idx};
                if ~isfield(component, name) || isempty(component.(name))
                    component.(name) = defaults.(name);
                end
            end

            if hasCanonicalCorrelation && ...
                    string(component.correlationModel) ~= "independent"
                component.correlation_model = ...
                    string(component.correlationModel);
            elseif hasLegacyCorrelation && ...
                    string(component.correlation_model) ~= "independent"
                component.correlationModel = ...
                    string(component.correlation_model);
            elseif hasCanonicalCorrelation
                component.correlation_model = ...
                    string(component.correlationModel);
            elseif hasLegacyCorrelation
                component.correlationModel = ...
                    string(component.correlation_model);
            end

            component.truth_m = double(component.truth_m);
            component.model_m = double(component.model_m);
            component.residual_m = component.truth_m - component.model_m;
            component.sigma_m = double(component.sigma_m);
            component.variance_m2 = double(component.variance_m2);
            component.correlationModel = string(component.correlationModel);
            component.correlation_model = string(component.correlation_model);
            component.valid = logical(component.valid);
        end

        function [extraTruth_m, extraModel_m, budget] = ...
                nonAtmospheric(context)
            if nargin < 1 || isempty(context)
                context = struct();
            end
            if ~isstruct(context)
                error('ErrorBudget:InvalidContext', ...
                    'context must be a struct.');
            end

            budget = struct();
            budget.hardware = ErrorBudget.emptyComponent();
            budget.antenna = ErrorBudget.emptyComponent();
            budget.multipath = ErrorBudget.emptyComponent();
            budget.tower_survey = ErrorBudget.emptyComponent();
            budget.legacy_sagnac = ErrorBudget.emptyComponent();

            if ErrorBudget.logicalField(context, 'useHardwareDelay', false)
                hardwareTruth_m = ...
                    ErrorBudget.scalarField(context, 'txHardwareDelay_m', 0.0) + ...
                    ErrorBudget.scalarField(context, 'towerTxSignalDelay_m', 0.0) + ...
                    ErrorBudget.scalarField(context, 'rxHardwareDelay_m', 0.0);

                hardwareModel_m = ...
                    ErrorBudget.scalarField(context, 'txHardwareDelayModel_m', 0.0) + ...
                    ErrorBudget.scalarField(context, 'rxHardwareDelayModel_m', 0.0);

                budget.hardware = ErrorBudget.withTruthModel( ...
                    budget.hardware, hardwareTruth_m, hardwareModel_m);
                budget.hardware.diagnostics = struct( ...
                    'tx_truth_configured_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'txHardwareDelay_m', 0.0), ...
                    'tx_truth_tower_specific_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'towerTxSignalDelay_m', 0.0), ...
                    'rx_truth_configured_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'rxHardwareDelay_m', 0.0), ...
                    'tx_model_configured_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'txHardwareDelayModel_m', 0.0), ...
                    'rx_model_configured_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'rxHardwareDelayModel_m', 0.0), ...
                    'note', "First-stage hardware model correction is global TX/RX. Tower-specific model TX delay remains future work.");
            end

            if ErrorBudget.logicalField(context, 'useMultipathDelay', false)
                multipathTruth_m = ...
                    ErrorBudget.scalarField(context, 'multipathDelay_m', 0.0) + ...
                    ErrorBudget.scalarField(context, ...
                    'multipathStochasticTruth_m', 0.0);
                multipathSigma_m = ErrorBudget.scalarField( ...
                    context, 'multipathSigma_m', 0.0);

                budget.multipath = ErrorBudget.withTruthModel( ...
                    budget.multipath, ...
                    multipathTruth_m, ...
                    ErrorBudget.scalarField( ...
                    context, 'multipathDelayModel_m', 0.0));

                budget.multipath.sigma_m = multipathSigma_m;
                budget.multipath.variance_m2 = multipathSigma_m^2;
                budget.multipath.correlation_model = "independent";
                budget.multipath.correlationModel = "independent";

                budget.multipath.diagnostics = struct( ...
                    'truth_configured_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'multipathDelay_m', 0.0), ...
                    'truth_stochastic_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'multipathStochasticTruth_m', 0.0), ...
                    'model_configured_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'multipathDelayModel_m', 0.0), ...
                    'sigma_m', multipathSigma_m, ...
                    'variance_m2', multipathSigma_m^2, ...
                    'elevation_deg', ...
                        ErrorBudget.scalarField(context, ...
                        'multipathElevation_deg', NaN), ...
                    'minimum_elevation_deg', ...
                        ErrorBudget.scalarField(context, ...
                        'multipathStochasticMinimumElevation_deg', NaN), ...
                    'random_seed', ...
                        ErrorBudget.scalarField(context, ...
                        'multipathStochasticRandomSeed', NaN), ...
                    'note', "First-stage stochastic multipath is an independent link/epoch truth sample. The estimator receives only model correction and diagonal variance, not the actual truth sample.");
            end

            if ErrorBudget.logicalField(context, 'useAntennaDelay', false)
                antennaTruth_m = ...
                    ErrorBudget.scalarField(context, 'antennaDelay_m', 0.0) + ...
                    ErrorBudget.scalarField(context, ...
                    'txAntennaCorrection_m', 0.0) + ...
                    ErrorBudget.scalarField(context, ...
                    'rxAntennaCorrection_m', 0.0);
                antennaModel_m = ErrorBudget.scalarField( ...
                    context, 'antennaDelayModel_m', 0.0);

                budget.antenna = ErrorBudget.withTruthModel( ...
                    budget.antenna, antennaTruth_m, antennaModel_m);
                budget.antenna.diagnostics = struct( ...
                    'truth_configured_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'antennaDelay_m', 0.0), ...
                    'model_configured_delay_m', antennaModel_m, ...
                    'tx_truth_correction_m', ...
                        ErrorBudget.scalarField(context, ...
                        'txAntennaCorrection_m', 0.0), ...
                    'rx_truth_correction_m', ...
                        ErrorBudget.scalarField(context, ...
                        'rxAntennaCorrection_m', 0.0), ...
                    'note', "First-stage antenna model correction is a scalar calibrated correction. Full PCO/PCV truth/model separation remains future work.");
            end

            if ErrorBudget.logicalField(context, 'useSagnacCorrection', false)
                budget.legacy_sagnac = ErrorBudget.withTruthModel( ...
                    budget.legacy_sagnac, ...
                    ErrorBudget.scalarField(context, ...
                    'sagnacCorrection_m', 0.0), ...
                    ErrorBudget.scalarField(context, ...
                    'sagnacCorrectionModel_m', 0.0));
                budget.legacy_sagnac.diagnostics = struct( ...
                    'truth_configured_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'sagnacCorrection_m', 0.0), ...
                    'model_configured_delay_m', ...
                        ErrorBudget.scalarField(context, ...
                        'sagnacCorrectionModel_m', 0.0), ...
                    'note', "Legacy scalar Sagnac placeholder. Use only for controlled bias studies; physical light-time/Sagnac propagation is handled separately.");
            end

            if ErrorBudget.logicalField(context, 'useTowerSurveyError', false)
                budget.tower_survey = ErrorBudget.withTruthModel( ...
                    budget.tower_survey, ...
                    ErrorBudget.scalarField(context, ...
                    'truthTowerSurvey_m', 0.0), ...
                    ErrorBudget.scalarField(context, ...
                    'modelTowerSurvey_m', 0.0));

                budget.tower_survey.diagnostics = struct( ...
                    'truth_position_offset_ecef_m', ...
                        ErrorBudget.getFieldOrDefault(context, ...
                        'truthTowerPositionOffsetEcef_m', zeros(3, 1)), ...
                    'model_position_offset_ecef_m', ...
                        ErrorBudget.getFieldOrDefault(context, ...
                        'modelTowerPositionOffsetEcef_m', zeros(3, 1)), ...
                    'note', "Tower survey error is modelled as an ECEF position-offset range effect added to truth/model pseudorange.");
            else
                budget.tower_survey.diagnostics = struct( ...
                    'note', "Tower survey range-effect is disabled.");
            end

            extraTruth_m = ...
                budget.hardware.truth_m + ...
                budget.antenna.truth_m + ...
                budget.multipath.truth_m + ...
                budget.tower_survey.truth_m + ...
                budget.legacy_sagnac.truth_m;

            extraModel_m = ...
                budget.hardware.model_m + ...
                budget.antenna.model_m + ...
                budget.multipath.model_m + ...
                budget.tower_survey.model_m + ...
                budget.legacy_sagnac.model_m;

            budget.total = ErrorBudget.withTruthModel( ...
                ErrorBudget.emptyComponent(), ...
                extraTruth_m, ...
                extraModel_m);
            budget.total.diagnostics = struct( ...
                'note', "Non-atmospheric model corrections use optional *Model_m configuration fields and default to zero for backward compatibility.");
        end

        function budget = atmosphere(context)
            if nargin < 1 || isempty(context)
                context = struct();
            end
            if ~isstruct(context)
                error('ErrorBudget:InvalidContext', ...
                    'context must be a struct.');
            end

            truthTotal_m = ErrorBudget.getFieldOrDefault( ...
                context, 'truthTotal_m', 0.0);
            modelTotal_m = ErrorBudget.getFieldOrDefault( ...
                context, 'modelTotal_m', 0.0);

            components = struct();
            components.troposphere = ErrorBudget.withTruthModel( ...
                ErrorBudget.emptyComponent(), ...
                ErrorBudget.getFieldOrDefault( ...
                context, 'truthTroposphere_m', 0.0), ...
                ErrorBudget.getFieldOrDefault( ...
                context, 'modelTroposphere_m', 0.0));
            components.troposphere.correlationModel = "sameTower";
            components.troposphere.correlation_model = "sameTower";

            components.ionosphere = ErrorBudget.withTruthModel( ...
                ErrorBudget.emptyComponent(), ...
                ErrorBudget.getFieldOrDefault( ...
                context, 'truthIonosphere_m', 0.0), ...
                ErrorBudget.getFieldOrDefault( ...
                context, 'modelIonosphere_m', 0.0));
            components.ionosphere.correlationModel = "sameTower";
            components.ionosphere.correlation_model = "sameTower";

            components.stochastic_residual = ErrorBudget.withTruthModel( ...
                ErrorBudget.emptyComponent(), ...
                ErrorBudget.getFieldOrDefault( ...
                context, 'stochasticResidualTotal_m', 0.0), ...
                0.0);
            components.stochastic_residual.correlationModel = "sameTower";
            components.stochastic_residual.correlation_model = "sameTower";
            components.stochastic_residual.diagnostics = struct( ...
                'troposphere_m', ErrorBudget.getFieldOrDefault( ...
                    context, 'stochasticResidualTroposphere_m', 0.0), ...
                'ionosphere_m', ErrorBudget.getFieldOrDefault( ...
                    context, 'stochasticResidualIonosphere_m', 0.0), ...
                'note', "Truth atmosphere residual samples are logged after measurement generation; the estimator receives covariance, not samples.");

            components.total = ErrorBudget.withTruthModel( ...
                ErrorBudget.emptyComponent(), truthTotal_m, modelTotal_m);

            budget = ErrorBudget.fromComponents(components);

            covariance = ErrorBudget.getFieldOrDefault( ...
                context, 'covariance', struct());
            covarianceSummary = struct( ...
                'sigma_m', ErrorBudget.scalarField( ...
                    covariance, 'sigma_m', 0.0), ...
                'variance_m2', ErrorBudget.scalarField( ...
                    covariance, 'variance_m2', 0.0), ...
                'residualTroposphereSigma_m', ErrorBudget.scalarField( ...
                    covariance, 'residualTroposphereSigma_m', 0.0), ...
                'residualIonosphereSigma_m', ErrorBudget.scalarField( ...
                    covariance, 'residualIonosphereSigma_m', 0.0), ...
                'correlationModel', "sameTower", ...
                'correlation_model', "sameTower");

            budget.truthTotal_m = truthTotal_m;
            budget.modelTotal_m = modelTotal_m;
            budget.residualTotal_m = truthTotal_m - modelTotal_m;
            budget.sameTowerVariance_m2 = covarianceSummary.variance_m2;
            budget.independentVariance_m2 = 0.0;
            budget.covariance = covarianceSummary;
        end
    end

    methods (Static, Access = private)
        function value = getFieldOrDefault(s, fieldName, defaultValue)
            if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
                value = s.(fieldName);
            else
                value = defaultValue;
            end
        end

        function value = scalarField(s, fieldName, defaultValue)
            value = double(ErrorBudget.getFieldOrDefault( ...
                s, fieldName, defaultValue));
        end

        function value = logicalField(s, fieldName, defaultValue)
            value = logical(ErrorBudget.getFieldOrDefault( ...
                s, fieldName, defaultValue));
        end
    end
end
