classdef CoherentTwoWayCodeRangingModel
    % CoherentTwoWayCodeRangingModel  Four-event transponded PN code range.

    properties (Constant)
        SpeedOfLight_mps = 299792458
        ProtocolIdentifier = 'coherentTranspondedPnTwoWayCode'
    end

    methods (Static)
        function [observation, truthDiagnostic] = simulateObservation( ...
                initiatorTruth, transponderTruth, physicalHardware, ...
                calibrationProduct, finalReceptionCoordinateTime_s, metadata, ...
                trackingError_s, solverOptions, propagationGroupDelay_s)
            if nargin < 7 || isempty(trackingError_s)
                trackingError_s = 0;
            end
            if nargin < 8
                solverOptions = struct();
            end
            if nargin < 9 || isempty(propagationGroupDelay_s)
                propagationGroupDelay_s = 0;
            end

            revgnss.CoherentTwoWayCodeRangingModel.validateTypes_( ...
                initiatorTruth, transponderTruth, physicalHardware, calibrationProduct);
            initiatorTruth.assertStateSource('physicalTruth');
            transponderTruth.assertStateSource('physicalTruth');
            physicalHardware.assertParameterSource('physicalTruth');
            calibrationProduct.assertParameterSource('calibrationProduct');
            revgnss.CoherentTwoWayCodeRangingModel.validatePair_( ...
                initiatorTruth, transponderTruth, physicalHardware, calibrationProduct);
            if ~(isscalar(finalReceptionCoordinateTime_s) && ...
                    isfinite(finalReceptionCoordinateTime_s))
                error('CoherentTwoWayCodeRangingModel:receptionTime', ...
                    'Final reception coordinate time must be finite.');
            end
            if ~(isscalar(trackingError_s) && isfinite(trackingError_s))
                error('CoherentTwoWayCodeRangingModel:trackingError', ...
                    'trackingError_s must be finite.');
            end
            if ~(isscalar(propagationGroupDelay_s) && ...
                    isfinite(propagationGroupDelay_s) && propagationGroupDelay_s >= 0)
                error('CoherentTwoWayCodeRangingModel:propagationDelay', ...
                    'Round-trip propagation group delay must be finite and nonnegative.');
            end
            metadata = revgnss.CoherentTwoWayCodeRangingModel.validateMetadata_(metadata);

            events = revgnss.CoherentTwoWayCodeRangingModel.solveEvents_( ...
                initiatorTruth, transponderTruth, physicalHardware, ...
                finalReceptionCoordinateTime_s, solverOptions);

            transmitTag_s = initiatorTruth.localTimeAt(events.t1_s);
            receiveTag_s = initiatorTruth.localTimeAt(events.t4_s);
            calibrationProduct.assertValidAt(receiveTag_s);
            physicalHardware.assertValidAt(receiveTag_s);

            measuredDelay_s = initiatorTruth.localClockRate * ...
                (events.forwardPropagationDelay_s + events.turnaroundCoordinate_s + ...
                events.returnPropagationDelay_s) + ...
                physicalHardware.initiatorTerminalGroupDelay_s + ...
                propagationGroupDelay_s + trackingError_s;
            trueTurnaroundEquivalent_s = initiatorTruth.localClockRate * ...
                physicalHardware.turnaroundProperTime_s / ...
                transponderTruth.properTimeRate;
            appliedTurnaroundEquivalent_s = initiatorTruth.localClockRate * ...
                calibrationProduct.turnaroundProperTime_s / ...
                transponderTruth.properTimeRate;
            processedRange_m = 0.5 * revgnss.CoherentTwoWayCodeRangingModel.SpeedOfLight_mps * ...
                (measuredDelay_s - calibrationProduct.initiatorTerminalGroupDelay_s - ...
                appliedTurnaroundEquivalent_s);

            record = struct();
            record.observationIdentifier = metadata.observationIdentifier;
            record.sessionIdentifier = metadata.sessionIdentifier;
            record.initiatorAssetIdentifier = initiatorTruth.assetIdentifier;
            record.transponderAssetIdentifier = transponderTruth.assetIdentifier;
            record.initiatorTransmitTerminalIdentifier = initiatorTruth.transmitTerminalIdentifier;
            record.initiatorReceiveTerminalIdentifier = initiatorTruth.receiveTerminalIdentifier;
            record.transponderReceiveTerminalIdentifier = transponderTruth.receiveTerminalIdentifier;
            record.transponderTransmitTerminalIdentifier = transponderTruth.transmitTerminalIdentifier;
            record.initiatorTransmitAntennaIdentifier = initiatorTruth.transmitAntennaIdentifier;
            record.initiatorReceiveAntennaIdentifier = initiatorTruth.receiveAntennaIdentifier;
            record.transponderReceiveAntennaIdentifier = transponderTruth.receiveAntennaIdentifier;
            record.transponderTransmitAntennaIdentifier = transponderTruth.transmitAntennaIdentifier;
            record.protocolIdentifier = revgnss.CoherentTwoWayCodeRangingModel.ProtocolIdentifier;
            record.signalIdentifier = metadata.signalIdentifier;
            record.channelIdentifier = metadata.channelIdentifier;
            record.forwardCarrierFrequency_Hz = ...
                metadata.forwardCarrierFrequency_Hz;
            record.returnCarrierFrequency_Hz = ...
                metadata.returnCarrierFrequency_Hz;
            record.codeChipRate_Hz = physicalHardware.codeChipRate_Hz;
            record.initiatorTransmitLocalClockTag_s = transmitTag_s;
            record.initiatorReceiveLocalClockTag_s = receiveTag_s;
            record.measuredLocalRoundTripDelay_s = measuredDelay_s;
            record.referenceLocalClockTag_s = receiveTag_s;
            record.referenceEpochRule = 'finalReception';
            record.localTimeSystemIdentifier = metadata.localTimeSystemIdentifier;
            record.timestampReferencePointIdentifier = ...
                metadata.timestampReferencePointIdentifier;
            record.commandedScheduleIdentifier = ...
                metadata.commandedScheduleIdentifier;
            record.processedObservableType = 'twoWayCodeRange';
            record.processedValue = processedRange_m;
            record.processedUnits = 'm';
            record.covarianceGroupIdentifier = metadata.covarianceGroupIdentifier;
            record.covarianceRowIndex = metadata.covarianceRowIndex;
            record.covarianceBlock = metadata.covarianceBlock_m2;
            record.covarianceUnits = 'm^2';
            record.calibrationProductIdentifiers = ...
                [{calibrationProduct.calibrationProductIdentifier}, ...
                metadata.additionalCalibrationProductIdentifiers];
            record.calibrationValidFromLocalTag_s = ...
                calibrationProduct.validFromLocalTag_s;
            record.calibrationValidUntilLocalTag_s = ...
                calibrationProduct.validUntilLocalTag_s;
            record.carrierToNoiseDensity_dBHz = metadata.carrierToNoiseDensity_dBHz;
            record.effectiveRangingBandwidth_Hz = ...
                metadata.effectiveRangingBandwidth_Hz;
            record.roundTripLinkMargin_dB = metadata.roundTripLinkMargin_dB;
            record.available = metadata.available;
            record.qualityFlags = metadata.qualityFlags;
            record.truthDiagnosticIdentifier = metadata.truthDiagnosticIdentifier;
            observation = revgnss.InterSatelliteObservationRecord(record);

            transmittedCodePhase_chips = mod(physicalHardware.codeChipRate_Hz * ...
                transmitTag_s, physicalHardware.codeLength_chips);
            returnedCodePhase_chips = physicalHardware.returnedCodePhase( ...
                transmittedCodePhase_chips);
            errors = struct( ...
                'terminalCalibrationError_s', ...
                    physicalHardware.initiatorTerminalGroupDelay_s - ...
                    calibrationProduct.initiatorTerminalGroupDelay_s, ...
                'turnaroundCalibrationErrorInInitiatorTime_s', ...
                    trueTurnaroundEquivalent_s - appliedTurnaroundEquivalent_s, ...
                'propagationGroupDelay_s', propagationGroupDelay_s, ...
                'trackingError_s', trackingError_s);

            values = struct();
            values.diagnosticIdentifier = metadata.truthDiagnosticIdentifier;
            values.t1TransmitCoordinateTime_s = events.t1_s;
            values.t2TransponderReceiveCoordinateTime_s = events.t2_s;
            values.t3TransponderTransmitCoordinateTime_s = events.t3_s;
            values.t4FinalReceptionCoordinateTime_s = events.t4_s;
            values.initiatorTransmitPhaseCentreAtT1_m = events.rA_tx_t1_m;
            values.transponderReceivePhaseCentreAtT2_m = events.rB_rx_t2_m;
            values.transponderTransmitPhaseCentreAtT3_m = events.rB_tx_t3_m;
            values.initiatorReceivePhaseCentreAtT4_m = events.rA_rx_t4_m;
            values.forwardGeometricRange_m = events.forwardRange_m;
            values.returnGeometricRange_m = events.returnRange_m;
            values.forwardLightTimeResidual_s = events.forwardResidual_s;
            values.returnLightTimeResidual_s = events.returnResidual_s;
            values.forwardIterationCount = events.forwardIterationCount;
            values.returnIterationCount = events.returnIterationCount;
            values.physicalTurnaroundProperTime_s = physicalHardware.turnaroundProperTime_s;
            values.turnaroundDelayDefinition = ...
                physicalHardware.turnaroundDelayDefinition;
            values.trueInitiatorTerminalGroupDelay_s = ...
                physicalHardware.initiatorTerminalGroupDelay_s;
            values.initiatorTerminalDelayDefinition = ...
                physicalHardware.initiatorTerminalDelayDefinition;
            values.trackingError_s = trackingError_s;
            values.propagationGroupDelay_s = propagationGroupDelay_s;
            values.trackedIncomingCodePhase_chips = transmittedCodePhase_chips;
            values.transmittedReturnCodePhase_chips = returnedCodePhase_chips;
            values.codeRateTurnaroundRatio = physicalHardware.codeRateTurnaroundRatio;
            values.carrierFrequencyTurnaroundRatio = ...
                physicalHardware.carrierFrequencyTurnaroundRatio;
            values.errorDecomposition_s = errors;
            values.referenceEpochRule = 'finalReception';
            truthDiagnostic = revgnss.truth.CoherentTwoWayCodeDiagnostic(values);
        end

        function [predictedRange_m, prediction] = predictProcessedRange( ...
                observation, initiatorEstimate, transponderEstimate, ...
                calibrationProduct, solverOptions, modeledPropagationGroupDelay_s)
            if nargin < 5
                solverOptions = struct();
            end
            if nargin < 6 || isempty(modeledPropagationGroupDelay_s)
                modeledPropagationGroupDelay_s = 0;
            end
            if ~(isscalar(modeledPropagationGroupDelay_s) && ...
                    isfinite(modeledPropagationGroupDelay_s) && ...
                    modeledPropagationGroupDelay_s >= 0)
                error('CoherentTwoWayCodeRangingModel:modeledPropagationDelay', ...
                    'Modeled round-trip propagation group delay must be finite and nonnegative.');
            end
            if ~isa(observation, 'revgnss.InterSatelliteObservationRecord')
                error('CoherentTwoWayCodeRangingModel:observationType', ...
                    'Prediction requires an InterSatelliteObservationRecord.');
            end
            if ~isa(initiatorEstimate, 'revgnss.TwoWayCodeEndpointModel') || ...
                    ~isa(transponderEstimate, 'revgnss.TwoWayCodeEndpointModel') || ...
                    ~isa(calibrationProduct, 'revgnss.CoherentTwoWayCodeHardwareModel')
                error('CoherentTwoWayCodeRangingModel:predictionType', ...
                    'Prediction requires estimator endpoint models and a hardware calibration product.');
            end
            initiatorEstimate.assertStateSource('estimatorState');
            transponderEstimate.assertStateSource('estimatorState');
            calibrationProduct.assertParameterSource('calibrationProduct');
            if ~strcmp(observation.protocolIdentifier, ...
                    revgnss.CoherentTwoWayCodeRangingModel.ProtocolIdentifier)
                error('CoherentTwoWayCodeRangingModel:protocol', ...
                    'Observation protocol is not coherent transponded PN two-way code.');
            end
            if ~strcmp(observation.initiatorAssetIdentifier, initiatorEstimate.assetIdentifier) || ...
                    ~strcmp(observation.transponderAssetIdentifier, transponderEstimate.assetIdentifier)
                error('CoherentTwoWayCodeRangingModel:endpointIdentity', ...
                    'Estimator endpoints do not match the observation record.');
            end

            finalReceptionCoordinateTime_s = initiatorEstimate.coordinateTimeAtLocalTag( ...
                observation.referenceLocalClockTag_s);
            calibrationProduct.assertValidAt(observation.referenceLocalClockTag_s);
            events = revgnss.CoherentTwoWayCodeRangingModel.solveEvents_( ...
                initiatorEstimate, transponderEstimate, calibrationProduct, ...
                finalReceptionCoordinateTime_s, solverOptions);

            predictedRawDelay_s = initiatorEstimate.localClockRate * ...
                (events.forwardPropagationDelay_s + events.turnaroundCoordinate_s + ...
                events.returnPropagationDelay_s) + ...
                calibrationProduct.initiatorTerminalGroupDelay_s + ...
                modeledPropagationGroupDelay_s;
            turnaroundEquivalent_s = initiatorEstimate.localClockRate * ...
                calibrationProduct.turnaroundProperTime_s / ...
                transponderEstimate.properTimeRate;
            predictedRange_m = 0.5 * revgnss.CoherentTwoWayCodeRangingModel.SpeedOfLight_mps * ...
                (predictedRawDelay_s - calibrationProduct.initiatorTerminalGroupDelay_s - ...
                turnaroundEquivalent_s);

            prediction = struct( ...
                'referenceEpochRule', 'finalReception', ...
                'referenceCoordinateTime_s', events.t4_s, ...
                't1_s', events.t1_s, 't2_s', events.t2_s, ...
                't3_s', events.t3_s, 't4_s', events.t4_s, ...
                'forwardPropagationDelay_s', events.forwardPropagationDelay_s, ...
                'returnPropagationDelay_s', events.returnPropagationDelay_s, ...
                'modeledPropagationGroupDelay_s', modeledPropagationGroupDelay_s, ...
                'forwardLightTimeResidual_s', events.forwardResidual_s, ...
                'returnLightTimeResidual_s', events.returnResidual_s);
        end

        function events = solvePhysicalEventGeometry( ...
                initiatorTruth,transponderTruth,physicalHardware, ...
                finalReceptionCoordinateTime_s,solverOptions)
            if nargin < 5
                solverOptions = struct();
            end
            if ~isa(initiatorTruth,'revgnss.TwoWayCodeEndpointModel') || ...
                    ~isa(transponderTruth,'revgnss.TwoWayCodeEndpointModel') || ...
                    ~isa(physicalHardware,'revgnss.CoherentTwoWayCodeHardwareModel')
                error('CoherentTwoWayCodeRangingModel:eventGeometryType', ...
                    'Physical event geometry requires two endpoints and one hardware model.');
            end
            initiatorTruth.assertStateSource('physicalTruth');
            transponderTruth.assertStateSource('physicalTruth');
            physicalHardware.assertParameterSource('physicalTruth');
            if strcmp(initiatorTruth.assetIdentifier, ...
                    transponderTruth.assetIdentifier)
                error('CoherentTwoWayCodeRangingModel:selfLink', ...
                    'Initiator and transponder must be different spacecraft.');
            end
            events = revgnss.CoherentTwoWayCodeRangingModel.solveEvents_( ...
                initiatorTruth,transponderTruth,physicalHardware, ...
                finalReceptionCoordinateTime_s,solverOptions);
        end
    end

    methods (Static, Access = private)
        function events = solveEvents_(initiator, transponder, hardware, ...
                t4_s, solverOptions)
            options = revgnss.CoherentTwoWayCodeRangingModel.solverOptions_(solverOptions);
            c = revgnss.CoherentTwoWayCodeRangingModel.SpeedOfLight_mps;

            rA_rx_t4_m = initiator.receivePhaseCentreAt(t4_s);
            [t3_s, returnDelay_s, returnIterations] = ...
                revgnss.CoherentTwoWayCodeRangingModel.solveRetardedTransmitTime_( ...
                    rA_rx_t4_m, t4_s, ...
                    @(time_s) transponder.transmitPhaseCentreAt(time_s), c, options);

            turnaroundCoordinate_s = ...
                transponder.coordinateDurationForProperDuration(hardware.turnaroundProperTime_s);
            t2_s = t3_s - turnaroundCoordinate_s;
            rB_rx_t2_m = transponder.receivePhaseCentreAt(t2_s);
            [t1_s, forwardDelay_s, forwardIterations] = ...
                revgnss.CoherentTwoWayCodeRangingModel.solveRetardedTransmitTime_( ...
                    rB_rx_t2_m, t2_s, ...
                    @(time_s) initiator.transmitPhaseCentreAt(time_s), c, options);

            rA_tx_t1_m = initiator.transmitPhaseCentreAt(t1_s);
            rB_tx_t3_m = transponder.transmitPhaseCentreAt(t3_s);
            forwardRange_m = norm(rB_rx_t2_m - rA_tx_t1_m);
            returnRange_m = norm(rA_rx_t4_m - rB_tx_t3_m);
            forwardResidual_s = forwardDelay_s - forwardRange_m / c;
            returnResidual_s = returnDelay_s - returnRange_m / c;
            if max(abs([forwardResidual_s, returnResidual_s])) > ...
                    10 * options.lightTimeTolerance_s
                error('CoherentTwoWayCodeRangingModel:lightTimeResidual', ...
                    'Four-event light-time equations did not close to the requested tolerance.');
            end
            if ~(t1_s <= t2_s && t2_s <= t3_s && t3_s <= t4_s)
                error('CoherentTwoWayCodeRangingModel:eventOrder', ...
                    'The solved four-event sequence is not time ordered.');
            end

            events = struct( ...
                't1_s', t1_s, 't2_s', t2_s, 't3_s', t3_s, 't4_s', t4_s, ...
                'rA_tx_t1_m', rA_tx_t1_m, 'rB_rx_t2_m', rB_rx_t2_m, ...
                'rB_tx_t3_m', rB_tx_t3_m, 'rA_rx_t4_m', rA_rx_t4_m, ...
                'forwardRange_m', forwardRange_m, 'returnRange_m', returnRange_m, ...
                'forwardPropagationDelay_s', forwardDelay_s, ...
                'returnPropagationDelay_s', returnDelay_s, ...
                'turnaroundCoordinate_s', turnaroundCoordinate_s, ...
                'forwardResidual_s', forwardResidual_s, ...
                'returnResidual_s', returnResidual_s, ...
                'forwardIterationCount', forwardIterations, ...
                'returnIterationCount', returnIterations);
        end

        function [transmitTime_s, delay_s, iterations] = solveRetardedTransmitTime_( ...
                receivePosition_m, receiveTime_s, transmitPositionFunction, c, options)
            delay_s = norm(receivePosition_m - ...
                transmitPositionFunction(receiveTime_s)) / c;
            converged = false;
            for iterations = 1:options.maximumIterations
                updatedDelay_s = norm(receivePosition_m - ...
                    transmitPositionFunction(receiveTime_s-delay_s)) / c;
                if iterations >= 3 && ...
                        abs(updatedDelay_s - delay_s) <= ...
                        options.lightTimeTolerance_s
                    delay_s = updatedDelay_s;
                    converged = true;
                    break
                end
                delay_s = updatedDelay_s;
            end
            if ~converged
                error('CoherentTwoWayCodeRangingModel:lightTimeConvergence', ...
                    'Retarded-time iteration did not converge.');
            end
            transmitTime_s = receiveTime_s-delay_s;
        end

        function options = solverOptions_(supplied)
            if isempty(supplied)
                supplied = struct();
            end
            if ~isstruct(supplied) || ~isscalar(supplied)
                error('CoherentTwoWayCodeRangingModel:solverOptions', ...
                    'solverOptions must be a scalar structure.');
            end
            allowed = {'lightTimeTolerance_s','maximumIterations'};
            unknown = setdiff(fieldnames(supplied), allowed);
            if ~isempty(unknown)
                error('CoherentTwoWayCodeRangingModel:solverOptions', ...
                    'Unsupported solver option %s.', unknown{1});
            end
            options = struct('lightTimeTolerance_s', 1e-13, 'maximumIterations', 50);
            for k = 1:numel(allowed)
                if isfield(supplied, allowed{k})
                    options.(allowed{k}) = supplied.(allowed{k});
                end
            end
            if ~(isscalar(options.lightTimeTolerance_s) && ...
                    isfinite(options.lightTimeTolerance_s) && options.lightTimeTolerance_s > 0)
                error('CoherentTwoWayCodeRangingModel:solverTolerance', ...
                    'lightTimeTolerance_s must be finite and positive.');
            end
            if ~(isscalar(options.maximumIterations) && ...
                    options.maximumIterations == round(options.maximumIterations) && ...
                    options.maximumIterations >= 1)
                error('CoherentTwoWayCodeRangingModel:solverIterations', ...
                    'maximumIterations must be a positive integer.');
            end
        end

        function validateTypes_(initiator, transponder, physicalHardware, calibration)
            if ~isa(initiator, 'revgnss.TwoWayCodeEndpointModel') || ...
                    ~isa(transponder, 'revgnss.TwoWayCodeEndpointModel') || ...
                    ~isa(physicalHardware, 'revgnss.CoherentTwoWayCodeHardwareModel') || ...
                    ~isa(calibration, 'revgnss.CoherentTwoWayCodeHardwareModel')
                error('CoherentTwoWayCodeRangingModel:inputType', ...
                    'Simulation requires endpoint and coherent hardware model objects.');
            end
        end

        function validatePair_(initiator, transponder, physicalHardware, calibration)
            if strcmp(initiator.assetIdentifier, transponder.assetIdentifier)
                error('CoherentTwoWayCodeRangingModel:selfLink', ...
                    'Initiator and transponder must be different spacecraft.');
            end
            if ~strcmp(physicalHardware.physicalChainIdentifier, ...
                    calibration.physicalChainIdentifier)
                error('CoherentTwoWayCodeRangingModel:calibrationChain', ...
                    'Calibration product does not identify the physical ranging chain.');
            end
        end

        function metadata = validateMetadata_(metadata)
            if ~isstruct(metadata) || ~isscalar(metadata)
                error('CoherentTwoWayCodeRangingModel:metadata', ...
                    'Observation metadata must be a scalar structure.');
            end
            required = {'observationIdentifier','sessionIdentifier','signalIdentifier', ...
                'covarianceGroupIdentifier','covarianceRowIndex','covarianceBlock_m2', ...
                'carrierToNoiseDensity_dBHz','available','qualityFlags', ...
                'truthDiagnosticIdentifier'};
            optionalDefaults = struct( ...
                'localTimeSystemIdentifier','initiatorOnboardClock', ...
                'timestampReferencePointIdentifier','initiatorReceiveTerminal', ...
                'commandedScheduleIdentifier','openLoopScenarioSchedule', ...
                'channelIdentifier','unspecifiedChannel', ...
                'forwardCarrierFrequency_Hz',NaN, ...
                'returnCarrierFrequency_Hz',NaN, ...
                'effectiveRangingBandwidth_Hz',NaN, ...
                'roundTripLinkMargin_dB',NaN, ...
                'additionalCalibrationProductIdentifiers',{{}});
            allowed = [required, fieldnames(optionalDefaults)'];
            unknown = setdiff(fieldnames(metadata), allowed);
            missing = setdiff(required, fieldnames(metadata));
            if ~isempty(unknown)
                error('CoherentTwoWayCodeRangingModel:metadata', ...
                    'Unsupported metadata field %s.', unknown{1});
            end
            if ~isempty(missing)
                error('CoherentTwoWayCodeRangingModel:metadata', ...
                    'Missing metadata field %s.', missing{1});
            end
            optionalNames = fieldnames(optionalDefaults);
            for fieldIndex = 1:numel(optionalNames)
                fieldName = optionalNames{fieldIndex};
                if ~isfield(metadata,fieldName)
                    metadata.(fieldName) = optionalDefaults.(fieldName);
                end
            end
            additionalIds = metadata.additionalCalibrationProductIdentifiers;
            if isstring(additionalIds)
                additionalIds = cellstr(additionalIds);
            end
            if ~iscell(additionalIds) || any(~cellfun(@(value) ...
                    ischar(value) || (isstring(value) && isscalar(value)), ...
                    additionalIds))
                error('CoherentTwoWayCodeRangingModel:metadata', ...
                    'Additional calibration identifiers must be a cell array of text.');
            end
            metadata.additionalCalibrationProductIdentifiers = ...
                cellfun(@char,additionalIds,'UniformOutput',false);
        end
    end
end
