classdef CoherentTwoWayRangeLinkUpdateAdapter
    % CoherentTwoWayRangeLinkUpdateAdapter  Plan Section 2.3.1 concrete adapter: the first real
    % revgnss.DistributedLinkUpdateAdapter for the coherent transponded PN two-way code range
    % observable. Reuses revgnss.CoherentTwoWayCodeRangingModel / revgnss.TwoWayCodeEndpointModel
    % for all physics; this file contains no range equation, no light-time iteration, and no
    % turnaround algebra. Truth-free: every input is either the immutable physical record, two
    % estimator-sourced revgnss.CommunicationEndpointState objects, or a configuration-derived
    % calibration product -- no simulation/asset/clock handle and no cfg is ever held here.
    %
    % ECEF -> ECI BRIDGE. revgnss.CommunicationEndpointState is frozen ECEF;
    % revgnss.TwoWayCodeEndpointModel takes inertial positions. estimatorEndpointModelFromState
    % performs the same conversion revgnss.TwoWayISLMeasurementBuilder.estimateEndpoint_ performs
    % (ecefStateToInertial + rotMatEcefToInertial*bodyToEcefRotation + first post-Newtonian
    % proper-time rate), so the underlying physics is identical to the joint reference path. This
    % is a controlled, cross-checked duplication (see tests/test_coherent_two_way_range_link_
    % update_adapter.m's cross-check against the joint linearizer's own output), not a
    % re-derivation: TwoWayISLMeasurementBuilder.estimateEndpoint_ is private to that class and
    % cannot be called from here.
    %
    % JACOBIANS. Both H_owner and H_remote are five-point central finite differences of the SAME
    % scalar residual, taken in EACH endpoint's OWN declared error coordinates
    % (columnPerturbationKinds dispatches per endpoint on its own covarianceComponentOrder /
    % attitudeErrorCoordinateConvention -- a mixed owner-Euler/remote-tangent pair is legal and
    % handled correctly, matching CommunicationEndpointStateProvider.requireCompatibleCovariance
    % Coordinates' own header). The tangent-mode attitude perturbation is the SAME right-
    % multiplicative body-frame rotation revgnss.AttitudeErrorStateKinematics.smallAnglePerturbedDcm
    % defines (C_new = C_nominal * Exp([delta]_x)), which is the operator the MEKF itself uses to
    % inject an attitude correction -- not a naive Euler-angle bump. Angular-rate columns are
    % declared and verified structurally zero: revgnss.TwoWayCodeEndpointModel.constantVelocity
    % installs a time-CONSTANT attitude function, so no rotation rate can enter the predicted
    % range at all.

    properties (Constant)
        ObservableIdentifier = 'coherentTwoWayCodeRange';
        SupportedPhysicalRecordClasses = {'revgnss.InterSatelliteObservationRecord'};
        SupportedProtocolIdentifier = 'coherentTranspondedPnTwoWayCode';
        SupportedProcessedObservableType = 'twoWayCodeRange';
        SupportedProcessedUnits = 'm';
        ReferenceEpochRule = 'finalReception';
        AttitudePitchGuard_rad = 1.3962634; % 80 deg: ZYX gimbal-adjacent guard (audit A16 / L2)
        RequiredPersistentCalibrationTreatment = 'rejected';
    end

    methods (Static)
        function [block, diagnostics] = buildUpdateBlock(args)
            required = {'delivery','ownerState','remoteState','calibrationProduct', ...
                'linearizationSteps','solverOptions','modeledPropagationGroupDelay_s', ...
                'weightSelectionRule','persistentCalibrationTreatment'};
            if ~isstruct(args) || ~isscalar(args)
                error('CoherentTwoWayRangeLinkUpdateAdapter:argsSchema', ...
                    'buildUpdateBlock requires a scalar struct.');
            end
            missing = setdiff(required,fieldnames(args));
            unknown = setdiff(fieldnames(args),required);
            if ~isempty(missing)
                error('CoherentTwoWayRangeLinkUpdateAdapter:argsSchema', ...
                    'buildUpdateBlock is missing argument %s.',missing{1});
            end
            if ~isempty(unknown)
                error('CoherentTwoWayRangeLinkUpdateAdapter:argsSchema', ...
                    'buildUpdateBlock received unsupported argument %s.',unknown{1});
            end

            delivery = args.delivery;
            ownerState = args.ownerState;
            remoteState = args.remoteState;
            if ~isa(delivery,'revgnss.LinkObservationDelivery')
                error('CoherentTwoWayRangeLinkUpdateAdapter:deliveryType', ...
                    'delivery must be a revgnss.LinkObservationDelivery.');
            end
            record = delivery.physicalObservationRecord;
            revgnss.CoherentTwoWayRangeLinkUpdateAdapter.requireSupportedRecord(record);

            revgnss.CommunicationEndpointStateProvider.requireSameEpochPair( ...
                ownerState, remoteState, delivery.coordinateEventEpoch_s);
            revgnss.CommunicationEndpointStateProvider.requireCompatibleCovarianceCoordinates( ...
                ownerState, remoteState);
            revgnss.CommunicationEndpointStateProvider.requireTerminalGeometryDeclared(ownerState);
            revgnss.CommunicationEndpointStateProvider.requireTerminalGeometryDeclared(remoteState);
            revgnss.CoherentTwoWayRangeLinkUpdateAdapter.requireTerminalGeometryMatchesRecord( ...
                ownerState, record, 'owner');
            revgnss.CoherentTwoWayRangeLinkUpdateAdapter.requireTerminalGeometryMatchesRecord( ...
                remoteState, record, 'remote');
            revgnss.CoherentTwoWayRangeLinkUpdateAdapter.requireLinearizableAttitude( ...
                ownerState, 'owner');
            revgnss.CoherentTwoWayRangeLinkUpdateAdapter.requireLinearizableAttitude( ...
                remoteState, 'remote');

            treatment = char(args.persistentCalibrationTreatment);
            if ~strcmp(treatment, ...
                    revgnss.CoherentTwoWayRangeLinkUpdateAdapter.RequiredPersistentCalibrationTreatment)
                error('CoherentTwoWayRangeLinkUpdateAdapter:persistentCalibrationTreatment', ...
                    'This adapter release supports only persistentCalibrationTreatment=''rejected''.');
            end
            if ~strcmp(treatment, delivery.persistentCalibrationTreatment)
                error('CoherentTwoWayRangeLinkUpdateAdapter:persistentCalibrationTreatmentMismatch', ...
                    'persistentCalibrationTreatment must equal the delivery''s own declared treatment.');
            end
            revgnss.CoherentTwoWayRangeLinkUpdateAdapter.requirePersistentCalibrationIsInert( ...
                args.calibrationProduct, record, treatment);

            if args.modeledPropagationGroupDelay_s ~= 0
                error('CoherentTwoWayRangeLinkUpdateAdapter:modeledPropagationGroupDelay', ...
                    'This adapter release requires modeledPropagationGroupDelay_s == 0 (plasma refused).');
            end

            if ownerState.canonicalPhysicalAssetIndex ~= delivery.ownerCanonicalIndex || ...
                    remoteState.canonicalPhysicalAssetIndex ~= delivery.remoteCanonicalIndex
                error('CoherentTwoWayRangeLinkUpdateAdapter:canonicalIndexMismatch', ...
                    'An endpoint state''s canonical physical asset index does not match its delivery.');
            end

            [predictedRange_m, prediction] = ...
                revgnss.CoherentTwoWayRangeLinkUpdateAdapter.predictProcessedRangeFromEndpointStates( ...
                ownerState, remoteState, delivery, args.calibrationProduct, args.solverOptions, ...
                args.modeledPropagationGroupDelay_s);
            residual_m = record.processedValue - predictedRange_m;

            [H_owner, ownerKinds] = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.jacobianRow_( ...
                ownerState, remoteState, delivery, args.calibrationProduct, args.solverOptions, ...
                args.modeledPropagationGroupDelay_s, args.linearizationSteps, 'owner');
            [H_remote, remoteKinds] = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.jacobianRow_( ...
                ownerState, remoteState, delivery, args.calibrationProduct, args.solverOptions, ...
                args.modeledPropagationGroupDelay_s, args.linearizationSteps, 'remote');

            Rind = record.covarianceBlock(record.covarianceRowIndex, record.covarianceRowIndex);
            if ~(isfinite(Rind) && Rind > 0)
                error('CoherentTwoWayRangeLinkUpdateAdapter:measurementCovariance', ...
                    'The record''s own-row measurement covariance must be finite and positive.');
            end
            remoteContribution_m2 = H_remote * remoteState.covarianceBlock * H_remote';
            remoteContribution_m2 = (remoteContribution_m2+remoteContribution_m2')/2;

            record_ = struct( ...
                'observationIdentifier',delivery.observationIdentifier, ...
                'deliveryIdentifier',delivery.deliveryIdentifier, ...
                'ownerAssetIdentifier',delivery.ownerAssetIdentifier, ...
                'remoteAssetIdentifier',delivery.remoteAssetIdentifier, ...
                'remoteProductIdentifier',delivery.remoteProductIdentifier, ...
                'coordinateEventEpoch_s',delivery.coordinateEventEpoch_s, ...
                'observableIdentifier',revgnss.CoherentTwoWayRangeLinkUpdateAdapter.ObservableIdentifier, ...
                'residual_m',residual_m, ...
                'ownerCovarianceComponentOrder',{ownerState.covarianceComponentOrder}, ...
                'remoteCovarianceComponentOrder',{remoteState.covarianceComponentOrder}, ...
                'ownerAttitudeErrorCoordinateConvention',ownerState.attitudeErrorCoordinateConvention, ...
                'remoteAttitudeErrorCoordinateConvention',remoteState.attitudeErrorCoordinateConvention, ...
                'ownerJacobian_mPerErrorUnit',H_owner, ...
                'remoteJacobian_mPerErrorUnit',H_remote, ...
                'independentMeasurementCovariance_m2',Rind, ...
                'remoteContributionCovariance_m2',remoteContribution_m2, ...
                'residualCovarianceAssembly','notAssembledInputsEligibleForSplitCovarianceIntersection', ...
                'persistentCalibrationTreatment',treatment, ...
                'calibrationStateIdentifiers',{{}}, ...
                'covarianceGroupIdentifiers',{{}}, ...
                'correlationPolicy','splitCovarianceIntersection', ...
                'weightSelectionRule',char(args.weightSelectionRule), ...
                'commonSourceContributionCovariances_m2',{{}}, ...
                'calibrationMappingJacobian_mPerCalibrationUnit',zeros(1,0), ...
                'calibrationStateUnits',{{}}, ...
                'persistentCalibrationReferenceLocalTag_s',NaN, ...
                'observableRowUnits','m');
            block = revgnss.DistributedLinkUpdateBlock(record_);

            diagnostics = struct( ...
                'predictedRange_m',predictedRange_m, ...
                'prediction',prediction, ...
                'ownerColumnPerturbationKinds',{ownerKinds}, ...
                'remoteColumnPerturbationKinds',{remoteKinds});
        end

        function [predictedRange_m, prediction] = predictProcessedRangeFromEndpointStates( ...
                ownerState, remoteState, delivery, calibrationProduct, solverOptions, ...
                modeledPropagationGroupDelay_s)
            ownerModel = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.estimatorEndpointModelFromState( ...
                ownerState, delivery.ownerRecordEndpointIdentifier);
            remoteModel = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.estimatorEndpointModelFromState( ...
                remoteState, delivery.remoteRecordEndpointIdentifier);
            [predictedRange_m, prediction] = revgnss.CoherentTwoWayCodeRangingModel.predictProcessedRange( ...
                delivery.physicalObservationRecord, ownerModel, remoteModel, calibrationProduct, ...
                solverOptions, modeledPropagationGroupDelay_s);
        end

        function endpointModel = estimatorEndpointModelFromState(endpointState, recordEndpointIdentifier)
            if ~isa(endpointState,'revgnss.CommunicationEndpointState')
                error('CoherentTwoWayRangeLinkUpdateAdapter:endpointStateType', ...
                    'estimatorEndpointModelFromState requires a revgnss.CommunicationEndpointState.');
            end
            rotation = revgnss.AttitudeKinematics.bodyToEcefRotation(endpointState.attitudeEulerZyx_rad);
            endpointModel = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.buildEndpointModel_( ...
                endpointState, recordEndpointIdentifier, endpointState.positionEcef_m, ...
                endpointState.velocityEcef_mps, rotation, endpointState.clockBias_m, ...
                endpointState.clockDriftRate_mps);
        end

        function kinds = columnPerturbationKinds(covarianceComponentOrder, attitudeErrorCoordinateConvention)
            if numel(covarianceComponentOrder) ~= 14
                error('CoherentTwoWayRangeLinkUpdateAdapter:componentOrder', ...
                    'covarianceComponentOrder must have exactly 14 entries (frozen v1 schema).');
            end
            if strcmp(char(attitudeErrorCoordinateConvention),'rightMultiplicativeLocalTangent_rad')
                attitudeKind = 'attitudeTangent';
            elseif strcmp(char(attitudeErrorCoordinateConvention),'eulerZYXError_rad')
                attitudeKind = 'attitudeEuler';
            else
                error('CoherentTwoWayRangeLinkUpdateAdapter:attitudeConvention', ...
                    'attitudeErrorCoordinateConvention must be a frozen v1 variant.');
            end
            kinds = [repmat({'position'},1,3), repmat({'velocity'},1,3), ...
                repmat({attitudeKind},1,3), repmat({'angularRate'},1,3), ...
                {'clockBias'}, {'clockDrift'}];
        end

        function text = describeObservable()
            text = struct( ...
                'observableIdentifier',revgnss.CoherentTwoWayRangeLinkUpdateAdapter.ObservableIdentifier, ...
                'protocolIdentifier',revgnss.CoherentTwoWayRangeLinkUpdateAdapter.SupportedProtocolIdentifier, ...
                'residualSignConvention','observedMinusPredicted', ...
                'jacobianQuantity','dPredictedObservablePerErrorCoordinate', ...
                'referenceEpochRule',revgnss.CoherentTwoWayRangeLinkUpdateAdapter.ReferenceEpochRule, ...
                'stencilIdentifier','fivePointCentral');
        end

        function requireSupportedRecord(record)
            if ~isa(record,'revgnss.InterSatelliteObservationRecord')
                error('CoherentTwoWayRangeLinkUpdateAdapter:recordType', ...
                    'This adapter requires a revgnss.InterSatelliteObservationRecord.');
            end
            if ~strcmp(record.protocolIdentifier, ...
                    revgnss.CoherentTwoWayRangeLinkUpdateAdapter.SupportedProtocolIdentifier)
                error('CoherentTwoWayRangeLinkUpdateAdapter:protocol', ...
                    'Record protocolIdentifier does not match this adapter''s supported protocol.');
            end
            if ~strcmp(record.processedObservableType, ...
                    revgnss.CoherentTwoWayRangeLinkUpdateAdapter.SupportedProcessedObservableType) || ...
                    ~strcmp(record.processedUnits, ...
                    revgnss.CoherentTwoWayRangeLinkUpdateAdapter.SupportedProcessedUnits)
                error('CoherentTwoWayRangeLinkUpdateAdapter:processedObservableType', ...
                    'Record processedObservableType/processedUnits do not match this adapter.');
            end
            if ~strcmp(record.referenceEpochRule,revgnss.CoherentTwoWayRangeLinkUpdateAdapter.ReferenceEpochRule)
                error('CoherentTwoWayRangeLinkUpdateAdapter:referenceEpochRule', ...
                    'Record referenceEpochRule does not match this adapter''s supported rule.');
            end
            if ~record.available
                error('CoherentTwoWayRangeLinkUpdateAdapter:recordUnavailable', ...
                    'The physical record is not available.');
            end
            idx = record.covarianceRowIndex;
            n = size(record.covarianceBlock,1);
            if ~(isnumeric(idx) && isscalar(idx) && idx == round(idx) && idx >= 1 && idx <= n)
                error('CoherentTwoWayRangeLinkUpdateAdapter:covarianceRowIndex', ...
                    'Record covarianceRowIndex is out of range for its own covarianceBlock.');
            end
        end

        function requireTerminalGeometryMatchesRecord(endpointState, record, role)
            if ~(ischar(role) && any(strcmp(role,{'owner','remote'})))
                error('CoherentTwoWayRangeLinkUpdateAdapter:role', ...
                    'role must be ''owner'' or ''remote''.');
            end
            terminal = endpointState.terminalGeometry;
            if strcmp(role,'owner')
                txTerminal = record.initiatorTransmitTerminalIdentifier;
                rxTerminal = record.initiatorReceiveTerminalIdentifier;
                txAntenna = record.initiatorTransmitAntennaIdentifier;
                rxAntenna = record.initiatorReceiveAntennaIdentifier;
            else
                txTerminal = record.transponderTransmitTerminalIdentifier;
                rxTerminal = record.transponderReceiveTerminalIdentifier;
                txAntenna = record.transponderTransmitAntennaIdentifier;
                rxAntenna = record.transponderReceiveAntennaIdentifier;
            end
            if ~strcmp(terminal.transmitTerminalIdentifier,txTerminal) || ...
                    ~strcmp(terminal.receiveTerminalIdentifier,rxTerminal) || ...
                    ~strcmp(terminal.transmitAntennaIdentifier,txAntenna) || ...
                    ~strcmp(terminal.receiveAntennaIdentifier,rxAntenna)
                error('CoherentTwoWayRangeLinkUpdateAdapter:terminalGeometryMismatch', ...
                    'The %s endpoint''s declared terminal geometry does not match the record''s own terminal/antenna identifiers.',role);
            end
        end

        function requireLinearizableAttitude(endpointState, role)
            pitch_rad = endpointState.attitudeEulerZyx_rad(2);
            guard = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.AttitudePitchGuard_rad;
            if ~(isfinite(pitch_rad) && abs(pitch_rad) <= guard)
                error('CoherentTwoWayRangeLinkUpdateAdapter:attitudeNotLinearizable', ...
                    'The %s endpoint''s pitch is too close to the ZYX gimbal singularity to linearize safely.',role);
            end
        end

        function requirePersistentCalibrationIsInert(calibrationProduct, record, treatment)
            if ~strcmp(treatment,'rejected')
                error('CoherentTwoWayRangeLinkUpdateAdapter:persistentCalibrationTreatment', ...
                    'Only persistentCalibrationTreatment=''rejected'' is supported by this method.');
            end
            if ~isa(calibrationProduct,'revgnss.CoherentTwoWayCodeHardwareModel')
                error('CoherentTwoWayRangeLinkUpdateAdapter:calibrationProductType', ...
                    'calibrationProduct must be a revgnss.CoherentTwoWayCodeHardwareModel.');
            end
            if ~isequal(calibrationProduct.calibrationCovariance_s2,zeros(2))
                error('CoherentTwoWayRangeLinkUpdateAdapter:persistentCalibrationNotInert', ...
                    ['persistentCalibrationTreatment=''rejected'' requires an exactly zero ' ...
                    'calibrationCovariance_s2; a nonzero persistent calibration uncertainty has ' ...
                    'no owner under this treatment.']);
            end
            if ~any(strcmp(calibrationProduct.calibrationProductIdentifier, ...
                    record.calibrationProductIdentifiers))
                error('CoherentTwoWayRangeLinkUpdateAdapter:persistentCalibrationNotInert', ...
                    'The calibration product''s identifier is not among the record''s own calibrationProductIdentifiers.');
            end
        end
    end

    methods (Static, Access = private)
        function endpointModel = buildEndpointModel_(endpointState, recordEndpointIdentifier, ...
                positionEcef_m, velocityEcef_mps, bodyToEcefRotation, clockBias_m, clockDriftRate_mps)
            t0 = endpointState.coordinateEpoch_s;
            [rI, vI] = models.frames.FrameTimeUtils.ecefStateToInertial( ...
                positionEcef_m, velocityEcef_mps, t0);
            bodyToInertial = models.frames.FrameTimeUtils.rotMatEcefToInertial(t0) * bodyToEcefRotation;
            c = revgnss.CoherentTwoWayCodeRangingModel.SpeedOfLight_mps;
            bias_s = clockBias_m / c;
            localClockRate = 1 + clockDriftRate_mps / c;
            properTimeRate = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.properTimeRate_(rI, vI);
            terminal = endpointState.terminalGeometry;
            endpointModel = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
                'estimatorState', recordEndpointIdentifier, rI, vI, t0, ...
                bodyToInertialRotation=bodyToInertial, ...
                transmitPhaseCentreOffset_body_m=terminal.transmitPhaseCentreOffset_body_m, ...
                receivePhaseCentreOffset_body_m=terminal.receivePhaseCentreOffset_body_m, ...
                transmitTerminalIdentifier=terminal.transmitTerminalIdentifier, ...
                receiveTerminalIdentifier=terminal.receiveTerminalIdentifier, ...
                transmitAntennaIdentifier=terminal.transmitAntennaIdentifier, ...
                receiveAntennaIdentifier=terminal.receiveAntennaIdentifier, ...
                clockLocalTimeAtReference_s=t0+bias_s, ...
                localClockRate=localClockRate, ...
                properTimeRate=properTimeRate);
        end

        function rate = properTimeRate_(rInertial_m, vInertial_mps)
            % Duplicated from TwoWayISLMeasurementBuilder.properTimeRate_ (private to that
            % class, so it cannot be called from here); identical formula, cross-checked
            % bit-for-bit in this adapter's own tests against the joint linearizer's prediction.
            c = revgnss.CoherentTwoWayCodeRangingModel.SpeedOfLight_mps;
            radius_m = norm(rInertial_m);
            if ~(isfinite(radius_m) && radius_m > 0) || any(~isfinite(vInertial_mps))
                error('CoherentTwoWayRangeLinkUpdateAdapter:properTimeState', ...
                    'Proper-time conversion requires a finite inertial state.');
            end
            rate = 1 - (revgnss.Constants.EARTH_GM_M3PS2/radius_m + ...
                0.5*dot(vInertial_mps,vInertial_mps))/c^2;
            if ~(isfinite(rate) && rate > 0)
                error('CoherentTwoWayRangeLinkUpdateAdapter:properTimeRate', ...
                    'Computed proper-time rate must be finite and positive.');
            end
        end

        function [H, kinds] = jacobianRow_(ownerState, remoteState, delivery, calibrationProduct, ...
                solverOptions, modeledPropagationGroupDelay_s, steps, role)
            % jacobianRow_  Computes H_owner (role='owner') or H_remote (role='remote') by
            % perturbing ONLY that endpoint's own state, in its own declared coordinates, while
            % the OTHER endpoint's model is built once, fixed, and reused for every column.
            if strcmp(role,'owner')
                perturbState = ownerState;
                fixedState = remoteState;
                perturbIdentifier = delivery.ownerRecordEndpointIdentifier;
                fixedIdentifier = delivery.remoteRecordEndpointIdentifier;
            else
                perturbState = remoteState;
                fixedState = ownerState;
                perturbIdentifier = delivery.remoteRecordEndpointIdentifier;
                fixedIdentifier = delivery.ownerRecordEndpointIdentifier;
            end
            kinds = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.columnPerturbationKinds( ...
                perturbState.covarianceComponentOrder, perturbState.attitudeErrorCoordinateConvention);
            nominalRotation = revgnss.AttitudeKinematics.bodyToEcefRotation( ...
                perturbState.attitudeEulerZyx_rad);

            fixedModel = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.estimatorEndpointModelFromState( ...
                fixedState, fixedIdentifier);

            H = zeros(1,14);
            for k = 1:14
                kind = kinds{k};
                if strcmp(kind,'angularRate')
                    H(k) = 0; % declared and structurally zero: constant-attitude endpoint model
                    continue
                end
                [stepSize, perturbFn] = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.stepAndPerturbFn_( ...
                    kind, k, steps, nominalRotation);
                predictAt = @(delta) revgnss.CoherentTwoWayRangeLinkUpdateAdapter.predictWithPerturbedRole_( ...
                    perturbState, perturbIdentifier, fixedModel, delivery, calibrationProduct, ...
                    solverOptions, modeledPropagationGroupDelay_s, role, perturbFn(delta));
                hp2 = predictAt(2*stepSize); hp1 = predictAt(stepSize);
                hm1 = predictAt(-stepSize); hm2 = predictAt(-2*stepSize);
                H(k) = (-hp2+8*hp1-8*hm1+hm2)/(12*stepSize);
            end
        end

        function [stepSize, perturbFn] = stepAndPerturbFn_(kind, columnIndex, steps, nominalRotation)
            switch kind
                case 'position'
                    axisIdx = columnIndex; % 1..3
                    stepSize = steps.positionStep_m;
                    perturbFn = @(delta) struct('positionDelta_m',revgnss.CoherentTwoWayRangeLinkUpdateAdapter.unitVector_(axisIdx,3)*delta, ...
                        'velocityDelta_mps',zeros(3,1),'rotation',nominalRotation,'clockBiasDelta_m',0,'clockDriftDelta_mps',0);
                case 'velocity'
                    axisIdx = columnIndex-3; % 4..6 -> 1..3
                    stepSize = steps.velocityStep_mps;
                    perturbFn = @(delta) struct('positionDelta_m',zeros(3,1), ...
                        'velocityDelta_mps',revgnss.CoherentTwoWayRangeLinkUpdateAdapter.unitVector_(axisIdx,3)*delta, ...
                        'rotation',nominalRotation,'clockBiasDelta_m',0,'clockDriftDelta_mps',0);
                case 'attitudeTangent'
                    axisIdx = columnIndex-6; % 7..9 -> 1..3
                    stepSize = steps.attitudeStep_rad;
                    perturbFn = @(delta) struct('positionDelta_m',zeros(3,1),'velocityDelta_mps',zeros(3,1), ...
                        'rotation',revgnss.AttitudeErrorStateKinematics.smallAnglePerturbedDcm( ...
                            nominalRotation,revgnss.CoherentTwoWayRangeLinkUpdateAdapter.unitVector_(axisIdx,3)*delta), ...
                        'clockBiasDelta_m',0,'clockDriftDelta_mps',0);
                case 'attitudeEuler'
                    axisIdx = columnIndex-6; % 7..9 -> 1..3
                    stepSize = steps.attitudeStep_rad;
                    perturbFn = @(delta) struct('positionDelta_m',zeros(3,1),'velocityDelta_mps',zeros(3,1), ...
                        'rotation',[],'eulerDelta_rad',revgnss.CoherentTwoWayRangeLinkUpdateAdapter.unitVector_(axisIdx,3)*delta, ...
                        'clockBiasDelta_m',0,'clockDriftDelta_mps',0);
                case 'clockBias'
                    stepSize = steps.clockBiasStep_m;
                    perturbFn = @(delta) struct('positionDelta_m',zeros(3,1),'velocityDelta_mps',zeros(3,1), ...
                        'rotation',nominalRotation,'clockBiasDelta_m',delta,'clockDriftDelta_mps',0);
                case 'clockDrift'
                    stepSize = steps.clockDriftStep_mps;
                    perturbFn = @(delta) struct('positionDelta_m',zeros(3,1),'velocityDelta_mps',zeros(3,1), ...
                        'rotation',nominalRotation,'clockBiasDelta_m',0,'clockDriftDelta_mps',delta);
                otherwise
                    error('CoherentTwoWayRangeLinkUpdateAdapter:columnKind', ...
                        'Unrecognised column perturbation kind %s.',kind);
            end
        end

        function e = unitVector_(axisIdx, n)
            e = zeros(n,1); e(axisIdx) = 1;
        end

        function value = predictWithPerturbedRole_(perturbState, perturbIdentifier, fixedModel, ...
                delivery, calibrationProduct, solverOptions, modeledPropagationGroupDelay_s, role, ...
                perturbation)
            if isfield(perturbation,'eulerDelta_rad')
                rotation = revgnss.AttitudeKinematics.bodyToEcefRotation( ...
                    perturbState.attitudeEulerZyx_rad + perturbation.eulerDelta_rad);
            else
                rotation = perturbation.rotation;
            end
            perturbedModel = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.buildEndpointModel_( ...
                perturbState, perturbIdentifier, ...
                perturbState.positionEcef_m + perturbation.positionDelta_m, ...
                perturbState.velocityEcef_mps + perturbation.velocityDelta_mps, ...
                rotation, ...
                perturbState.clockBias_m + perturbation.clockBiasDelta_m, ...
                perturbState.clockDriftRate_mps + perturbation.clockDriftDelta_mps);
            if strcmp(role,'owner')
                initiatorModel = perturbedModel; transponderModel = fixedModel;
            else
                initiatorModel = fixedModel; transponderModel = perturbedModel;
            end
            [value, ~] = revgnss.CoherentTwoWayCodeRangingModel.predictProcessedRange( ...
                delivery.physicalObservationRecord, initiatorModel, transponderModel, ...
                calibrationProduct, solverOptions, modeledPropagationGroupDelay_s);
        end
    end
end
