classdef EndpointStateProduct
    % EndpointStateProduct  Immutable local-estimator state product.

    properties (SetAccess = immutable)
        sourceAssetIdentifier (1,:) char
        sourceAssetName (1,:) char
        sourceAssetIndex (1,1) double
        sourceEpoch_s (1,1) double
        validAtEpoch_s (1,1) double
        deliveryEpoch_s (1,1) double
        sequenceIdentifier (1,:) char
        stateComponentOrder (1,:) cell
        covarianceComponentOrder (1,:) cell
        stateVector (:,1) double
        stateComponents (1,1) struct
        covarianceBlock (:,:) double
        processModelProvenance (1,1) struct
        qualityFlags (1,1) struct
    end

    methods
        function obj = EndpointStateProduct(product)
            required = {'sourceAssetIdentifier','sourceAssetName','sourceAssetIndex', ...
                'sourceEpoch_s','validAtEpoch_s','deliveryEpoch_s','sequenceIdentifier', ...
                'stateComponentOrder','covarianceComponentOrder','stateVector', ...
                'stateComponents','covarianceBlock', ...
                'processModelProvenance','qualityFlags'};
            supplied = fieldnames(product);
            missing = setdiff(required,supplied);
            unknown = setdiff(supplied,required);
            if ~isempty(missing)
                error('EndpointStateProduct:missingField', ...
                    'State product is missing %s.',missing{1});
            end
            if ~isempty(unknown)
                error('EndpointStateProduct:unknownField', ...
                    'State product contains unsupported field %s.',unknown{1});
            end
            if ~(isnumeric(product.sourceAssetIndex) && isscalar(product.sourceAssetIndex) && ...
                    isfinite(product.sourceAssetIndex) && ...
                    product.sourceAssetIndex == round(product.sourceAssetIndex) && ...
                    product.sourceAssetIndex >= 1)
                error('EndpointStateProduct:assetIndex', ...
                    'sourceAssetIndex must be a positive integer.');
            end
            epochs = [product.sourceEpoch_s,product.validAtEpoch_s,product.deliveryEpoch_s];
            if ~(isnumeric(epochs) && numel(epochs) == 3 && all(isfinite(epochs))) || ...
                    product.validAtEpoch_s ~= product.sourceEpoch_s || ...
                    product.deliveryEpoch_s < product.validAtEpoch_s
                error('EndpointStateProduct:epoch', ...
                    'Product epochs must be finite with delivery at or after validity.');
            end
            x = product.stateVector(:);
            P = product.covarianceBlock;
            if isempty(x) || any(~isfinite(x)) || ~isnumeric(P) || ...
                    size(P,1) ~= numel(x) || size(P,2) ~= numel(x) || ...
                    any(~isfinite(P),'all') || norm(P-P','fro') > 1e-10 || ...
                    min(eig((P+P')/2)) < -1e-10
                error('EndpointStateProduct:covariance', ...
                    'State product covariance must be finite, symmetric, PSD, and state-error aligned.');
            end
            order = product.stateComponentOrder;
            if ~(iscell(order) && numel(order) == numel(x) && ...
                    all(cellfun(@(v) ischar(v) || (isstring(v) && isscalar(v)),order)))
                error('EndpointStateProduct:stateOrder', ...
                    'stateComponentOrder must name every exported state component.');
            end
            covarianceOrder = product.covarianceComponentOrder;
            if ~(iscell(covarianceOrder) && numel(covarianceOrder) == numel(x) && ...
                    all(cellfun(@(v) ischar(v) || (isstring(v) && isscalar(v)),covarianceOrder)))
                error('EndpointStateProduct:covarianceOrder', ...
                    'covarianceComponentOrder must name every exported error coordinate.');
            end
            if ~(isstruct(product.stateComponents) && isstruct(product.processModelProvenance) && ...
                    isstruct(product.qualityFlags))
                error('EndpointStateProduct:provenance', ...
                    'State components, process provenance, and quality flags must be structs.');
            end
            if ~isfield(product.processModelProvenance,'attitudeCovarianceCoordinates') || ...
                    ~(ischar(product.processModelProvenance.attitudeCovarianceCoordinates) || ...
                    (isstring(product.processModelProvenance.attitudeCovarianceCoordinates) && ...
                    isscalar(product.processModelProvenance.attitudeCovarianceCoordinates)))
                error('EndpointStateProduct:attitudeCovarianceCoordinates', ...
                    'Process provenance must state the attitude covariance coordinates.');
            end

            obj.sourceAssetIdentifier = char(product.sourceAssetIdentifier);
            obj.sourceAssetName = char(product.sourceAssetName);
            obj.sourceAssetIndex = double(product.sourceAssetIndex);
            obj.sourceEpoch_s = double(product.sourceEpoch_s);
            obj.validAtEpoch_s = double(product.validAtEpoch_s);
            obj.deliveryEpoch_s = double(product.deliveryEpoch_s);
            obj.sequenceIdentifier = char(product.sequenceIdentifier);
            obj.stateComponentOrder = cellfun(@char,order,'UniformOutput',false);
            obj.covarianceComponentOrder = cellfun(@char,covarianceOrder,'UniformOutput',false);
            obj.stateVector = x;
            obj.stateComponents = product.stateComponents;
            obj.covarianceBlock = (P+P')/2;
            obj.processModelProvenance = product.processModelProvenance;
            obj.qualityFlags = product.qualityFlags;
        end

        function product = toStruct(obj)
            product = struct();
            names = properties(obj);
            for index = 1:numel(names)
                product.(names{index}) = obj.(names{index});
            end
        end
    end

    methods (Static)
        function product = fromLocalEstimator(sim, assetIndex, sourceEpoch_s, ...
                deliveryDelay_s, sequenceIdentifier)
            if ~(isa(sim,'revgnss.ReverseGNSSSimulation') && sim.isInit)
                error('EndpointStateProduct:simulation', ...
                    'An initialized local ReverseGNSSSimulation is required.');
            end
            if sim.lastEstimatedEpoch < 1 || sim.lastTruthEpoch ~= sim.lastEstimatedEpoch
                error('EndpointStateProduct:localUpdate', ...
                    'A state product requires a completed local update at its source epoch.');
            end
            expectedEpoch_s = sim.tVec(sim.lastEstimatedEpoch);
            if ~(isnumeric(sourceEpoch_s) && isscalar(sourceEpoch_s) && ...
                    isfinite(sourceEpoch_s) && sourceEpoch_s == expectedEpoch_s)
                error('EndpointStateProduct:sourceEpoch', ...
                    'sourceEpoch_s must equal the most recently completed local-update epoch.');
            end
            expectedAssetIndex = 1;
            if isfield(sim.cfg,'asset') && isfield(sim.cfg.asset,'physicalAssetIndex')
                expectedAssetIndex = sim.cfg.asset.physicalAssetIndex;
            end
            if assetIndex ~= expectedAssetIndex
                error('EndpointStateProduct:sourceAsset', ...
                    'sourceAssetIndex must identify the local estimator that produced the state.');
            end
            if ~(isnumeric(deliveryDelay_s) && isscalar(deliveryDelay_s) && ...
                    isfinite(deliveryDelay_s) && deliveryDelay_s >= 0)
                error('EndpointStateProduct:deliveryDelay', ...
                    'deliveryDelay_s must be finite and nonnegative.');
            end
            sm = sim.ekf.stateMap;
            stateIndices = [sm.r_idx(:);sm.v_idx(:);sm.euler_idx(:); ...
                sm.omega_idx(:);sm.b_rx_idx;sm.bdot_rx_idx];
            xMeasurement = sim.ekf.getMeasurementState();
            x = xMeasurement(stateIndices);
            P = sim.ekf.P(stateIndices,stateIndices);
            labels = [ ...
                {'positionEcefX_m','positionEcefY_m','positionEcefZ_m'}, ...
                {'velocityEcefX_mps','velocityEcefY_mps','velocityEcefZ_mps'}, ...
                {'attitudeRoll_rad','attitudePitch_rad','attitudeYaw_rad'}, ...
                {'angularRateX_radps','angularRateY_radps','angularRateZ_radps'}, ...
                {'clockBias_m','clockDrift_mps'}];
            covarianceLabels = [ ...
                {'positionErrorEcefX_m','positionErrorEcefY_m','positionErrorEcefZ_m'}, ...
                {'velocityErrorEcefX_mps','velocityErrorEcefY_mps','velocityErrorEcefZ_mps'}, ...
                {'attitudeRollError_rad','attitudePitchError_rad','attitudeYawError_rad'}, ...
                {'angularRateErrorX_radps','angularRateErrorY_radps','angularRateErrorZ_radps'}, ...
                {'clockBiasError_m','clockDriftError_mps'}];
            attitudeCovarianceCoordinates = 'eulerZYXError_rad';
            if strcmp(sim.ekf.attitudeParameterization,'quaternionErrorState')
                covarianceLabels(7:9) = {'attitudeTangentErrorX_rad', ...
                    'attitudeTangentErrorY_rad','attitudeTangentErrorZ_rad'};
                attitudeCovarianceCoordinates = 'rightMultiplicativeLocalTangent_rad';
            end
            provenance = struct('stateDefinition', ...
                'position, velocity, nominal attitude, angular rate, receiver clock', ...
                'attitudeCovarianceCoordinates',attitudeCovarianceCoordinates, ...
                'dynamicsMode',revgnss.EndpointStateProduct.field_( ...
                    sim.cfg,{'estimator','dynamics','mode'},'unspecified'), ...
                'clockModel',revgnss.EndpointStateProduct.field_( ...
                    sim.cfg,{'asset','clock','name'},'unspecified'), ...
                'timeStep_s',sim.cfg.simulation.dt_s);
            components = struct('positionEcef_m',x(1:3), ...
                'velocityEcef_mps',x(4:6), ...
                'attitudeEuler_rad',sim.ekf.getReportEulerRad(), ...
                'angularRate_radps',x(10:12), ...
                'clockBias_m',x(13), ...
                'clockDrift_mps',x(14));
            record = struct( ...
                'sourceAssetIdentifier',sprintf('spacecraft:%d',assetIndex), ...
                'sourceAssetName',sim.asset.name, ...
                'sourceAssetIndex',assetIndex, ...
                'sourceEpoch_s',sourceEpoch_s, ...
                'validAtEpoch_s',sourceEpoch_s, ...
                'deliveryEpoch_s',sourceEpoch_s+deliveryDelay_s, ...
                'sequenceIdentifier',sequenceIdentifier, ...
                'stateComponentOrder',{labels}, ...
                'covarianceComponentOrder',{covarianceLabels}, ...
                'stateVector',x, ...
                'stateComponents',components, ...
                'covarianceBlock',P, ...
                'processModelProvenance',provenance, ...
                'qualityFlags',struct('estimatorDerived',true, ...
                    'truthUsed',false,'diagnosticOnly',true,'consumedByEstimator',false));
            product = revgnss.EndpointStateProduct(record);
        end
    end

    methods (Static, Access = private)
        function value = field_(s,path,defaultValue)
            value = s;
            for index = 1:numel(path)
                if ~isstruct(value) || ~isfield(value,path{index})
                    value = defaultValue;
                    return
                end
                value = value.(path{index});
            end
            if isstring(value); value = char(value); end
        end
    end
end
