classdef FirstOrderReciprocalClockTransferLinkUpdateAdapter
    % FirstOrderReciprocalClockTransferLinkUpdateAdapter  Plan Section 2.3.2 concrete adapter:
    % the second revgnss.DistributedLinkUpdateAdapter, for the first-order reciprocal ISL
    % clock-difference observable. Reuses revgnss.ReciprocalTimeTransferModel for all physics;
    % this file contains no clock-difference equation of its own.
    %
    % ANALYTIC PARTIALS, NOT A STENCIL. Unlike revgnss.CoherentTwoWayRangeLinkUpdateAdapter (an
    % iterative light-time solve with no closed form), revgnss.ReciprocalTimeTransferModel
    % returns EXACT analytic partials (referenceClockPartial=-1, remoteClockPartial=+1, and
    % position/velocity partials that are IDENTICALLY zero whenever includeReciprocity=false,
    % which this release always passes -- see ReciprocityTermSupported). H_owner/H_remote are
    % therefore built by direct label lookup against each endpoint's own
    % covarianceComponentOrder, never by finite difference; attitude/angular-rate/clock-drift
    % columns are declared and structurally zero (the model has no dependence on them at all
    % while the reciprocity term is refused).
    %
    % NO ECEF -> ECI BRIDGE, NO PHASE-CENTRE LEVER ARM. Since the position/velocity partials are
    % always zero, the values fed into revgnss.ReciprocalTimeTransferModel.evaluate cannot affect
    % the residual or any Jacobian column beyond satisfying the model's own minimum-separation
    % validity check; revgnss.CommunicationEndpointState's own ECEF positionEcef_m/
    % velocityEcef_mps are used directly, with no frame conversion and no lever-arm correction.

    properties (Constant)
        ObservableIdentifier = 'firstOrderReciprocalClockTransfer';
        SupportedPhysicalRecordClasses = {'revgnss.InterSatelliteTimeTransferObservationRecord'};
        SupportedProtocolIdentifier = 'reciprocalTwoWayTimeTransfer';
        SupportedProcessedObservableType = 'twoWayClockDifference';
        SupportedProcessedUnits = 'm';
        ReferenceEpochRule = 'commonCoordinateEpoch';
        SupportedModeIdentifier = 'firstOrderReciprocal';
        RequiredPersistentCalibrationTreatment = 'rejected';
        ReciprocityTermSupported = false;
        RawTimestampTagsSupported = false;
    end

    methods (Static)
        function [block, diagnostics] = buildUpdateBlock(args)
            required = {'delivery','ownerState','remoteState','weightSelectionRule', ...
                'persistentCalibrationTreatment'};
            if ~isstruct(args) || ~isscalar(args)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:argsSchema', ...
                    'buildUpdateBlock requires a scalar struct.');
            end
            missing = setdiff(required,fieldnames(args));
            unknown = setdiff(fieldnames(args),required);
            if ~isempty(missing)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:argsSchema', ...
                    'buildUpdateBlock is missing argument %s.',missing{1});
            end
            if ~isempty(unknown)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:argsSchema', ...
                    'buildUpdateBlock received unsupported argument %s.',unknown{1});
            end

            delivery = args.delivery;
            ownerState = args.ownerState;
            remoteState = args.remoteState;
            if ~isa(delivery,'revgnss.LinkObservationDelivery')
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:deliveryType', ...
                    'delivery must be a revgnss.LinkObservationDelivery.');
            end
            record = delivery.physicalObservationRecord;
            revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.requireSupportedRecord(record);

            revgnss.CommunicationEndpointStateProvider.requireSameEpochPair( ...
                ownerState, remoteState, delivery.coordinateEventEpoch_s);
            revgnss.CommunicationEndpointStateProvider.requireCompatibleCovarianceCoordinates( ...
                ownerState, remoteState);
            revgnss.CommunicationEndpointStateProvider.requireTerminalGeometryDeclared(ownerState);
            revgnss.CommunicationEndpointStateProvider.requireTerminalGeometryDeclared(remoteState);
            revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter. ...
                requireTerminalIdentityMatchesRecord(ownerState, record, 'owner');
            revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter. ...
                requireTerminalIdentityMatchesRecord(remoteState, record, 'remote');

            treatment = char(args.persistentCalibrationTreatment);
            if ~strcmp(treatment, ...
                    revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter. ...
                    RequiredPersistentCalibrationTreatment)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:persistentCalibrationTreatment', ...
                    'This adapter release supports only persistentCalibrationTreatment=''rejected''.');
            end
            if ~strcmp(treatment, delivery.persistentCalibrationTreatment)
                error(['FirstOrderReciprocalClockTransferLinkUpdateAdapter:' ...
                    'persistentCalibrationTreatmentMismatch'], ...
                    'persistentCalibrationTreatment must equal the delivery''s own declared treatment.');
            end

            if ownerState.canonicalPhysicalAssetIndex ~= delivery.ownerCanonicalIndex || ...
                    remoteState.canonicalPhysicalAssetIndex ~= delivery.remoteCanonicalIndex
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:canonicalIndexMismatch', ...
                    'An endpoint state''s canonical physical asset index does not match its delivery.');
            end

            % Defense-in-depth: ownerState/remoteState are re-fetched from their providers here
            % (phase 5), not the same objects revgnss.LinkObservationDelivery.propose validated
            % at phase 4, so the same physical-validity check is re-run rather than trusted.
            revgnss.DistributedClockGaugeContract.requireEndpointPropagationDelayValid( ...
                ownerState, remoteState, record);

            referenceModelState = struct( ...
                'position_m',ownerState.positionEcef_m, ...
                'velocity_mps',ownerState.velocityEcef_mps, ...
                'clockBias_m',ownerState.clockBias_m);
            remoteModelState = struct( ...
                'position_m',remoteState.positionEcef_m, ...
                'velocity_mps',remoteState.velocityEcef_mps, ...
                'clockBias_m',remoteState.clockBias_m);
            result = revgnss.ReciprocalTimeTransferModel.evaluate( ...
                referenceModelState, remoteModelState, ...
                revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.SupportedModeIdentifier, ...
                false);
            predictedValue_m = result.value_m;
            residual_m = record.processedValue - predictedValue_m;

            H_owner = revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.jacobianRow_( ...
                ownerState.covarianceComponentOrder, result.referenceClockPartial);
            H_remote = revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.jacobianRow_( ...
                remoteState.covarianceComponentOrder, result.remoteClockPartial);

            Rind = record.covarianceBlock(record.covarianceRowIndex, record.covarianceRowIndex);
            if ~(isfinite(Rind) && Rind > 0)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:measurementCovariance', ...
                    'The record''s own-row measurement covariance must be finite and positive.');
            end
            remoteContribution_m2 = H_remote * remoteState.covarianceBlock * H_remote';
            remoteContribution_m2 = (remoteContribution_m2+remoteContribution_m2')/2;

            record_ = struct( ...
                'observationIdentifier',delivery.observationIdentifier, ...
                'deliveryIdentifier',delivery.deliveryIdentifier, ...
                'ownerAssetIdentifier',delivery.ownerAssetIdentifier, ...
                'remoteAssetIdentifier',delivery.remoteAssetIdentifier, ...
                'remoteProductIdentifier',delivery.remoteProductIdentifier, ...
                'coordinateEventEpoch_s',delivery.coordinateEventEpoch_s, ...
                'observableIdentifier', ...
                    revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.ObservableIdentifier, ...
                'residual_m',residual_m, ...
                'ownerCovarianceComponentOrder',{ownerState.covarianceComponentOrder}, ...
                'remoteCovarianceComponentOrder',{remoteState.covarianceComponentOrder}, ...
                'ownerAttitudeErrorCoordinateConvention',ownerState.attitudeErrorCoordinateConvention, ...
                'remoteAttitudeErrorCoordinateConvention',remoteState.attitudeErrorCoordinateConvention, ...
                'ownerJacobian_mPerErrorUnit',H_owner, ...
                'remoteJacobian_mPerErrorUnit',H_remote, ...
                'independentMeasurementCovariance_m2',Rind, ...
                'remoteContributionCovariance_m2',remoteContribution_m2, ...
                'residualCovarianceAssembly','notAssembledInputsEligibleForSplitCovarianceIntersection', ...
                'persistentCalibrationTreatment',treatment, ...
                'calibrationStateIdentifiers',{{}}, ...
                'covarianceGroupIdentifiers',{{}}, ...
                'correlationPolicy','splitCovarianceIntersection', ...
                'weightSelectionRule',char(args.weightSelectionRule), ...
                'commonSourceContributionCovariances_m2',{{}}, ...
                'calibrationMappingJacobian_mPerCalibrationUnit',zeros(1,0), ...
                'calibrationStateUnits',{{}}, ...
                'persistentCalibrationReferenceLocalTag_s',NaN);
            block = revgnss.DistributedLinkUpdateBlock(record_);

            diagnostics = struct( ...
                'predictedValue_m',predictedValue_m, ...
                'prediction',result);
        end

        function text = describeObservable()
            text = struct( ...
                'observableIdentifier', ...
                    revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.ObservableIdentifier, ...
                'protocolIdentifier', ...
                    revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.SupportedProtocolIdentifier, ...
                'residualSignConvention','observedMinusPredicted', ...
                'jacobianQuantity','dPredictedObservablePerErrorCoordinate', ...
                'referenceEpochRule', ...
                    revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.ReferenceEpochRule, ...
                'stencilIdentifier','analyticModelPartials');
        end

        function requireSupportedRecord(record)
            if ~isa(record,'revgnss.InterSatelliteTimeTransferObservationRecord')
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:recordType', ...
                    'This adapter requires a revgnss.InterSatelliteTimeTransferObservationRecord.');
            end
            if ~strcmp(record.protocolIdentifier, ...
                    revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.SupportedProtocolIdentifier)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:protocol', ...
                    'Record protocolIdentifier does not match this adapter''s supported protocol.');
            end
            if ~strcmp(record.processedObservableType, ...
                    revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter. ...
                    SupportedProcessedObservableType) || ...
                    ~strcmp(record.processedUnits, ...
                    revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.SupportedProcessedUnits)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:processedObservableType', ...
                    'Record processedObservableType/processedUnits do not match this adapter.');
            end
            if ~strcmp(record.referenceEpochRule, ...
                    revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.ReferenceEpochRule)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:referenceEpochRule', ...
                    'Record referenceEpochRule does not match this adapter''s supported rule.');
            end
            if ~strcmp(record.modeIdentifier, ...
                    revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.SupportedModeIdentifier)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:mode', ...
                    'Record modeIdentifier does not match this adapter''s supported mode.');
            end
            if record.rawTimestampTagsAvailable && ...
                    ~revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.RawTimestampTagsSupported
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:rawTimestampTagsUnsupported', ...
                    'A raw four-timestamp claim is not supported by this adapter release.');
            end
            if record.reciprocityTermIncluded && ...
                    ~revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter.ReciprocityTermSupported
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:reciprocityTermUnsupported', ...
                    'The reciprocity term is not supported by this adapter release.');
            end
            if ~record.available
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:recordUnavailable', ...
                    'The physical record is not available.');
            end
            idx = record.covarianceRowIndex;
            n = size(record.covarianceBlock,1);
            if ~(isnumeric(idx) && isscalar(idx) && idx == round(idx) && idx >= 1 && idx <= n)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:covarianceRowIndex', ...
                    'Record covarianceRowIndex is out of range for its own covarianceBlock.');
            end
        end

        function requireTerminalIdentityMatchesRecord(endpointState, record, role)
            if ~(ischar(role) && any(strcmp(role,{'owner','remote'})))
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:role', ...
                    'role must be ''owner'' or ''remote''.');
            end
            terminal = endpointState.terminalGeometry;
            if strcmp(role,'owner')
                expectedTerminal = record.referenceTerminalIdentifier;
            else
                expectedTerminal = record.remoteTerminalIdentifier;
            end
            if ~strcmp(terminal.transmitTerminalIdentifier,expectedTerminal) || ...
                    ~strcmp(terminal.receiveTerminalIdentifier,expectedTerminal)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:terminalGeometryMismatch', ...
                    ['The %s endpoint''s declared terminal geometry does not match the record''s ' ...
                    'own terminal identifier.'],role);
            end
        end
    end

    methods (Static, Access = private)
        function H = jacobianRow_(covarianceComponentOrder, clockBiasPartial)
            % jacobianRow_  Direct label lookup, not a stencil: revgnss.ReciprocalTimeTransferModel
            % is closed-form and its position/velocity/attitude partials are identically zero
            % whenever includeReciprocity=false (this adapter's only supported mode), so every
            % column but clockBiasError_m is declared and structurally zero here rather than
            % computed.
            n = numel(covarianceComponentOrder);
            H = zeros(1,n);
            index = find(strcmp(covarianceComponentOrder,'clockBiasError_m'),1);
            if isempty(index)
                error('FirstOrderReciprocalClockTransferLinkUpdateAdapter:componentOrder', ...
                    'covarianceComponentOrder does not declare ''clockBiasError_m''.');
            end
            H(index) = clockBiasPartial;
        end
    end
end
