classdef FrozenProductEndpointProvider
    % FrozenProductEndpointProvider  Remote-side revgnss.CommunicationEndpointStateProvider.
    %
    % Built only from a frozen, already-validated revgnss.EstimatorEligibleEndpointStateProduct
    % -- never from a live neighbour simulation object, and never from truth. A raw
    % revgnss.EndpointStateProduct is refused by type: that is the Section 2.0.4 diagnostic /
    % estimator-eligible separation, enforced structurally rather than by convention.

    properties (SetAccess = immutable)
        endpointIdentifier (1,:) char
        canonicalPhysicalAssetIndex (1,1) double
        remoteProductIdentifier (1,:) char
        declaredEvaluationPolicy (1,:) char
        frozenEpoch_s (1,1) double
        frozenState (1,1)
    end

    methods (Access = private)
        function obj = FrozenProductEndpointProvider(endpointIdentifier, ...
                canonicalPhysicalAssetIndex, remoteProductIdentifier, ...
                declaredEvaluationPolicy, frozenEpoch_s, frozenState)
            if ~isa(frozenState,'revgnss.CommunicationEndpointState')
                error('FrozenProductEndpointProvider:frozenStateType', ...
                    'frozenState must be a revgnss.CommunicationEndpointState.');
            end
            obj.endpointIdentifier = endpointIdentifier;
            obj.canonicalPhysicalAssetIndex = canonicalPhysicalAssetIndex;
            obj.remoteProductIdentifier = remoteProductIdentifier;
            obj.declaredEvaluationPolicy = declaredEvaluationPolicy;
            obj.frozenEpoch_s = frozenEpoch_s;
            obj.frozenState = frozenState;
        end
    end

    methods
        function state = stateAtCoordinateEpoch(obj, coordinateEpoch_s)
            if ~(isnumeric(coordinateEpoch_s) && isscalar(coordinateEpoch_s) && ...
                    isfinite(coordinateEpoch_s) && coordinateEpoch_s == obj.frozenEpoch_s)
                error('FrozenProductEndpointProvider:epochOutsideFrozenScope', ...
                    'This provider is frozen at one coordinate epoch only.');
            end
            state = obj.frozenState;
        end
    end

    methods (Static)
        function provider = fromEstimatorEligibleProduct(product, deliveryEpoch_s, terminalGeometry)
            if nargin < 3 || isempty(terminalGeometry)
                terminalGeometry = revgnss.FrozenProductEndpointProvider.undeclaredTerminalGeometry_();
            end
            if ~isa(product,'revgnss.EstimatorEligibleEndpointStateProduct')
                error('FrozenProductEndpointProvider:productType', ...
                    'A revgnss.EstimatorEligibleEndpointStateProduct is required.');
            end
            % Re-run at the DELIVERY epoch: this is what rejects a delayed/aged product with a
            % stated reason rather than silently treating it as current (Section 2.1 rule 3).
            revgnss.DistributedLinkProtocolContract.requireDeliveryProvenance( ...
                product.diagnosticProduct,deliveryEpoch_s);
            if ~strcmp(product.declaredRemoteProductPropagationPolicy,'frozenSameEpochOnly')
                error('FrozenProductEndpointProvider:propagationPolicy', ...
                    'Only the frozen same-epoch-only remote-product propagation policy is supported.');
            end

            productAge_s = deliveryEpoch_s - product.diagnosticProduct.validAtEpoch_s;
            endpointIdentifier = sprintf('spacecraft:%d',product.canonicalPhysicalAssetIndex);
            components = product.diagnosticProduct.stateComponents;
            stateRecord = struct( ...
                'endpointIdentifier',endpointIdentifier, ...
                'canonicalPhysicalAssetIndex',product.canonicalPhysicalAssetIndex, ...
                'stateSource','estimatorState', ...
                'stateOrigin','frozenRemoteProduct', ...
                'coordinateEpoch_s',deliveryEpoch_s, ...
                'stateEvaluationPolicy','frozenSameEpochOnly', ...
                'coordinateTimeScale',product.coordinateTimeScale, ...
                'frameIdentifier',product.frameIdentifier, ...
                'clockDatumIdentifier',product.clockDatumIdentifier, ...
                'stateSchemaVersion',product.stateSchemaVersion, ...
                'attitudeErrorCoordinateConvention',product.attitudeErrorCoordinateConvention, ...
                'stateComponentOrder',{product.diagnosticProduct.stateComponentOrder}, ...
                'covarianceComponentOrder',{product.diagnosticProduct.covarianceComponentOrder}, ...
                'stateVector',product.diagnosticProduct.stateVector, ...
                'covarianceBlock',product.diagnosticProduct.covarianceBlock, ...
                'positionEcef_m',components.positionEcef_m, ...
                'velocityEcef_mps',components.velocityEcef_mps, ...
                'attitudeEulerZyx_rad',components.attitudeEuler_rad, ...
                'angularRateBody_radps',components.angularRate_radps, ...
                'clockBias_m',components.clockBias_m, ...
                'clockDriftRate_mps',components.clockDrift_mps, ...
                'terminalGeometry',terminalGeometry, ...
                'productProvenance',struct( ...
                    'sourceKind','estimatorEligibleProduct', ...
                    'productIdentifier',product.productIdentifier, ...
                    'sequenceIdentifier',product.diagnosticProduct.sequenceIdentifier, ...
                    'sourceEpoch_s',product.sourceEpoch_s, ...
                    'deliveryEpoch_s',deliveryEpoch_s, ...
                    'productAge_s',productAge_s, ...
                    'dynamicsMode',product.diagnosticProduct.processModelProvenance.dynamicsMode, ...
                    'clockModel',product.diagnosticProduct.processModelProvenance.clockModel, ...
                    'timeStep_s',product.diagnosticProduct.processModelProvenance.timeStep_s), ...
                'qualityFlags',product.qualityFlags, ...
                'clockAnchorDeclaration',product.clockAnchorDeclaration);
            frozenState = revgnss.CommunicationEndpointState(stateRecord);

            provider = revgnss.FrozenProductEndpointProvider(endpointIdentifier, ...
                product.canonicalPhysicalAssetIndex,product.productIdentifier, ...
                'frozenSameEpochOnly',deliveryEpoch_s,frozenState);
        end
    end

    methods (Static, Access = private)
        function geometry = undeclaredTerminalGeometry_()
            geometry = struct('declared',false, ...
                'transmitTerminalIdentifier','terminal:undeclared', ...
                'receiveTerminalIdentifier','terminal:undeclared', ...
                'transmitAntennaIdentifier','antenna:undeclared', ...
                'receiveAntennaIdentifier','antenna:undeclared', ...
                'transmitPhaseCentreOffset_body_m',zeros(3,1), ...
                'receivePhaseCentreOffset_body_m',zeros(3,1));
        end
    end
end
