classdef GroundRelayOneWayPassRecordBuilder
    % GroundRelayOneWayPassRecordBuilder  Plan Section 4.5: the truth-side 'relayTransit' adapter
    % for ONE direction of a classical relay TWSTFT session (source -> relay -> destination).
    % Public analogue of revgnss.DirectReciprocalTimeTransferBuilder's private assembleDirect_,
    % but for revgnss.ReciprocalTimestampEventModel.solveRelayTransit -- the classical TWSTFT
    % topology (station A -> relay S -> station B, AND station B -> relay S -> station A) needs
    % TWO independent calls to this builder (one per direction), never one 8-tag call:
    % revgnss.FourTimestampClockDifferenceObservable's own combination formula relies on tags(1)/
    % (4) sharing one clock and tags(2)/(3) sharing another -- true for a direct round trip, FALSE
    % for a one-way relay pass (tags 1 and 4 here are two DIFFERENT station clocks). Combining two
    % of these records into one session-level clock difference is
    % revgnss.GroundRelaySessionObservableBuilder's job, not this class's.
    %
    % Covariance is assembled ONLY from counterTagNoiseBlock and atmosphereBlock at this per-pass
    % level -- terminalModemDelayBlock and relayBlock are ALWAYS called with [] here (no
    % double-count): all shared/calibration uncertainty (relay group delay, both stations'
    % terminal delay, shared atmosphere) lives exactly once, at SESSION level, assembled by
    % revgnss.GroundRelayTimeTransferSessionBuilder via revgnss.ReciprocalTimeTransferCovarianceBuilder.
    % relayBlock (that method's first real, non-empty caller).
    %
    % localClockTags_s stay RAW here -- no terminal-delay or atmosphere-value correction is baked
    % in (matches revgnss.ReciprocalTimestampExchangeRecord's own documented RAW-TAGS-ONLY design
    % intent). revgnss.GroundRelaySessionObservableBuilder.combine applies both corrections, once,
    % when it builds the session-level observable from a pair of these records.
    %
    % Both propagation legs of a one-way relay pass (leg 1: source->relay, events (1,2); leg 2:
    % relay->destination, events (3,4)) are GROUND-SPACE legs (a bent-pipe relay is transparent to
    % atmosphere -- it has no atmosphere-dependent behaviour of its own), so legAppliesAtmosphere
    % is [true true true true] whenever atmosphere is applied, never split per-leg.

    methods (Static)
        function record = buildOneWayPass(sourceEndpoint, relayEndpoint, destinationEndpoint, ...
                hardwareForSolver, t4_s, atmosphereLegVariance_s2, options)
            arguments
                sourceEndpoint
                relayEndpoint
                destinationEndpoint
                hardwareForSolver (1,1) revgnss.ReciprocalLinkHardwareModel
                t4_s (1,1) double
                atmosphereLegVariance_s2 (1,:) double = []
                options.exchangeIdentifier (1,:) char = ''
                options.sessionIdentifier (1,:) char = ''
                options.protocolIdentifier (1,:) char = ''
                options.signalIdentifier (1,:) char = ''
                options.channelIdentifier (1,:) char = ''
                options.carrierFrequency_Hz (1,:) double = []
                options.counterTagSigma_s (1,:) double = []
                options.counterTagLabels (1,:) cell = {}
                options.applyAtmosphere (1,1) logical = false
                options.referenceEpochRule (1,:) char = 'finalReception'
                options.qualityFlags (1,1) struct = struct()
                options.truthDiagnosticIdentifier (1,:) char = ''
                options.solverOptions (1,1) struct = struct()
            end
            revgnss.GroundRelayOneWayPassRecordBuilder.requireOptions_(options);

            events = revgnss.ReciprocalTimestampEventModel.solveRelayTransit( ...
                sourceEndpoint, relayEndpoint, destinationEndpoint, hardwareForSolver, t4_s, ...
                options.solverOptions);
            chainEndpoints = {sourceEndpoint.assetIdentifier, relayEndpoint.assetIdentifier, ...
                relayEndpoint.assetIdentifier, destinationEndpoint.assetIdentifier};
            tags_s = revgnss.ReciprocalTimestampEventModel.localClockTags(events, ...
                {sourceEndpoint, relayEndpoint, relayEndpoint, destinationEndpoint});

            hardwareForSolver.assertValidAt(tags_s(4));

            if options.applyAtmosphere && isempty(atmosphereLegVariance_s2)
                error('GroundRelayOneWayPassRecordBuilder:atmosphereVarianceRequired', ...
                    'applyAtmosphere=true requires a nonempty atmosphereLegVariance_s2.');
            end
            if ~options.applyAtmosphere && ~isempty(atmosphereLegVariance_s2)
                error('GroundRelayOneWayPassRecordBuilder:atmosphereVarianceNotApplicable', ...
                    'atmosphereLegVariance_s2 must not be supplied when applyAtmosphere=false.');
            end

            covBuilder = revgnss.ReciprocalTimeTransferCovarianceBuilder;
            blocks = { ...
                covBuilder.counterTagNoiseBlock(options.counterTagSigma_s, options.counterTagLabels), ...
                covBuilder.terminalModemDelayBlock([]), ...
                covBuilder.productCalibrationBlock([]), ...
                covBuilder.atmosphereBlock(atmosphereLegVariance_s2), ...
                covBuilder.relayBlock([]), ...
                covBuilder.sessionCommonModeBlock([])};
            [covarianceBlock, componentOrder, ~] = covBuilder.assemble(blocks);

            if isscalar(options.carrierFrequency_Hz)
                chainFrequency_Hz = repmat(options.carrierFrequency_Hz,1,4);
            else
                chainFrequency_Hz = options.carrierFrequency_Hz;
            end

            record = revgnss.ReciprocalTimestampExchangeRecord(struct( ...
                'exchangeIdentifier', options.exchangeIdentifier, ...
                'sessionIdentifier', options.sessionIdentifier, ...
                'topologyKind', 'relayTransit', ...
                'chainEndpointIdentifiers', {chainEndpoints}, ...
                'chainTerminalIdentifiers', {{sourceEndpoint.transmitTerminalIdentifier, ...
                    relayEndpoint.receiveTerminalIdentifier, relayEndpoint.transmitTerminalIdentifier, ...
                    destinationEndpoint.receiveTerminalIdentifier}}, ...
                'localClockCompareEndpointIdentifiers', ...
                {{sourceEndpoint.assetIdentifier, destinationEndpoint.assetIdentifier}}, ...
                'referenceEpochRule', options.referenceEpochRule, ...
                'referenceCoordinateEpoch_s', t4_s, ...
                'coordinateTimeEvents_s', [events.t1_s, events.t2_s, events.t3_s, events.t4_s], ...
                'localClockTags_s', tags_s, ...
                'localClockTagAvailable', true(1,4), ...
                'localTimeSystemIdentifiers', {chainEndpoints}, ...
                'protocolIdentifier', options.protocolIdentifier, ...
                'signalIdentifier', options.signalIdentifier, ...
                'channelIdentifier', options.channelIdentifier, ...
                'chainCarrierFrequency_Hz', chainFrequency_Hz, ...
                'legAppliesAtmosphere', repmat(options.applyAtmosphere,1,4), ...
                'calibrationProductIdentifiers', {{hardwareForSolver.calibrationProductIdentifier}}, ...
                'covarianceGroupIdentifiers', {{}}, ...
                'covarianceBlock', covarianceBlock, ...
                'covarianceComponentOrder', {componentOrder}, ...
                'covarianceUnits', 's^2', ...
                'qualityFlags', options.qualityFlags, ...
                'availability', true, ...
                'truthDiagnosticIdentifier', options.truthDiagnosticIdentifier));
        end
    end

    methods (Static, Access = private)
        function requireOptions_(options)
            required = {'exchangeIdentifier','sessionIdentifier','protocolIdentifier', ...
                'signalIdentifier','channelIdentifier'};
            for k = 1:numel(required)
                if isempty(options.(required{k}))
                    error('GroundRelayOneWayPassRecordBuilder:missingRequiredOption', ...
                        '%s is required and was not supplied.',required{k});
                end
            end
            if isempty(options.carrierFrequency_Hz)
                error('GroundRelayOneWayPassRecordBuilder:missingRequiredOption', ...
                    'carrierFrequency_Hz is required and was not supplied.');
            end
            if ~(isscalar(options.carrierFrequency_Hz) || numel(options.carrierFrequency_Hz) == 4) || ...
                    any(~isfinite(options.carrierFrequency_Hz)) || any(options.carrierFrequency_Hz <= 0)
                error('GroundRelayOneWayPassRecordBuilder:carrierFrequency', ...
                    'carrierFrequency_Hz must be a finite positive scalar or 1-by-4 vector.');
            end
            % Combined review m9: an empty counterTagSigma_s with applyAtmosphere=false leaves the
            % assembled covarianceBlock 0x0, which revgnss.ReciprocalTimestampExchangeRecord's own
            % constructor then rejects with a foreign, confusing error identifier
            % (ReciprocalTimestampExchangeRecord:covarianceBlock) rather than this class's own
            % ClassName:reason convention -- fail loudly and clearly here instead.
            if isempty(options.counterTagSigma_s)
                error('GroundRelayOneWayPassRecordBuilder:missingRequiredOption', ...
                    'counterTagSigma_s is required and was not supplied.');
            end
        end
    end
end
