classdef IndependentFleetCoordinator < handle
    % IndependentFleetCoordinator  Epoch-synchronous independent local EKFs.

    properties
        cfg (1,1) struct
        localSimulations cell = {}
        exchangeJournal = []
        deliveryLedger = []
        tVec (:,1) double = []
        nAssets (1,1) double = 0
        isInitialized (1,1) logical = false
        isComplete (1,1) logical = false
    end

    properties (Access = private)
        calibrationRegistry_ = []
        estimatorEligibleProducts_ cell = {}
        pendingLinkDeliveries_ cell = {}
        coordinatorGeneratedCount_ (1,1) double = 0
        coordinatorDeliveredCount_ (1,1) double = 0
        % linkGenerationTally_  Plan Section 2.5: per-(observableIdentifier,ownerAssetIdentifier)
        % generated-record counts. Tracked separately from revgnss.DistributedDeliveryLedger
        % because "generated" is a phase-4 fact recorded BEFORE any ledger entry exists (the
        % ledger only ever sees eligible/rejected records, one entry each, never a raw
        % generated-only count); this is the coordinator's own equivalent of
        % coordinatorGeneratedCount_, split by key instead of collapsed to one fleet-wide total.
        linkGenerationTally_ (1,:) struct = struct('observableIdentifier',{}, ...
            'ownerAssetIdentifier',{},'processedObservableType',{},'generatedRecords',{})
    end

    properties (Constant)
        ArchitectureLabel = 'independentLocalEkfsGroundOnly'
    end

    methods
        function obj = IndependentFleetCoordinator(cfg)
            if nargin > 0
                obj.cfg = cfg;
            end
        end

        function initialize(obj)
            if obj.isInitialized; return; end
            obj.cfg = revgnss.ConfigFactory.finalizeConfig(obj.cfg);
            revgnss.IndependentFleetCoordinator.validateConfig(obj.cfg);
            settings = revgnss.IndependentFleetCoordinator.settingsFromConfig(obj.cfg);
            setup = revgnss.IndependentFleetScenarioFactory.federatedSetup(obj.cfg,false);
            obj.nAssets = setup.N;
            obj.localSimulations = cell(1,obj.nAssets);
            obj.exchangeJournal = revgnss.CommunicationExchangeJournal();
            if settings.deliveryLedger.enable
                obj.deliveryLedger = revgnss.DistributedDeliveryLedger();
            end
            obj.calibrationRegistry_ = revgnss.DistributedLinkCalibrationRegistry( ...
                settings.linkUpdate.calibrationOwnership.policy);

            for assetIndex = 1:obj.nAssets
                leafCfg = revgnss.IndependentFleetScenarioFactory.stageOneLeafConfigForIndex( ...
                    setup,obj.cfg,assetIndex);
                localSim = revgnss.ReverseGNSSSimulation(leafCfg);
                localSim.initialize();
                if assetIndex == 1
                    obj.tVec = localSim.tVec;
                elseif ~isequal(localSim.tVec,obj.tVec)
                    error('IndependentFleetCoordinator:epochGrid', ...
                        'Every local estimator must use the same coordinate-time epoch grid.');
                end
                obj.localSimulations{assetIndex} = localSim;
            end
            obj.requireDistinctLocalClockSeeds_();
            if settings.stateExchange.enable && obj.nAssets < 2
                error('IndependentFleetCoordinator:stateExchangeAssetCount', ...
                    'State exchange requires at least two local spacecraft estimators.');
            end
            obj.isInitialized = true;
        end

        function run(obj)
            if ~obj.isInitialized; obj.initialize(); end
            if obj.isComplete; return; end
            settings = revgnss.IndependentFleetCoordinator.settingsFromConfig(obj.cfg);

            % Per-epoch phase order (frozen by revgnss.DistributedLinkProtocolContract.
            % EpochFinalizationPhaseOrder, plan Section 2.0.1): truth advance + local
            % prediction -> local ground/onboard update -> publish/freeze estimator products
            % -> generate/validate/deliver link records -> owner-only link update -> commit
            % local history and report data. Phases 4-5 remain no-ops unless validateConfig's
            % sanctioned tuple (Section 2.3.1: enable=true, ownerPolicy='initiator',
            % correlationPolicy='splitCovarianceIntersection',
            % updateAdapter.observable='coherentTwoWayCodeRange') is active; every other
            % combination is rejected before run() can be reached, so nothing partial ever
            % flows through them.
            %
            % COMMIT-ORDERING HAZARD: CLOSED. The loop below runs the local update through
            % runLocalEstimationEpochWithoutHistoryCommit, which stages this epoch's
            % history/report row but does not write it, and releases it through
            % commitPendingEpochHistory only after phases 3-5. recordEpoch/logStep read
            % ekf.x/P at commit time, so the owner-only link update filled into
            % applyOwnerOnlyLinkUpdate_ is described by THIS epoch's history/NEES row rather
            % than mutating state behind an already-written one. That closes the blocker
            % recorded in the plan's Stage-2 readiness decision ("current local history is
            % committed before a later link update could be recorded") and in the Section 2.0
            % completion record. lastEstimatedEpoch is deliberately NOT deferred: phase 3's
            % product publication requires it to be current.
            for epochIndex = 1:numel(obj.tVec)
                for assetIndex = 1:obj.nAssets
                    obj.localSimulations{assetIndex}.advanceTruthEpoch(epochIndex);
                end
                for assetIndex = 1:obj.nAssets
                    localSimulation = obj.localSimulations{assetIndex};
                    localSimulation.runLocalEstimationEpochWithoutHistoryCommit(epochIndex);
                end
                if settings.stateExchange.enable
                    obj.publishStateProducts_(epochIndex,settings);
                end
                obj.generateValidateDeliverLinkRecords_(epochIndex,settings);
                obj.applyOwnerOnlyLinkUpdate_(epochIndex,settings);
                for assetIndex = 1:obj.nAssets
                    obj.localSimulations{assetIndex}.commitPendingEpochHistory();
                end
                obj.exchangeJournal.advanceToEpoch(obj.tVec(epochIndex), ...
                    settings.stateExchange.maximumAge_s);
            end

            for assetIndex = 1:obj.nAssets
                obj.localSimulations{assetIndex}.finishRun(false);
            end
            obj.isComplete = true;
            counters = obj.linkObservationCounters_();
            fprintf('Independent fleet complete: %d local EKFs, %d state products, %d ISL updates.\n', ...
                obj.nAssets,obj.exchangeJournal.numberProducts(),counters.consumedByOwner);
        end

        function results = getResults(obj)
            if ~obj.isInitialized
                error('IndependentFleetCoordinator:notInitialized', ...
                    'Initialize the independent fleet before requesting results.');
            end
            results = struct('architectureLabel',obj.ArchitectureLabel, ...
                'N',obj.nAssets,'asset',{cell(1,obj.nAssets)}, ...
                'endpointStateProducts',obj.exchangeJournal.export(), ...
                'stateExchange',obj.exchangeJournal.summary(), ...
                'linkObservationCounters',obj.linkObservationCounters_(), ...
                'linkDelivery',revgnss.DistributedDeliveryLedger.summaryOrEmpty(obj.deliveryLedger), ...
                'linkDeliveryByObservableAndOwner', ...
                    {revgnss.DistributedDeliveryLedger.summaryByObservableAndOwnerOrEmpty(obj.deliveryLedger)}, ...
                'linkGenerationTally',{obj.linkGenerationTally()}, ...
                'distributedLinkPolicy',obj.distributedLinkPolicy_(), ...
                'distributedResultStatus',obj.distributedResultStatus_(), ...
                'complete',obj.isComplete);
            for assetIndex = 1:obj.nAssets
                results.asset{assetIndex} = obj.extractAssetResult_( ...
                    obj.localSimulations{assetIndex},assetIndex);
            end
        end

        function summary = runtimeSummary(obj)
            counters = obj.linkObservationCounters_();
            summary = struct('architectureLabel',obj.ArchitectureLabel, ...
                'nAssets',obj.nAssets, ...
                'independentLocalEkfs',true, ...
                'stateExchange',obj.exchangeJournal.summary(), ...
                'linkObservationCounters',counters, ...
                'linkDelivery',revgnss.DistributedDeliveryLedger.summaryOrEmpty(obj.deliveryLedger), ...
                'relativeEstimatorStatus','notImplementedInStage1', ...
                'linkFusionStatus','notImplementedInStage1', ...
                'distributedResultStatus',obj.distributedResultStatus_(), ...
                'distributedLinkPolicy',obj.distributedLinkPolicy_());
        end

        function products = estimatorEligibleProducts(obj)
            % estimatorEligibleProducts  Read-only accessor for the Section 2.1 additive
            % publication path (stateExchange.estimatorEligibleProfile.enable). Empty unless
            % that toggle is enabled; every Stage-1 diagnostic-only path is unaffected by it.
            products = obj.estimatorEligibleProducts_;
        end

        function tally = linkGenerationTally(obj)
            % linkGenerationTally  Read-only accessor for the plan Section 2.5 per-observable/
            % per-asset generated-record tally. See linkGenerationTally_'s own header for why
            % this is tracked outside revgnss.DistributedDeliveryLedger.
            tally = obj.linkGenerationTally_;
        end
    end

    methods (Static)
        function tf = isEnabled(cfg)
            tf = false;
            if ~(isfield(cfg,'multiAsset') && isstruct(cfg.multiAsset) && ...
                    isfield(cfg.multiAsset,'distributedEstimator'))
                return
            end
            raw = cfg.multiAsset.distributedEstimator;
            if ~(isstruct(raw) && isfield(raw,'enable'))
                tf = true;  % Route malformed requests to the strict validator.
                return
            end
            tf = ~(islogical(raw.enable) && isscalar(raw.enable) && ~raw.enable);
        end

        function settings = settingsFromConfig(cfg)
            settings = revgnss.IndependentFleetCoordinator.defaultSettings_();
            if ~(isfield(cfg,'multiAsset') && ...
                    isfield(cfg.multiAsset,'distributedEstimator'))
                return
            end
            source = cfg.multiAsset.distributedEstimator;
            if ~isstruct(source); return; end
            names = fieldnames(settings);
            for index = 1:numel(names)
                name = names{index};
                if isfield(source,name)
                    settings.(name) = source.(name);
                end
            end
        end

        function validateConfig(cfg)
            if ~(isfield(cfg,'multiAsset') && ...
                    isfield(cfg.multiAsset,'distributedEstimator'))
                return
            end
            raw = cfg.multiAsset.distributedEstimator;
            if ~isstruct(raw)
                error('IndependentFleetCoordinator:configurationType', ...
                    'cfg.multiAsset.distributedEstimator must be a struct.');
            end
            required = {'enable','executionMode','stateExchange','linkUpdate', ...
                'outOfSequencePolicy','deliveryLedger'};
            for index = 1:numel(required)
                if ~isfield(raw,required{index})
                    error('IndependentFleetCoordinator:configurationField', ...
                        'distributedEstimator.%s must be declared in masterConfig.',required{index});
                end
            end
            settings = revgnss.IndependentFleetCoordinator.settingsFromConfig(cfg);
            revgnss.IndependentFleetCoordinator.requireLogical_(settings.enable,'enable');
            if ~(isstruct(settings.stateExchange) && isfield(settings.stateExchange,'enable') && ...
                    isfield(settings.stateExchange,'maximumAge_s') && ...
                    isfield(settings.stateExchange,'deliveryDelay_s') && ...
                    isfield(settings.stateExchange,'estimatorEligibleProfile') && ...
                    isstruct(settings.stateExchange.estimatorEligibleProfile) && ...
                    isfield(settings.stateExchange.estimatorEligibleProfile,'enable'))
                error('IndependentFleetCoordinator:stateExchangeSchema', ...
                    ['distributedEstimator.stateExchange requires enable, maximumAge_s, ' ...
                    'deliveryDelay_s, and estimatorEligibleProfile.enable.']);
            end
            if ~(isstruct(settings.linkUpdate) && isfield(settings.linkUpdate,'enable') && ...
                    isfield(settings.linkUpdate,'ownerPolicy') && ...
                    isfield(settings.linkUpdate,'correlationPolicy') && ...
                    isfield(settings.linkUpdate,'commonSourceTreatment') && ...
                    isfield(settings.linkUpdate,'timeTransferClockClaim') && ...
                    isfield(settings.linkUpdate,'remoteProductPropagationPolicy') && ...
                    isfield(settings.linkUpdate,'roleReversalPolicy') && ...
                    isfield(settings.linkUpdate,'calibrationOwnership') && ...
                    isstruct(settings.linkUpdate.calibrationOwnership) && ...
                    isfield(settings.linkUpdate.calibrationOwnership,'policy') && ...
                    isfield(settings.linkUpdate,'updateAdapter') && ...
                    isstruct(settings.linkUpdate.updateAdapter) && ...
                    isfield(settings.linkUpdate.updateAdapter,'observable'))
                error('IndependentFleetCoordinator:linkUpdateSchema', ...
                    ['distributedEstimator.linkUpdate requires enable, ownerPolicy, ' ...
                    'correlationPolicy, commonSourceTreatment, timeTransferClockClaim, ' ...
                    'remoteProductPropagationPolicy, roleReversalPolicy, ' ...
                    'calibrationOwnership.policy, and updateAdapter.observable.']);
            end
            if ~(isstruct(settings.deliveryLedger) && isfield(settings.deliveryLedger,'enable'))
                error('IndependentFleetCoordinator:configurationField', ...
                    'distributedEstimator.deliveryLedger requires enable.');
            end
            revgnss.IndependentFleetCoordinator.requireLogical_( ...
                settings.stateExchange.enable,'stateExchange.enable');
            revgnss.IndependentFleetCoordinator.requireLogical_( ...
                settings.stateExchange.estimatorEligibleProfile.enable, ...
                'stateExchange.estimatorEligibleProfile.enable');
            revgnss.IndependentFleetCoordinator.requireLogical_( ...
                settings.linkUpdate.enable,'linkUpdate.enable');
            revgnss.IndependentFleetCoordinator.requireLogical_( ...
                settings.deliveryLedger.enable,'deliveryLedger.enable');
            revgnss.IndependentFleetCoordinator.requireNonnegative_( ...
                settings.stateExchange.maximumAge_s,'stateExchange.maximumAge_s');
            revgnss.IndependentFleetCoordinator.requireNonnegative_( ...
                settings.stateExchange.deliveryDelay_s,'stateExchange.deliveryDelay_s');
            if ~strcmp(revgnss.IndependentFleetCoordinator.requireText_( ...
                    settings.executionMode,'executionMode'),'epochSynchronous')
                error('IndependentFleetCoordinator:executionMode', ...
                    'Stage 1 supports executionMode=''epochSynchronous'' only.');
            end
            if ~strcmp(revgnss.IndependentFleetCoordinator.requireText_( ...
                    settings.outOfSequencePolicy,'outOfSequencePolicy'),'reject')
                error('IndependentFleetCoordinator:outOfSequencePolicy', ...
                    'Stage 1 supports outOfSequencePolicy=''reject'' only.');
            end
            ownerPolicy = revgnss.IndependentFleetCoordinator.requireText_( ...
                settings.linkUpdate.ownerPolicy,'linkUpdate.ownerPolicy');
            correlationPolicy = revgnss.IndependentFleetCoordinator.requireText_( ...
                settings.linkUpdate.correlationPolicy,'linkUpdate.correlationPolicy');
            observable = char(revgnss.IndependentFleetCoordinator.requireText_( ...
                settings.linkUpdate.updateAdapter.observable,'linkUpdate.updateAdapter.observable'));
            % Stage 2.0 freezes the correlation and clock-claim vocabulary (Sections 2.0.5,
            % 2.0.6). requireCommonSourceTreatmentDeclared and requireClockClaim validate
            % schema/vocabulary membership unconditionally; every commonSourceTreatment entry
            % must still be 'rejected' (no covariance-group/shared-state treatment exists).
            revgnss.DistributedLinkProtocolContract.requireCommonSourceTreatmentDeclared( ...
                settings.linkUpdate.commonSourceTreatment);
            clockClaim = revgnss.IndependentFleetCoordinator.requireText_( ...
                settings.linkUpdate.timeTransferClockClaim,'linkUpdate.timeTransferClockClaim');
            revgnss.DistributedLinkProtocolContract.requireClockClaim(clockClaim);
            commonSourceRejected = ...
                revgnss.DistributedLinkProtocolContract.isFullyRejectedCommonSourceTreatment( ...
                settings.linkUpdate.commonSourceTreatment);

            % Plan Section 2.3.1/2.3.2/2.3-item-3: exactly ONE non-disabled configuration is
            % sanctioned at a time -- one of coherentTwoWayCodeRange, firstOrderReciprocal
            % ClockTransfer, oneWayCode, or oneWayDoppler, under splitCovarianceIntersection,
            % owned by the initiator, every common source still rejected. Every other
            % combination (including any partial/mixed one, and combining more than one
            % sanctioned observable at once -- Section 2.3.2 U6, generalised N-way) fails
            % validation; there is no silent fallback (invariant 6).
            sanctionedObservables = { ...
                'coherentTwoWayCodeRange','firstOrderReciprocalClockTransfer', ...
                'oneWayCode','oneWayDoppler'};
            sanctionedActive = settings.linkUpdate.enable && strcmp(ownerPolicy,'initiator') && ...
                strcmp(correlationPolicy,'splitCovarianceIntersection') && ...
                any(strcmp(observable,sanctionedObservables)) && commonSourceRejected;
            allDisabled = ~settings.linkUpdate.enable && strcmp(ownerPolicy,'disabled') && ...
                strcmp(correlationPolicy,'disabled') && strcmp(observable,'none') && ...
                commonSourceRejected;
            if ~sanctionedActive && ~allDisabled
                error('IndependentFleetCoordinator:linkUpdateUnavailable', ...
                    ['Only five distributedEstimator.linkUpdate configurations are supported: ' ...
                    'fully disabled (enable=false, ownerPolicy=''disabled'', ' ...
                    'correlationPolicy=''disabled'', updateAdapter.observable=''none''), or one ' ...
                    'of the four sanctioned tuples (enable=true, ownerPolicy=''initiator'', ' ...
                    'correlationPolicy=''splitCovarianceIntersection'', every ' ...
                    'commonSourceTreatment entry ''rejected'', and updateAdapter.observable one ' ...
                    'of ''coherentTwoWayCodeRange'', ''firstOrderReciprocalClockTransfer'', ' ...
                    '''oneWayCode'', or ''oneWayDoppler''). No partial/mixed combination, and no ' ...
                    'combination of more than one sanctioned observable at once, is accepted.']);
            end
            sanctionedObservable = 'none';
            if sanctionedActive
                sanctionedObservable = observable;
                revgnss.DistributedLinkUpdateAdapter.requireObservableSelectable(observable);
                revgnss.DistributedLinkUpdateAdapter.requireRegisteredAdapter( ...
                    revgnss.IndependentFleetCoordinator.adapterClassForObservable_(observable));
                revgnss.SplitCovarianceIntersectionBound.requireObservableHasDemonstratedBound( ...
                    observable);
                % deliveryLedger is a separate toggle (defaults false) from linkUpdate.enable;
                % phases 4-5 unconditionally call obj.deliveryLedger.recordEligible/recordConsumed/
                % recordRejected once linkUpdate is active, including on the rejection path
                % itself, so leaving it disabled here would crash on the first generated link
                % record instead of failing cleanly at construction time.
                if ~settings.deliveryLedger.enable
                    error('IndependentFleetCoordinator:deliveryLedgerRequiredForSanctionedTuple', ...
                        ['The sanctioned linkUpdate tuple requires ' ...
                        'distributedEstimator.deliveryLedger.enable=true: phases 4-5 record every ' ...
                        'generated link record (eligible, consumed, or rejected) in the fleet-wide ' ...
                        'ledger unconditionally.']);
                end
            end

            % Three word toggles remain pinned to their single frozen legal value regardless of
            % sanctionedActive: no propagation/role-reversal/calibration-ownership treatment is
            % implemented for ANY observable (invariant 6).
            if ~strcmp(char(revgnss.IndependentFleetCoordinator.requireText_( ...
                    settings.linkUpdate.remoteProductPropagationPolicy, ...
                    'linkUpdate.remoteProductPropagationPolicy')),'frozenSameEpochOnly') || ...
                    ~strcmp(char(revgnss.IndependentFleetCoordinator.requireText_( ...
                    settings.linkUpdate.roleReversalPolicy,'linkUpdate.roleReversalPolicy')), ...
                    'disabled') || ...
                    ~strcmp(char(revgnss.IndependentFleetCoordinator.requireText_( ...
                    settings.linkUpdate.calibrationOwnership.policy, ...
                    'linkUpdate.calibrationOwnership.policy')),'undeclared')
                error('IndependentFleetCoordinator:section21ControlsUnavailable', ...
                    ['No implementation exists for remoteProductPropagationPolicy, ' ...
                    'roleReversalPolicy, or calibrationOwnership.policy other than their ' ...
                    'single frozen default.']);
            end

            % Per-asset-leaf assertion: a leaf runs one local estimator and owns no fleet
            % accounting. This STRENGTHENS the existing leaf-forcing convention (see
            % IndependentFleetScenarioFactory, which forces both sub-toggles false on every
            % leaf) into an asserted invariant rather than an implicit convention.
            isPerAssetLeaf = revgnss.IndependentFleetCoordinator.logicalPath_( ...
                cfg,{'multiAsset','perAssetLeaf'},false);
            if isPerAssetLeaf && (settings.stateExchange.estimatorEligibleProfile.enable || ...
                    settings.deliveryLedger.enable)
                error('IndependentFleetCoordinator:perAssetLeafSubToggleUnavailable', ...
                    ['A per-asset leaf configuration runs one local estimator and owns no ' ...
                    'fleet accounting. stateExchange.estimatorEligibleProfile.enable and ' ...
                    'deliveryLedger.enable belong to the coordinator config and must be false ' ...
                    'on a leaf; IndependentFleetScenarioFactory forces them false alongside ' ...
                    'distributedEstimator.enable, stateExchange.enable, and linkUpdate.enable.']);
            end

            % Coupling checks run unconditionally (even when distributedEstimator.enable is
            % false), so an unsupported combination fails in configuration validation rather
            % than silently no-op-ing (invariant 6). Because isPerAssetLeaf already forces both
            % antecedents false on any leaf, these checks never fire there.
            if settings.stateExchange.estimatorEligibleProfile.enable && ...
                    ~settings.stateExchange.enable
                error('IndependentFleetCoordinator:estimatorEligibleProfileRequiresStateExchange', ...
                    'stateExchange.estimatorEligibleProfile.enable requires stateExchange.enable=true.');
            end
            if settings.stateExchange.estimatorEligibleProfile.enable
                revgnss.DistributedLinkProtocolContract.requireSameEpochScope(settings.stateExchange);
            end
            if settings.deliveryLedger.enable && ~settings.enable
                error('IndependentFleetCoordinator:deliveryLedgerRequiresFleet', ...
                    'deliveryLedger.enable requires distributedEstimator.enable=true.');
            end

            if ~settings.enable; return; end

            nAssets = revgnss.IndependentFleetCoordinator.numericPath_( ...
                cfg,{'scenario','nSpaceAssets'},1);
            if nAssets < 2
                error('IndependentFleetCoordinator:assetCount', ...
                    'Independent fleet execution requires scenario.nSpaceAssets >= 2.');
            end
            mode = revgnss.IndependentFleetCoordinator.textPath_( ...
                cfg,{'multiAsset','mode'},'fast');
            if ~strcmpi(mode,'fast')
                error('IndependentFleetCoordinator:mode', ...
                    'Independent fleet execution requires multiAsset.mode=''fast''; joint remains separate.');
            end
            if ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'orbit','useOrbitPropagator'},false)
                error('IndependentFleetCoordinator:orbitPropagator', ...
                    'Independent fleet execution requires orbit.useOrbitPropagator=true.');
            end
            orbitMode = revgnss.IndependentFleetCoordinator.textPath_( ...
                cfg,{'orbit','mode'},'');
            if ~any(strcmpi(orbitMode,{'twoBodyRk4','j2Rk4'}))
                error('IndependentFleetCoordinator:orbitMode', ...
                    ['Independent fleet execution requires orbit.mode=''twoBodyRk4'' ' ...
                    'or ''j2Rk4'' because every member uses an explicit ECI initial state.']);
            end
            if ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'rng','independentStreams','enable'},false)
                error('IndependentFleetCoordinator:independentRng', ...
                    ['Independent fleet execution requires rng.independentStreams.enable=true ' ...
                    'so epoch staging cannot change a local noise realization.']);
            end
            % islUpdateUnavailable: every ISL/TWSTFT path stays unconditionally rejected EXCEPT
            % the ones the ACTIVE sanctioned tuple legitimately needs (measurements.isl.enable,
            % plus the two-way or one-way family parent enable, plus the one leaf enable for the
            % selected observable) -- and even those are permitted only under a matching
            % sanctionedObservable (Section 2.3.2 U6, generalised N-way: every non-matching
            % observable's own enable path stays rejected even when another is sanctioned).
            % range.useInEKF, timeTransfer.useInEKF, oneWay.code.useInEKF,
            % oneWay.doppler.useInEKF, and multiAsset.keepIslInPerAssetEkf stay rejected always:
            % the distributed path never routes an ISL row through the joint/per-asset-leaf EKF
            % linearizer.
            if revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'multiAsset','keepIslInPerAssetEkf'},false) || ...
                    revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','twoWay','range','useInEKF'},false) || ...
                    revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','twoWay','timeTransfer','useInEKF'},false) || ...
                    revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','oneWay','code','useInEKF'},false) || ...
                    revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','oneWay','doppler','useInEKF'},false) || ...
                    revgnss.IndependentFleetCoordinator.islObservableRequested_( ...
                    cfg,sanctionedObservable)
                error('IndependentFleetCoordinator:islUpdateUnavailable', ...
                    ['Only measurements.isl.enable, plus the two-way or one-way family parent ' ...
                    'enable, plus the one leaf enable matching the active sanctioned observable, ' ...
                    'may be true. Every *.useInEKF leaf and multiAsset.keepIslInPerAssetEkf must ' ...
                    'always stay false; every other ISL/TWSTFT observable path must stay disabled.']);
            end
            if sanctionedActive
                revgnss.IndependentFleetCoordinator.requireSanctionedIslConfiguration_( ...
                    cfg,sanctionedObservable);
            end
            estimateMode = revgnss.IndependentFleetCoordinator.textPath_( ...
                cfg,{'multiAsset','estimateMode'},'off');
            if ~strcmpi(estimateMode,'off') || ...
                    revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'multiAsset','towersObserveSecondaries'},false)
                error('IndependentFleetCoordinator:centralSecondaryState', ...
                    ['Stage 1 uses one complete local EKF per asset; centralized secondary ' ...
                    'state allocation is incompatible and must remain disabled.']);
            end
        end
    end

    methods (Access = private)
        function generateValidateDeliverLinkRecords_(obj, epochIndex, settings)
            % generateValidateDeliverLinkRecords_  Section 2.0.1 phase 4. Truth is read HERE,
            % by the simulator (plan Section 2.0.1 explicitly permits this), via the same
            % revgnss.TwoWayISLMeasurementBuilder.generateObservations the joint path uses.
            % Every truth diagnostic is discarded immediately; nothing downstream of this
            % method ever receives a SpaceAsset/clock/truth handle. Each successfully proposed
            % delivery is recorded ELIGIBLE in the fleet-wide ledger and staged for phase 5; a
            % rejected proposal is recorded REJECTED with its exact reason, never an uncaught
            % error and never silently dropped.
            obj.pendingLinkDeliveries_ = {};
            if ~settings.linkUpdate.enable; return; end

            observable = char(settings.linkUpdate.updateAdapter.observable);
            isTimeTransfer = strcmp(observable,'firstOrderReciprocalClockTransfer');
            isOneWay = strcmp(observable,'oneWayCode') || strcmp(observable,'oneWayDoppler');

            t_s = obj.tVec(epochIndex);
            assets = cellfun(@(sim) sim.asset,obj.localSimulations,'UniformOutput',false);
            if isOneWay
                [observations,~,info] = revgnss.OneWayInterSatelliteObservationBuilder.generateObservations( ...
                    obj.cfg,assets,t_s);
            elseif isTimeTransfer
                [observations,~,info] = revgnss.InterSatelliteTimeTransferBuilder.generateObservations( ...
                    obj.cfg,assets,t_s);
            else
                [observations,~,info] = revgnss.TwoWayISLMeasurementBuilder.generateObservations( ...
                    obj.cfg,assets{1},assets,t_s);
            end
            info.truthDiagnostic = []; %#ok<NASGU>

            for observationIndex = 1:numel(observations)
                record = observations{observationIndex};
                linkInfo = info.linkInfos{observationIndex};
                linkInfo.truthDiagnostic = []; %#ok<NASGU>
                obj.coordinatorGeneratedCount_ = obj.coordinatorGeneratedCount_ + 1;
                attribution = revgnss.IndependentFleetCoordinator.linkAttributionFromRecord_( ...
                    record,observable,settings.linkUpdate.ownerPolicy);
                obj.tallyGeneratedLinkRecord_(attribution);

                try
                    if isOneWay
                        ownerCanonical = revgnss.CanonicalEndpointIdentity.fromRecordIdentifier( ...
                            record.receiverAssetIdentifier);
                        remoteCanonical = revgnss.CanonicalEndpointIdentity.fromRecordIdentifier( ...
                            record.transmitterAssetIdentifier);
                    elseif isTimeTransfer
                        ownerCanonical = revgnss.CanonicalEndpointIdentity.fromRecordIdentifier( ...
                            record.referenceAssetIdentifier);
                        remoteCanonical = revgnss.CanonicalEndpointIdentity.fromRecordIdentifier( ...
                            record.remoteAssetIdentifier);
                    else
                        ownerCanonical = revgnss.CanonicalEndpointIdentity.fromRecordIdentifier( ...
                            record.initiatorAssetIdentifier);
                        remoteCanonical = revgnss.CanonicalEndpointIdentity.fromRecordIdentifier( ...
                            record.transponderAssetIdentifier);
                    end
                    ownerIdx = ownerCanonical.physicalAssetIndex;
                    remoteIdx = remoteCanonical.physicalAssetIndex;
                    if ownerIdx < 1 || ownerIdx > obj.nAssets || remoteIdx < 1 || remoteIdx > obj.nAssets
                        error('IndependentFleetCoordinator:linkEndpointOutOfRange', ...
                            'Link record %s names an asset index outside the running fleet.', ...
                            record.observationIdentifier);
                    end

                    if isOneWay
                        terminalGeometry = revgnss.IndependentFleetCoordinator. ...
                            terminalGeometryFromOneWayRecord_(record,'owner');
                        remoteTerminalGeometry = revgnss.IndependentFleetCoordinator. ...
                            terminalGeometryFromOneWayRecord_(record,'remote');
                    elseif isTimeTransfer
                        terminalGeometry = revgnss.IndependentFleetCoordinator. ...
                            terminalGeometryFromTimeTransferRecord_(record,'owner');
                        remoteTerminalGeometry = revgnss.IndependentFleetCoordinator. ...
                            terminalGeometryFromTimeTransferRecord_(record,'remote');
                    else
                        terminalGeometry = revgnss.IndependentFleetCoordinator.terminalGeometryFromRecord_( ...
                            record,'owner');
                        remoteTerminalGeometry = revgnss.IndependentFleetCoordinator.terminalGeometryFromRecord_( ...
                            record,'remote');
                    end
                    ownerProvider = revgnss.OwnerLocalEstimatorEndpointProvider.fromLocalSimulation( ...
                        obj.localSimulations{ownerIdx},ownerIdx,t_s,terminalGeometry);

                    remoteSim = obj.localSimulations{remoteIdx};
                    diagnosticProduct = revgnss.EndpointStateProduct.fromLocalEstimator( ...
                        remoteSim,remoteIdx,t_s,0, ...
                        sprintf('spacecraft:%d:epoch:%09d',remoteIdx,epochIndex));
                    eligibleProduct = revgnss.EstimatorEligibleEndpointStateProduct.fromDiagnosticProduct( ...
                        diagnosticProduct,settings.linkUpdate.commonSourceTreatment);
                    remoteProvider = revgnss.FrozenProductEndpointProvider.fromEstimatorEligibleProduct( ...
                        eligibleProduct,t_s,remoteTerminalGeometry);

                    % No calibration product object exists for firstOrderReciprocalClockTransfer
                    % or the one-way observables (plan Section 2.3.2/2.3-item-3: unlike the range
                    % observable, their adapters' buildUpdateBlock arg schemas deliberately carry
                    % no calibrationProduct at all); calibrationProduct stays [] and is never
                    % referenced on those paths.
                    calibrationProduct = [];
                    if ~isTimeTransfer && ~isOneWay
                        linkDefinitionIndex = 0;
                        if isfield(linkInfo,'linkDefinitionIndex')
                            linkDefinitionIndex = linkInfo.linkDefinitionIndex;
                        end
                        calibrationProduct = revgnss.TwoWayISLMeasurementBuilder. ...
                            calibrationProductForLinkDefinitionIndex(obj.cfg,linkDefinitionIndex);
                    end

                    proposeArgs = struct( ...
                        'physicalObservationRecord',record, ...
                        'ownerProvider',ownerProvider, ...
                        'remoteProvider',remoteProvider, ...
                        'ownerPolicy',settings.linkUpdate.ownerPolicy, ...
                        'roleReversalPolicy',settings.linkUpdate.roleReversalPolicy, ...
                        'remoteProductPropagationPolicy',settings.linkUpdate.remoteProductPropagationPolicy, ...
                        'stateExchangeSettings',struct('maximumAge_s',settings.stateExchange.maximumAge_s, ...
                            'deliveryDelay_s',settings.stateExchange.deliveryDelay_s), ...
                        'outOfSequencePolicy',settings.outOfSequencePolicy, ...
                        'commonSourceTreatment',settings.linkUpdate.commonSourceTreatment, ...
                        'correlationPolicy',settings.linkUpdate.correlationPolicy, ...
                        'calibrationRegistry',obj.calibrationRegistry_, ...
                        'deliveryEpoch_s',t_s,'coordinateEventEpoch_s',t_s, ...
                        'observableIdentifier',settings.linkUpdate.updateAdapter.observable, ...
                        'persistentCalibrationTreatment','rejected', ...
                        'configurationSnapshot',obj.cfg);
                    [delivery,rejection] = revgnss.LinkObservationDelivery.tryPropose(proposeArgs);
                    if rejection.rejected
                        obj.rejectRecord_(record,t_s,rejection.reasonCode,rejection.reasonMessage, ...
                            rejection.sourceErrorIdentifier,attribution);
                        continue
                    end
                    obj.deliveryLedger.recordEligible(delivery);
                    obj.pendingLinkDeliveries_{end+1} = struct( ...
                        'delivery',delivery,'calibrationProduct',calibrationProduct); %#ok<AGROW>
                catch ME
                    obj.rejectRecord_(record,t_s,'observablePredictionFailed',ME.message,ME.identifier, ...
                        attribution);
                end
            end
        end

        function applyOwnerOnlyLinkUpdate_(obj, epochIndex, settings)
            % applyOwnerOnlyLinkUpdate_  Section 2.0.1 phase 5. Each staged delivery is applied
            % to its OWNER leaf's own local EKF only, via the certified conservative bound
            % (revgnss.SplitCovarianceIntersectionBound, extended to the full owner state by
            % revgnss.ConservativeFullStateLinkUpdate). ekf.x/P mutation here is safely ordered:
            % run() commits each local history row AFTER this phase, so this epoch's recorded
            % state/NEES row describes the post-update state.
            if ~settings.linkUpdate.enable; return; end
            t_s = obj.tVec(epochIndex); %#ok<NASGU>

            for index = 1:numel(obj.pendingLinkDeliveries_)
                staged = obj.pendingLinkDeliveries_{index};
                delivery = staged.delivery;
                try
                    obj.applyOneLinkUpdate_(delivery,staged.calibrationProduct);
                    obj.deliveryLedger.recordConsumed(delivery.observationIdentifier, ...
                        delivery.ownerAssetIdentifier,delivery.deliveryEpoch_s);
                    ownerSim = obj.localSimulations{delivery.ownerCanonicalIndex};
                    ownerSim.observationLedger.markEligible(delivery.physicalObservationRecord, ...
                        delivery.deliveryEpoch_s);
                    ownerSim.observationLedger.consume(delivery.physicalObservationRecord, ...
                        delivery.deliveryEpoch_s);
                    obj.coordinatorDeliveredCount_ = obj.coordinatorDeliveredCount_ + 1;
                catch ME
                    obj.deliveryLedger.recordRejectedFromEligible(delivery.observationIdentifier, ...
                        'observablePredictionFailed',ME.message,ME.identifier);
                end
            end
            obj.pendingLinkDeliveries_ = {};
        end

        function applyOneLinkUpdate_(obj, delivery, calibrationProduct)
            % applyOneLinkUpdate_  Builds the real physics block (adapter), the certified
            % conservative full-state bound, and applies it to the OWNER leaf's own EKF. Throws
            % on any failure; the caller (applyOwnerOnlyLinkUpdate_) converts that into a mapped
            % ledger rejection rather than an uncaught error.
            ownerState = delivery.ownerProvider.stateAtCoordinateEpoch(delivery.coordinateEventEpoch_s);
            remoteState = delivery.remoteProvider.stateAtCoordinateEpoch(delivery.coordinateEventEpoch_s);

            switch delivery.observableIdentifier
                case 'coherentTwoWayCodeRange'
                    steps = revgnss.IndependentFleetCoordinator.linearizationStepsFromConfig_(obj.cfg);
                    buildArgs = struct( ...
                        'delivery',delivery,'ownerState',ownerState,'remoteState',remoteState, ...
                        'calibrationProduct',calibrationProduct,'linearizationSteps',steps, ...
                        'solverOptions',struct(),'modeledPropagationGroupDelay_s',0, ...
                        'weightSelectionRule','fixedDeclaredWeights', ...
                        'persistentCalibrationTreatment','rejected');
                    [block, ~] = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.buildUpdateBlock(buildArgs);
                case 'firstOrderReciprocalClockTransfer'
                    buildArgs = struct( ...
                        'delivery',delivery,'ownerState',ownerState,'remoteState',remoteState, ...
                        'weightSelectionRule','fixedDeclaredWeights', ...
                        'persistentCalibrationTreatment','rejected');
                    [block, ~] = revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter. ...
                        buildUpdateBlock(buildArgs);
                case 'oneWayCode'
                    buildArgs = struct( ...
                        'delivery',delivery,'ownerState',ownerState,'remoteState',remoteState, ...
                        'weightSelectionRule','fixedDeclaredWeights', ...
                        'persistentCalibrationTreatment','rejected');
                    [block, ~] = revgnss.OneWayCodeRangeLinkUpdateAdapter.buildUpdateBlock(buildArgs);
                case 'oneWayDoppler'
                    buildArgs = struct( ...
                        'delivery',delivery,'ownerState',ownerState,'remoteState',remoteState, ...
                        'weightSelectionRule','fixedDeclaredWeights', ...
                        'persistentCalibrationTreatment','rejected');
                    [block, ~] = revgnss.OneWayDopplerRangeRateLinkUpdateAdapter.buildUpdateBlock(buildArgs);
                otherwise
                    error('IndependentFleetCoordinator:adapterClassForObservable', ...
                        'Observable ''%s'' has no registered adapter dispatch.', ...
                        delivery.observableIdentifier);
            end
            revgnss.DistributedLinkUpdateAdapter.requireUpdateBlock(block,delivery,ownerState,remoteState);

            ownerSim = obj.localSimulations{delivery.ownerCanonicalIndex};
            blk = revgnss.AssetStateBlock.forAsset(ownerSim.ekf.stateMap,1);
            schemaIndices = [blk.r(:);blk.v(:);blk.euler(:);ownerSim.ekf.stateMap.omega_idx(:); ...
                blk.b;blk.bdot];

            Hi = block.ownerJacobian_mPerErrorUnit;
            Hj = block.remoteJacobian_mPerErrorUnit;
            Pi_schema = ownerSim.ekf.P(schemaIndices,schemaIndices);
            Pi_schema = (Pi_schema+Pi_schema')/2;
            Pj = remoteState.covarianceBlock;
            Rind = block.independentMeasurementCovariance_m2;
            Sremote = Hj*Pj*Hj'; Sremote = (Sremote+Sremote')/2;
            K0 = Pi_schema*Hi'/(Hi*Pi_schema*Hi' + Sremote + Rind);
            declaredWeights = revgnss.ConservativeFullStateLinkUpdate.declaredWeightsFromFullStateTraces( ...
                ownerSim.ekf.P,schemaIndices,Hi,K0,Sremote);

            emptyCommonRows = struct('covarianceGroupIdentifier',{},'commonSourceName',{}, ...
                'contribution_m2',{},'sourceProductIdentifier',{});
            emptyCalibRows = struct('calibrationStateIdentifier',{}, ...
                'mappingColumn_mPerCalibrationUnit',{},'stateUnits',{},'priorVariance',{}, ...
                'priorVarianceUnits',{});
            rawBoundArgs = struct( ...
                'ownerPriorCovariance_errorUnit2',Pi_schema, ...
                'ownerJacobian_mPerErrorUnit',Hi, ...
                'remotePriorCovariance_errorUnit2',Pj, ...
                'remoteJacobian_mPerErrorUnit',Hj, ...
                'totalMeasurementCovariance_m2',Rind, ...
                'totalMeasurementCovarianceIncludesDeclaredCommonSources',true, ...
                'declaredCommonSourceContributions',emptyCommonRows, ...
                'declaredCalibrationContributions',emptyCalibRows, ...
                'ownerCovarianceComponentOrder',{ownerState.covarianceComponentOrder}, ...
                'ownerAttitudeErrorCoordinateConvention',ownerState.attitudeErrorCoordinateConvention, ...
                'remoteCovarianceComponentOrder',{remoteState.covarianceComponentOrder}, ...
                'remoteAttitudeErrorCoordinateConvention',remoteState.attitudeErrorCoordinateConvention, ...
                'weightSelectionRule','fixedDeclaredWeights', ...
                'declaredWeights',declaredWeights, ...
                'correlationPolicy','splitCovarianceIntersection');
            [scaledArgs, ownerScale, ~] = ...
                revgnss.ConservativeFullStateLinkUpdate.rescaleBoundArgsToUnitDiagonal(rawBoundArgs);
            boundResult = revgnss.SplitCovarianceIntersectionBound.ownerPosteriorBound(scaledArgs);

            applyArgs = struct( ...
                'xPrior',ownerSim.ekf.x,'PPrior',ownerSim.ekf.P,'schemaStateIndices',schemaIndices, ...
                'boundResult',boundResult,'H_owner',Hi,'ownerScale',ownerScale, ...
                'residual_m',block.residual_m, ...
                'attitudeParameterization',ownerSim.ekf.attitudeParameterization, ...
                'nominalQuatPrior',ownerSim.ekf.nominalQuat_wxyz(:,1));
            result = revgnss.ConservativeFullStateLinkUpdate.applyOwnerOnlyUpdate(applyArgs);

            ownerSim.ekf.x = result.xPosterior;
            ownerSim.ekf.P = result.PPosterior;
            ownerSim.ekf.nominalQuat_wxyz(:,1) = result.nominalQuatPosterior;
            if result.attitudeInjectionNorm_rad > 0
                ownerSim.ekf.attitudeInjectionCount = ownerSim.ekf.attitudeInjectionCount + 1;
                ownerSim.ekf.maxAttitudeInjectionNorm_rad = max( ...
                    ownerSim.ekf.maxAttitudeInjectionNorm_rad,result.attitudeInjectionNorm_rad);
            end
        end

        function rejectRecord_(obj, record, deliveryEpoch_s, reasonCode, reasonMessage, ...
                sourceErrorIdentifier, attribution)
            % rejectRecord_  attribution (plan Section 2.5) is a
            % linkAttributionFromRecord_-built struct: no revgnss.LinkObservationDelivery exists
            % yet on this path (the proposal itself failed, or failed before one could be
            % built), so the ledger's per-observable/per-asset report accounting still needs an
            % observable identifier and a best-effort (never reconciled) owner/remote label.
            rejectionRecord = struct( ...
                'observationIdentifier',record.observationIdentifier, ...
                'ownerAssetIdentifier',attribution.ownerAssetIdentifier, ...
                'remoteAssetIdentifier',attribution.remoteAssetIdentifier, ...
                'remoteProductIdentifier','', ...
                'sourceEpoch_s',deliveryEpoch_s, ...
                'deliveryEpoch_s',deliveryEpoch_s, ...
                'reasonCode',reasonCode, ...
                'reasonMessage',reasonMessage, ...
                'sourceErrorIdentifier',sourceErrorIdentifier, ...
                'physicalRecordClass',class(record), ...
                'observableIdentifier',attribution.observableIdentifier, ...
                'processedObservableType',attribution.processedObservableType, ...
                'processedUnits',attribution.processedUnits, ...
                'ownerAttributionSource',attribution.ownerAttributionSource);
            obj.deliveryLedger.recordRejected(rejectionRecord);
        end

        function tallyGeneratedLinkRecord_(obj, attribution)
            key = @(t) strcmp({t.observableIdentifier},attribution.observableIdentifier) & ...
                strcmp({t.ownerAssetIdentifier},attribution.ownerAssetIdentifier);
            index = find(key(obj.linkGenerationTally_),1);
            if isempty(index)
                obj.linkGenerationTally_(end+1) = struct( ...
                    'observableIdentifier',attribution.observableIdentifier, ...
                    'ownerAssetIdentifier',attribution.ownerAssetIdentifier, ...
                    'processedObservableType',attribution.processedObservableType, ...
                    'generatedRecords',1);
            else
                obj.linkGenerationTally_(index).generatedRecords = ...
                    obj.linkGenerationTally_(index).generatedRecords+1;
            end
        end

        function policy = distributedLinkPolicy_(obj)
            % distributedLinkPolicy_  Plan Section 2.5: a flat, report-ready echo of the
            % sanctioned tuple this run configured, so the report can state the correlation
            % policy / calibration ownership / propagation policy without a second copy of the
            % validation logic in validateConfig.
            settings = revgnss.IndependentFleetCoordinator.settingsFromConfig(obj.cfg);
            observable = char(settings.linkUpdate.updateAdapter.observable);
            rowUnits = '';
            if ~strcmp(observable,'none')
                rowUnits = revgnss.DistributedLinkUpdateAdapter.RowUnitsByObservable.(observable);
            end
            policy = struct( ...
                'linkUpdateEnabled',settings.linkUpdate.enable, ...
                'observableIdentifier',observable, ...
                'observableRowUnits',rowUnits, ...
                'ownerPolicy',char(settings.linkUpdate.ownerPolicy), ...
                'correlationPolicy',char(settings.linkUpdate.correlationPolicy), ...
                'roleReversalPolicy',char(settings.linkUpdate.roleReversalPolicy), ...
                'remoteProductPropagationPolicy',char(settings.linkUpdate.remoteProductPropagationPolicy), ...
                'persistentCalibrationTreatment','rejected', ... % literal proposeArgs itself passes, not a config read
                'calibrationOwnershipPolicy',char(settings.linkUpdate.calibrationOwnership.policy), ...
                'commonSourceTreatment',settings.linkUpdate.commonSourceTreatment, ...
                'outOfSequencePolicy',char(settings.outOfSequencePolicy), ...
                'deliveryLedgerEnabled',settings.deliveryLedger.enable, ...
                'stateExchangeEnabled',settings.stateExchange.enable, ...
                'estimatorEligibleProfileEnabled',settings.stateExchange.estimatorEligibleProfile.enable, ...
                'stateExchangeMaximumAge_s',settings.stateExchange.maximumAge_s, ...
                'stateExchangeDeliveryDelay_s',settings.stateExchange.deliveryDelay_s);
        end

        function status = distributedResultStatus_(obj)
            settings = revgnss.IndependentFleetCoordinator.settingsFromConfig(obj.cfg);
            counters = obj.linkObservationCounters_();
            status = revgnss.DistributedFleetReportingContract.resultStatus( ...
                settings.linkUpdate.enable,char(settings.linkUpdate.correlationPolicy), ...
                counters.consumedByOwner);
        end

        function publishStateProducts_(obj, epochIndex, settings)
            % publishStateProducts_  Section 2.0.4/2.1: the Stage-1 diagnostic product and
            % journal record below are UNCHANGED. When
            % stateExchange.estimatorEligibleProfile.enable is true, an ADDITIONAL immutable
            % revgnss.EstimatorEligibleEndpointStateProduct is built from the same diagnostic
            % product and stored for later retrieval (estimatorEligibleProducts()); nothing is
            % consumed, no ekf.x/P is touched, and the Stage-1 path below never sees this branch.
            sourceEpoch_s = obj.tVec(epochIndex);
            for assetIndex = 1:obj.nAssets
                sequenceIdentifier = sprintf('spacecraft:%d:epoch:%09d', ...
                    assetIndex,epochIndex);
                product = revgnss.EndpointStateProduct.fromLocalEstimator( ...
                    obj.localSimulations{assetIndex},assetIndex,sourceEpoch_s, ...
                    settings.stateExchange.deliveryDelay_s,sequenceIdentifier);
                obj.exchangeJournal.record(product,sourceEpoch_s);
                if settings.stateExchange.estimatorEligibleProfile.enable
                    eligibleProduct = revgnss.EstimatorEligibleEndpointStateProduct. ...
                        fromDiagnosticProduct(product,settings.linkUpdate.commonSourceTreatment);
                    obj.estimatorEligibleProducts_{end+1} = eligibleProduct;
                end
            end
        end

        function counters = linkObservationCounters_(obj)
            % linkObservationCounters_  `generated` sums the LEAF-populated count (always 0 on
            % the distributed path, since records are generated by THIS coordinator at phase 4,
            % never written to any leaf's interSatelliteObservations) plus the coordinator's own
            % phase-4 count (always 0 on the disabled path) -- so the disabled-path value is
            % unchanged and the active-path value is real, never internally contradictory
            % against a nonzero consumedByOwner.
            consumed = 0;
            leafGenerated = 0;
            for assetIndex = 1:numel(obj.localSimulations)
                sim = obj.localSimulations{assetIndex};
                if isempty(sim); continue; end
                consumed = consumed + sim.observationLedger.numberConsumed();
                leafGenerated = leafGenerated + numel(sim.interSatelliteObservations);
            end
            counters = struct('generated',leafGenerated+obj.coordinatorGeneratedCount_, ...
                'delivered',obj.coordinatorDeliveredCount_, ...
                'consumedByOwner',consumed);
        end

        function result = extractAssetResult_(~, sim, assetIndex)
            sm = sim.ekf.stateMap;
            result = struct('assetIndex',assetIndex, ...
                'assetIdentifier',sprintf('spacecraft:%d',assetIndex), ...
                'assetName',sim.asset.name, ...
                'x',sim.ekf.x,'P',sim.ekf.P,'stateMap',sm, ...
                'history',sim.ekf.history,'truthR',sim.asset.r_ecef_m, ...
                'truthV',sim.asset.v_ecef_mps, ...
                'truthClk',sim.asset.clock.getBiasMeters(), ...
                'cfg',sim.cfg);
            if sim.orbitTruthCache.enabled
                result.truthTraj = sim.orbitTruthCache.r_ecef_m;
                result.truthVelTraj = sim.orbitTruthCache.v_ecef_mps;
                result.truthTime_s = sim.orbitTruthCache.t_s(:).';
            else
                result.truthTraj = sim.asset.history.r_ecef_m;
                result.truthVelTraj = sim.asset.history.v_ecef_mps;
                result.truthTime_s = sim.asset.history.time_s(:).';
            end
            result.truthClkTraj_m = [];
            result.truthClkTime_s = [];
            try
                if ~isempty(sim.asset.clock.history.bias_s)
                    result.truthClkTraj_m = sim.asset.clock.history.bias_s(:).' * ...
                        revgnss.Constants.SPEED_OF_LIGHT_MPS;
                    result.truthClkTime_s = sim.asset.clock.history.time_s(:).';
                end
            catch
            end
        end

        function requireDistinctLocalClockSeeds_(obj)
            clockSeeds = zeros(1,obj.nAssets);
            for assetIndex = 1:obj.nAssets
                clockSeeds(assetIndex) = obj.localSimulations{assetIndex}.asset.clock.seed;
            end
            if numel(unique(clockSeeds)) ~= obj.nAssets
                error('IndependentFleetCoordinator:clockSeed', ...
                    ['Every local spacecraft receiver clock must use a distinct seed. ' ...
                    'Repeated seeds would create an artificial common clock realization.']);
            end
        end
    end

    methods (Static, Access = private)
        function settings = defaultSettings_()
            commonSourceTreatment = struct( ...
                'towerClockProduct','rejected', ...
                'terminalCalibration','rejected', ...
                'transmittedStateProduct','rejected', ...
                'sessionTimingProduct','rejected', ...
                'sharedForceAtmosphericProduct','rejected');
            settings = struct('enable',false,'executionMode','epochSynchronous', ...
                'stateExchange',struct('enable',false,'maximumAge_s',0, ...
                    'deliveryDelay_s',0, ...
                    'estimatorEligibleProfile',struct('enable',false)), ...
                'linkUpdate',struct('enable',false,'ownerPolicy','disabled', ...
                    'correlationPolicy','disabled', ...
                    'commonSourceTreatment',commonSourceTreatment, ...
                    'timeTransferClockClaim','relativeBiasOnly', ...
                    'remoteProductPropagationPolicy','frozenSameEpochOnly', ...
                    'roleReversalPolicy','disabled', ...
                    'calibrationOwnership',struct('policy','undeclared'), ...
                    'updateAdapter',struct('observable','none')), ...
                'outOfSequencePolicy','reject', ...
                'deliveryLedger',struct('enable',false));
        end

        function requireLogical_(value,name)
            if ~(islogical(value) && isscalar(value))
                error('IndependentFleetCoordinator:logicalSetting', ...
                    'distributedEstimator.%s must be a logical scalar.',name);
            end
        end

        function requireNonnegative_(value,name)
            if ~(isnumeric(value) && isscalar(value) && isfinite(value) && value >= 0)
                error('IndependentFleetCoordinator:numericSetting', ...
                    'distributedEstimator.%s must be a finite nonnegative scalar.',name);
            end
        end

        function text = requireText_(value,name)
            if ~(ischar(value) || (isstring(value) && isscalar(value)))
                error('IndependentFleetCoordinator:textSetting', ...
                    'distributedEstimator.%s must be text.',name);
            end
            text = char(value);
        end

        function value = logicalPath_(cfg,path,defaultValue)
            value = defaultValue;
            node = cfg;
            for index = 1:numel(path)
                if ~isstruct(node) || ~isfield(node,path{index}); return; end
                node = node.(path{index});
            end
            if islogical(node) && isscalar(node); value = node; end
        end

        function attribution = linkAttributionFromRecord_(record, observableIdentifier, ownerPolicy)
            % linkAttributionFromRecord_  Plan Section 2.5 non-throwing report-time endpoint
            % attribution: needed on the phase-4 rejection path, where NO
            % revgnss.LinkObservationDelivery exists yet (the proposal itself may have failed,
            % or may fail below before one is built) -- observableIdentifier is always the
            % passed scalar (the coordinator always knows the one sanctioned observable for the
            % run), never a sentinel, but the owner/remote endpoint labels are only a best-
            % effort record-declared reading, reusing the SAME role mapping propose() itself
            % uses (revgnss.LinkObservationDelivery.ownerRemoteEndpointFieldsFor) so there is
            % never a second copy of that mapping (invariant 9). Deliberately non-throwing: an
            % uncaught error inside the rejection path itself would be strictly worse than the
            % frozen 'unattributed' sentinel below, and the sentinel is a strict improvement
            % over the pre-Section-2.5 behaviour (a bare '').
            %
            % CANONICALIZED, not the raw record label: a physical record declares its endpoints
            % in the 'asset:N' scheme (revgnss.CanonicalEndpointIdentity.fromRecordIdentifier),
            % but every ledger entry built via a real revgnss.LinkObservationDelivery stores the
            % 'spacecraft:N' canonical product scheme (out.ownerAssetIdentifier =
            % args.ownerProvider.endpointIdentifier in propose()). Reading the raw 'asset:N'
            % label here would key linkGenerationTally_ under a DIFFERENT string than the same
            % physical satellite's ledger entries use, so DistributedFleetReportingContract.
            % buildLinkAccounting's join would never match a generated count to its own
            % delivered/consumed counts for the same asset (found by execution: a real run
            % showed generated=6 filed under 'asset:1' with 0 delivered, and delivered=6/
            % consumed=6 filed separately under 'spacecraft:1', reconciled=false).
            attribution = struct( ...
                'observableIdentifier',char(observableIdentifier), ...
                'ownerAssetIdentifier',revgnss.DistributedDeliveryLedger.UnattributedAssetIdentifier, ...
                'remoteAssetIdentifier','', ...
                'processedObservableType','', ...
                'processedUnits','', ...
                'ownerAttributionSource','unattributed');
            try
                [ownerField,remoteField] = revgnss.LinkObservationDelivery.ownerRemoteEndpointFieldsFor( ...
                    class(record),char(ownerPolicy));
                ownerCanonical = revgnss.CanonicalEndpointIdentity.fromRecordIdentifier(record.(ownerField));
                remoteCanonical = revgnss.CanonicalEndpointIdentity.fromRecordIdentifier(record.(remoteField));
                attribution.ownerAssetIdentifier = sprintf('spacecraft:%d',ownerCanonical.physicalAssetIndex);
                attribution.remoteAssetIdentifier = sprintf('spacecraft:%d',remoteCanonical.physicalAssetIndex);
                attribution.processedObservableType = record.processedObservableType;
                attribution.processedUnits = record.processedUnits;
                attribution.ownerAttributionSource = 'recordDeclaredEndpointLabel';
            catch
            end
        end

        function geometry = terminalGeometryFromRecord_(record, role)
            % terminalGeometryFromRecord_  Builds a declared revgnss.CommunicationEndpointState
            % terminalGeometry struct from the record's own terminal/antenna identifiers and the
            % ESTIMATOR's configured lever arm (never a truth diagnostic value) -- role='owner'
            % reads the record's initiator fields, role='remote' its transponder fields. This is
            % what requireTerminalGeometryMatchesRecord (adapter) cross-checks against.
            leverArm = revgnss.IndependentFleetCoordinator.estimatorLeverArm_();
            if strcmp(role,'owner')
                geometry = struct('declared',true, ...
                    'transmitTerminalIdentifier',record.initiatorTransmitTerminalIdentifier, ...
                    'receiveTerminalIdentifier',record.initiatorReceiveTerminalIdentifier, ...
                    'transmitAntennaIdentifier',record.initiatorTransmitAntennaIdentifier, ...
                    'receiveAntennaIdentifier',record.initiatorReceiveAntennaIdentifier, ...
                    'transmitPhaseCentreOffset_body_m',leverArm, ...
                    'receivePhaseCentreOffset_body_m',leverArm);
            else
                geometry = struct('declared',true, ...
                    'transmitTerminalIdentifier',record.transponderTransmitTerminalIdentifier, ...
                    'receiveTerminalIdentifier',record.transponderReceiveTerminalIdentifier, ...
                    'transmitAntennaIdentifier',record.transponderTransmitAntennaIdentifier, ...
                    'receiveAntennaIdentifier',record.transponderReceiveAntennaIdentifier, ...
                    'transmitPhaseCentreOffset_body_m',leverArm, ...
                    'receivePhaseCentreOffset_body_m',leverArm);
            end
        end

        function geometry = terminalGeometryFromOneWayRecord_(record, role)
            % terminalGeometryFromOneWayRecord_  A one-way record's transmit/receive
            % terminal+antenna quadruple is asymmetric by role: the owner (always the record's
            % RECEIVER) uses only its receive slot; the remote (always the record's
            % TRANSMITTER) uses only its transmit slot -- OneWayCodeRangeLinkUpdateAdapter/
            % OneWayDopplerRangeRateLinkUpdateAdapter's requireTerminalIdentityMatchesRecord
            % checks ONLY that used slot per role. The unused slot still needs a value
            % (CommunicationEndpointState requires the full quadruple regardless of role), so it
            % is filled with a frozen sentinel and a zero lever arm -- declared-unused, never a
            % physics input for either observable (the estimator's own configured lever arm,
            % never a truth diagnostic value, matches the SAME masterConfig key
            % OneWayInterSatelliteObservationBuilder.truthEndpoint_ reads, mirroring
            % estimatorLeverArm_'s own precedent).
            leverArm = revgnss.IndependentFleetCoordinator.estimatorOneWayLeverArm_();
            if strcmp(role,'owner')
                geometry = struct('declared',true, ...
                    'transmitTerminalIdentifier','terminal:notUsedByOneWayRole', ...
                    'receiveTerminalIdentifier',record.receiveTerminalIdentifier, ...
                    'transmitAntennaIdentifier','antenna:notUsedByOneWayRole', ...
                    'receiveAntennaIdentifier',record.receiveAntennaIdentifier, ...
                    'transmitPhaseCentreOffset_body_m',zeros(3,1), ...
                    'receivePhaseCentreOffset_body_m',leverArm);
            else
                geometry = struct('declared',true, ...
                    'transmitTerminalIdentifier',record.transmitTerminalIdentifier, ...
                    'receiveTerminalIdentifier','terminal:notUsedByOneWayRole', ...
                    'transmitAntennaIdentifier',record.transmitAntennaIdentifier, ...
                    'receiveAntennaIdentifier','antenna:notUsedByOneWayRole', ...
                    'transmitPhaseCentreOffset_body_m',leverArm, ...
                    'receivePhaseCentreOffset_body_m',zeros(3,1));
            end
        end

        function geometry = terminalGeometryFromTimeTransferRecord_(record, role)
            % terminalGeometryFromTimeTransferRecord_  The time-transfer record carries one
            % terminal identifier per role (referenceTerminalIdentifier/remoteTerminalIdentifier),
            % not the separate transmit/receive terminal+antenna quadruple the two-way range
            % record declares -- so the SAME identifier fills both the transmit and receive
            % terminal slots, and antenna identity uses the frozen sentinel below (this record
            % type does not carry a separate antenna concept at all). The lever arm is exactly
            % zero: revgnss.ReciprocalTimeTransferModel's position/velocity partials are always
            % zero for this adapter (Section 2.3.2 does not support the reciprocity term), so no
            % phase-centre offset can ever reach the adapter's residual or Jacobian -- this is a
            % declarative geometry tag only, never a physics input.
            if strcmp(role,'owner')
                terminalIdentifier = record.referenceTerminalIdentifier;
            else
                terminalIdentifier = record.remoteTerminalIdentifier;
            end
            geometry = struct('declared',true, ...
                'transmitTerminalIdentifier',terminalIdentifier, ...
                'receiveTerminalIdentifier',terminalIdentifier, ...
                'transmitAntennaIdentifier','antenna:notCarriedByTimeTransferRecord', ...
                'receiveAntennaIdentifier','antenna:notCarriedByTimeTransferRecord', ...
                'transmitPhaseCentreOffset_body_m',zeros(3,1), ...
                'receivePhaseCentreOffset_body_m',zeros(3,1));
        end

        function leverArm = estimatorLeverArm_()
            % estimatorLeverArm_  The ISL terminal lever arm masterConfig already declares
            % (measurements.isl.twoWay.terminalGeometry.*), matching what
            % revgnss.TwoWayISLMeasurementBuilder.terminalGeometry_ feeds to BOTH the truth and
            % estimator endpoints today -- so the shipped configuration has no phase-centre error
            % to begin with; a future config could diverge them without changing this code.
            leverArm = [0.8;0.2;0.3];
        end

        function leverArm = estimatorOneWayLeverArm_()
            % estimatorOneWayLeverArm_  Mirrors estimatorLeverArm_'s exact precedent for the
            % one-way subtree: a hard-coded literal matching masterConfig's shipped
            % measurements.isl.oneWay.terminalGeometry.* default (the SAME value
            % revgnss.OneWayInterSatelliteObservationBuilder.truthEndpoint_ reads from config),
            % not a config read -- so the shipped configuration has no phase-centre error to
            % begin with, but a future config could diverge the two without changing this code
            % (same documented, accepted hazard as estimatorLeverArm_'s own header).
            leverArm = [0.8;0.2;0.3];
        end

        function steps = linearizationStepsFromConfig_(cfg)
            steps = struct( ...
                'positionStep_m',revgnss.IndependentFleetCoordinator.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','range','linearization','positionStep_m'},0.5), ...
                'velocityStep_mps',revgnss.IndependentFleetCoordinator.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','range','linearization','velocityStep_mps'},0.05), ...
                'attitudeStep_rad',revgnss.IndependentFleetCoordinator.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','range','linearization','attitudeStep_rad'},5e-4), ...
                'clockBiasStep_m',revgnss.IndependentFleetCoordinator.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','range','linearization','clockBiasStep_m'},10), ...
                'clockDriftStep_mps',revgnss.IndependentFleetCoordinator.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','range','linearization','clockDriftStep_mps'},0.01));
        end

        function value = numericPath_(cfg,path,defaultValue)
            value = defaultValue;
            node = cfg;
            for index = 1:numel(path)
                if ~isstruct(node) || ~isfield(node,path{index}); return; end
                node = node.(path{index});
            end
            if isnumeric(node) && isscalar(node) && isfinite(node); value = node; end
        end

        function value = textPath_(cfg,path,defaultValue)
            value = defaultValue;
            node = cfg;
            for index = 1:numel(path)
                if ~isstruct(node) || ~isfield(node,path{index}); return; end
                node = node.(path{index});
            end
            if ischar(node) || (isstring(node) && isscalar(node)); value = char(node); end
        end

        function className = adapterClassForObservable_(observable)
            switch char(observable)
                case 'coherentTwoWayCodeRange'
                    className = 'revgnss.CoherentTwoWayRangeLinkUpdateAdapter';
                case 'firstOrderReciprocalClockTransfer'
                    className = 'revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter';
                case 'oneWayCode'
                    className = 'revgnss.OneWayCodeRangeLinkUpdateAdapter';
                case 'oneWayDoppler'
                    className = 'revgnss.OneWayDopplerRangeRateLinkUpdateAdapter';
                otherwise
                    error('IndependentFleetCoordinator:adapterClassForObservable', ...
                        'Observable ''%s'' has no registered adapter dispatch.',char(observable));
            end
        end

        function tf = islObservableRequested_(cfg,sanctionedObservable)
            % islObservableRequested_  measurements.isl.enable, plus the two-way or one-way
            % family parent enable, plus the one leaf enable for the SELECTED observable, are
            % the paths a sanctioned tuple legitimately needs (plan Section 2.3.1 / audit A17:
            % measurements.isl.enable is the two-way builder's OWN parent validation gate, not
            % only the one-way LEGACY builder's runtime gate) -- each exempted ONLY when its own
            % family/observable is the active sanctionedObservable (Section 2.3.2 U6, generalised
            % N-way: every non-matching family/observable's own enable path stays rejected even
            % when another is sanctioned), and checked unconditionally otherwise. Every leaf
            % still forces measurements.isl.enable (and every other measurements.isl.* key)
            % false regardless of this fleet-level value (IndependentFleetScenarioFactory), so
            % this can never reach a per-asset-leaf EKF; every *.useInEKF leaf is checked
            % unconditionally by the caller, not here.
            if nargin < 2; sanctionedObservable = 'none'; end
            sanctionedObservable = char(sanctionedObservable);
            paths = { ...
                {'measurements','isl','code','enable'}, ...
                {'measurements','isl','code','useInEKF'}, ...
                {'measurements','isl','doppler','enable'}, ...
                {'measurements','isl','doppler','useInEKF'}, ...
                {'measurements','isl','carrier','enable'}, ...
                {'measurements','isl','carrier','useInEKF'}, ...
                {'measurements','isl','timing','enable'}, ...
                {'measurements','isl','twoWay','doppler','enable'}, ...
                {'measurements','isl','twoWay','doppler','useInEKF'}, ...
                {'measurements','twstft','enable'}, ...
                {'measurements','twstft','code','enable'}, ...
                {'measurements','twstft','code','useInEKF'}, ...
                {'multiAsset','twoWayISL','enable'}, ...
                {'multiAsset','twoWayTimeTransferISL','enable'}, ...
                {'multiAsset','twoWayTimeTransferISL','useInEKF'}};
            tf = false;
            for index = 1:numel(paths)
                if revgnss.IndependentFleetCoordinator.logicalPath_(cfg,paths{index},false)
                    tf = true;
                    return
                end
            end
            isRangeSanctioned = strcmp(sanctionedObservable,'coherentTwoWayCodeRange');
            isTimeTransferSanctioned = strcmp(sanctionedObservable,'firstOrderReciprocalClockTransfer');
            isOneWayCodeSanctioned = strcmp(sanctionedObservable,'oneWayCode');
            isOneWayDopplerSanctioned = strcmp(sanctionedObservable,'oneWayDoppler');
            anySanctioned = isRangeSanctioned || isTimeTransferSanctioned || ...
                isOneWayCodeSanctioned || isOneWayDopplerSanctioned;
            % measurements.isl.enable: exempt under ANY sanctioned observable (shared parent of
            % both the two-way and one-way distributed subtrees).
            if ~anySanctioned && revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','enable'},false)
                tf = true;
                return
            end
            % measurements.isl.twoWay.enable: exempt under range OR time-transfer only.
            if ~(isRangeSanctioned || isTimeTransferSanctioned) && ...
                    revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','twoWay','enable'},false)
                tf = true;
                return
            end
            % measurements.isl.oneWay.enable: exempt under oneWayCode OR oneWayDoppler only.
            if ~(isOneWayCodeSanctioned || isOneWayDopplerSanctioned) && ...
                    revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','oneWay','enable'},false)
                tf = true;
                return
            end
            % Per-observable leaf toggles: exempt only under their own tuple.
            if ~isRangeSanctioned && revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','twoWay','range','enable'},false)
                tf = true;
                return
            end
            if ~isTimeTransferSanctioned && revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','twoWay','timeTransfer','enable'},false)
                tf = true;
                return
            end
            if ~isOneWayCodeSanctioned && revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','oneWay','code','enable'},false)
                tf = true;
                return
            end
            if ~isOneWayDopplerSanctioned && revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','oneWay','doppler','enable'},false)
                tf = true;
                return
            end
        end

        function requireSanctionedIslConfiguration_(cfg, sanctionedObservable)
            % requireSanctionedIslConfiguration_  Additional gates reachable ONLY under a
            % sanctioned linkUpdate tuple (plan Section 2.3.1 G4-G8-family, widened in Section
            % 2.3.2 for firstOrderReciprocalClockTransfer): every persistent calibration/plasma/
            % reciprocity error source the SANCTIONED observable's own builder could inject must
            % be identically zero/disabled (invariant 8 -- none of these are modelled as a
            % distributed-adapter state, so a nonzero value would leak into R as white per-epoch
            % noise), and no two enabled links may share the same initiator (a second same-epoch
            % delivery to one owner would linearize at a stale pre-update prior;
            % revgnss.OwnerLocalEstimatorEndpointProvider is frozen at construction and cannot
            % see an update applied earlier in the same epoch).
            sanctionedObservable = char(sanctionedObservable);
            if strcmp(sanctionedObservable,'coherentTwoWayCodeRange')
                if ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                        cfg,{'measurements','isl','twoWay','enable'},false) || ...
                        ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                        cfg,{'measurements','isl','twoWay','range','enable'},false)
                    error('IndependentFleetCoordinator:twoWayRangeNotEnabled', ...
                        'The sanctioned tuple requires measurements.isl.twoWay.enable and .range.enable both true.');
                end
                requireZero_ = @(path,identifierSuffix) revgnss.IndependentFleetCoordinator. ...
                    requireZeroPath_(cfg,path,identifierSuffix);
                requireZero_({'measurements','isl','twoWay','truth','turnaroundCalibrationError_s'}, ...
                    'persistentCalibrationUnavailableForDistributedRow');
                requireZero_({'measurements','isl','twoWay','truth','terminalCalibrationError_s'}, ...
                    'persistentCalibrationUnavailableForDistributedRow');
                requireZero_({'measurements','isl','twoWay','calibration','turnaroundSigma_s'}, ...
                    'persistentCalibrationUnavailableForDistributedRow');
                requireZero_({'measurements','isl','twoWay','calibration','terminalSigma_s'}, ...
                    'persistentCalibrationUnavailableForDistributedRow');
                if revgnss.IndependentFleetCoordinator.logicalPath_( ...
                        cfg,{'measurements','isl','twoWay','calibration','residualBiasState','enable'},false)
                    error('IndependentFleetCoordinator:persistentCalibrationUnavailableForDistributedRow', ...
                        'measurements.isl.twoWay.calibration.residualBiasState.enable must be false.');
                end
                requireZero_({'measurements','isl','twoWay','range','plasma','residualSigma_m'}, ...
                    'plasmaGroupDelayUnavailableForDistributedRow');
                if revgnss.IndependentFleetCoordinator.logicalPath_( ...
                        cfg,{'measurements','isl','twoWay','range','plasma','enable'},false)
                    error('IndependentFleetCoordinator:plasmaGroupDelayUnavailableForDistributedRow', ...
                        'measurements.isl.twoWay.range.plasma.enable must be false.');
                end
            elseif strcmp(sanctionedObservable,'firstOrderReciprocalClockTransfer')
                if ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                        cfg,{'measurements','isl','twoWay','enable'},false) || ...
                        ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                        cfg,{'measurements','isl','twoWay','timeTransfer','enable'},false)
                    error('IndependentFleetCoordinator:twoWayTimeTransferNotEnabled', ...
                        ['The sanctioned tuple requires measurements.isl.twoWay.enable and ' ...
                        '.timeTransfer.enable both true.']);
                end
                if revgnss.IndependentFleetCoordinator.logicalPath_( ...
                        cfg,{'measurements','isl','twoWay','timeTransfer','includeReciprocityResidual'},false)
                    error('IndependentFleetCoordinator:reciprocityTermUnavailableForDistributedRow', ...
                        ['measurements.isl.twoWay.timeTransfer.includeReciprocityResidual must be ' ...
                        'false: the reciprocal clock-transfer adapter does not support the ' ...
                        'reciprocity term.']);
                end
                % Mirrors revgnss.DistributedClockGaugeContract.TimeTransferPersistentDelayConfig
                % Paths_ exactly: without this, a nonzero persistent time-transfer delay source
                % passes validateConfig but every delivery is rejected at propose() time via
                % requireTimeTransferCalibrationProvenance, silently degrading the sanctioned
                % tuple to zero consumed link updates instead of failing at construction.
                requireZeroTimeTransfer_ = @(path,identifierSuffix) revgnss.IndependentFleetCoordinator. ...
                    requireZeroPath_(cfg,path,identifierSuffix);
                requireZeroTimeTransfer_({'measurements','isl','twoWay','timeTransfer','calibration', ...
                    'terminalDelayError_s'},'persistentTimeTransferDelayUnavailableForDistributedRow');
                requireZeroTimeTransfer_({'measurements','isl','twoWay','timeTransfer','calibration', ...
                    'terminalSigma_s'},'persistentTimeTransferDelayUnavailableForDistributedRow');
                requireZeroTimeTransfer_({'measurements','isl','twoWay','truth', ...
                    'terminalCalibrationError_s'},'persistentTimeTransferDelayUnavailableForDistributedRow');
                requireZeroTimeTransfer_({'measurements','isl','twoWay','calibration','terminalSigma_s'}, ...
                    'persistentTimeTransferDelayUnavailableForDistributedRow');
            elseif strcmp(sanctionedObservable,'oneWayCode') || strcmp(sanctionedObservable,'oneWayDoppler')
                if ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                        cfg,{'measurements','isl','oneWay','enable'},false)
                    error('IndependentFleetCoordinator:oneWayNotEnabled', ...
                        'The sanctioned tuple requires measurements.isl.oneWay.enable=true.');
                end
                if strcmp(sanctionedObservable,'oneWayCode')
                    if ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                            cfg,{'measurements','isl','oneWay','code','enable'},false)
                        error('IndependentFleetCoordinator:oneWayCodeNotEnabled', ...
                            'The sanctioned tuple requires measurements.isl.oneWay.code.enable=true.');
                    end
                else
                    if ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                            cfg,{'measurements','isl','oneWay','doppler','enable'},false)
                        error('IndependentFleetCoordinator:oneWayDopplerNotEnabled', ...
                            'The sanctioned tuple requires measurements.isl.oneWay.doppler.enable=true.');
                    end
                end
                % revgnss.OneWayInterSatelliteObservationBuilder.validateConfig is otherwise
                % NEVER called by anything (unlike TwoWayISLMeasurementBuilder/InterSatelliteTime
                % TransferBuilder, which ConfigFactory.finalizeConfig registers directly) -- every
                % gate inside it (sigmaSource/linkBudget.model vocabulary, schedule bounds,
                % positive sigmas, link-identity/co-firing uniqueness) was previously unreachable
                % dead code. Scoped to the sanctioned tuple so no other path's behaviour moves.
                revgnss.OneWayInterSatelliteObservationBuilder.validateConfig(cfg);
                % Mirrors the time-transfer persistent-delay precedent exactly (Section 2.3.2's
                % own review finding): without this, a nonzero persistent one-way terminal-delay
                % source passes validateConfig but every delivery is rejected at propose() time,
                % silently degrading the sanctioned tuple to zero consumed link updates instead
                % of failing at construction.
                requireZeroOneWay_ = @(path,identifierSuffix) revgnss.IndependentFleetCoordinator. ...
                    requireZeroPath_(cfg,path,identifierSuffix);
                requireZeroOneWay_({'measurements','isl','oneWay','calibration', ...
                    'transmitTerminalDelayError_s'},'persistentOneWayDelayUnavailableForDistributedRow');
                requireZeroOneWay_({'measurements','isl','oneWay','calibration', ...
                    'receiveTerminalDelayError_s'},'persistentOneWayDelayUnavailableForDistributedRow');
                requireZeroOneWay_({'measurements','isl','oneWay','calibration','terminalSigma_s'}, ...
                    'persistentOneWayDelayUnavailableForDistributedRow');
                % The legacy broadcast-ephemeris product (revgnss.ISLMeasurementBuilder's
                % productBias_) has no counterpart on this path at all -- OneWayInterSatellite
                % ObservationBuilder never reads measurements.isl.product.*. Refused by name
                % rather than left silently inert: a user who enables it here would reasonably
                % expect it to affect the sanctioned tuple, and it never does (invariant 6 --
                % unsupported combinations fail validation, they never silently no-op).
                % Only .enable is checked, matching how ISLMeasurementBuilder.productCfg_ itself
                % treats these keys: masterConfig's shipped sigmaPos_m/sigmaClock_m/etc defaults
                % are NOT zero (0.05 m / 0.03 m / ...), but productCfg_ unconditionally zeroes
                % all four the moment enable=false, so they are already fully inert on the
                % legacy path too -- requiring them literally zero here would only force users
                % to override four keys that were never going to be read, not close a real gap.
                if revgnss.IndependentFleetCoordinator.logicalPath_( ...
                        cfg,{'measurements','isl','product','enable'},false)
                    error('IndependentFleetCoordinator:broadcastProductUnavailableForDistributedRow', ...
                        'measurements.isl.product.enable must be false under the sanctioned one-way tuple.');
                end
                if revgnss.IndependentFleetCoordinator.logicalPath_( ...
                        cfg,{'measurements','isl','lightTime','enable'},false)
                    error('IndependentFleetCoordinator:lightTimeCorrectionUnavailableForDistributedRow', ...
                        'measurements.isl.lightTime.enable must be false under the sanctioned one-way tuple.');
                end
            else
                error('IndependentFleetCoordinator:sanctionedObservable', ...
                    'requireSanctionedIslConfiguration_ requires a sanctioned observable.');
            end

            isOneWayFamily = strcmp(sanctionedObservable,'oneWayCode') || ...
                strcmp(sanctionedObservable,'oneWayDoppler');
            if isOneWayFamily
                links = revgnss.OneWayInterSatelliteObservationBuilder.linkDefinitions(cfg);
                if ~isempty(links)
                    receiverIndices = [links.receiverAssetIndex];
                    if numel(unique(receiverIndices)) ~= numel(receiverIndices)
                        error('IndependentFleetCoordinator:coFiringLinksPerOwner', ...
                            ['No two enabled one-way links may share the same receiverAssetIndex: ' ...
                            'a second same-epoch delivery to one owner cannot see the first ' ...
                            'delivery''s update.']);
                    end
                end
                return
            end

            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            if strcmp(sanctionedObservable,'coherentTwoWayCodeRange')
                for linkIndex = 1:numel(links)
                    link = links(linkIndex);
                    if isfield(link,'turnaroundCalibrationError_s') && ...
                            isnumeric(link.turnaroundCalibrationError_s) && ...
                            link.turnaroundCalibrationError_s ~= 0
                        error('IndependentFleetCoordinator:persistentCalibrationUnavailableForDistributedRow', ...
                            'Link %d declares a nonzero turnaroundCalibrationError_s.',linkIndex);
                    end
                    if isfield(link,'terminalCalibrationError_s') && ...
                            isnumeric(link.terminalCalibrationError_s) && ...
                            link.terminalCalibrationError_s ~= 0
                        error('IndependentFleetCoordinator:persistentCalibrationUnavailableForDistributedRow', ...
                            'Link %d declares a nonzero terminalCalibrationError_s.',linkIndex);
                    end
                end
            end
            if ~isempty(links)
                initiatorIndices = [links.initiatorAssetIndex];
                if numel(unique(initiatorIndices)) ~= numel(initiatorIndices)
                    error('IndependentFleetCoordinator:coFiringLinksPerOwner', ...
                        ['No two enabled links may share the same initiatorAssetIndex: a second ' ...
                        'same-epoch delivery to one owner cannot see the first delivery''s update.']);
                end
            end
        end

        function requireZeroPath_(cfg,path,identifierSuffix)
            value = revgnss.IndependentFleetCoordinator.numericPath_(cfg,path,0);
            if value ~= 0
                error(['IndependentFleetCoordinator:' identifierSuffix], ...
                    '%s must be exactly zero under the sanctioned linkUpdate tuple.', ...
                    strjoin(path,'.'));
            end
        end
    end
end
