classdef IndependentFleetCoordinator < handle
    % IndependentFleetCoordinator  Epoch-synchronous independent local EKFs.

    properties
        cfg (1,1) struct
        localSimulations cell = {}
        exchangeJournal = []
        deliveryLedger = []
        tVec (:,1) double = []
        nAssets (1,1) double = 0
        isInitialized (1,1) logical = false
        isComplete (1,1) logical = false
    end

    properties (Access = private)
        calibrationRegistry_ = []
        estimatorEligibleProducts_ cell = {}
        pendingLinkDeliveries_ cell = {}
        coordinatorGeneratedCount_ (1,1) double = 0
        coordinatorDeliveredCount_ (1,1) double = 0
    end

    properties (Constant)
        ArchitectureLabel = 'independentLocalEkfsGroundOnly'
    end

    methods
        function obj = IndependentFleetCoordinator(cfg)
            if nargin > 0
                obj.cfg = cfg;
            end
        end

        function initialize(obj)
            if obj.isInitialized; return; end
            obj.cfg = revgnss.ConfigFactory.finalizeConfig(obj.cfg);
            revgnss.IndependentFleetCoordinator.validateConfig(obj.cfg);
            settings = revgnss.IndependentFleetCoordinator.settingsFromConfig(obj.cfg);
            setup = revgnss.IndependentFleetScenarioFactory.federatedSetup(obj.cfg,false);
            obj.nAssets = setup.N;
            obj.localSimulations = cell(1,obj.nAssets);
            obj.exchangeJournal = revgnss.CommunicationExchangeJournal();
            if settings.deliveryLedger.enable
                obj.deliveryLedger = revgnss.DistributedDeliveryLedger();
            end
            obj.calibrationRegistry_ = revgnss.DistributedLinkCalibrationRegistry( ...
                settings.linkUpdate.calibrationOwnership.policy);

            for assetIndex = 1:obj.nAssets
                leafCfg = revgnss.IndependentFleetScenarioFactory.stageOneLeafConfigForIndex( ...
                    setup,obj.cfg,assetIndex);
                localSim = revgnss.ReverseGNSSSimulation(leafCfg);
                localSim.initialize();
                if assetIndex == 1
                    obj.tVec = localSim.tVec;
                elseif ~isequal(localSim.tVec,obj.tVec)
                    error('IndependentFleetCoordinator:epochGrid', ...
                        'Every local estimator must use the same coordinate-time epoch grid.');
                end
                obj.localSimulations{assetIndex} = localSim;
            end
            obj.requireDistinctLocalClockSeeds_();
            if settings.stateExchange.enable && obj.nAssets < 2
                error('IndependentFleetCoordinator:stateExchangeAssetCount', ...
                    'State exchange requires at least two local spacecraft estimators.');
            end
            obj.isInitialized = true;
        end

        function run(obj)
            if ~obj.isInitialized; obj.initialize(); end
            if obj.isComplete; return; end
            settings = revgnss.IndependentFleetCoordinator.settingsFromConfig(obj.cfg);

            % Per-epoch phase order (frozen by revgnss.DistributedLinkProtocolContract.
            % EpochFinalizationPhaseOrder, plan Section 2.0.1): truth advance + local
            % prediction -> local ground/onboard update -> publish/freeze estimator products
            % -> generate/validate/deliver link records -> owner-only link update -> commit
            % local history and report data. Phases 4-5 remain no-ops unless validateConfig's
            % sanctioned tuple (Section 2.3.1: enable=true, ownerPolicy='initiator',
            % correlationPolicy='splitCovarianceIntersection',
            % updateAdapter.observable='coherentTwoWayCodeRange') is active; every other
            % combination is rejected before run() can be reached, so nothing partial ever
            % flows through them.
            %
            % COMMIT-ORDERING HAZARD: CLOSED. The loop below runs the local update through
            % runLocalEstimationEpochWithoutHistoryCommit, which stages this epoch's
            % history/report row but does not write it, and releases it through
            % commitPendingEpochHistory only after phases 3-5. recordEpoch/logStep read
            % ekf.x/P at commit time, so the owner-only link update filled into
            % applyOwnerOnlyLinkUpdate_ is described by THIS epoch's history/NEES row rather
            % than mutating state behind an already-written one. That closes the blocker
            % recorded in the plan's Stage-2 readiness decision ("current local history is
            % committed before a later link update could be recorded") and in the Section 2.0
            % completion record. lastEstimatedEpoch is deliberately NOT deferred: phase 3's
            % product publication requires it to be current.
            for epochIndex = 1:numel(obj.tVec)
                for assetIndex = 1:obj.nAssets
                    obj.localSimulations{assetIndex}.advanceTruthEpoch(epochIndex);
                end
                for assetIndex = 1:obj.nAssets
                    localSimulation = obj.localSimulations{assetIndex};
                    localSimulation.runLocalEstimationEpochWithoutHistoryCommit(epochIndex);
                end
                if settings.stateExchange.enable
                    obj.publishStateProducts_(epochIndex,settings);
                end
                obj.generateValidateDeliverLinkRecords_(epochIndex,settings);
                obj.applyOwnerOnlyLinkUpdate_(epochIndex,settings);
                for assetIndex = 1:obj.nAssets
                    obj.localSimulations{assetIndex}.commitPendingEpochHistory();
                end
                obj.exchangeJournal.advanceToEpoch(obj.tVec(epochIndex), ...
                    settings.stateExchange.maximumAge_s);
            end

            for assetIndex = 1:obj.nAssets
                obj.localSimulations{assetIndex}.finishRun(false);
            end
            obj.isComplete = true;
            counters = obj.linkObservationCounters_();
            fprintf('Independent fleet complete: %d local EKFs, %d state products, %d ISL updates.\n', ...
                obj.nAssets,obj.exchangeJournal.numberProducts(),counters.consumedByOwner);
        end

        function results = getResults(obj)
            if ~obj.isInitialized
                error('IndependentFleetCoordinator:notInitialized', ...
                    'Initialize the independent fleet before requesting results.');
            end
            results = struct('architectureLabel',obj.ArchitectureLabel, ...
                'N',obj.nAssets,'asset',{cell(1,obj.nAssets)}, ...
                'endpointStateProducts',obj.exchangeJournal.export(), ...
                'stateExchange',obj.exchangeJournal.summary(), ...
                'linkObservationCounters',obj.linkObservationCounters_(), ...
                'linkDelivery',revgnss.DistributedDeliveryLedger.summaryOrEmpty(obj.deliveryLedger), ...
                'complete',obj.isComplete);
            for assetIndex = 1:obj.nAssets
                results.asset{assetIndex} = obj.extractAssetResult_( ...
                    obj.localSimulations{assetIndex},assetIndex);
            end
        end

        function summary = runtimeSummary(obj)
            counters = obj.linkObservationCounters_();
            summary = struct('architectureLabel',obj.ArchitectureLabel, ...
                'nAssets',obj.nAssets, ...
                'independentLocalEkfs',true, ...
                'stateExchange',obj.exchangeJournal.summary(), ...
                'linkObservationCounters',counters, ...
                'linkDelivery',revgnss.DistributedDeliveryLedger.summaryOrEmpty(obj.deliveryLedger), ...
                'relativeEstimatorStatus','notImplementedInStage1', ...
                'linkFusionStatus','notImplementedInStage1');
        end

        function products = estimatorEligibleProducts(obj)
            % estimatorEligibleProducts  Read-only accessor for the Section 2.1 additive
            % publication path (stateExchange.estimatorEligibleProfile.enable). Empty unless
            % that toggle is enabled; every Stage-1 diagnostic-only path is unaffected by it.
            products = obj.estimatorEligibleProducts_;
        end
    end

    methods (Static)
        function tf = isEnabled(cfg)
            tf = false;
            if ~(isfield(cfg,'multiAsset') && isstruct(cfg.multiAsset) && ...
                    isfield(cfg.multiAsset,'distributedEstimator'))
                return
            end
            raw = cfg.multiAsset.distributedEstimator;
            if ~(isstruct(raw) && isfield(raw,'enable'))
                tf = true;  % Route malformed requests to the strict validator.
                return
            end
            tf = ~(islogical(raw.enable) && isscalar(raw.enable) && ~raw.enable);
        end

        function settings = settingsFromConfig(cfg)
            settings = revgnss.IndependentFleetCoordinator.defaultSettings_();
            if ~(isfield(cfg,'multiAsset') && ...
                    isfield(cfg.multiAsset,'distributedEstimator'))
                return
            end
            source = cfg.multiAsset.distributedEstimator;
            if ~isstruct(source); return; end
            names = fieldnames(settings);
            for index = 1:numel(names)
                name = names{index};
                if isfield(source,name)
                    settings.(name) = source.(name);
                end
            end
        end

        function validateConfig(cfg)
            if ~(isfield(cfg,'multiAsset') && ...
                    isfield(cfg.multiAsset,'distributedEstimator'))
                return
            end
            raw = cfg.multiAsset.distributedEstimator;
            if ~isstruct(raw)
                error('IndependentFleetCoordinator:configurationType', ...
                    'cfg.multiAsset.distributedEstimator must be a struct.');
            end
            required = {'enable','executionMode','stateExchange','linkUpdate', ...
                'outOfSequencePolicy','deliveryLedger'};
            for index = 1:numel(required)
                if ~isfield(raw,required{index})
                    error('IndependentFleetCoordinator:configurationField', ...
                        'distributedEstimator.%s must be declared in masterConfig.',required{index});
                end
            end
            settings = revgnss.IndependentFleetCoordinator.settingsFromConfig(cfg);
            revgnss.IndependentFleetCoordinator.requireLogical_(settings.enable,'enable');
            if ~(isstruct(settings.stateExchange) && isfield(settings.stateExchange,'enable') && ...
                    isfield(settings.stateExchange,'maximumAge_s') && ...
                    isfield(settings.stateExchange,'deliveryDelay_s') && ...
                    isfield(settings.stateExchange,'estimatorEligibleProfile') && ...
                    isstruct(settings.stateExchange.estimatorEligibleProfile) && ...
                    isfield(settings.stateExchange.estimatorEligibleProfile,'enable'))
                error('IndependentFleetCoordinator:stateExchangeSchema', ...
                    ['distributedEstimator.stateExchange requires enable, maximumAge_s, ' ...
                    'deliveryDelay_s, and estimatorEligibleProfile.enable.']);
            end
            if ~(isstruct(settings.linkUpdate) && isfield(settings.linkUpdate,'enable') && ...
                    isfield(settings.linkUpdate,'ownerPolicy') && ...
                    isfield(settings.linkUpdate,'correlationPolicy') && ...
                    isfield(settings.linkUpdate,'commonSourceTreatment') && ...
                    isfield(settings.linkUpdate,'timeTransferClockClaim') && ...
                    isfield(settings.linkUpdate,'remoteProductPropagationPolicy') && ...
                    isfield(settings.linkUpdate,'roleReversalPolicy') && ...
                    isfield(settings.linkUpdate,'calibrationOwnership') && ...
                    isstruct(settings.linkUpdate.calibrationOwnership) && ...
                    isfield(settings.linkUpdate.calibrationOwnership,'policy') && ...
                    isfield(settings.linkUpdate,'updateAdapter') && ...
                    isstruct(settings.linkUpdate.updateAdapter) && ...
                    isfield(settings.linkUpdate.updateAdapter,'observable'))
                error('IndependentFleetCoordinator:linkUpdateSchema', ...
                    ['distributedEstimator.linkUpdate requires enable, ownerPolicy, ' ...
                    'correlationPolicy, commonSourceTreatment, timeTransferClockClaim, ' ...
                    'remoteProductPropagationPolicy, roleReversalPolicy, ' ...
                    'calibrationOwnership.policy, and updateAdapter.observable.']);
            end
            if ~(isstruct(settings.deliveryLedger) && isfield(settings.deliveryLedger,'enable'))
                error('IndependentFleetCoordinator:configurationField', ...
                    'distributedEstimator.deliveryLedger requires enable.');
            end
            revgnss.IndependentFleetCoordinator.requireLogical_( ...
                settings.stateExchange.enable,'stateExchange.enable');
            revgnss.IndependentFleetCoordinator.requireLogical_( ...
                settings.stateExchange.estimatorEligibleProfile.enable, ...
                'stateExchange.estimatorEligibleProfile.enable');
            revgnss.IndependentFleetCoordinator.requireLogical_( ...
                settings.linkUpdate.enable,'linkUpdate.enable');
            revgnss.IndependentFleetCoordinator.requireLogical_( ...
                settings.deliveryLedger.enable,'deliveryLedger.enable');
            revgnss.IndependentFleetCoordinator.requireNonnegative_( ...
                settings.stateExchange.maximumAge_s,'stateExchange.maximumAge_s');
            revgnss.IndependentFleetCoordinator.requireNonnegative_( ...
                settings.stateExchange.deliveryDelay_s,'stateExchange.deliveryDelay_s');
            if ~strcmp(revgnss.IndependentFleetCoordinator.requireText_( ...
                    settings.executionMode,'executionMode'),'epochSynchronous')
                error('IndependentFleetCoordinator:executionMode', ...
                    'Stage 1 supports executionMode=''epochSynchronous'' only.');
            end
            if ~strcmp(revgnss.IndependentFleetCoordinator.requireText_( ...
                    settings.outOfSequencePolicy,'outOfSequencePolicy'),'reject')
                error('IndependentFleetCoordinator:outOfSequencePolicy', ...
                    'Stage 1 supports outOfSequencePolicy=''reject'' only.');
            end
            ownerPolicy = revgnss.IndependentFleetCoordinator.requireText_( ...
                settings.linkUpdate.ownerPolicy,'linkUpdate.ownerPolicy');
            correlationPolicy = revgnss.IndependentFleetCoordinator.requireText_( ...
                settings.linkUpdate.correlationPolicy,'linkUpdate.correlationPolicy');
            observable = char(revgnss.IndependentFleetCoordinator.requireText_( ...
                settings.linkUpdate.updateAdapter.observable,'linkUpdate.updateAdapter.observable'));
            % Stage 2.0 freezes the correlation and clock-claim vocabulary (Sections 2.0.5,
            % 2.0.6). requireCommonSourceTreatmentDeclared and requireClockClaim validate
            % schema/vocabulary membership unconditionally; every commonSourceTreatment entry
            % must still be 'rejected' (no covariance-group/shared-state treatment exists).
            revgnss.DistributedLinkProtocolContract.requireCommonSourceTreatmentDeclared( ...
                settings.linkUpdate.commonSourceTreatment);
            clockClaim = revgnss.IndependentFleetCoordinator.requireText_( ...
                settings.linkUpdate.timeTransferClockClaim,'linkUpdate.timeTransferClockClaim');
            revgnss.DistributedLinkProtocolContract.requireClockClaim(clockClaim);
            commonSourceRejected = ...
                revgnss.DistributedLinkProtocolContract.isFullyRejectedCommonSourceTreatment( ...
                settings.linkUpdate.commonSourceTreatment);

            % Plan Section 2.3.1: exactly ONE non-disabled configuration is sanctioned --
            % coherentTwoWayCodeRange under splitCovarianceIntersection, owned by the
            % initiator, every common source still rejected. Every other combination
            % (including any partial/mixed one) fails validation; there is no silent
            % fallback (invariant 6).
            sanctionedActive = settings.linkUpdate.enable && strcmp(ownerPolicy,'initiator') && ...
                strcmp(correlationPolicy,'splitCovarianceIntersection') && ...
                strcmp(observable,'coherentTwoWayCodeRange') && commonSourceRejected;
            allDisabled = ~settings.linkUpdate.enable && strcmp(ownerPolicy,'disabled') && ...
                strcmp(correlationPolicy,'disabled') && strcmp(observable,'none') && ...
                commonSourceRejected;
            if ~sanctionedActive && ~allDisabled
                error('IndependentFleetCoordinator:linkUpdateUnavailable', ...
                    ['Only two distributedEstimator.linkUpdate configurations are supported: ' ...
                    'fully disabled (enable=false, ownerPolicy=''disabled'', ' ...
                    'correlationPolicy=''disabled'', updateAdapter.observable=''none''), or the ' ...
                    'sanctioned tuple (enable=true, ownerPolicy=''initiator'', ' ...
                    'correlationPolicy=''splitCovarianceIntersection'', ' ...
                    'updateAdapter.observable=''coherentTwoWayCodeRange'', every ' ...
                    'commonSourceTreatment entry ''rejected''). No partial/mixed combination ' ...
                    'is accepted.']);
            end
            if sanctionedActive
                revgnss.DistributedLinkUpdateAdapter.requireObservableSelectable(observable);
                revgnss.DistributedLinkUpdateAdapter.requireRegisteredAdapter( ...
                    'revgnss.CoherentTwoWayRangeLinkUpdateAdapter');
                revgnss.SplitCovarianceIntersectionBound.requireObservableHasDemonstratedBound( ...
                    observable);
                % deliveryLedger is a separate toggle (defaults false) from linkUpdate.enable;
                % phases 4-5 unconditionally call obj.deliveryLedger.recordEligible/recordConsumed/
                % recordRejected once linkUpdate is active, including on the rejection path
                % itself, so leaving it disabled here would crash on the first generated link
                % record instead of failing cleanly at construction time.
                if ~settings.deliveryLedger.enable
                    error('IndependentFleetCoordinator:deliveryLedgerRequiredForSanctionedTuple', ...
                        ['The sanctioned linkUpdate tuple requires ' ...
                        'distributedEstimator.deliveryLedger.enable=true: phases 4-5 record every ' ...
                        'generated link record (eligible, consumed, or rejected) in the fleet-wide ' ...
                        'ledger unconditionally.']);
                end
            end

            % Three word toggles remain pinned to their single frozen legal value regardless of
            % sanctionedActive: no propagation/role-reversal/calibration-ownership treatment is
            % implemented for ANY observable (invariant 6).
            if ~strcmp(char(revgnss.IndependentFleetCoordinator.requireText_( ...
                    settings.linkUpdate.remoteProductPropagationPolicy, ...
                    'linkUpdate.remoteProductPropagationPolicy')),'frozenSameEpochOnly') || ...
                    ~strcmp(char(revgnss.IndependentFleetCoordinator.requireText_( ...
                    settings.linkUpdate.roleReversalPolicy,'linkUpdate.roleReversalPolicy')), ...
                    'disabled') || ...
                    ~strcmp(char(revgnss.IndependentFleetCoordinator.requireText_( ...
                    settings.linkUpdate.calibrationOwnership.policy, ...
                    'linkUpdate.calibrationOwnership.policy')),'undeclared')
                error('IndependentFleetCoordinator:section21ControlsUnavailable', ...
                    ['No implementation exists for remoteProductPropagationPolicy, ' ...
                    'roleReversalPolicy, or calibrationOwnership.policy other than their ' ...
                    'single frozen default.']);
            end

            % Per-asset-leaf assertion: a leaf runs one local estimator and owns no fleet
            % accounting. This STRENGTHENS the existing leaf-forcing convention (see
            % IndependentFleetScenarioFactory, which forces both sub-toggles false on every
            % leaf) into an asserted invariant rather than an implicit convention.
            isPerAssetLeaf = revgnss.IndependentFleetCoordinator.logicalPath_( ...
                cfg,{'multiAsset','perAssetLeaf'},false);
            if isPerAssetLeaf && (settings.stateExchange.estimatorEligibleProfile.enable || ...
                    settings.deliveryLedger.enable)
                error('IndependentFleetCoordinator:perAssetLeafSubToggleUnavailable', ...
                    ['A per-asset leaf configuration runs one local estimator and owns no ' ...
                    'fleet accounting. stateExchange.estimatorEligibleProfile.enable and ' ...
                    'deliveryLedger.enable belong to the coordinator config and must be false ' ...
                    'on a leaf; IndependentFleetScenarioFactory forces them false alongside ' ...
                    'distributedEstimator.enable, stateExchange.enable, and linkUpdate.enable.']);
            end

            % Coupling checks run unconditionally (even when distributedEstimator.enable is
            % false), so an unsupported combination fails in configuration validation rather
            % than silently no-op-ing (invariant 6). Because isPerAssetLeaf already forces both
            % antecedents false on any leaf, these checks never fire there.
            if settings.stateExchange.estimatorEligibleProfile.enable && ...
                    ~settings.stateExchange.enable
                error('IndependentFleetCoordinator:estimatorEligibleProfileRequiresStateExchange', ...
                    'stateExchange.estimatorEligibleProfile.enable requires stateExchange.enable=true.');
            end
            if settings.stateExchange.estimatorEligibleProfile.enable
                revgnss.DistributedLinkProtocolContract.requireSameEpochScope(settings.stateExchange);
            end
            if settings.deliveryLedger.enable && ~settings.enable
                error('IndependentFleetCoordinator:deliveryLedgerRequiresFleet', ...
                    'deliveryLedger.enable requires distributedEstimator.enable=true.');
            end

            if ~settings.enable; return; end

            nAssets = revgnss.IndependentFleetCoordinator.numericPath_( ...
                cfg,{'scenario','nSpaceAssets'},1);
            if nAssets < 2
                error('IndependentFleetCoordinator:assetCount', ...
                    'Independent fleet execution requires scenario.nSpaceAssets >= 2.');
            end
            mode = revgnss.IndependentFleetCoordinator.textPath_( ...
                cfg,{'multiAsset','mode'},'fast');
            if ~strcmpi(mode,'fast')
                error('IndependentFleetCoordinator:mode', ...
                    'Independent fleet execution requires multiAsset.mode=''fast''; joint remains separate.');
            end
            if ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'orbit','useOrbitPropagator'},false)
                error('IndependentFleetCoordinator:orbitPropagator', ...
                    'Independent fleet execution requires orbit.useOrbitPropagator=true.');
            end
            orbitMode = revgnss.IndependentFleetCoordinator.textPath_( ...
                cfg,{'orbit','mode'},'');
            if ~any(strcmpi(orbitMode,{'twoBodyRk4','j2Rk4'}))
                error('IndependentFleetCoordinator:orbitMode', ...
                    ['Independent fleet execution requires orbit.mode=''twoBodyRk4'' ' ...
                    'or ''j2Rk4'' because every member uses an explicit ECI initial state.']);
            end
            if ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'rng','independentStreams','enable'},false)
                error('IndependentFleetCoordinator:independentRng', ...
                    ['Independent fleet execution requires rng.independentStreams.enable=true ' ...
                    'so epoch staging cannot change a local noise realization.']);
            end
            % islUpdateUnavailable: every ISL/TWSTFT path stays unconditionally rejected EXCEPT
            % the three (measurements.isl.enable, .twoWay.enable, .twoWay.range.enable) the
            % sanctioned coherentTwoWayCodeRange tuple legitimately needs -- and even those three
            % are permitted ONLY under sanctionedActive. range.useInEKF and
            % multiAsset.keepIslInPerAssetEkf stay rejected always: the distributed path never
            % routes an ISL row through the joint/per-asset-leaf EKF linearizer.
            if revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'multiAsset','keepIslInPerAssetEkf'},false) || ...
                    revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','twoWay','range','useInEKF'},false) || ...
                    revgnss.IndependentFleetCoordinator.islObservableRequested_(cfg,sanctionedActive)
                error('IndependentFleetCoordinator:islUpdateUnavailable', ...
                    ['Only measurements.isl.enable/.twoWay.enable/.twoWay.range.enable may be ' ...
                    'true, and only under the sanctioned linkUpdate tuple. ' ...
                    'measurements.isl.twoWay.range.useInEKF and multiAsset.keepIslInPerAssetEkf ' ...
                    'must always stay false; every other ISL/TWSTFT observable path must stay ' ...
                    'disabled.']);
            end
            if sanctionedActive
                revgnss.IndependentFleetCoordinator.requireSanctionedIslConfiguration_(cfg);
            end
            estimateMode = revgnss.IndependentFleetCoordinator.textPath_( ...
                cfg,{'multiAsset','estimateMode'},'off');
            if ~strcmpi(estimateMode,'off') || ...
                    revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'multiAsset','towersObserveSecondaries'},false)
                error('IndependentFleetCoordinator:centralSecondaryState', ...
                    ['Stage 1 uses one complete local EKF per asset; centralized secondary ' ...
                    'state allocation is incompatible and must remain disabled.']);
            end
        end
    end

    methods (Access = private)
        function generateValidateDeliverLinkRecords_(obj, epochIndex, settings)
            % generateValidateDeliverLinkRecords_  Section 2.0.1 phase 4. Truth is read HERE,
            % by the simulator (plan Section 2.0.1 explicitly permits this), via the same
            % revgnss.TwoWayISLMeasurementBuilder.generateObservations the joint path uses.
            % Every truth diagnostic is discarded immediately; nothing downstream of this
            % method ever receives a SpaceAsset/clock/truth handle. Each successfully proposed
            % delivery is recorded ELIGIBLE in the fleet-wide ledger and staged for phase 5; a
            % rejected proposal is recorded REJECTED with its exact reason, never an uncaught
            % error and never silently dropped.
            obj.pendingLinkDeliveries_ = {};
            if ~settings.linkUpdate.enable; return; end

            t_s = obj.tVec(epochIndex);
            assets = cellfun(@(sim) sim.asset,obj.localSimulations,'UniformOutput',false);
            [observations,~,info] = revgnss.TwoWayISLMeasurementBuilder.generateObservations( ...
                obj.cfg,assets{1},assets,t_s);
            info.truthDiagnostic = []; %#ok<NASGU>

            for observationIndex = 1:numel(observations)
                record = observations{observationIndex};
                linkInfo = info.linkInfos{observationIndex};
                linkInfo.truthDiagnostic = []; %#ok<NASGU>
                obj.coordinatorGeneratedCount_ = obj.coordinatorGeneratedCount_ + 1;

                try
                    ownerCanonical = revgnss.CanonicalEndpointIdentity.fromRecordIdentifier( ...
                        record.initiatorAssetIdentifier);
                    remoteCanonical = revgnss.CanonicalEndpointIdentity.fromRecordIdentifier( ...
                        record.transponderAssetIdentifier);
                    ownerIdx = ownerCanonical.physicalAssetIndex;
                    remoteIdx = remoteCanonical.physicalAssetIndex;
                    if ownerIdx < 1 || ownerIdx > obj.nAssets || remoteIdx < 1 || remoteIdx > obj.nAssets
                        error('IndependentFleetCoordinator:linkEndpointOutOfRange', ...
                            'Link record %s names an asset index outside the running fleet.', ...
                            record.observationIdentifier);
                    end

                    terminalGeometry = revgnss.IndependentFleetCoordinator.terminalGeometryFromRecord_( ...
                        record,'owner');
                    remoteTerminalGeometry = revgnss.IndependentFleetCoordinator.terminalGeometryFromRecord_( ...
                        record,'remote');
                    ownerProvider = revgnss.OwnerLocalEstimatorEndpointProvider.fromLocalSimulation( ...
                        obj.localSimulations{ownerIdx},ownerIdx,t_s,terminalGeometry);

                    remoteSim = obj.localSimulations{remoteIdx};
                    diagnosticProduct = revgnss.EndpointStateProduct.fromLocalEstimator( ...
                        remoteSim,remoteIdx,t_s,0, ...
                        sprintf('spacecraft:%d:epoch:%09d',remoteIdx,epochIndex));
                    eligibleProduct = revgnss.EstimatorEligibleEndpointStateProduct.fromDiagnosticProduct( ...
                        diagnosticProduct,settings.linkUpdate.commonSourceTreatment);
                    remoteProvider = revgnss.FrozenProductEndpointProvider.fromEstimatorEligibleProduct( ...
                        eligibleProduct,t_s,remoteTerminalGeometry);

                    linkDefinitionIndex = 0;
                    if isfield(linkInfo,'linkDefinitionIndex')
                        linkDefinitionIndex = linkInfo.linkDefinitionIndex;
                    end
                    calibrationProduct = revgnss.TwoWayISLMeasurementBuilder. ...
                        calibrationProductForLinkDefinitionIndex(obj.cfg,linkDefinitionIndex);

                    proposeArgs = struct( ...
                        'physicalObservationRecord',record, ...
                        'ownerProvider',ownerProvider, ...
                        'remoteProvider',remoteProvider, ...
                        'ownerPolicy',settings.linkUpdate.ownerPolicy, ...
                        'roleReversalPolicy',settings.linkUpdate.roleReversalPolicy, ...
                        'remoteProductPropagationPolicy',settings.linkUpdate.remoteProductPropagationPolicy, ...
                        'stateExchangeSettings',struct('maximumAge_s',settings.stateExchange.maximumAge_s, ...
                            'deliveryDelay_s',settings.stateExchange.deliveryDelay_s), ...
                        'outOfSequencePolicy',settings.outOfSequencePolicy, ...
                        'commonSourceTreatment',settings.linkUpdate.commonSourceTreatment, ...
                        'correlationPolicy',settings.linkUpdate.correlationPolicy, ...
                        'calibrationRegistry',obj.calibrationRegistry_, ...
                        'deliveryEpoch_s',t_s,'coordinateEventEpoch_s',t_s, ...
                        'observableIdentifier',settings.linkUpdate.updateAdapter.observable, ...
                        'persistentCalibrationTreatment','rejected');
                    [delivery,rejection] = revgnss.LinkObservationDelivery.tryPropose(proposeArgs);
                    if rejection.rejected
                        obj.rejectRecord_(record,t_s,rejection.reasonCode,rejection.reasonMessage, ...
                            rejection.sourceErrorIdentifier);
                        continue
                    end
                    obj.deliveryLedger.recordEligible(delivery);
                    obj.pendingLinkDeliveries_{end+1} = struct( ...
                        'delivery',delivery,'calibrationProduct',calibrationProduct); %#ok<AGROW>
                catch ME
                    obj.rejectRecord_(record,t_s,'observablePredictionFailed',ME.message,ME.identifier);
                end
            end
        end

        function applyOwnerOnlyLinkUpdate_(obj, epochIndex, settings)
            % applyOwnerOnlyLinkUpdate_  Section 2.0.1 phase 5. Each staged delivery is applied
            % to its OWNER leaf's own local EKF only, via the certified conservative bound
            % (revgnss.SplitCovarianceIntersectionBound, extended to the full owner state by
            % revgnss.ConservativeFullStateLinkUpdate). ekf.x/P mutation here is safely ordered:
            % run() commits each local history row AFTER this phase, so this epoch's recorded
            % state/NEES row describes the post-update state.
            if ~settings.linkUpdate.enable; return; end
            t_s = obj.tVec(epochIndex); %#ok<NASGU>

            for index = 1:numel(obj.pendingLinkDeliveries_)
                staged = obj.pendingLinkDeliveries_{index};
                delivery = staged.delivery;
                try
                    obj.applyOneLinkUpdate_(delivery,staged.calibrationProduct);
                    obj.deliveryLedger.recordConsumed(delivery.observationIdentifier, ...
                        delivery.ownerAssetIdentifier,delivery.deliveryEpoch_s);
                    ownerSim = obj.localSimulations{delivery.ownerCanonicalIndex};
                    ownerSim.observationLedger.markEligible(delivery.physicalObservationRecord, ...
                        delivery.deliveryEpoch_s);
                    ownerSim.observationLedger.consume(delivery.physicalObservationRecord, ...
                        delivery.deliveryEpoch_s);
                    obj.coordinatorDeliveredCount_ = obj.coordinatorDeliveredCount_ + 1;
                catch ME
                    obj.deliveryLedger.recordRejectedFromEligible(delivery.observationIdentifier, ...
                        'observablePredictionFailed',ME.message,ME.identifier);
                end
            end
            obj.pendingLinkDeliveries_ = {};
        end

        function applyOneLinkUpdate_(obj, delivery, calibrationProduct)
            % applyOneLinkUpdate_  Builds the real physics block (adapter), the certified
            % conservative full-state bound, and applies it to the OWNER leaf's own EKF. Throws
            % on any failure; the caller (applyOwnerOnlyLinkUpdate_) converts that into a mapped
            % ledger rejection rather than an uncaught error.
            ownerState = delivery.ownerProvider.stateAtCoordinateEpoch(delivery.coordinateEventEpoch_s);
            remoteState = delivery.remoteProvider.stateAtCoordinateEpoch(delivery.coordinateEventEpoch_s);

            steps = revgnss.IndependentFleetCoordinator.linearizationStepsFromConfig_(obj.cfg);
            buildArgs = struct( ...
                'delivery',delivery,'ownerState',ownerState,'remoteState',remoteState, ...
                'calibrationProduct',calibrationProduct,'linearizationSteps',steps, ...
                'solverOptions',struct(),'modeledPropagationGroupDelay_s',0, ...
                'weightSelectionRule','fixedDeclaredWeights', ...
                'persistentCalibrationTreatment','rejected');
            [block, ~] = revgnss.CoherentTwoWayRangeLinkUpdateAdapter.buildUpdateBlock(buildArgs);
            revgnss.DistributedLinkUpdateAdapter.requireUpdateBlock(block,delivery,ownerState,remoteState);

            ownerSim = obj.localSimulations{delivery.ownerCanonicalIndex};
            blk = revgnss.AssetStateBlock.forAsset(ownerSim.ekf.stateMap,1);
            schemaIndices = [blk.r(:);blk.v(:);blk.euler(:);ownerSim.ekf.stateMap.omega_idx(:); ...
                blk.b;blk.bdot];

            Hi = block.ownerJacobian_mPerErrorUnit;
            Hj = block.remoteJacobian_mPerErrorUnit;
            Pi_schema = ownerSim.ekf.P(schemaIndices,schemaIndices);
            Pi_schema = (Pi_schema+Pi_schema')/2;
            Pj = remoteState.covarianceBlock;
            Rind = block.independentMeasurementCovariance_m2;
            Sremote = Hj*Pj*Hj'; Sremote = (Sremote+Sremote')/2;
            K0 = Pi_schema*Hi'/(Hi*Pi_schema*Hi' + Sremote + Rind);
            declaredWeights = revgnss.ConservativeFullStateLinkUpdate.declaredWeightsFromFullStateTraces( ...
                ownerSim.ekf.P,schemaIndices,Hi,K0,Sremote);

            emptyCommonRows = struct('covarianceGroupIdentifier',{},'commonSourceName',{}, ...
                'contribution_m2',{},'sourceProductIdentifier',{});
            emptyCalibRows = struct('calibrationStateIdentifier',{}, ...
                'mappingColumn_mPerCalibrationUnit',{},'stateUnits',{},'priorVariance',{}, ...
                'priorVarianceUnits',{});
            rawBoundArgs = struct( ...
                'ownerPriorCovariance_errorUnit2',Pi_schema, ...
                'ownerJacobian_mPerErrorUnit',Hi, ...
                'remotePriorCovariance_errorUnit2',Pj, ...
                'remoteJacobian_mPerErrorUnit',Hj, ...
                'totalMeasurementCovariance_m2',Rind, ...
                'totalMeasurementCovarianceIncludesDeclaredCommonSources',true, ...
                'declaredCommonSourceContributions',emptyCommonRows, ...
                'declaredCalibrationContributions',emptyCalibRows, ...
                'ownerCovarianceComponentOrder',{ownerState.covarianceComponentOrder}, ...
                'ownerAttitudeErrorCoordinateConvention',ownerState.attitudeErrorCoordinateConvention, ...
                'remoteCovarianceComponentOrder',{remoteState.covarianceComponentOrder}, ...
                'remoteAttitudeErrorCoordinateConvention',remoteState.attitudeErrorCoordinateConvention, ...
                'weightSelectionRule','fixedDeclaredWeights', ...
                'declaredWeights',declaredWeights, ...
                'correlationPolicy','splitCovarianceIntersection');
            [scaledArgs, ownerScale, ~] = ...
                revgnss.ConservativeFullStateLinkUpdate.rescaleBoundArgsToUnitDiagonal(rawBoundArgs);
            boundResult = revgnss.SplitCovarianceIntersectionBound.ownerPosteriorBound(scaledArgs);

            applyArgs = struct( ...
                'xPrior',ownerSim.ekf.x,'PPrior',ownerSim.ekf.P,'schemaStateIndices',schemaIndices, ...
                'boundResult',boundResult,'H_owner',Hi,'ownerScale',ownerScale, ...
                'residual_m',block.residual_m, ...
                'attitudeParameterization',ownerSim.ekf.attitudeParameterization, ...
                'nominalQuatPrior',ownerSim.ekf.nominalQuat_wxyz(:,1));
            result = revgnss.ConservativeFullStateLinkUpdate.applyOwnerOnlyUpdate(applyArgs);

            ownerSim.ekf.x = result.xPosterior;
            ownerSim.ekf.P = result.PPosterior;
            ownerSim.ekf.nominalQuat_wxyz(:,1) = result.nominalQuatPosterior;
            if result.attitudeInjectionNorm_rad > 0
                ownerSim.ekf.attitudeInjectionCount = ownerSim.ekf.attitudeInjectionCount + 1;
                ownerSim.ekf.maxAttitudeInjectionNorm_rad = max( ...
                    ownerSim.ekf.maxAttitudeInjectionNorm_rad,result.attitudeInjectionNorm_rad);
            end
        end

        function rejectRecord_(obj, record, deliveryEpoch_s, reasonCode, reasonMessage, sourceErrorIdentifier)
            rejectionRecord = struct( ...
                'observationIdentifier',record.observationIdentifier, ...
                'ownerAssetIdentifier','', ...
                'remoteProductIdentifier','', ...
                'sourceEpoch_s',deliveryEpoch_s, ...
                'deliveryEpoch_s',deliveryEpoch_s, ...
                'reasonCode',reasonCode, ...
                'reasonMessage',reasonMessage, ...
                'sourceErrorIdentifier',sourceErrorIdentifier, ...
                'physicalRecordClass',class(record));
            obj.deliveryLedger.recordRejected(rejectionRecord);
        end

        function publishStateProducts_(obj, epochIndex, settings)
            % publishStateProducts_  Section 2.0.4/2.1: the Stage-1 diagnostic product and
            % journal record below are UNCHANGED. When
            % stateExchange.estimatorEligibleProfile.enable is true, an ADDITIONAL immutable
            % revgnss.EstimatorEligibleEndpointStateProduct is built from the same diagnostic
            % product and stored for later retrieval (estimatorEligibleProducts()); nothing is
            % consumed, no ekf.x/P is touched, and the Stage-1 path below never sees this branch.
            sourceEpoch_s = obj.tVec(epochIndex);
            for assetIndex = 1:obj.nAssets
                sequenceIdentifier = sprintf('spacecraft:%d:epoch:%09d', ...
                    assetIndex,epochIndex);
                product = revgnss.EndpointStateProduct.fromLocalEstimator( ...
                    obj.localSimulations{assetIndex},assetIndex,sourceEpoch_s, ...
                    settings.stateExchange.deliveryDelay_s,sequenceIdentifier);
                obj.exchangeJournal.record(product,sourceEpoch_s);
                if settings.stateExchange.estimatorEligibleProfile.enable
                    eligibleProduct = revgnss.EstimatorEligibleEndpointStateProduct. ...
                        fromDiagnosticProduct(product,settings.linkUpdate.commonSourceTreatment);
                    obj.estimatorEligibleProducts_{end+1} = eligibleProduct;
                end
            end
        end

        function counters = linkObservationCounters_(obj)
            % linkObservationCounters_  `generated` sums the LEAF-populated count (always 0 on
            % the distributed path, since records are generated by THIS coordinator at phase 4,
            % never written to any leaf's interSatelliteObservations) plus the coordinator's own
            % phase-4 count (always 0 on the disabled path) -- so the disabled-path value is
            % unchanged and the active-path value is real, never internally contradictory
            % against a nonzero consumedByOwner.
            consumed = 0;
            leafGenerated = 0;
            for assetIndex = 1:numel(obj.localSimulations)
                sim = obj.localSimulations{assetIndex};
                if isempty(sim); continue; end
                consumed = consumed + sim.observationLedger.numberConsumed();
                leafGenerated = leafGenerated + numel(sim.interSatelliteObservations);
            end
            counters = struct('generated',leafGenerated+obj.coordinatorGeneratedCount_, ...
                'delivered',obj.coordinatorDeliveredCount_, ...
                'consumedByOwner',consumed);
        end

        function result = extractAssetResult_(~, sim, assetIndex)
            sm = sim.ekf.stateMap;
            result = struct('assetIndex',assetIndex, ...
                'assetIdentifier',sprintf('spacecraft:%d',assetIndex), ...
                'assetName',sim.asset.name, ...
                'x',sim.ekf.x,'P',sim.ekf.P,'stateMap',sm, ...
                'history',sim.ekf.history,'truthR',sim.asset.r_ecef_m, ...
                'truthV',sim.asset.v_ecef_mps, ...
                'truthClk',sim.asset.clock.getBiasMeters(), ...
                'cfg',sim.cfg);
            if sim.orbitTruthCache.enabled
                result.truthTraj = sim.orbitTruthCache.r_ecef_m;
                result.truthVelTraj = sim.orbitTruthCache.v_ecef_mps;
                result.truthTime_s = sim.orbitTruthCache.t_s(:).';
            else
                result.truthTraj = sim.asset.history.r_ecef_m;
                result.truthVelTraj = sim.asset.history.v_ecef_mps;
                result.truthTime_s = sim.asset.history.time_s(:).';
            end
            result.truthClkTraj_m = [];
            result.truthClkTime_s = [];
            try
                if ~isempty(sim.asset.clock.history.bias_s)
                    result.truthClkTraj_m = sim.asset.clock.history.bias_s(:).' * ...
                        revgnss.Constants.SPEED_OF_LIGHT_MPS;
                    result.truthClkTime_s = sim.asset.clock.history.time_s(:).';
                end
            catch
            end
        end

        function requireDistinctLocalClockSeeds_(obj)
            clockSeeds = zeros(1,obj.nAssets);
            for assetIndex = 1:obj.nAssets
                clockSeeds(assetIndex) = obj.localSimulations{assetIndex}.asset.clock.seed;
            end
            if numel(unique(clockSeeds)) ~= obj.nAssets
                error('IndependentFleetCoordinator:clockSeed', ...
                    ['Every local spacecraft receiver clock must use a distinct seed. ' ...
                    'Repeated seeds would create an artificial common clock realization.']);
            end
        end
    end

    methods (Static, Access = private)
        function settings = defaultSettings_()
            commonSourceTreatment = struct( ...
                'towerClockProduct','rejected', ...
                'terminalCalibration','rejected', ...
                'transmittedStateProduct','rejected', ...
                'sessionTimingProduct','rejected', ...
                'sharedForceAtmosphericProduct','rejected');
            settings = struct('enable',false,'executionMode','epochSynchronous', ...
                'stateExchange',struct('enable',false,'maximumAge_s',0, ...
                    'deliveryDelay_s',0, ...
                    'estimatorEligibleProfile',struct('enable',false)), ...
                'linkUpdate',struct('enable',false,'ownerPolicy','disabled', ...
                    'correlationPolicy','disabled', ...
                    'commonSourceTreatment',commonSourceTreatment, ...
                    'timeTransferClockClaim','relativeBiasOnly', ...
                    'remoteProductPropagationPolicy','frozenSameEpochOnly', ...
                    'roleReversalPolicy','disabled', ...
                    'calibrationOwnership',struct('policy','undeclared'), ...
                    'updateAdapter',struct('observable','none')), ...
                'outOfSequencePolicy','reject', ...
                'deliveryLedger',struct('enable',false));
        end

        function requireLogical_(value,name)
            if ~(islogical(value) && isscalar(value))
                error('IndependentFleetCoordinator:logicalSetting', ...
                    'distributedEstimator.%s must be a logical scalar.',name);
            end
        end

        function requireNonnegative_(value,name)
            if ~(isnumeric(value) && isscalar(value) && isfinite(value) && value >= 0)
                error('IndependentFleetCoordinator:numericSetting', ...
                    'distributedEstimator.%s must be a finite nonnegative scalar.',name);
            end
        end

        function text = requireText_(value,name)
            if ~(ischar(value) || (isstring(value) && isscalar(value)))
                error('IndependentFleetCoordinator:textSetting', ...
                    'distributedEstimator.%s must be text.',name);
            end
            text = char(value);
        end

        function value = logicalPath_(cfg,path,defaultValue)
            value = defaultValue;
            node = cfg;
            for index = 1:numel(path)
                if ~isstruct(node) || ~isfield(node,path{index}); return; end
                node = node.(path{index});
            end
            if islogical(node) && isscalar(node); value = node; end
        end

        function geometry = terminalGeometryFromRecord_(record, role)
            % terminalGeometryFromRecord_  Builds a declared revgnss.CommunicationEndpointState
            % terminalGeometry struct from the record's own terminal/antenna identifiers and the
            % ESTIMATOR's configured lever arm (never a truth diagnostic value) -- role='owner'
            % reads the record's initiator fields, role='remote' its transponder fields. This is
            % what requireTerminalGeometryMatchesRecord (adapter) cross-checks against.
            leverArm = revgnss.IndependentFleetCoordinator.estimatorLeverArm_();
            if strcmp(role,'owner')
                geometry = struct('declared',true, ...
                    'transmitTerminalIdentifier',record.initiatorTransmitTerminalIdentifier, ...
                    'receiveTerminalIdentifier',record.initiatorReceiveTerminalIdentifier, ...
                    'transmitAntennaIdentifier',record.initiatorTransmitAntennaIdentifier, ...
                    'receiveAntennaIdentifier',record.initiatorReceiveAntennaIdentifier, ...
                    'transmitPhaseCentreOffset_body_m',leverArm, ...
                    'receivePhaseCentreOffset_body_m',leverArm);
            else
                geometry = struct('declared',true, ...
                    'transmitTerminalIdentifier',record.transponderTransmitTerminalIdentifier, ...
                    'receiveTerminalIdentifier',record.transponderReceiveTerminalIdentifier, ...
                    'transmitAntennaIdentifier',record.transponderTransmitAntennaIdentifier, ...
                    'receiveAntennaIdentifier',record.transponderReceiveAntennaIdentifier, ...
                    'transmitPhaseCentreOffset_body_m',leverArm, ...
                    'receivePhaseCentreOffset_body_m',leverArm);
            end
        end

        function leverArm = estimatorLeverArm_()
            % estimatorLeverArm_  The ISL terminal lever arm masterConfig already declares
            % (measurements.isl.twoWay.terminalGeometry.*), matching what
            % revgnss.TwoWayISLMeasurementBuilder.terminalGeometry_ feeds to BOTH the truth and
            % estimator endpoints today -- so the shipped configuration has no phase-centre error
            % to begin with; a future config could diverge them without changing this code.
            leverArm = [0.8;0.2;0.3];
        end

        function steps = linearizationStepsFromConfig_(cfg)
            steps = struct( ...
                'positionStep_m',revgnss.IndependentFleetCoordinator.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','range','linearization','positionStep_m'},0.5), ...
                'velocityStep_mps',revgnss.IndependentFleetCoordinator.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','range','linearization','velocityStep_mps'},0.05), ...
                'attitudeStep_rad',revgnss.IndependentFleetCoordinator.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','range','linearization','attitudeStep_rad'},5e-4), ...
                'clockBiasStep_m',revgnss.IndependentFleetCoordinator.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','range','linearization','clockBiasStep_m'},10), ...
                'clockDriftStep_mps',revgnss.IndependentFleetCoordinator.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','range','linearization','clockDriftStep_mps'},0.01));
        end

        function value = numericPath_(cfg,path,defaultValue)
            value = defaultValue;
            node = cfg;
            for index = 1:numel(path)
                if ~isstruct(node) || ~isfield(node,path{index}); return; end
                node = node.(path{index});
            end
            if isnumeric(node) && isscalar(node) && isfinite(node); value = node; end
        end

        function value = textPath_(cfg,path,defaultValue)
            value = defaultValue;
            node = cfg;
            for index = 1:numel(path)
                if ~isstruct(node) || ~isfield(node,path{index}); return; end
                node = node.(path{index});
            end
            if ischar(node) || (isstring(node) && isscalar(node)); value = char(node); end
        end

        function tf = islObservableRequested_(cfg,sanctionedActive)
            % islObservableRequested_  measurements.isl.enable/.twoWay.enable/.twoWay.range.enable
            % are the three paths the sanctioned coherentTwoWayCodeRange tuple legitimately
            % needs (plan Section 2.3.1 / audit A17: measurements.isl.enable is the two-way
            % builder's OWN parent validation gate, not only the one-way builder's runtime
            % gate) -- exempted from this list ONLY when sanctionedActive, and checked
            % separately by the caller otherwise. Every leaf still forces measurements.isl.enable
            % (and every other measurements.isl.* key) false regardless of this fleet-level
            % value (IndependentFleetScenarioFactory), so this can never reach a per-asset-leaf
            % EKF; range.useInEKF is checked unconditionally by the caller, not here.
            if nargin < 2; sanctionedActive = false; end
            paths = { ...
                {'measurements','isl','code','enable'}, ...
                {'measurements','isl','code','useInEKF'}, ...
                {'measurements','isl','doppler','enable'}, ...
                {'measurements','isl','doppler','useInEKF'}, ...
                {'measurements','isl','carrier','enable'}, ...
                {'measurements','isl','carrier','useInEKF'}, ...
                {'measurements','isl','timing','enable'}, ...
                {'measurements','isl','twoWay','doppler','enable'}, ...
                {'measurements','isl','twoWay','doppler','useInEKF'}, ...
                {'measurements','isl','twoWay','timeTransfer','enable'}, ...
                {'measurements','isl','twoWay','timeTransfer','useInEKF'}, ...
                {'measurements','twstft','enable'}, ...
                {'measurements','twstft','code','enable'}, ...
                {'measurements','twstft','code','useInEKF'}, ...
                {'multiAsset','twoWayISL','enable'}, ...
                {'multiAsset','twoWayTimeTransferISL','enable'}, ...
                {'multiAsset','twoWayTimeTransferISL','useInEKF'}};
            tf = false;
            for index = 1:numel(paths)
                if revgnss.IndependentFleetCoordinator.logicalPath_(cfg,paths{index},false)
                    tf = true;
                    return
                end
            end
            if ~sanctionedActive
                exemptOnlyUnderSanctionedTuple = { ...
                    {'measurements','isl','enable'}, ...
                    {'measurements','isl','twoWay','enable'}, ...
                    {'measurements','isl','twoWay','range','enable'}};
                for index = 1:numel(exemptOnlyUnderSanctionedTuple)
                    if revgnss.IndependentFleetCoordinator.logicalPath_( ...
                            cfg,exemptOnlyUnderSanctionedTuple{index},false)
                        tf = true;
                        return
                    end
                end
            end
        end

        function requireSanctionedIslConfiguration_(cfg)
            % requireSanctionedIslConfiguration_  Additional gates reachable ONLY under the
            % sanctioned coherentTwoWayCodeRange tuple (plan Section 2.3.1 G4-G8-family):
            % the two-way link must be enabled with useInEKF=false, every persistent
            % calibration/plasma error source must be identically zero (invariant 8 -- these
            % are never modelled as a distributed-adapter state, so a nonzero value would leak
            % into R as white per-epoch noise), and no two enabled links may share the same
            % initiator (a second same-epoch delivery to one owner would linearize at a stale
            % pre-update prior; revgnss.OwnerLocalEstimatorEndpointProvider is frozen at
            % construction and cannot see an update applied earlier in the same epoch).
            if ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','twoWay','enable'},false) || ...
                    ~revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','twoWay','range','enable'},false)
                error('IndependentFleetCoordinator:twoWayRangeNotEnabled', ...
                    'The sanctioned tuple requires measurements.isl.twoWay.enable and .range.enable both true.');
            end
            requireZero_ = @(path,identifierSuffix) revgnss.IndependentFleetCoordinator. ...
                requireZeroPath_(cfg,path,identifierSuffix);
            requireZero_({'measurements','isl','twoWay','truth','turnaroundCalibrationError_s'}, ...
                'persistentCalibrationUnavailableForDistributedRow');
            requireZero_({'measurements','isl','twoWay','truth','terminalCalibrationError_s'}, ...
                'persistentCalibrationUnavailableForDistributedRow');
            requireZero_({'measurements','isl','twoWay','calibration','turnaroundSigma_s'}, ...
                'persistentCalibrationUnavailableForDistributedRow');
            requireZero_({'measurements','isl','twoWay','calibration','terminalSigma_s'}, ...
                'persistentCalibrationUnavailableForDistributedRow');
            if revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','twoWay','calibration','residualBiasState','enable'},false)
                error('IndependentFleetCoordinator:persistentCalibrationUnavailableForDistributedRow', ...
                    'measurements.isl.twoWay.calibration.residualBiasState.enable must be false.');
            end
            requireZero_({'measurements','isl','twoWay','range','plasma','residualSigma_m'}, ...
                'plasmaGroupDelayUnavailableForDistributedRow');
            if revgnss.IndependentFleetCoordinator.logicalPath_( ...
                    cfg,{'measurements','isl','twoWay','range','plasma','enable'},false)
                error('IndependentFleetCoordinator:plasmaGroupDelayUnavailableForDistributedRow', ...
                    'measurements.isl.twoWay.range.plasma.enable must be false.');
            end

            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            for linkIndex = 1:numel(links)
                link = links(linkIndex);
                if isfield(link,'turnaroundCalibrationError_s') && ...
                        isnumeric(link.turnaroundCalibrationError_s) && ...
                        link.turnaroundCalibrationError_s ~= 0
                    error('IndependentFleetCoordinator:persistentCalibrationUnavailableForDistributedRow', ...
                        'Link %d declares a nonzero turnaroundCalibrationError_s.',linkIndex);
                end
                if isfield(link,'terminalCalibrationError_s') && ...
                        isnumeric(link.terminalCalibrationError_s) && ...
                        link.terminalCalibrationError_s ~= 0
                    error('IndependentFleetCoordinator:persistentCalibrationUnavailableForDistributedRow', ...
                        'Link %d declares a nonzero terminalCalibrationError_s.',linkIndex);
                end
            end
            if ~isempty(links)
                initiatorIndices = [links.initiatorAssetIndex];
                if numel(unique(initiatorIndices)) ~= numel(initiatorIndices)
                    error('IndependentFleetCoordinator:coFiringLinksPerOwner', ...
                        ['No two enabled links may share the same initiatorAssetIndex: a second ' ...
                        'same-epoch delivery to one owner cannot see the first delivery''s update.']);
                end
            end
        end

        function requireZeroPath_(cfg,path,identifierSuffix)
            value = revgnss.IndependentFleetCoordinator.numericPath_(cfg,path,0);
            if value ~= 0
                error(['IndependentFleetCoordinator:' identifierSuffix], ...
                    '%s must be exactly zero under the sanctioned linkUpdate tuple.', ...
                    strjoin(path,'.'));
            end
        end
    end
end
