classdef InterSatelliteTimeTransferBuilder
    % InterSatelliteTimeTransferBuilder  Scenario-gated reciprocal ISL clock rows.

    methods (Static)
        function validateConfig(cfg)
            enabled = revgnss.InterSatelliteTimeTransferBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','timeTransfer','enable'},false);
            useInEkf = revgnss.InterSatelliteTimeTransferBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','timeTransfer','useInEKF'},false);
            if useInEkf && ~enabled
                error('InterSatelliteTimeTransferBuilder:useGuard', ...
                    'timeTransfer.useInEKF requires timeTransfer.enable=true.');
            end
            if ~enabled
                return
            end
            if ~revgnss.InterSatelliteTimeTransferBuilder.getBool_( ...
                    cfg,{'measurements','isl','enable'},false) || ...
                    ~revgnss.InterSatelliteTimeTransferBuilder.getBool_( ...
                    cfg,{'measurements','isl','twoWay','enable'},false)
                error('InterSatelliteTimeTransferBuilder:parentDisabled', ...
                    ['ISL time transfer requires measurements.isl.enable and ' ...
                     'measurements.isl.twoWay.enable.']);
            end
            mode = revgnss.InterSatelliteTimeTransferBuilder.walk_( ...
                cfg,{'measurements','isl','twoWay','timeTransfer','mode'}, ...
                revgnss.ReciprocalTimeTransferModel.FirstOrderMode);
            revgnss.ReciprocalTimeTransferModel.validateMode(mode);
            sigma_m = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','timeTransfer','sigma_m'},NaN);
            reciprocitySigma_m = ...
                revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','timeTransfer', ...
                'reciprocitySigma_m'},NaN);
            warmup_s = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','timeTransfer','warmup_s'},NaN);
            if ~(isfinite(sigma_m) && sigma_m > 0 && ...
                    isfinite(reciprocitySigma_m) && reciprocitySigma_m >= 0 && ...
                    isfinite(warmup_s) && warmup_s >= 0)
                error('InterSatelliteTimeTransferBuilder:parameters', ...
                    'Time-transfer sigmas and warmup must be finite and nonnegative.');
            end
            revgnss.InterSatelliteTimeTransferBuilder.validateLinks_(cfg);
            if useInEkf
                estimatorMode = revgnss.InterSatelliteTimeTransferBuilder.getStr_( ...
                    cfg,{'multiAsset','mode'},'fast');
                if ~strcmp(estimatorMode,'joint')
                    error('InterSatelliteTimeTransferBuilder:jointEstimatorRequired', ...
                        ['ISL clock differences must update both endpoint clocks. ' ...
                         'Use multiAsset.mode=''joint''.']);
                end
            end
        end

        function [observations,truthDiagnostics,info] = ...
                generateObservations(cfg,assets,t_s)
            observations = {};
            truthDiagnostics = {};
            linkInfos = {};
            info = revgnss.InterSatelliteTimeTransferBuilder.defaultInfo_(cfg);
            if ~info.enabled
                return
            end
            links = revgnss.InterSatelliteTimeTransferBuilder.links_(cfg);
            for linkIndex = 1:numel(links)
                link = links(linkIndex);
                if ~revgnss.InterSatelliteTimeTransferBuilder. ...
                        scheduled_(cfg,link,t_s)
                    continue
                end
                referenceIndex = link.initiatorAssetIndex;
                remoteIndex = link.transponderAssetIndex;
                if max(referenceIndex,remoteIndex) > numel(assets)
                    error('InterSatelliteTimeTransferBuilder:endpointAsset', ...
                        'A configured time-transfer endpoint is unavailable.');
                end
                truthReference = ...
                    revgnss.InterSatelliteTimeTransferBuilder.truthState_( ...
                    cfg,assets{referenceIndex},referenceIndex);
                truthRemote = ...
                    revgnss.InterSatelliteTimeTransferBuilder.truthState_( ...
                    cfg,assets{remoteIndex},remoteIndex);
                result = revgnss.ReciprocalTimeTransferModel.evaluate( ...
                    truthReference,truthRemote,info.mode, ...
                    info.includeReciprocityResidual);
                epochIndex = round(t_s/max( ...
                    revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                    cfg,{'simulation','dt_s'},1),eps));
                noise_m = info.sigma_m * ...
                    revgnss.InterSatelliteTimeTransferBuilder.drawNormal_( ...
                    cfg,referenceIndex,remoteIndex,epochIndex);
                variance_m2 = info.sigma_m^2;
                if info.includeReciprocityResidual
                    variance_m2 = variance_m2 + info.reciprocitySigma_m^2;
                end
                observationIdentifier = sprintf( ...
                    '%s:time-transfer:e%09d',link.linkIdentifier,epochIndex);
                record = struct( ...
                    'observationIdentifier',observationIdentifier, ...
                    'sessionIdentifier',sprintf('%s:session:e%09d', ...
                        link.linkIdentifier,epochIndex), ...
                    'linkIdentifier',link.linkIdentifier, ...
                    'referenceAssetIdentifier',sprintf('asset:%d',referenceIndex), ...
                    'remoteAssetIdentifier',sprintf('asset:%d',remoteIndex), ...
                    'referenceTerminalIdentifier',sprintf( ...
                        'asset:%d:isl-time-transfer-terminal',referenceIndex), ...
                    'remoteTerminalIdentifier',sprintf( ...
                        'asset:%d:isl-time-transfer-terminal',remoteIndex), ...
                    'protocolIdentifier','reciprocalTwoWayTimeTransfer', ...
                    'modeIdentifier',info.mode, ...
                    'signalIdentifier',link.signalIdentifier, ...
                    'channelIdentifier',link.channelIdentifier, ...
                    'referenceEpoch_s',t_s, ...
                    'referenceEpochRule','commonCoordinateEpoch', ...
                    'rawTimestampTagsAvailable',false, ...
                    'timestampTags_s',nan(1,4), ...
                    'processedObservableType','twoWayClockDifference', ...
                    'processedValue',result.value_m+noise_m, ...
                    'processedUnits','m', ...
                    'covarianceGroupIdentifier',observationIdentifier, ...
                    'covarianceRowIndex',1, ...
                    'covarianceBlock',variance_m2, ...
                    'covarianceUnits','m^2', ...
                    'calibrationProductIdentifiers',{{ ...
                        link.calibrationProductIdentifier}}, ...
                    'available',true, ...
                    'qualityFlags',struct( ...
                        'scheduled',true, ...
                        'rawTimestampTagsAvailable',false, ...
                        'physicalFourEventModelApplied',false), ...
                    'truthDiagnosticIdentifier',[observationIdentifier '-truth']);
                observation = ...
                    revgnss.InterSatelliteTimeTransferObservationRecord(record);
                diagnostic = struct( ...
                    'diagnosticIdentifier',[observationIdentifier '-truth'], ...
                    'mode',info.mode, ...
                    'referenceAssetIndex',referenceIndex, ...
                    'remoteAssetIndex',remoteIndex, ...
                    'referenceClockBias_m',truthReference.clockBias_m, ...
                    'remoteClockBias_m',truthRemote.clockBias_m, ...
                    'clockDifference_m',result.clockDifference_m, ...
                    'reciprocity_m',result.reciprocity_m, ...
                    'range_m',result.range_m, ...
                    'rangeRate_mps',result.rangeRate_mps, ...
                    'thermalError_m',noise_m);
                linkInfo = revgnss.InterSatelliteTimeTransferBuilder. ...
                    linkInfo_(cfg,assets,link,observation);
                linkInfo.truthDiagnostic = diagnostic;
                observations{end+1} = observation; %#ok<AGROW>
                truthDiagnostics{end+1} = diagnostic; %#ok<AGROW>
                linkInfos{end+1} = linkInfo; %#ok<AGROW>
            end
            info = revgnss.InterSatelliteTimeTransferBuilder. ...
                aggregateInfo_(cfg,linkInfos,observations);
        end

        function [zAdd,hAdd,HAdd,RAdd,info] = ...
                linearizeRecordedObservations( ...
                cfg,observations,x,stateMap,nx,t_s,info)
            if nargin < 7 || isempty(info)
                linkInfos = cell(1,numel(observations));
                for observationIndex = 1:numel(observations)
                    linkInfos{observationIndex} = ...
                        revgnss.InterSatelliteTimeTransferBuilder. ...
                        infoFromObservation_(cfg,observations{observationIndex});
                end
                info = revgnss.InterSatelliteTimeTransferBuilder. ...
                    aggregateInfo_(cfg,linkInfos,observations);
            end
            zAdd = [];
            hAdd = [];
            HAdd = zeros(0,nx);
            RAdd = zeros(0);
            processedInfos = cell(1,numel(observations));
            for observationIndex = 1:numel(observations)
                observation = observations{observationIndex};
                linkInfo = info.linkInfos{observationIndex};
                [zRow,hRow,HRow,RRow,linkInfo] = ...
                    revgnss.InterSatelliteTimeTransferBuilder. ...
                    linearizeRecordedObservation( ...
                    cfg,observation,x,stateMap,nx,t_s,linkInfo);
                processedInfos{observationIndex} = linkInfo;
                if isempty(zRow)
                    continue
                end
                zAdd = [zAdd;zRow]; %#ok<AGROW>
                hAdd = [hAdd;hRow]; %#ok<AGROW>
                HAdd = [HAdd;HRow]; %#ok<AGROW>
                RAdd = blkdiag(RAdd,RRow);
            end
            info = revgnss.InterSatelliteTimeTransferBuilder. ...
                aggregateInfo_(cfg,processedInfos,observations);
            info.zEkf = zAdd;
            info.hEkf = hAdd;
            if ~isempty(zAdd)
                info.prefitRms_m = sqrt(mean((zAdd-hAdd).^2));
            end
        end

        function [zAdd,hAdd,HAdd,RAdd,info] = ...
                linearizeRecordedObservation( ...
                cfg,observation,x,stateMap,nx,t_s,info)
            if ~isa(observation, ...
                    'revgnss.InterSatelliteTimeTransferObservationRecord')
                error('InterSatelliteTimeTransferBuilder:observationType', ...
                    'An immutable ISL time-transfer record is required.');
            end
            if abs(observation.referenceEpoch_s-t_s) > ...
                    10*eps(max(1,abs(t_s)))
                error('InterSatelliteTimeTransferBuilder:observationEpoch', ...
                    'The observation must be processed at its reference epoch.');
            end
            referenceIndex = ...
                revgnss.InterSatelliteTimeTransferBuilder.assetIndex_( ...
                observation.referenceAssetIdentifier);
            remoteIndex = revgnss.InterSatelliteTimeTransferBuilder.assetIndex_( ...
                observation.remoteAssetIdentifier);
            referenceBlock = revgnss.AssetStateBlock.forAsset( ...
                stateMap,referenceIndex);
            remoteBlock = revgnss.AssetStateBlock.forAsset(stateMap,remoteIndex);
            if isempty(referenceBlock.b) || isempty(remoteBlock.b)
                error('InterSatelliteTimeTransferBuilder:endpointState', ...
                    'Both endpoint clock states must be estimated.');
            end
            [modelReference,referenceLeverJacobian] = ...
                revgnss.InterSatelliteTimeTransferBuilder.estimateState_( ...
                cfg,x,referenceBlock);
            [modelRemote,remoteLeverJacobian] = ...
                revgnss.InterSatelliteTimeTransferBuilder.estimateState_( ...
                cfg,x,remoteBlock);
            result = revgnss.ReciprocalTimeTransferModel.evaluate( ...
                modelReference,modelRemote,observation.modeIdentifier, ...
                info.includeReciprocityResidual);
            HRow = zeros(1,nx);
            HRow(referenceBlock.b) = result.referenceClockPartial;
            HRow(remoteBlock.b) = result.remoteClockPartial;
            if info.includeReciprocityResidual
                HRow(referenceBlock.r) = result.referencePositionPartial;
                HRow(referenceBlock.v) = result.referenceVelocityPartial;
                HRow(remoteBlock.r) = result.remotePositionPartial;
                HRow(remoteBlock.v) = result.remoteVelocityPartial;
                if ~isempty(referenceBlock.euler)
                    HRow(referenceBlock.euler) = ...
                        result.referencePositionPartial* ...
                        referenceLeverJacobian;
                end
                if ~isempty(remoteBlock.euler)
                    HRow(remoteBlock.euler) = ...
                        result.remotePositionPartial*remoteLeverJacobian;
                end
            end
            useInEkf = info.useInEKF && observation.available;
            role = 'diagnosticOnly';
            if useInEkf
                role = 'physicalEKF';
            end
            row = revgnss.ObservableRowDescriptor.create( ...
                0,'islTwoWayTimeTransfer',observation.linkIdentifier, ...
                observation.signalIdentifier,NaN,NaN,find(HRow~=0), ...
                'first-order reciprocal inter-satellite clock-difference observable', ...
                role);
            row = revgnss.ObservableRowDescriptor.withFlags(row,true,false);
            info.rows = row;
            info.nRows = 1;
            info.nEkfRows = double(useInEkf);
            info.ekfRowTypes = {};
            info.eligibleObservationRecords = {};
            if useInEkf
                zAdd = observation.processedValue;
                hAdd = result.value_m;
                HAdd = HRow;
                RAdd = observation.covarianceBlock( ...
                    observation.covarianceRowIndex, ...
                    observation.covarianceRowIndex);
                info.ekfRowTypes = {'twoWayTimeTransfer'};
                info.eligibleObservationRecords = {observation};
            else
                zAdd = [];
                hAdd = [];
                HAdd = zeros(0,nx);
                RAdd = zeros(0);
            end
            info.zEkf = zAdd;
            info.hEkf = hAdd;
        end

        function h = predictEkfRows(cfg,x,stateMap,info)
            h = [];
            if isempty(info) || ~isstruct(info) || ...
                    ~isfield(info,'linkInfos')
                return
            end
            for linkIndex = 1:numel(info.linkInfos)
                linkInfo = info.linkInfos{linkIndex};
                if isempty(linkInfo) || linkInfo.nEkfRows < 1 || ...
                        isempty(linkInfo.observationRecord)
                    continue
                end
                observation = linkInfo.observationRecord;
                referenceIndex = ...
                    revgnss.InterSatelliteTimeTransferBuilder.assetIndex_( ...
                    observation.referenceAssetIdentifier);
                remoteIndex = ...
                    revgnss.InterSatelliteTimeTransferBuilder.assetIndex_( ...
                    observation.remoteAssetIdentifier);
                referenceBlock = revgnss.AssetStateBlock.forAsset( ...
                    stateMap,referenceIndex);
                remoteBlock = revgnss.AssetStateBlock.forAsset( ...
                    stateMap,remoteIndex);
                [referenceState,~] = ...
                    revgnss.InterSatelliteTimeTransferBuilder. ...
                    estimateState_(cfg,x,referenceBlock);
                [remoteState,~] = ...
                    revgnss.InterSatelliteTimeTransferBuilder. ...
                    estimateState_(cfg,x,remoteBlock);
                result = revgnss.ReciprocalTimeTransferModel.evaluate( ...
                    referenceState,remoteState,observation.modeIdentifier, ...
                    info.includeReciprocityResidual);
                h(end+1,1) = result.value_m; %#ok<AGROW>
            end
        end
    end

    methods (Static, Access = private)
        function info = defaultInfo_(cfg)
            info = struct( ...
                'enabled',revgnss.InterSatelliteTimeTransferBuilder.getBool_( ...
                    cfg,{'measurements','isl','twoWay','timeTransfer','enable'},false), ...
                'useInEKF',revgnss.InterSatelliteTimeTransferBuilder.getBool_( ...
                    cfg,{'measurements','isl','twoWay','timeTransfer','useInEKF'},false), ...
                'mode',revgnss.InterSatelliteTimeTransferBuilder.getStr_( ...
                    cfg,{'measurements','isl','twoWay','timeTransfer','mode'}, ...
                    revgnss.ReciprocalTimeTransferModel.FirstOrderMode), ...
                'sigma_m',revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                    cfg,{'measurements','isl','twoWay','timeTransfer','sigma_m'},0.03), ...
                'includeReciprocityResidual', ...
                    revgnss.InterSatelliteTimeTransferBuilder.getBool_( ...
                    cfg,{'measurements','isl','twoWay','timeTransfer', ...
                    'includeReciprocityResidual'},false), ...
                'reciprocitySigma_m', ...
                    revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                    cfg,{'measurements','isl','twoWay','timeTransfer', ...
                    'reciprocitySigma_m'},0.005), ...
                'linkInfos',{{}}, ...
                'observationRecords',{{}}, ...
                'eligibleObservationRecords',{{}}, ...
                'rows',struct([]), ...
                'ekfRowTypes',{{}}, ...
                'nRows',0, ...
                'nEkfRows',0, ...
                'prefitRms_m',NaN);
        end

        function info = aggregateInfo_(cfg,linkInfos,observations)
            info = revgnss.InterSatelliteTimeTransferBuilder.defaultInfo_(cfg);
            info.linkInfos = linkInfos;
            info.observationRecords = observations;
            for linkIndex = 1:numel(linkInfos)
                linkInfo = linkInfos{linkIndex};
                if isempty(linkInfo)
                    continue
                end
                info.nRows = info.nRows + linkInfo.nRows;
                info.nEkfRows = info.nEkfRows + linkInfo.nEkfRows;
                info.rows = [info.rows,linkInfo.rows];
                info.ekfRowTypes = [info.ekfRowTypes, ...
                    linkInfo.ekfRowTypes];
                info.eligibleObservationRecords = [ ...
                    info.eligibleObservationRecords, ...
                    linkInfo.eligibleObservationRecords];
            end
        end

        function info = linkInfo_(cfg,assets,link,observation)
            info = revgnss.InterSatelliteTimeTransferBuilder.defaultInfo_(cfg);
            info.referenceAssetIndex = link.initiatorAssetIndex;
            info.remoteAssetIndex = link.transponderAssetIndex;
            info.referenceAssetName = assets{link.initiatorAssetIndex}.name;
            info.remoteAssetName = assets{link.transponderAssetIndex}.name;
            info.linkIdentifier = link.linkIdentifier;
            info.observationRecord = observation;
            info.truthDiagnostic = [];
            info.rows = struct([]);
            info.ekfRowTypes = {};
            info.eligibleObservationRecords = {};
        end

        function info = infoFromObservation_(cfg,observation)
            links = revgnss.InterSatelliteTimeTransferBuilder.links_(cfg);
            match = find(strcmp({links.linkIdentifier}, ...
                observation.linkIdentifier),1);
            if isempty(match)
                error('InterSatelliteTimeTransferBuilder:linkIdentity', ...
                    'Observation link %s is not configured.', ...
                    observation.linkIdentifier);
            end
            placeholderAssets = cell(1,max( ...
                links(match).initiatorAssetIndex, ...
                links(match).transponderAssetIndex));
            for assetIndex = 1:numel(placeholderAssets)
                placeholderAssets{assetIndex} = struct( ...
                    'name',sprintf('asset-%d',assetIndex));
            end
            info = revgnss.InterSatelliteTimeTransferBuilder.linkInfo_( ...
                cfg,placeholderAssets,links(match),observation);
        end

        function links = links_(cfg)
            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            if isempty(links)
                referenceIndex = ...
                    revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                    cfg,{'measurements','isl','receiverAssetIndex'},1);
                remoteIndex = ...
                    revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                    cfg,{'measurements','isl','transmitterAssetIndex'},2);
                links = struct( ...
                    'linkIdentifier', ...
                        revgnss.InterSatelliteTimeTransferBuilder.getStr_( ...
                        cfg,{'measurements','isl','twoWay','linkIdentifier'}, ...
                        sprintf('isl-two-way-link-A%d-A%d', ...
                        referenceIndex,remoteIndex)), ...
                    'initiatorAssetIndex',referenceIndex, ...
                    'transponderAssetIndex',remoteIndex, ...
                    'calibrationProductIdentifier', ...
                        revgnss.InterSatelliteTimeTransferBuilder.getStr_( ...
                        cfg,{'measurements','isl','twoWay','timeTransfer', ...
                        'calibration','productIdentifier'}, ...
                        'isl-time-transfer-calibration'), ...
                    'signalIdentifier', ...
                        revgnss.InterSatelliteTimeTransferBuilder.getStr_( ...
                        cfg,{'measurements','isl','twoWay','signalIdentifier'}, ...
                        'ISL-PN'), ...
                    'channelIdentifier', ...
                        revgnss.InterSatelliteTimeTransferBuilder.getStr_( ...
                        cfg,{'measurements','isl','twoWay','channelIdentifier'}, ...
                        'PN-1'), ...
                    'schedule',struct( ...
                        'updatePhase_s', ...
                        revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                        cfg,{'measurements','isl','twoWay','schedule', ...
                        'updatePhase_s'},0), ...
                        'commandIdentifier', ...
                        revgnss.InterSatelliteTimeTransferBuilder.getStr_( ...
                        cfg,{'measurements','isl','twoWay','schedule', ...
                        'commandIdentifier'},'scenario-open-loop')));
            else
                for linkIndex = 1:numel(links)
                    if isfield(links,'timeTransferCalibrationProductIdentifier') && ...
                            ~isempty(links(linkIndex). ...
                            timeTransferCalibrationProductIdentifier)
                        productIdentifier = char(links(linkIndex). ...
                            timeTransferCalibrationProductIdentifier);
                    else
                        productIdentifier = sprintf( ...
                            '%s:time-transfer-calibration', ...
                            char(links(linkIndex).linkIdentifier));
                    end
                    links(linkIndex).calibrationProductIdentifier = ...
                        productIdentifier;
                end
            end
        end

        function validateLinks_(cfg)
            links = revgnss.InterSatelliteTimeTransferBuilder.links_(cfg);
            nAssets = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'scenario','nSpaceAssets'},1);
            period_s = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','schedule', ...
                'updatePeriod_s'},NaN);
            start_s = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','schedule','start_s'},0);
            stop_s = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','schedule','stop_s'},NaN);
            if ~(isfinite(period_s) && period_s > 0 && ...
                    isfinite(start_s) && isfinite(stop_s) && stop_s >= start_s)
                error('InterSatelliteTimeTransferBuilder:schedule', ...
                    'The time-transfer schedule must have a positive period and valid bounds.');
            end
            identifiers = cell(1,numel(links));
            calibrationIdentifiers = cell(1,numel(links));
            for linkIndex = 1:numel(links)
                endpoints = [links(linkIndex).initiatorAssetIndex, ...
                    links(linkIndex).transponderAssetIndex];
                if any(endpoints ~= round(endpoints)) || ...
                        any(endpoints < 1) || any(endpoints > nAssets) || ...
                        endpoints(1) == endpoints(2)
                    error('InterSatelliteTimeTransferBuilder:endpoints', ...
                        'Each time-transfer link requires two distinct configured spacecraft.');
                end
                identifiers{linkIndex} = char( ...
                    links(linkIndex).linkIdentifier);
                calibrationIdentifiers{linkIndex} = char( ...
                    links(linkIndex).calibrationProductIdentifier);
                phase_s = links(linkIndex).schedule.updatePhase_s;
                if ~(isscalar(phase_s) && isfinite(phase_s) && ...
                        phase_s >= 0 && phase_s < period_s)
                    error('InterSatelliteTimeTransferBuilder:schedulePhase', ...
                        'Each time-transfer link phase must be inside one update period.');
                end
            end
            if numel(unique(identifiers)) ~= numel(identifiers) || ...
                    numel(unique(calibrationIdentifiers)) ~= ...
                    numel(calibrationIdentifiers)
                error('InterSatelliteTimeTransferBuilder:linkIdentity', ...
                    'Time-transfer link and calibration identifiers must be unique.');
            end
            revgnss.InterSatelliteTimeTransferBuilder.meanTerminalLever_(cfg,1);
        end

        function scheduled = scheduled_(cfg,link,t_s)
            warmup_s = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','timeTransfer','warmup_s'},0);
            start_s = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','schedule','start_s'},0);
            stop_s = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','schedule','stop_s'},1e12);
            if t_s < max(warmup_s,start_s) || t_s > stop_s
                scheduled = false;
                return
            end
            outages = revgnss.InterSatelliteTimeTransferBuilder.walk_( ...
                cfg,{'measurements','isl','twoWay','schedule','outages_s'}, ...
                zeros(0,2));
            if ~isempty(outages) && any(t_s >= outages(:,1) & t_s <= outages(:,2))
                scheduled = false;
                return
            end
            period_s = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','schedule','updatePeriod_s'},1);
            phase_s = link.schedule.updatePhase_s;
            dt_s = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'simulation','dt_s'},1);
            remainder = mod(t_s-phase_s,period_s);
            scheduled = min(remainder,period_s-remainder) <= ...
                10*eps(max(1,period_s)) + dt_s*1e-10;
        end

        function state = truthState_(cfg,asset,assetIndex)
            lever = revgnss.InterSatelliteTimeTransferBuilder. ...
                meanTerminalLever_(cfg,assetIndex);
            state = struct( ...
                'position_m',revgnss.AttitudeKinematics.applyLeverArm( ...
                    asset.r_ecef_m,asset.attitude_euler_rad,lever), ...
                'velocity_mps',asset.v_ecef_mps(:), ...
                'clockBias_m',asset.clock.getBiasMeters());
        end

        function [state,leverJacobian] = estimateState_(cfg,x,block)
            lever = revgnss.InterSatelliteTimeTransferBuilder. ...
                meanTerminalLever_(cfg,1);
            euler = revgnss.AssetStateBlock.eulerEst(block,x);
            state = struct( ...
                'position_m',revgnss.AttitudeKinematics.applyLeverArm( ...
                    x(block.r),euler,lever), ...
                'velocity_mps',x(block.v), ...
                'clockBias_m',x(block.b));
            leverJacobian = ...
                revgnss.InterSatelliteTimeTransferBuilder. ...
                leverJacobian_(cfg,euler,lever);
        end

        function lever = meanTerminalLever_(cfg,~)
            transmitLever = revgnss.InterSatelliteTimeTransferBuilder.walk_( ...
                cfg,{'measurements','isl','twoWay','terminalGeometry', ...
                'transmitPhaseCentreOffset_body_m'},zeros(3,1));
            receiveLever = revgnss.InterSatelliteTimeTransferBuilder.walk_( ...
                cfg,{'measurements','isl','twoWay','terminalGeometry', ...
                'receivePhaseCentreOffset_body_m'},zeros(3,1));
            if ~isnumeric(transmitLever) || numel(transmitLever) ~= 3 || ...
                    ~isnumeric(receiveLever) || numel(receiveLever) ~= 3
                error('InterSatelliteTimeTransferBuilder:terminalGeometry', ...
                    'ISL transmit and receive phase centres must contain three metres.');
            end
            lever = 0.5*(transmitLever(:)+receiveLever(:));
        end

        function jacobian = leverJacobian_(cfg,euler,lever)
            parameterization = ...
                revgnss.InterSatelliteTimeTransferBuilder.getStr_( ...
                cfg,{'estimator','attitude','parameterization'},'eulerZYX');
            if ~strcmp(parameterization,'quaternionErrorState')
                jacobian = ...
                    revgnss.AttitudeKinematics. ...
                    finiteDiffLeverArmJacobian(euler,lever,1e-6);
                return
            end
            nominalRotation = ...
                revgnss.AttitudeKinematics.bodyToEcefRotation(euler);
            step_rad = 1e-6;
            jacobian = zeros(3,3);
            for component = 1:3
                positive = zeros(3,1);
                negative = zeros(3,1);
                positive(component) = step_rad;
                negative(component) = -step_rad;
                positiveRotation = ...
                    revgnss.AttitudeErrorStateKinematics. ...
                    smallAnglePerturbedDcm(nominalRotation,positive);
                negativeRotation = ...
                    revgnss.AttitudeErrorStateKinematics. ...
                    smallAnglePerturbedDcm(nominalRotation,negative);
                jacobian(:,component) = ...
                    (positiveRotation*lever-negativeRotation*lever)/ ...
                    (2*step_rad);
            end
        end

        function value = drawNormal_(cfg,referenceIndex,remoteIndex,epochIndex)
            seed = revgnss.InterSatelliteTimeTransferBuilder.getNum_( ...
                cfg,{'simulation','seed'},42);
            stream = RandStream('mt19937ar','Seed',mod( ...
                seed+1700003+4001*referenceIndex+7919*remoteIndex+ ...
                104729*epochIndex,2^31-1));
            value = randn(stream,1,1);
        end

        function index = assetIndex_(identifier)
            token = regexp(char(identifier),'^asset:(\d+)$','tokens','once');
            if isempty(token)
                error('InterSatelliteTimeTransferBuilder:assetIdentifier', ...
                    'Asset identifier %s is invalid.',char(identifier));
            end
            index = str2double(token{1});
        end

        function tf = getBool_(cfg,path,defaultValue)
            value = revgnss.InterSatelliteTimeTransferBuilder.walk_( ...
                cfg,path,defaultValue);
            tf = islogical(value) && isscalar(value) && value;
        end

        function value = getNum_(cfg,path,defaultValue)
            value = revgnss.InterSatelliteTimeTransferBuilder.walk_( ...
                cfg,path,defaultValue);
            if ~isnumeric(value) || ~isscalar(value)
                value = defaultValue;
            end
        end

        function value = getStr_(cfg,path,defaultValue)
            value = revgnss.InterSatelliteTimeTransferBuilder.walk_( ...
                cfg,path,defaultValue);
            if ~(ischar(value) || (isstring(value) && isscalar(value)))
                value = defaultValue;
            end
            value = char(value);
        end

        function value = walk_(cfg,path,defaultValue)
            value = cfg;
            for pathIndex = 1:numel(path)
                if isstruct(value) && isfield(value,path{pathIndex})
                    value = value.(path{pathIndex});
                else
                    value = defaultValue;
                    return
                end
            end
        end
    end
end
