classdef LinkObservationDelivery
    % LinkObservationDelivery  Interface #2 (plan Section 2.1): binds one immutable physical
    % observation to canonical endpoints, one owner filter, source/delivery epochs, a frozen
    % estimator-eligible remote product identifier, and covariance/calibration groups.
    %
    % This class performs NO strcmp-based endpoint-identifier translation anywhere: every
    % endpoint binding goes through revgnss.CanonicalEndpointIdentity.requireReconciled. It
    % proves the two LABELS agree; it relies on revgnss.OwnerLocalEstimatorEndpointProvider
    % having already proven, at its own construction, that the label names the filter that
    % actually produced the state (see that class's sourceAsset guard).
    %
    % The lifecycle (eligible/consumed/rejected) itself is NOT owned here: it belongs to
    % revgnss.DistributedDeliveryLedger. This class only proposes one candidate binding.

    properties (Constant)
        AllowedPhysicalRecordClasses = { ...
            'revgnss.InterSatelliteObservationRecord', ...
            'revgnss.InterSatelliteTimeTransferObservationRecord'};
        AllowedOwnerPolicies = {'disabled','initiator'};
        AllowedRoleReversalPolicies = {'disabled','separateScheduledSession'};
        AllowedRemoteProductPropagationPolicies = {'frozenSameEpochOnly'};
        % remoteProductSchemaMismatch is reserved vocabulary: schema-version mismatches
        % (DistributedLinkProtocolContract:stateComponentOrder /
        % :covarianceComponentOrder) are raised while BUILDING a FrozenProductEndpointProvider
        % (requireDeliveryProvenance runs inside fromEstimatorEligibleProduct), before propose()
        % ever receives the already-constructed provider, so this code has no reachable
        % identifier today. Kept frozen for a future propose()-time schema check.
        AllowedRejectionReasonCodes = { ...
            'endpointIdentityUnreconciled','remoteProductStale','remoteProductNotYetDelivered', ...
            'remoteProductNotEstimatorEligible','remoteProductSchemaMismatch', ...
            'attitudeConventionMismatch','covarianceGroupNotSingleton','calibrationProvenanceMissing', ...
            'calibrationValidityExpired','calibrationOwnerUndeclared','ownerPolicyUnsupported', ...
            'ownerPolicyNotDefinedForRecordType','roleReversalUnsupported','recordUnavailable', ...
            'recordClassNotSanctioned','outOfSequenceDelivery','productAgeNonZero', ...
            'propagationPolicyUnsupported','endpointsNotDistinct','sameEpochScopeViolated', ...
            'ownerProviderSourceAssetMismatch','commonSourceNotRejected', ...
            'correlationPolicyUnsupported','providerClassNotSanctioned', ...
            'observableNotSelectable','recordClassNotSupportedForObservable', ...
            'persistentCalibrationTreatmentUnsupported', ...
            'observableClockClaimUndeclared','clockDatumMismatch', ...
            'clockAnchorUndeclared','unanchoredClockPair','propagationDelayInvalid', ...
            'remoteStateProvenanceUnsupported'};
    end

    properties (SetAccess = immutable)
        deliveryIdentifier (1,:) char
        observationIdentifier (1,:) char
        sessionIdentifier (1,:) char
        physicalObservationRecord (1,1)
        physicalRecordClass (1,:) char
        processedObservableType (1,:) char
        processedUnits (1,:) char
        ownerPolicy (1,:) char
        roleReversalPolicy (1,:) char
        ownerAssetIdentifier (1,:) char
        ownerRecordEndpointIdentifier (1,:) char
        ownerCanonicalIndex (1,1) double
        remoteAssetIdentifier (1,:) char
        remoteRecordEndpointIdentifier (1,:) char
        remoteCanonicalIndex (1,1) double
        ownerProvider (1,1)
        remoteProvider (1,1)
        remoteProductIdentifier (1,:) char
        sourceEpoch_s (1,1) double
        deliveryEpoch_s (1,1) double
        coordinateEventEpoch_s (1,1) double
        remoteProductAge_s (1,1) double
        remoteProductPropagationPolicy (1,:) char
        covarianceGroupIdentifier (1,:) char
        calibrationProductIdentifiers (1,:) cell
        calibrationStateIdentifiers (1,:) cell
        commonSourceTreatment (1,1) struct
        correlationPolicy (1,:) char
        observableIdentifier (1,:) char
        persistentCalibrationTreatment (1,:) char
        clockClaim (1,:) char
        remoteStateProvenance (1,:) char
        pairAbsolutelyAnchored (1,1) logical
        pairAnchorDatumIdentifier (1,:) char
    end

    methods (Access = private)
        function obj = LinkObservationDelivery(record)
            required = {'deliveryIdentifier','observationIdentifier','sessionIdentifier', ...
                'physicalObservationRecord','physicalRecordClass','processedObservableType', ...
                'processedUnits','ownerPolicy','roleReversalPolicy','ownerAssetIdentifier', ...
                'ownerRecordEndpointIdentifier','ownerCanonicalIndex','remoteAssetIdentifier', ...
                'remoteRecordEndpointIdentifier','remoteCanonicalIndex','ownerProvider', ...
                'remoteProvider','remoteProductIdentifier','sourceEpoch_s','deliveryEpoch_s', ...
                'coordinateEventEpoch_s','remoteProductAge_s','remoteProductPropagationPolicy', ...
                'covarianceGroupIdentifier','calibrationProductIdentifiers', ...
                'calibrationStateIdentifiers','commonSourceTreatment','correlationPolicy', ...
                'observableIdentifier','persistentCalibrationTreatment','clockClaim', ...
                'remoteStateProvenance','pairAbsolutelyAnchored','pairAnchorDatumIdentifier'};
            supplied = fieldnames(record);
            missing = setdiff(required,supplied);
            unknown = setdiff(supplied,required);
            if ~isempty(missing)
                error('LinkObservationDelivery:missingField', ...
                    'LinkObservationDelivery is missing %s.',missing{1});
            end
            if ~isempty(unknown)
                error('LinkObservationDelivery:unknownField', ...
                    'LinkObservationDelivery contains unsupported field %s.',unknown{1});
            end
            for index = 1:numel(required)
                obj.(required{index}) = record.(required{index});
            end
        end
    end

    methods (Static)
        function delivery = propose(args)
            if nargin < 1 || ~isstruct(args) || ~isscalar(args)
                error('LinkObservationDelivery:missingField', ...
                    'propose requires a scalar argument struct.');
            end
            requiredArgs = {'physicalObservationRecord','ownerProvider','remoteProvider', ...
                'ownerPolicy','roleReversalPolicy','remoteProductPropagationPolicy', ...
                'stateExchangeSettings','outOfSequencePolicy','commonSourceTreatment', ...
                'correlationPolicy','calibrationRegistry','deliveryEpoch_s','coordinateEventEpoch_s', ...
                'observableIdentifier','persistentCalibrationTreatment'};
            missingArgs = setdiff(requiredArgs,fieldnames(args));
            if ~isempty(missingArgs)
                error('LinkObservationDelivery:missingField', ...
                    'propose is missing argument %s.',missingArgs{1});
            end

            record = args.physicalObservationRecord;
            allowedClasses = revgnss.LinkObservationDelivery.AllowedPhysicalRecordClasses;
            if ~any(strcmp(class(record),allowedClasses))
                error('LinkObservationDelivery:recordClassNotSanctioned', ...
                    'Class %s is not a sanctioned physical link record.',class(record));
            end
            if ~record.available
                error('LinkObservationDelivery:recordUnavailable', ...
                    'The physical link record is not available.');
            end
            revgnss.DistributedLinkUpdateAdapter.requireRecordClassSupportedForObservable( ...
                args.observableIdentifier,class(record));
            treatment = char(args.persistentCalibrationTreatment);
            if ~any(strcmp(treatment, ...
                    revgnss.DistributedLinkUpdateAdapter.AllowedPersistentCalibrationTreatments))
                error('LinkObservationDelivery:persistentCalibrationTreatmentUnsupported', ...
                    'persistentCalibrationTreatment must be a frozen allowed treatment.');
            end
            if ~isa(args.ownerProvider,'revgnss.OwnerLocalEstimatorEndpointProvider')
                error('LinkObservationDelivery:ownerProviderType', ...
                    'ownerProvider must be a revgnss.OwnerLocalEstimatorEndpointProvider.');
            end
            if ~isa(args.remoteProvider,'revgnss.FrozenProductEndpointProvider')
                error('LinkObservationDelivery:remoteProviderType', ...
                    'remoteProvider must be a revgnss.FrozenProductEndpointProvider.');
            end

            ownerPolicy = char(args.ownerPolicy);
            if ~any(strcmp(ownerPolicy,revgnss.LinkObservationDelivery.AllowedOwnerPolicies)) || ...
                    strcmp(ownerPolicy,'disabled')
                error('LinkObservationDelivery:ownerPolicyUnsupported', ...
                    'A delivery cannot be proposed under a disabled or unrecognised ownerPolicy.');
            end
            roleReversalPolicy = char(args.roleReversalPolicy);
            if ~strcmp(roleReversalPolicy,'disabled')
                error('LinkObservationDelivery:roleReversalUnsupported', ...
                    ['Role reversal is allowed only for a later uniquely identified, ' ...
                    'non-overlapping scheduled session, which does not exist.']);
            end

            [ownerField,remoteField] = revgnss.LinkObservationDelivery.ownerEndpointFieldFor_( ...
                class(record),ownerPolicy);
            ownerRecordEndpointIdentifier = record.(ownerField);
            remoteRecordEndpointIdentifier = record.(remoteField);

            revgnss.CanonicalEndpointIdentity.requireReconciled( ...
                args.ownerProvider.endpointIdentifier,ownerRecordEndpointIdentifier);
            revgnss.CanonicalEndpointIdentity.requireReconciled( ...
                args.remoteProvider.endpointIdentifier,remoteRecordEndpointIdentifier);

            ownerCanonicalIndex = args.ownerProvider.canonicalPhysicalAssetIndex;
            remoteCanonicalIndex = args.remoteProvider.canonicalPhysicalAssetIndex;
            if ownerCanonicalIndex == remoteCanonicalIndex
                error('LinkObservationDelivery:endpointsNotDistinct', ...
                    'The owner and remote endpoint must name distinct physical spacecraft.');
            end

            revgnss.DistributedLinkProtocolContract.requireSameEpochScope(args.stateExchangeSettings);
            revgnss.DistributedLinkProtocolContract.requireOutOfSequenceRejected( ...
                args.outOfSequencePolicy);

            remoteProductPropagationPolicy = char(args.remoteProductPropagationPolicy);
            if ~any(strcmp(remoteProductPropagationPolicy, ...
                    revgnss.LinkObservationDelivery.AllowedRemoteProductPropagationPolicies))
                error('LinkObservationDelivery:propagationPolicyUnsupported', ...
                    'remoteProductPropagationPolicy is not supported.');
            end

            deliveryEpoch_s = args.deliveryEpoch_s;
            ownerState = revgnss.CommunicationEndpointStateProvider.requireStateAt( ...
                args.ownerProvider,deliveryEpoch_s);
            remoteState = revgnss.CommunicationEndpointStateProvider.requireStateAt( ...
                args.remoteProvider,deliveryEpoch_s);
            revgnss.CommunicationEndpointStateProvider.requireSameEpochPair( ...
                ownerState,remoteState,deliveryEpoch_s);

            % Plan Section 2.4: adapter-agnostic clock/gauge/time-alignment guards. Live on
            % every delivery today, not only a future time-transfer one -- see
            % revgnss.DistributedClockGaugeContract's class header for why.
            clockClaim = revgnss.DistributedClockGaugeContract.requireObservableClockClaimDeclared( ...
                args.observableIdentifier);
            revgnss.DistributedClockGaugeContract.requireEndpointPairTimeFrameDatumCompatible( ...
                ownerState,remoteState);
            anchorSummary = revgnss.DistributedClockGaugeContract.requireDeclaredClockAnchorPair( ...
                ownerState,remoteState,clockClaim);
            remoteStateProvenance = revgnss.DistributedClockGaugeContract.requireRemoteStateProvenance( ...
                remoteState);

            revgnss.DistributedLinkProtocolContract.requireSingletonCovarianceGroup(record);
            revgnss.DistributedLinkProtocolContract.requireCalibrationProvenance(record);

            revgnss.DistributedLinkProtocolContract.requireCommonSourceTreatmentDeclared( ...
                args.commonSourceTreatment);
            if ~revgnss.DistributedLinkProtocolContract.isFullyRejectedCommonSourceTreatment( ...
                    args.commonSourceTreatment)
                error('LinkObservationDelivery:commonSourceNotRejected', ...
                    'Every common-source treatment must still be ''rejected''.');
            end
            correlationPolicy = char(args.correlationPolicy);
            if ~any(strcmp(correlationPolicy, ...
                    revgnss.DistributedLinkUpdateAdapter.ReachableCorrelationPolicies))
                error('LinkObservationDelivery:correlationPolicyUnsupported', ...
                    'correlationPolicy is not reachable today.');
            end
            if ~strcmp(correlationPolicy,'disabled')
                % Strictly stronger than the old blanket 'disabled'-only check: a non-disabled
                % policy is reachable only for an observable with a demonstrated conservative
                % bound (plan Section 2.2 bullet 4 / Section 2.3.1).
                revgnss.SplitCovarianceIntersectionBound.requireObservableHasDemonstratedBound( ...
                    args.observableIdentifier);
            end

            if strcmp(treatment,'rejected')
                % No registry lookup: G7-family configuration gates are the proof that any
                % persistent calibration error is identically zero, so there is nothing to own.
                % The record's own calibrationProductIdentifiers remain PROVENANCE ONLY (see
                % calibrationProductIdentifiers below) and are never aliased into
                % calibrationStateIdentifiers, which names STATES a registry could own.
                calibrationStateIdentifiers = {};
            else
                calibrationStateIdentifiers = record.calibrationProductIdentifiers;
                if ~isempty(calibrationStateIdentifiers)
                    if isempty(args.calibrationRegistry)
                        error('LinkObservationDelivery:calibrationOwnerUndeclared', ...
                            'A persistent calibration state has no declared owner registry.');
                    end
                    args.calibrationRegistry.requireDeclaredOwnerFor( ...
                        calibrationStateIdentifiers,args.ownerProvider.endpointIdentifier);
                end
            end

            coordinateEventEpoch_s = args.coordinateEventEpoch_s;
            if ~(isnumeric(coordinateEventEpoch_s) && isscalar(coordinateEventEpoch_s) && ...
                    isfinite(coordinateEventEpoch_s) && coordinateEventEpoch_s == deliveryEpoch_s)
                error('LinkObservationDelivery:coordinateEventEpochMismatch', ...
                    ['The initial Stage-2 scope requires coordinateEventEpoch_s to equal ' ...
                    'deliveryEpoch_s; a real final-reception event solve is a Section 2.3 ' ...
                    'adapter responsibility.']);
            end

            out = struct();
            out.deliveryIdentifier = sprintf('delivery:%s:%s', ...
                record.observationIdentifier,ownerRecordEndpointIdentifier);
            out.observationIdentifier = record.observationIdentifier;
            out.sessionIdentifier = record.sessionIdentifier;
            out.physicalObservationRecord = record;
            out.physicalRecordClass = class(record);
            out.processedObservableType = record.processedObservableType;
            out.processedUnits = record.processedUnits;
            out.ownerPolicy = ownerPolicy;
            out.roleReversalPolicy = roleReversalPolicy;
            out.ownerAssetIdentifier = args.ownerProvider.endpointIdentifier;
            out.ownerRecordEndpointIdentifier = ownerRecordEndpointIdentifier;
            out.ownerCanonicalIndex = ownerCanonicalIndex;
            out.remoteAssetIdentifier = args.remoteProvider.endpointIdentifier;
            out.remoteRecordEndpointIdentifier = remoteRecordEndpointIdentifier;
            out.remoteCanonicalIndex = remoteCanonicalIndex;
            out.ownerProvider = args.ownerProvider;
            out.remoteProvider = args.remoteProvider;
            out.remoteProductIdentifier = args.remoteProvider.remoteProductIdentifier;
            out.sourceEpoch_s = deliveryEpoch_s;
            out.deliveryEpoch_s = deliveryEpoch_s;
            out.coordinateEventEpoch_s = coordinateEventEpoch_s;
            out.remoteProductAge_s = remoteState.productProvenance.productAge_s;
            out.remoteProductPropagationPolicy = remoteProductPropagationPolicy;
            out.covarianceGroupIdentifier = record.covarianceGroupIdentifier;
            out.calibrationProductIdentifiers = record.calibrationProductIdentifiers;
            out.calibrationStateIdentifiers = calibrationStateIdentifiers;
            out.commonSourceTreatment = args.commonSourceTreatment;
            out.correlationPolicy = correlationPolicy;
            out.observableIdentifier = char(args.observableIdentifier);
            out.persistentCalibrationTreatment = treatment;
            out.clockClaim = clockClaim;
            out.remoteStateProvenance = remoteStateProvenance;
            out.pairAbsolutelyAnchored = anchorSummary.pairAbsolutelyAnchored;
            out.pairAnchorDatumIdentifier = anchorSummary.pairAnchorDatumIdentifier;

            delivery = revgnss.LinkObservationDelivery(out);
        end

        function [delivery,rejection] = tryPropose(args)
            delivery = [];
            try
                delivery = revgnss.LinkObservationDelivery.propose(args);
                rejection = struct('rejected',false,'reasonCode','','reasonMessage','', ...
                    'sourceErrorIdentifier','');
            catch ME
                code = revgnss.LinkObservationDelivery.reasonCodeForIdentifier(ME.identifier);
                rejection = struct('rejected',true,'reasonCode',code, ...
                    'reasonMessage',ME.message,'sourceErrorIdentifier',ME.identifier);
            end
        end

        function code = reasonCodeForIdentifier(errorIdentifier)
            map = { ...
                'CanonicalEndpointIdentity:unreconciled','endpointIdentityUnreconciled'; ...
                'DistributedLinkProtocolContract:staleProduct','remoteProductStale'; ...
                'DistributedLinkProtocolContract:notYetDelivered','remoteProductNotYetDelivered'; ...
                'DistributedLinkProtocolContract:attitudeConventionMismatch','attitudeConventionMismatch'; ...
                'DistributedLinkProtocolContract:covarianceGroupNotSingleton','covarianceGroupNotSingleton'; ...
                'DistributedLinkProtocolContract:calibrationMissing','calibrationProvenanceMissing'; ...
                'DistributedLinkProtocolContract:calibrationValidityExpired','calibrationValidityExpired'; ...
                'DistributedLinkProtocolContract:maximumAge','sameEpochScopeViolated'; ...
                'DistributedLinkProtocolContract:deliveryDelay','sameEpochScopeViolated'; ...
                'DistributedLinkProtocolContract:outOfSequencePolicy','outOfSequenceDelivery'; ...
                'FrozenProductEndpointProvider:productType','remoteProductNotEstimatorEligible'; ...
                'CommunicationEndpointStateProvider:epochOutsideFrozenScope','productAgeNonZero'; ...
                'OwnerLocalEstimatorEndpointProvider:epochOutsideFrozenScope','productAgeNonZero'; ...
                'FrozenProductEndpointProvider:epochOutsideFrozenScope','productAgeNonZero'; ...
                'OwnerLocalEstimatorEndpointProvider:sourceAsset','ownerProviderSourceAssetMismatch'; ...
                'LinkObservationDelivery:recordClassNotSanctioned','recordClassNotSanctioned'; ...
                'LinkObservationDelivery:recordUnavailable','recordUnavailable'; ...
                'LinkObservationDelivery:ownerProviderType','providerClassNotSanctioned'; ...
                'LinkObservationDelivery:remoteProviderType','providerClassNotSanctioned'; ...
                'LinkObservationDelivery:ownerPolicyUnsupported','ownerPolicyUnsupported'; ...
                'LinkObservationDelivery:ownerPolicyNotDefinedForRecordType', ...
                    'ownerPolicyNotDefinedForRecordType'; ...
                'LinkObservationDelivery:roleReversalUnsupported','roleReversalUnsupported'; ...
                'LinkObservationDelivery:endpointsNotDistinct','endpointsNotDistinct'; ...
                'LinkObservationDelivery:propagationPolicyUnsupported','propagationPolicyUnsupported'; ...
                'LinkObservationDelivery:commonSourceNotRejected','commonSourceNotRejected'; ...
                'LinkObservationDelivery:correlationPolicyUnsupported','correlationPolicyUnsupported'; ...
                'LinkObservationDelivery:calibrationOwnerUndeclared','calibrationOwnerUndeclared'; ...
                'DistributedLinkCalibrationRegistry:policyDisabled','calibrationOwnerUndeclared'; ...
                'DistributedLinkCalibrationRegistry:unknownCalibrationState', ...
                    'calibrationOwnerUndeclared'; ...
                'LinkObservationDelivery:coordinateEventEpochMismatch','sameEpochScopeViolated'; ...
                'DistributedLinkUpdateAdapter:observableNotSelectable','observableNotSelectable'; ...
                'DistributedLinkUpdateAdapter:recordClassNotSupportedForObservable', ...
                    'recordClassNotSupportedForObservable'; ...
                'DistributedLinkUpdateAdapter:adapterNotRegistered', ...
                    'recordClassNotSupportedForObservable'; ...
                'LinkObservationDelivery:persistentCalibrationTreatmentUnsupported', ...
                    'persistentCalibrationTreatmentUnsupported'; ...
                'SplitCovarianceIntersectionBound:observableBoundNotDemonstrated', ...
                    'correlationPolicyUnsupported'; ...
                'DistributedClockGaugeContract:observableClockClaimUndeclared', ...
                    'observableClockClaimUndeclared'; ...
                'DistributedClockGaugeContract:coordinateTimeScaleMismatch','clockDatumMismatch'; ...
                'DistributedClockGaugeContract:frameIdentifierMismatch','clockDatumMismatch'; ...
                'DistributedClockGaugeContract:clockDatumMismatch','clockDatumMismatch'; ...
                'DistributedClockGaugeContract:stateSchemaVersionMismatch', ...
                    'remoteProductSchemaMismatch'; ...
                'DistributedClockGaugeContract:clockAnchorUndeclared','clockAnchorUndeclared'; ...
                'DistributedClockGaugeContract:clockAnchorDatumMismatch','clockDatumMismatch'; ...
                'DistributedClockGaugeContract:unanchoredClockPair','unanchoredClockPair'; ...
                'DistributedClockGaugeContract:propagationDelayInvalid','propagationDelayInvalid'; ...
                'DistributedClockGaugeContract:remoteStateProvenanceUnsupported', ...
                    'remoteStateProvenanceUnsupported'; ...
                'DistributedClockGaugeContract:remoteStateProvenanceUndeclared', ...
                    'remoteStateProvenanceUnsupported'; ...
                'DistributedClockGaugeContract:endpointStateType','providerClassNotSanctioned'};
            row = find(strcmp(map(:,1),errorIdentifier),1);
            if isempty(row)
                error('LinkObservationDelivery:rejectionReasonUnmapped', ...
                    'Error identifier %s has no frozen rejection-reason mapping.',errorIdentifier);
            end
            code = map{row,2};
        end
    end

    methods (Static, Access = private)
        function [ownerField,remoteField] = ownerEndpointFieldFor_(recordClass, ownerPolicy)
            if strcmp(recordClass,'revgnss.InterSatelliteObservationRecord') && ...
                    strcmp(ownerPolicy,'initiator')
                ownerField = 'initiatorAssetIdentifier';
                remoteField = 'transponderAssetIdentifier';
                return
            end
            error('LinkObservationDelivery:ownerPolicyNotDefinedForRecordType', ...
                ['ownerPolicy ''%s'' has no defined owner/remote endpoint role for record ' ...
                'class %s.'],ownerPolicy,recordClass);
        end
    end
end
