classdef ObservableRowDescriptor
    % ObservableRowDescriptor  Metadata for one EKF/diagnostic observable row.

    methods (Static)
        function row = create(rowIndex, observableType, linkId, signalName, ...
                towerIdx, receiverIdx, stateColumns, provenance, role)
            if nargin < 9 || isempty(role); role = 'physicalEKF'; end
            if nargin < 8 || isempty(provenance); provenance = ''; end
            if nargin < 7 || isempty(stateColumns); stateColumns = []; end
            row = struct( ...
                'rowIndex', rowIndex, ...
                'observableType', char(observableType), ...
                'linkId', char(linkId), ...
                'signalName', char(signalName), ...
                'towerIndex', towerIdx, ...
                'receiverIndex', receiverIdx, ...
                'stateColumns', unique(stateColumns(:))', ...
                'provenance', char(provenance), ...
                'role', char(role), ...
                'updatesClock', false, ...
                'attitudeSensitive', false);
        end

        function row = withFlags(row, updatesClock, attitudeSensitive)
            row.updatesClock = logical(updatesClock);
            row.attitudeSensitive = logical(attitudeSensitive);
        end
    end
end
