classdef OneWayInterSatelliteObservationBuilder
    % OneWayInterSatelliteObservationBuilder  Scenario-gated one-way ISL code/range-rate rows
    % (plan Section 2.3 item 3). Truth is read HERE (simulator-side generator, plan Section
    % 2.0.1 explicitly permits this); nothing downstream (the two link-update adapters) ever
    % receives a SpaceAsset/clock/truth handle. Mirrors revgnss.InterSatelliteTimeTransferBuilder's
    % structure. Contains NO broadcast-ephemeris-product mechanism: unlike the legacy
    % revgnss.ISLMeasurementBuilder, there is no piecewise-constant product-error state here at
    % all (plan invariant 8) -- every draw is a single fresh thermal-noise sample.

    methods (Static)
        function validateConfig(cfg)
            enabled = revgnss.OneWayInterSatelliteObservationBuilder.getBool_( ...
                cfg,{'measurements','isl','oneWay','enable'},false);
            if ~enabled; return; end
            if ~revgnss.OneWayInterSatelliteObservationBuilder.getBool_( ...
                    cfg,{'measurements','isl','enable'},false)
                error('OneWayInterSatelliteObservationBuilder:parentDisabled', ...
                    'One-way ISL requires measurements.isl.enable.');
            end
            codeEnabled = revgnss.OneWayInterSatelliteObservationBuilder.getBool_( ...
                cfg,{'measurements','isl','oneWay','code','enable'},false);
            dopplerEnabled = revgnss.OneWayInterSatelliteObservationBuilder.getBool_( ...
                cfg,{'measurements','isl','oneWay','doppler','enable'},false);
            codeSigma_m = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'measurements','isl','oneWay','code','sigma_m'},NaN);
            dopplerSigma_mps = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'measurements','isl','oneWay','doppler','sigma_mps'},NaN);
            if codeEnabled && ~(isfinite(codeSigma_m) && codeSigma_m > 0)
                error('OneWayInterSatelliteObservationBuilder:parameters', ...
                    'One-way code sigma_m must be finite and positive.');
            end
            if dopplerEnabled && ~(isfinite(dopplerSigma_mps) && dopplerSigma_mps > 0)
                error('OneWayInterSatelliteObservationBuilder:parameters', ...
                    'One-way Doppler sigma_mps must be finite and positive.');
            end
            linkBudgetModel = revgnss.OneWayInterSatelliteObservationBuilder.getStr_( ...
                cfg,{'measurements','isl','oneWay','code','linkBudget','model'},'fixed');
            if ~any(strcmp(linkBudgetModel,{'fixed','physicalRF'}))
                error('OneWayInterSatelliteObservationBuilder:linkBudgetModel', ...
                    'code.linkBudget.model must be ''fixed'' or ''physicalRF''.');
            end
            dopplerSigmaSource = revgnss.OneWayInterSatelliteObservationBuilder.getStr_( ...
                cfg,{'measurements','isl','oneWay','doppler','sigmaSource'},'declaredConstant');
            if ~strcmp(dopplerSigmaSource,'declaredConstant')
                error('OneWayInterSatelliteObservationBuilder:dopplerSigmaSource', ...
                    'doppler.sigmaSource must be ''declaredConstant''; no other model is implemented.');
            end
            revgnss.OneWayInterSatelliteObservationBuilder.validateLinks_(cfg);
        end

        function [observations,truthDiagnostics,info] = generateObservations(cfg,assets,t_s)
            observations = {};
            truthDiagnostics = {};
            linkInfos = {};
            info = revgnss.OneWayInterSatelliteObservationBuilder.defaultInfo_(cfg);
            if ~info.enabled
                return
            end
            links = revgnss.OneWayInterSatelliteObservationBuilder.links_(cfg);
            for linkIndex = 1:numel(links)
                link = links(linkIndex);
                if ~revgnss.OneWayInterSatelliteObservationBuilder.scheduled_(cfg,link,t_s)
                    continue
                end
                receiverIndex = link.receiverAssetIndex;
                transmitterIndex = link.transmitterAssetIndex;
                if max(receiverIndex,transmitterIndex) > numel(assets)
                    error('OneWayInterSatelliteObservationBuilder:endpointAsset', ...
                        'A configured one-way endpoint is unavailable.');
                end
                truthReceiver = revgnss.OneWayInterSatelliteObservationBuilder.truthEndpoint_( ...
                    cfg,assets{receiverIndex},'receiver');
                truthTransmitter = revgnss.OneWayInterSatelliteObservationBuilder.truthEndpoint_( ...
                    cfg,assets{transmitterIndex},'transmitter');
                epochIndex = round(t_s/max( ...
                    revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                    cfg,{'simulation','dt_s'},1),eps));

                kinds = {};
                if info.codeEnabled; kinds{end+1} = struct('type','oneWayCodeRange', ...
                        'units','m','covUnits','m^2','sigma',info.codeSigma_m,'kindIndex',1); end
                if info.dopplerEnabled; kinds{end+1} = struct('type','oneWayRangeRate', ...
                        'units','m/s','covUnits','m^2/s^2','sigma',info.dopplerSigma_mps,'kindIndex',2); end

                for kindIndex = 1:numel(kinds)
                    kind = kinds{kindIndex};
                    [truthValue,geometry] = revgnss.OneWayInterSatelliteRangingModel. ...
                        predictProcessedValue(kind.type,truthReceiver,truthTransmitter);
                    noise = kind.sigma*revgnss.OneWayInterSatelliteObservationBuilder.drawNormal_( ...
                        cfg,transmitterIndex,receiverIndex,epochIndex,kind.kindIndex);
                    variance = kind.sigma^2;
                    typeTag = 'oneWayCode';
                    if strcmp(kind.type,'oneWayRangeRate'); typeTag = 'oneWayDoppler'; end
                    observationIdentifier = sprintf('%s:%s:e%09d', ...
                        link.linkIdentifier,typeTag,epochIndex);
                    record = struct( ...
                        'observationIdentifier',observationIdentifier, ...
                        'sessionIdentifier',sprintf('%s:%s:session:e%09d', ...
                            link.linkIdentifier,typeTag,epochIndex), ...
                        'linkIdentifier',link.linkIdentifier, ...
                        'transmitterAssetIdentifier',sprintf('asset:%d',transmitterIndex), ...
                        'receiverAssetIdentifier',sprintf('asset:%d',receiverIndex), ...
                        'transmitTerminalIdentifier',sprintf( ...
                            'asset:%d:isl-one-way-terminal',transmitterIndex), ...
                        'receiveTerminalIdentifier',sprintf( ...
                            'asset:%d:isl-one-way-terminal',receiverIndex), ...
                        'transmitAntennaIdentifier','antenna:notDeclared', ...
                        'receiveAntennaIdentifier','antenna:notDeclared', ...
                        'protocolIdentifier','oneWayBroadcastPnRanging', ...
                        'signalIdentifier',link.signalIdentifier, ...
                        'channelIdentifier',link.channelIdentifier, ...
                        'sessionInitiatorRole','receiver', ...
                        'carrierFrequency_Hz',info.carrierFrequency_Hz, ...
                        'codeChipRate_Hz',info.codeChipRate_Hz, ...
                        'referenceLocalClockTag_s',t_s, ...
                        'referenceEpoch_s',t_s, ...
                        'referenceEpochRule','commonCoordinateEpoch', ...
                        'processedObservableType',kind.type, ...
                        'processedValue',truthValue+noise, ...
                        'processedUnits',kind.units, ...
                        'covarianceGroupIdentifier',observationIdentifier, ...
                        'covarianceRowIndex',1, ...
                        'covarianceBlock',variance, ...
                        'covarianceUnits',kind.covUnits, ...
                        'calibrationProductIdentifiers',{{link.calibrationProductIdentifier}}, ...
                        'calibrationValidFromLocalTag_s',info.calibrationValidFrom_s, ...
                        'calibrationValidUntilLocalTag_s',info.calibrationValidUntil_s, ...
                        'transmitPhaseCentreOffset_body_m',info.transmitLever_m, ...
                        'receivePhaseCentreOffset_body_m',info.receiveLever_m, ...
                        'geometryKernelIdentifier', ...
                            revgnss.OneWayInterSatelliteRangingModel.GeometryKernelIdentifier, ...
                        'lightTimeCorrectionApplied',false, ...
                        'leverArmRateTermApplied',false, ...
                        'broadcastEphemerisProductApplied',false, ...
                        'available',true, ...
                        'qualityFlags',struct('scheduled',true), ...
                        'truthDiagnosticIdentifier',[observationIdentifier '-truth']);
                    observation = revgnss.OneWayInterSatelliteObservationRecord(record);
                    diagnostic = struct( ...
                        'diagnosticIdentifier',[observationIdentifier '-truth'], ...
                        'processedObservableType',kind.type, ...
                        'receiverAssetIndex',receiverIndex, ...
                        'transmitterAssetIndex',transmitterIndex, ...
                        'truthValue',truthValue, ...
                        'range_m',geometry.range_m, ...
                        'rangeRate_mps',geometry.rangeRate_mps, ...
                        'thermalError',noise);
                    linkInfo = struct('linkDefinitionIndex',linkIndex, ...
                        'receiverAssetIndex',receiverIndex,'transmitterAssetIndex',transmitterIndex, ...
                        'linkIdentifier',link.linkIdentifier,'observableType',kind.type, ...
                        'observationRecord',observation,'truthDiagnostic',diagnostic);
                    observations{end+1} = observation; %#ok<AGROW>
                    truthDiagnostics{end+1} = diagnostic; %#ok<AGROW>
                    linkInfos{end+1} = linkInfo; %#ok<AGROW>
                end
            end
            info.linkInfos = linkInfos;
            info.observationRecords = observations;
        end

        function links = linkDefinitions(cfg)
            links = revgnss.OneWayInterSatelliteObservationBuilder.links_(cfg);
        end

        function geometry = terminalGeometryForRole(cfg,role)
            info = revgnss.OneWayInterSatelliteObservationBuilder.defaultInfo_(cfg);
            if strcmp(role,'owner') || strcmp(role,'receiver')
                lever = info.receiveLever_m;
            else
                lever = info.transmitLever_m;
            end
            geometry = struct('leverArm_body_m',lever);
        end
    end

    methods (Static, Access = private)
        function info = defaultInfo_(cfg)
            info = struct( ...
                'enabled',revgnss.OneWayInterSatelliteObservationBuilder.getBool_( ...
                    cfg,{'measurements','isl','oneWay','enable'},false), ...
                'codeEnabled',revgnss.OneWayInterSatelliteObservationBuilder.getBool_( ...
                    cfg,{'measurements','isl','oneWay','code','enable'},false), ...
                'dopplerEnabled',revgnss.OneWayInterSatelliteObservationBuilder.getBool_( ...
                    cfg,{'measurements','isl','oneWay','doppler','enable'},false), ...
                'codeSigma_m',revgnss.OneWayInterSatelliteObservationBuilder.codeSigma_(cfg), ...
                'dopplerSigma_mps',revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                    cfg,{'measurements','isl','oneWay','doppler','sigma_mps'},0.02), ...
                'carrierFrequency_Hz',revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                    cfg,{'measurements','isl','oneWay','carrierFrequency_Hz'},26e9), ...
                'codeChipRate_Hz',revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                    cfg,{'measurements','isl','oneWay','codeChipRate_Hz'},10.23e6), ...
                'calibrationValidFrom_s',revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                    cfg,{'measurements','isl','oneWay','calibration','validFromLocalTag_s'},-1e12), ...
                'calibrationValidUntil_s',revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                    cfg,{'measurements','isl','oneWay','calibration','validUntilLocalTag_s'},1e12), ...
                'transmitLever_m',revgnss.OneWayInterSatelliteObservationBuilder.walk_( ...
                    cfg,{'measurements','isl','oneWay','terminalGeometry', ...
                    'transmitPhaseCentreOffset_body_m'},zeros(3,1)), ...
                'receiveLever_m',revgnss.OneWayInterSatelliteObservationBuilder.walk_( ...
                    cfg,{'measurements','isl','oneWay','terminalGeometry', ...
                    'receivePhaseCentreOffset_body_m'},zeros(3,1)), ...
                'linkInfos',{{}}, ...
                'observationRecords',{{}});
        end

        function sigma = codeSigma_(cfg)
            model = revgnss.OneWayInterSatelliteObservationBuilder.getStr_( ...
                cfg,{'measurements','isl','oneWay','code','linkBudget','model'},'fixed');
            if ~strcmp(model,'physicalRF')
                sigma = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                    cfg,{'measurements','isl','oneWay','code','sigma_m'},0.30);
                return
            end
            leg = revgnss.OneWayInterSatelliteObservationBuilder.walk_( ...
                cfg,{'measurements','isl','oneWay','code','linkBudget','leg'},[]);
            distance_m = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'measurements','isl','oneWay','code','linkBudget','distance_m'},NaN);
            if ~isstruct(leg) || ~isfinite(distance_m)
                error('OneWayInterSatelliteObservationBuilder:linkBudgetLeg', ...
                    ['code.linkBudget.model=''physicalRF'' requires a fully declared leg struct ' ...
                    'and code.linkBudget.distance_m.']);
            end
            leg.distance_m = distance_m;
            out = revgnss.InterSatelliteRFLinkModel.evaluateOneWayLeg(leg);
            sigma = out.oneWayCodeRangeSigma_m;
        end

        function links = links_(cfg)
            declared = revgnss.OneWayInterSatelliteObservationBuilder.walk_( ...
                cfg,{'measurements','isl','oneWay','links'},struct([]));
            if isempty(declared) || ~isstruct(declared)
                receiverIndex = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                    cfg,{'measurements','isl','receiverAssetIndex'},1);
                transmitterIndex = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                    cfg,{'measurements','isl','transmitterAssetIndex'},2);
                links = struct( ...
                    'linkIdentifier',sprintf('isl-one-way-link-A%d-A%d', ...
                        transmitterIndex,receiverIndex), ...
                    'transmitterAssetIndex',transmitterIndex, ...
                    'receiverAssetIndex',receiverIndex, ...
                    'calibrationProductIdentifier',revgnss.OneWayInterSatelliteObservationBuilder.getStr_( ...
                        cfg,{'measurements','isl','oneWay','calibration','productIdentifier'}, ...
                        'isl-one-way-calibration'), ...
                    'signalIdentifier',revgnss.OneWayInterSatelliteObservationBuilder.getStr_( ...
                        cfg,{'measurements','isl','oneWay','signalIdentifier'},'ISL-PN'), ...
                    'channelIdentifier',revgnss.OneWayInterSatelliteObservationBuilder.getStr_( ...
                        cfg,{'measurements','isl','oneWay','channelIdentifier'},'PN-1'), ...
                    'schedule',struct( ...
                        'updatePhase_s',revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                        cfg,{'measurements','isl','oneWay','schedule','updatePhase_s'},0)));
            else
                links = declared;
                for linkIndex = 1:numel(links)
                    if ~isfield(links,'calibrationProductIdentifier') || ...
                            isempty(links(linkIndex).calibrationProductIdentifier)
                        links(linkIndex).calibrationProductIdentifier = sprintf( ...
                            '%s:calibration',char(links(linkIndex).linkIdentifier));
                    else
                        links(linkIndex).calibrationProductIdentifier = ...
                            char(links(linkIndex).calibrationProductIdentifier);
                    end
                    if ~isfield(links,'schedule') || isempty(links(linkIndex).schedule)
                        links(linkIndex).schedule = struct('updatePhase_s',0);
                    end
                end
            end
        end

        function validateLinks_(cfg)
            links = revgnss.OneWayInterSatelliteObservationBuilder.links_(cfg);
            nAssets = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'scenario','nSpaceAssets'},1);
            period_s = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'measurements','isl','oneWay','schedule','updatePeriod_s'},NaN);
            start_s = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'measurements','isl','oneWay','schedule','start_s'},0);
            stop_s = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'measurements','isl','oneWay','schedule','stop_s'},NaN);
            if ~(isfinite(period_s) && period_s > 0 && isfinite(start_s) && ...
                    isfinite(stop_s) && stop_s >= start_s)
                error('OneWayInterSatelliteObservationBuilder:schedule', ...
                    'The one-way schedule must have a positive period and valid bounds.');
            end
            identifiers = cell(1,numel(links));
            receiverIndices = zeros(1,numel(links));
            for linkIndex = 1:numel(links)
                endpoints = [links(linkIndex).transmitterAssetIndex, ...
                    links(linkIndex).receiverAssetIndex];
                if any(endpoints ~= round(endpoints)) || any(endpoints < 1) || ...
                        any(endpoints > nAssets) || endpoints(1) == endpoints(2)
                    error('OneWayInterSatelliteObservationBuilder:endpoints', ...
                        'Each one-way link requires two distinct configured spacecraft.');
                end
                identifiers{linkIndex} = char(links(linkIndex).linkIdentifier);
                receiverIndices(linkIndex) = links(linkIndex).receiverAssetIndex;
                phase_s = links(linkIndex).schedule.updatePhase_s;
                if ~(isscalar(phase_s) && isfinite(phase_s) && phase_s >= 0 && phase_s < period_s)
                    error('OneWayInterSatelliteObservationBuilder:schedulePhase', ...
                        'Each one-way link phase must be inside one update period.');
                end
            end
            if numel(unique(identifiers)) ~= numel(identifiers)
                error('OneWayInterSatelliteObservationBuilder:linkIdentity', ...
                    'One-way link identifiers must be unique.');
            end
            if numel(unique(receiverIndices)) ~= numel(receiverIndices)
                error('OneWayInterSatelliteObservationBuilder:coFiringLinksPerOwner', ...
                    'No two enabled one-way links may share the same receiverAssetIndex.');
            end
        end

        function scheduled = scheduled_(cfg,link,t_s)
            warmup_s = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'measurements','isl','oneWay','warmup_s'},0);
            start_s = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'measurements','isl','oneWay','schedule','start_s'},0);
            stop_s = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'measurements','isl','oneWay','schedule','stop_s'},1e12);
            if t_s < max(warmup_s,start_s) || t_s > stop_s
                scheduled = false;
                return
            end
            period_s = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'measurements','isl','oneWay','schedule','updatePeriod_s'},1);
            phase_s = link.schedule.updatePhase_s;
            dt_s = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'simulation','dt_s'},1);
            remainder = mod(t_s-phase_s,period_s);
            scheduled = min(remainder,period_s-remainder) <= 10*eps(max(1,period_s))+dt_s*1e-10;
        end

        function state = truthEndpoint_(cfg,asset,role)
            geometry = revgnss.OneWayInterSatelliteObservationBuilder.terminalGeometryForRole( ...
                cfg,role);
            rotation = revgnss.AttitudeKinematics.bodyToEcefRotation(asset.attitude_euler_rad);
            state = struct( ...
                'position_m',asset.r_ecef_m(:), ...
                'velocity_mps',asset.v_ecef_mps(:), ...
                'bodyToEcefRotation',rotation, ...
                'clockBias_m',asset.clock.getBiasMeters(), ...
                'clockDriftRate_mps',asset.clock.getDriftMetersPerSecond(), ...
                'phaseCentreOffset_body_m',geometry.leverArm_body_m);
        end

        function value = drawNormal_(cfg,transmitterIndex,receiverIndex,epochIndex,kindIndex)
            seed = revgnss.OneWayInterSatelliteObservationBuilder.getNum_( ...
                cfg,{'simulation','seed'},42);
            stream = RandStream('mt19937ar','Seed',mod( ...
                seed+1900007+4001*transmitterIndex+7919*receiverIndex+ ...
                104729*epochIndex+31*kindIndex,2^31-1));
            value = randn(stream,1,1);
        end

        function tf = getBool_(cfg,path,defaultValue)
            value = revgnss.OneWayInterSatelliteObservationBuilder.walk_(cfg,path,defaultValue);
            tf = islogical(value) && isscalar(value) && value;
        end

        function value = getNum_(cfg,path,defaultValue)
            value = revgnss.OneWayInterSatelliteObservationBuilder.walk_(cfg,path,defaultValue);
            if ~isnumeric(value) || ~isscalar(value)
                value = defaultValue;
            end
        end

        function value = getStr_(cfg,path,defaultValue)
            value = revgnss.OneWayInterSatelliteObservationBuilder.walk_(cfg,path,defaultValue);
            if ~(ischar(value) || (isstring(value) && isscalar(value)))
                value = defaultValue;
            end
            value = char(value);
        end

        function value = walk_(cfg,path,defaultValue)
            value = cfg;
            for pathIndex = 1:numel(path)
                if isstruct(value) && isfield(value,path{pathIndex})
                    value = value.(path{pathIndex});
                else
                    value = defaultValue;
                    return
                end
            end
        end
    end
end
