classdef OneWayInterSatelliteRangingModel
    % OneWayInterSatelliteRangingModel  Shared processed one-way code-range/range-rate model
    % (plan Section 2.3 item 3). Pure, static, truth-free: no cfg, no truth, no I/O, no handle.
    % Sits between the truth-reading revgnss.OneWayInterSatelliteObservationBuilder and the
    % truth-free revgnss.OneWayCodeRangeLinkUpdateAdapter / OneWayDopplerRangeRateLinkUpdateAdapter
    % so that no physics equation lives in an adapter file and truth and model share one kernel
    % by construction (mirrors revgnss.ReciprocalTimeTransferModel's role for Section 2.3.2).
    %
    % EXACTLY FRAME-INVARIANT (no ECEF->ECI bridge needed, and for a different reason than
    % Section 2.3.2's "the partials are zero"): rho=||Delta|| is exactly invariant under any
    % rotation about a common origin, and rangeRate=u'*Deltav is exactly invariant too, because
    % u_eci is parallel to Delta_eci so the Sagnac transport term u_eci'*(omega x Delta_eci) is
    % exactly zero. revgnss.CommunicationEndpointState's own ECEF positionEcef_m/velocityEcef_mps
    % are used directly.

    properties (Constant)
        SupportedProcessedObservableTypes = {'oneWayCodeRange','oneWayRangeRate'};
        GeometryKernelIdentifier = 'instantaneousCoordinateEpochGeometry';
        LightTimeCorrectionSupported = false;
        LeverArmRateTermSupported = false;
        MinimumSeparation_m = 1;
    end

    methods (Static)
        function [value, geometry] = predictProcessedValue(processedObservableType, ...
                receiverEndpoint, transmitterEndpoint)
            allowed = revgnss.OneWayInterSatelliteRangingModel.SupportedProcessedObservableTypes;
            if ~(ischar(processedObservableType) || ...
                    (isstring(processedObservableType) && isscalar(processedObservableType))) || ...
                    ~any(strcmp(char(processedObservableType),allowed))
                error('OneWayInterSatelliteRangingModel:processedObservableType', ...
                    'processedObservableType must be ''oneWayCodeRange'' or ''oneWayRangeRate''.');
            end
            revgnss.OneWayInterSatelliteRangingModel.validateEndpoint_(receiverEndpoint,'receiver');
            revgnss.OneWayInterSatelliteRangingModel.validateEndpoint_(transmitterEndpoint,'transmitter');

            pr = receiverEndpoint.position_m(:) + ...
                receiverEndpoint.bodyToEcefRotation*receiverEndpoint.phaseCentreOffset_body_m(:);
            pt = transmitterEndpoint.position_m(:) + ...
                transmitterEndpoint.bodyToEcefRotation*transmitterEndpoint.phaseCentreOffset_body_m(:);
            delta = pr-pt;
            range_m = norm(delta);
            if range_m < revgnss.OneWayInterSatelliteRangingModel.MinimumSeparation_m
                error('OneWayInterSatelliteRangingModel:endpointSeparation', ...
                    'One-way link endpoints must be separated by at least %g m.', ...
                    revgnss.OneWayInterSatelliteRangingModel.MinimumSeparation_m);
            end
            lineOfSight = delta/range_m;
            deltaVelocity = receiverEndpoint.velocity_mps(:)-transmitterEndpoint.velocity_mps(:);
            rangeRate_mps = lineOfSight'*deltaVelocity;

            geometry = struct( ...
                'range_m',range_m, ...
                'rangeRate_mps',rangeRate_mps, ...
                'lineOfSightUnit',lineOfSight, ...
                'relativeVelocity_mps',deltaVelocity, ...
                'receiverPhaseCentre_m',pr, ...
                'transmitterPhaseCentre_m',pt, ...
                'receiverRotation',receiverEndpoint.bodyToEcefRotation, ...
                'transmitterRotation',transmitterEndpoint.bodyToEcefRotation);

            if strcmp(char(processedObservableType),'oneWayCodeRange')
                value = range_m+receiverEndpoint.clockBias_m-transmitterEndpoint.clockBias_m;
            else
                value = rangeRate_mps+receiverEndpoint.clockDriftRate_mps- ...
                    transmitterEndpoint.clockDriftRate_mps;
            end
        end

        function partials = geometryPartials(geometry)
            % geometryPartials  RECEIVER-side position/velocity partials of range and range
            % rate, evaluated from an already-computed geometry struct. The transmitter-side
            % partials are the exact negatives (the kernel is a function of delta=pr-pt and
            % deltaVelocity=vr-vt only); the caller negates rather than recomputing.
            u = geometry.lineOfSightUnit;
            rho = geometry.range_m;
            deltaVelocity = geometry.relativeVelocity_mps;
            M = (eye(3)-u*u')/rho;
            partials = struct( ...
                'dRange_dReceiverPosition',u', ...
                'dRangeRate_dReceiverPosition',deltaVelocity'*M, ...
                'dRangeRate_dReceiverVelocity',u', ...
                'lineOfSightUnit',u, ...
                'invRange_perM',1/rho, ...
                'rangeRate_mps',geometry.rangeRate_mps);
        end

        function endpoint = endpointFromCommunicationState(endpointState, role)
            if ~isa(endpointState,'revgnss.CommunicationEndpointState')
                error('OneWayInterSatelliteRangingModel:endpointStateType', ...
                    'endpointFromCommunicationState requires a revgnss.CommunicationEndpointState.');
            end
            if ~(ischar(role) && any(strcmp(role,{'receiver','transmitter'})))
                error('OneWayInterSatelliteRangingModel:role', ...
                    'role must be ''receiver'' or ''transmitter''.');
            end
            terminal = endpointState.terminalGeometry;
            if strcmp(role,'receiver')
                leverArm = terminal.receivePhaseCentreOffset_body_m;
            else
                leverArm = terminal.transmitPhaseCentreOffset_body_m;
            end
            rotation = revgnss.AttitudeKinematics.bodyToEcefRotation( ...
                endpointState.attitudeEulerZyx_rad);
            endpoint = struct( ...
                'position_m',endpointState.positionEcef_m, ...
                'velocity_mps',endpointState.velocityEcef_mps, ...
                'bodyToEcefRotation',rotation, ...
                'clockBias_m',endpointState.clockBias_m, ...
                'clockDriftRate_mps',endpointState.clockDriftRate_mps, ...
                'phaseCentreOffset_body_m',leverArm);
        end
    end

    methods (Static, Access = private)
        function validateEndpoint_(state,label)
            if ~isstruct(state)
                error('OneWayInterSatelliteRangingModel:endpointType', ...
                    '%s endpoint must be a struct.',label);
            end
            required = {'position_m','velocity_mps','bodyToEcefRotation','clockBias_m', ...
                'clockDriftRate_mps','phaseCentreOffset_body_m'};
            for fieldIndex = 1:numel(required)
                if ~isfield(state,required{fieldIndex})
                    error('OneWayInterSatelliteRangingModel:endpointField', ...
                        '%s endpoint is missing %s.',label,required{fieldIndex});
                end
            end
            if ~isnumeric(state.position_m) || numel(state.position_m) ~= 3 || ...
                    any(~isfinite(state.position_m(:))) || ...
                    ~isnumeric(state.velocity_mps) || numel(state.velocity_mps) ~= 3 || ...
                    any(~isfinite(state.velocity_mps(:))) || ...
                    ~isnumeric(state.bodyToEcefRotation) || ...
                    ~isequal(size(state.bodyToEcefRotation),[3 3]) || ...
                    any(~isfinite(state.bodyToEcefRotation(:))) || ...
                    ~(isnumeric(state.clockBias_m) && isscalar(state.clockBias_m) && ...
                    isfinite(state.clockBias_m)) || ...
                    ~(isnumeric(state.clockDriftRate_mps) && isscalar(state.clockDriftRate_mps) && ...
                    isfinite(state.clockDriftRate_mps)) || ...
                    ~isnumeric(state.phaseCentreOffset_body_m) || ...
                    numel(state.phaseCentreOffset_body_m) ~= 3 || ...
                    any(~isfinite(state.phaseCentreOffset_body_m(:)))
                error('OneWayInterSatelliteRangingModel:endpointValue', ...
                    '%s endpoint contains invalid values.',label);
            end
        end
    end
end
