classdef ReciprocalTimeTransferModel
    % ReciprocalTimeTransferModel  Shared processed clock-difference model.

    properties (Constant)
        SpeedOfLight_mps = 299792458
        FirstOrderMode = 'firstOrderReciprocal'
        PhysicalTimestampMode = 'fourTimestampPhysical'
    end

    methods (Static)
        function result = evaluate(referenceState,remoteState,mode,includeReciprocity)
            if nargin < 3 || isempty(mode)
                mode = revgnss.ReciprocalTimeTransferModel.FirstOrderMode;
            end
            if nargin < 4 || isempty(includeReciprocity)
                includeReciprocity = false;
            end
            revgnss.ReciprocalTimeTransferModel.validateMode(mode);
            revgnss.ReciprocalTimeTransferModel.validateState_( ...
                referenceState,'reference');
            revgnss.ReciprocalTimeTransferModel.validateState_( ...
                remoteState,'remote');
            if ~(islogical(includeReciprocity) && isscalar(includeReciprocity))
                error('ReciprocalTimeTransferModel:reciprocityFlag', ...
                    'includeReciprocity must be a logical scalar.');
            end

            deltaPosition = remoteState.position_m(:) - ...
                referenceState.position_m(:);
            deltaVelocity = remoteState.velocity_mps(:) - ...
                referenceState.velocity_mps(:);
            range_m = norm(deltaPosition);
            if range_m < 1
                error('ReciprocalTimeTransferModel:endpointSeparation', ...
                    'Time-transfer endpoints must be separated by at least one metre.');
            end
            lineOfSight = deltaPosition/range_m;
            rangeRate_mps = lineOfSight.'*deltaVelocity;
            reciprocity_m = 0;
            referencePositionPartial = zeros(1,3);
            remotePositionPartial = zeros(1,3);
            referenceVelocityPartial = zeros(1,3);
            remoteVelocityPartial = zeros(1,3);
            if includeReciprocity
                reciprocity_m = -(deltaPosition.'*deltaVelocity)/ ...
                    revgnss.ReciprocalTimeTransferModel.SpeedOfLight_mps;
                referencePositionPartial = deltaVelocity.'/ ...
                    revgnss.ReciprocalTimeTransferModel.SpeedOfLight_mps;
                remotePositionPartial = -referencePositionPartial;
                referenceVelocityPartial = deltaPosition.'/ ...
                    revgnss.ReciprocalTimeTransferModel.SpeedOfLight_mps;
                remoteVelocityPartial = -referenceVelocityPartial;
            end

            clockDifference_m = remoteState.clockBias_m - ...
                referenceState.clockBias_m;
            result = struct( ...
                'mode',char(mode), ...
                'value_m',clockDifference_m+reciprocity_m, ...
                'clockDifference_m',clockDifference_m, ...
                'reciprocity_m',reciprocity_m, ...
                'range_m',range_m, ...
                'rangeRate_mps',rangeRate_mps, ...
                'referenceClockPartial',-1, ...
                'remoteClockPartial',1, ...
                'referencePositionPartial',referencePositionPartial, ...
                'remotePositionPartial',remotePositionPartial, ...
                'referenceVelocityPartial',referenceVelocityPartial, ...
                'remoteVelocityPartial',remoteVelocityPartial);
        end

        function validateMode(mode)
            if ~(ischar(mode) || (isstring(mode) && isscalar(mode)))
                error('ReciprocalTimeTransferModel:mode', ...
                    'Time-transfer mode must be text.');
            end
            mode = char(mode);
            if strcmp(mode,revgnss.ReciprocalTimeTransferModel.FirstOrderMode)
                return
            end
            if strcmp(mode, ...
                    revgnss.ReciprocalTimeTransferModel.PhysicalTimestampMode)
                error('ReciprocalTimeTransferModel:fourTimestampUnavailable', ...
                    ['fourTimestampPhysical is reserved for the future raw-tag ' ...
                     'implementation and is not currently available.']);
            end
            error('ReciprocalTimeTransferModel:mode', ...
                ['Time-transfer mode must be firstOrderReciprocal or ' ...
                 'fourTimestampPhysical.']);
        end
    end

    methods (Static, Access = private)
        function validateState_(state,label)
            if ~isstruct(state)
                error('ReciprocalTimeTransferModel:stateType', ...
                    '%s endpoint state must be a struct.',label);
            end
            required = {'position_m','velocity_mps','clockBias_m'};
            for fieldIndex = 1:numel(required)
                fieldName = required{fieldIndex};
                if ~isfield(state,fieldName)
                    error('ReciprocalTimeTransferModel:stateField', ...
                        '%s endpoint state is missing %s.',label,fieldName);
                end
            end
            if ~isnumeric(state.position_m) || numel(state.position_m) ~= 3 || ...
                    any(~isfinite(state.position_m(:))) || ...
                    ~isnumeric(state.velocity_mps) || ...
                    numel(state.velocity_mps) ~= 3 || ...
                    any(~isfinite(state.velocity_mps(:))) || ...
                    ~(isnumeric(state.clockBias_m) && ...
                    isscalar(state.clockBias_m) && ...
                    isfinite(state.clockBias_m))
                error('ReciprocalTimeTransferModel:stateValue', ...
                    '%s endpoint state contains invalid values.',label);
            end
        end
    end
end
