classdef ReportEquations
    % ReportEquations  Canonical measurement-equation strings for report pages.
    %
    % All methods return cell arrays of char lines.  Used by LatexReportBuilder
    % to build equation pages and by tests to verify equation content.
    methods (Static)

        function lines = codeEquation()
            % codeEquation  Single-frequency code pseudorange model.
            lines = { ...
                'Code pseudorange (single frequency):', ...
                '  P_f = rho + b_rx - b_twr + T + I_f + d_code + eps_P', ...
                '  b_rx  > 0  (receiver clock bias, positive sign)', ...
                '  b_twr     (tower clock bias, subtracted in equation)', ...
                '  T    >= 0  (troposphere delay, positive for code and carrier)', ...
                '  I_f  >= 0  (ionosphere delay, POSITIVE for code)', ...
            };
        end

        function lines = carrierEquation()
            % carrierEquation  Carrier phase pseudorange model (metres).
            lines = { ...
                'Carrier phase (metres):', ...
                '  Phi_f = rho + b_rx - b_twr + T - I_f + B_phi + d_phase + eps_phi', ...
                '          Ionosphere is NEGATIVE for carrier (phase advance).', ...
                '  B_phi = float ambiguity [m]  — no integer fixing in this simulator', ...
                '  L1 carrier only in ekfFloat mode (no L2 carrier EKF rows)', ...
            };
        end

        function lines = ifEquation()
            % ifEquation  Ionosphere-free code combination.
            f1 = 1575.42e6;  f2 = 1227.60e6;
            a  =  f1^2 / (f1^2 - f2^2);
            b  = -f2^2 / (f1^2 - f2^2);
            lines = { ...
                'Ionosphere-free code combination:', ...
                '  P_IF = alpha * P_L1 + beta * P_L2', ...
                sprintf('  alpha = f_L1^2 / (f_L1^2 - f_L2^2) = %.6f', a), ...
                sprintf('  beta  = -f_L2^2/ (f_L1^2 - f_L2^2) = %.6f', b), ...
                '  First-order ionosphere removed; geometry and clocks preserved.', ...
                '  Noise amplified: sigma_IF ~ 2.98 * sigma_L1', ...
            };
        end

        function lines = zwdContribution()
            % zwdContribution  ZWD state H column for perTowerZwd mode.
            lines = { ...
                'ZWD state contribution (perTowerZwd mode):', ...
                '  h_zwd = m_w(el) * ZWD     [m_w = wet mapping function]', ...
                '  H_zwd = m_w(el)            [Jacobian column for ZWD state]', ...
            };
        end

    end
end
