classdef SimulationToggleManifest
    % SimulationToggleManifest  Simulation-impacting toggle manifest from cfg.
    %
    % Usage:
    %   manifest = revgnss.SimulationToggleManifest.fromConfig(cfg);          % cfg only
    %   manifest = revgnss.SimulationToggleManifest.fromConfig(cfg, out);     % cfg + runtime out
    %   T        = revgnss.SimulationToggleManifest.toTable(manifest);
    %   revgnss.SimulationToggleManifest.writeCsv(T, '/path/manifest.csv');
    %   compact  = revgnss.SimulationToggleManifest.compact(manifest);
    %
    % Status values:
    %   active               - implemented and active in this cfg
    %   inactive_available   - implemented but off in this cfg
    %   guarded_or_config_only - present but guarded, unsupported, or irrelevant to active scenario
    %   diagnostic_only      - does not change physics/EKF; changes diagnostics/reporting only

    methods (Static)

        % ----------------------------------------------------------------
        function manifest = fromConfig(cfg, varargin)
            % fromConfig  Build manifest struct array from finalized cfg.
            %   manifest = fromConfig(cfg)       — cfg-based classification only
            %   manifest = fromConfig(cfg, out)  — out.summary used for runtime status
            % The 'out' struct (optional) is currently unused beyond validation; the
            % manifest is fully determined by cfg at this time.
            G  = @(p) revgnss.SimulationToggleManifest.getf_(cfg, p);
            FV = @(v) revgnss.SimulationToggleManifest.fmtVal_(v);
            MK = @(cat,path,val,st,si,aff,cond,notes) ...
                 revgnss.SimulationToggleManifest.mkRow_(cat, path, FV(val), st, si, aff, cond, notes);
            A  = 'active';
            IA = 'inactive_available';
            GC = 'guarded_or_config_only';
            DO = 'diagnostic_only';
            rows = {};

            %% --- Signals -----------------------------------------------
            mask  = G('signals.enabledMask');
            if isempty(mask); mask = true; end
            isDual = numel(mask) >= 2 && mask(1) && mask(2);
            names_ = G('signals.names');
            freqs_ = G('signals.frequencyHz');
            ebfC_  = G('measurements.code.enabledByFrequency');
            ebfCar_= G('measurements.carrier.enabledByFrequency');

            if isDual; stMask = A; else; stMask = IA; end
            rows{end+1} = MK('Signals','cfg.signals.enabledMask', mask, stMask, true, ...
                'measurementRows,measurementValue,R,stateDimension', 'always', ...
                'L1 only: single-freq code/carrier/Doppler; L1+L2: enables IF rows and baseline attitude AR');

            if isempty(names_); names_ = {'L1'}; end
            rows{end+1} = MK('Signals','cfg.signals.names', names_, A, true, ...
                'measurementRows', 'derived by finalizeConfig', ...
                'Signal catalogue; ordering must match enabledMask and frequencyHz');

            if ~isempty(freqs_)
                rows{end+1} = MK('Signals','cfg.signals.frequencyHz', freqs_, A, true, ...
                    'measurementValue,R', 'derived by finalizeConfig', ...
                    'Carrier frequency determines wavelength and IF combination coefficients');
            end

            wl_ = G('signals.wavelength_m');
            if isempty(wl_)
                try
                    c_ = 299792458;
                    if ~isempty(freqs_) && isnumeric(freqs_)
                        wl_ = c_ ./ freqs_;
                    end
                catch; end
            end
            if ~isempty(wl_)
                rows{end+1} = MK('Signals','cfg.signals.wavelength_m (derived)', wl_, A, true, ...
                    'measurementValue', 'derived from frequencyHz', ...
                    'Wavelength controls carrier phase conversion cycles→metres');
            end

            if isDual; stDual = A; else; stDual = IA; end
            rows{end+1} = MK('Signals','derived: dualFrequency mode', isDual, stDual, true, ...
                'measurementRows,R,stateDimension', 'enabledMask=[true,true]', ...
                'Dual-freq enables IF combination rows; single-freq blocks them');

            if ~isempty(ebfC_)
                rows{end+1} = MK('Signals','cfg.measurements.code.enabledByFrequency', ebfC_, A, true, ...
                    'measurementRows', 'derived by finalizeConfig from enabledMask', ...
                    'Per-frequency code row inclusion; must match enabledMask');
            end
            if ~isempty(ebfCar_)
                rows{end+1} = MK('Signals','cfg.measurements.carrier.enabledByFrequency', ebfCar_, ...
                    ternst_(isDual && logical(G('measurements.carrierPhase.enable')), A, IA), true, ...
                    'measurementRows', 'derived by finalizeConfig from enabledMask', ...
                    'Per-frequency carrier row inclusion; single-freq excludes L2 carrier rows');
            end

            %% --- Scenario / topology -----------------------------------
            nSA_ = G('scenario.nSpaceAssets'); if isempty(nSA_); nSA_=1; end
            nRx_ = G('scenario.nReceivers');   if isempty(nRx_); nRx_=1; end
            nTw_ = G('scenario.nTowers');       if isempty(nTw_); nTw_=5; end
            orc_ = G('scenario.orbitClass');    if isempty(orc_); orc_='GEO'; end
            islEn_    = logical_G_(G('measurements.isl.enable'));
            twstftEn_ = logical_G_(G('measurements.twstft.enable'));
            twoWayEn_ = logical_G_(G('measurements.isl.twoWay.enable'));

            rows{end+1} = MK('Scenario','cfg.scenario.nSpaceAssets', nSA_, A, true, ...
                'stateDimension,measurementRows', 'always', ...
                'Exactly 1 supported; nSpaceAssets>1 guarded and errors in ConfigFactory');
            rows{end+1} = MK('Scenario','cfg.scenario.nReceivers', nRx_, A, true, ...
                'stateDimension,attitude', 'always', ...
                'nReceivers=1: no attitude; nReceivers>1: enables lever-arm attitude EKF');
            rows{end+1} = MK('Scenario','cfg.scenario.nTowers', nTw_, A, true, ...
                'measurementRows', 'always', ...
                'Number of active ground towers; finalizeConfig trims tower array');
            rows{end+1} = MK('Scenario','cfg.scenario.orbitClass', orc_, A, false, ...
                'truth', 'always (documentary)', ...
                'Orbit class label; dynamics controlled by orbit.truth.mode');

            stMA = GC;
            rows{end+1} = MK('Scenario','derived: multi-asset estimation', nSA_>1, stMA, false, ...
                'stateDimension', 'nSpaceAssets>1', ...
                'Multi-asset estimation explicitly guarded in v1; nSpaceAssets>1 errors');

            rows{end+1} = MK('Scenario','cfg.measurements.isl.enable', islEn_, GC, false, ...
                'measurementRows', 'isl.enable=true', ...
                'ISL one-way: guarded/irrelevant for single-asset one-way scenario');
            rows{end+1} = MK('Scenario','cfg.measurements.twstft.enable', twstftEn_, GC, false, ...
                'measurementRows', 'twstft.enable=true', ...
                'TWSTFT: guarded/irrelevant for single-asset one-way scenario');
            rows{end+1} = MK('Scenario','cfg.measurements.isl.twoWay.enable', twoWayEn_, GC, false, ...
                'measurementRows', 'isl.twoWay.enable=true', ...
                'Two-way ISL: guarded/irrelevant for single-asset one-way scenario');

            %% --- Code measurements -------------------------------------
            prEn_ = logical_G_(G('measurements.pseudorange.enable')); if isempty(prEn_); prEn_=true; end
            cnMdl_= G('measurements.codeNoise.model'); if isempty(cnMdl_); cnMdl_='constant'; end
            cnSig_= G('errors.codeNoise.sigma_m');
            cIF_en_  = logical_G_(G('measurements.code.ionosphereFreeRows.enable'));
            cIF_ekf_ = logical_G_(G('measurements.code.ionosphereFreeRows.useInEkf'));

            if prEn_; stPR=A; else; stPR=IA; end
            rows{end+1} = MK('Code','cfg.measurements.pseudorange.enable', prEn_, stPR, true, ...
                'measurementRows', 'always', 'Primary observable; disabling removes all code rows');
            rows{end+1} = MK('Code','cfg.measurements.codeNoise.model', cnMdl_, A, true, ...
                'measurementValue,R', 'pseudorange enabled', ...
                'constant: fixed sigma; CN0-dependent also available but not used in default run');
            if ~isempty(cnSig_)
                if cnSig_>0; stSig=A; else; stSig=IA; end
                rows{end+1} = MK('Code','cfg.errors.codeNoise.sigma_m', cnSig_, stSig, true, ...
                    'measurementValue,R', 'pseudorange enabled', ...
                    'Code measurement noise sigma; zero means deterministic pseudoranges');
            end
            if cIF_en_ && cIF_ekf_; stCIF=A; elseif cIF_en_; stCIF=IA; else; stCIF=IA; end
            rows{end+1} = MK('Code','cfg.measurements.code.ionosphereFreeRows.enable', cIF_en_, stCIF, true, ...
                'measurementRows,R', 'enabledMask=[true,true]', ...
                'Enables L1/L2 IF code combination (replaces separate rows when useInEkf=true)');
            rows{end+1} = MK('Code','cfg.measurements.code.ionosphereFreeRows.useInEkf', cIF_ekf_, stCIF, true, ...
                'measurementRows', 'code.ionosphereFreeRows.enable=true', ...
                'Feeds IF rows into EKF; requires enable=true and dual-frequency');

            if cIF_en_ && cIF_ekf_; stDCB=A; else; stDCB=IA; end
            rows{end+1} = MK('Code','derived: code IF active in EKF', cIF_en_&&cIF_ekf_, stDCB, true, ...
                'measurementRows,R', 'enable=true AND useInEkf=true AND dual-freq', ...
                'IF active: noise amplified (factor ~3); DCB modelled as zero in v1 — known limitation L1');
            rows{end+1} = MK('Code','derived: DCB limitation', 'zero (v1)', GC, false, ...
                'measurementValue', 'code IF active', ...
                'Differential code biases set to zero; not calibrated; see known limitation L1');

            %% --- Carrier measurements ----------------------------------
            carEn_   = logical_G_(G('measurements.carrierPhase.enable'));
            carMode_ = G('measurements.carrierMode'); if isempty(carMode_); carMode_='off'; end
            ambMode_ = G('estimation.ambiguityMode'); if isempty(ambMode_); ambMode_='off'; end
            estAmb_  = logical_G_(G('estimator.estimateCarrierAmbiguities'));
            cArIF_en_ = logical_G_(G('measurements.carrier.ionosphereFreeRows.enable'));
            cArIF_ekf_= logical_G_(G('measurements.carrier.ionosphereFreeRows.useInEkf'));
            isFloat_ = strcmp(carMode_,'ekfFloat');

            if carEn_; stCar=A; else; stCar=IA; end
            rows{end+1} = MK('Carrier','cfg.measurements.carrierPhase.enable', carEn_, stCar, true, ...
                'measurementRows,stateDimension', 'always', ...
                'Enables carrier phase observables; adds ambiguity states per tower×receiver×signal');
            rows{end+1} = MK('Carrier','cfg.measurements.carrierMode', carMode_, ...
                ternst_(isFloat_, A, IA), true, ...
                'measurementRows,stateDimension', 'carrierPhase.enable=true', ...
                'ekfFloat: float ambiguities in EKF; off/diagnostic: carrier not in EKF');
            rows{end+1} = MK('Carrier','cfg.estimation.ambiguityMode', ambMode_, ...
                ternst_(isFloat_, A, IA), true, ...
                'stateDimension', 'carrierMode=ekfFloat', ...
                'floatPerTowerReceiverSignal: one float state per tower×rx×signal pair');
            if ~isempty(estAmb_)
                rows{end+1} = MK('Carrier','cfg.estimator.estimateCarrierAmbiguities', estAmb_, ...
                    ternst_(estAmb_, A, IA), true, 'stateDimension', 'carrierMode=ekfFloat', ...
                    'Derived flag; true when float carrier ambiguity states are in EKF');
            end

            if cArIF_en_&&cArIF_ekf_; stCarIF=A; elseif cArIF_en_; stCarIF=IA; else; stCarIF=IA; end
            rows{end+1} = MK('Carrier','cfg.measurements.carrier.ionosphereFreeRows.enable', cArIF_en_, stCarIF, true, ...
                'measurementRows,stateDimension', 'dual-freq AND carrierMode=ekfFloat', ...
                'Carrier IF float rows; B_IF=alpha*B_L1+beta*B_L2 (non-integer); requires L1+L2 and ekfFloat');
            rows{end+1} = MK('Carrier','cfg.measurements.carrier.ionosphereFreeRows.useInEkf', cArIF_ekf_, stCarIF, true, ...
                'measurementRows', 'carrier.ionosphereFreeRows.enable=true', ...
                'Feeds carrier IF float rows into EKF; replaces separate L1/L2 carrier rows');
            rows{end+1} = MK('Carrier','derived: carrier IF float rows active', cArIF_en_&&cArIF_ekf_, ...
                ternst_(cArIF_en_&&cArIF_ekf_, A, IA), true, 'measurementRows,R', ...
                'enable=true AND useInEkf=true AND dual-freq AND ekfFloat', ...
                'Float-only; IF combination float ambiguity not an integer; no fixing in v1');
            rows{end+1} = MK('Carrier','derived: carrier IF integer fixing', false, GC, false, ...
                'stateDimension', 'not implemented', ...
                'Carrier-IF integer fixing explicitly unsupported in v1; B_IF is non-integer by construction');
            rows{end+1} = MK('Carrier','derived: LAMBDA/MLAMBDA', false, GC, false, ...
                'stateDimension', 'not implemented', ...
                'LAMBDA/MLAMBDA not implemented; no ILS search or false-fix-risk control');

            if isDual && carEn_; stL2C=A; else; stL2C=IA; end
            rows{end+1} = MK('Carrier','derived: L1 carrier rows in EKF', carEn_&&isFloat_, ...
                ternst_(carEn_&&isFloat_, A, IA), true, 'measurementRows', ...
                'carrierPhase.enable=true AND carrierMode=ekfFloat', ...
                'L1 carrier float ambiguity rows; primary signal for DiffAtt');
            rows{end+1} = MK('Carrier','derived: L2 carrier rows in EKF', isDual&&carEn_&&isFloat_, stL2C, true, ...
                'measurementRows,stateDimension', 'dual-freq AND ekfFloat', ...
                'L2 rows separate from L1; joint L1+L2 baseline AR uses both');

            %% --- Doppler -----------------------------------------------
            dopEn_    = logical_G_(G('measurements.doppler.enable'));
            dopEkf_   = logical_G_(G('measurements.doppler.useInEKF'));
            dopTruth_ = logical_G_(G('physics.doppler.truth.enable'));
            dopMdl_   = logical_G_(G('physics.doppler.model.enable'));
            dopLevel_ = G('measurements.doppler.modelLevel'); if isempty(dopLevel_); dopLevel_='ecefOnlyV1'; end
            dopRot_   = logical_G_(G('measurements.doppler.includeTowerRotationalVelocity'));
            dopDrift_ = logical_G_(G('measurements.doppler.includeTowerClockProductDrift'));
            dopSag_   = logical_G_(G('measurements.doppler.includeSagnacRate'));
            dopLT_    = logical_G_(G('measurements.doppler.includeLightTimeRate'));
            dopJac_   = G('measurements.doppler.jacobianMode'); if isempty(dopJac_); dopJac_='ecefOnlyV1'; end
            dopActive_= dopEn_ && dopEkf_ && dopMdl_;

            if dopEn_; stD=A; else; stD=IA; end
            rows{end+1} = MK('Doppler','cfg.measurements.doppler.enable', dopEn_, stD, true, ...
                'measurementRows', 'always', 'Enables range-rate observable rows');
            rows{end+1} = MK('Doppler','cfg.measurements.doppler.useInEKF', dopEkf_, ...
                ternst_(dopEkf_&&dopEn_, A, IA), true, 'measurementRows', ...
                'doppler.enable=true', 'Feeds Doppler into EKF update; requires physics.doppler.model.enable');
            rows{end+1} = MK('Doppler','cfg.physics.doppler.truth.enable', dopTruth_, ...
                ternst_(dopTruth_, A, IA), true, 'measurementValue', ...
                'doppler.enable=true', 'Computes Doppler truth with full range-rate model');
            rows{end+1} = MK('Doppler','cfg.physics.doppler.model.enable', dopMdl_, ...
                ternst_(dopMdl_, A, IA), true, 'measurementValue', ...
                'doppler.useInEKF=true', 'EKF Doppler model; disabling auto-disables useInEKF in finalizeConfig');
            rows{end+1} = MK('Doppler','cfg.measurements.doppler.modelLevel', dopLevel_, ...
                ternst_(dopActive_, A, IA), true, 'measurementValue', ...
                'doppler active', 'frameConsistentV2: includes tower rotation and product drift');
            rows{end+1} = MK('Doppler','cfg.measurements.doppler.includeTowerRotationalVelocity', dopRot_, ...
                ternst_(dopRot_&&dopActive_, A, IA), true, 'measurementValue', ...
                'modelLevel=frameConsistentV2', ...
                'Tower ECEF velocity from Earth rotation; ~465 m/s at equator projected onto LOS');
            rows{end+1} = MK('Doppler','cfg.measurements.doppler.includeTowerClockProductDrift', dopDrift_, ...
                ternst_(dopDrift_&&dopActive_, A, IA), true, 'measurementValue,R', ...
                'truthHistoryProductNoisy mode', ...
                'Product clock drift enters both Doppler observation and R covariance');
            rows{end+1} = MK('Doppler','cfg.measurements.doppler.includeSagnacRate', dopSag_, ...
                ternst_(dopSag_&&dopActive_, A, IA), true, 'measurementValue', ...
                'explicitly set', ...
                'Sagnac rate term; captured by tower velocity when includeTowerRotationalVelocity=true');
            rows{end+1} = MK('Doppler','cfg.measurements.doppler.includeLightTimeRate', dopLT_, ...
                ternst_(dopLT_&&dopActive_, A, IA), true, 'measurementValue', ...
                'explicitly set', ...
                'Light-time rate: metadata-only in v1 (simplifiedV1); known limitation L2');
            rows{end+1} = MK('Doppler','cfg.measurements.doppler.jacobianMode', dopJac_, ...
                ternst_(dopActive_, A, IA), true, 'EKF', ...
                'doppler active', 'analyticRangeRateV1: analytic LOS range-rate Jacobian');
            rows{end+1} = MK('Doppler','derived: Doppler IF combination', false, GC, false, ...
                'measurementRows', 'not implemented', ...
                'Doppler ionosphere-rate term not modelled; Doppler IF combination not implemented (limitation L2)');

            %% --- Clock -------------------------------------------------
            rxDet_  = logical_G_(G('clock.receiver.deterministic'));
            if isempty(rxDet_); rxDet_ = logical_G_(G('asset.clock.deterministic')); end
            if isempty(rxDet_); rxDet_ = true; end
            estTwr_ = logical_G_(G('estimator.estimateTowerClocks'));
            prodMode_ = G('clocks.tower.product.mode'); if isempty(prodMode_); prodMode_='perfectCorrection'; end
            isProd_ = strcmp(prodMode_,'truthHistoryProductNoisy');
            addToR_ = logical_G_(G('clocks.tower.product.addToR'));
            sharedCorr_ = logical_G_(G('clocks.tower.product.sharedErrorCorrelation'));

            rows{end+1} = MK('Clock','cfg.clock.receiver.deterministic', rxDet_, ...
                ternst_(~rxDet_, A, IA), true, 'measurementValue,EKF', ...
                'always', 'false: stochastic rx clock (bias+drift Gauss-Markov); EKF estimates bias+drift states');
            rows{end+1} = MK('Clock','cfg.asset.clock.deterministic', ...
                G('asset.clock.deterministic'), ternst_(~rxDet_, A, IA), true, ...
                'measurementValue', 'asset.clock.deterministic=false', ...
                'Redundant path; canonical control is cfg.clock.receiver.deterministic');
            rows{end+1} = MK('Clock','derived: receiver clock bias estimated', ~rxDet_, ...
                ternst_(~rxDet_, A, IA), true, 'stateDimension,EKF', ...
                'clock.receiver.deterministic=false', ...
                'Stochastic receiver clock drives EKF clock bias+drift states (2 states)');
            rows{end+1} = MK('Clock','cfg.estimator.estimateTowerClocks', estTwr_, ...
                ternst_(estTwr_, A, GC), true, 'stateDimension', ...
                'estimateTowerClocks=true', ...
                'false: tower clocks corrected by product (not estimated); avoids clock-gauge ambiguity');
            rows{end+1} = MK('Clock','cfg.clocks.tower.product.mode', prodMode_, ...
                ternst_(isProd_, A, IA), true, 'measurementValue,R', ...
                'always', ...
                'truthHistoryProductNoisy: synthetic product with latency, bias, drift noise');
            if isProd_
                rows{end+1} = MK('Clock','cfg.clocks.tower.product.updateInterval_s', ...
                    G('clocks.tower.product.updateInterval_s'), A, true, 'measurementValue,R', ...
                    'truthHistoryProductNoisy mode', 'Product epoch spacing; step at boundary triggers slip-detection risk');
                rows{end+1} = MK('Clock','cfg.clocks.tower.product.latency_s', ...
                    G('clocks.tower.product.latency_s'), A, true, 'measurementValue', ...
                    'truthHistoryProductNoisy mode', 'Broadcast delay; increases product age and prediction error');
                rows{end+1} = MK('Clock','cfg.clocks.tower.product.sigmaBias_m', ...
                    G('clocks.tower.product.sigmaBias_m'), A, true, 'measurementValue,R', ...
                    'truthHistoryProductNoisy mode', ...
                    '0.01 m ~ 0.033 ns (IGS-class); reduced from 0.05 m at Stage 72 to prevent false carrier slips');
                rows{end+1} = MK('Clock','cfg.clocks.tower.product.sigmaDrift_mps', ...
                    G('clocks.tower.product.sigmaDrift_mps'), A, true, 'measurementValue,R', ...
                    'truthHistoryProductNoisy mode', 'Drift noise sigma; grows prediction error with product age');
                rows{end+1} = MK('Clock','cfg.clocks.tower.product.covBiasDrift', ...
                    G('clocks.tower.product.covBiasDrift'), A, true, 'R', ...
                    'truthHistoryProductNoisy mode', 'Bias-drift cross-covariance; zero in default (uncorrelated)');
                rows{end+1} = MK('Clock','cfg.clocks.tower.product.validity_s', ...
                    G('clocks.tower.product.validity_s'), A, true, 'measurementValue', ...
                    'truthHistoryProductNoisy mode', 'Product staleness guard; exceeding halts correction');
                rows{end+1} = MK('Clock','cfg.clocks.tower.product.addToR', addToR_, ...
                    ternst_(addToR_&&isProd_, A, IA), true, 'R', ...
                    'truthHistoryProductNoisy mode', 'Inflates code R with product prediction uncertainty (diagonal)');
                rows{end+1} = MK('Clock','cfg.clocks.tower.product.sharedErrorCorrelation', sharedCorr_, ...
                    ternst_(sharedCorr_&&isProd_, A, IA), true, 'R', ...
                    'truthHistoryProductNoisy mode', ...
                    'Same product error shared across code rows from same tower; generates off-diagonal R terms');
            else
                rows{end+1} = MK('Clock','cfg.clocks.tower.product.* (all params)', 'N/A (mode not active)', ...
                    IA, false, 'R', 'clocks.tower.product.mode=truthHistoryProductNoisy', ...
                    'Product parameters inactive; perfectCorrection mode uses true clock values');
            end
            % Tower clock deterministic check
            nDet_ = 0;
            if isfield(cfg,'towers')
                for kk = 1:numel(cfg.towers)
                    if isfield(cfg.towers(kk),'clock') && isfield(cfg.towers(kk).clock,'deterministic')
                        if cfg.towers(kk).clock.deterministic; nDet_ = nDet_+1; end
                    end
                end
            end
            if nDet_ < numel_safe_(cfg,'towers'); stTwrClk=A; else; stTwrClk=IA; end
            rows{end+1} = MK('Clock','derived: tower clock stochastic count', ...
                sprintf('%d/%d towers stochastic', numel_safe_(cfg,'towers')-nDet_, numel_safe_(cfg,'towers')), ...
                stTwrClk, true, 'measurementValue', 'towers(k).clock.deterministic=false', ...
                'Stochastic tower clocks add noise to pseudorange truth; must be corrected by product');

            %% --- Covariance --------------------------------------------
            shEn_  = logical_G_(G('covariance.sharedErrors.enable'));
            shMd_  = G('covariance.sharedErrors.mode'); if isempty(shMd_); shMd_='none'; end
            shCode_= logical_G_(G('covariance.sharedErrors.applyTowerClockToCode'));
            shCar_ = logical_G_(G('covariance.sharedErrors.applyTowerClockToCarrier'));
            shDop_ = logical_G_(G('covariance.sharedErrors.applyTowerClockToDoppler'));
            shCarP_= G('covariance.sharedErrors.carrierPolicy');
            shDopP_= G('covariance.sharedErrors.dopplerPolicy');
            shSPD_ = logical_G_(G('covariance.sharedErrors.ensureSPD'));
            pcEn_  = logical_G_(G('covariance.productClock.enable'));
            pcCode_= logical_G_(G('covariance.productClock.applyToCode'));
            pcDop_ = logical_G_(G('covariance.productClock.applyToDoppler'));
            pcCar_ = logical_G_(G('covariance.productClock.applyToCarrier'));
            pcCross_= logical_G_(G('covariance.productClock.crossCodeDoppler'));
            pcCarP_= G('covariance.productClock.carrierPolicy');
            pcDopP_= G('covariance.productClock.dopplerPolicy');

            rows{end+1} = MK('Covariance','cfg.covariance.sharedErrors.enable', shEn_, ...
                ternst_(shEn_, A, IA), true, 'R', 'sharedErrors.enable=true', ...
                'Block-tower-clock off-diagonal R terms for code rows sharing same tower product');
            rows{end+1} = MK('Covariance','cfg.covariance.sharedErrors.mode', shMd_, ...
                ternst_(shEn_, A, IA), true, 'R', 'sharedErrors.enable=true', ...
                'blockTowerClockProduct: R_ij+=sigma_twr^2 for same-tower pairs; keeps R symmetric PD');
            rows{end+1} = MK('Covariance','cfg.covariance.sharedErrors.applyTowerClockToCode', shCode_, ...
                ternst_(shCode_&&shEn_, A, IA), true, 'R', 'sharedErrors.enable=true', ...
                'Adds shared product bias block to code R; primary off-diagonal inflation');
            rows{end+1} = MK('Covariance','cfg.covariance.sharedErrors.applyTowerClockToCarrier', shCar_, ...
                ternst_(shCar_&&shEn_, A, IA), true, 'R', 'sharedErrors.enable=true', ...
                'false: float ambiguity absorbs constant arc bias (see carrierPolicy)');
            rows{end+1} = MK('Covariance','cfg.covariance.sharedErrors.applyTowerClockToDoppler', shDop_, ...
                ternst_(shDop_&&shEn_, A, IA), true, 'R', 'sharedErrors.enable=true', ...
                'false: Doppler drift covariance owned by productClock.dopplerPolicy');
            rows{end+1} = MK('Covariance','cfg.covariance.sharedErrors.carrierPolicy', ...
                shCarP_, ternst_(~isempty(shCarP_)&&shEn_, A, IA), true, 'R', ...
                'sharedErrors.applyTowerClockToCarrier=false', ...
                'arcBiasAbsorbsConstantProductBias: float arc ambiguity absorbs bias; drift residual in productClock');
            rows{end+1} = MK('Covariance','cfg.covariance.sharedErrors.dopplerPolicy', ...
                shDopP_, ternst_(~isempty(shDopP_)&&shEn_, A, IA), true, 'R', ...
                'sharedErrors.enable=true', ...
                'frameConsistentV2: tower rotation + product drift covariance blocks for Doppler R');
            rows{end+1} = MK('Covariance','cfg.covariance.sharedErrors.ensureSPD', shSPD_, ...
                ternst_(shEn_, A, IA), true, 'R', 'sharedErrors.enable=true', ...
                'Applies jitter to ensure R remains symmetric positive-definite after block inflation');
            rows{end+1} = MK('Covariance','cfg.covariance.productClock.enable', pcEn_, ...
                ternst_(pcEn_&&isProd_, A, IA), true, 'R', ...
                'truthHistoryProductNoisy mode', ...
                'Adds age-weighted product prediction uncertainty to code/carrier/Doppler R');
            rows{end+1} = MK('Covariance','cfg.covariance.productClock.applyToCode', pcCode_, ...
                ternst_(pcEn_&&pcCode_, A, IA), true, 'R', 'productClock.enable=true', ...
                'Adds sigma_bias^2 + t_age^2*sigma_drift^2 to code R diagonal (and block via sharedErrors)');
            rows{end+1} = MK('Covariance','cfg.covariance.productClock.applyToDoppler', pcDop_, ...
                ternst_(pcEn_&&pcDop_, A, IA), true, 'R', 'productClock.enable=true', ...
                'Adds sigma_drift^2 block to Doppler R; drift covariance owned by addDopplerDriftBlock');
            rows{end+1} = MK('Covariance','cfg.covariance.productClock.applyToCarrier', pcCar_, ...
                ternst_(pcEn_&&pcCar_, A, IA), true, 'R', 'productClock.enable=true', ...
                'Adds time-varying drift residual to carrier R (arc-start reference); bias absorbed by float ambiguity');
            rows{end+1} = MK('Covariance','cfg.covariance.productClock.crossCodeDoppler', pcCross_, ...
                ternst_(pcCross_&&pcEn_, A, IA), true, 'R', 'productClock.enable=true', ...
                'false: code-Doppler cross-covariance not implemented (limitation L3); R remains block-diagonal');
            rows{end+1} = MK('Covariance','cfg.covariance.productClock.carrierPolicy', ...
                pcCarP_, ternst_(pcEn_&&pcCar_, A, IA), true, 'R', ...
                'productClock.applyToCarrier=true', ...
                'timeVaryingProductResidualOnly: per-arc drift residual; bias absorbed by float ambiguity state');
            rows{end+1} = MK('Covariance','cfg.covariance.productClock.dopplerPolicy', ...
                pcDopP_, ternst_(pcEn_&&pcDop_, A, IA), true, 'R', ...
                'productClock.applyToDoppler=true', ...
                'sharedClockDriftProductBlock: off-diagonal drift variance block across same-tower Doppler rows');

            %% --- Orbit / Dynamics --------------------------------------
            orbProp_ = logical_G_(G('orbit.useOrbitPropagator'));
            orbTruth_= G('orbit.truth.mode'); if isempty(orbTruth_); orbTruth_='stationaryEcef'; end
            orbMode_ = G('orbit.mode');      if isempty(orbMode_);  orbMode_='stationaryEcef'; end
            dynMode_ = G('estimator.dynamics.mode'); if isempty(dynMode_); dynMode_='constantVelocity'; end
            fdPos_   = G('estimator.dynamics.fdPositionStep_m');
            fdVel_   = G('estimator.dynamics.fdVelocityStep_mps');
            pnMM_    = logical_G_(G('estimator.processNoise.modelMismatch.enable'));
            isJ2Truth_= contains(lower(orbTruth_),'j2');
            isTwBody_ = strcmp(dynMode_,'twoBody') || strcmp(dynMode_,'twoBodyRk4');
            isMismatch_= isJ2Truth_ && isTwBody_;

            rows{end+1} = MK('OrbitDynamics','cfg.orbit.useOrbitPropagator', orbProp_, ...
                ternst_(orbProp_, A, IA), true, 'truth', 'always', ...
                'false: stationary ECEF; true: propagates GEO orbit from Keplerian elements');
            rows{end+1} = MK('OrbitDynamics','cfg.orbit.truth.mode', orbTruth_, ...
                ternst_(~strcmp(orbTruth_,'stationaryEcef'), A, IA), true, 'truth', ...
                'orbit.useOrbitPropagator=true', ...
                'j2Rk4: J2-perturbed truth; twoBodyRk4: two-body truth; stationaryEcef: static');
            rows{end+1} = MK('OrbitDynamics','cfg.orbit.mode', orbMode_, ...
                ternst_(~strcmp(orbMode_,'stationaryEcef'), A, IA), false, 'truth', ...
                'derived from orbit.truth.mode', 'Legacy alias; canonical is orbit.truth.mode');
            rows{end+1} = MK('OrbitDynamics','cfg.estimator.dynamics.mode', dynMode_, ...
                ternst_(~strcmp(dynMode_,'constantVelocity'), A, IA), true, ...
                'Q,F', 'always', ...
                'constantVelocity: zero Q diagonal; twoBody: inertial orbit prediction with FD STM');
            if ~isempty(fdPos_)
                rows{end+1} = MK('OrbitDynamics','cfg.estimator.dynamics.fdPositionStep_m', fdPos_, ...
                    ternst_(isTwBody_, A, IA), true, 'F', ...
                    'dynamics.mode=twoBody', 'Finite-difference step for position partial of STM');
            end
            if ~isempty(fdVel_)
                rows{end+1} = MK('OrbitDynamics','cfg.estimator.dynamics.fdVelocityStep_mps', fdVel_, ...
                    ternst_(isTwBody_, A, IA), true, 'F', ...
                    'dynamics.mode=twoBody', 'Finite-difference step for velocity partial of STM');
            end
            rows{end+1} = MK('OrbitDynamics','cfg.estimator.processNoise.modelMismatch.enable', pnMM_, ...
                ternst_(pnMM_, A, IA), true, 'Q', ...
                'dynamics.mode=twoBody AND orbit.truth.mode=j2Rk4', ...
                'Adds sigma_mismatch to process noise Q to account for unmodelled J2 perturbation');
            rows{end+1} = MK('OrbitDynamics','derived: J2 truth active', isJ2Truth_, ...
                ternst_(isJ2Truth_, A, IA), true, 'truth', ...
                'orbit.truth.mode contains j2', ...
                'j2Rk4: J2 perturbation ~8.3e-6 m/s^2 (radial) at GEO equatorial; two-body EKF mismatch');
            rows{end+1} = MK('OrbitDynamics','derived: truth/EKF dynamics mismatch', isMismatch_, ...
                ternst_(isMismatch_, A, IA), true, 'Q,truth', ...
                'j2Rk4 truth AND twoBody EKF', ...
                'J2 truth vs two-body EKF; process noise sigma_accel=0.01 >> 0.1*J2 compensates');
            rows{end+1} = MK('OrbitDynamics','derived: process-noise mismatch augmentation', pnMM_, ...
                ternst_(pnMM_, A, IA), true, 'Q', ...
                'processNoise.modelMismatch.enable=true', ...
                'Explicit J2 acceleration sigma added to Q when mismatch detected');

            %% --- Relativity / Range corrections -----------------------
            sagTr_  = logical_G_(G('physics.sagnac.truth.enable'));
            sagMd_  = logical_G_(G('physics.sagnac.model.enable'));
            ltEn_   = logical_G_(G('physics.lightTime.enable'));
            ltMode_ = G('physics.lightTime.mode'); if isempty(ltMode_); ltMode_='sagnacFirstOrder'; end
            ltIter_ = G('physics.lightTime.iterations');
            ltTol_  = G('physics.lightTime.tolerance_s');
            ltTr_   = logical_G_(G('physics.lightTime.truth.enable'));
            ltMd_   = logical_G_(G('physics.lightTime.model.enable'));
            shTr_   = logical_G_(G('physics.relativity.shapiro.truth.enable'));
            shMd_   = logical_G_(G('physics.relativity.shapiro.model.enable'));
            rlkTr_  = logical_G_(G('physics.relativity.clock.truth.enable'));
            rlkMd_  = logical_G_(G('physics.relativity.clock.model.enable'));
            isIterLT_= strcmp(ltMode_,'iterativeOneWay');

            rows{end+1} = MK('Relativity','cfg.physics.sagnac.truth.enable', sagTr_, ...
                ternst_(sagTr_&&~isIterLT_, A, ternst_(isIterLT_&&sagTr_, GC, IA)), true, ...
                'measurementValue', 'always', ...
                'Sagnac first-order correction in truth; disabled when iterativeOneWay to prevent double-count');
            rows{end+1} = MK('Relativity','cfg.physics.sagnac.model.enable', sagMd_, ...
                ternst_(sagMd_&&~isIterLT_, A, ternst_(isIterLT_&&sagMd_, GC, IA)), true, ...
                'measurementValue', 'sagnac.model.enable=true', ...
                'Sagnac in EKF model; iterativeOneWay mode subsumes Sagnac — enabling both double-counts');
            rows{end+1} = MK('Relativity','cfg.physics.lightTime.enable', ltEn_, ...
                ternst_(ltEn_, A, IA), true, 'measurementValue', 'always', ...
                'Enables light-time correction; false: instantaneous range (biased by ~0.12 m at GEO)');
            rows{end+1} = MK('Relativity','cfg.physics.lightTime.mode', ltMode_, ...
                ternst_(ltEn_, A, IA), true, 'measurementValue', ...
                'lightTime.enable=true', ...
                'iterativeOneWay: full iterative signal-path solve; sagnacFirstOrder: first-order only');
            if ~isempty(ltIter_)
                rows{end+1} = MK('Relativity','cfg.physics.lightTime.iterations', ltIter_, ...
                    ternst_(isIterLT_, A, IA), true, 'measurementValue', ...
                    'lightTime.mode=iterativeOneWay', ...
                    '2 iterations typically sufficient for GEO one-way (~0.12 s light time)');
            end
            if ~isempty(ltTol_)
                rows{end+1} = MK('Relativity','cfg.physics.lightTime.tolerance_s', ltTol_, ...
                    ternst_(isIterLT_, A, IA), false, 'measurementValue', ...
                    'lightTime.mode=iterativeOneWay', 'Convergence tolerance in seconds');
            end
            rows{end+1} = MK('Relativity','cfg.physics.lightTime.truth.enable', ltTr_, ...
                ternst_(ltEn_&&ltTr_, A, IA), true, 'measurementValue', ...
                'lightTime.enable=true', 'Applies light-time correction to truth range computation');
            rows{end+1} = MK('Relativity','cfg.physics.lightTime.model.enable', ltMd_, ...
                ternst_(ltEn_&&ltMd_, A, IA), true, 'measurementValue', ...
                'lightTime.enable=true', 'Applies light-time correction in EKF model');
            rows{end+1} = MK('Relativity','cfg.physics.relativity.shapiro.truth.enable', shTr_, ...
                ternst_(shTr_, A, IA), true, 'measurementValue', 'always', ...
                'Shapiro delay ~3 mm at GEO zenith; included in truth pseudorange');
            rows{end+1} = MK('Relativity','cfg.physics.relativity.shapiro.model.enable', shMd_, ...
                ternst_(shMd_, A, IA), true, 'measurementValue', 'always', ...
                'Shapiro delay in EKF model; matched truth/model → zero residual contribution');
            rows{end+1} = MK('Relativity','cfg.physics.relativity.clock.truth.enable', rlkTr_, ...
                ternst_(rlkTr_, GC, IA), false, 'measurementValue', ...
                'relativity.clock.truth.enable=true', ...
                'Relativistic clock correction; enabled but guarded/warned as not validated in v1');
            rows{end+1} = MK('Relativity','cfg.physics.relativity.clock.model.enable', rlkMd_, ...
                ternst_(rlkMd_, GC, IA), false, 'measurementValue', ...
                'relativity.clock.model.enable=true', ...
                'Relativistic clock in EKF model; set but guarded/not validated in v1');

            %% --- Atmosphere --------------------------------------------
            tropTr_ = logical_G_(G('errors.troposphere.truth.enable'));
            tropMd_ = logical_G_(G('errors.troposphere.model.enable'));
            tropTyp_= G('errors.troposphere.modelType'); if isempty(tropTyp_); tropTyp_='simpleMapped'; end
            tropSto_= logical_G_(G('errors.troposphere.stochastic.enable'));
            tropoMode_= G('estimation.troposphereMode'); if isempty(tropoMode_); tropoMode_='none'; end
            tropoZwd_en_= strcmp(tropoMode_,'ekf') || strcmp(tropoMode_,'zwdEkf');
            ionoTr_ = logical_G_(G('errors.ionosphere.truth.enable'));
            ionoMd_ = logical_G_(G('errors.ionosphere.model.enable'));
            ionoTyp_= G('errors.ionosphere.modelType'); if isempty(ionoTyp_); ionoTyp_='simpleMapped'; end
            ionoSto_= logical_G_(G('errors.ionosphere.stochastic.enable'));
            ionoSci_= logical_G_(G('errors.ionosphere.scintillation.enable'));

            rows{end+1} = MK('Atmosphere','cfg.errors.troposphere.truth.enable', tropTr_, ...
                ternst_(tropTr_, A, IA), true, 'measurementValue', 'always', ...
                'Troposphere delay in truth; simpleMapped: Niell-style elevation scaling; ~2.3 m zenith');
            rows{end+1} = MK('Atmosphere','cfg.errors.troposphere.model.enable', tropMd_, ...
                ternst_(tropMd_, A, IA), true, 'measurementValue', 'always', ...
                'Troposphere model in EKF; matched truth+model → zero residual contribution');
            rows{end+1} = MK('Atmosphere','cfg.errors.troposphere.modelType', tropTyp_, ...
                ternst_(tropTr_||tropMd_, A, IA), false, 'measurementValue', ...
                'troposphere enabled', ...
                'simpleMapped: M(e)=1/sin(e) scaling; not VMF3/GPT3/ERA5 — known limitation');
            rows{end+1} = MK('Atmosphere','cfg.errors.troposphere.stochastic.enable', tropSto_, ...
                ternst_(tropSto_, A, IA), true, 'measurementValue', ...
                'errors.troposphere.truth.enable=true', ...
                'Adds ZWD random walk to troposphere truth; unmodelled residual in EKF');
            rows{end+1} = MK('Atmosphere','cfg.estimation.troposphereMode', tropoMode_, ...
                ternst_(tropoZwd_en_, A, IA), true, 'stateDimension,Q', ...
                'estimation.troposphereMode=ekf', ...
                'ekf/zwdEkf: one ZWD state per tower; none: no tropo state in EKF (default — weak observability at GEO)');
            rows{end+1} = MK('Atmosphere','cfg.estimation.tropoZwd.* (sigma, tau)', ...
                sprintf('sig=%.3g tau=%g', ...
                    safe_num_(G('estimation.tropoZwd.sigma_ss_m'),0.05), ...
                    safe_num_(G('estimation.tropoZwd.tau_s'),3600)), ...
                ternst_(tropoZwd_en_, A, IA), true, 'Q', ...
                'estimation.troposphereMode=ekf', ...
                'ZWD process noise steady-state sigma and time constant; sets Q for tropo state');
            rows{end+1} = MK('Atmosphere','cfg.errors.ionosphere.truth.enable', ionoTr_, ...
                ternst_(ionoTr_, A, IA), true, 'measurementValue', 'always', ...
                'Ionosphere delay in truth; sign convention: adds to code, subtracts from carrier');
            rows{end+1} = MK('Atmosphere','cfg.errors.ionosphere.model.enable', ionoMd_, ...
                ternst_(ionoMd_, A, IA), true, 'measurementValue', 'always', ...
                'Iono model in EKF; matched truth+model → zero residual; IF combination eliminates it');
            rows{end+1} = MK('Atmosphere','cfg.errors.ionosphere.modelType', ionoTyp_, ...
                ternst_(ionoTr_||ionoMd_, A, IA), false, 'measurementValue', ...
                'ionosphere enabled', ...
                'simpleMapped: thin-shell M(e) mapping; not Klobuchar/IONEX — known limitation');
            rows{end+1} = MK('Atmosphere','cfg.errors.ionosphere.stochastic.enable', ionoSto_, ...
                ternst_(ionoSto_, A, IA), true, 'measurementValue', ...
                'ionosphere enabled', 'Adds random walk to iono truth; residual in EKF observations');
            rows{end+1} = MK('Atmosphere','cfg.errors.ionosphere.scintillation.enable', ionoSci_, ...
                ternst_(ionoSci_, A, IA), true, 'measurementValue', ...
                'ionosphere enabled', 'Phase scintillation adds to carrier and Doppler truth noise');
            rows{end+1} = MK('Atmosphere','derived: IF covariance limitation', 'uncorrelated L1/L2 assumption', ...
                GC, false, 'R', 'code/carrier IF active', ...
                'Var(IF)=alpha^2*Var(L1)+beta^2*Var(L2), Cov(L1,L2)=0; correlated iono noise not propagated to IF R');

            %% --- Antenna / HW / Multipath / Survey / Correlated -------
            pcoTr_  = logical_G_(G('effects.antennaPCO.truth.enable'));
            pcoMd_  = logical_G_(G('effects.antennaPCO.model.enable'));
            pcvTr_  = logical_G_(G('effects.antennaPCV.truth.enable'));
            pcvMd_  = logical_G_(G('effects.antennaPCV.model.enable'));
            survTr_ = logical_G_(G('effects.towerSurvey.truth.enable'));
            survMd_ = logical_G_(G('effects.towerSurvey.model.enable'));
            hwTr_   = logical_G_(G('errors.hardwareDelay.truth.enable'));
            hwMd_   = logical_G_(G('errors.hardwareDelay.model.enable'));
            mpTr_   = logical_G_(G('errors.multipath.truth.enable'));
            mpMd_   = logical_G_(G('errors.multipath.model.enable'));
            corrEn_ = logical_G_(G('effects.correlatedNoise.enable'));

            rows{end+1} = MK('Antenna','cfg.effects.antennaPCO.truth.enable', pcoTr_, ...
                ternst_(pcoTr_, A, IA), true, 'measurementValue', 'always', ...
                'Antenna phase-centre offset in truth; synthetic calibrated constants (no ANTEX in v1)');
            rows{end+1} = MK('Antenna','cfg.effects.antennaPCO.model.enable', pcoMd_, ...
                ternst_(pcoMd_, A, IA), true, 'measurementValue', 'always', ...
                'PCO correction in EKF model; matched truth+model → zero residual');
            rows{end+1} = MK('Antenna','cfg.effects.antennaPCV.truth.enable', pcvTr_, ...
                ternst_(pcvTr_, A, IA), true, 'measurementValue', 'always', ...
                'Phase-centre variation in truth; toy model (elevation-only; no ANTEX/azimuth)');
            rows{end+1} = MK('Antenna','cfg.effects.antennaPCV.model.enable', pcvMd_, ...
                ternst_(pcvMd_, A, IA), true, 'measurementValue', 'always', ...
                'PCV correction in EKF; no ANTEX in v1; azimuth-dependent PCV not supported');
            rows{end+1} = MK('Antenna','cfg.effects.towerSurvey.truth.enable', survTr_, ...
                ternst_(survTr_, A, IA), true, 'measurementValue', 'always', ...
                'Tower antenna survey error in truth; biases tower position used in range computation');
            rows{end+1} = MK('Antenna','cfg.effects.towerSurvey.model.enable', survMd_, ...
                ternst_(survMd_, A, IA), true, 'measurementValue', 'always', ...
                'Survey error corrected in EKF model; matched cancels; unmatched adds range bias');
            rows{end+1} = MK('HardwareMultipathSurvey','cfg.errors.hardwareDelay.truth.enable', hwTr_, ...
                ternst_(hwTr_, A, IA), true, 'measurementValue', 'always', ...
                'Per-signal hardware delay in truth; set to zero in v1 (no calibrated DCB products)');
            rows{end+1} = MK('HardwareMultipathSurvey','cfg.errors.hardwareDelay.model.enable', hwMd_, ...
                ternst_(hwMd_, A, IA), true, 'measurementValue', 'always', ...
                'Hardware delay correction in EKF model; zero-DCB known limitation L1');
            rows{end+1} = MK('HardwareMultipathSurvey','cfg.errors.multipath.truth.enable', mpTr_, ...
                ternst_(mpTr_, A, IA), true, 'measurementValue', 'always', ...
                'Multipath bias in truth pseudorange; synthetic elevation-dependent model in v1');
            rows{end+1} = MK('HardwareMultipathSurvey','cfg.errors.multipath.model.enable', mpMd_, ...
                ternst_(mpMd_, A, IA), true, 'measurementValue', 'always', ...
                'Multipath correction in EKF model; matched cancels; real multipath unmodelled in v1');
            rows{end+1} = MK('HardwareMultipathSurvey','cfg.effects.correlatedNoise.enable', corrEn_, ...
                ternst_(corrEn_, A, IA), true, 'measurementValue,R', 'always', ...
                'Spatially correlated measurement noise; adds off-diagonal R structure beyond tower-clock block');

            %% --- Attitude ----------------------------------------------
            estAtt_ = logical_G_(G('estimator.estimateAttitude'));
            estOmg_ = logical_G_(G('estimator.estimateAngularRate'));
            attParam_= G('estimator.attitude.parameterization');
            if isempty(attParam_); attParam_='eulerZYX'; end
            maxInj_ = G('estimator.attitude.maxErrorStateInjection_rad');
            attCarMode_= G('estimator.attitudeCarrierMode'); if isempty(attCarMode_); attCarMode_='off'; end
            calWin_ = G('estimator.diffAtt.calibWin_s');
            refMode_= G('estimator.diffAtt.referenceMode');
            refSig_ = G('estimator.diffAtt.referenceSigma_deg');
            kavEn_  = logical_G_(G('estimator.runKnownAmbiguityValidation'));
            isQuat_ = strcmp(attParam_,'quaternionErrorState');
            isDiffAtt_ = strcmp(attCarMode_,'calibratedDifferentialAmbiguity');

            nArms_ = 0;
            try
                arms_ = cfg.asset.receiverLeverArms_body_m;
                if isnumeric(arms_) && size(arms_,1)==3; nArms_=size(arms_,2); end
            catch; end

            rows{end+1} = MK('Attitude','cfg.estimator.estimateAttitude', estAtt_, ...
                ternst_(estAtt_, A, IA), true, 'stateDimension', 'nReceivers>1', ...
                '3 Euler/quaternion states in EKF; requires nReceivers>1 and carrier lever-arm geometry');
            rows{end+1} = MK('Attitude','cfg.estimator.estimateAngularRate', estOmg_, ...
                ternst_(estOmg_, A, IA), true, 'stateDimension', ...
                'estimateAngularRate=true', 'Angular rate states frozen (near-zero Q) in default run');
            rows{end+1} = MK('Attitude','cfg.estimator.attitude.parameterization', attParam_, ...
                ternst_(estAtt_&&isQuat_, A, ternst_(estAtt_, A, IA)), true, ...
                'stateDimension,EKF', 'estimateAttitude=true', ...
                'quaternionErrorState: nominal quat + 3-state error-state EKF; eulerZYX: 3 Euler states directly');
            if ~isempty(maxInj_)
                rows{end+1} = MK('Attitude','cfg.estimator.attitude.maxErrorStateInjection_rad', maxInj_, ...
                    ternst_(isQuat_&&estAtt_, A, IA), false, 'EKF', ...
                    'quaternionErrorState active', ...
                    'Warns when error-state injection norm exceeds threshold; not a clamp');
            end
            rows{end+1} = MK('Attitude','cfg.estimator.attitudeCarrierMode', attCarMode_, ...
                ternst_(isDiffAtt_&&estAtt_, A, IA), true, 'measurementRows,EKF', ...
                'estimateAttitude=true AND carrierMode=ekfFloat', ...
                'calibratedDifferentialAmbiguity: baseline-differenced carrier phases drive attitude EKF');
            if ~isempty(calWin_)
                rows{end+1} = MK('Attitude','cfg.estimator.diffAtt.calibWin_s', calWin_, ...
                    ternst_(isDiffAtt_, A, IA), true, 'EKF', 'attitudeCarrierMode=calibratedDifferential*', ...
                    'Calibration window length for differential ambiguity bias estimation');
            end
            if ~isempty(refMode_)
                rows{end+1} = MK('Attitude','cfg.estimator.diffAtt.referenceMode', refMode_, ...
                    ternst_(isDiffAtt_, A, IA), true, 'EKF', ...
                    'attitudeCarrierMode=calibratedDifferential*', ...
                    'externalInitialAttitude: prevents delta_B absorbing initial EKF attitude error');
            end
            if ~isempty(refSig_)
                rows{end+1} = MK('Attitude','cfg.estimator.diffAtt.referenceSigma_deg', refSig_, ...
                    ternst_(isDiffAtt_, A, IA), true, 'EKF', ...
                    'referenceMode=externalInitialAttitude', ...
                    'Noise on injected reference attitude; controls reference uncertainty');
            end
            rows{end+1} = MK('Attitude','cfg.estimator.runKnownAmbiguityValidation', kavEn_, ...
                ternst_(kavEn_, DO, IA), false, 'EKF', 'estimateAttitude=true', ...
                'Runs 120 s sub-simulation with truth ambiguities; attitude validation only — not operational fixing');
            rows{end+1} = MK('Attitude','derived: receiver lever-arm count', nArms_, ...
                ternst_(nArms_>1, A, IA), true, 'measurementRows,attitude', ...
                'nReceivers>1', ...
                'Non-collinear cross pattern (4-rx default); rank-3 baseline geometry required for full attitude obs.');

            %% --- Ambiguity resolution ----------------------------------
            arEn_   = logical_G_(G('estimator.diffAtt.ambiguityResolution.enable'));
            arMeth_ = G('estimator.diffAtt.ambiguityResolution.method');
            arSig_  = G('estimator.diffAtt.ambiguityResolution.signal');
            arEbf_  = G('estimator.diffAtt.ambiguityResolution.enabledByFrequency');
            arSHW_  = G('estimator.diffAtt.ambiguityResolution.searchHalfWidth_cycles');
            arMinA_ = G('estimator.diffAtt.ambiguityResolution.minArcEpochs');
            arRms_  = G('estimator.diffAtt.ambiguityResolution.rmsThreshold_cycles');
            arRat_  = G('estimator.diffAtt.ambiguityResolution.ratioThreshold');
            arMaxFl_= G('estimator.diffAtt.ambiguityResolution.maxFloatDistance_cycles');
            arMaxWL_= G('estimator.diffAtt.ambiguityResolution.maxWideLaneFloatDistance_cycles');
            arPFP_  = G('estimator.diffAtt.ambiguityResolution.partialFixPolicy');
            arRAll_ = G('estimator.diffAtt.ambiguityResolution.requireAllForGnssOnlyClaim');
            iaEn_   = logical_G_(G('estimator.integerAmbiguity.enable'));
            iaMode_ = G('estimator.integerAmbiguity.mode');
            iaMinAL_= G('estimator.integerAmbiguity.minArcLength_s');
            iaMaxSig_= G('estimator.integerAmbiguity.maxSigma_cycles');
            iaMaxDI_= G('estimator.integerAmbiguity.maxDistanceToInteger_cycles');
            iaFV_   = G('estimator.integerAmbiguity.fixVariance_cycles2');
            iaRS_   = logical_G_(G('estimator.integerAmbiguity.resetOnSlip'));

            rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.enable', arEn_, ...
                ternst_(arEn_&&isDiffAtt_, A, IA), true, 'EKF,carrierArc', ...
                'attitudeCarrierMode=calibratedDifferential AND carrierMode=ekfFloat AND nReceivers>1', ...
                'Baseline integer AR for attitude: constrainedBaselineIntegerSearch on L1 (or L1+L2) baselines');
            rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.method', ...
                arMeth_, ternst_(arEn_, A, IA), false, 'EKF', 'ambiguityResolution.enable=true', ...
                'constrainedBaselineIntegerSearch: grid search over integer offsets; no LAMBDA in v1');
            rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.signal', ...
                arSig_, ternst_(arEn_, A, IA), true, 'measurementRows', ...
                'ambiguityResolution.enable=true', 'L1 primary AR signal; L2 added for dual-freq screening');
            if ~isempty(arEbf_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.enabledByFrequency', ...
                    arEbf_, ternst_(arEn_, A, IA), true, 'measurementRows', ...
                    'ambiguityResolution.enable=true', ...
                    'Per-frequency AR enable; derived from signals.enabledMask in finalizeConfig');
            end
            if ~isempty(arSHW_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.searchHalfWidth_cycles', ...
                    arSHW_, ternst_(arEn_, A, IA), true, 'EKF', ...
                    'ambiguityResolution.enable=true', 'Integer search range ±N cycles around float estimate');
            end
            if ~isempty(arMinA_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.minArcEpochs', ...
                    arMinA_, ternst_(arEn_, A, IA), true, 'carrierArc', ...
                    'ambiguityResolution.enable=true', 'Minimum arc length before attempting AR fix');
            end
            if ~isempty(arRat_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.ratioThreshold', ...
                    arRat_, ternst_(arEn_, A, IA), true, 'EKF', ...
                    'ambiguityResolution.enable=true', 'Ratio test for fix acceptance; 3.0 from Stage 75 hardening');
            end
            if ~isempty(arRms_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.rmsThreshold_cycles', ...
                    arRms_, ternst_(arEn_, A, IA), true, 'EKF', ...
                    'ambiguityResolution.enable=true', 'RMS residual gate: fix rejected when post-fix RMS exceeds this');
            end
            if ~isempty(arMaxFl_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.maxFloatDistance_cycles', ...
                    arMaxFl_, ternst_(arEn_, A, IA), true, 'EKF', ...
                    'ambiguityResolution.enable=true', 'Float-distance guard; blocks fix when far from any integer');
            end
            if ~isempty(arMaxWL_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.maxWideLaneFloatDistance_cycles', ...
                    arMaxWL_, ternst_(arEn_&&isDual, A, IA), true, 'EKF', ...
                    'dual-freq AND ambiguityResolution.enable=true', ...
                    'WL consistency screening threshold; WL used as gate only, not full WL/NL fixing');
            end
            if ~isempty(arPFP_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.partialFixPolicy', ...
                    arPFP_, ternst_(arEn_, A, IA), true, 'EKF', ...
                    'ambiguityResolution.enable=true', ...
                    'useFixedOnlyOrExplicitMixed: uses fixed baselines only when all fixed; prevents partial inconsistency');
            end
            if ~isempty(arRAll_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.diffAtt.ambiguityResolution.requireAllForGnssOnlyClaim', ...
                    arRAll_, ternst_(arEn_, A, IA), false, 'EKF', ...
                    'ambiguityResolution.enable=true', ...
                    'GNSS-only fixed attitude claim requires all baselines fixed; partial fix not a GNSS-only claim');
            end
            rows{end+1} = MK('Ambiguity','cfg.estimator.integerAmbiguity.enable', iaEn_, ...
                ternst_(iaEn_, A, IA), true, 'EKF', 'always', ...
                'Guarded raw-carrier integer fixing; controlledRawCarrier mode; strict sigma/distance/rms gates');
            rows{end+1} = MK('Ambiguity','cfg.estimator.integerAmbiguity.mode', ...
                iaMode_, ternst_(iaEn_, A, IA), true, 'EKF', ...
                'integerAmbiguity.enable=true', ...
                'controlledRawCarrier: raw L1/L2 per-track integer fix with strict gates; not IF fixing; not LAMBDA');
            if ~isempty(iaMinAL_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.integerAmbiguity.minArcLength_s', iaMinAL_, ...
                    ternst_(iaEn_, A, IA), true, 'carrierArc', 'integerAmbiguity.enable=true', ...
                    'Minimum carrier arc duration before attempting raw integer fix');
            end
            if ~isempty(iaMaxSig_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.integerAmbiguity.maxSigma_cycles', iaMaxSig_, ...
                    ternst_(iaEn_, A, IA), true, 'EKF', 'integerAmbiguity.enable=true', ...
                    'Float sigma gate: fix only when float ambiguity sigma < 0.15 cycles');
            end
            if ~isempty(iaMaxDI_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.integerAmbiguity.maxDistanceToInteger_cycles', iaMaxDI_, ...
                    ternst_(iaEn_, A, IA), true, 'EKF', 'integerAmbiguity.enable=true', ...
                    'Pull-in gate: fix only when float estimate within 0.20 cycles of an integer');
            end
            rows{end+1} = MK('Ambiguity','cfg.estimator.integerAmbiguity.resetOnSlip', iaRS_, ...
                ternst_(iaEn_, A, IA), true, 'carrierArc', ...
                'integerAmbiguity.enable=true', ...
                'Reset integer fix on confirmed carrier slip; prevents wrong integer from persisting across arc break');
            if ~isempty(iaFV_)
                rows{end+1} = MK('Ambiguity','cfg.estimator.integerAmbiguity.fixVariance_cycles2', iaFV_, ...
                    ternst_(iaEn_, A, IA), true, 'EKF', 'integerAmbiguity.enable=true', ...
                    'Posterior ambiguity variance after a fix; small value forces EKF to treat integer as known');
            end
            rows{end+1} = MK('Ambiguity','derived: LAMBDA/MLAMBDA (integerAmbiguity)', false, GC, false, ...
                'EKF', 'not implemented', ...
                'Integer Least Squares (LAMBDA/MLAMBDA) not implemented; fixing uses simple distance-to-integer gate');

            %% --- Carrier Slip ------------------------------------------
            csEn_   = logical_G_(G('carrierSlip.enable'));
            csMeth_ = G('carrierSlip.method');
            csThr_  = G('carrierSlip.threshold_m');
            csMinA_ = G('carrierSlip.minArcLength_s');
            csProd_ = logical_G_(G('carrierSlip.productStepCompensation'));
            csAtm_  = logical_G_(G('carrierSlip.atmosphereStepCompensation'));
            csAnt_  = logical_G_(G('carrierSlip.antennaStepCompensation'));
            csHW_   = logical_G_(G('carrierSlip.hardwareStepCompensation'));
            csDiff_ = logical_G_(G('carrierSlip.diffAttitudeBaselineMode'));
            csReset_= logical_G_(G('carrierSlip.resetAmbiguityOnConfirmedSlip'));
            csInj_  = logical_G_(G('carrierSlip.syntheticSlipInjection.enable'));
            sdEn_   = logical_G_(G('measurements.carrier.slipDetection.enable'));
            sdMinEp_= G('measurements.carrier.slipDetection.minEpochsBeforeDetect');
            sdAct_  = G('measurements.carrier.slipDetection.action');

            rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.enable', csEn_, ...
                ternst_(csEn_&&carEn_, A, IA), true, 'carrierArc,measurementRows', ...
                'carrierPhase.enable=true', ...
                'Master slip detection guard; modelStepCompensatedResidualJump removes product-boundary false slips');
            rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.method', csMeth_, ...
                ternst_(csEn_&&carEn_, A, IA), true, 'carrierArc', ...
                'carrierSlip.enable=true', ...
                'modelStepCompensatedResidualJump: slipMetric=observed_jump − expected_model_jump');
            if ~isempty(csThr_)
                rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.threshold_m', csThr_, ...
                    ternst_(csEn_, A, IA), true, 'carrierArc', 'carrierSlip.enable=true', ...
                    '0.10 m threshold; 7-sigma below with sigma_bias=0.01 m (false-slip prob ~1e-12)');
            end
            if ~isempty(csMinA_)
                rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.minArcLength_s', csMinA_, ...
                    ternst_(csEn_, A, IA), true, 'carrierArc', 'carrierSlip.enable=true', ...
                    'Minimum arc epoch count before ambiguity is considered converged');
            end
            rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.productStepCompensation', csProd_, ...
                ternst_(csProd_&&csEn_, A, IA), true, 'carrierArc', ...
                'carrierSlip.enable=true AND truthHistoryProductNoisy mode', ...
                'Subtracts expected product step from slip metric; prevents false reset at product epoch boundary');
            rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.atmosphereStepCompensation', csAtm_, ...
                ternst_(csAtm_&&csEn_, A, IA), false, 'carrierArc', ...
                'carrierSlip.enable=true', 'Documented intent; v1 atmosphere model is smooth — no step expected');
            rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.antennaStepCompensation', csAnt_, ...
                ternst_(csAnt_&&csEn_, A, IA), false, 'carrierArc', ...
                'carrierSlip.enable=true', 'Documented intent; v1 PCO is static — no step expected');
            rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.hardwareStepCompensation', csHW_, ...
                ternst_(csHW_&&csEn_, A, IA), false, 'carrierArc', ...
                'carrierSlip.enable=true', 'Documented intent; v1 hardware delay is static — no step expected');
            rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.diffAttitudeBaselineMode', csDiff_, ...
                ternst_(csDiff_&&csEn_, A, IA), false, 'carrierArc', ...
                'carrierSlip.enable=true AND attitudeCarrierMode active', ...
                'DiffAtt slip detector disabled per Stage 69; carrier slip handled by main detector');
            rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.resetAmbiguityOnConfirmedSlip', csReset_, ...
                ternst_(csReset_&&csEn_, A, IA), true, 'stateDimension,carrierArc', ...
                'carrierSlip.enable=true', 'Resets float ambiguity state to large sigma on confirmed slip');
            rows{end+1} = MK('CarrierSlip','cfg.carrierSlip.syntheticSlipInjection.enable', csInj_, ...
                ternst_(csInj_, A, IA), true, 'measurementValue,carrierArc', ...
                'carrierSlip.syntheticSlipInjection.enable=true', ...
                'Injects synthetic cycle slip into carrier truth for stress testing; not active in default run');
            rows{end+1} = MK('CarrierSlip','cfg.measurements.carrier.slipDetection.enable', sdEn_, ...
                ternst_(sdEn_&&carEn_, A, IA), true, 'carrierArc,measurementRows', ...
                'carrierPhase.enable=true', ...
                'Enables per-track residual-jump slip test (compensated by model step)');
            if ~isempty(sdMinEp_)
                rows{end+1} = MK('CarrierSlip','cfg.measurements.carrier.slipDetection.minEpochsBeforeDetect', ...
                    sdMinEp_, ternst_(sdEn_, A, IA), false, 'carrierArc', ...
                    'slipDetection.enable=true', 'Epochs before slip detection activates on a new arc');
            end
            if ~isempty(sdAct_)
                rows{end+1} = MK('CarrierSlip','cfg.measurements.carrier.slipDetection.action', ...
                    sdAct_, ternst_(sdEn_, A, IA), true, 'measurementRows,carrierArc', ...
                    'slipDetection.enable=true', ...
                    'resetAndSkip: resets ambiguity sigma and skips carrier measurement this epoch');
            end

            %% --- Diagnostics (selected) --------------------------------
            rows{end+1} = MK('Diagnostics','cfg.diagnostics.codeIonoFreeRows.enable', ...
                logical_G_(G('diagnostics.codeIonoFreeRows.enable')), ...
                ternst_(logical_G_(G('diagnostics.codeIonoFreeRows.enable')), DO, IA), ...
                false, 'diagnostics', 'code IF active', ...
                'Code IF row count/consistency diagnostic; no EKF physics effect');
            rows{end+1} = MK('Diagnostics','cfg.diagnostics.carrierIonoFreeRows.enable', ...
                logical_G_(G('diagnostics.carrierIonoFreeRows.enable')), ...
                ternst_(logical_G_(G('diagnostics.carrierIonoFreeRows.enable')), DO, IA), ...
                false, 'diagnostics', 'carrier IF active', ...
                'Carrier IF diagnostic; traces L1/L2 state pairs; no EKF physics effect');
            rows{end+1} = MK('Diagnostics','cfg.diagnostics.wideLaneNarrowLane.enable', ...
                logical_G_(G('diagnostics.wideLaneNarrowLane.enable')), ...
                ternst_(logical_G_(G('diagnostics.wideLaneNarrowLane.enable')), DO, IA), ...
                false, 'diagnostics', 'diagnostics.wideLaneNarrowLane.enable=true', ...
                'WL/NL sigma diagnostic; no integer fixing, no LAMBDA; computes Var(WL) from Pamb only');
            rows{end+1} = MK('Diagnostics','cfg.diagnostics.ambiguityFixingReadiness.enable', ...
                logical_G_(G('diagnostics.ambiguityFixingReadiness.enable')), ...
                ternst_(logical_G_(G('diagnostics.ambiguityFixingReadiness.enable')), DO, IA), ...
                false, 'diagnostics', 'diagnostics.ambiguityFixingReadiness.enable=true', ...
                'Readiness gate: collects arc/residual/NIS evidence; does not fix or round ambiguities');
            rows{end+1} = MK('Diagnostics','cfg.diagnostics.ekfInnovationAccounting.enable', ...
                logical_G_(G('diagnostics.ekfInnovationAccounting.enable')), ...
                ternst_(logical_G_(G('diagnostics.ekfInnovationAccounting.enable')), DO, IA), ...
                false, 'diagnostics', 'diagnostics.ekfInnovationAccounting.enable=true', ...
                'Separates physical/gauge/augmented NIS; no EKF math effect');
            rows{end+1} = MK('Diagnostics','cfg.validation.scientificCampaign.enable', ...
                logical_G_(G('validation.scientificCampaign.enable')), ...
                ternst_(logical_G_(G('validation.scientificCampaign.enable')), DO, IA), ...
                false, 'diagnostics', 'validation.scientificCampaign.enable=true', ...
                'Multi-case × multi-seed NIS/NEES campaign; runs sub-simulations but does not change main EKF');

            % Combine all rows
            if isempty(rows)
                manifest = revgnss.SimulationToggleManifest.emptyRow_();
                manifest = manifest(false);
                return;
            end
            manifest = rows{1};
            for ri = 2:numel(rows)
                manifest(end+1) = rows{ri}; %#ok<AGROW>
            end
        end

        % ----------------------------------------------------------------
        function T = toTable(manifest)
            % toTable  Convert manifest struct array to MATLAB table.
            if isempty(manifest)
                T = table();
                return;
            end
            cats  = {manifest.category}';
            paths = {manifest.cfgPath}';
            vals  = {manifest.value}';
            stats = {manifest.status}';
            sims  = [manifest.simulationImpact]';
            affs  = {manifest.affects}';
            conds = {manifest.activeCondition}';
            notes = {manifest.notes}';
            T = table(cats, paths, vals, stats, sims, affs, conds, notes, ...
                'VariableNames', {'category','cfgPath','value','status', ...
                'simulationImpact','affects','activeCondition','notes'});
        end

        % ----------------------------------------------------------------
        function writeCsv(T, csvPath)
            % writeCsv  Write manifest table to CSV.
            if isempty(T) || ~istable(T); return; end
            folder = fileparts(csvPath);
            if ~isempty(folder) && ~exist(folder,'dir'); mkdir(folder); end
            writetable(T, csvPath);
        end

        % ----------------------------------------------------------------
        function c = compact(manifest)
            % compact  Return lightweight copy (struct array has no heavy fields).
            c = manifest;
        end

    end % methods (Static)

    methods (Static, Access = private)

        function v = getf_(cfg, dotPath)
            % Safe nested field accessor. dotPath: 'a.b.c' (no leading 'cfg.').
            try
                v = cfg;
                parts = strsplit(dotPath, '.');
                if strcmp(parts{1},'cfg'); parts = parts(2:end); end
                for k = 1:numel(parts)
                    v = v.(parts{k});
                end
            catch
                v = [];
            end
        end

        function s = fmtVal_(v)
            % Format MATLAB value as compact string.
            if isempty(v)
                s = 'N/A';
            elseif islogical(v) && isscalar(v)
                if v; s = 'true'; else; s = 'false'; end
            elseif islogical(v)
                p = arrayfun(@(x) num2str(double(x)), v, 'UniformOutput', false);
                s = ['[' strjoin(p,',') ']'];
            elseif isnumeric(v) && isscalar(v)
                if isnan(v)
                    s = 'NaN';
                elseif v == round(v) && abs(v) < 1e9
                    s = sprintf('%g', v);
                else
                    s = sprintf('%.4g', v);
                end
            elseif isnumeric(v) && numel(v) <= 8
                s = mat2str(v, 4);
            elseif isnumeric(v)
                s = sprintf('[%dx%d %s]', size(v,1), size(v,2), class(v));
            elseif ischar(v)
                s = v;
            elseif iscell(v) && all(cellfun(@ischar, v))
                s = ['{' strjoin(v,',') '}'];
            else
                s = class(v);
            end
        end

        function m = mkRow_(cat, path, valStr, status, simImpact, affects, cond, notes)
            % mkRow_  Construct single manifest row struct.
            m.category        = cat;
            m.cfgPath         = path;
            m.value           = valStr;
            m.status          = status;
            m.simulationImpact = logical(simImpact);
            m.affects         = affects;
            m.activeCondition = cond;
            m.notes           = notes;
        end

        function m = emptyRow_()
            m = revgnss.SimulationToggleManifest.mkRow_( ...
                '','','','',false,'','','');
        end

    end % methods (Static, Access = private)

end % classdef

% ---- File-scope helpers (not classdef methods) --------------------------

function b = logical_G_(v)
    % Cast safely to logical; missing → false.
    if isempty(v); b = false;
    elseif islogical(v) && isscalar(v); b = v;
    elseif isnumeric(v) && isscalar(v); b = logical(v);
    else; b = false;
    end
end

function s = ternst_(cond, a, b)
    % Ternary for status strings.
    if cond; s = a; else; s = b; end
end

function n = numel_safe_(cfg, field)
    try; n = numel(cfg.(field)); catch; n = 0; end
end

function v = safe_num_(val, default)
    if isnumeric(val) && isscalar(val) && ~isnan(val); v = val; else; v = default; end
end
