classdef StageHistory
    % StageHistory  Implemented-stage history and missing-scientific-items list.
    %
    % Separates stage-history bookkeeping from runtime source-truth in ReportStatus.
    % ReportStatus.current() delegates to this class for long list fields.
    %
    % Usage:
    %   items   = revgnss.StageHistory.implementedItems()
    %   missing = revgnss.StageHistory.missingScientificItems(55)
    %   item    = revgnss.StageHistory.currentImplementedItem(55)

    methods (Static)

        function list = implementedItems()
            % implementedItems  Full history of implemented-stage items.
            list = {
                'ReportStatus: runtime git SHA, branch, validation mode, missing-stages list'
                'ValidationSummary: JSON + TXT summary writer and reader'
                'ValidationRunner: deterministic random test selection (seed per stage, 2-5 tests)'
                'FrameTimeUtils: simple ECEF/inertial Earth-rotation and Sagnac foundation'
                'run_stage24_validation.m: targeted smoke validation + all-toggle report run'
                'Report Stage 24 validation status section in PDF/TEX'
                'All-toggle report mode: all independent boolean features enabled for run'
                'README updated to Stage 24 with runtime-SHA policy'
                'TWSTFT code time-transfer diagnostic scaffold (Stage 24a, diagnostic-only)'
                'Stage 25: env-var all-toggle gate; run_stage25_26_validation executes main script directly'
                'Stage 26: OrbitDynamics two-body + J2 + RK4; OrbitPropagator orbit-mode selector'
                'Stage 27: validation artifact closure; preliminary summary before report; real PDF text via pdftotext'
                'Stage 28: OrbitDiagnostics helper; OrbitPropagator time-grid validation; orbit diagnostics in report'
                'Stage 29: validation gate moved into main script; .gitignore for output artifacts; SHA-based freshness check'
                'Stage 30: MainScriptValidationGate helper; restored pre/post-run gate in run_oo_reverse_gnss_report.m'
                'Stage 31: AttitudeObservability audit class; H-column rank/condition/classification; report subsection'
                'Stage 32: ReceiverGeometry helper; body-frame lever-arm normalisation, baselines, centroid; report subsection'
                'Stage 33: AttitudeKinematics convention(), eulerToDcm(), gimbal metric, validateDcm(), finite-diff lever-arm Jacobian; report subsection'
                'Stage 34: AttitudeJacobianAudit audit(), finiteDiffRangeAttitudePartial(), hOnlySummary(); H-only summary in production; report subsection'
                'Stage 35: AttitudeEvidenceReport helper; scenario-level attitude evidence summary linking truth/estimate histories with observability, receiver geometry, Euler convention, and Jacobian audit status'
                'Stage 36: AttitudeScenarioReadiness helper; single-asset attitude scenario readiness classification from receiver geometry rank, measurement modes, observability, Jacobian audit, and evidence status'
                'Stage 37: validation-status chapter removed from PDF; README contains validation status and missing-scientific-stages summary; PDF verification checks scientific content and absence of validation-status heading'
                'Stage 38: CarrierAttitudePreparation helper; rowInventory (totalCarrierRows/totalDiffAttRows from summary), ambiguityInventory (nAmbiguities from nTowers*nReceivers), classify_ priority chain; report subsection in writeAttitudeObservability_'
                'Stage 39: CarrierRowMetadataInventory helper; carrier/differential-attitude row and ambiguity metadata inventory with summary fallback and explicit limitations; reused in Stage 38 helper; report subsection'
                'Stage 40: AmbiguityReadinessDiagnostics helper; float ambiguity readiness assessment using Stage 39 inventory, covariance check, slip detection status, known-ambiguity validation flag; blockers and score; report subsection'
                'Stage 41: AmbiguityStateMetadata helper; EKF ambiguity state-map export and final ambiguity covariance sub-block diagnostics for float ambiguity readiness'
                'Stage 42: SignalCatalog signal facade; guarded L2 carrier EKF row architecture (l2EkfRows.enable); L2 ambiguity states, wavelength, iono scaling per signal; L2CarrierArchitectureDiagnostics; AmbiguityStateMetadata signal ID labels (L1/L2)'
                'Stage 43: diagnostic-only L1/L2 ionosphere-free combination coefficients, first-order ionosphere cancellation check, and noise amplification reporting; no EKF IF rows and no integer fixing'
                'Stage 44: SignalConfigResolver for consistent L2 detection from any cfg field; IonosphereFreeBiasBudget diagnostic IF bias residual propagation; fixes l2SignalEnabled_ bug in IFCombinationDiagnostics'
                'Stage 45: guarded L1/L2 ionosphere-free code EKF rows via IF combination using alpha/beta coefficients; uncorrelated-noise R_IF; explicit bias-budget and noise-amplification limitations; no carrier IF, no integer fixing, no PPP-grade claim'
                'Stage 46: CodeIonoFreeConsistencyDiagnostics; explicit row-count, H-compatibility, R/noise-amplification, residual/NIS, and bias-state-risk audit for Stage 45 code IF EKF rows; combineJacobians utility in CodeIonoFreeRowBuilder'
                'Stage 47: CarrierIonoFreeRowBuilder post-processes L1+L2 carrier EKF rows into IF rows (float ambiguity, non-integer); CarrierIonoFreeEkfDiagnostics; B_IF=alpha*B_L1+beta*B_L2; no integer fixing, no LAMBDA/MLAMBDA, no calibrated DCB'
                'Stage 48: CarrierIonoFreeAmbiguityTraceability helper; explicit L1/L2 ambiguity state pair metadata in cpInfo (ambiguityStateIdxL1/L2, ambiguityStateIdxPair, ambiguityWeights); Var(B_IF)=[alpha beta]*P_pair*[alpha;beta] from Stage 41 Pamb; stale EKF-state-map-refactoring limitation removed from AmbiguityReadinessDiagnostics'
                'Stage 49: wide-lane / narrow-lane float diagnostics from traced L1/L2 ambiguity covariance; no integer fixing, no LAMBDA/MLAMBDA, no phase-bias products, no false-fix-risk control'
                'Stage 50: ambiguity fixing readiness gate combining Stages 41/48/49, arc-quality availability, and residual/NIS availability; strict readiness gate only; no integer fixing, no LAMBDA/MLAMBDA, no phase-bias products, no false-fix-risk control'
                'Stage 51: ambiguity readiness evidence hardening; non-early-return evidence collection, explicit arc-quality and residual/NIS availability diagnostics, public arcQuality/residualConsistency/blockerList, readiness score, blocker aggregation, and status-warning consistency; no integer fixing'
                'Stage 52: carrier arc and cycle-slip evidence export; CarrierTrackManager extended with slipCount_ and currentArcEpoch_ per track; CarrierArcEvidence helper; compact arc fields in summary; AmbiguityFixingReadinessGate.arcQuality() prefers Stage 52 fields; report subsection; no integer fixing'
                'Stage 53: cycle-slip-aware arc-separated float ambiguities; CarrierTrackManager extended with currentArcId_ per track; AmbiguityArcState helper; per-row arc metadata in summary; arc consistency check for carrier IF and WL/NL pairs; Stage 53 compact fields in summary; report subsection; no integer fixing'
                'Stage 54: enforceCarrierArcConsistency.enable gate in CarrierIonoFreeRowBuilder.buildFromStack; arc-inconsistent pairs filtered before IF combination; empty-output handling when all pairs skipped; new cpInfo_IF fields (nArcSkippedPairs, arcConsistencyEnforced, arcMetaUsedForEnforcement); arc-blocked classification in WideLaneNarrowLaneDiagnostics; Stage 54 blockers in AmbiguityFixingReadinessGate; Stage 54 compact summary fields; Stage 54 report subsection; no integer fixing'
                'Stage 55: source-truth and report-architecture cleanup; StageHistory and DiagnosticPluginRegistry helpers; ReportStatus delegates history/missing lists to StageHistory; ReportRunner calls DiagnosticPluginRegistry.collectAll for plugin metadata; Stage 55 PDF subsection; no physics change, no EKF math change, no ambiguity fixing, no LAMBDA/MLAMBDA, no false-fix-risk control'
                'Stage 56: measurement geometry core consolidation; LinkGeometry shared helper for tower position, antenna position, analytic LOS Jacobian, FD position/attitude Jacobian, and attitude partial gate; CodeJacobianBuilder and CarrierMeasurementBuilder migrated; preferred cfg.estimator.attitude.use<Kind>Partials config with backward-compat legacy path; stale carrier-IF comment in CarrierMeasurementBuilder replaced with scientifically correct guard; no physics change, no EKF math change, no integer fixing, no LAMBDA/MLAMBDA, no false-fix-risk control'
                'Stage 57: EKF innovation accounting and gauge/NIS cleanup; EkfInnovationAccounting helper with classifyRows/compute/residualRms/compact; ReverseGNSSSimulation captures nu and S from update() to build separated physical/gauge/augmented NIS accounting; Diagnostics stores per-epoch Stage 57 fields; ReportRunner exposes physicalNIS, gaugeNIS, and per-type RMS in summary; ClockExactReportBuilder Stage 57 subsection; legacyMeanNisIncludesGauge flag marks existing meanNIS as augmented; physicalConsistencyUsesGaugeRows=false; no measurement physics change, no EKF update math change, no integer fixing, no LAMBDA/MLAMBDA, no false-fix-risk control'
                'Stage 58: EKF two-body/J2 dynamics prediction; ECEF state transformed to inertial-like frame with constant Earth rotation, propagated by OrbitDynamics RK4 two-body/J2, transformed back to ECEF, and finite-difference 6x6 translational STM used in EKF prediction; EkfDynamicsPredictor helper with mode/propagateEcef/finiteDiffStm6/summaryLines; FrameTimeUtils extended with ecefStateToInertial/inertialStateToEcef/omegaEcef_radps/roundTripStateError; default constantVelocity mode is backward compatible; no drag, SRP, third bodies, EOP/IERS, relativistic clock model, integer fixing, LAMBDA/MLAMBDA, or false-fix-risk control'
                'Stage 59: controlled single-space-asset multi-antenna float-carrier attitude scenario; non-collinear 4-receiver lever-arm cross pattern with z-offset (baseline rank 3); carrier attitude partials enabled via preferred Stage 56 controls; EKF float ambiguities with arc-separated ambiguity metadata (Stage 53) and enforced carrier arc consistency (Stage 54); attitude error norm, carrier residual RMS, physical NIS-per-DOF, baseline rank, and dynamics self-consistency reported; constantVelocity EKF dynamics for self-consistency with static-ECEF GEO truth; ISL/TWSTFT disabled; ScenarioPresets.apply helper and SingleAssetAttitudeScenarioReport helper added; no integer fixing, no LAMBDA/MLAMBDA, no calibrated phase-bias products, no false-fix-risk control, no PPP-grade attitude claim, no multi-space-asset estimation'
                'Stage 60: carrier-attitude measurement model closure; CarrierAttitudeRowClosure helper with rowGeometry/attitudeJacobianFiniteDiff/compareRow/spotCheck methods delegating to LinkGeometry; CarrierMeasurementBuilder extended with per-row cpInfo closure metadata (leverArmNorm_m, attitudePartialsEnabled, attitudeSensitive, hAttitudeNorm, rowUsesLinkGeometry, carrierAttClosureAvail); SingleAssetAttitudeScenarioReport extended with component-level roll/pitch/yaw truth/estimate/error from final diag.log euler; ReportRunner populates stage60* summary fields including FD spot-check closure status; component-level euler errors exported to singleAssetAttitudeRollError_deg/Pitch/Yaw; no integer fixing, no LAMBDA/MLAMBDA, no quaternion/error-state EKF, no PPP-grade claim, no new orbit dynamics, no new attitude parameterization'
                'Stage 61: quaternion nominal / small-angle error-state attitude EKF; AttitudeErrorStateKinematics helper (quatNormalize, eulerToQuatZYX, quatToEulerZYX, quatToDcm, deltaQuat, injectRight, propagateQuatBodyRate, smallAnglePerturbedDcm, wrapEulerError_deg, summaryLines); ReverseGNSSEKF extended with nominalQuat_wxyz, attitudeParameterization, getMeasurementState(), getReportEulerRad(), quaternionErrorState predict/update paths; LinkGeometry.finiteDiffAttitudeJacobian extended with quaternionErrorState mode (perturbs DCM body-frame, not Euler angles); Diagnostics uses getReportEulerRad(); ReverseGNSSSimulation routes measurement state via getMeasurementState(); CarrierAttitudeRowClosure adds stage61CarrierClosureUsesErrorStateJacobian and closed-quaternion-error-state classification; run script selects quaternionErrorState; no integer fixing, no LAMBDA/MLAMBDA, no PPP-grade claim, no new orbit dynamics'
                'Stage 62: quaternion error-state covariance consistency closure; ReverseGNSSEKF.update now computes S, K, and Joseph posterior covariance from the pre-update covariance Pminus, then injects delta_theta into the nominal quaternion and applies the attitude reset Jacobian G=I-0.5*skew(delta_theta) to the posterior covariance; records covarianceResetOrder=posterior-after-joseph, injection norms, quaternion norm, and reset Jacobian condition number; injection size guard (default 10 deg) warns if exceeded; Stage 57 physical/gauge accounting and Stage 60 carrier-attitude closure preserved; legacy eulerZYX mode unchanged; no integer fixing, no LAMBDA/MLAMBDA, no false-fix-risk control, no PPP-grade claim'
                'Stage 63: controlled single-asset raw-carrier integer ambiguity fixing; IntegerAmbiguityFixer helper with assess/resetOnSlip/summaryLines; 18 scientific guards (scenario, ambiguity mode, arc length, covariance sigma, distance-to-integer, residual RMS, held/reset management); fixes applied as EKF pseudo-measurements via new applyAmbiguityPseudoMeasurement method in ReverseGNSSEKF; held fixes tracked per arc in ReverseGNSSSimulation.fixState63_; fix counts accumulated in fix63Log_; stage63* summary fields and Stage 63 PDF subsection; NOT LAMBDA/MLAMBDA, NOT carrier-IF integer fixing, NOT wide-lane/narrow-lane, NOT formal false-fix-risk control, NOT calibrated phase-bias products, NOT PPP-grade attitude'
                'Stage 64: scientific closure and v1 freeze; PCV default corrected to none; IF covariance assumption documented (alpha^2*Var_L1+beta^2*Var_L2, Cov=0); Doppler labelled simplified-v1 (LOS range-rate + rx/tower clock drift only); Stage 64 Final Scientific Closure section in PDF; stage64* summary fields in ReportRunner; scenario semantics clarified (cleanIdeal/matchedError/finalAllToggle); active-no-fixes from Stage 63 acknowledged and not treated as failure; Stage 61/62 quaternion covariance update-order preserved; full suite NOT RUN; v1 frozen as controlled internally consistent MATLAB EKF simulation demonstration'
                'Stage 65: lean final report and code cleanup; removed 13 stage-history/architecture chapter methods from ClockExactReportBuilder (~2530 lines deleted); suppressed ISL/multi-asset/signal-iono/carrier-track/troposphere/bias-architecture/disabled-components/attitude-observability chapters from PDF; added final-10%-zoom state-estimate plots (position, clock bias, clock drift, attitude); extracted Stage 64 Final Scientific Closure into standalone writeFinalScientificClosure_ method called directly from writeTexFile_; report structure now: scenario-summary, state-estimation(+zoom), measurement-validation, per-receiver, oscillator, clock-observability, tx-code-bias, numerical-summary, final-scientific-closure; simulation physics unchanged; no feature removed'
                'Stage 66: single-asset one-way realistic reverse-GNSS v1 closure; active main-script scenario reduced to one estimated spacecraft and one-way tower-to-space observables only; ISL/TWSTFT/two-way/multi-asset scaffolding removed from active configuration while preserving inactive future code paths in ConfigFactory; orbit-class configuration clarified (cfg.scenario.orbitClass=GEO default); final report states one-way code/carrier/Doppler models, active toggles, dynamics mode, clock/PCV/IF covariance assumptions, ambiguity status, and non-operational limitations; Stage 66 Single-Asset One-Way Scientific Closure section in PDF with nSpaceAssets=1, ISL/TWSTFT/two-way disabled flags; stale quaternion EKF missing-item corrected in README (quaternionErrorState added in Stage 61/62); README, ReportStatus, StageHistory, MainScriptValidationGate, and run_oo_reverse_gnss_report updated to Stage 66; validates with one 3600 s all-toggle run'
                'Stage 67: single-asset attitude, clock, and dynamics realism closure; (A) attitude estimator labelled as carrier lever-arm quaternion error-state EKF (Stages 61/62 nominal+delta_theta with Joseph posterior covariance reset); coarseBaselineIntegerSearch labelled optional initializer only; calibratedDifferentialAmbiguity labelled relative tracking only; cfg.estimator.attitude.primaryMode=carrierLeverArmQuaternionEkf added; (B) stochastic tower and receiver clocks replace perfect corrections; cfg.clock.receiver.deterministic=false; cfg.errors.towerClockCorrection.mode=noisyCorrection; tower clock deterministic=false set per-tower in ScenarioPresets; overlapping Allan deviation plot added to Oscillator Stability section; AllanDeviation class added with compute/getRxClockBiasTrue/getTowerClockBiasMatrix static methods; getRxClockBiasTrue getter added to Diagnostics; (C) matched twoBodyRk4 truth propagator + twoBody EKF dynamics replace static-ECEF truth; ScenarioPresets.singleAssetCarrierAttitude adds orbit.useOrbitPropagator=true, orbit.mode=twoBodyRk4, estimator.dynamics.mode=twoBody, GEO 35786 km equatorial; Stage 67 Attitude, Clock, and Dynamics Realism Closure section added to PDF with three compact tables plus Allan plot reference; stage67* summary fields in ReportRunner; validates with one 3600 s all-toggle run'
                'Stage 68: complete single-asset one-way physics closure; (A) PDF restructured: stage-titled science chapters removed; new non-stage-titled Simulation Physics and Configuration section added before Numerical Summary containing 6 compact tables (scenario topology, measurement model, atmosphere/antenna/bias, attitude, clocks, orbital dynamics) plus limitations list; Numerical Summary is now the final report section; (B) antenna PCO enabled by default (synthetic calibrated constants; no ANTEX); PCV default remains disabled; (C) troposphere (simpleMapped Saastamoinen-style, truth+model on) and ionosphere (simpleMapped 1/f^2, truth+model on) documented as active defaults; (D) stage68* summary fields added to ReportRunner capturing trop/iono/sagnac/PCO/PCV/hardware/multipath enable status; (E) Stage 67 non-perfect clocks, matched twoBodyRk4/twoBody dynamics, and quaternion EKF attitude all retained; (F) README stale static-ECEF text removed; all gate files updated to Stage 68; validates with one 3600 s all-toggle run'
                'Stage 69: fixes the active attitude solution by making raw L1 receiver-differenced carrier with calibrated body-frame lever arms the primary attitude measurement for the quaternion error-state EKF; disables coarse candidate search by default (attitudeInitMode=none); adds externalInitialAttitude calibration reference mode to DiffAttitudeBuilder so that delta_B is calibrated at the reference (truth+0.1 deg noise) attitude rather than the wrong initial EKF attitude, preventing calibration from absorbing the initial attitude error; adds primary-signal filter in DiffAttitudeBuilder.accumulate and buildRows so that only the lowest-signalIdx row per tower-antenna pair is used, fixing a silent zero-calibration bug that occurred with twoFrequency.enable=true (two L1+L2 rows per pair produced sum(mask)!=1 causing every pair to be skipped); in ReverseGNSSSimulation, the differential carrier input is switched to floatRows (raw L1) when IF combination is active so that DiffAtt always operates on raw L1 and not the IF-combined signal; updates position-error plot to show X/Y/Z ECEF components plus 3D norm from the existing getPositionErrorVecs() method; all gate files updated to Stage 69; validates with one 3600 s all-toggle run'
                'Stage 70: baseline carrier attitude integer ambiguity resolution; adds BaselineCarrierAmbiguityResolver helper (raw-L1 candidate search, RMS cost, ratio test) called from DiffAttitudeBuilder.finalize(); accumulates accumSumSq (sum of squares of ΔΦ−Δρ_ref) during calibration window for efficient closed-form cost evaluation; external initial attitude used only as search centre to produce N_float near the true integer, not as primary calibration source; if all baselines pass gates (rmsThreshold_cycles=0.10, ratioThreshold=2.0, minArcEpochs=10, searchHalfWidth=5) then delta_B=lambda_L1*N_int and externalReferenceUsedForCalibration=false; falls back to Stage 69 float calibration if fix fails; replaces Euler-angle perturbation Jacobian in DiffAttitudeBuilder.buildRows with LinkGeometry.finiteDiffAttitudeJacobian (quaternion error-state body-frame DCM perturbation) for correct ∂Δρ/∂δθ Jacobian in QES EKF mode; adds seven Stage 70 summary fields (baselineIntegerFixAttempted, baselineIntegerFixAccepted, nBaselineIntegerFixed, nBaselineIntegerRejected, baselineIntegerFixClassification, externalReferenceUsedAsSearchCenter, externalReferenceUsedForCalibration); updates attitude determination and limitations tables in Simulation Physics section; no new report chapters; all gate files updated to Stage 70; validates with one 3600 s all-toggle run'
                'Stage 71: replaces active truth-plus-noise tower clock correction with a synthetic product-prediction clock model using product epochs, latency, bias/drift prediction, product uncertainty, and deterministic per-product noise; keeps receiver clock bias/drift estimated by EKF while tower clocks are product-corrected rather than freely estimated to avoid gauge ambiguity; reports product age/sigma and shared-covariance status; propagates tower clock product prediction sigma into code and carrier measurement R (addToR=true); Doppler clock-drift sigma reported as simplified v1 and not added to Doppler R; fixes ConfigFactory mapping of truthHistoryProductNoisy to use correct internal mode instead of noisyCorrection; adds TowerClockCorrectionProvider.productNoise_ persistent-cache deterministic seeded noise so same product epoch always yields same correction within a run; adds eleven Stage 71 summary fields; updates clock model table and limitations in Simulation Physics section; preserves Allan deviation plot for asset and tower truth clocks; no real CLK ingestion, no operational timing claim; no new report chapters; all gate files updated to Stage 71; validates with one 3600 s all-toggle run'
                'Stage 73: implements model-step-compensated carrier cycle-slip detection and carrier-arc robustness for the single-asset one-way simulation; root cause of Stage 71/72 false-slip problem was that CycleSlipDetector compared raw consecutive prefit residuals without subtracting the known tower clock product model step, causing every 30 s product epoch boundary to appear as a cycle slip; Stage 73 introduces CycleSlipDetector.detectCompensated() which computes slipMetric = observedJump - expectedModelJump where expectedModelJump = towerClkModel_k - towerClkModel_{k-1}; slips are only declared when |slipMetric| >= threshold; tower clock model values are passed through CarrierMeasurementBuilder.cpInfo.towerClkModel_m per row and stored in CarrierTrackManager.prevTowerClkModel_m_ per track; product boundary events (|expectedJump| > 1mm after warmup) are counted separately from confirmed slips; DiffAtt baseline slip detection remains disabled per Stage 69 design (differential carrier cancels common tower clock; innovation gate is the only guard); ambiguity resets remain local to affected arcs; cfg.carrierSlip block added to run script with method=modelStepCompensatedResidualJump, productStepCompensation=true, syntheticSlipInjection.enable=false; Stage 73 summary fields added to ReportRunner and Numerical Summary; Stage 72 single-asset one-way product-clock setup, frozen report structure, and navigation performance preserved; validates with one 3600 s all-toggle run'
                'Stage 72: repairs Stage 71 clock-product navigation regression; identified actual root cause: each 30 s product-epoch boundary causes a step of (b_noise_new - b_noise_old) ~ N(0, sqrt(2)*sigmaBias) in the tower clock model correction; CycleSlipDetector compares consecutive pre-fit carrier residuals and flags jumps >= slipDetection.threshold_m (0.1 m) as cycle slips; with Stage 71 sigmaBias=0.05 m the jump RMS was 0.07 m giving ~15 percent false-slip rate per measurement per epoch change, causing cascading ambiguity resets every 30 s that prevented carrier phase convergence and left navigation dominated by code measurements (position error ~28 m); fix reduces sigmaBias to 0.01 m (0.033 ns, IGS-class product quality) so jump sigma is 0.014 m, seven sigma below threshold (false-slip probability ~1e-12); also corrects GroundTower history to seed t=0 initial state in constructor so clockAtProductEpoch(t_prod=0) always finds a valid history entry, and fixes the earliest-entry fallback in clockAtProductEpoch to use current tower state rather than projecting from a later history anchor with wrong age; moves Stage 71 summary field computation before PDF generation so product metadata is finite in the ClockExact report; updates gauge text from stale ''perfect truth subtracted'' to product-corrected description; sets towerClockSharedCovarianceApplied=false and towerClockProductDiagonalInflation=true (only diagonal per-row code-R inflation is implemented); preserves single-asset one-way scenario and frozen report structure; validates with one 3600 s all-toggle run'
            };
        end

        function list = missingScientificItems(~)
            % missingScientificItems  Not-implemented items that must not be claimed.
            % v1 is at Stage 73. These items are not implemented and must not be claimed.
            list = {
                'Full CI / full test-suite validation (current: targeted random smoke, 2-5 tests only; full suite NOT RUN)'
                'Calibrated antenna PCO/PCV and ANTEX hardware-bias products (default PCV=none; toy PCV is synthetic-only; geometry model is reference-point only)'
                'Production-grade quaternion attitude robustness: large-error injection bounding, ring-down prevention, and formal reset-transition validation (Stage 61 adds quaternionErrorState mode; Stage 62 fixes covariance reset ordering; production-grade injection clamping not implemented)'
                'Integer ambiguity fixing (LAMBDA/MLAMBDA, carrier-IF, wide-lane/narrow-lane): Stage 63 adds controlled raw-carrier fixing path; active-no-fixes in all-toggle run is correct (IF combination prevents individual L1 sigma convergence); LAMBDA/MLAMBDA, carrier-IF integer fixing, WL/NL, calibrated phase-bias products, and formal false-fix-risk control are NOT implemented'
                'Calibrated inter-frequency biases / DCB / differential phase biases (not modelled in v1)'
                'Simplified v1 Doppler only (LOS range-rate + rx/tower clock drift; no Sagnac-rate, no relativistic range-rate, no lever-arm velocity from body rates, no high-fidelity transmitter dynamics)'
                'IF covariance uses uncorrelated noise assumption (Var_IF=alpha^2*Var_L1+beta^2*Var_L2, Cov(L1,L2)=0); correlated dual-frequency noise modelling not implemented'
                'Monte Carlo / NIS / NEES stochastic consistency validation'
                'Scientific troposphere: Niell/GMF/VMF3/GPT3/ERA5 mapping functions'
                'Scientific ionosphere: Klobuchar/IONEX/higher-order ionosphere models'
                'Full IERS/EOP GCRS/ITRF reference-frame and Earth-orientation products'
                'Full relativistic GNSS clock modelling (Schwarzschild, gravitational redshift)'
                'Higher-fidelity orbit dynamics: drag, SRP, third bodies, precise orbit products'
                'Real TWSTFT / relay / transponder physics'
                'External GNSS product ingestion: SP3, CLK, RINEX, IONEX, ANTEX'
                'Operational navigation, precise orbit determination, mission-qualified attitude, or PPP-grade processing (v1 is a controlled EKF demonstration only)'
            };
        end

        function item = currentImplementedItem(stage)
            % currentImplementedItem  Return the single implemented-items entry for stage.
            all_ = revgnss.StageHistory.implementedItems();
            prefix = sprintf('Stage %d:', stage);
            for k = 1:numel(all_)
                if startsWith(all_{k}, prefix)
                    item = all_{k};
                    return
                end
            end
            item = sprintf('Stage %d: (no history entry found)', stage);
        end

    end
end
