classdef SynchronizedPairCorrectionMessage
    % SynchronizedPairCorrectionMessage  The "signed immutable correction message" plan Stage
    % 3.2 item 4 calls for: ONE object carrying BOTH endpoints' computed corrections, built ONCE
    % from the SAME shared innovation (items 2-3), with every affected pairwise cross block
    % precomputed (item 5). assemble() IS the atomicity gate: it either produces a message that
    % is fully applicable to both endpoints, or it throws and NOTHING is ever delivered -- there
    % is no partially-built message. "Signed" = revgnss.ImmutableContentDigest, a deterministic
    % integrity tag, not a cryptographic signature (see that class's header).
    %
    % This class computes and validates; it applies nothing (mirrors revgnss.
    % DistributedPairCovarianceUpdateResult's own discipline). Application happens only via
    % revgnss.SynchronizedPairLinkUpdateTransaction after BOTH endpoints acknowledge.

    properties (SetAccess = immutable)
        messageIdentifier               (1,:) char
        messageSignature_hex            (1,:) char
        messageSignaturePolicy          (1,:) char
        issuerIdentifier                (1,:) char
        protocolSchemaVersion           (1,:) char
        stateSchemaVersion              (1,:) char
        observationIdentifier           (1,:) char
        deliveryIdentifier              (1,:) char
        sessionIdentifier               (1,:) char
        observableIdentifier            (1,:) char
        observableRowUnits              (1,:) char
        coordinateEventEpoch_s          (1,1) double
        deliveryEpoch_s                 (1,1) double
        sourceEpoch_s                   (1,1) double
        networkRevisionNumberAtAssembly (1,1) double
        partialDeliveryPolicy           (1,:) char
        thirdMemberCrossConditioning    (1,:) char

        residual_rowUnit                (:,1) double
        innovationCovariance_rowUnit2   (:,:) double
        normalizedInnovationSquared     (1,1) double
        pairUpdateResult

        ownerEndpointCorrection         (1,1) struct
        remoteEndpointCorrection        (1,1) struct

        crossBlockCorrections           (1,:) struct
        untouchedCrossBlockIdentifiers  (1,:) cell
        thirdMemberOmissionAudit        (1,1) struct
    end

    methods (Access = private)
        function obj = SynchronizedPairCorrectionMessage(record)
            required = {'messageIdentifier','messageSignature_hex','messageSignaturePolicy', ...
                'issuerIdentifier','protocolSchemaVersion','stateSchemaVersion', ...
                'observationIdentifier','deliveryIdentifier','sessionIdentifier', ...
                'observableIdentifier','observableRowUnits','coordinateEventEpoch_s', ...
                'deliveryEpoch_s','sourceEpoch_s','networkRevisionNumberAtAssembly', ...
                'partialDeliveryPolicy','thirdMemberCrossConditioning','residual_rowUnit', ...
                'innovationCovariance_rowUnit2','normalizedInnovationSquared','pairUpdateResult', ...
                'ownerEndpointCorrection','remoteEndpointCorrection','crossBlockCorrections', ...
                'untouchedCrossBlockIdentifiers','thirdMemberOmissionAudit'};
            supplied = fieldnames(record);
            missing = setdiff(required,supplied);
            unknown = setdiff(supplied,required);
            if ~isempty(missing)
                error('SynchronizedPairCorrectionMessage:missingField', ...
                    'SynchronizedPairCorrectionMessage is missing %s.',missing{1});
            end
            if ~isempty(unknown)
                error('SynchronizedPairCorrectionMessage:unknownField', ...
                    'SynchronizedPairCorrectionMessage contains unsupported field %s.',unknown{1});
            end
            if ~isa(record.pairUpdateResult,'revgnss.DistributedPairCovarianceUpdateResult')
                error('SynchronizedPairCorrectionMessage:pairUpdateResultType', ...
                    'pairUpdateResult must be a revgnss.DistributedPairCovarianceUpdateResult.');
            end
            for index = 1:numel(required)
                name = required{index};
                obj.(name) = record.(name);
            end
        end
    end

    methods
        function corr = correctionForEndpoint(obj, endpointIdentifier)
            id = char(endpointIdentifier);
            if strcmp(id,obj.ownerEndpointCorrection.endpointIdentifier)
                corr = obj.ownerEndpointCorrection;
            elseif strcmp(id,obj.remoteEndpointCorrection.endpointIdentifier)
                corr = obj.remoteEndpointCorrection;
            else
                error('SynchronizedPairCorrectionMessage:endpointNotAddressed', ...
                    'This message does not address endpoint %s.',id);
            end
        end

        function tf = coversPair(obj, firstId, secondId)
            ids = {obj.ownerEndpointCorrection.endpointIdentifier, ...
                obj.remoteEndpointCorrection.endpointIdentifier};
            tf = any(strcmp(ids,char(firstId))) && any(strcmp(ids,char(secondId)));
        end

        function s = provenanceSummary(obj)
            s = struct( ...
                'messageIdentifier',obj.messageIdentifier, ...
                'observationIdentifier',obj.observationIdentifier, ...
                'observableIdentifier',obj.observableIdentifier, ...
                'ownerEndpointIdentifier',obj.ownerEndpointCorrection.endpointIdentifier, ...
                'remoteEndpointIdentifier',obj.remoteEndpointCorrection.endpointIdentifier, ...
                'coordinateEventEpoch_s',obj.coordinateEventEpoch_s, ...
                'crossBlockCorrectionCount',numel(obj.crossBlockCorrections), ...
                'thirdMemberOmissionAudit',obj.thirdMemberOmissionAudit);
        end
    end

    methods (Static)
        function message = assemble(assembleArgs)
            required = {'observationIdentifier','deliveryIdentifier','sessionIdentifier', ...
                'observableIdentifier','observableRowUnits','coordinateEventEpoch_s', ...
                'deliveryEpoch_s','sourceEpoch_s','issuerIdentifier','partialDeliveryPolicy', ...
                'messageSignaturePolicy','thirdMemberCrossConditioning','ownerEndpoint', ...
                'remoteEndpoint','ownerJacobian_mPerErrorUnit','remoteJacobian_mPerErrorUnit', ...
                'independentMeasurementCovariance_m2','residual_m','priorPairCrossCovariance', ...
                'thirdMembers','networkRevisionNumber','clockClaim','pairAbsolutelyAnchored'};
            supplied = fieldnames(assembleArgs);
            missing = setdiff(required,supplied);
            unknown = setdiff(supplied,required);
            if ~isempty(missing)
                error('SynchronizedPairCorrectionMessage:assembleArgsSchema', ...
                    'assemble is missing %s.',missing{1});
            end
            if ~isempty(unknown)
                error('SynchronizedPairCorrectionMessage:assembleArgsSchema', ...
                    'assemble received unsupported field %s.',unknown{1});
            end

            % --- 1. schema / vocabulary / gauge checks --------------------------------------
            if ~revgnss.SynchronizedDeliveryContract.isPairExactEligibleObservable( ...
                    assembleArgs.observableIdentifier)
                error('SynchronizedPairCorrectionMessage:observableNotEligible', ...
                    'Observable %s is not pair-exact eligible.',char(assembleArgs.observableIdentifier));
            end
            if strcmp(char(assembleArgs.clockClaim),'relativeBiasOnly') && ...
                    ~logical(assembleArgs.pairAbsolutelyAnchored)
                error('SynchronizedPairCorrectionMessage:clockGaugeNotAnchored', ...
                    ['A relative-bias-only, unanchored clock claim cannot drive a pair-exact ' ...
                    'update: the exact update moves the remote''s clock states too, and an ' ...
                    'unanchored pair would move an unobservable gauge direction on both endpoints.']);
            end
            owner = assembleArgs.ownerEndpoint;
            remote = assembleArgs.remoteEndpoint;
            revgnss.SynchronizedPairCorrectionMessage.requireEndpointRecord_(owner,'ownerEndpoint');
            revgnss.SynchronizedPairCorrectionMessage.requireEndpointRecord_(remote,'remoteEndpoint');
            if ~strcmp(owner.stateSchemaVersion,remote.stateSchemaVersion) || ...
                    ~strcmp(owner.stateSchemaVersion,revgnss.DistributedLinkProtocolContract.StateSchemaVersion)
                error('SynchronizedPairCorrectionMessage:stateSchemaVersionMismatch', ...
                    'Both endpoints must declare the frozen Stage-2 v1 state schema version.');
            end

            % --- 2. zero-pad the schema-local Jacobians onto each endpoint's OWN full span --
            Hi = zeros(size(assembleArgs.ownerJacobian_mPerErrorUnit,1),owner.localStateDimension);
            Hi(:,owner.schemaStateIndices) = assembleArgs.ownerJacobian_mPerErrorUnit;
            Hj = zeros(size(assembleArgs.remoteJacobian_mPerErrorUnit,1),remote.localStateDimension);
            Hj(:,remote.schemaStateIndices) = assembleArgs.remoteJacobian_mPerErrorUnit;
            if size(assembleArgs.priorPairCrossCovariance,1) ~= owner.localStateDimension || ...
                    size(assembleArgs.priorPairCrossCovariance,2) ~= remote.localStateDimension
                error('SynchronizedPairCorrectionMessage:crossCovarianceDimension', ...
                    'priorPairCrossCovariance must be ownerLocalStateDimension-by-remoteLocalStateDimension.');
            end

            % --- 3. the pair-exact primitive (3.1, unmodified) -------------------------------
            primitiveRecord = struct( ...
                'observationIdentifier',assembleArgs.observationIdentifier, ...
                'deliveryIdentifier',assembleArgs.deliveryIdentifier, ...
                'observableIdentifier',assembleArgs.observableIdentifier, ...
                'observableRowUnits',assembleArgs.observableRowUnits, ...
                'ownerEndpointIdentifier',owner.identifier, ...
                'remoteEndpointIdentifier',remote.identifier, ...
                'coordinateEventEpoch_s',assembleArgs.coordinateEventEpoch_s, ...
                'Hi',Hi,'Hj',Hj, ...
                'Pii',owner.PPrior,'Pij',assembleArgs.priorPairCrossCovariance,'Pjj',remote.PPrior, ...
                'R',assembleArgs.independentMeasurementCovariance_m2, ...
                'residual',assembleArgs.residual_m);
            pairResult = revgnss.DistributedCovarianceNetwork.pairMeasurementUpdatePrimitive(primitiveRecord);

            % --- 4. per-endpoint attitude injection/reset ------------------------------------
            ownerInjected = revgnss.LocalStateCorrectionInjection.applyWithAttitudeReset(struct( ...
                'xPrior',owner.xPrior,'PPosterior',pairResult.ownerPosteriorLocalCovariance, ...
                'schemaStateIndices',owner.schemaStateIndices, ...
                'stateCorrection_full',pairResult.ownerStateCorrection_errorUnit, ...
                'attitudeParameterization',owner.attitudeParameterization, ...
                'nominalQuatPrior',owner.nominalQuatPrior));
            remoteInjected = revgnss.LocalStateCorrectionInjection.applyWithAttitudeReset(struct( ...
                'xPrior',remote.xPrior,'PPosterior',pairResult.remotePosteriorLocalCovariance, ...
                'schemaStateIndices',remote.schemaStateIndices, ...
                'stateCorrection_full',pairResult.remoteStateCorrection_errorUnit, ...
                'attitudeParameterization',remote.attitudeParameterization, ...
                'nominalQuatPrior',remote.nominalQuatPrior));

            % --- 5. attitude-reset congruence on the pair cross block, re-check PSD ----------
            PijPosterior = revgnss.DistributedCovarianceNetwork.applyAttitudeResetCongruenceToPairCross( ...
                pairResult.posteriorCrossCovariance,ownerInjected.attitudeResetJacobian, ...
                remoteInjected.attitudeResetJacobian,owner.schemaStateIndices,remote.schemaStateIndices);
            revgnss.SynchronizedPairCorrectionMessage.requireSymmetricPsd_( ...
                ownerInjected.PPosterior,'ownerEndpointCorrection.PPosterior');
            revgnss.SynchronizedPairCorrectionMessage.requireSymmetricPsd_( ...
                remoteInjected.PPosterior,'remoteEndpointCorrection.PPosterior');

            % --- 6. third-member cross-block conditioning, ALL simultaneously ----------------
            thirdMembers = assembleArgs.thirdMembers;
            nThird = numel(thirdMembers);
            crossBlockCorrections = struct('firstEndpointIdentifier',{},'secondEndpointIdentifier',{}, ...
                'posteriorCrossCovariance',{},'transformKind',{});
            crossBlockCorrections(1) = struct('firstEndpointIdentifier',owner.identifier, ...
                'secondEndpointIdentifier',remote.identifier,'posteriorCrossCovariance',PijPosterior, ...
                'transformKind','pairExactDirect');
            if nThird > 0
                thirdRecord = struct( ...
                    'Hi',Hi,'Hj',Hj,'Ki',pairResult.ownerGain_errorUnitPerRowUnit, ...
                    'Kj',pairResult.remoteGain_errorUnitPerRowUnit, ...
                    'Gi',ownerInjected.attitudeResetJacobian,'Gj',remoteInjected.attitudeResetJacobian, ...
                    'ownerSchemaStateIndices',owner.schemaStateIndices, ...
                    'remoteSchemaStateIndices',remote.schemaStateIndices, ...
                    'Pik',{{thirdMembers.priorCrossToOwner}},'Pjk',{{thirdMembers.priorCrossToRemote}});
                [PikPlus, PjkPlus] = revgnss.DistributedCovarianceNetwork.pairExactThirdMemberCrossTransforms( ...
                    thirdRecord);
                for k = 1:nThird
                    crossBlockCorrections(end+1) = struct( ...  %#ok<AGROW>
                        'firstEndpointIdentifier',owner.identifier, ...
                        'secondEndpointIdentifier',thirdMembers(k).endpointIdentifier, ...
                        'posteriorCrossCovariance',PikPlus{k},'transformKind','pairExactThirdMember');
                    crossBlockCorrections(end+1) = struct( ...  %#ok<AGROW>
                        'firstEndpointIdentifier',remote.identifier, ...
                        'secondEndpointIdentifier',thirdMembers(k).endpointIdentifier, ...
                        'posteriorCrossCovariance',PjkPlus{k},'transformKind','pairExactThirdMember');
                end
            end

            % --- 7. third-member omitted-correction audit ------------------------------------
            if nThird > 0
                auditRecord = struct('S',pairResult.innovationCovariance_rowUnit2,'Hi',Hi,'Hj',Hj, ...
                    'Pki',{{thirdMembers.priorCrossToOwner}},'Pkj',{{thirdMembers.priorCrossToRemote}}, ...
                    'Pkk',{{thirdMembers.localMarginal}}, ...
                    'endpointIdentifiers',{{thirdMembers.endpointIdentifier}});
                thirdMemberOmissionAudit = ...
                    revgnss.DistributedCovarianceNetwork.thirdMemberOmittedCorrectionAudit(auditRecord);
            else
                thirdMemberOmissionAudit = struct('endpointIdentifiers',{{}},'ratios',[],'isNegligible',true);
            end

            % --- 8. finiteness sweep ----------------------------------------------------------
            revgnss.SynchronizedPairCorrectionMessage.requireAllFinite_(ownerInjected.xPosterior,'owner x+');
            revgnss.SynchronizedPairCorrectionMessage.requireAllFinite_(ownerInjected.PPosterior,'owner P+');
            revgnss.SynchronizedPairCorrectionMessage.requireAllFinite_(remoteInjected.xPosterior,'remote x+');
            revgnss.SynchronizedPairCorrectionMessage.requireAllFinite_(remoteInjected.PPosterior,'remote P+');
            for index = 1:numel(crossBlockCorrections)
                revgnss.SynchronizedPairCorrectionMessage.requireAllFinite_( ...
                    crossBlockCorrections(index).posteriorCrossCovariance, ...
                    sprintf('cross block %d',index));
            end

            % --- 9. compute the signature; construct -----------------------------------------
            messageIdentifier = sprintf('correction:%s',char(assembleArgs.observationIdentifier));
            ownerCorrection = revgnss.SynchronizedPairCorrectionMessage.endpointCorrectionStruct_( ...
                owner,'owner',ownerInjected);
            remoteCorrection = revgnss.SynchronizedPairCorrectionMessage.endpointCorrectionStruct_( ...
                remote,'remote',remoteInjected);

            record = struct( ...
                'messageIdentifier',messageIdentifier, ...
                'messageSignaturePolicy',char(assembleArgs.messageSignaturePolicy), ...
                'issuerIdentifier',char(assembleArgs.issuerIdentifier), ...
                'protocolSchemaVersion',revgnss.SynchronizedDeliveryContract.ProtocolSchemaVersion, ...
                'stateSchemaVersion',owner.stateSchemaVersion, ...
                'observationIdentifier',char(assembleArgs.observationIdentifier), ...
                'deliveryIdentifier',char(assembleArgs.deliveryIdentifier), ...
                'sessionIdentifier',char(assembleArgs.sessionIdentifier), ...
                'observableIdentifier',char(assembleArgs.observableIdentifier), ...
                'observableRowUnits',char(assembleArgs.observableRowUnits), ...
                'coordinateEventEpoch_s',assembleArgs.coordinateEventEpoch_s, ...
                'deliveryEpoch_s',assembleArgs.deliveryEpoch_s, ...
                'sourceEpoch_s',assembleArgs.sourceEpoch_s, ...
                'networkRevisionNumberAtAssembly',assembleArgs.networkRevisionNumber, ...
                'partialDeliveryPolicy',char(assembleArgs.partialDeliveryPolicy), ...
                'thirdMemberCrossConditioning',char(assembleArgs.thirdMemberCrossConditioning), ...
                'residual_rowUnit',assembleArgs.residual_m(:), ...
                'innovationCovariance_rowUnit2',pairResult.innovationCovariance_rowUnit2, ...
                'normalizedInnovationSquared',pairResult.normalizedInnovationSquared, ...
                'pairUpdateResult',pairResult, ...
                'ownerEndpointCorrection',ownerCorrection, ...
                'remoteEndpointCorrection',remoteCorrection, ...
                'crossBlockCorrections',crossBlockCorrections, ...
                'untouchedCrossBlockIdentifiers',{{}}, ...
                'thirdMemberOmissionAudit',thirdMemberOmissionAudit);

            payloadForSignature = rmfield(record,{'pairUpdateResult'});
            payloadForSignature.pairUpdateResultDigestSeed = struct( ...
                'S',pairResult.innovationCovariance_rowUnit2, ...
                'ownerPosterior',pairResult.ownerPosteriorLocalCovariance, ...
                'remotePosterior',pairResult.remotePosteriorLocalCovariance);
            record.messageSignature_hex = revgnss.ImmutableContentDigest.of(payloadForSignature);

            message = revgnss.SynchronizedPairCorrectionMessage(record);
        end

        function hex = signatureFor(payloadStruct)
            hex = revgnss.ImmutableContentDigest.of(payloadStruct);
        end

        function requireIntact(message)
            if ~isa(message,'revgnss.SynchronizedPairCorrectionMessage')
                error('SynchronizedPairCorrectionMessage:messageType', ...
                    'requireIntact requires a revgnss.SynchronizedPairCorrectionMessage.');
            end
            recomputed = revgnss.SynchronizedPairCorrectionMessage.recomputeSignature_(message);
            if ~strcmp(recomputed,message.messageSignature_hex)
                error('SynchronizedPairCorrectionMessage:messageSignatureInvalid', ...
                    'The message content digest does not match its declared signature.');
            end
        end

        function message = fromRecordWithDeclaredSignature(record, declaredSignature_hex)
            % fromRecordWithDeclaredSignature  The ONLY way to construct a message carrying a
            % signature that may not match its own payload -- used exclusively to test tamper
            % detection (the class is otherwise immutable and always self-signs at assemble()).
            % Deliberately does NOT call requireIntact: doing so would reject exactly the
            % mismatched-signature message this factory exists to produce, making tamper
            % detection structurally untestable (Section 3.2 review finding B4). The caller is
            % expected to pass the result to requireIntact/prepareAcknowledgement itself and
            % assert that THEY reject it.
            record.messageSignature_hex = char(declaredSignature_hex);
            message = revgnss.SynchronizedPairCorrectionMessage(record);
        end

        function requireApplicableNow(message, networkRevisionNumber)
            if ~isa(message,'revgnss.SynchronizedPairCorrectionMessage')
                error('SynchronizedPairCorrectionMessage:messageType', ...
                    'requireApplicableNow requires a revgnss.SynchronizedPairCorrectionMessage.');
            end
            if message.networkRevisionNumberAtAssembly ~= networkRevisionNumber
                error('SynchronizedPairCorrectionMessage:staleNetworkRevision', ...
                    'The network has advanced since this message was assembled.');
            end
        end
    end

    methods (Static, Access = private)
        function requireEndpointRecord_(endpoint, name)
            required = {'identifier','canonicalPhysicalAssetIndex','localStateDimension', ...
                'schemaStateIndices','localStateMapFingerprint','attitudeParameterization', ...
                'attitudeErrorCoordinateConvention','xPrior','PPrior','nominalQuatPrior', ...
                'priorStateDigest_hex','stateSchemaVersion'};
            supplied = fieldnames(endpoint);
            missing = setdiff(required,supplied);
            if ~isempty(missing)
                error('SynchronizedPairCorrectionMessage:endpointRecordSchema', ...
                    '%s is missing %s.',name,missing{1});
            end
        end

        function corr = endpointCorrectionStruct_(endpoint, role, injected)
            % endpointCorrectionStruct_  Uses injected.PPosterior (the POST-attitude-reset-
            % congruence covariance LocalStateCorrectionInjection.applyWithAttitudeReset already
            % computed) for BOTH the delivered PPosterior field and the PSD/minimum-eigenvalue
            % figure below -- never the raw pre-reset pairResult.*PosteriorLocalCovariance, which
            % is expressed about the OLD nominal quaternion while xPosterior/nominalQuatPosterior
            % (also from injected) are already expressed about the NEW one. Using the raw value
            % here would ship a state/covariance pair with an internally inconsistent attitude
            % reference in quaternionErrorState mode (the masterConfig default) -- see the
            % Section 3.2 review finding B1.
            corr = struct( ...
                'endpointIdentifier',endpoint.identifier, ...
                'endpointRole',role, ...
                'canonicalPhysicalAssetIndex',endpoint.canonicalPhysicalAssetIndex, ...
                'localStateDimension',endpoint.localStateDimension, ...
                'schemaStateIndices',endpoint.schemaStateIndices, ...
                'localStateMapFingerprint',endpoint.localStateMapFingerprint, ...
                'attitudeParameterization',endpoint.attitudeParameterization, ...
                'attitudeErrorCoordinateConvention',endpoint.attitudeErrorCoordinateConvention, ...
                'priorStateDigest_hex',endpoint.priorStateDigest_hex, ...
                'stateCorrection_errorUnit',injected.xPosterior-endpoint.xPrior, ...
                'xPosterior',injected.xPosterior, ...
                'PPosterior',injected.PPosterior, ...
                'nominalQuatPosterior',injected.nominalQuatPosterior, ...
                'attitudeResetJacobian',injected.attitudeResetJacobian, ...
                'attitudeInjectionNorm_rad',injected.attitudeInjectionNorm_rad, ...
                'posteriorMinimumScaledEigenvalue', ...
                    revgnss.SynchronizedPairCorrectionMessage.minimumScaledEigenvalue_(injected.PPosterior));
        end

        function requireSymmetricPsd_(M, contextName)
            if any(~isfinite(M(:)))
                error('SynchronizedPairCorrectionMessage:nonFiniteCorrection', ...
                    '%s is not finite.',contextName);
            end
            if norm(M-M','fro') > revgnss.SynchronizedDeliveryContract.PosteriorSymmetryToleranceRelative* ...
                    max(1,norm(M,'fro'))
                error('SynchronizedPairCorrectionMessage:posteriorNotSymmetricPositiveSemiDefinite', ...
                    '%s is not symmetric.',contextName);
            end
            if revgnss.SynchronizedPairCorrectionMessage.minimumScaledEigenvalue_(M) < ...
                    -revgnss.SynchronizedDeliveryContract.PosteriorEigenvalueToleranceScaled
                error('SynchronizedPairCorrectionMessage:posteriorNotSymmetricPositiveSemiDefinite', ...
                    '%s is not positive semi-definite.',contextName);
            end
        end

        function e = minimumScaledEigenvalue_(M)
            D = sqrt(max(diag(M),0));
            D(D==0) = 1;
            Dinv = diag(1./D);
            scaled = Dinv*M*Dinv;
            scaled = (scaled+scaled')/2;
            e = min(eig(scaled));
        end

        function requireAllFinite_(M, contextName)
            if any(~isfinite(M(:)))
                error('SynchronizedPairCorrectionMessage:nonFiniteCorrection', ...
                    '%s contains a non-finite value.',contextName);
            end
        end

        function hex = recomputeSignature_(message)
            record = struct( ...
                'messageIdentifier',message.messageIdentifier, ...
                'messageSignaturePolicy',message.messageSignaturePolicy, ...
                'issuerIdentifier',message.issuerIdentifier, ...
                'protocolSchemaVersion',message.protocolSchemaVersion, ...
                'stateSchemaVersion',message.stateSchemaVersion, ...
                'observationIdentifier',message.observationIdentifier, ...
                'deliveryIdentifier',message.deliveryIdentifier, ...
                'sessionIdentifier',message.sessionIdentifier, ...
                'observableIdentifier',message.observableIdentifier, ...
                'observableRowUnits',message.observableRowUnits, ...
                'coordinateEventEpoch_s',message.coordinateEventEpoch_s, ...
                'deliveryEpoch_s',message.deliveryEpoch_s, ...
                'sourceEpoch_s',message.sourceEpoch_s, ...
                'networkRevisionNumberAtAssembly',message.networkRevisionNumberAtAssembly, ...
                'partialDeliveryPolicy',message.partialDeliveryPolicy, ...
                'thirdMemberCrossConditioning',message.thirdMemberCrossConditioning, ...
                'residual_rowUnit',message.residual_rowUnit, ...
                'innovationCovariance_rowUnit2',message.innovationCovariance_rowUnit2, ...
                'normalizedInnovationSquared',message.normalizedInnovationSquared, ...
                'ownerEndpointCorrection',message.ownerEndpointCorrection, ...
                'remoteEndpointCorrection',message.remoteEndpointCorrection, ...
                'crossBlockCorrections',message.crossBlockCorrections, ...
                'untouchedCrossBlockIdentifiers',{message.untouchedCrossBlockIdentifiers}, ...
                'thirdMemberOmissionAudit',message.thirdMemberOmissionAudit);
            payloadForSignature = record;
            payloadForSignature.pairUpdateResultDigestSeed = struct( ...
                'S',message.pairUpdateResult.innovationCovariance_rowUnit2, ...
                'ownerPosterior',message.pairUpdateResult.ownerPosteriorLocalCovariance, ...
                'remotePosterior',message.pairUpdateResult.remotePosteriorLocalCovariance);
            hex = revgnss.ImmutableContentDigest.of(payloadForSignature);
        end
    end
end
