classdef TwoWayISLMeasurementBuilder
    % TwoWayISLMeasurementBuilder  Coherent four-event PN two-way ranging.

    properties (Constant)
        C_mps = 299792458
        Protocol = 'coherentTranspondedPnTwoWayCode'
    end

    methods (Static)
        function validateConfig(cfg)
            parentEnabled = revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','enable'},false);
            rangeEnabled = revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','range','enable'},false);
            useRange = revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','range','useInEKF'},false);
            dopplerRequested = ...
                revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','doppler','enable'},false) || ...
                revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','doppler','useInEKF'},false);
            if (rangeEnabled || useRange || dopplerRequested) && ~parentEnabled
                error('TwoWayISLMeasurementBuilder:twoWayParentDisabled', ...
                    'Two-way code and Doppler require twoWay.enable=true.');
            end
            if useRange && ~rangeEnabled
                error('TwoWayISLMeasurementBuilder:rangeUseGuard', ...
                    'twoWay.range.useInEKF requires twoWay.range.enable=true.');
            end
            if dopplerRequested
                error('TwoWayISLMeasurementBuilder:dopplerUnavailable', ...
                    'Coherent two-way Doppler is not implemented and must remain disabled.');
            end
            if ~rangeEnabled
                return
            end
            if ~revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                    cfg,{'measurements','isl','enable'},false)
                error('TwoWayISLMeasurementBuilder:parentDisabled', ...
                    'The coherent two-way link requires measurements.isl.enable=true.');
            end
            nAssets = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'scenario','nSpaceAssets'},1);
            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            remoteIdx = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','transmitterAssetIndex'},2);
            initiatorIdx = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','receiverAssetIndex'},1);
            if isempty(links) && (nAssets < 2 || remoteIdx < 1 || remoteIdx > nAssets || ...
                    initiatorIdx < 1 || initiatorIdx > nAssets || ...
                    initiatorIdx == remoteIdx)
                error('TwoWayISLMeasurementBuilder:endpoints', ...
                    'A coherent two-way link requires two distinct configured spacecraft.');
            end
            protocol = revgnss.TwoWayISLMeasurementBuilder.getStr_( ...
                cfg,{'measurements','isl','twoWay','protocol'}, ...
                revgnss.TwoWayISLMeasurementBuilder.Protocol);
            if ~strcmp(protocol,revgnss.TwoWayISLMeasurementBuilder.Protocol)
                error('TwoWayISLMeasurementBuilder:protocol', ...
                    'Only coherentTranspondedPnTwoWayCode is implemented.');
            end
            revgnss.TwoWayISLMeasurementBuilder.terminalGeometry_(cfg,1);
            codeRatio = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','codeRateTurnaroundRatio'},1);
            if codeRatio ~= 1
                error('TwoWayISLMeasurementBuilder:codeRateRatio', ...
                    'Coherent tracked PN ranging requires codeRateTurnaroundRatio=1.');
            end
            forwardFrequency = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','forwardCarrierFrequency_Hz'},NaN);
            returnFrequency = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','returnCarrierFrequency_Hz'},NaN);
            carrierRatio = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','carrierFrequencyTurnaroundRatio'},NaN);
            if ~(isfinite(forwardFrequency) && forwardFrequency > 0 && ...
                    isfinite(returnFrequency) && returnFrequency > 0 && ...
                    isfinite(carrierRatio) && carrierRatio > 0)
                error('TwoWayISLMeasurementBuilder:carrierFrequency', ...
                    'Forward/return carrier frequencies and turnaround ratio must be positive.');
            end
            if abs(returnFrequency-forwardFrequency*carrierRatio) > ...
                    1e-12*max(returnFrequency,forwardFrequency)
                error('TwoWayISLMeasurementBuilder:carrierFrequencyRatio', ...
                    ['returnCarrierFrequency_Hz must equal forwardCarrierFrequency_Hz ' ...
                     'times carrierFrequencyTurnaroundRatio.']);
            end
            linkModel = revgnss.TwoWayISLMeasurementBuilder.getStr_( ...
                cfg,{'measurements','isl','twoWay','range','linkBudget','model'},'fixed');
            if ~ismember(linkModel,{'fixed','linkBudget','physicalRF'})
                error('TwoWayISLMeasurementBuilder:linkModel', ...
                    'Two-way code link model must be fixed, linkBudget, or physicalRF.');
            end
            plasmaEnabled = revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','range','plasma','enable'},false);
            if plasmaEnabled && ~strcmp(linkModel,'physicalRF')
                error('TwoWayISLMeasurementBuilder:plasmaRequiresPhysicalRF', ...
                    'ISL plasma group delay requires range.linkBudget.model=''physicalRF''.');
            end
            if plasmaEnabled
                truthTec = [ ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','range','plasma','truthForwardTEC_electrons_per_m2'},0), ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','range','plasma','truthReturnTEC_electrons_per_m2'},0)];
                modelTec = [ ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','range','plasma','estimatorForwardTEC_electrons_per_m2'},0), ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','range','plasma','estimatorReturnTEC_electrons_per_m2'},0)];
                residualSigma = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','range','plasma','residualSigma_m'},0);
                if any(~isfinite([truthTec,modelTec,residualSigma])) || ...
                        any([truthTec,modelTec,residualSigma] < 0)
                    error('TwoWayISLMeasurementBuilder:plasmaParameters', ...
                        'TEC values and plasma residual sigma must be finite and nonnegative.');
                end
                if all(truthTec == modelTec) && residualSigma == 0
                    error('TwoWayISLMeasurementBuilder:plasmaTruthModelSeparation', ...
                        ['An enabled plasma truth model must use an independent estimator ' ...
                         'correction or a nonzero residual uncertainty.']);
                end
            end
            if strcmp(linkModel,'physicalRF')
                validationDistance = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                    cfg,{'measurements','isl','twoWay','range','linkBudget', ...
                    'validationDistance_m'},1e5);
                revgnss.TwoWayISLMeasurementBuilder.rfModels_( ...
                    cfg,validationDistance);
            end
            minimumTrackingCn0 = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','range','tracking', ...
                'minimumCarrierToNoiseDensity_dBHz'},25);
            if ~(isscalar(minimumTrackingCn0) && isfinite(minimumTrackingCn0))
                error('TwoWayISLMeasurementBuilder:trackingThreshold', ...
                    'The two-way tracking C/N0 threshold must be finite.');
            end
            updatePeriod = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','schedule','updatePeriod_s'},1);
            updatePhase = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','schedule','updatePhase_s'},0);
            dt_s = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'simulation','dt_s'},1);
            if ~(isfinite(updatePeriod) && updatePeriod > 0 && ...
                    isfinite(updatePhase) && updatePhase >= 0 && ...
                    updatePhase < updatePeriod)
                error('TwoWayISLMeasurementBuilder:schedule', ...
                    'Two-way update period and phase define an invalid schedule.');
            end
            if abs(updatePeriod/dt_s-round(updatePeriod/dt_s)) > 1e-10 || ...
                    abs(updatePhase/dt_s-round(updatePhase/dt_s)) > 1e-10
                error('TwoWayISLMeasurementBuilder:scheduleGrid', ...
                    'Two-way update period and phase must align with simulation.dt_s.');
            end
            revgnss.TwoWayISLMeasurementBuilder.validateLinkDefinitions_( ...
                cfg,links,nAssets,updatePeriod,dt_s);
            outages = revgnss.TwoWayISLMeasurementBuilder.walk_(cfg, ...
                {'measurements','isl','twoWay','schedule','outages_s'},zeros(0,2));
            if ~(isnumeric(outages) && size(outages,2) == 2 && ...
                    all(isfinite(outages(:))) && all(outages(:,2) >= outages(:,1)))
                error('TwoWayISLMeasurementBuilder:scheduleOutages', ...
                    'twoWay.schedule.outages_s must be a finite N-by-2 interval matrix.');
            end
            if useRange
                mode = revgnss.TwoWayISLMeasurementBuilder.getStr_( ...
                    cfg,{'multiAsset','mode'},'fast');
                if ~strcmp(mode,'joint')
                    error('TwoWayISLMeasurementBuilder:jointEstimatorRequired', ...
                        ['A physical two-way range must update both endpoints. Set ' ...
                         'multiAsset.mode=''joint'' or keep range.useInEKF=false.']);
                end
            end
            stencil = revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                {'measurements','isl','twoWay','range','linearization', ...
                'stencil'},'fivePoint');
            if ~strcmp(stencil,'fivePoint')
                error('TwoWayISLMeasurementBuilder:linearizationStencil', ...
                    'The coherent two-way row uses the validated fivePoint stencil.');
            end
            stepPaths = { ...
                'positionStep_m','velocityStep_mps','attitudeStep_rad', ...
                'clockBiasStep_m','clockDriftStep_mps'};
            for stepIndex = 1:numel(stepPaths)
                stepValue = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','range','linearization', ...
                    stepPaths{stepIndex}},NaN);
                if ~(isscalar(stepValue) && isfinite(stepValue) && stepValue > 0)
                    error('TwoWayISLMeasurementBuilder:linearizationStep', ...
                        'Every two-way linearization step must be positive and finite.');
                end
            end
            turnaroundError_s = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','truth', ...
                'turnaroundCalibrationError_s'},0);
            terminalError_s = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','truth', ...
                'terminalCalibrationError_s'},0);
            turnaroundSigma_s = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','calibration', ...
                'turnaroundSigma_s'},0);
            terminalSigma_s = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','calibration', ...
                'terminalSigma_s'},0);
            biasStateEnabled = revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','calibration', ...
                'residualBiasState','enable'},false);
            biasProcessSigma = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','calibration', ...
                'residualBiasState','processNoiseSigma_m_per_sqrt_s'},0);
            calibrationCorrelationModel = ...
                revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                {'measurements','isl','twoWay','calibration', ...
                'errorCorrelationModel'},'independentPhysicalChains');
            if ~strcmp(calibrationCorrelationModel,'independentPhysicalChains')
                error('TwoWayISLMeasurementBuilder:sharedCalibrationUnavailable', ...
                    ['Only independent physical-chain calibration states are active. ' ...
                     'Shared terminal calibration requires shared nuisance states.']);
            end
            calibrationValues = [turnaroundError_s,terminalError_s, ...
                turnaroundSigma_s,terminalSigma_s,biasProcessSigma];
            if any(~isfinite(calibrationValues)) || ...
                    any(calibrationValues(3:5) < 0)
                error('TwoWayISLMeasurementBuilder:calibrationParameters', ...
                    'Two-way calibration values must be finite and sigmas nonnegative.');
            end
            validFrom = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','calibration', ...
                'validFromLocalTag_s'},0);
            validUntil = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','calibration', ...
                'validUntilLocalTag_s'},1e12);
            if ~(isfinite(validFrom) && isfinite(validUntil) && ...
                    validUntil >= validFrom)
                error('TwoWayISLMeasurementBuilder:calibrationValidity', ...
                    'The two-way calibration validity interval is invalid.');
            end
            if biasStateEnabled && (~useRange || ...
                    hypot(turnaroundSigma_s,terminalSigma_s) == 0)
                error('TwoWayISLMeasurementBuilder:calibrationBiasState', ...
                    ['The calibration residual-bias state requires an active EKF range ' ...
                     'and nonzero calibration uncertainty.']);
            end
            persistentCalibration = any(calibrationValues(1:4) ~= 0);
            if useRange && persistentCalibration && ~biasStateEnabled
                error('TwoWayISLMeasurementBuilder:persistentCalibrationRequiresState', ...
                    ['A recurring calibration error or uncertainty must use the ' ...
                     'persistent residual-bias state; it cannot be repeated as white R.']);
            end
        end

        function links = linkDefinitions(cfg)
            links = revgnss.TwoWayISLMeasurementBuilder.walk_(cfg, ...
                {'measurements','isl','twoWay','links'},struct([]));
            if isempty(links)
                links = struct([]);
                return
            end
            if ~isstruct(links) || ~isfield(links,'enable')
                error('TwoWayISLMeasurementBuilder:linkDefinitions', ...
                    'twoWay.links must be a struct array with an enable field.');
            end
            enabled = false(1,numel(links));
            for linkIndex = 1:numel(links)
                value = links(linkIndex).enable;
                if ~(islogical(value) && isscalar(value))
                    error('TwoWayISLMeasurementBuilder:linkEnable', ...
                        'Each two-way link enable field must be a logical scalar.');
                end
                enabled(linkIndex) = value;
            end
            links = links(enabled);
        end

        function identifiers = calibrationLinkIdentifiers(cfg)
            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            if isempty(links)
                identifiers = {revgnss.TwoWayISLMeasurementBuilder.getStr_( ...
                    cfg,{'measurements','isl','twoWay','linkIdentifier'}, ...
                    'isl-two-way-code-link-A1-A2')};
                return
            end
            identifiers = arrayfun(@(link) char(link.linkIdentifier),links, ...
                'UniformOutput',false);
        end

        function [zAdd,hAdd,HAdd,RAdd,info] = build( ...
                cfg,primaryAsset,assets,x,stateMap,nx,t_s)
            if nargin < 7; t_s = 0; end
            [observation,truthDiagnostic,info] = ...
                revgnss.TwoWayISLMeasurementBuilder.generateObservation( ...
                cfg,primaryAsset,assets,t_s);
            if isempty(observation)
                zAdd = []; hAdd = []; HAdd = zeros(0,nx); RAdd = zeros(0);
                return
            end
            [zAdd,hAdd,HAdd,RAdd,info] = ...
                revgnss.TwoWayISLMeasurementBuilder.linearizeRecordedObservation( ...
                cfg,observation,x,stateMap,nx,t_s,info);
            info.truthDiagnostic = truthDiagnostic;
        end

        function [observations,truthDiagnostics,info] = ...
                generateObservations(cfg,primaryAsset,assets,t_s)
            if nargin < 4; t_s = 0; end
            observations = {};
            truthDiagnostics = {};
            linkInfos = {};
            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            if isempty(links)
                [observation,diagnostic,linkInfo] = ...
                    revgnss.TwoWayISLMeasurementBuilder.generateObservation( ...
                    cfg,primaryAsset,assets,t_s);
                linkInfo.linkDefinitionIndex = 0;
                if ~isempty(observation)
                    observations = {observation};
                    truthDiagnostics = {diagnostic};
                    linkInfos = {linkInfo};
                end
            else
                for linkIndex = 1:numel(links)
                    linkCfg = revgnss.TwoWayISLMeasurementBuilder. ...
                        configForLink_(cfg,links(linkIndex));
                    [observation,diagnostic,linkInfo] = ...
                        revgnss.TwoWayISLMeasurementBuilder.generateObservation( ...
                        linkCfg,primaryAsset,assets,t_s);
                    linkInfo.linkDefinitionIndex = linkIndex;
                    if isempty(observation); continue; end
                    observations{end+1} = observation; %#ok<AGROW>
                    truthDiagnostics{end+1} = diagnostic; %#ok<AGROW>
                    linkInfos{end+1} = linkInfo; %#ok<AGROW>
                end
            end
            info = revgnss.TwoWayISLMeasurementBuilder.aggregateInfo_( ...
                cfg,assets,linkInfos,observations);
        end

        function [zAdd,hAdd,HAdd,RAdd,info] = ...
                linearizeRecordedObservations( ...
                cfg,observations,x,stateMap,nx,t_s,info)
            if nargin < 7 || isempty(info)
                reconstructedInfos = cell(1,numel(observations));
                for observationIndex = 1:numel(observations)
                    reconstructedInfos{observationIndex} = ...
                        revgnss.TwoWayISLMeasurementBuilder. ...
                        infoForObservation_(cfg,observations{observationIndex});
                end
                info = revgnss.TwoWayISLMeasurementBuilder.aggregateInfo_( ...
                    cfg,{},reconstructedInfos,observations);
            end
            if ~iscell(observations)
                error('TwoWayISLMeasurementBuilder:observationCollection', ...
                    'Plural recorded-observation processing requires a cell array.');
            end
            if ~isfield(info,'linkInfos') || ...
                    numel(info.linkInfos) ~= numel(observations)
                error('TwoWayISLMeasurementBuilder:observationInfoCount', ...
                    'Every recorded observation requires its generation metadata.');
            end

            zAdd = [];
            hAdd = [];
            HAdd = zeros(0,nx);
            RAdd = zeros(0);
            processedInfos = cell(1,numel(observations));
            for observationIndex = 1:numel(observations)
                linkInfo = info.linkInfos{observationIndex};
                linkInfo.truthDiagnostic = [];
                linkCfg = revgnss.TwoWayISLMeasurementBuilder. ...
                    configForInfo_(cfg,linkInfo);
                [zLink,hLink,HLink,RLink,linkInfo] = ...
                    revgnss.TwoWayISLMeasurementBuilder. ...
                    linearizeRecordedObservation( ...
                    linkCfg,observations{observationIndex},x,stateMap,nx, ...
                    t_s,linkInfo);
                processedInfos{observationIndex} = linkInfo;
                if isempty(zLink); continue; end
                zAdd = [zAdd;zLink]; %#ok<AGROW>
                hAdd = [hAdd;hLink]; %#ok<AGROW>
                HAdd = [HAdd;HLink]; %#ok<AGROW>
                RAdd = blkdiag(RAdd,RLink);
            end
            info = revgnss.TwoWayISLMeasurementBuilder.aggregateInfo_( ...
                cfg,{},processedInfos,observations);
            info.zEkf = zAdd;
            info.hEkf = hAdd;
            if ~isempty(zAdd)
                info.prefitRms = sqrt(mean((zAdd-hAdd).^2));
            end
        end

        function [observation,truthDiagnostic,info] = generateObservation( ...
                cfg,primaryAsset,assets,t_s)
            if nargin < 4; t_s = 0; end
            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            if ~isempty(links)
                cfg = revgnss.TwoWayISLMeasurementBuilder. ...
                    configForLink_(cfg,links(1));
            end
            observation = [];
            truthDiagnostic = [];
            info = revgnss.TwoWayISLMeasurementBuilder.defaultInfo(cfg,assets);
            [info.scheduled,info.scheduleStatus] = ...
                revgnss.TwoWayISLMeasurementBuilder.scheduleStatus_(cfg,t_s);
            info.nRangeRows = double(info.rangeEnabled && info.scheduled);
            if ~info.enabled || ~info.rangeEnabled || ~info.scheduled; return; end

            initiator = assets{info.receiverAssetIndex};
            transponder = assets{info.transmitterAssetIndex};
            if info.receiverAssetIndex == 1; initiator = primaryAsset; end

            truthInitiator = revgnss.TwoWayISLMeasurementBuilder.truthEndpoint_( ...
                cfg,initiator,info.receiverAssetIndex,t_s);
            truthTransponder = revgnss.TwoWayISLMeasurementBuilder.truthEndpoint_( ...
                cfg,transponder,info.transmitterAssetIndex,t_s);
            [physicalHardware,calibrationProduct] = ...
                revgnss.TwoWayISLMeasurementBuilder.hardwareModels_(cfg);
            info.physicalChainIdentifier = ...
                physicalHardware.physicalChainIdentifier;
            info.calibrationProductIdentifier = ...
                calibrationProduct.calibrationProductIdentifier;

            events = revgnss.CoherentTwoWayCodeRangingModel. ...
                solvePhysicalEventGeometry( ...
                truthInitiator,truthTransponder,physicalHardware,t_s,struct());
            legDistances_m = [events.forwardRange_m,events.returnRange_m];
            representativeDistance_m = mean(legDistances_m);
            [rfTruth,rfEstimator] = ...
                revgnss.TwoWayISLMeasurementBuilder.rfModels_(cfg,legDistances_m);
            if isempty(rfTruth)
                thermalSigma = revgnss.TwoWayISLMeasurementBuilder.rangeSigma_( ...
                    cfg,representativeDistance_m);
                physicalPropagationDelay_s = 0;
                modeledPropagationDelay_s = 0;
                measuredCn0_dBHz = info.carrierToNoiseDensity_dBHz;
                effectiveBandwidth_Hz = NaN;
            else
                thermalSigma = rfTruth.codeRangeSigma_m;
                physicalPropagationDelay_s = ...
                    (rfTruth.forward.plasmaGroupDelay_m + ...
                    rfTruth.return.plasmaGroupDelay_m)/ ...
                    revgnss.TwoWayISLMeasurementBuilder.C_mps;
                modeledPropagationDelay_s = ...
                    (rfEstimator.forward.plasmaGroupDelay_m + ...
                    rfEstimator.return.plasmaGroupDelay_m)/ ...
                    revgnss.TwoWayISLMeasurementBuilder.C_mps;
                measuredCn0_dBHz = rfTruth.roundTripLimitingCN0_dBHz;
                effectiveBandwidth_Hz = min( ...
                    rfTruth.forward.rangingBandwidth_Hz, ...
                    rfTruth.return.rangingBandwidth_Hz);
            end
            minimumTrackingCn0 = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','range','tracking', ...
                'minimumCarrierToNoiseDensity_dBHz'},25);
            enforceTrackingThreshold = ...
                revgnss.TwoWayISLMeasurementBuilder.getBool_(cfg, ...
                {'measurements','isl','twoWay','range','tracking', ...
                'enforceThreshold'},false);
            if isnan(measuredCn0_dBHz)
                linkMargin_dB = NaN;
                trackingAvailable = true;
            else
                linkMargin_dB = measuredCn0_dBHz-minimumTrackingCn0;
                trackingAvailable = ~enforceTrackingThreshold || linkMargin_dB >= 0;
            end
            calibrationVariance = ...
                revgnss.TwoWayISLMeasurementBuilder.calibrationVariance_m2_( ...
                calibrationProduct);
            biasStateEnabled = revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','calibration', ...
                'residualBiasState','enable'},false);
            plasmaResidualSigma = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','range','plasma','residualSigma_m'},0);
            observationVariance = thermalSigma^2 + plasmaResidualSigma^2;
            if ~biasStateEnabled
                observationVariance = observationVariance + calibrationVariance;
            end
            epochIdx = round(t_s/max( ...
                revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'simulation','dt_s'},1),eps));
            trackingError_s = 2*thermalSigma/ ...
                revgnss.TwoWayISLMeasurementBuilder.C_mps * ...
                revgnss.TwoWayISLMeasurementBuilder.drawNormal_( ...
                cfg,info.receiverAssetIndex,info.transmitterAssetIndex,epochIdx);
            observationId = sprintf('%s:code:e%09d', ...
                info.linkIdentifier,epochIdx);
            metadata = struct( ...
                'observationIdentifier',observationId, ...
                'sessionIdentifier',sprintf('%s:session:e%09d', ...
                    info.linkIdentifier,epochIdx), ...
                'signalIdentifier',info.signalIdentifier, ...
                'channelIdentifier', ...
                    revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                    {'measurements','isl','twoWay','channelIdentifier'},'PN-1'), ...
                'forwardCarrierFrequency_Hz', ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay', ...
                    'forwardCarrierFrequency_Hz'},NaN), ...
                'returnCarrierFrequency_Hz', ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay', ...
                    'returnCarrierFrequency_Hz'},NaN), ...
                'covarianceGroupIdentifier',observationId, ...
                'covarianceRowIndex',1, ...
                'covarianceBlock_m2',observationVariance, ...
                'carrierToNoiseDensity_dBHz',measuredCn0_dBHz, ...
                'effectiveRangingBandwidth_Hz',effectiveBandwidth_Hz, ...
                'roundTripLinkMargin_dB',linkMargin_dB, ...
                'additionalCalibrationProductIdentifiers',{ ...
                    revgnss.TwoWayISLMeasurementBuilder. ...
                    phaseCentreCalibrationIdentifiers_(cfg, ...
                    info.receiverAssetIndex,info.transmitterAssetIndex)}, ...
                'localTimeSystemIdentifier', ...
                    revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                    {'measurements','isl','twoWay','localTimeSystemIdentifier'}, ...
                    'initiatorOnboardClock'), ...
                'timestampReferencePointIdentifier', ...
                    revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                    {'measurements','isl','twoWay', ...
                    'timestampReferencePointIdentifier'}, ...
                    'initiatorReceiveTerminal'), ...
                'commandedScheduleIdentifier', ...
                    revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                    {'measurements','isl','twoWay','schedule', ...
                    'commandIdentifier'},'open-loop-scenario-schedule'), ...
                'available',trackingAvailable, ...
                'qualityFlags',struct( ...
                    'trackingLocked',trackingAvailable, ...
                    'calibrationValid',true, ...
                    'pointingCommanded',true, ...
                    'pointingModelApplied',false, ...
                    'lineOfSightClear',true, ...
                    'commandSource', ...
                        revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                        {'measurements','isl','twoWay','schedule', ...
                        'commandSource'},'scenarioOpenLoop')), ...
                'truthDiagnosticIdentifier',[observationId '-truth']);
            [observation,truthDiagnostic] = ...
                revgnss.CoherentTwoWayCodeRangingModel.simulateObservation( ...
                truthInitiator,truthTransponder,physicalHardware, ...
                calibrationProduct,t_s,metadata,trackingError_s,struct(), ...
                physicalPropagationDelay_s);

            info.observationRecord = observation;
            info.truthDiagnostic = truthDiagnostic;
            info.protocol = observation.protocolIdentifier;
            info.referenceEpochRule = observation.referenceEpochRule;
            info.rangeSigma_m = sqrt(observationVariance);
            info.thermalSigma_m = thermalSigma;
            info.calibrationSigma_m = sqrt(calibrationVariance);
            if biasStateEnabled
                info.calibrationUncertaintyTreatment = ...
                    'estimatedPersistentResidualBias';
            elseif calibrationVariance > 0
                info.calibrationUncertaintyTreatment = ...
                    'diagnosticMeasurementCovariance';
            else
                info.calibrationUncertaintyTreatment = 'none';
            end
            info.plasmaResidualSigma_m = plasmaResidualSigma;
            info.physicalPropagationGroupDelay_s = physicalPropagationDelay_s;
            info.modeledPropagationGroupDelay_s = modeledPropagationDelay_s;
            info.carrierToNoiseDensity_dBHz = measuredCn0_dBHz;
            info.effectiveRangingBandwidth_Hz = effectiveBandwidth_Hz;
            info.roundTripLinkMargin_dB = linkMargin_dB;
            info.trackingAvailable = trackingAvailable;
            info.rfLinkTruth = rfTruth;
            info.rfLinkEstimator = rfEstimator;
            info.linkEvents = revgnss.TwoWayISLMeasurementBuilder.linkEvents_( ...
                truthDiagnostic,initiator,transponder,info);
        end

        function [zAdd,hAdd,HAdd,RAdd,info] = ...
                linearizeRecordedObservation( ...
                cfg,observation,x,stateMap,nx,t_s,info)
            if nargin < 7 || isempty(info)
                info = revgnss.TwoWayISLMeasurementBuilder.defaultInfo(cfg,{});
                info.receiverAssetIndex = ...
                    revgnss.TwoWayISLMeasurementBuilder.assetIndexFromIdentifier_( ...
                    observation.initiatorAssetIdentifier);
                info.transmitterAssetIndex = ...
                    revgnss.TwoWayISLMeasurementBuilder.assetIndexFromIdentifier_( ...
                    observation.transponderAssetIdentifier);
                info.linkIdentifier = ...
                    revgnss.TwoWayISLMeasurementBuilder. ...
                    linkIdentifierFromObservation_(observation);
            end
            if nargin < 6 || ~(isscalar(t_s) && isfinite(t_s))
                error('TwoWayISLMeasurementBuilder:predictionEpoch', ...
                    'Recorded-observation processing requires a finite coordinate epoch.');
            end
            if ~isa(observation,'revgnss.InterSatelliteObservationRecord')
                error('TwoWayISLMeasurementBuilder:observationType', ...
                    'Processing requires an immutable inter-satellite observation record.');
            end
            if ~isfield(info,'linkIdentifier') || isempty(info.linkIdentifier)
                info.linkIdentifier = ...
                    revgnss.TwoWayISLMeasurementBuilder. ...
                    linkIdentifierFromObservation_(observation);
            end
            if ~isempty(revgnss.TwoWayISLMeasurementBuilder. ...
                    linkDefinitions(cfg))
                cfg = revgnss.TwoWayISLMeasurementBuilder. ...
                    configForInfo_(cfg,info);
            end
            if nargin < 5 || isempty(nx); nx = numel(x); end
            if numel(x) ~= nx
                error('TwoWayISLMeasurementBuilder:stateDimension', ...
                    'The supplied state dimension does not match the estimator state.');
            end
            info.observationRecord = observation;
            info.protocol = observation.protocolIdentifier;
            info.referenceEpochRule = observation.referenceEpochRule;
            info.rangeSigma_m = sqrt(observation.covarianceBlock( ...
                observation.covarianceRowIndex,observation.covarianceRowIndex));
            info.carrierToNoiseDensity_dBHz = ...
                observation.carrierToNoiseDensity_dBHz;
            info.effectiveRangingBandwidth_Hz = ...
                observation.effectiveRangingBandwidth_Hz;
            info.roundTripLinkMargin_dB = observation.roundTripLinkMargin_dB;
            info.trackingAvailable = observation.available;

            zAdd = []; hAdd = []; HAdd = zeros(0,nx); RAdd = zeros(0);
            if info.rangeUseInEKF && observation.available
                initiatorBlock = revgnss.AssetStateBlock.forAsset( ...
                    stateMap,info.receiverAssetIndex);
                transponderBlock = revgnss.AssetStateBlock.forAsset( ...
                    stateMap,info.transmitterAssetIndex);
                if isempty(initiatorBlock.r) || isempty(transponderBlock.r)
                    error('TwoWayISLMeasurementBuilder:endpointState', ...
                        'Both coherent-ranging endpoints must be estimated states.');
                end
                [~,calibrationProduct] = ...
                    revgnss.TwoWayISLMeasurementBuilder.hardwareModels_(cfg);
                if ~any(strcmp(observation.calibrationProductIdentifiers, ...
                        calibrationProduct.calibrationProductIdentifier))
                    error('TwoWayISLMeasurementBuilder:calibrationIdentity', ...
                        'The configured calibration product does not match the observation.');
                end
                predictedRange = ...
                    revgnss.TwoWayISLMeasurementBuilder.predictFromState_( ...
                    cfg,observation,calibrationProduct,x,stateMap,info,t_s);
                Hrow = revgnss.TwoWayISLMeasurementBuilder.finiteDifferenceRow_( ...
                    cfg,observation,calibrationProduct,x,stateMap,info,t_s,nx);
                biasStateEnabled = ...
                    revgnss.TwoWayISLMeasurementBuilder.getBool_(cfg, ...
                    {'measurements','isl','twoWay','calibration', ...
                    'residualBiasState','enable'},false);
                if biasStateEnabled
                    biasIndex = revgnss.TwoWayISLMeasurementBuilder. ...
                        calibrationBiasIndex_(stateMap,info.linkIdentifier);
                    Hrow(biasIndex) = 1;
                end
                zAdd = observation.processedValue;
                hAdd = predictedRange;
                HAdd = Hrow;
                RAdd = observation.covarianceBlock( ...
                    observation.covarianceRowIndex, ...
                    observation.covarianceRowIndex);
                info = revgnss.TwoWayISLMeasurementBuilder.addMeta_( ...
                    info,Hrow,true,stateMap);
            else
                info = revgnss.TwoWayISLMeasurementBuilder.addMeta_( ...
                    info,[],false,stateMap);
            end
            info.zEkf = zAdd;
            info.hEkf = hAdd;
            if ~isempty(zAdd); info.prefitRms = abs(zAdd-hAdd); end
        end

        function h = predictEkfRows(cfg,~,assets,x,stateMap,info,t_s)
            h = [];
            if isstruct(info) && isfield(info,'linkInfos')
                for linkIndex = 1:numel(info.linkInfos)
                    linkInfo = info.linkInfos{linkIndex};
                    if ~isfield(linkInfo,'observationRecord') || ...
                            isempty(linkInfo.observationRecord) || ...
                            ~linkInfo.rangeUseInEKF || linkInfo.nEkfRows < 1
                        continue
                    end
                    linkCfg = revgnss.TwoWayISLMeasurementBuilder. ...
                        configForInfo_(cfg,linkInfo);
                    [~,calibration] = ...
                        revgnss.TwoWayISLMeasurementBuilder. ...
                        hardwareModels_(linkCfg);
                    h(end+1,1) = ... %#ok<AGROW>
                        revgnss.TwoWayISLMeasurementBuilder.predictFromState_( ...
                        linkCfg,linkInfo.observationRecord,calibration,x, ...
                        stateMap,linkInfo,t_s);
                end
                if isempty(assets); h = []; end
                return
            end
            if isempty(info) || ~isfield(info,'observationRecord') || ...
                    isempty(info.observationRecord) || ~info.rangeUseInEKF
                return
            end
            if ~(isscalar(t_s) && isfinite(t_s))
                error('TwoWayISLMeasurementBuilder:predictionEpoch', ...
                    'Postfit prediction requires the estimator coordinate epoch.');
            end
            [~,calibration] = revgnss.TwoWayISLMeasurementBuilder.hardwareModels_(cfg);
            h = revgnss.TwoWayISLMeasurementBuilder.predictFromState_( ...
                cfg,info.observationRecord,calibration,x,stateMap,info,t_s);
            if isempty(assets); h = []; end
        end

        function info = defaultInfo(cfg,assets)
            info = struct();
            info.enabled = revgnss.TwoWayISLMeasurementBuilder.isEnabled_(cfg);
            info.transmitterAssetIndex = ...
                revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','transmitterAssetIndex'},2);
            info.receiverAssetIndex = ...
                revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','receiverAssetIndex'},1);
            info.transmitterAssetName = '';
            info.receiverAssetName = '';
            if info.enabled && numel(assets) >= max( ...
                    info.transmitterAssetIndex,info.receiverAssetIndex)
                info.transmitterAssetName = assets{info.transmitterAssetIndex}.name;
                info.receiverAssetName = assets{info.receiverAssetIndex}.name;
            end
            info.rangeEnabled = revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','range','enable'},false);
            info.rangeUseInEKF = revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','range','useInEKF'},false);
            info.dopplerEnabled = false;
            info.dopplerUseInEKF = false;
            info.linkIdentifier = ...
                revgnss.TwoWayISLMeasurementBuilder.getStr_( ...
                cfg,{'measurements','isl','twoWay','linkIdentifier'}, ...
                sprintf('isl-two-way-code-link-A%d-A%d', ...
                info.receiverAssetIndex,info.transmitterAssetIndex));
            info.signalIdentifier = revgnss.TwoWayISLMeasurementBuilder.getStr_( ...
                cfg,{'measurements','isl','twoWay','signalIdentifier'},'ISL-PN');
            info.carrierToNoiseDensity_dBHz = ...
                revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                    cfg,{'measurements','isl','twoWay','carrierToNoiseDensity_dBHz'},NaN);
            info.effectiveRangingBandwidth_Hz = NaN;
            info.roundTripLinkMargin_dB = NaN;
            info.trackingAvailable = false;
            info.clockCancellation = ...
                ['Initiator clock offset cancels in its local round-trip interval; ' ...
                 'clock rate, motion, phase centres, and calibrated delays remain.'];
            info.rows = struct([]);
            info.ekfRowTypes = {};
            info.nRangeRows = double(info.rangeEnabled);
            info.nDopplerDiagnosticRows = 0;
            info.nEkfRows = 0;
            info.prefitRms = NaN;
            info.linkEvents = struct([]);
            info.observationRecord = [];
            info.truthDiagnostic = [];
            info.physicalChainIdentifier = '';
            info.calibrationProductIdentifier = '';
            info.rfLinkTruth = [];
            info.rfLinkEstimator = [];
            info.physicalPropagationGroupDelay_s = 0;
            info.modeledPropagationGroupDelay_s = 0;
            info.plasmaResidualSigma_m = 0;
            info.calibrationUncertaintyTreatment = 'none';
            info.scheduled = false;
            info.scheduleStatus = 'notEvaluated';
        end

        function calibrationProduct = calibrationProductForLinkDefinitionIndex(cfg, linkDefinitionIndex)
            % calibrationProductForLinkDefinitionIndex  Pure exposure (plan Section 2.3.1): the
            % SAME per-link calibration resolution generateObservations/configForLink_ already
            % perform internally (calibration.productIdentifier is overridden per link), exposed
            % so a distributed-link-update caller can resolve the identical calibration product
            % for a link record without re-deriving configForLink_/hardwareModels_, both private
            % to this class. linkDefinitionIndex==0 (or the legacy no-links path) resolves the
            % top-level cfg unchanged, matching generateObservation's own linkDefinitionIndex=0
            % convention. No existing call site changes; this method calls the same private
            % helpers unmodified.
            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            if isnumeric(linkDefinitionIndex) && isscalar(linkDefinitionIndex) && ...
                    linkDefinitionIndex >= 1 && linkDefinitionIndex <= numel(links)
                cfg = revgnss.TwoWayISLMeasurementBuilder.configForLink_( ...
                    cfg,links(linkDefinitionIndex));
            end
            [~,calibrationProduct] = revgnss.TwoWayISLMeasurementBuilder.hardwareModels_(cfg);
        end
    end

    methods (Static, Access = private)
        function validateLinkDefinitions_(cfg,links,nAssets,period_s,dt_s)
            if isempty(links); return; end
            required = {'linkIdentifier','initiatorAssetIndex', ...
                'transponderAssetIndex','physicalChainIdentifier', ...
                'calibrationProductIdentifier','signalIdentifier', ...
                'channelIdentifier','schedule'};
            identifiers = cell(1,numel(links));
            chainIdentifiers = cell(1,numel(links));
            calibrationIdentifiers = cell(1,numel(links));
            commandIdentifiers = cell(1,numel(links));
            phases_s = zeros(1,numel(links));
            endpoints = zeros(numel(links),2);
            for linkIndex = 1:numel(links)
                missing = setdiff(required,fieldnames(links(linkIndex)));
                if ~isempty(missing)
                    error('TwoWayISLMeasurementBuilder:linkField', ...
                        'Two-way link %d is missing field %s.', ...
                        linkIndex,missing{1});
                end
                endpoints(linkIndex,:) = [ ...
                    links(linkIndex).initiatorAssetIndex, ...
                    links(linkIndex).transponderAssetIndex];
                if any(~isfinite(endpoints(linkIndex,:))) || ...
                        any(endpoints(linkIndex,:) ~= ...
                        round(endpoints(linkIndex,:))) || ...
                        any(endpoints(linkIndex,:) < 1) || ...
                        any(endpoints(linkIndex,:) > nAssets) || ...
                        endpoints(linkIndex,1) == endpoints(linkIndex,2)
                    error('TwoWayISLMeasurementBuilder:linkEndpoints', ...
                        'Each enabled two-way link requires two distinct spacecraft indices.');
                end
                identifiers{linkIndex} = ...
                    revgnss.TwoWayISLMeasurementBuilder.textField_( ...
                    links(linkIndex),'linkIdentifier',linkIndex);
                chainIdentifiers{linkIndex} = ...
                    revgnss.TwoWayISLMeasurementBuilder.textField_( ...
                    links(linkIndex),'physicalChainIdentifier',linkIndex);
                calibrationIdentifiers{linkIndex} = ...
                    revgnss.TwoWayISLMeasurementBuilder.textField_( ...
                    links(linkIndex),'calibrationProductIdentifier',linkIndex);
                revgnss.TwoWayISLMeasurementBuilder.textField_( ...
                    links(linkIndex),'signalIdentifier',linkIndex);
                revgnss.TwoWayISLMeasurementBuilder.textField_( ...
                    links(linkIndex),'channelIdentifier',linkIndex);
                if ~isstruct(links(linkIndex).schedule) || ...
                        ~isfield(links(linkIndex).schedule,'updatePhase_s') || ...
                        ~isfield(links(linkIndex).schedule,'commandIdentifier')
                    error('TwoWayISLMeasurementBuilder:linkSchedule', ...
                        'Each enabled link requires a phase and command identifier.');
                end
                phases_s(linkIndex) = ...
                    links(linkIndex).schedule.updatePhase_s;
                if ~(isscalar(phases_s(linkIndex)) && ...
                        isfinite(phases_s(linkIndex)) && ...
                        phases_s(linkIndex) >= 0 && ...
                        phases_s(linkIndex) < period_s)
                    error('TwoWayISLMeasurementBuilder:linkSchedule', ...
                        'Each link phase must be in [0, updatePeriod_s).');
                end
                if abs(phases_s(linkIndex)/dt_s - ...
                        round(phases_s(linkIndex)/dt_s)) > 1e-10
                    error('TwoWayISLMeasurementBuilder:linkScheduleGrid', ...
                        'Each link phase must align with simulation.dt_s.');
                end
                commandIdentifiers{linkIndex} = ...
                    revgnss.TwoWayISLMeasurementBuilder.textField_( ...
                    links(linkIndex).schedule,'commandIdentifier',linkIndex);
                linkCalibrationErrors = [ ...
                    links(linkIndex).turnaroundCalibrationError_s, ...
                    links(linkIndex).terminalCalibrationError_s];
                if any(~isfinite(linkCalibrationErrors))
                    error('TwoWayISLMeasurementBuilder:linkCalibrationError', ...
                        'Each link calibration error must be finite.');
                end
            end
            revgnss.TwoWayISLMeasurementBuilder.assertUniqueText_( ...
                identifiers,'linkIdentifier');
            revgnss.TwoWayISLMeasurementBuilder.assertUniqueText_( ...
                chainIdentifiers,'physicalChainIdentifier');
            revgnss.TwoWayISLMeasurementBuilder.assertUniqueText_( ...
                calibrationIdentifiers,'calibrationProductIdentifier');
            revgnss.TwoWayISLMeasurementBuilder.assertUniqueText_( ...
                commandIdentifiers,'schedule.commandIdentifier');

            physicalPairs = sort(endpoints,2);
            if size(unique(physicalPairs,'rows'),1) ~= size(physicalPairs,1)
                error('TwoWayISLMeasurementBuilder:duplicatePhysicalLink', ...
                    'A physical spacecraft pair may be declared only once.');
            end
            tolerance = 10*eps(max(1,period_s));
            for firstIndex = 1:numel(links)-1
                for secondIndex = firstIndex+1:numel(links)
                    shareTerminal = any(ismember( ...
                        endpoints(firstIndex,:),endpoints(secondIndex,:)));
                    sameEpoch = abs(phases_s(firstIndex)- ...
                        phases_s(secondIndex)) <= tolerance;
                    if shareTerminal && sameEpoch
                        error('TwoWayISLMeasurementBuilder:terminalScheduleConflict', ...
                            ['Links %s and %s command the same spacecraft terminal ' ...
                             'at the same epoch phase.'], ...
                            identifiers{firstIndex},identifiers{secondIndex});
                    end
                end
            end
            if ~strcmp(revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                    {'measurements','isl','twoWay','schedule','commandSource'},''), ...
                    'scenarioOpenLoop')
                error('TwoWayISLMeasurementBuilder:scheduleCommandSource', ...
                    'Declared fleet links require commandSource=scenarioOpenLoop.');
            end
        end

        function cfg = configForLink_(cfg,link)
            cfg.measurements.isl.receiverAssetIndex = ...
                link.initiatorAssetIndex;
            cfg.measurements.isl.transmitterAssetIndex = ...
                link.transponderAssetIndex;
            cfg.measurements.isl.twoWay.linkIdentifier = ...
                char(link.linkIdentifier);
            cfg.measurements.isl.twoWay.physicalChainIdentifier = ...
                char(link.physicalChainIdentifier);
            cfg.measurements.isl.twoWay.calibration.productIdentifier = ...
                char(link.calibrationProductIdentifier);
            cfg.measurements.isl.twoWay.truth.turnaroundCalibrationError_s = ...
                link.turnaroundCalibrationError_s;
            cfg.measurements.isl.twoWay.truth.terminalCalibrationError_s = ...
                link.terminalCalibrationError_s;
            cfg.measurements.isl.twoWay.signalIdentifier = ...
                char(link.signalIdentifier);
            cfg.measurements.isl.twoWay.channelIdentifier = ...
                char(link.channelIdentifier);
            cfg.measurements.isl.twoWay.schedule.updatePhase_s = ...
                link.schedule.updatePhase_s;
            cfg.measurements.isl.twoWay.schedule.commandIdentifier = ...
                char(link.schedule.commandIdentifier);
            cfg.measurements.isl.twoWay.links = struct([]);
        end

        function cfg = configForInfo_(cfg,info)
            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            if isempty(links); return; end
            linkIndex = 0;
            if isfield(info,'linkDefinitionIndex') && ...
                    isscalar(info.linkDefinitionIndex)
                linkIndex = info.linkDefinitionIndex;
            end
            if linkIndex < 1 || linkIndex > numel(links)
                linkIndex = find(strcmp( ...
                    {links.linkIdentifier},info.linkIdentifier),1);
            end
            if isempty(linkIndex) || linkIndex < 1 || linkIndex > numel(links)
                error('TwoWayISLMeasurementBuilder:linkIdentity', ...
                    'Recorded observation link %s is not declared.', ...
                    info.linkIdentifier);
            end
            cfg = revgnss.TwoWayISLMeasurementBuilder. ...
                configForLink_(cfg,links(linkIndex));
        end

        function info = aggregateInfo_(cfg,assets,linkInfos,observations)
            if isempty(linkInfos)
                info = revgnss.TwoWayISLMeasurementBuilder.defaultInfo(cfg,assets);
            else
                info = linkInfos{1};
            end
            info.linkInfos = linkInfos;
            info.observationRecords = observations;
            info.eligibleObservationRecords = {};
            info.linkIdentifiers = {};
            info.rows = struct([]);
            info.ekfRowTypes = {};
            info.linkEvents = struct([]);
            info.nRangeRows = 0;
            info.nEkfRows = 0;
            for linkIndex = 1:numel(linkInfos)
                linkInfo = linkInfos{linkIndex};
                info.linkIdentifiers{end+1} = ...
                    linkInfo.linkIdentifier; %#ok<AGROW>
                info.nRangeRows = info.nRangeRows + linkInfo.nRangeRows;
                info.nEkfRows = info.nEkfRows + linkInfo.nEkfRows;
                if ~isempty(linkInfo.rows)
                    info.rows = [info.rows,linkInfo.rows]; %#ok<AGROW>
                end
                if ~isempty(linkInfo.ekfRowTypes)
                    info.ekfRowTypes = [info.ekfRowTypes, ...
                        linkInfo.ekfRowTypes]; %#ok<AGROW>
                end
                if ~isempty(linkInfo.linkEvents)
                    info.linkEvents = [info.linkEvents, ...
                        linkInfo.linkEvents]; %#ok<AGROW>
                end
                if linkInfo.nEkfRows > 0 && ...
                        ~isempty(linkInfo.observationRecord)
                    info.eligibleObservationRecords{end+1} = ...
                        linkInfo.observationRecord; %#ok<AGROW>
                end
            end
            if numel(observations) == 1
                info.observationRecord = observations{1};
            else
                info.observationRecord = [];
            end
            info.scheduled = ~isempty(observations);
            if info.scheduled
                info.scheduleStatus = 'scheduledLinks';
            else
                info.scheduleStatus = 'noScheduledLinks';
            end
        end

        function index = calibrationBiasIndex_(stateMap,linkIdentifier)
            if ~isfield(stateMap,'twoWayCodeCalibrationBiasIdx') || ...
                    isempty(stateMap.twoWayCodeCalibrationBiasIdx)
                error('TwoWayISLMeasurementBuilder:calibrationBiasState', ...
                    'The configured link has no calibration-bias state.');
            end
            indices = stateMap.twoWayCodeCalibrationBiasIdx(:);
            if numel(indices) == 1
                index = indices(1);
                return
            end
            if ~isfield(stateMap,'twoWayCodeCalibrationBiasLinkIdentifiers') || ...
                    numel(stateMap.twoWayCodeCalibrationBiasLinkIdentifiers) ~= ...
                    numel(indices)
                error('TwoWayISLMeasurementBuilder:calibrationBiasMap', ...
                    'Per-link calibration-bias identifiers are missing.');
            end
            match = find(strcmp( ...
                stateMap.twoWayCodeCalibrationBiasLinkIdentifiers, ...
                linkIdentifier),1);
            if isempty(match)
                error('TwoWayISLMeasurementBuilder:calibrationBiasLink', ...
                    'No calibration-bias state is assigned to link %s.', ...
                    linkIdentifier);
            end
            index = indices(match);
        end

        function value = textField_(input,fieldName,linkIndex)
            value = input.(fieldName);
            if ~(ischar(value) || (isstring(value) && isscalar(value))) || ...
                    isempty(strtrim(char(value)))
                error('TwoWayISLMeasurementBuilder:linkTextField', ...
                    'Two-way link %d field %s must be nonempty text.', ...
                    linkIndex,fieldName);
            end
            value = char(value);
        end

        function assertUniqueText_(values,fieldName)
            if numel(unique(values)) ~= numel(values)
                error('TwoWayISLMeasurementBuilder:duplicateLinkIdentity', ...
                    'Enabled links require unique %s values.',fieldName);
            end
        end

        function info = infoForObservation_(cfg,observation)
            identifier = revgnss.TwoWayISLMeasurementBuilder. ...
                linkIdentifierFromObservation_(observation);
            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            linkIndex = find(strcmp({links.linkIdentifier},identifier),1);
            if isempty(linkIndex)
                linkCfg = cfg;
                linkIndex = 0;
            else
                linkCfg = revgnss.TwoWayISLMeasurementBuilder. ...
                    configForLink_(cfg,links(linkIndex));
            end
            info = revgnss.TwoWayISLMeasurementBuilder.defaultInfo(linkCfg,{});
            info.receiverAssetIndex = ...
                revgnss.TwoWayISLMeasurementBuilder.assetIndexFromIdentifier_( ...
                observation.initiatorAssetIdentifier);
            info.transmitterAssetIndex = ...
                revgnss.TwoWayISLMeasurementBuilder.assetIndexFromIdentifier_( ...
                observation.transponderAssetIdentifier);
            info.linkIdentifier = identifier;
            info.linkDefinitionIndex = linkIndex;
        end

        function identifier = linkIdentifierFromObservation_(observation)
            token = regexp(observation.observationIdentifier, ...
                '^(.*):code:e[0-9]+$','tokens','once');
            if isempty(token)
                error('TwoWayISLMeasurementBuilder:observationLinkIdentity', ...
                    'The observation identifier does not contain its physical link.');
            end
            identifier = token{1};
        end

        function assetIndex = assetIndexFromIdentifier_(identifier)
            token = regexp(char(identifier),'^asset:(\d+)$','tokens','once');
            if isempty(token)
                error('TwoWayISLMeasurementBuilder:assetIdentifier', ...
                    ['The recorded asset identifier cannot be mapped to the ' ...
                     'configured joint state.']);
            end
            assetIndex = str2double(token{1});
            if ~(isfinite(assetIndex) && assetIndex >= 1 && ...
                    assetIndex == round(assetIndex))
                error('TwoWayISLMeasurementBuilder:assetIdentifier', ...
                    'The recorded asset identifier contains an invalid index.');
            end
        end

        function endpoint = truthEndpoint_(cfg,asset,assetIdx,t_s)
            [rInertial,vInertial] = models.frames.FrameTimeUtils.ecefStateToInertial( ...
                asset.r_ecef_m,asset.v_ecef_mps,t_s);
            bodyToInertial = models.frames.FrameTimeUtils.rotMatEcefToInertial(t_s) * ...
                revgnss.AttitudeKinematics.bodyToEcefRotation( ...
                asset.attitude_euler_rad);
            bias_s = asset.clock.getBiasMeters()/ ...
                revgnss.TwoWayISLMeasurementBuilder.C_mps;
            localClockRate = 1 + asset.clock.getDriftMetersPerSecond()/ ...
                revgnss.TwoWayISLMeasurementBuilder.C_mps;
            properTimeRate = ...
                revgnss.TwoWayISLMeasurementBuilder.properTimeRate_( ...
                rInertial,vInertial);
            geometry = revgnss.TwoWayISLMeasurementBuilder. ...
                terminalGeometry_(cfg,assetIdx);
            endpoint = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
                'physicalTruth',sprintf('asset:%d',assetIdx),rInertial,vInertial,t_s, ...
                bodyToInertialRotation=bodyToInertial, ...
                transmitPhaseCentreOffset_body_m=geometry.transmitOffset_body_m, ...
                receivePhaseCentreOffset_body_m=geometry.receiveOffset_body_m, ...
                transmitTerminalIdentifier=geometry.transmitTerminalIdentifier, ...
                receiveTerminalIdentifier=geometry.receiveTerminalIdentifier, ...
                transmitAntennaIdentifier=geometry.transmitAntennaIdentifier, ...
                receiveAntennaIdentifier=geometry.receiveAntennaIdentifier, ...
                clockLocalTimeAtReference_s=t_s+bias_s, ...
                localClockRate=localClockRate, ...
                properTimeRate=properTimeRate);
        end

        function endpoint = estimateEndpoint_(cfg,x,stateMap,assetIdx,t_s)
            blk = revgnss.AssetStateBlock.forAsset(stateMap,assetIdx);
            [rInertial,vInertial] = models.frames.FrameTimeUtils.ecefStateToInertial( ...
                x(blk.r),x(blk.v),t_s);
            bodyToInertial = models.frames.FrameTimeUtils.rotMatEcefToInertial(t_s) * ...
                revgnss.AttitudeKinematics.bodyToEcefRotation(x(blk.euler));
            bias_s = x(blk.b)/revgnss.TwoWayISLMeasurementBuilder.C_mps;
            localClockRate = ...
                1 + x(blk.bdot)/revgnss.TwoWayISLMeasurementBuilder.C_mps;
            properTimeRate = ...
                revgnss.TwoWayISLMeasurementBuilder.properTimeRate_( ...
                rInertial,vInertial);
            geometry = revgnss.TwoWayISLMeasurementBuilder. ...
                terminalGeometry_(cfg,assetIdx);
            endpoint = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
                'estimatorState',sprintf('asset:%d',assetIdx),rInertial,vInertial,t_s, ...
                bodyToInertialRotation=bodyToInertial, ...
                transmitPhaseCentreOffset_body_m=geometry.transmitOffset_body_m, ...
                receivePhaseCentreOffset_body_m=geometry.receiveOffset_body_m, ...
                transmitTerminalIdentifier=geometry.transmitTerminalIdentifier, ...
                receiveTerminalIdentifier=geometry.receiveTerminalIdentifier, ...
                transmitAntennaIdentifier=geometry.transmitAntennaIdentifier, ...
                receiveAntennaIdentifier=geometry.receiveAntennaIdentifier, ...
                clockLocalTimeAtReference_s=t_s+bias_s, ...
                localClockRate=localClockRate, ...
                properTimeRate=properTimeRate);
        end

        function value = predictFromState_(cfg,observation,calibration,x, ...
                stateMap,info,t_s)
            initiator = revgnss.TwoWayISLMeasurementBuilder.estimateEndpoint_( ...
                cfg,x,stateMap,info.receiverAssetIndex,t_s);
            transponder = revgnss.TwoWayISLMeasurementBuilder.estimateEndpoint_( ...
                cfg,x,stateMap,info.transmitterAssetIndex,t_s);
            [value,~] = revgnss.CoherentTwoWayCodeRangingModel.predictProcessedRange( ...
                observation,initiator,transponder,calibration,struct(), ...
                revgnss.TwoWayISLMeasurementBuilder.modeledPropagationDelay_( ...
                cfg,x,stateMap,info));
            if revgnss.TwoWayISLMeasurementBuilder.getBool_(cfg, ...
                    {'measurements','isl','twoWay','calibration', ...
                    'residualBiasState','enable'},false)
                biasIndex = revgnss.TwoWayISLMeasurementBuilder. ...
                    calibrationBiasIndex_(stateMap,info.linkIdentifier);
                value = value + x(biasIndex);
            end
        end

        function row = finiteDifferenceRow_(cfg,observation,calibration,x, ...
                stateMap,info,t_s,nx)
            row = zeros(1,nx);
            initiator = revgnss.AssetStateBlock.forAsset( ...
                stateMap,info.receiverAssetIndex);
            transponder = revgnss.AssetStateBlock.forAsset( ...
                stateMap,info.transmitterAssetIndex);
            columns = [initiator.r;initiator.v;initiator.euler; ...
                initiator.b;initiator.bdot;transponder.r;transponder.v; ...
                transponder.euler;transponder.b;transponder.bdot];
            positionStep = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','range','linearization', ...
                'positionStep_m'},0.5);
            velocityStep = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','range','linearization', ...
                'velocityStep_mps'},0.05);
            attitudeStep = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','range','linearization', ...
                'attitudeStep_rad'},1e-3);
            clockBiasStep = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','range','linearization', ...
                'clockBiasStep_m'},10);
            clockDriftStep = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','range','linearization', ...
                'clockDriftStep_mps'},0.01);
            steps = [repmat(positionStep,3,1);repmat(velocityStep,3,1); ...
                repmat(attitudeStep,3,1);clockBiasStep;clockDriftStep; ...
                repmat(positionStep,3,1);repmat(velocityStep,3,1); ...
                repmat(attitudeStep,3,1);clockBiasStep;clockDriftStep];
            for columnIdx = 1:numel(columns)
                stateIndex = columns(columnIdx);
                step = steps(columnIdx);
                xp2 = x; xp1 = x; xm1 = x; xm2 = x;
                xp2(stateIndex) = xp2(stateIndex)+2*step;
                xp1(stateIndex) = xp1(stateIndex)+step;
                xm1(stateIndex) = xm1(stateIndex)-step;
                xm2(stateIndex) = xm2(stateIndex)-2*step;
                hp2 = revgnss.TwoWayISLMeasurementBuilder.predictFromState_( ...
                    cfg,observation,calibration,xp2,stateMap,info,t_s);
                hp1 = revgnss.TwoWayISLMeasurementBuilder.predictFromState_( ...
                    cfg,observation,calibration,xp1,stateMap,info,t_s);
                hm1 = revgnss.TwoWayISLMeasurementBuilder.predictFromState_( ...
                    cfg,observation,calibration,xm1,stateMap,info,t_s);
                hm2 = revgnss.TwoWayISLMeasurementBuilder.predictFromState_( ...
                    cfg,observation,calibration,xm2,stateMap,info,t_s);
                row(stateIndex) = (-hp2+8*hp1-8*hm1+hm2)/(12*step);
            end
        end

        function [physical,calibration] = hardwareModels_(cfg)
            turnaround = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','turnaroundProperTime_s'},1e-3);
            terminal = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','initiatorTerminalGroupDelay_s'},0);
            turnaroundError = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','truth','turnaroundCalibrationError_s'},0);
            terminalError = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','truth','terminalCalibrationError_s'},0);
            carrierRatio = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','carrierFrequencyTurnaroundRatio'},1);
            chipRate = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','codeChipRate_Hz'},10.23e6);
            codeLength = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','codeLength_chips'},1023);
            sigmaTurnaround = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','calibration','turnaroundSigma_s'},0);
            sigmaTerminal = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','calibration','terminalSigma_s'},0);
            covariance = diag([sigmaTurnaround^2,sigmaTerminal^2]);
            chainIdentifier = 'isl-two-way-code-chain';
            chainIdentifier = revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                {'measurements','isl','twoWay','physicalChainIdentifier'}, ...
                chainIdentifier);
            calibrationIdentifier = ...
                revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                {'measurements','isl','twoWay','calibration', ...
                'productIdentifier'},'isl-two-way-code-calibration');
            validFrom = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','calibration', ...
                'validFromLocalTag_s'},0);
            validUntil = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','calibration', ...
                'validUntilLocalTag_s'},1e12);
            physical = revgnss.CoherentTwoWayCodeHardwareModel( ...
                parameterSource='physicalTruth', ...
                physicalChainIdentifier=chainIdentifier, ...
                calibrationProductIdentifier='physical-parameters', ...
                turnaroundProperTime_s=turnaround+turnaroundError, ...
                initiatorTerminalGroupDelay_s=terminal+terminalError, ...
                carrierFrequencyTurnaroundRatio=carrierRatio, ...
                codeRateTurnaroundRatio=1,codeChipRate_Hz=chipRate, ...
                codeLength_chips=codeLength);
            calibration = revgnss.CoherentTwoWayCodeHardwareModel( ...
                parameterSource='calibrationProduct', ...
                physicalChainIdentifier=chainIdentifier, ...
                calibrationProductIdentifier=calibrationIdentifier, ...
                turnaroundProperTime_s=turnaround, ...
                initiatorTerminalGroupDelay_s=terminal, ...
                carrierFrequencyTurnaroundRatio=carrierRatio, ...
                codeRateTurnaroundRatio=1,codeChipRate_Hz=chipRate, ...
                codeLength_chips=codeLength, ...
                calibrationCovariance_s2=covariance, ...
                validFromLocalTag_s=validFrom, ...
                validUntilLocalTag_s=validUntil);
        end

        function variance = calibrationVariance_m2_(calibration)
            gradient = -0.5*revgnss.TwoWayISLMeasurementBuilder.C_mps*[1;1];
            variance = gradient'*calibration.calibrationCovariance_s2*gradient;
        end

        function sigma = rangeSigma_(cfg,distance_m)
            sigma0 = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'measurements','isl','twoWay','range','sigma_m'},0.25);
            sigma = revgnss.ISLLinkBudget.sigma( ...
                cfg,distance_m,{'measurements','isl','twoWay','range'},sigma0);
        end

        function [truthResult,estimatorResult] = rfModels_(cfg,legDistances_m)
            truthResult = [];
            estimatorResult = [];
            model = revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                {'measurements','isl','twoWay','range','linkBudget','model'},'fixed');
            if ~strcmp(model,'physicalRF')
                return
            end
            legDistances_m = double(legDistances_m(:)');
            if isscalar(legDistances_m)
                legDistances_m = repmat(legDistances_m,1,2);
            end
            if numel(legDistances_m) ~= 2 || ...
                    any(~isfinite(legDistances_m)) || any(legDistances_m <= 0)
                error('TwoWayISLMeasurementBuilder:rfLegDistances', ...
                    'RF evaluation requires positive forward and return distances.');
            end
            forwardFrequency = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','forwardCarrierFrequency_Hz'},NaN);
            returnFrequency = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','returnCarrierFrequency_Hz'},NaN);
            plasmaEnabled = revgnss.TwoWayISLMeasurementBuilder.getBool_(cfg, ...
                {'measurements','isl','twoWay','range','plasma','enable'},false);
            truthTec = zeros(1,2);
            estimatorTec = zeros(1,2);
            if plasmaEnabled
                truthTec = [ ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','range','plasma', ...
                    'truthForwardTEC_electrons_per_m2'},0), ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','range','plasma', ...
                    'truthReturnTEC_electrons_per_m2'},0)];
                estimatorTec = [ ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','range','plasma', ...
                    'estimatorForwardTEC_electrons_per_m2'},0), ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','range','plasma', ...
                    'estimatorReturnTEC_electrons_per_m2'},0)];
            end
            truthSpec.forward = revgnss.TwoWayISLMeasurementBuilder.rfLeg_( ...
                cfg,'forward',forwardFrequency,legDistances_m(1),truthTec(1));
            truthSpec.return = revgnss.TwoWayISLMeasurementBuilder.rfLeg_( ...
                cfg,'return',returnFrequency,legDistances_m(2),truthTec(2));
            truthSpec.forwardReturnTrackingErrorCorrelation = ...
                revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','range','linkBudget', ...
                'forwardReturnTrackingErrorCorrelation'},0);
            estimatorSpec = truthSpec;
            estimatorSpec.forward.TEC_electrons_per_m2 = estimatorTec(1);
            estimatorSpec.return.TEC_electrons_per_m2 = estimatorTec(2);
            truthResult = revgnss.InterSatelliteRFLinkModel.evaluate(truthSpec);
            estimatorResult = revgnss.InterSatelliteRFLinkModel.evaluate(estimatorSpec);
        end

        function rate = properTimeRate_(rInertial_m,vInertial_mps)
            c = revgnss.TwoWayISLMeasurementBuilder.C_mps;
            radius_m = norm(rInertial_m);
            if ~(isfinite(radius_m) && radius_m > 0) || ...
                    any(~isfinite(vInertial_mps))
                error('TwoWayISLMeasurementBuilder:properTimeState', ...
                    'Proper-time conversion requires a finite inertial state.');
            end
            % First post-Newtonian spherical-Earth rate d(tau)/dt.
            rate = 1 - (revgnss.Constants.EARTH_GM_M3PS2/radius_m + ...
                0.5*dot(vInertial_mps,vInertial_mps))/c^2;
            if ~(isfinite(rate) && rate > 0)
                error('TwoWayISLMeasurementBuilder:properTimeRate', ...
                    'Computed proper-time rate must be finite and positive.');
            end
        end

        function geometry = terminalGeometry_(cfg,assetIdx)
            mode = revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                {'measurements','isl','twoWay','terminalGeometry','mode'}, ...
                'commonAperture');
            if ~ismember(mode,{'commonAperture','separateTransmitReceive'})
                error('TwoWayISLMeasurementBuilder:terminalGeometryMode', ...
                    'Terminal geometry mode must be commonAperture or separateTransmitReceive.');
            end
            txOffset = revgnss.TwoWayISLMeasurementBuilder.walk_(cfg, ...
                {'measurements','isl','twoWay','terminalGeometry', ...
                'transmitPhaseCentreOffset_body_m'},[]);
            rxOffset = revgnss.TwoWayISLMeasurementBuilder.walk_(cfg, ...
                {'measurements','isl','twoWay','terminalGeometry', ...
                'receivePhaseCentreOffset_body_m'},[]);
            if ~(isnumeric(txOffset) && numel(txOffset) == 3 && ...
                    isnumeric(rxOffset) && numel(rxOffset) == 3 && ...
                    all(isfinite(txOffset(:))) && all(isfinite(rxOffset(:))))
                error('TwoWayISLMeasurementBuilder:terminalPhaseCentre', ...
                    'ISL transmit and receive phase-centre offsets must be finite 3-vectors.');
            end
            txOffset = txOffset(:);
            rxOffset = rxOffset(:);
            if strcmp(mode,'commonAperture') && norm(txOffset-rxOffset) > 1e-12
                error('TwoWayISLMeasurementBuilder:commonApertureGeometry', ...
                    'commonAperture requires identical transmit and receive phase centres.');
            end
            chain = revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                {'measurements','isl','twoWay','physicalChainIdentifier'}, ...
                'isl-two-way-code-chain');
            phaseCentreCalibration = ...
                revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                {'measurements','isl','twoWay','terminalGeometry', ...
                'calibrationProductIdentifier'}, ...
                'isl-phase-centre-calibration');
            geometry.transmitOffset_body_m = txOffset;
            geometry.receiveOffset_body_m = rxOffset;
            geometry.transmitTerminalIdentifier = sprintf( ...
                '%s:asset-%d:transmit-terminal',chain,assetIdx);
            geometry.receiveTerminalIdentifier = sprintf( ...
                '%s:asset-%d:receive-terminal',chain,assetIdx);
            if strcmp(mode,'commonAperture')
                antennaIdentifier = sprintf('%s:asset-%d:common-aperture', ...
                    phaseCentreCalibration,assetIdx);
                geometry.transmitAntennaIdentifier = antennaIdentifier;
                geometry.receiveAntennaIdentifier = antennaIdentifier;
            else
                geometry.transmitAntennaIdentifier = sprintf( ...
                    '%s:asset-%d:transmit-aperture', ...
                    phaseCentreCalibration,assetIdx);
                geometry.receiveAntennaIdentifier = sprintf( ...
                    '%s:asset-%d:receive-aperture', ...
                    phaseCentreCalibration,assetIdx);
            end
        end

        function identifiers = phaseCentreCalibrationIdentifiers_( ...
                cfg,initiatorAssetIndex,transponderAssetIndex)
            baseIdentifier = revgnss.TwoWayISLMeasurementBuilder.getStr_(cfg, ...
                {'measurements','isl','twoWay','terminalGeometry', ...
                'calibrationProductIdentifier'}, ...
                'isl-phase-centre-calibration');
            identifiers = { ...
                sprintf('%s:asset-%d',baseIdentifier,initiatorAssetIndex), ...
                sprintf('%s:asset-%d',baseIdentifier,transponderAssetIndex)};
        end

        function leg = rfLeg_(cfg,legName,frequency_Hz,distance_m,tec)
            base = {'measurements','isl','twoWay','range','linkBudget',legName};
            leg.frequency_Hz = frequency_Hz;
            leg.distance_m = distance_m;
            leg.losses_dB = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,[base,{'losses_dB'}],NaN);
            leg.integrationTime_s = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,[base,{'integrationTime_s'}],NaN);
            leg.modulationTrackingCoefficient = ...
                revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,[base,{'modulationTrackingCoefficient'}],NaN);
            bandwidthDefinition = revgnss.TwoWayISLMeasurementBuilder.getStr_( ...
                cfg,[base,{'bandwidthDefinition'}],'chipRate');
            if strcmp(bandwidthDefinition,'chipRate')
                leg.chipRate_Hz = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                    {'measurements','isl','twoWay','codeChipRate_Hz'},NaN);
            elseif strcmp(bandwidthDefinition,'effectiveBandwidth')
                leg.bandwidth_Hz = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                    cfg,[base,{'effectiveRangingBandwidth_Hz'}],NaN);
            else
                error('TwoWayISLMeasurementBuilder:bandwidthDefinition', ...
                    'RF bandwidthDefinition must be chipRate or effectiveBandwidth.');
            end

            leg.transmitAntenna = ...
                revgnss.TwoWayISLMeasurementBuilder.rfAntenna_( ...
                cfg,[base,{'transmitAntenna'}]);
            leg.receiveAntenna = ...
                revgnss.TwoWayISLMeasurementBuilder.rfAntenna_( ...
                cfg,[base,{'receiveAntenna'}]);
            powerDefinition = revgnss.TwoWayISLMeasurementBuilder.getStr_( ...
                cfg,[base,{'powerDefinition'}],'eirp');
            if strcmp(powerDefinition,'eirp')
                leg.eirp_dBW = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                    cfg,[base,{'eirp_dBW'}],NaN);
            elseif strcmp(powerDefinition,'conductedPower')
                leg.transmitPower_dBW = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                    cfg,[base,{'transmitPower_dBW'}],NaN);
            else
                error('TwoWayISLMeasurementBuilder:powerDefinition', ...
                    'RF powerDefinition must be eirp or conductedPower.');
            end
            noiseDefinition = revgnss.TwoWayISLMeasurementBuilder.getStr_( ...
                cfg,[base,{'receiverNoiseDefinition'}],'GT');
            if strcmp(noiseDefinition,'GT')
                leg.receiverGT_dB_per_K = ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                    cfg,[base,{'receiverGT_dB_per_K'}],NaN);
            elseif strcmp(noiseDefinition,'systemNoiseTemperature')
                leg.systemNoiseTemperature_K = ...
                    revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                    cfg,[base,{'systemNoiseTemperature_K'}],NaN);
            else
                error('TwoWayISLMeasurementBuilder:receiverNoiseDefinition', ...
                    ['RF receiverNoiseDefinition must be GT or ' ...
                     'systemNoiseTemperature.']);
            end
            leg.TEC_electrons_per_m2 = tec;
        end

        function antenna = rfAntenna_(cfg,path)
            antenna.model = revgnss.TwoWayISLMeasurementBuilder.getStr_( ...
                cfg,[path,{'model'}],'fixedAperture');
            if strcmp(antenna.model,'fixedGain')
                antenna.gain_dBi = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                    cfg,[path,{'gain_dBi'}],NaN);
            elseif strcmp(antenna.model,'fixedAperture')
                antenna.diameter_m = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                    cfg,[path,{'diameter_m'}],NaN);
                antenna.efficiency = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                    cfg,[path,{'efficiency'}],NaN);
            else
                error('TwoWayISLMeasurementBuilder:antennaDefinition', ...
                    'RF antenna model must be fixedGain or fixedAperture.');
            end
        end

        function delay_s = modeledPropagationDelay_(cfg,x,stateMap,info)
            delay_s = 0;
            if ~revgnss.TwoWayISLMeasurementBuilder.getBool_(cfg, ...
                    {'measurements','isl','twoWay','range','plasma','enable'},false)
                return
            end
            initiator = revgnss.AssetStateBlock.forAsset( ...
                stateMap,info.receiverAssetIndex);
            transponder = revgnss.AssetStateBlock.forAsset( ...
                stateMap,info.transmitterAssetIndex);
            if isempty(initiator.r) || isempty(transponder.r)
                return
            end
            distance_m = norm(x(initiator.r)-x(transponder.r));
            [~,modelResult] = ...
                revgnss.TwoWayISLMeasurementBuilder.rfModels_(cfg,distance_m);
            delay_s = (modelResult.forward.plasmaGroupDelay_m + ...
                modelResult.return.plasmaGroupDelay_m)/ ...
                revgnss.TwoWayISLMeasurementBuilder.C_mps;
        end

        function [scheduled,status] = scheduleStatus_(cfg,t_s)
            period = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','schedule','updatePeriod_s'},1);
            phase = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','schedule','updatePhase_s'},0);
            start_s = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','schedule','start_s'},0);
            stop_s = revgnss.TwoWayISLMeasurementBuilder.getNum_(cfg, ...
                {'measurements','isl','twoWay','schedule','stop_s'},1e12);
            scheduled = false;
            status = 'outsideActiveInterval';
            tolerance = 10*eps(max(1,abs(t_s)));
            if t_s < start_s-tolerance || t_s > stop_s+tolerance
                return
            end
            cycle = (t_s-phase)/period;
            if cycle < -tolerance || abs(cycle-round(cycle)) > tolerance
                status = 'notScheduled';
                return
            end
            outages = revgnss.TwoWayISLMeasurementBuilder.walk_(cfg, ...
                {'measurements','isl','twoWay','schedule','outages_s'},zeros(0,2));
            for outageIdx = 1:size(outages,1)
                if t_s >= outages(outageIdx,1)-tolerance && ...
                        t_s <= outages(outageIdx,2)+tolerance
                    status = 'scheduledOutage';
                    return
                end
            end
            scheduled = true;
            status = 'scheduled';
        end

        function events = linkEvents_(diagnostic,initiator,transponder,info)
            role = 'diagnosticOnly'; if info.rangeUseInEKF; role = 'EKF'; end
            linkId = info.linkIdentifier;
            t1 = diagnostic.t1TransmitCoordinateTime_s;
            t2 = diagnostic.t2TransponderReceiveCoordinateTime_s;
            t3 = diagnostic.t3TransponderTransmitCoordinateTime_s;
            t4 = diagnostic.t4FinalReceptionCoordinateTime_s;
            bA1 = initiator.clock.getBiasMeters() + ...
                initiator.clock.getDriftMetersPerSecond()*(t1-t4);
            bB2 = transponder.clock.getBiasMeters() + ...
                transponder.clock.getDriftMetersPerSecond()*(t2-t4);
            bB3 = transponder.clock.getBiasMeters() + ...
                transponder.clock.getDriftMetersPerSecond()*(t3-t4);
            bA4 = initiator.clock.getBiasMeters();
            events(1) = revgnss.ISLLinkEventDescriptor.create( ...
                linkId=linkId,linkType='twoWayISL',eventRole='forwardLeg', ...
                txIndex=info.receiverAssetIndex,txName=info.receiverAssetName, ...
                rxIndex=info.transmitterAssetIndex,rxName=info.transmitterAssetName, ...
                receiveTime_s=t2,transmitTime_s=t1,lightTime_s=t2-t1, ...
                range_m=diagnostic.forwardGeometricRange_m, ...
                rxClockBias_m=bB2,txClockBias_m=bA1, ...
                processingDelay_s=t3-t2,timingMode='fourEventLightTime', ...
                rowRole=role);
            events(2) = revgnss.ISLLinkEventDescriptor.create( ...
                linkId=linkId,linkType='twoWayISL',eventRole='returnLeg', ...
                txIndex=info.transmitterAssetIndex,txName=info.transmitterAssetName, ...
                rxIndex=info.receiverAssetIndex,rxName=info.receiverAssetName, ...
                receiveTime_s=t4,transmitTime_s=t3,lightTime_s=t4-t3, ...
                range_m=diagnostic.returnGeometricRange_m, ...
                rxClockBias_m=bA4,txClockBias_m=bB3, ...
                processingDelay_s=t3-t2,timingMode='fourEventLightTime', ...
                rowRole=role);
        end

        function info = addMeta_(info,Hrow,useInEkf,stateMap)
            columns = find(Hrow~=0);
            role = 'diagnosticOnly'; if useInEkf; role = 'physicalEKF'; end
            linkId = info.linkIdentifier;
            row = revgnss.ObservableRowDescriptor.create(0,'islTwoWayRange', ...
                linkId,info.signalIdentifier,NaN,1,columns, ...
                'idealized sequential four-event two-way code-delay observable',role);
            attitudeColumns = [];
            if isfield(stateMap,'asset')
                for assetIdx = [info.receiverAssetIndex,info.transmitterAssetIndex]
                    attitudeColumns = [attitudeColumns; ...
                        stateMap.asset(assetIdx).euler(:)]; %#ok<AGROW>
                end
            end
            row = revgnss.ObservableRowDescriptor.withFlags(row,false, ...
                any(ismember(columns,attitudeColumns)));
            info.rows = row;
            if useInEkf
                info.ekfRowTypes = {'islTwoWayRange'};
                info.nEkfRows = 1;
            end
        end

        function value = drawNormal_(cfg,initiatorIdx,transponderIdx,epochIdx)
            seed = revgnss.TwoWayISLMeasurementBuilder.getNum_( ...
                cfg,{'simulation','seed'},42);
            stream = RandStream('mt19937ar','Seed',mod( ...
                seed + 700001 + 1009*initiatorIdx + 9176*transponderIdx + ...
                104729*epochIdx,2^31-1));
            value = randn(stream,1,1);
        end

        function tf = isEnabled_(cfg)
            tf = revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','enable'},false) && ...
                revgnss.TwoWayISLMeasurementBuilder.getBool_( ...
                cfg,{'measurements','isl','twoWay','range','enable'},false);
        end

        function tf = getBool_(cfg,path,defaultValue)
            value = revgnss.TwoWayISLMeasurementBuilder.walk_(cfg,path,defaultValue);
            tf = islogical(value) && isscalar(value) && value;
        end

        function value = getNum_(cfg,path,defaultValue)
            value = revgnss.TwoWayISLMeasurementBuilder.walk_(cfg,path,defaultValue);
            if ~isnumeric(value) || ~isscalar(value); value = defaultValue; end
        end

        function value = getStr_(cfg,path,defaultValue)
            value = revgnss.TwoWayISLMeasurementBuilder.walk_(cfg,path,defaultValue);
            if ~(ischar(value) || (isstring(value) && isscalar(value)))
                value = defaultValue;
            end
            value = char(value);
        end

        function value = walk_(cfg,path,defaultValue)
            value = cfg;
            for pathIdx = 1:numel(path)
                if isstruct(value) && isfield(value,path{pathIdx})
                    value = value.(path{pathIdx});
                else
                    value = defaultValue;
                    return
                end
            end
        end
    end
end
