classdef StarTrackerObservationModel
    % StarTrackerObservationModel  Truth-independent star-tracker residual.

    methods (Static)
        function [innovation_rad,model] = linearizedResidual( ...
                q_I_B_estimate,observation,nominalAlignmentCorrection_rad)
            assert(isa(observation,'models.sensors.StarTrackerObservation') && ...
                observation.valid, ...
                'StarTrackerObservationModel:invalidObservation', ...
                'A valid StarTrackerObservation is required.');
            if nargin < 3 || isempty(nominalAlignmentCorrection_rad)
                nominalAlignmentCorrection_rad = zeros(3,1);
            end
            alignmentCorrection = nominalAlignmentCorrection_rad(:);
            assert(numel(alignmentCorrection) == 3 && ...
                all(isfinite(alignmentCorrection)), ...
                'StarTrackerObservationModel:invalidAlignmentEstimate', ...
                'Alignment correction must contain three finite components.');

            q_B_S_model = revgnss.AttitudeQuaternion.multiply( ...
                observation.alignmentCalibration.q_B_S_wxyz, ...
                revgnss.AttitudeQuaternion.fromRotationVector( ...
                alignmentCorrection));
            q_I_S_prediction = revgnss.AttitudeQuaternion.multiply( ...
                q_I_B_estimate,q_B_S_model);
            q_predictionToMeasurement = revgnss.AttitudeQuaternion.multiply( ...
                revgnss.AttitudeQuaternion.inverse(q_I_S_prediction), ...
                observation.q_I_S_meas_wxyz);
            innovation_rad = revgnss.AttitudeQuaternion.toRotationVector( ...
                q_predictionToMeasurement);

            C_B_S_model = revgnss.AttitudeQuaternion.toDcm(q_B_S_model);
            model.predictedQuaternion_I_S_wxyz = q_I_S_prediction;
            model.attitudeErrorJacobian = C_B_S_model.';
            model.alignmentErrorJacobian = eye(3);
            model.whiteAngularCovariance_rad2 = ...
                observation.whiteAngularCovariance_rad2;
            model.alignmentParameterIdentifier = ...
                observation.alignmentCalibration.identifier;
            model.alignmentTreatment = ...
                observation.alignmentCalibration.treatment;
            model.alignmentPriorCovariance_rad2 = ...
                observation.alignmentCalibration.covariance_rad2;
            model.alignmentRandomWalkPsd_rad2ps = ...
                observation.alignmentCalibration.driftProcessNoise_rad2ps;
            model.alignmentStateConvention = ['q_B_S_nom = q_B_S_cal (x) ' ...
                'Exp(nominal correction); local state error is right multiplicative in S'];
            model.correlationPolicy = ['alignment is a persistent calibration parameter; ' ...
                'do not add its covariance as independent noise at every epoch'];
            model.residualConvention = ...
                'Log(q_I_S_prediction^{-1} (x) q_I_S_measured), expressed in S';
        end
    end
end
