function entries = derivedConfigPathRegistry()
%DERIVEDCONFIGPATHREGISTRY  Config paths a SCENARIO must not write, and what to write instead.
%
%   Returns a struct array with fields:
%       path        dotted config path, e.g. 'measurements.codeMode'
%       severity    'blocked'  the resolution ALWAYS overwrites it, so a scenario value
%                              is guaranteed dead
%                   'warn'     the resolution overwrites it under stated conditions only
%                   'error'    the knob was removed and setting it now raises
%       instead     the path a scenario should write to reach the same effect, or '' when
%                   there is none
%       note        one line naming the derivation site and what setting the path does
%
%   WHY THIS FILE EXISTS. deepMergeConfig validates that a path EXISTS, and
%   configEnumRegistry validates that a string VALUE is legal. Neither asks the third
%   question: will this leaf still hold the value I gave it once finalizeConfig has run?
%   For the paths below the answer is no. They are derived from some other knob, so a
%   scenario that sets them resolves without complaint, runs to completion, and reports a
%   setting the run did not use -- the same silent-no-op class of defect that
%   resolveEnablePairsPostMerge exists to close for the truth/model enable pairs, and that
%   test_scenario_override_invariance detects after the fact for the shipped ladder.
%
%   This registry is what lets the config editor refuse the mistake BEFORE the file is
%   written, and what lets checkPersonalConfig name it afterwards.
%
%   SCOPE. Curated, not exhaustive, and the same rule as configEnumRegistry applies: an
%   entry earns its place when the overwrite changes PHYSICS or the estimator rather than
%   a label. Every entry below was read off the derivation site, not from a comment, and
%   the site is cited so the claim can be rechecked when that code moves.
%
%   See also CONFIGENUMREGISTRY, SCENARIORESOLUTIONEXCEPTIONREGISTRY, CHECKPERSONALCONFIG.

    e = @(p, s, i, n) struct('path', p, 'severity', s, 'instead', i, 'note', n);
    entries = [ ...
        ...% ---- Owned by the RUN, not by the scenario ----------------------------
        e('simulation.duration_s', 'blocked', '', ...
          ['run_oo_v1 injects the arc length as a CALLER OVERRIDE after the JSON is ' ...
           'merged (run_oo_v1.m:41), and caller overrides are the most specific layer ' ...
           'of all, so a scenario value is always beaten. Pass the duration as the ' ...
           'second argument instead: run_oo_v1(''mine.json'', 7200).']), ...
        ...% ---- Ionosphere handling derives the code observable ------------------
        e('measurements.codeMode', 'blocked', 'atmosphere.ionosphereFree', ...
          ['ConfigFactory.applyIonosphereHandling (ConfigFactory.m:560-569) sets codeMode ' ...
           'from atmosphere.ionosphereFree / atmosphere.estimateIono AFTER the merge, so ' ...
           'any scenario value is overwritten. golden_baseline.json states this explicitly ' ...
           'and declines to set it.']), ...
        ...% ---- Tower clock treatment --------------------------------------------
        e('estimator.towerClockMode', 'blocked', 'towerClock.correctionMode', ...
          ['finalizeConfig maps towerClock.correctionMode to the internal ' ...
           'estimator.towerClockMode (ConfigFactory.m:806). The two vocabularies differ: ' ...
           'the external names are ''perfectTruth''-style and the internal switch falls ' ...
           'through to towerClockModel = 0 on an unrecognised value, so writing the ' ...
           'internal field directly is how you get NO tower clock model at all.']), ...
        e('estimator.estimateTowerClocks', 'blocked', 'clock.mode', ...
          ['Mapped from clock.mode at ConfigFactory.m:945-947, with a gauge check ' ...
           'alongside it. Named as derived-and-dead in docs/golden_baseline_provenance.md.']), ...
        e('clockScaling.customOscillators', 'blocked', 'clock.customOscillators', ...
          ['finalizeConfig mirrors clock.customOscillators into clockScaling before ' ...
           'makeClockConfig reads it (ConfigFactory.m:1914-1917). There is ONE oscillator ' ...
           'table and clock.* is the side of it a scenario owns.']), ...
        e('clock.templateSource', 'error', 'clock.customOscillators', ...
          ['REMOVED 2026-08-10 and caught loudly: ConfigFactory.m:1919 raises ' ...
           'ConfigFactory:templateSourceRemoved. There is now one table, Winkel (2003) ' ...
           'Table 2.1, in ConfigFactory.oscillatorCatalog_. Select an oscillator by name ' ...
           '(OCXO1/OCXO2/RUBIDIUM1/RUBIDIUM2/CESIUM1/CESIUM2/QUARTZ/TCXO/ZERO) or override ' ...
           'its coefficients through clock.customOscillators.']), ...
        ...% ---- Attitude observability follows the antenna count -----------------
        ...% All four are written unconditionally by finalizeConfig from scenario.nReceivers
        ...% (and, for the first, from whether a star tracker or gyro is enabled). A scenario
        ...% asking for attitude states therefore asks for them through nReceivers and the
        ...% sensor enables, never by setting the estimate* flags.
        e('estimator.estimateAttitude', 'blocked', 'scenario.nReceivers', ...
          ['finalizeConfig sets this from nReceivers plus estimator.starTracker.enable / ' ...
           'estimator.imu.enable (ConfigFactory.m:2027-2038).']), ...
        e('estimator.estimateAttitudeFromPseudorange', 'blocked', 'scenario.nReceivers', ...
          ['finalizeConfig sets this true for nReceivers > 1, then clears it when ' ...
           'estimator.attitude.useCodePartials is false (ConfigFactory.m:2038-2048).']), ...
        e('estimator.estimateAngularRate', 'blocked', '', ...
          'finalizeConfig writes false on both branches (ConfigFactory.m:2031, :2040).'), ...
        e('estimator.estimateAngularRateFromPseudorange', 'blocked', '', ...
          'finalizeConfig writes false on both branches (ConfigFactory.m:2033, :2041).'), ...
        ...% ---- Receiver geometry -------------------------------------------------
        e('asset.receiverLeverArm_body_m', 'blocked', 'scenario.nReceivers', ...
          ['The singular lever arm is written by finalizeConfig: [0;0;0] at nReceivers == 1 ' ...
           '(ConfigFactory.m:2029). The plural receiverLeverArms_body_m is the one a ' ...
           'scenario can own.']), ...
        e('asset.receiverLeverArms_body_m', 'warn', '', ...
          ['CONDITIONAL. A custom 3 x nReceivers matrix WINS and is kept as-is ' ...
           '(ConfigFactory.m:2052). Anything of another shape is replaced by the canonical ' ...
           'non-coplanar cross [1 -1 0 0; 0 0 1 -1; 0.2 0.2 -0.2 -0.2] for nReceivers <= 4, ' ...
           'and raises for nReceivers > 4. Set it only with the matching column count.']), ...
        ...% ---- Shape normalisation, values preserved ------------------------------
        e('signals.enabledMask', 'warn', '', ...
          ['ORIENTATION ONLY, VALUES PRESERVED. jsondecode parses a JSON array as a COLUMN ' ...
           'and ConfigFactory stores the canonical mask as a ROW, so the resolved value ' ...
           'differs in SHAPE from the file. No JSON spelling can produce a row. This is ' ...
           'the one entry class in scenarioResolutionExceptionRegistry and is listed here ' ...
           'so the same normalisation does not read as a lost setting.']) ...
        ];
end
