classdef AttitudeSensorSuite < handle
    % AttitudeSensorSuite  Epoch attitude-sensor generation and EKF row assembly.
    %
    % Truth-side sensor objects receive q_E_B and omega_B/E^B from each simulated
    % spacecraft. Estimator-side methods receive only immutable observations and
    % the EKF nominal q_E_B.

    properties (SetAccess = private)
        estimatedAssetCount
        gyroscopeEnabled
        starTrackerEnabled
        starTrackerUseInEKF
        starTrackers
        gyroscopeObservations
        starTrackerObservations
        starTrackerOutages_s
        history
    end

    methods
        function obj = AttitudeSensorSuite(cfg, ekf)
            revgnss.AttitudeSensorSuite.validateConfig(cfg);
            obj.estimatedAssetCount = 1;
            if ekf.jointMultiAssetEnabled
                obj.estimatedAssetCount = ekf.nSpaceAssets;
            end
            obj.gyroscopeEnabled = logical(cfg.estimator.imu.enable);
            obj.starTrackerEnabled = logical(cfg.estimator.starTracker.enable);
            obj.starTrackerUseInEKF = obj.starTrackerEnabled && ...
                logical(cfg.estimator.starTracker.useInEKF);
            obj.starTrackers = cell(1,obj.estimatedAssetCount);
            obj.gyroscopeObservations = cell(1,obj.estimatedAssetCount);
            obj.starTrackerObservations = cell(1,obj.estimatedAssetCount);
            obj.starTrackerOutages_s = cfg.estimator.starTracker.outages_s;
            obj.history = struct('time_s',zeros(1,0), ...
                'gyroscopeValid',false(obj.estimatedAssetCount,0), ...
                'starTrackerValid',false(obj.estimatedAssetCount,0), ...
                'starTrackerRows',zeros(obj.estimatedAssetCount,0), ...
                'physicalGyroBiasTruth_radps', ...
                zeros(3,obj.estimatedAssetCount,0));

            for assetIdx = 1:obj.estimatedAssetCount
                if obj.starTrackerEnabled
                    [trackerConfig,calibration] = ...
                        obj.starTrackerConfig_(cfg,assetIdx);
                    obj.starTrackers{assetIdx} = ...
                        models.sensors.StarTrackerMeasurementModel( ...
                        trackerConfig,calibration);
                end
            end
        end

        function generate(obj,assets,time_s,sampleInterval_s)
            assert(numel(assets) >= obj.estimatedAssetCount, ...
                'AttitudeSensorSuite:missingAssets', ...
                'The estimated spacecraft do not all have truth-side sensor hosts.');
            for assetIdx = 1:obj.estimatedAssetCount
                q_E_B_truth = ...
                    revgnss.AttitudeErrorStateKinematics.eulerToQuatZYX( ...
                    assets{assetIdx}.attitude_euler_rad);
                if obj.gyroscopeEnabled
                    obj.gyroscopeObservations{assetIdx} = ...
                        assets{assetIdx}.sampleInertialSensors( ...
                        time_s,sampleInterval_s);
                    assert(isa(obj.gyroscopeObservations{assetIdx}, ...
                        'models.sensors.GyroscopeObservation'), ...
                        'AttitudeSensorSuite:missingPhysicalGyroscope', ...
                        ['Estimated spacecraft %d has no physical IMU owner. ' ...
                         'Resolve cfg.assets(%d).imu before simulation.'], ...
                        assetIdx,assetIdx);
                end
                if obj.starTrackerEnabled
                    available = ~obj.isStarTrackerOutage_(time_s);
                    obj.starTrackerObservations{assetIdx} = ...
                        obj.starTrackers{assetIdx}.sampleFromEarthFixedAttitude( ...
                        q_E_B_truth,time_s,available);
                end
            end
            epochColumn = numel(obj.history.time_s)+1;
            obj.history.time_s(epochColumn) = time_s;
            obj.history.gyroscopeValid(:,epochColumn) = false;
            obj.history.starTrackerValid(:,epochColumn) = false;
            obj.history.starTrackerRows(:,epochColumn) = 0;
            obj.history.physicalGyroBiasTruth_radps(:,:,epochColumn) = ...
                nan(3,obj.estimatedAssetCount);
            for assetIdx = 1:obj.estimatedAssetCount
                obj.history.gyroscopeValid(assetIdx,epochColumn) = ...
                    ~isempty(obj.gyroscopeObservations{assetIdx}) && ...
                    obj.gyroscopeObservations{assetIdx}.valid;
                if ~isempty(assets{assetIdx}.imu)
                    obj.history.physicalGyroBiasTruth_radps(:,assetIdx,epochColumn) = ...
                        assets{assetIdx}.imu.gyroBias_radps;
                end
                obj.history.starTrackerValid(assetIdx,epochColumn) = ...
                    ~isempty(obj.starTrackerObservations{assetIdx}) && ...
                    obj.starTrackerObservations{assetIdx}.valid;
            end
        end

        function [omega_B_E_meas_radps,omega_B_I_meas_radps] = ...
                gyroscopeInputsForFilter(obj,ekf)
            omega_B_E_meas_radps = [];
            omega_B_I_meas_radps = [];
            if ~obj.gyroscopeEnabled
                return
            end
            omega_B_E_meas_radps = zeros(3,obj.estimatedAssetCount);
            omega_B_I_meas_radps = zeros(3,obj.estimatedAssetCount);
            for assetIdx = 1:obj.estimatedAssetCount
                observation = obj.gyroscopeObservations{assetIdx};
                assert(~isempty(observation) && observation.valid, ...
                    'AttitudeSensorSuite:missingGyroscopeObservation', ...
                    'No valid gyroscope observation exists for spacecraft %d.',assetIdx);
                omega_B_I_meas_radps(:,assetIdx) = ...
                    observation.omega_B_I_meas_body_radps;
                omega_B_E_meas_radps(:,assetIdx) = ...
                    ekf.inertialGyroscopeToEarthRelative(observation,assetIdx);
            end
        end

        function [z,h,H,R,info] = buildStarTrackerRows(obj,ekf,time_s)
            z = zeros(0,1);
            h = zeros(0,1);
            H = zeros(0,ekf.nx);
            R = zeros(0);
            info = struct('enabled',obj.starTrackerEnabled, ...
                'useInEKF',obj.starTrackerUseInEKF,'nValid',0,'nRows',0, ...
                'NIS',NaN,'spacecraft',struct([]));
            if ~obj.starTrackerEnabled
                return
            end

            for assetIdx = 1:obj.estimatedAssetCount
                observation = obj.starTrackerObservations{assetIdx};
                valid = ~isempty(observation) && observation.valid;
                entry = struct('assetIndex',assetIdx,'valid',valid, ...
                    'status','missing','rowStart',0,'rowCount',0, ...
                    'innovationNorm_rad',NaN);
                if ~isempty(observation)
                    entry.status = observation.status;
                end
                if valid
                    info.nValid = info.nValid + 1;
                end
                if valid && obj.starTrackerUseInEKF
                    q_E_B_nominal = ekf.nominalQuat_wxyz(:,assetIdx);
                    q_I_B_nominal = revgnss.AttitudeQuaternion. ...
                        ecefBodyToInertial(q_E_B_nominal,time_s);
                    [innovation,model] = ...
                        models.sensors.StarTrackerObservationModel.linearizedResidual( ...
                        q_I_B_nominal,observation);
                    row = zeros(3,ekf.nx);
                    attitudeIdx = ekf.stateMap.asset(assetIdx).euler;
                    row(:,attitudeIdx) = model.attitudeErrorJacobian;
                    entry.rowStart = numel(z)+1;
                    entry.rowCount = 3;
                    entry.innovationNorm_rad = norm(innovation);
                    z = [z;innovation]; %#ok<AGROW>
                    h = [h;zeros(3,1)]; %#ok<AGROW>
                    H = [H;row]; %#ok<AGROW>
                    R = blkdiag(R,model.whiteAngularCovariance_rad2);
                end
                if isempty(info.spacecraft)
                    info.spacecraft = entry;
                else
                    info.spacecraft(end+1) = entry;
                end
            end
            info.nRows = numel(z);
            if ~isempty(obj.history.time_s) && ...
                    abs(obj.history.time_s(end)-time_s) <= ...
                    10*eps(max(1,abs(time_s)))
                for assetIdx = 1:numel(info.spacecraft)
                    obj.history.starTrackerRows(assetIdx,end) = ...
                        info.spacecraft(assetIdx).rowCount;
                end
            end
        end
    end

    methods (Static)
        function validateConfig(cfg)
            imuEnabled = i_bool(cfg,{'estimator','imu','enable'},false);
            starEnabled = i_bool(cfg,{'estimator','starTracker','enable'},false);
            starUse = i_bool(cfg,{'estimator','starTracker','useInEKF'},false);
            parameterization = i_text(cfg, ...
                {'estimator','attitude','parameterization'},'eulerZYX');
            estimateAttitude = i_bool(cfg, ...
                {'estimator','estimateAttitude'},true);

            if imuEnabled
                assert(strcmp(parameterization,'quaternionErrorState'), ...
                    'AttitudeSensorSuite:imuRequiresQuaternion', ...
                    'Inertial gyroscope aiding requires quaternionErrorState attitude.');
                assert(estimateAttitude, ...
                    'AttitudeSensorSuite:imuRequiresAttitudeEstimation', ...
                    'Inertial gyroscope aiding requires attitude estimation.');
            end
            if starEnabled && starUse
                assert(strcmp(parameterization,'quaternionErrorState'), ...
                    'AttitudeSensorSuite:starTrackerRequiresQuaternion', ...
                    'Star-tracker EKF rows require quaternionErrorState attitude.');
                assert(estimateAttitude, ...
                    'AttitudeSensorSuite:starTrackerRequiresAttitudeEstimation', ...
                    'Star-tracker EKF rows require attitude estimation.');
                treatment = i_text(cfg, ...
                    {'estimator','starTracker','calibration','treatment'},'');
                assert(strcmp(treatment,'fixedCalibration'), ...
                    'AttitudeSensorSuite:alignmentStateUnavailable', ...
                    ['Active star-tracker rows currently require fixedCalibration. ' ...
                     'Persistent alignment uncertainty needs an estimated alignment state.']);
                calibrationCovariance = i_value(cfg, ...
                    {'estimator','starTracker','calibration','covariance_rad2'},nan(3));
                driftPsd = i_value(cfg, ...
                    {'estimator','starTracker','calibration', ...
                    'driftProcessNoise_rad2ps'},nan(3));
                assert(isequal(size(calibrationCovariance),[3,3]) && ...
                    isequal(size(driftPsd),[3,3]) && ...
                    norm(calibrationCovariance,'fro') == 0 && ...
                    norm(driftPsd,'fro') == 0, ...
                    'AttitudeSensorSuite:uncertainFixedAlignment', ...
                    ['fixedCalibration requires zero alignment covariance and drift PSD. ' ...
                     'Uncertainty cannot be repeated as independent measurement noise.']);
                fixedBias = i_value(cfg, ...
                    {'estimator','starTracker','truth', ...
                    'fixedAlignmentBias_rad'},nan(3,1));
                driftRate = i_value(cfg, ...
                    {'estimator','starTracker','truth', ...
                    'alignmentDriftRate_radps'},nan(3,1));
                driftRandomWalk = i_value(cfg, ...
                    {'estimator','starTracker','truth', ...
                    'alignmentDriftRandomWalk_rad_per_sqrt_s'},NaN);
                drawFromCalibration = i_value(cfg, ...
                    {'estimator','starTracker','truth', ...
                    'drawAlignmentFromCalibrationCovariance'},true);
                exactTruthAlignment = isnumeric(fixedBias) && ...
                    numel(fixedBias) == 3 && all(isfinite(fixedBias(:))) && ...
                    norm(fixedBias(:)) == 0 && isnumeric(driftRate) && ...
                    numel(driftRate) == 3 && all(isfinite(driftRate(:))) && ...
                    norm(driftRate(:)) == 0 && ...
                    isscalar(driftRandomWalk) && ...
                    isfinite(driftRandomWalk) && driftRandomWalk == 0 && ...
                    (islogical(drawFromCalibration) || ...
                    isnumeric(drawFromCalibration)) && ...
                    isscalar(drawFromCalibration) && ...
                    isfinite(double(drawFromCalibration)) && ...
                    ~logical(drawFromCalibration);
                assert(exactTruthAlignment, ...
                    'AttitudeSensorSuite:unmodeledFixedAlignment', ...
                    ['fixedCalibration requires zero truth alignment bias, drift, ' ...
                     'random walk, and no calibration-covariance draw.']);
            end
            if starEnabled
                updatePeriod_s = i_value(cfg, ...
                    {'estimator','starTracker','updatePeriod_s'},NaN);
                sigma_rad = i_value(cfg, ...
                    {'estimator','starTracker','whiteAngularSigma_rad'},NaN);
                assert(isscalar(updatePeriod_s) && isfinite(updatePeriod_s) && ...
                    updatePeriod_s > 0, ...
                    'AttitudeSensorSuite:invalidStarTrackerPeriod', ...
                    'Star-tracker update period must be finite and positive.');
                assert(isscalar(sigma_rad) && isfinite(sigma_rad) && sigma_rad >= 0, ...
                    'AttitudeSensorSuite:invalidStarTrackerNoise', ...
                    'Star-tracker angular sigma must be finite and nonnegative.');
                outages = i_value(cfg, ...
                    {'estimator','starTracker','outages_s'},zeros(0,2));
                assert(isnumeric(outages) && size(outages,2) == 2 && ...
                    all(isfinite(outages(:))) && ...
                    all(outages(:,2) >= outages(:,1)), ...
                    'AttitudeSensorSuite:invalidStarTrackerOutages', ...
                    'Star-tracker outages must be finite [start,end] rows.');
            end
        end
    end

    methods (Access = private)
        function [tracker,calibration] = starTrackerConfig_(~,cfg,assetIdx)
            source = cfg.estimator.starTracker;
            tracker.sensorIdentifier = sprintf('spacecraft-%d:star-tracker',assetIdx);
            tracker.updatePeriod_s = source.updatePeriod_s;
            tracker.updatePhase_s = source.updatePhase_s;
            tracker.whiteAngularSigma_rad = source.whiteAngularSigma_rad;
            tracker.fixedAlignmentBias_rad = ...
                source.truth.fixedAlignmentBias_rad;
            tracker.alignmentDriftRate_radps = ...
                source.truth.alignmentDriftRate_radps;
            tracker.alignmentDriftRandomWalk_rad_per_sqrt_s = ...
                source.truth.alignmentDriftRandomWalk_rad_per_sqrt_s;
            tracker.drawAlignmentFromCalibrationCovariance = ...
                source.truth.drawAlignmentFromCalibrationCovariance;
            tracker.seed = source.truth.seed + 1013*(assetIdx-1);
            calibration = source.calibration;
            calibration.identifier = sprintf('%s:spacecraft-%d', ...
                char(source.calibration.identifier),assetIdx);
        end

        function unavailable = isStarTrackerOutage_(obj,time_s)
            unavailable = false;
            for outageIdx = 1:size(obj.starTrackerOutages_s,1)
                if time_s >= obj.starTrackerOutages_s(outageIdx,1) && ...
                        time_s <= obj.starTrackerOutages_s(outageIdx,2)
                    unavailable = true;
                    return
                end
            end
        end
    end
end

function value = i_value(s,path,defaultValue)
    value = defaultValue;
    cursor = s;
    for idx = 1:numel(path)
        if ~isstruct(cursor) || ~isfield(cursor,path{idx})
            return
        end
        cursor = cursor.(path{idx});
    end
    value = cursor;
end

function value = i_bool(s,path,defaultValue)
    value = i_value(s,path,defaultValue);
    value = (islogical(value) || isnumeric(value)) && isscalar(value) && ...
        isfinite(double(value)) && logical(value);
end

function value = i_text(s,path,defaultValue)
    value = i_value(s,path,defaultValue);
    if isstring(value) && isscalar(value)
        value = char(value);
    end
    if ~ischar(value)
        value = defaultValue;
    end
end
