classdef CommunicationEndpointState
    % CommunicationEndpointState  Frozen per-endpoint snapshot (plan Section 2.1).
    %
    % The immutable value every revgnss.CommunicationEndpointStateProvider implementation
    % returns. This is the type gate for Interface #1: a truth-sourced endpoint cannot be
    % represented (stateSource is frozen to 'estimatorState' only), and every coordinate-time
    % scale / frame / clock-datum / state-schema / attitude-error-convention tag required by
    % revgnss.DistributedLinkProtocolContract is carried explicitly rather than inferred from
    % label shape alone.
    %
    % FRAME NOTE: this state is ECEF, because DistributedLinkProtocolContract.FrameIdentifier
    % is 'ECEF' and EndpointStateProduct exports ECEF component labels.
    % revgnss.TwoWayCodeEndpointModel takes INERTIAL positions. The ECEF -> ECI conversion is
    % a Section 2.3 adapter responsibility; nothing in Section 2.1 performs it.

    properties (SetAccess = immutable)
        endpointIdentifier (1,:) char
        canonicalPhysicalAssetIndex (1,1) double
        stateSource (1,:) char
        stateOrigin (1,:) char
        coordinateEpoch_s (1,1) double
        stateEvaluationPolicy (1,:) char
        coordinateTimeScale (1,:) char
        frameIdentifier (1,:) char
        clockDatumIdentifier (1,:) char
        stateSchemaVersion (1,:) char
        attitudeErrorCoordinateConvention (1,:) char
        stateComponentOrder (1,:) cell
        covarianceComponentOrder (1,:) cell
        stateVector (:,1) double
        covarianceBlock (:,:) double
        positionEcef_m (3,1) double
        velocityEcef_mps (3,1) double
        attitudeEulerZyx_rad (3,1) double
        angularRateBody_radps (3,1) double
        clockBias_m (1,1) double
        clockDriftRate_mps (1,1) double
        terminalGeometry (1,1) struct
        productProvenance (1,1) struct
        qualityFlags (1,1) struct
        clockAnchorDeclaration (1,1)
    end

    methods
        function obj = CommunicationEndpointState(record)
            required = {'endpointIdentifier','canonicalPhysicalAssetIndex','stateSource', ...
                'stateOrigin','coordinateEpoch_s','stateEvaluationPolicy', ...
                'coordinateTimeScale','frameIdentifier','clockDatumIdentifier', ...
                'stateSchemaVersion','attitudeErrorCoordinateConvention', ...
                'stateComponentOrder','covarianceComponentOrder','stateVector', ...
                'covarianceBlock','positionEcef_m','velocityEcef_mps', ...
                'attitudeEulerZyx_rad','angularRateBody_radps','clockBias_m', ...
                'clockDriftRate_mps','terminalGeometry','productProvenance','qualityFlags', ...
                'clockAnchorDeclaration'};
            supplied = fieldnames(record);
            missing = setdiff(required,supplied);
            unknown = setdiff(supplied,required);
            if ~isempty(missing)
                error('CommunicationEndpointState:missingField', ...
                    'CommunicationEndpointState is missing %s.',missing{1});
            end
            if ~isempty(unknown)
                error('CommunicationEndpointState:unknownField', ...
                    'CommunicationEndpointState contains unsupported field %s.',unknown{1});
            end

            canonicalId = revgnss.CanonicalEndpointIdentity.fromProductIdentifier( ...
                record.endpointIdentifier);
            if canonicalId.physicalAssetIndex ~= record.canonicalPhysicalAssetIndex
                error('CommunicationEndpointState:identityMismatch', ...
                    ['endpointIdentifier ''%s'' and canonicalPhysicalAssetIndex %d disagree ' ...
                    'on the physical spacecraft this state describes.'], ...
                    record.endpointIdentifier,record.canonicalPhysicalAssetIndex);
            end
            if ~isa(record.clockAnchorDeclaration,'revgnss.EndpointClockAnchorDeclaration')
                error('CommunicationEndpointState:clockAnchorDeclarationType', ...
                    'clockAnchorDeclaration must be a revgnss.EndpointClockAnchorDeclaration.');
            end
            if record.clockAnchorDeclaration.canonicalPhysicalAssetIndex ~= ...
                    record.canonicalPhysicalAssetIndex
                error('CommunicationEndpointState:clockAnchorDeclarationIdentityMismatch', ...
                    'clockAnchorDeclaration names a different physical spacecraft than this state.');
            end
            if ~strcmp(record.clockAnchorDeclaration.clockDatumIdentifier, ...
                    char(record.clockDatumIdentifier))
                error('CommunicationEndpointState:clockAnchorDeclarationDatumMismatch', ...
                    'clockAnchorDeclaration.clockDatumIdentifier does not match this state''s own.');
            end

            allowedSources = revgnss.CommunicationEndpointStateProvider.AllowedStateSources;
            if ~(ischar(record.stateSource) || ...
                    (isstring(record.stateSource) && isscalar(record.stateSource))) || ...
                    ~any(strcmp(char(record.stateSource),allowedSources))
                error('CommunicationEndpointState:stateSource', ...
                    'stateSource must be one of the frozen estimator-only sources.');
            end
            allowedOrigins = revgnss.CommunicationEndpointStateProvider.AllowedStateOrigins;
            if ~(ischar(record.stateOrigin) || ...
                    (isstring(record.stateOrigin) && isscalar(record.stateOrigin))) || ...
                    ~any(strcmp(char(record.stateOrigin),allowedOrigins))
                error('CommunicationEndpointState:stateOrigin', ...
                    'stateOrigin must be one of the frozen origins.');
            end
            if ~(isstruct(record.qualityFlags) && isfield(record.qualityFlags,'truthUsed') && ...
                    islogical(record.qualityFlags.truthUsed))
                error('CommunicationEndpointState:qualityFlagsSchema', ...
                    'qualityFlags.truthUsed must be a logical field.');
            end
            if record.qualityFlags.truthUsed
                error('CommunicationEndpointState:truthUsed', ...
                    'A CommunicationEndpointState may never be truth-sourced.');
            end

            if ~strcmp(char(record.coordinateTimeScale), ...
                    revgnss.DistributedLinkProtocolContract.CoordinateTimeScale)
                error('CommunicationEndpointState:coordinateTimeScale', ...
                    'coordinateTimeScale must equal the frozen contract value.');
            end
            if ~strcmp(char(record.frameIdentifier), ...
                    revgnss.DistributedLinkProtocolContract.FrameIdentifier)
                error('CommunicationEndpointState:frameIdentifier', ...
                    'frameIdentifier must equal the frozen contract value.');
            end
            if ~strcmp(char(record.clockDatumIdentifier), ...
                    revgnss.DistributedLinkProtocolContract.ClockDatumIdentifier)
                error('CommunicationEndpointState:clockDatumIdentifier', ...
                    'clockDatumIdentifier must equal the frozen contract value.');
            end
            if ~strcmp(char(record.stateSchemaVersion), ...
                    revgnss.DistributedLinkProtocolContract.StateSchemaVersion)
                error('CommunicationEndpointState:stateSchemaVersion', ...
                    'stateSchemaVersion must equal the frozen contract value.');
            end

            x = record.stateVector(:);
            expectedOrder = revgnss.DistributedLinkProtocolContract.StateSchemaV1StateComponentOrder;
            if ~isequal(record.stateComponentOrder,expectedOrder)
                error('CommunicationEndpointState:stateComponentOrder', ...
                    'stateComponentOrder must equal the frozen v1 state component order.');
            end
            if numel(x) ~= numel(expectedOrder)
                error('CommunicationEndpointState:stateVector', ...
                    'stateVector must carry exactly the v1 state components.');
            end
            matchesEuler = isequal(record.covarianceComponentOrder, ...
                revgnss.DistributedLinkProtocolContract.StateSchemaV1CovarianceComponentOrderEuler);
            matchesTangent = isequal(record.covarianceComponentOrder, ...
                revgnss.DistributedLinkProtocolContract.StateSchemaV1CovarianceComponentOrderTangent);
            if ~(matchesEuler || matchesTangent)
                error('CommunicationEndpointState:covarianceComponentOrder', ...
                    'covarianceComponentOrder must equal a frozen v1 variant.');
            end
            variant = 'euler';
            if matchesTangent; variant = 'tangent'; end
            allowedConventions = ...
                revgnss.DistributedLinkProtocolContract.AllowedAttitudeErrorCoordinateConventions;
            if ~(ischar(record.attitudeErrorCoordinateConvention) || ...
                    (isstring(record.attitudeErrorCoordinateConvention) && ...
                    isscalar(record.attitudeErrorCoordinateConvention))) || ...
                    ~any(strcmp(char(record.attitudeErrorCoordinateConvention),allowedConventions))
                error('CommunicationEndpointState:attitudeConvention', ...
                    'attitudeErrorCoordinateConvention must be a frozen attitude-error convention.');
            end
            declaredConvention = char(record.attitudeErrorCoordinateConvention);
            conventionMatchesVariant = ...
                (strcmp(variant,'euler') && strcmp(declaredConvention,'eulerZYXError_rad')) || ...
                (strcmp(variant,'tangent') && ...
                strcmp(declaredConvention,'rightMultiplicativeLocalTangent_rad'));
            if ~conventionMatchesVariant
                error('CommunicationEndpointState:attitudeConventionMismatch', ...
                    ['attitudeErrorCoordinateConvention (''%s'') does not match the ' ...
                    'covariance label set actually carried by this state (''%s'').'], ...
                    declaredConvention,variant);
            end

            P = record.covarianceBlock;
            if isempty(x) || any(~isfinite(x)) || ~isnumeric(P) || ...
                    size(P,1) ~= numel(x) || size(P,2) ~= numel(x) || ...
                    any(~isfinite(P),'all') || norm(P-P','fro') > 1e-10 || ...
                    min(eig((P+P')/2)) < -1e-10
                error('CommunicationEndpointState:covariance', ...
                    'covarianceBlock must be finite, symmetric, PSD, and state-error aligned.');
            end

            if ~(isnumeric(record.positionEcef_m) && numel(record.positionEcef_m) == 3 && ...
                    isnumeric(record.velocityEcef_mps) && numel(record.velocityEcef_mps) == 3 && ...
                    isnumeric(record.attitudeEulerZyx_rad) && ...
                    numel(record.attitudeEulerZyx_rad) == 3 && ...
                    isnumeric(record.angularRateBody_radps) && ...
                    numel(record.angularRateBody_radps) == 3 && ...
                    isnumeric(record.clockBias_m) && isscalar(record.clockBias_m) && ...
                    isnumeric(record.clockDriftRate_mps) && isscalar(record.clockDriftRate_mps))
                error('CommunicationEndpointState:componentShape', ...
                    'Component fields must have the fixed v1 shapes.');
            end
            componentsFromVector = [record.positionEcef_m(:);record.velocityEcef_mps(:); ...
                record.attitudeEulerZyx_rad(:);record.angularRateBody_radps(:); ...
                record.clockBias_m;record.clockDriftRate_mps];
            if ~isequal(componentsFromVector,x)
                error('CommunicationEndpointState:componentConsistency', ...
                    'The named components must equal the corresponding stateVector entries exactly.');
            end

            allowedPolicies = ...
                revgnss.CommunicationEndpointStateProvider.AllowedStateEvaluationPolicies;
            if ~(ischar(record.stateEvaluationPolicy) || ...
                    (isstring(record.stateEvaluationPolicy) && ...
                    isscalar(record.stateEvaluationPolicy))) || ...
                    ~any(strcmp(char(record.stateEvaluationPolicy),allowedPolicies))
                error('CommunicationEndpointState:evaluationPolicy', ...
                    'stateEvaluationPolicy must be a frozen evaluation policy.');
            end

            if ~(isstruct(record.productProvenance) && ...
                    isfield(record.productProvenance,'productAge_s') && ...
                    isnumeric(record.productProvenance.productAge_s) && ...
                    isscalar(record.productProvenance.productAge_s) && ...
                    record.productProvenance.productAge_s == 0)
                error('CommunicationEndpointState:productAge', ...
                    'productProvenance.productAge_s must be exactly 0 in the initial scope.');
            end

            terminal = record.terminalGeometry;
            requiredTerminalFields = {'declared','transmitTerminalIdentifier', ...
                'receiveTerminalIdentifier','transmitAntennaIdentifier', ...
                'receiveAntennaIdentifier','transmitPhaseCentreOffset_body_m', ...
                'receivePhaseCentreOffset_body_m'};
            if ~isstruct(terminal) || ...
                    ~isempty(setdiff(requiredTerminalFields,fieldnames(terminal))) || ...
                    ~isempty(setdiff(fieldnames(terminal),requiredTerminalFields)) || ...
                    ~(islogical(terminal.declared) && isscalar(terminal.declared))
                error('CommunicationEndpointState:terminalGeometry', ...
                    'terminalGeometry must declare exactly the frozen fields.');
            end
            if ~terminal.declared
                if ~(isequal(terminal.transmitPhaseCentreOffset_body_m,zeros(3,1)) && ...
                        isequal(terminal.receivePhaseCentreOffset_body_m,zeros(3,1)) && ...
                        strcmp(char(terminal.transmitTerminalIdentifier),'terminal:undeclared') && ...
                        strcmp(char(terminal.receiveTerminalIdentifier),'terminal:undeclared') && ...
                        strcmp(char(terminal.transmitAntennaIdentifier),'antenna:undeclared') && ...
                        strcmp(char(terminal.receiveAntennaIdentifier),'antenna:undeclared'))
                    error('CommunicationEndpointState:terminalGeometry', ...
                        'An undeclared terminal geometry must use the frozen zero/undeclared markers.');
                end
            else
                % A declared geometry's phase-centre offsets are metre-valued body-frame lever
                % arms that a Section 2.3 adapter feeds directly into the range equation
                % (revgnss.TwoWayCodeEndpointModel.transmit/receivePhaseCentreAt): they must be
                % validated here with the same rigor as any other component field, not merely
                % assigned through.
                if ~(isnumeric(terminal.transmitPhaseCentreOffset_body_m) && ...
                        isequal(size(terminal.transmitPhaseCentreOffset_body_m),[3 1]) && ...
                        all(isfinite(terminal.transmitPhaseCentreOffset_body_m)) && ...
                        isnumeric(terminal.receivePhaseCentreOffset_body_m) && ...
                        isequal(size(terminal.receivePhaseCentreOffset_body_m),[3 1]) && ...
                        all(isfinite(terminal.receivePhaseCentreOffset_body_m)))
                    error('CommunicationEndpointState:terminalGeometry', ...
                        ['A declared terminal geometry must carry finite 3-by-1 ' ...
                        'transmit/receivePhaseCentreOffset_body_m lever arms.']);
                end
                identifierFields = {'transmitTerminalIdentifier','receiveTerminalIdentifier', ...
                    'transmitAntennaIdentifier','receiveAntennaIdentifier'};
                for index = 1:numel(identifierFields)
                    value = terminal.(identifierFields{index});
                    if ~((ischar(value) || (isstring(value) && isscalar(value))) && ...
                            ~isempty(strtrim(char(value))))
                        error('CommunicationEndpointState:terminalGeometry', ...
                            'A declared terminal geometry must carry a nonempty %s.', ...
                            identifierFields{index});
                    end
                end
            end

            obj.endpointIdentifier = char(record.endpointIdentifier);
            obj.canonicalPhysicalAssetIndex = double(record.canonicalPhysicalAssetIndex);
            obj.stateSource = char(record.stateSource);
            obj.stateOrigin = char(record.stateOrigin);
            obj.coordinateEpoch_s = double(record.coordinateEpoch_s);
            obj.stateEvaluationPolicy = char(record.stateEvaluationPolicy);
            obj.coordinateTimeScale = char(record.coordinateTimeScale);
            obj.frameIdentifier = char(record.frameIdentifier);
            obj.clockDatumIdentifier = char(record.clockDatumIdentifier);
            obj.stateSchemaVersion = char(record.stateSchemaVersion);
            obj.attitudeErrorCoordinateConvention = char(record.attitudeErrorCoordinateConvention);
            obj.stateComponentOrder = cellfun(@char,record.stateComponentOrder,'UniformOutput',false);
            obj.covarianceComponentOrder = cellfun(@char,record.covarianceComponentOrder, ...
                'UniformOutput',false);
            obj.stateVector = x;
            obj.covarianceBlock = (P+P')/2;
            obj.positionEcef_m = record.positionEcef_m(:);
            obj.velocityEcef_mps = record.velocityEcef_mps(:);
            obj.attitudeEulerZyx_rad = record.attitudeEulerZyx_rad(:);
            obj.angularRateBody_radps = record.angularRateBody_radps(:);
            obj.clockBias_m = double(record.clockBias_m);
            obj.clockDriftRate_mps = double(record.clockDriftRate_mps);
            obj.terminalGeometry = terminal;
            obj.productProvenance = record.productProvenance;
            obj.qualityFlags = record.qualityFlags;
            obj.clockAnchorDeclaration = record.clockAnchorDeclaration;
        end

        function s = toStruct(obj)
            s = struct();
            names = properties(obj);
            for index = 1:numel(names)
                if strcmp(names{index},'clockAnchorDeclaration')
                    s.(names{index}) = obj.(names{index}).toStruct();
                else
                    s.(names{index}) = obj.(names{index});
                end
            end
        end
    end
end
