classdef FourTimestampClockDifferenceLinkUpdateAdapter
    % FourTimestampClockDifferenceLinkUpdateAdapter  Plan Section 4.4: the 5th
    % revgnss.DistributedLinkUpdateAdapter, for the direct four-timestamp ISL clock-difference
    % observable. Reuses revgnss.FourTimestampObservableLinearization.islTwoEndpointJacobian for
    % all physics; this file contains no light-time equation, no FD stencil, and no turnaround
    % algebra of its own.
    %
    % ownerRole is hardcoded 'origin' -- a design choice, not a discovered necessity:
    % revgnss.InterSatelliteFourTimestampObservationRecord's referenceAssetIdentifier field is
    % DEFINED to be the link's initiator (t1-transmitting) endpoint, and the sanctioned tuple
    % already forces ownerPolicy='initiator' (+revgnss/IndependentFleetCoordinator.m), so
    % owner==origin holds by construction -- never re-derived per delivery.
    %
    % R-VALUE: FLAT, DECLARED sigma_m, NOT A PHYSICAL MULTI-TERM REDUCTION.
    % revgnss.FourTimestampClockDifferenceObservable's own header explicitly hands "reducing
    % rawCovarianceBlock into a scalar variance" to "a future Section 4.4 adapter" without
    % requiring it be solved now. Given this project's own track record of catching two real
    % sign/unit bugs in exactly this class of derivation (Section 4.2's m^2-vs-s^2 mislabeling;
    % Section 4.3's factor-of-c error in revgnss.FourTimestampObservableLinearization.
    % calibrationMappingJacobian), this release uses a flat, independently-declared sigma_m,
    % matching revgnss.FirstOrderReciprocalClockTransferLinkUpdateAdapter/
    % revgnss.CoherentTwoWayRangeLinkUpdateAdapter's own precedent of a config-declared scalar R.
    % A real closed-form multi-term reduction (tag-noise -> allocation -> atmosphere/calibration
    % weight mapping) is out of scope this stage.

    properties (Constant)
        ObservableIdentifier = 'fourTimestampClockDifference';
        SupportedPhysicalRecordClasses = {'revgnss.InterSatelliteFourTimestampObservationRecord'};
        SupportedProtocolIdentifier = 'directFourTimestampTwoWay';
        SupportedProcessedObservableType = 'fourTimestampClockDifference';
        SupportedProcessedUnits = 'm';
        ReferenceEpochRule = 'finalReception';
        SupportedModeIdentifier = 'fourTimestampClockDifference';
        RequiredPersistentCalibrationTreatment = 'rejected';
        ReciprocityTermSupported = false;
        RawTimestampTagsSupported = true;
    end

    methods (Static)
        function [block, diagnostics] = buildUpdateBlock(args)
            required = {'delivery','ownerState','remoteState','calibrationProduct', ...
                'linearizationSteps','solverOptions','weightSelectionRule', ...
                'persistentCalibrationTreatment'};
            if ~isstruct(args) || ~isscalar(args)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:argsSchema', ...
                    'buildUpdateBlock requires a scalar struct.');
            end
            missing = setdiff(required,fieldnames(args));
            unknown = setdiff(fieldnames(args),required);
            if ~isempty(missing)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:argsSchema', ...
                    'buildUpdateBlock is missing argument %s.',missing{1});
            end
            if ~isempty(unknown)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:argsSchema', ...
                    'buildUpdateBlock received unsupported argument %s.',unknown{1});
            end

            delivery = args.delivery;
            ownerState = args.ownerState;
            remoteState = args.remoteState;
            if ~isa(delivery,'revgnss.LinkObservationDelivery')
                error('FourTimestampClockDifferenceLinkUpdateAdapter:deliveryType', ...
                    'delivery must be a revgnss.LinkObservationDelivery.');
            end
            record = delivery.physicalObservationRecord;
            revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.requireSupportedRecord(record);

            revgnss.CommunicationEndpointStateProvider.requireSameEpochPair( ...
                ownerState, remoteState, delivery.coordinateEventEpoch_s);
            revgnss.CommunicationEndpointStateProvider.requireCompatibleCovarianceCoordinates( ...
                ownerState, remoteState);
            revgnss.CommunicationEndpointStateProvider.requireTerminalGeometryDeclared(ownerState);
            revgnss.CommunicationEndpointStateProvider.requireTerminalGeometryDeclared(remoteState);
            revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.requireTerminalGeometryMatchesRecord( ...
                ownerState, record, 'owner');
            revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.requireTerminalGeometryMatchesRecord( ...
                remoteState, record, 'remote');

            treatment = char(args.persistentCalibrationTreatment);
            if ~strcmp(treatment, ...
                    revgnss.FourTimestampClockDifferenceLinkUpdateAdapter. ...
                    RequiredPersistentCalibrationTreatment)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:persistentCalibrationTreatment', ...
                    'This adapter release supports only persistentCalibrationTreatment=''rejected''.');
            end
            if ~strcmp(treatment, delivery.persistentCalibrationTreatment)
                error(['FourTimestampClockDifferenceLinkUpdateAdapter:' ...
                    'persistentCalibrationTreatmentMismatch'], ...
                    'persistentCalibrationTreatment must equal the delivery''s own declared treatment.');
            end

            if ownerState.canonicalPhysicalAssetIndex ~= delivery.ownerCanonicalIndex || ...
                    remoteState.canonicalPhysicalAssetIndex ~= delivery.remoteCanonicalIndex
                error('FourTimestampClockDifferenceLinkUpdateAdapter:canonicalIndexMismatch', ...
                    'An endpoint state''s canonical physical asset index does not match its delivery.');
            end

            hardware = args.calibrationProduct;
            if ~isa(hardware,'revgnss.ReciprocalLinkHardwareModel')
                error('FourTimestampClockDifferenceLinkUpdateAdapter:calibrationProductType', ...
                    'calibrationProduct must be a revgnss.ReciprocalLinkHardwareModel.');
            end
            hardware.assertParameterSource('calibrationProduct');

            ownerModel = revgnss.FourTimestampEstimatorEndpointBridge.fromCommunicationEndpointState( ...
                ownerState, delivery.ownerRecordEndpointIdentifier);
            remoteModel = revgnss.FourTimestampEstimatorEndpointBridge.fromCommunicationEndpointState( ...
                remoteState, delivery.remoteRecordEndpointIdentifier);
            [predictedValue_m,~] = revgnss.FourTimestampObservableBuilder.predictFromEndpointModels( ...
                ownerModel, remoteModel, hardware, delivery.coordinateEventEpoch_s, ...
                struct('solverOptions',args.solverOptions));
            residual_m = record.processedValue - predictedValue_m;

            options = struct('linearizationSteps',args.linearizationSteps, ...
                'solverOptions',args.solverOptions);
            [H_owner, H_remote, ~, ~, ~] = ...
                revgnss.FourTimestampObservableLinearization.islTwoEndpointJacobian( ...
                ownerState, remoteState, 'origin', hardware, delivery.coordinateEventEpoch_s, options);

            Rind = record.covarianceBlock(record.covarianceRowIndex, record.covarianceRowIndex);
            if ~(isfinite(Rind) && Rind > 0)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:measurementCovariance', ...
                    'The record''s own-row measurement covariance must be finite and positive.');
            end
            remoteContribution_m2 = H_remote * remoteState.covarianceBlock * H_remote';
            remoteContribution_m2 = (remoteContribution_m2+remoteContribution_m2')/2;

            record_ = struct( ...
                'observationIdentifier',delivery.observationIdentifier, ...
                'deliveryIdentifier',delivery.deliveryIdentifier, ...
                'ownerAssetIdentifier',delivery.ownerAssetIdentifier, ...
                'remoteAssetIdentifier',delivery.remoteAssetIdentifier, ...
                'remoteProductIdentifier',delivery.remoteProductIdentifier, ...
                'coordinateEventEpoch_s',delivery.coordinateEventEpoch_s, ...
                'observableIdentifier',revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.ObservableIdentifier, ...
                'residual_m',residual_m, ...
                'ownerCovarianceComponentOrder',{ownerState.covarianceComponentOrder}, ...
                'remoteCovarianceComponentOrder',{remoteState.covarianceComponentOrder}, ...
                'ownerAttitudeErrorCoordinateConvention',ownerState.attitudeErrorCoordinateConvention, ...
                'remoteAttitudeErrorCoordinateConvention',remoteState.attitudeErrorCoordinateConvention, ...
                'ownerJacobian_mPerErrorUnit',H_owner, ...
                'remoteJacobian_mPerErrorUnit',H_remote, ...
                'independentMeasurementCovariance_m2',Rind, ...
                'remoteContributionCovariance_m2',remoteContribution_m2, ...
                'residualCovarianceAssembly','notAssembledInputsEligibleForSplitCovarianceIntersection', ...
                'persistentCalibrationTreatment',treatment, ...
                'calibrationStateIdentifiers',{{}}, ...
                'covarianceGroupIdentifiers',{{}}, ...
                'correlationPolicy','splitCovarianceIntersection', ...
                'weightSelectionRule',char(args.weightSelectionRule), ...
                'commonSourceContributionCovariances_m2',{{}}, ...
                'calibrationMappingJacobian_mPerCalibrationUnit',zeros(1,0), ...
                'calibrationStateUnits',{{}}, ...
                'persistentCalibrationReferenceLocalTag_s',NaN, ...
                'observableRowUnits','m');
            block = revgnss.DistributedLinkUpdateBlock(record_);

            diagnostics = struct('predictedValue_m',predictedValue_m);
        end

        function text = describeObservable()
            text = struct( ...
                'observableIdentifier',revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.ObservableIdentifier, ...
                'protocolIdentifier', ...
                    revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.SupportedProtocolIdentifier, ...
                'residualSignConvention','observedMinusPredicted', ...
                'jacobianQuantity','dPredictedObservablePerErrorCoordinate', ...
                'referenceEpochRule',revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.ReferenceEpochRule, ...
                'stencilIdentifier','fivePointCentral');
        end

        function requireSupportedRecord(record)
            if ~isa(record,'revgnss.InterSatelliteFourTimestampObservationRecord')
                error('FourTimestampClockDifferenceLinkUpdateAdapter:recordType', ...
                    'This adapter requires a revgnss.InterSatelliteFourTimestampObservationRecord.');
            end
            if ~strcmp(record.protocolIdentifier, ...
                    revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.SupportedProtocolIdentifier)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:protocol', ...
                    'Record protocolIdentifier does not match this adapter''s supported protocol.');
            end
            if ~strcmp(record.processedObservableType, ...
                    revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.SupportedProcessedObservableType) || ...
                    ~strcmp(record.processedUnits, ...
                    revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.SupportedProcessedUnits)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:processedObservableType', ...
                    'Record processedObservableType/processedUnits do not match this adapter.');
            end
            if ~strcmp(record.referenceEpochRule, ...
                    revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.ReferenceEpochRule)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:referenceEpochRule', ...
                    'Record referenceEpochRule does not match this adapter''s supported rule.');
            end
            if ~strcmp(record.modeIdentifier, ...
                    revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.SupportedModeIdentifier)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:mode', ...
                    'Record modeIdentifier does not match this adapter''s supported mode.');
            end
            if ~record.rawTimestampTagsAvailable
                error('FourTimestampClockDifferenceLinkUpdateAdapter:rawTimestampTagsRequired', ...
                    ['A fourTimestampClockDifference record must declare rawTimestampTagsAvailable=true ' ...
                    '(the inverse of firstOrderReciprocalClockTransfer''s always-false convention).']);
            end
            if record.reciprocityTermIncluded && ...
                    ~revgnss.FourTimestampClockDifferenceLinkUpdateAdapter.ReciprocityTermSupported
                error('FourTimestampClockDifferenceLinkUpdateAdapter:reciprocityTermUnsupported', ...
                    'The reciprocity term is not supported by this adapter release.');
            end
            if ~record.available
                error('FourTimestampClockDifferenceLinkUpdateAdapter:recordUnavailable', ...
                    'The physical record is not available.');
            end
            idx = record.covarianceRowIndex;
            n = size(record.covarianceBlock,1);
            if ~(isnumeric(idx) && isscalar(idx) && idx == round(idx) && idx >= 1 && idx <= n)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:covarianceRowIndex', ...
                    'Record covarianceRowIndex is out of range for its own covarianceBlock.');
            end
        end

        function requireTerminalGeometryMatchesRecord(endpointState, record, role)
            if ~(ischar(role) && any(strcmp(role,{'owner','remote'})))
                error('FourTimestampClockDifferenceLinkUpdateAdapter:role', ...
                    'role must be ''owner'' or ''remote''.');
            end
            terminal = endpointState.terminalGeometry;
            if strcmp(role,'owner')
                txTerminal = record.referenceTransmitTerminalIdentifier;
                rxTerminal = record.referenceReceiveTerminalIdentifier;
                txAntenna = record.referenceTransmitAntennaIdentifier;
                rxAntenna = record.referenceReceiveAntennaIdentifier;
            else
                txTerminal = record.remoteTransmitTerminalIdentifier;
                rxTerminal = record.remoteReceiveTerminalIdentifier;
                txAntenna = record.remoteTransmitAntennaIdentifier;
                rxAntenna = record.remoteReceiveAntennaIdentifier;
            end
            if ~strcmp(terminal.transmitTerminalIdentifier,txTerminal) || ...
                    ~strcmp(terminal.receiveTerminalIdentifier,rxTerminal) || ...
                    ~strcmp(terminal.transmitAntennaIdentifier,txAntenna) || ...
                    ~strcmp(terminal.receiveAntennaIdentifier,rxAntenna)
                error('FourTimestampClockDifferenceLinkUpdateAdapter:terminalGeometryMismatch', ...
                    ['The %s endpoint''s declared terminal geometry does not match the record''s own ' ...
                    'terminal/antenna identifiers.'],role);
            end
        end
    end
end
