classdef InterSatelliteFourTimestampTimeTransferBuilder
    % InterSatelliteFourTimestampTimeTransferBuilder  Plan Section 4.4: the ISL truth-side
    % generator for the direct four-timestamp clock-difference observable. Reuses
    % revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg) VERBATIM for link identity,
    % schedule, signal/channel (item 4), and revgnss.DirectReciprocalTimeTransferBuilder.buildFromIsl
    % (Section 4.2) + revgnss.FourTimestampObservableBuilder.fromExchangeRecord (Section 4.3) for
    % the physics -- this file contains no light-time equation of its own.
    %
    % Serves ONLY the distributed-fleet sanctioned-observable path
    % (revgnss.IndependentFleetCoordinator, via revgnss.FourTimestampClockDifferenceLinkUpdateAdapter):
    % unlike revgnss.InterSatelliteTimeTransferBuilder, this class has no
    % linearizeRecordedObservation(s)/predictEkfRows counterpart, because
    % revgnss.InterSatelliteTimeTransferObservationRecord's frozen protocol/mode vocabulary
    % (enforced by revgnss.ReciprocalTimeTransferModel.validateMode) is structurally incapable of
    % carrying raw-tag physics regardless of what string is placed in .mode -- confirmed by direct
    % read of that class's constructor. Extending four-timestamp ISL physics to the legacy joint-
    % mode EKF is a real, deferred capability gap (a third state-container adapter shape would be
    % required), not silently declined.

    methods (Static)
        function validateConfig(cfg)
            % validateConfig  Scoped to the sanctioned tuple, mirroring
            % revgnss.OneWayInterSatelliteObservationBuilder.validateConfig's own precedent
            % (+revgnss/IndependentFleetCoordinator.m's requireSanctionedIslConfiguration_ is the
            % ONLY caller -- this is never reached from revgnss.ConfigFactory.finalizeConfig,
            % since the sanctioned-tuple gate already owns this observable's reachability).
            info = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.info_(cfg);
            if ~(isfinite(info.sigma_m) && info.sigma_m > 0)
                error('InterSatelliteFourTimestampTimeTransferBuilder:sigma', ...
                    'measurements.isl.twoWay.fourTimestampPhysical.sigma_m must be a positive scalar.');
            end
            if ~any(strcmp(info.terminalDelayAllocation, ...
                    revgnss.FourTimestampObservableBuilder.AllowedTerminalDelayAllocations))
                error('InterSatelliteFourTimestampTimeTransferBuilder:terminalDelayAllocation', ...
                    'terminalDelayAllocation must be a frozen allocation.');
            end
            if ~(isfinite(info.carrierFrequency_Hz) && info.carrierFrequency_Hz > 0)
                error('InterSatelliteFourTimestampTimeTransferBuilder:carrierFrequency', ...
                    'measurements.isl.twoWay.fourTimestampPhysical.carrierFrequency_Hz must be a positive scalar.');
            end
            % Combined-review M4: counterTag.sigma_s is passed into revgnss.
            % DirectReciprocalTimeTransferBuilder.buildFromIsl only to build the TRUTH exchange
            % record's OWN covarianceBlock -- generateObservations below then discards that block
            % entirely and sets the OBSERVATION record's covarianceBlock to info.sigma_m^2
            % directly, so a nonzero declared counterTag.sigma_s never reaches
            % revgnss.FourTimestampClockDifferenceLinkUpdateAdapter's Rind at all. Refuse rather
            % than accept-and-drop, mirroring the ground-space host's own guard.
            if any(info.counterTagSigma_s(:) ~= 0)
                error('InterSatelliteFourTimestampTimeTransferBuilder:counterTagNoiseNotWired', ...
                    ['measurements.isl.twoWay.fourTimestampPhysical.counterTag.sigma_s is not ' ...
                    'wired into the observation record''s reported covariance and must stay ' ...
                    'all-zero.']);
            end
            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            nAssets = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.numericPath_( ...
                cfg,{'scenario','nSpaceAssets'},1);
            for linkIndex = 1:numel(links)
                endpoints = [links(linkIndex).initiatorAssetIndex,links(linkIndex).transponderAssetIndex];
                if any(endpoints ~= round(endpoints)) || any(endpoints < 1) || any(endpoints > nAssets) || ...
                        endpoints(1) == endpoints(2)
                    error('InterSatelliteFourTimestampTimeTransferBuilder:endpoints', ...
                        'Each four-timestamp ISL link requires two distinct configured spacecraft.');
                end
            end
        end

        function [observations,truthDiagnostics,info] = generateObservations(cfg,assets,t_s)
            observations = {};
            truthDiagnostics = {};
            linkInfos = {};
            info = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.info_(cfg);
            hardware = revgnss.FourTimestampPhysicalLinkConfig.hardwareModel(cfg,'isl','physicalTruth');
            links = revgnss.TwoWayISLMeasurementBuilder.linkDefinitions(cfg);
            for linkIndex = 1:numel(links)
                link = links(linkIndex);
                if ~revgnss.InterSatelliteFourTimestampTimeTransferBuilder.scheduled_(cfg,link,t_s)
                    continue
                end
                originIdx = link.initiatorAssetIndex;
                destinationIdx = link.transponderAssetIndex;
                if max(originIdx,destinationIdx) > numel(assets)
                    error('InterSatelliteFourTimestampTimeTransferBuilder:endpointAsset', ...
                        'A configured four-timestamp ISL endpoint is unavailable.');
                end
                originGeometry = revgnss.FourTimestampPhysicalLinkConfig.shortNameIslTerminalGeometry( ...
                    cfg,originIdx);
                destinationGeometry = revgnss.FourTimestampPhysicalLinkConfig.shortNameIslTerminalGeometry( ...
                    cfg,destinationIdx);

                epochIndex = round(t_s/max(revgnss.InterSatelliteFourTimestampTimeTransferBuilder.numericPath_( ...
                    cfg,{'simulation','dt_s'},1),eps));
                exchangeIdentifier = sprintf('%s:four-timestamp:e%09d',link.linkIdentifier,epochIndex);
                record = revgnss.DirectReciprocalTimeTransferBuilder.buildFromIsl( ...
                    assets{originIdx},originIdx,originGeometry, ...
                    assets{destinationIdx},destinationIdx,destinationGeometry, ...
                    hardware,t_s, ...
                    exchangeIdentifier=exchangeIdentifier, ...
                    sessionIdentifier=sprintf('%s:session:e%09d',link.linkIdentifier,epochIndex), ...
                    protocolIdentifier='directFourTimestampTwoWay', ...
                    signalIdentifier=link.signalIdentifier, ...
                    channelIdentifier=link.channelIdentifier, ...
                    carrierFrequency_Hz=info.carrierFrequency_Hz, ...
                    counterTagSigma_s=info.counterTagSigma_s,counterTagLabels=info.counterTagLabels, ...
                    truthDiagnosticIdentifier=[exchangeIdentifier '-truth']);
                observable = revgnss.FourTimestampObservableBuilder.fromExchangeRecord( ...
                    record,hardware,struct('terminalDelayAllocation',info.terminalDelayAllocation));

                noise_m = info.sigma_m * revgnss.InterSatelliteFourTimestampTimeTransferBuilder.drawNormal_( ...
                    cfg,originIdx,destinationIdx,epochIndex);
                observationIdentifier = sprintf('%s:four-timestamp:e%09d',link.linkIdentifier,epochIndex);
                fields = struct( ...
                    'observationIdentifier',observationIdentifier, ...
                    'sessionIdentifier',sprintf('%s:session:e%09d',link.linkIdentifier,epochIndex), ...
                    'linkIdentifier',link.linkIdentifier, ...
                    'referenceAssetIdentifier',sprintf('asset:%d',originIdx), ...
                    'remoteAssetIdentifier',sprintf('asset:%d',destinationIdx), ...
                    'referenceTransmitTerminalIdentifier',originGeometry.transmitTerminalIdentifier, ...
                    'referenceReceiveTerminalIdentifier',originGeometry.receiveTerminalIdentifier, ...
                    'referenceTransmitAntennaIdentifier',originGeometry.transmitAntennaIdentifier, ...
                    'referenceReceiveAntennaIdentifier',originGeometry.receiveAntennaIdentifier, ...
                    'remoteTransmitTerminalIdentifier',destinationGeometry.transmitTerminalIdentifier, ...
                    'remoteReceiveTerminalIdentifier',destinationGeometry.receiveTerminalIdentifier, ...
                    'remoteTransmitAntennaIdentifier',destinationGeometry.transmitAntennaIdentifier, ...
                    'remoteReceiveAntennaIdentifier',destinationGeometry.receiveAntennaIdentifier, ...
                    'protocolIdentifier','directFourTimestampTwoWay', ...
                    'modeIdentifier','fourTimestampClockDifference', ...
                    'signalIdentifier',link.signalIdentifier, ...
                    'channelIdentifier',link.channelIdentifier, ...
                    'referenceEpoch_s',t_s, ...
                    'referenceEpochRule','finalReception', ...
                    'rawTimestampTagsAvailable',true, ...
                    'timestampTags_s',record.localClockTags_s, ...
                    'processedObservableType','fourTimestampClockDifference', ...
                    'processedValue',observable.clockDifferenceValue_m+noise_m, ...
                    'processedUnits','m', ...
                    'covarianceGroupIdentifier',observationIdentifier, ...
                    'covarianceRowIndex',1, ...
                    'covarianceBlock',info.sigma_m^2, ...
                    'covarianceUnits','m^2', ...
                    'calibrationProductIdentifiers',{{hardware.calibrationProductIdentifier}}, ...
                    'available',true, ...
                    'qualityFlags',struct('scheduled',true,'rawTimestampTagsAvailable',true, ...
                        'physicalFourEventModelApplied',true), ...
                    'truthDiagnosticIdentifier',[observationIdentifier '-truth'], ...
                    'referenceLocalClockTag_s',record.localClockTags_s(4), ...
                    'calibrationValidFromLocalTag_s',hardware.validFromLocalTag_s, ...
                    'calibrationValidUntilLocalTag_s',hardware.validUntilLocalTag_s, ...
                    'reciprocityTermIncluded',false);
                observation = revgnss.InterSatelliteFourTimestampObservationRecord(fields);

                diagnostic = struct( ...
                    'diagnosticIdentifier',[observationIdentifier '-truth'], ...
                    'originAssetIndex',originIdx,'destinationAssetIndex',destinationIdx, ...
                    'clockDifferenceTruth_m',observable.clockDifferenceValue_m, ...
                    'thermalError_m',noise_m);
                linkInfo = struct('linkDefinitionIndex',linkIndex,'observationRecord',observation, ...
                    'truthDiagnostic',diagnostic,'nRows',1,'nEkfRows',0,'ekfRowTypes',{{}}, ...
                    'eligibleObservationRecords',{{}});
                observations{end+1} = observation; %#ok<AGROW>
                truthDiagnostics{end+1} = diagnostic; %#ok<AGROW>
                linkInfos{end+1} = linkInfo; %#ok<AGROW>
            end
            info.linkInfos = linkInfos;
        end
    end

    methods (Static, Access = private)
        function info = info_(cfg)
            info = struct( ...
                'sigma_m',revgnss.InterSatelliteFourTimestampTimeTransferBuilder.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','fourTimestampPhysical','sigma_m'},0.03), ...
                'terminalDelayAllocation',revgnss.InterSatelliteFourTimestampTimeTransferBuilder.textPath_( ...
                    cfg,{'measurements','isl','twoWay','fourTimestampPhysical','terminalDelayAllocation'}, ...
                    'receiveEvent'), ...
                'carrierFrequency_Hz',revgnss.InterSatelliteFourTimestampTimeTransferBuilder.numericPath_( ...
                    cfg,{'measurements','isl','twoWay','fourTimestampPhysical','carrierFrequency_Hz'},26e9), ...
                'counterTagSigma_s',revgnss.InterSatelliteFourTimestampTimeTransferBuilder.vectorPath_( ...
                    cfg,{'measurements','isl','twoWay','fourTimestampPhysical','counterTag','sigma_s'}, ...
                    zeros(1,4)), ...
                'counterTagLabels',{revgnss.InterSatelliteFourTimestampTimeTransferBuilder.cellPath_( ...
                    cfg,{'measurements','isl','twoWay','fourTimestampPhysical','counterTag','labels'}, ...
                    {'t1','t2','t3','t4'})});
        end

        function scheduled = scheduled_(cfg,link,t_s)
            % scheduled_  Duplicated from revgnss.InterSatelliteTimeTransferBuilder.scheduled_
            % (private to that class): the SAME cfg.measurements.isl.twoWay.schedule.* fields
            % apply (item 4, no separate schedule concept for this observable), minus that
            % method's own timeTransfer.warmup_s concern (this observable declares none).
            start_s = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.numericPath_( ...
                cfg,{'measurements','isl','twoWay','schedule','start_s'},0);
            stop_s = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.numericPath_( ...
                cfg,{'measurements','isl','twoWay','schedule','stop_s'},1e12);
            if t_s < start_s || t_s > stop_s
                scheduled = false;
                return
            end
            outages = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.vectorPath_( ...
                cfg,{'measurements','isl','twoWay','schedule','outages_s'},zeros(0,2));
            if ~isempty(outages) && any(t_s >= outages(:,1) & t_s <= outages(:,2))
                scheduled = false;
                return
            end
            period_s = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.numericPath_( ...
                cfg,{'measurements','isl','twoWay','schedule','updatePeriod_s'},1);
            phase_s = link.schedule.updatePhase_s;
            dt_s = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.numericPath_( ...
                cfg,{'simulation','dt_s'},1);
            remainder = mod(t_s-phase_s,period_s);
            scheduled = min(remainder,period_s-remainder) <= 10*eps(max(1,period_s)) + dt_s*1e-10;
        end

        function value = drawNormal_(cfg,originIdx,destinationIdx,epochIndex)
            seed = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.numericPath_( ...
                cfg,{'simulation','seed'},42);
            stream = RandStream('mt19937ar','Seed',mod( ...
                seed+2600003+4001*originIdx+7919*destinationIdx+104729*epochIndex,2^31-1));
            value = randn(stream,1,1);
        end

        function value = numericPath_(cfg, path, defaultValue)
            value = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.walk_(cfg,path,defaultValue);
            if ~isnumeric(value) || ~isscalar(value); value = defaultValue; end
        end

        function value = textPath_(cfg, path, defaultValue)
            value = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.walk_(cfg,path,defaultValue);
            if ~(ischar(value) || (isstring(value) && isscalar(value))); value = defaultValue; end
            value = char(value);
        end

        function value = vectorPath_(cfg, path, defaultValue)
            value = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.walk_(cfg,path,defaultValue);
        end

        function value = cellPath_(cfg, path, defaultValue)
            value = revgnss.InterSatelliteFourTimestampTimeTransferBuilder.walk_(cfg,path,defaultValue);
            if ~iscell(value); value = defaultValue; end
        end

        function value = walk_(cfg, path, defaultValue)
            value = cfg;
            for index = 1:numel(path)
                if isstruct(value) && isfield(value,path{index})
                    value = value.(path{index});
                else
                    value = defaultValue;
                    return
                end
            end
        end
    end
end
