classdef ReportEquations
    % ReportEquations  Canonical measurement-equation strings for report pages.
    %
    % All methods return cell arrays of char lines.  Used by LatexReportBuilder
    % to build equation pages and by tests to verify equation content.
    methods (Static)

        function lines = codeEquation()
            % codeEquation  Single-frequency code pseudorange model.
            lines = { ...
                'Code pseudorange (single frequency):', ...
                '  P_f = rho + b_rx - b_twr + T + I_f + d_code + eps_P', ...
                '  b_rx  > 0  (receiver clock bias, positive sign)', ...
                '  b_twr     (tower clock bias, subtracted in equation)', ...
                '  T    >= 0  (troposphere delay, positive for code and carrier)', ...
                '  I_f  >= 0  (ionosphere delay, POSITIVE for code)', ...
            };
        end

        function lines = carrierEquation()
            % carrierEquation  Carrier phase pseudorange model (metres).
            lines = { ...
                'Carrier phase (metres):', ...
                '  Phi_f = rho + b_rx - b_twr + T - I_f + B_phi + d_phase + eps_phi', ...
                '          Ionosphere is NEGATIVE for carrier (phase advance).', ...
                '  B_phi = float ambiguity [m]  — no integer fixing in this simulator', ...
                '  Raw L1/L2 carrier rows may be used in ekfFloat when canonical masks enable them', ...
            };
        end

        function lines = ifEquation(cfg)
            % ifEquation  Ionosphere-free code combination.
            %   ifEquation(cfg) uses the band pair the run actually resolved; with no
            %   cfg it falls back to the canonical L-band catalogue. Both coefficients
            %   and the noise amplification are derived, never hardcoded -- the old
            %   literal "2.98" is only true for the GPS L1/L2 pair.
            if nargin < 1; cfg = struct(); end
            % masterConfig's own default is single-frequency (signals.enabled = {'L1'}), so the
            % strict call raises SignalUtils:ionoFreeNeedsTwoSignals on the DEFAULT config and NO
            % single-frequency run could produce a report. Ask instead of assuming; when there is
            % no pair, say so rather than printing coefficients for a combination that was never
            % formed.
            [ifOk_, a, b] = revgnss.SignalUtils.tryIonosphereFreeCoefficients(cfg);
            if ~ifOk_
                a = NaN; b = NaN;
            end
            lines = { ...
                'Ionosphere-free code combination:', ...
                '  P_IF = alpha * P_L1 + beta * P_L2', ...
                sprintf('  alpha = f_L1^2 / (f_L1^2 - f_L2^2) = %.6f', a), ...
                sprintf('  beta  = -f_L2^2/ (f_L1^2 - f_L2^2) = %.6f', b), ...
                '  First-order ionosphere removed; geometry and clocks preserved.', ...
                sprintf('  Noise amplified: sigma_IF ~ %.2f * sigma_L1', sqrt(a^2 + b^2)), ...
            };
        end

        function lines = zwdContribution()
            % zwdContribution  ZWD state H column for perTowerZwd mode.
            lines = { ...
                'ZWD state contribution (perTowerZwd mode):', ...
                '  h_zwd = m_w(el) * ZWD     [m_w = wet mapping function]', ...
                '  H_zwd = m_w(el)            [Jacobian column for ZWD state]', ...
            };
        end

    end
end
