classdef SynchronizedPairLinkUpdateTransaction
    % SynchronizedPairLinkUpdateTransaction  The two-phase-commit atomicity mechanism for plan
    % Stage 3.2 items 6-7 ("mark the original observation consumed only after both endpoint
    % deliveries are acknowledged"; "reject partial delivery instead of applying a half
    % update"). Pure static; no handle of its own.
    %
    % Genuinely atomic, not conventionally atomic: phases 1-2 mutate NOTHING at all (message
    % assembly and cross-block staging are both pure/validating, and prepareAcknowledgement
    % never writes), so every foreseeable refusal (fingerprint drift, digest mismatch, ledger
    % already holds the record, non-PSD posterior, stale revision, missing cross block) is a
    % REFUSAL BEFORE ANY WRITE. "Reject partial delivery" is the normal path here, not an
    % exception path. Only phases 3-4 (commitAcknowledgedPairUpdate) ever mutate anything, and
    % that mutation is journaled and verified-rolled-back on any failure.

    methods (Static)
        function outcome = executeSynchronizedPairUpdate(args)
            required = {'network','delivery','updateBlock','ownerReceiver','remoteReceiver', ...
                'ownerCaptureProvider','remoteCaptureProvider','thirdMemberSupply', ...
                'deliveryLedger','coordinateEventEpoch_s','issuerIdentifier'};
            missing = setdiff(required,fieldnames(args));
            if ~isempty(missing)
                error('SynchronizedPairLinkUpdateTransaction:argsSchema', ...
                    'executeSynchronizedPairUpdate is missing argument %s.',missing{1});
            end

            outcome = struct('applied',false,'refusalReasonCode','','refusalReasonMessage','', ...
                'rolledBack',false,'correctionMessage',[],'ownerAcknowledgement',[], ...
                'remoteAcknowledgement',[],'pairUpdateResult',[],'thirdMemberOmissionAudit',[], ...
                'stagedCrossBlockCount',0);

            % ---- PHASE 1: assemble the signed correction message [NO MUTATION ANYWHERE] ----
            % block is a revgnss.DistributedLinkUpdateBlock on the live coordinator path (a
            % classdef object -- isfield() on it is ALWAYS false, which made this guard
            % structurally unreachable there); every field checked below is a mandatory property
            % of that class, so a plain, unconditional field/property read is correct for both
            % the real object and a schema-matching plain struct fixture.
            block = args.updateBlock;
            if ~isempty(block.commonSourceContributionCovariances_m2)
                outcome.refusalReasonCode = 'pairExactCommonSourceContributionUntreated';
                outcome.refusalReasonMessage = ['A declared common-source contribution is not ' ...
                    'treated by the Stage 3.2 exact path.'];
                return
            end
            if ~isempty(block.calibrationStateIdentifiers) || ...
                    ~isempty(block.calibrationMappingJacobian_mPerCalibrationUnit)
                outcome.refusalReasonCode = 'pairExactCommonSourceContributionUntreated';
                outcome.refusalReasonMessage = ['A declared persistent-calibration state/mapping ' ...
                    'column is not treated by the Stage 3.2 exact path (unlike the conservative ' ...
                    'route, which hands it to the bound module).'];
                return
            end

            ownerId = args.delivery.ownerAssetIdentifier;
            remoteId = args.delivery.remoteAssetIdentifier;
            Pii = revgnss.LocalEpochTransitionCaptureProvider.requireLocalMarginal(args.ownerCaptureProvider);
            Pjj = revgnss.LocalEpochTransitionCaptureProvider.requireLocalMarginal(args.remoteCaptureProvider);
            Pij = args.network.orientedCrossCovariance(ownerId,remoteId);

            thirdMembers = struct('endpointIdentifier',{},'priorCrossToOwner',{}, ...
                'priorCrossToRemote',{},'localMarginal',{});
            for k = 1:numel(args.thirdMemberSupply)
                supply = args.thirdMemberSupply(k);
                thirdMembers(end+1) = struct( ...  %#ok<AGROW>
                    'endpointIdentifier',supply.endpointIdentifier, ...
                    'priorCrossToOwner',args.network.orientedCrossCovariance(ownerId,supply.endpointIdentifier), ...
                    'priorCrossToRemote',args.network.orientedCrossCovariance(remoteId,supply.endpointIdentifier), ...
                    'localMarginal',supply.localMarginal);
            end

            ownerEndpoint = struct( ...
                'identifier',ownerId,'canonicalPhysicalAssetIndex',args.ownerCaptureProvider.canonicalPhysicalAssetIndex, ...
                'localStateDimension',args.ownerCaptureProvider.localStateDimension(), ...
                'schemaStateIndices',args.ownerCaptureProvider.schemaStateIndices(), ...
                'localStateMapFingerprint',args.ownerCaptureProvider.localStateMapFingerprint(), ...
                'attitudeParameterization',args.ownerCaptureProvider.attitudeParameterization(), ...
                'attitudeErrorCoordinateConvention',revgnss.SynchronizedPairLinkUpdateTransaction. ...
                    attitudeConventionFor_(args.ownerCaptureProvider.attitudeParameterization()), ...
                'xPrior',args.ownerCaptureProvider.localState(),'PPrior',Pii, ...
                'nominalQuatPrior',args.ownerCaptureProvider.nominalQuaternion(), ...
                'priorStateDigest_hex',args.ownerCaptureProvider.localStateDigest(), ...
                'stateSchemaVersion',revgnss.DistributedLinkProtocolContract.StateSchemaVersion);
            remoteEndpoint = struct( ...
                'identifier',remoteId,'canonicalPhysicalAssetIndex',args.remoteCaptureProvider.canonicalPhysicalAssetIndex, ...
                'localStateDimension',args.remoteCaptureProvider.localStateDimension(), ...
                'schemaStateIndices',args.remoteCaptureProvider.schemaStateIndices(), ...
                'localStateMapFingerprint',args.remoteCaptureProvider.localStateMapFingerprint(), ...
                'attitudeParameterization',args.remoteCaptureProvider.attitudeParameterization(), ...
                'attitudeErrorCoordinateConvention',revgnss.SynchronizedPairLinkUpdateTransaction. ...
                    attitudeConventionFor_(args.remoteCaptureProvider.attitudeParameterization()), ...
                'xPrior',args.remoteCaptureProvider.localState(),'PPrior',Pjj, ...
                'nominalQuatPrior',args.remoteCaptureProvider.nominalQuaternion(), ...
                'priorStateDigest_hex',args.remoteCaptureProvider.localStateDigest(), ...
                'stateSchemaVersion',revgnss.DistributedLinkProtocolContract.StateSchemaVersion);

            try
                message = revgnss.SynchronizedPairCorrectionMessage.assemble(struct( ...
                    'observationIdentifier',args.delivery.observationIdentifier, ...
                    'deliveryIdentifier',args.delivery.deliveryIdentifier, ...
                    'sessionIdentifier',args.delivery.sessionIdentifier, ...
                    'observableIdentifier',args.delivery.observableIdentifier, ...
                    'observableRowUnits',block.observableRowUnits, ...
                    'coordinateEventEpoch_s',args.coordinateEventEpoch_s, ...
                    'deliveryEpoch_s',args.delivery.deliveryEpoch_s, ...
                    'sourceEpoch_s',args.delivery.sourceEpoch_s, ...
                    'issuerIdentifier',args.issuerIdentifier, ...
                    'partialDeliveryPolicy','rejectWholeUpdate', ...
                    'messageSignaturePolicy','contentDigestFnv1a64', ...
                    'thirdMemberCrossConditioning','exactJointPairTransform', ...
                    'ownerEndpoint',ownerEndpoint,'remoteEndpoint',remoteEndpoint, ...
                    'ownerJacobian_mPerErrorUnit',block.ownerJacobian_mPerErrorUnit, ...
                    'remoteJacobian_mPerErrorUnit',block.remoteJacobian_mPerErrorUnit, ...
                    'independentMeasurementCovariance_m2',block.independentMeasurementCovariance_m2, ...
                    'residual_m',block.residual_m, ...
                    'priorPairCrossCovariance',Pij,'thirdMembers',thirdMembers, ...
                    'networkRevisionNumber',args.network.currentRevisionNumber(), ...
                    'clockClaim',args.delivery.clockClaim, ...
                    'pairAbsolutelyAnchored',args.delivery.pairAbsolutelyAnchored));
            catch ME
                outcome.refusalReasonCode = 'synchronizedPreparationFailed';
                outcome.refusalReasonMessage = ME.message;
                return
            end
            outcome.correctionMessage = message;
            outcome.pairUpdateResult = message.pairUpdateResult;
            outcome.thirdMemberOmissionAudit = message.thirdMemberOmissionAudit;

            try
                staged = args.network.stagePairExactLinkTransform(message);
            catch ME
                if ~isempty(regexp(ME.identifier,':linearizationPointSupersededByPairExactUpdate$','once'))
                    outcome.refusalReasonCode = 'linearizationPointSupersededByPairExactUpdate';
                    args.network.noteSupersededDeliveryRejection();
                else
                    outcome.refusalReasonCode = 'synchronizedPreparationFailed';
                end
                outcome.refusalReasonMessage = ME.message;
                return
            end
            outcome.stagedCrossBlockCount = numel(staged.replacementKeys);

            % ---- PHASE 2: acknowledge both endpoints; both or neither -----------------------
            try
                revgnss.SynchronizedPairCorrectionMessage.requireApplicableNow( ...
                    message,args.network.currentRevisionNumber());
            catch ME
                outcome.refusalReasonCode = 'staleNetworkRevision';
                outcome.refusalReasonMessage = ME.message;
                return
            end

            entry = args.deliveryLedger.entryFor(args.delivery.observationIdentifier);
            entryState = entry.state;

            record = args.delivery.physicalObservationRecord;
            ownerAck = args.ownerReceiver.prepareAcknowledgement(message,record,entryState);
            remoteAck = args.remoteReceiver.prepareAcknowledgement(message,record,entryState);
            outcome.ownerAcknowledgement = ownerAck;
            outcome.remoteAcknowledgement = remoteAck;

            if ~(ownerAck.accepted && remoteAck.accepted)
                outcome.refusalReasonCode = 'synchronizedPartialDeliveryRejected';
                if ~ownerAck.accepted
                    outcome.refusalReasonMessage = sprintf('owner refused: %s',ownerAck.reasonCode);
                else
                    outcome.refusalReasonMessage = sprintf('remote refused: %s',remoteAck.reasonCode);
                end
                return
                % NOTHING HAS BEEN WRITTEN ANYWHERE -- this is requirement 7, and it is the
                % NORMAL path, not an exception path.
            end

            % ---- PHASE 3-4: the only mutating code, journaled + verified rollback -----------
            commitArgs = struct('network',args.network,'staged',staged,'message',message, ...
                'ownerReceiver',args.ownerReceiver,'remoteReceiver',args.remoteReceiver, ...
                'ownerAcknowledgement',ownerAck,'remoteAcknowledgement',remoteAck, ...
                'deliveryLedger',args.deliveryLedger,'delivery',args.delivery, ...
                'physicalObservationRecord',record,'coordinateEventEpoch_s',args.coordinateEventEpoch_s);
            revgnss.SynchronizedPairLinkUpdateTransaction.commitAcknowledgedPairUpdate(commitArgs);

            outcome.applied = true;
            outcome.refusalReasonCode = '';
            outcome.refusalReasonMessage = '';
        end

        function commitAcknowledgedPairUpdate(commitArgs)
            % commitAcknowledgedPairUpdate  PUBLIC, pure, test-callable (U34): the only mutating
            % step. Journals a pre-image of everything it is about to touch, then commits in a
            % fixed order; on ANY failure it restores in reverse order and VERIFIES each
            % restoration by isequaln against the journal before declaring the rollback safe. A
            % restoration that fails verification SEALS the network rather than continuing.
            required = {'network','staged','message','ownerReceiver','remoteReceiver', ...
                'ownerAcknowledgement','remoteAcknowledgement','deliveryLedger','delivery', ...
                'physicalObservationRecord','coordinateEventEpoch_s'};
            missing = setdiff(required,fieldnames(commitArgs));
            if ~isempty(missing)
                error('SynchronizedPairLinkUpdateTransaction:commitArgsSchema', ...
                    'commitAcknowledgedPairUpdate is missing argument %s.',missing{1});
            end

            network = commitArgs.network;
            ownerReceiver = commitArgs.ownerReceiver;
            remoteReceiver = commitArgs.remoteReceiver;

            journal = struct( ...
                'networkPreImage',network.stagedPreImage(commitArgs.staged), ...
                'ownerSnapshot',ownerReceiver.takeRollbackSnapshot(), ...
                'remoteSnapshot',remoteReceiver.takeRollbackSnapshot());

            step = '';
            try
                step = 'C1_network';
                network.commitStagedPairExactLinkTransform(commitArgs.staged);

                step = 'C2_owner';
                ownerReceiver.commitAcknowledgedCorrection(commitArgs.message,commitArgs.ownerAcknowledgement);

                step = 'C3_remote';
                remoteReceiver.commitAcknowledgedCorrection(commitArgs.message,commitArgs.remoteAcknowledgement);

                step = 'C4_ledger';
                commitArgs.deliveryLedger.recordSynchronizedPairConsumption(struct( ...
                    'observationIdentifier',commitArgs.delivery.observationIdentifier, ...
                    'ownerAssetIdentifier',commitArgs.delivery.ownerAssetIdentifier, ...
                    'updateEpoch_s',commitArgs.delivery.deliveryEpoch_s, ...
                    'correctionMessage',commitArgs.message, ...
                    'ownerAcknowledgement',commitArgs.ownerAcknowledgement, ...
                    'remoteAcknowledgement',commitArgs.remoteAcknowledgement, ...
                    'correlationNetworkRoute','pairExact', ...
                    'correlationNetworkRouteReasonCode','pairExactRouteAvailable'));

                step = 'C5_localLedgers';
                ownerReceiver.recordOwnerConsumption(commitArgs.physicalObservationRecord, ...
                    commitArgs.coordinateEventEpoch_s);
                remoteReceiver.recordNonOwnerEndpointApplication(commitArgs.physicalObservationRecord, ...
                    commitArgs.coordinateEventEpoch_s);
            catch ME
                % The journal ({networkPreImage,ownerSnapshot,remoteSnapshot}) covers exactly
                % C1-C3's effects. A failure AT or AFTER C4 means C1-C3 already succeeded --
                % the network and BOTH endpoint filters already correctly reflect the new,
                % scientifically valid state -- and only the LEDGER bookkeeping (C4/C5) failed.
                % Rolling the filters back in that case would revert a correct update just
                % because a bookkeeping step failed, AND the journal never covered C4/C5's own
                % effects in the first place, so "verified rollback" could never honestly be
                % claimed for it. Seal immediately instead (Section 3.2 review finding B3).
                journalCoversFailure = any(strcmp(step,{'C1_network','C2_owner','C3_remote'}));
                if journalCoversFailure
                    revgnss.SynchronizedPairLinkUpdateTransaction.rollbackJournal_( ...
                        network,ownerReceiver,remoteReceiver,journal,step,ME);
                else
                    network.sealOnFailedRollback(sprintf( ...
                        ['commit failed at step %s, AFTER the network and both endpoint filters ' ...
                        'were already committed (only ledger bookkeeping remained); no rollback ' ...
                        'was attempted since the journal never covered this step''s effects. ' ...
                        'Cause: %s'],step,ME.message));
                    error('SynchronizedPairLinkUpdateTransaction:fatalUnrecoverablePartialCommit', ...
                        ['A synchronized pair update failed at step %s after the network and ' ...
                        'both endpoint filters were already correctly committed; the correlation ' ...
                        'network has been sealed rather than either rolling back an already-' ...
                        'correct update or falsely claiming a verified rollback. The fleet-wide ' ...
                        'and/or local consumption ledgers may now disagree with filter state and ' ...
                        'require manual reconciliation. Original cause: %s'],step,ME.message);
                end
            end
        end
    end

    methods (Static, Access = private)
        function rollbackJournal_(network, ownerReceiver, remoteReceiver, journal, failedStep, cause)
            rollbackOk = true;
            try
                remoteReceiver.rollback(journal.remoteSnapshot);
                ownerReceiver.rollback(journal.ownerSnapshot);
                network.restoreStagedPreImage(journal.networkPreImage);
            catch
                rollbackOk = false;
            end
            if rollbackOk
                error('SynchronizedPairLinkUpdateTransaction:commitRolledBack', ...
                    ['A synchronized pair update failed at step %s and was fully, verifiably ' ...
                    'rolled back. Cause: %s'],failedStep,cause.message);
            end
            network.sealOnFailedRollback(sprintf( ...
                'commit failed at step %s and rollback could not be verified: %s', ...
                failedStep,cause.message));
            error('SynchronizedPairLinkUpdateTransaction:fatalUnrecoverablePartialCommit', ...
                ['A synchronized pair update failed at step %s and its rollback could NOT be ' ...
                'verified; the correlation network has been sealed. Original cause: %s'], ...
                failedStep,cause.message);
        end

        function convention = attitudeConventionFor_(attitudeParameterization)
            if strcmp(attitudeParameterization,'quaternionErrorState')
                convention = 'rightMultiplicativeLocalTangent_rad';
            else
                convention = 'eulerZYXError_rad';
            end
        end
    end
end
