function names = coreMetricNames()
%CORECMETRICNAMES  Hard scientific contract for the Stage-85 regression gate.
%   These summary metrics must NEVER move versus the frozen Phase-0 golden
%   reference. They span position, clock, attitude, known-ambiguity validation,
%   NIS, residuals, measurement-row structure, ionosphere-free combination
%   coefficients, EKF dynamics energy conservation, and integer AR counts.
%   A change to any of these (value beyond tolerance, or presence) FAILS the gate.
%
%   Do NOT trim this list to make a change pass. Equivalence is the contract.
    names = { ...
        'finalPositionRMS_m'; ...
        'finalPositionError_m'; ...
        'finalPositionLast_m'; ...
        'finalClockBiasRMS_m'; ...
        'finalClockErr_m'; ...
        'initialAttitudeError_deg'; ...
        'finalAttitudeError_deg'; ...
        'attitudeImprovementRatio'; ...
        'finalAttitudeSigma_deg'; ...
        'singleAssetAttitudeErrorNorm_deg'; ...
        'knownAmbImprovementRatio'; ...
        'knownAmbFinalError_deg'; ...
        'knownAmbInitError_deg'; ...
        'meanNIS'; ...
        'expectedNIS'; ...
        'physicalNIS'; ...
        'finalPrefitRMS_m'; ...
        'finalPostfitRMS_m'; ...
        'physicalResidualRms_m'; ...
        'codeResidualRms57_m'; ...
        'carrierResidualRms57_m'; ...
        'dopplerResidualRms57_m'; ...
        'diffAttResidRMS_m'; ...
        'nStates'; ...
        'nAmbiguityStates'; ...
        'totalCodeRows'; ...
        'totalCarrierRows'; ...
        'totalDopplerRows'; ...
        'totalCodeIonoFreeRows'; ...
        'totalCarrierIfRows'; ...
        'nTowers'; ...
        'nReceivers'; ...
        'codeIonoFreeAlpha'; ...
        'codeIonoFreeBeta'; ...
        'carrierIonoFreeAlpha'; ...
        'carrierIonoFreeBeta'; ...
        'ekfDynamicsEnergyDrift_Jkg'; ...
        'nBaselineIntegerFixed'; ...
        'nBaselineArUsedInEkf' ...
    };
end
