function test_inter_satellite_time_transfer_multi_link_schedule()
% Time transfer reuses the declared fleet link schedule without enabling range.

    cfg = resolveSimulationConfig( ...
        'test003_jointCoherentTwoWayCode.json');
    cfg.simulation.duration_s = 1;
    cfg.measurements.isl.twoWay.range.enable = false;
    cfg.measurements.isl.twoWay.range.useInEKF = false;
    cfg.measurements.isl.twoWay.calibration.residualBiasState.enable = false;
    cfg.measurements.isl.twoWay.timeTransfer.enable = true;
    cfg.measurements.isl.twoWay.timeTransfer.useInEKF = true;
    cfg.measurements.isl.twoWay.timeTransfer.mode = ...
        'firstOrderReciprocal';

    simulation = revgnss.ReverseGNSSSimulation(cfg);
    simulation.initialize();
    [observations,~,info] = ...
        revgnss.InterSatelliteTimeTransferBuilder.generateObservations( ...
        simulation.cfg,simulation.assets,0);
    [z,~,~,~,info] = ...
        revgnss.InterSatelliteTimeTransferBuilder. ...
        linearizeRecordedObservations( ...
        simulation.cfg,observations, ...
        simulation.ekf.getMeasurementState(),simulation.ekf.stateMap, ...
        simulation.ekf.nx,0,info);

    assert(numel(observations) == 3);
    assert(info.nRows == 3 && numel(z) == 3);
    assert(revgnss.MultiAssetConfig.twoWayConcurrentLinkCount_( ...
        simulation.cfg) == 3);
    linkIdentifiers = cellfun(@(observation) ...
        observation.linkIdentifier,observations,'UniformOutput',false);
    calibrationIdentifiers = cellfun(@(observation) ...
        observation.calibrationProductIdentifiers{1},observations, ...
        'UniformOutput',false);
    assert(numel(unique(linkIdentifiers)) == 3);
    assert(numel(unique(calibrationIdentifiers)) == 3);

    [rangeObservations,~,~] = ...
        revgnss.TwoWayISLMeasurementBuilder.generateObservations( ...
        simulation.cfg,simulation.asset,simulation.assets,0);
    assert(isempty(rangeObservations));
    fprintf('test_inter_satellite_time_transfer_multi_link_schedule: PASS\n');
end
