function test_inter_satellite_time_transfer()
% Scenario gating, endpoint ownership, recording, and joint-EKF consumption.

    cfg = resolveSimulationConfig( ...
        'joint_G5S2R4_reciprocal_time_transfer.json');
    cfg.simulation.duration_s = 1;
    cfg.estimator.minMeasurementsForUpdate = 1;
    multiAssetSummary = revgnss.MultiAssetConfig.summary(cfg);
    assert(multiAssetSummary.islRows == 1);
    manifest = revgnss.SimulationToggleManifest.fromConfig(cfg);
    manifestPaths = {manifest.cfgPath};
    enableRow = manifest(strcmp(manifestPaths, ...
        'cfg.measurements.isl.twoWay.timeTransfer.enable'));
    modeRow = manifest(strcmp(manifestPaths, ...
        'cfg.measurements.isl.twoWay.timeTransfer.mode'));
    assert(isscalar(enableRow) && strcmp(enableRow.status,'active'));
    assert(isscalar(modeRow) && ...
        strcmp(modeRow.value,'firstOrderReciprocal'));
    simulation = revgnss.ReverseGNSSSimulation(cfg);
    simulation.initialize();

    [observations,diagnostics,info] = ...
        revgnss.InterSatelliteTimeTransferBuilder.generateObservations( ...
        simulation.cfg,simulation.assets,0);
    assert(isscalar(observations));
    assert(isscalar(diagnostics));
    observation = observations{1};
    assert(isa(observation, ...
        'revgnss.InterSatelliteTimeTransferObservationRecord'));
    assert(~observation.rawTimestampTagsAvailable);
    assert(all(isnan(observation.timestampTags_s)));
    assert(strcmp(observation.modeIdentifier,'firstOrderReciprocal'));

    x = simulation.ekf.getMeasurementState();
    [z,h,H,R,linearizationInfo] = ...
        revgnss.InterSatelliteTimeTransferBuilder. ...
        linearizeRecordedObservations( ...
        simulation.cfg,observations,x,simulation.ekf.stateMap, ...
        simulation.ekf.nx,0,info);
    assert(isequal(size(H),[1 simulation.ekf.nx]));
    assert(isscalar(z) && isscalar(h) && isscalar(R) && R > 0);
    referenceBlock = revgnss.AssetStateBlock.forAsset( ...
        simulation.ekf.stateMap,1);
    remoteBlock = revgnss.AssetStateBlock.forAsset( ...
        simulation.ekf.stateMap,2);
    assert(H(referenceBlock.b) == -1);
    assert(H(remoteBlock.b) == 1);
    assert(any(abs(H([referenceBlock.r;referenceBlock.v; ...
        remoteBlock.r;remoteBlock.v])) > 0));
    lever = 0.5*( ...
        simulation.cfg.measurements.isl.twoWay.terminalGeometry. ...
        transmitPhaseCentreOffset_body_m(:)+ ...
        simulation.cfg.measurements.isl.twoWay.terminalGeometry. ...
        receivePhaseCentreOffset_body_m(:));
    referenceEuler = x(referenceBlock.euler);
    remoteEuler = x(remoteBlock.euler);
    referenceRotation = ...
        revgnss.AttitudeKinematics.bodyToEcefRotation(referenceEuler);
    remoteRotation = ...
        revgnss.AttitudeKinematics.bodyToEcefRotation(remoteEuler);
    referenceState = struct( ...
        'position_m',x(referenceBlock.r)+referenceRotation*lever, ...
        'velocity_mps',x(referenceBlock.v), ...
        'clockBias_m',x(referenceBlock.b));
    remoteState = struct( ...
        'position_m',x(remoteBlock.r)+remoteRotation*lever, ...
        'velocity_mps',x(remoteBlock.v), ...
        'clockBias_m',x(remoteBlock.b));
    model = revgnss.ReciprocalTimeTransferModel.evaluate( ...
        referenceState,remoteState,'firstOrderReciprocal',true);
    referenceLeverJacobian = zeros(3,3);
    remoteLeverJacobian = zeros(3,3);
    for component = 1:3
        axis = zeros(3,1);
        axis(component) = 1;
        referenceLeverJacobian(:,component) = ...
            referenceRotation*cross(axis,lever);
        remoteLeverJacobian(:,component) = ...
            remoteRotation*cross(axis,lever);
    end
    expectedReferenceAttitude = ...
        model.referencePositionPartial*referenceLeverJacobian;
    expectedRemoteAttitude = ...
        model.remotePositionPartial*remoteLeverJacobian;
    assert(norm(H(referenceBlock.euler)-expectedReferenceAttitude) < ...
        1e-6*max(norm(expectedReferenceAttitude),1e-14));
    assert(norm(H(remoteBlock.euler)-expectedRemoteAttitude) < ...
        1e-6*max(norm(expectedRemoteAttitude),1e-14));
    hRepeat = revgnss.InterSatelliteTimeTransferBuilder.predictEkfRows( ...
        simulation.cfg,x,simulation.ekf.stateMap,linearizationInfo);
    assert(abs(hRepeat-h) < 1e-12);

    cfgOff = simulation.cfg;
    cfgOff.measurements.isl.twoWay.timeTransfer.enable = false;
    cfgOff.measurements.isl.twoWay.timeTransfer.useInEKF = false;
    [observationsOff,~,infoOff] = ...
        revgnss.InterSatelliteTimeTransferBuilder.generateObservations( ...
        cfgOff,simulation.assets,0);
    assert(isempty(observationsOff) && infoOff.nEkfRows == 0);

    cfgFuture = simulation.cfg;
    cfgFuture.measurements.isl.twoWay.timeTransfer.mode = ...
        'fourTimestampPhysical';
    assertThrows_(@() revgnss.InterSatelliteTimeTransferBuilder. ...
        validateConfig(cfgFuture), ...
        'ReciprocalTimeTransferModel:fourTimestampUnavailable');

    simulation.run();
    assert(simulation.observationLedger.numberEligible() > 0);
    assert(simulation.observationLedger.numberEligible() == ...
        simulation.observationLedger.numberConsumed());
    result = simulation.getResults();
    recordTypes = cellfun(@class,result.interSatelliteObservations, ...
        'UniformOutput',false);
    assert(any(strcmp(recordTypes, ...
        'revgnss.InterSatelliteTimeTransferObservationRecord')));
    assert(~any(strcmp(recordTypes, ...
        'revgnss.InterSatelliteObservationRecord')), ...
        'The disabled two-way range path generated a code-range record.');
    fprintf('test_inter_satellite_time_transfer: PASS\n');
end

function assertThrows_(callback,identifier)
    thrown = false;
    try
        callback();
    catch exception
        thrown = strcmp(exception.identifier,identifier);
    end
    assert(thrown,'Expected error %s.',identifier);
end
