function test_coherent_two_way_code_static_closure()
% Static four-event closure, phase-centre geometry, and calibrated delay.

c = revgnss.CoherentTwoWayCodeRangingModel.SpeedOfLight_mps;
baseline_m = 1.0e6;
turnaround_s = 2.0e-6;
terminalDelay_s = 12e-9;

initiatorTruth = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'physicalTruth', 'spacecraft:A', [0;0;0], zeros(3,1), 0, ...
    transmitPhaseCentreOffset_body_m=[1;0;0], ...
    receivePhaseCentreOffset_body_m=[-0.5;0;0], ...
    transmitTerminalIdentifier='A:tx', receiveTerminalIdentifier='A:rx', ...
    transmitAntennaIdentifier='A:tx-pc', receiveAntennaIdentifier='A:rx-pc');
transponderTruth = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'physicalTruth', 'spacecraft:B', [baseline_m;0;0], zeros(3,1), 0, ...
    transmitPhaseCentreOffset_body_m=[-0.75;0;0], ...
    receivePhaseCentreOffset_body_m=[0.25;0;0], ...
    transmitTerminalIdentifier='B:tx', receiveTerminalIdentifier='B:rx', ...
    transmitAntennaIdentifier='B:tx-pc', receiveAntennaIdentifier='B:rx-pc');

physical = hardware_('physicalTruth', turnaround_s, terminalDelay_s);
calibration = hardware_('calibrationProduct', turnaround_s, terminalDelay_s);
metadata = metadata_(0.04);
[observation, diagnostic] = revgnss.CoherentTwoWayCodeRangingModel.simulateObservation( ...
    initiatorTruth, transponderTruth, physical, calibration, 100, metadata);

forwardRange_m = baseline_m - 0.75;
returnRange_m = baseline_m - 0.25;
expectedRange_m = 0.5 * (forwardRange_m + returnRange_m);
assert(abs(observation.processedValue - expectedRange_m) < 1e-3);
assert(abs(diagnostic.forwardGeometricRange_m - forwardRange_m) < 1e-9);
assert(abs(diagnostic.returnGeometricRange_m - returnRange_m) < 1e-9);
assert(max(abs([diagnostic.forwardLightTimeResidual_s, ...
    diagnostic.returnLightTimeResidual_s])) < 1e-11);
assert(strcmp(observation.referenceEpochRule, 'finalReception'));
assert(observation.referenceLocalClockTag_s == ...
    observation.initiatorReceiveLocalClockTag_s);
assert(diagnostic.codeRateTurnaroundRatio == 1);
expectedReturnPhase = mod(diagnostic.trackedIncomingCodePhase_chips + ...
    physical.codePhaseCalibration_chips, physical.codeLength_chips);
assert(abs(diagnostic.transmittedReturnCodePhase_chips - expectedReturnPhase) < 1e-12);

initiatorEstimate = endpointEstimate_(initiatorTruth, [0;0;0]);
transponderEstimate = endpointEstimate_(transponderTruth, [baseline_m;0;0]);
[prediction_m, prediction] = revgnss.CoherentTwoWayCodeRangingModel.predictProcessedRange( ...
    observation, initiatorEstimate, transponderEstimate, calibration);
assert(abs(prediction_m - observation.processedValue) < 1e-3);
assert(strcmp(prediction.referenceEpochRule, 'finalReception'));

biasedCalibration = hardware_('calibrationProduct', turnaround_s + 20e-9, terminalDelay_s);
[biasedObservation, ~] = revgnss.CoherentTwoWayCodeRangingModel.simulateObservation( ...
    initiatorTruth, transponderTruth, physical, biasedCalibration, 100, metadata);
expectedBias_m = -0.5 * c * 20e-9;
assert(abs((biasedObservation.processedValue - expectedRange_m) - expectedBias_m) < 1e-3);

fprintf('test_coherent_two_way_code_static_closure: PASS\n');
end

function endpoint = endpointEstimate_(truthEndpoint, referencePosition_m)
endpoint = revgnss.TwoWayCodeEndpointModel.constantVelocity( ...
    'estimatorState', truthEndpoint.assetIdentifier, referencePosition_m, zeros(3,1), 0, ...
    transmitPhaseCentreOffset_body_m=truthEndpoint.transmitPhaseCentreOffset_body_m, ...
    receivePhaseCentreOffset_body_m=truthEndpoint.receivePhaseCentreOffset_body_m, ...
    transmitTerminalIdentifier=truthEndpoint.transmitTerminalIdentifier, ...
    receiveTerminalIdentifier=truthEndpoint.receiveTerminalIdentifier, ...
    transmitAntennaIdentifier=truthEndpoint.transmitAntennaIdentifier, ...
    receiveAntennaIdentifier=truthEndpoint.receiveAntennaIdentifier);
end

function hardware = hardware_(source, turnaround_s, terminalDelay_s)
hardware = revgnss.CoherentTwoWayCodeHardwareModel( ...
    parameterSource=source, physicalChainIdentifier='chain:A-B:Ka', ...
    calibrationProductIdentifier='cal:A-B:Ka:001', ...
    turnaroundProperTime_s=turnaround_s, ...
    initiatorTerminalGroupDelay_s=terminalDelay_s, ...
    carrierFrequencyTurnaroundRatio=880/749, ...
    codeRateTurnaroundRatio=1, codeChipRate_Hz=10.23e6, ...
    codeLength_chips=10230, codePhaseCalibration_chips=0.125);
end

function metadata = metadata_(variance_m2)
metadata = struct( ...
    'observationIdentifier', 'obs:A-B:0001', ...
    'sessionIdentifier', 'session:A-B:0001', ...
    'signalIdentifier', 'PN10', ...
    'covarianceGroupIdentifier', 'cov:A-B:0001', ...
    'covarianceRowIndex', 1, ...
    'covarianceBlock_m2', variance_m2, ...
    'carrierToNoiseDensity_dBHz', 55, ...
    'available', true, ...
    'qualityFlags', struct('codeLock',true,'pointingLock',true), ...
    'truthDiagnosticIdentifier', 'truth:A-B:0001');
end
