classdef ResultBuilder
    %RESULTBUILDER Builds the simulation results struct.
    %
    % This class owns the mapping from completed simulation state/history into
    % the saved results struct. It does not run the simulation and does not
    % create report-specific data.

    methods (Static)

        function status = errorBudgetStatus(sim)
            mcfg = sim.cfg.measurement;

            status = struct();

            status.truth_model_residual_convention = ...
                "truth enters y; model enters yp; residual_m = truth_m - model_m; estimator gets covariance, not truth random samples";

            status.measurement_domain = ...
                "all pseudorange error-budget terms are represented in metres unless explicitly suffixed _s";

            status.enabled = struct();
            status.enabled.measurement_noise = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableMeasurementNoise', false) || ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableNoise', false);
            status.enabled.atmosphere_truth = ...
                ~isempty(sim.measurementModel.truthAtmosphere) && ...
                sim.measurementModel.truthAtmosphere.isEnabled();
            status.enabled.atmosphere_model = ...
                ~isempty(sim.measurementModel.modelAtmosphere) && ...
                sim.measurementModel.modelAtmosphere.isEnabled();
            status.enabled.hardware_delay = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableHardwareDelay', false);
            status.enabled.multipath_delay = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableMultipathDelay', false);
            status.enabled.stochastic_multipath = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableStochasticMultipath', false);
            status.enabled.antenna_delay = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableAntennaDelay', false);
            status.enabled.tower_survey_error = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableTowerSurveyError', false);
            status.enabled.legacy_sagnac_scalar = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableSagnacCorrection', false);
            status.enabled.light_time_truth = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrectionTruth', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrection', false));
            status.enabled.light_time_model = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrectionModel', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrection', false));
            status.enabled.relativistic_path_truth = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelayTruth', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelay', false));
            status.enabled.relativistic_path_model = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelayModel', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelay', false));
            status.enabled.relativistic_clock_truth = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrectionTruth', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrection', false));
            status.enabled.relativistic_clock_model = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrectionModel', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrection', false));

            status.implemented = [ ...
                "truth/model atmosphere with same-tower residual covariance", ...
                "measurement noise as independent pseudorange variance", ...
                "hardware truth/model global TX/RX delay", ...
                "deterministic multipath truth/model correction", ...
                "stochastic multipath truth sample with independent diagonal R variance", ...
                "scalar antenna truth/model correction", ...
                "tower survey ECEF offset range-effect truth/model correction", ...
                "ECI inertial iterative light-time truth/model correction", ...
                "Shapiro relativistic path delay truth/model correction", ...
                "legacy scalar Sagnac truth/model placeholder with light-time conflict guard"];

            status.guarded_not_implemented = [ ...
                "relativistic clock correction", ...
                "carrier-phase observables", ...
                "full antenna PCO/PCV truth/model calibration chain", ...
                "tower-specific hardware model delay", ...
                "full ECEF-frame Sagnac propagation mode"];

            status.diagnostics_available = [ ...
                "history.atmosphere", ...
                "history.non_atmospheric", ...
                "history.propagation", ...
                "history.measurement_covariance_*", ...
                "prefit_residual_by_receiver_tower_m", ...
                "postfit_residual_by_receiver_tower_m"];

            status.position_error_warning = ...
                "position error alone is not sufficient; common-mode range errors can be absorbed by receiver/tower clock states, so inspect innovations, residual budgets, and R";
        end

        function results = fromSimulation(sim)
            towerClockEkfEnabled = ResultBuilder.towerClockEkfEnabled(sim);

            reportData = struct();
            reportData.error_budget_status = ...
                ResultBuilder.errorBudgetStatus(sim);
            reportData.time_vec = sim.time_s;
            results.state_est = sim.history.x;
            results.state_truth = sim.history.truth;
            results.covariance_diag = sim.history.covariance_diag;

            results.innovation_rms_m = sim.history.innovation_rms_m;
            results.postfit_innovation_rms_m = sim.history.postfit_innovation_rms_m;
            results.nis_history = sim.history.nis_history;
            results.H_rank_history = sim.history.H_rank_history;

            results.measurement_covariance_range_mean_variance_m2 = ...
                sim.history.measurement_covariance_range_mean_variance_m2;
            results.measurement_covariance_range_max_offdiag_m2 = ...
                sim.history.measurement_covariance_range_max_offdiag_m2;
            results.measurement_covariance_range_dimension = ...
                sim.history.measurement_covariance_range_dimension;

            results.measurement_covariance_update_mean_variance_m2 = ...
                sim.history.measurement_covariance_update_mean_variance_m2;
            results.measurement_covariance_update_max_offdiag_m2 = ...
                sim.history.measurement_covariance_update_max_offdiag_m2;
            results.measurement_covariance_update_dimension = ...
                sim.history.measurement_covariance_update_dimension;

            results.receiver_names = sim.receiverNames;
            results.receiver_offsets_body_m = sim.receiverOffsetsBody_m;
            results.num_receivers = sim.numReceivers;
            results.scenario_name = sim.scenarioName;

            results.state_names = StateIndexFactory.stateNames( ...
                sim.towerNames, towerClockEkfEnabled);
            
            results.observability = ObservabilityAnalyzer.analyzeNormalMatrix( ...
                sim.observabilityNormalMatrix, results.state_names);
            results.ground_clock_true_m = sim.history.ground_clock_true_m;
            results.ground_clock_correction_m = sim.history.ground_clock_correction_m;
            results.ground_clock_residual_m = sim.history.ground_clock_residual_m;

            results.clock_bias_truth_m = sim.history.truth(sim.idx.rxClockBias, :);
            results.clock_bias_est_m = sim.history.x(sim.idx.rxClockBias, :);

            results.pseudorange_by_receiver_tower_m = ...
                sim.history.pseudorange_by_receiver_tower_m;

            results.true_range_by_receiver_tower_m = ...
                sim.history.true_range_by_receiver_tower_m;

            results.atmosphere = sim.history.atmosphere;
            results.propagation = sim.history.propagation;
            if isfield(sim.history, 'non_atmospheric')
                results.non_atmospheric = sim.history.non_atmospheric;
            end
            
            results.atmosphere_truth_delay_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_delay_by_receiver_tower_m;

            results.atmosphere_truth_troposphere_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_troposphere_by_receiver_tower_m;

            results.atmosphere_truth_ionosphere_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_ionosphere_by_receiver_tower_m;
            results.atmosphere_truth_ionosphere_ipp_lat_deg_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_ipp_lat_deg_by_receiver_tower;

            results.atmosphere_truth_ionosphere_ipp_lon_deg_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_ipp_lon_deg_by_receiver_tower;

            results.atmosphere_truth_ionosphere_vtec_TECU_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_vtec_TECU_by_receiver_tower;

            results.atmosphere_truth_ionosphere_stec_TECU_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_stec_TECU_by_receiver_tower;

            results.atmosphere_truth_ionosphere_mapping_factor_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_mapping_factor_by_receiver_tower;

            results.atmosphere_truth_ionosphere_frequency_Hz_by_receiver_tower = ...
                sim.history.atmosphere_truth_ionosphere_frequency_Hz_by_receiver_tower;
            
            results.atmosphere_truth_troposphere_pressure_hPa_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_pressure_hPa_by_receiver_tower;

            results.atmosphere_truth_troposphere_temperature_K_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_temperature_K_by_receiver_tower;

            results.atmosphere_truth_troposphere_relative_humidity_fraction_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_relative_humidity_fraction_by_receiver_tower;

            results.atmosphere_truth_troposphere_water_vapor_pressure_hPa_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_water_vapor_pressure_hPa_by_receiver_tower;

            results.atmosphere_truth_troposphere_zhd_m_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_zhd_m_by_receiver_tower;

            results.atmosphere_truth_troposphere_zwd_m_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_zwd_m_by_receiver_tower;

            results.atmosphere_truth_troposphere_mapping_hydrostatic_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_mapping_hydrostatic_by_receiver_tower;

            results.atmosphere_truth_troposphere_mapping_wet_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_mapping_wet_by_receiver_tower;

            results.atmosphere_truth_troposphere_slant_hydrostatic_m_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_slant_hydrostatic_m_by_receiver_tower;

            results.atmosphere_truth_troposphere_slant_wet_m_by_receiver_tower = ...
                sim.history.atmosphere_truth_troposphere_slant_wet_m_by_receiver_tower;
            results.atmosphere_truth_troposphere_residual_by_tower_m = ...
                sim.history.atmosphere_truth_troposphere_residual_by_tower_m;

            results.atmosphere_truth_ionosphere_residual_by_tower_m = ...
                sim.history.atmosphere_truth_ionosphere_residual_by_tower_m;

            results.atmosphere_truth_troposphere_total_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_troposphere_total_by_receiver_tower_m;

            results.atmosphere_truth_ionosphere_total_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_ionosphere_total_by_receiver_tower_m; 

            results.atmosphere_truth_residual_by_tower_m = ...
                sim.history.atmosphere_truth_residual_by_tower_m;

            results.atmosphere_truth_total_by_receiver_tower_m = ...
                sim.history.atmosphere_truth_total_by_receiver_tower_m;

            results.atmosphere_model_delay_by_receiver_tower_m = ...
                sim.history.atmosphere_model_delay_by_receiver_tower_m;

            results.atmosphere_model_troposphere_by_receiver_tower_m = ...
                sim.history.atmosphere_model_troposphere_by_receiver_tower_m;

            results.atmosphere_model_ionosphere_by_receiver_tower_m = ...
                sim.history.atmosphere_model_ionosphere_by_receiver_tower_m;

            results.atmosphere_model_ionosphere_ipp_lat_deg_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_ipp_lat_deg_by_receiver_tower;

            results.atmosphere_model_ionosphere_ipp_lon_deg_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_ipp_lon_deg_by_receiver_tower;

            results.atmosphere_model_ionosphere_vtec_TECU_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_vtec_TECU_by_receiver_tower;

            results.atmosphere_model_ionosphere_stec_TECU_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_stec_TECU_by_receiver_tower;

            results.atmosphere_model_ionosphere_mapping_factor_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_mapping_factor_by_receiver_tower;

            results.atmosphere_model_ionosphere_frequency_Hz_by_receiver_tower = ...
                sim.history.atmosphere_model_ionosphere_frequency_Hz_by_receiver_tower;
            
            results.atmosphere_model_troposphere_pressure_hPa_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_pressure_hPa_by_receiver_tower;

            results.atmosphere_model_troposphere_temperature_K_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_temperature_K_by_receiver_tower;

            results.atmosphere_model_troposphere_relative_humidity_fraction_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_relative_humidity_fraction_by_receiver_tower;

            results.atmosphere_model_troposphere_water_vapor_pressure_hPa_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_water_vapor_pressure_hPa_by_receiver_tower;

            results.atmosphere_model_troposphere_zhd_m_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_zhd_m_by_receiver_tower;

            results.atmosphere_model_troposphere_zwd_m_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_zwd_m_by_receiver_tower;

            results.atmosphere_model_troposphere_mapping_hydrostatic_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_mapping_hydrostatic_by_receiver_tower;

            results.atmosphere_model_troposphere_mapping_wet_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_mapping_wet_by_receiver_tower;

            results.atmosphere_model_troposphere_slant_hydrostatic_m_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_slant_hydrostatic_m_by_receiver_tower;

            results.atmosphere_model_troposphere_slant_wet_m_by_receiver_tower = ...
                sim.history.atmosphere_model_troposphere_slant_wet_m_by_receiver_tower;
            results.enableTowerClockEKF = towerClockEkfEnabled;

            if towerClockEkfEnabled
                results.tower_clock_bias_est_m = ...
                    sim.history.x(sim.idx.towerClockBias, :);

                results.tower_clock_bias_truth_m = ...
                    sim.history.truth(sim.idx.towerClockBias, :);

                results.tower_clock_drift_est_mps = ...
                    sim.history.x(sim.idx.towerClockDrift, :);

                results.tower_clock_drift_truth_mps = ...
                    sim.history.truth(sim.idx.towerClockDrift, :);
            end
        end
    end

    methods (Static, Access = private)

        function tf = towerClockEkfEnabled(sim)
            tf = logical(ResultBuilder.getFieldOrDefault( ...
                sim.cfg, 'enableTowerClockEKF', false));
        end

        function value = getFieldOrDefault(s, fieldName, defaultValue)
            if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
                value = s.(fieldName);
            else
                value = defaultValue;
            end
        end
    end
end
