classdef ResultBuilder
    %RESULTBUILDER Builds the simulation results struct.
    %
    % This class owns the mapping from completed simulation state/history into
    % the saved results struct. It does not run the simulation and does not
    % create report-specific data.

    methods (Static)

        function status = errorBudgetStatus(sim)
            mcfg = sim.cfg.measurement;

            status = struct();

            status.truth_model_residual_convention = ...
                "truth enters y; model enters yp; residual_m = truth_m - model_m; estimator gets covariance, not truth random samples";

            status.measurement_domain = ...
                "all pseudorange error-budget terms are represented in metres unless explicitly suffixed _s";

            status.enabled = struct();
            status.enabled.measurement_noise = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableMeasurementNoise', false) || ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableNoise', false);
            status.enabled.atmosphere_truth = ...
                ~isempty(sim.measurementModel.truthAtmosphere) && ...
                sim.measurementModel.truthAtmosphere.isEnabled();
            status.enabled.atmosphere_model = ...
                ~isempty(sim.measurementModel.modelAtmosphere) && ...
                sim.measurementModel.modelAtmosphere.isEnabled();
            status.enabled.hardware_delay = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableHardwareDelay', false);
            status.enabled.multipath_delay = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableMultipathDelay', false);
            status.enabled.stochastic_multipath = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableStochasticMultipath', false);
            status.enabled.antenna_delay = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableAntennaDelay', false);
            status.enabled.tower_survey_error = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableTowerSurveyError', false);
            status.enabled.legacy_sagnac_scalar = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableSagnacCorrection', false);
            status.enabled.light_time_truth = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrectionTruth', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrection', false));
            status.enabled.light_time_model = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrectionModel', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrection', false));
            status.enabled.relativistic_path_truth = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelayTruth', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelay', false));
            status.enabled.relativistic_path_model = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelayModel', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelay', false));
            status.enabled.relativistic_clock_truth = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrectionTruth', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrection', false));
            status.enabled.relativistic_clock_model = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrectionModel', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrection', false));

            clockModel = ResultBuilder.getFieldOrDefault( ...
                sim.cfg.process, 'clockModel', "brownHwang");
            clockModelKey = lower(regexprep(strtrim(string(clockModel)), ...
                '[-_]', ''));
            status.clock_model = string(clockModel);
            if clockModelKey == "coupledgaussmarkov"
                status.experimental = ...
                    "coupledGaussMarkov clock process-noise model is experimental/guarded pending dedicated derivation and regression tests";
            else
                status.experimental = strings(1, 0);
            end

            status.implemented = [ ...
                "truth/model atmosphere with same-tower residual covariance", ...
                "measurement noise as independent pseudorange variance", ...
                "hardware truth/model global TX/RX delay", ...
                "deterministic multipath truth/model correction", ...
                "stochastic multipath truth sample with independent diagonal R variance", ...
                "scalar antenna truth/model correction", ...
                "tower survey ECEF offset range-effect truth/model correction", ...
                "ECI inertial iterative light-time truth/model correction", ...
                "legacy scalar Sagnac truth/model placeholder with light-time conflict guard"];

            status.guarded_not_implemented = [ ...
                "Shapiro relativistic path delay truth/model correction", ...
                "relativistic clock correction", ...
                "carrier-phase observables", ...
                "full antenna PCO/PCV truth/model calibration chain", ...
                "tower-specific hardware model delay", ...
                "full ECEF-frame Sagnac propagation mode"];

            status.diagnostics_available = [ ...
                "history.errors", ...
                "history.diagnostics", ...
                "history.measurement_covariance_*", ...
                "prefit_residual_by_receiver_tower_m", ...
                "postfit_residual_by_receiver_tower_m"];

            status.position_error_warning = ...
                "position error alone is not sufficient; common-mode range errors can be absorbed by receiver/tower clock states, so inspect innovations, residual budgets, and R";
        end

        function results = fromSimulation(sim)
            towerClockEkfEnabled = ResultBuilder.towerClockEkfEnabled(sim);

            results = struct();
            results.error_budget_status = ...
                ResultBuilder.errorBudgetStatus(sim);

            results.time_s = sim.time_s;

            results.state_est = sim.history.x;
            results.state_truth = sim.history.truth;
            results.covariance_diag = sim.history.covariance_diag;

            results = BuilderFieldCopier.copyNamedFields(results, sim.history, [
                "innovation_rms_m"
                "postfit_innovation_rms_m"
                "nis_history"
                "H_rank_history"
                "measurement_covariance_range_mean_variance_m2"
                "measurement_covariance_range_max_offdiag_m2"
                "measurement_covariance_range_dimension"
                "measurement_covariance_update_mean_variance_m2"
                "measurement_covariance_update_max_offdiag_m2"
                "measurement_covariance_update_dimension"]);

            results.receiver_names = sim.receiverNames;
            results.receiver_offsets_body_m = sim.receiverOffsetsBody_m;
            results.num_receivers = sim.numReceivers;
            results.scenario_name = sim.scenarioName;

            results.state_names = StateIndexFactory.stateNames( ...
                sim.towerNames, towerClockEkfEnabled);
            
            results.observability = ObservabilityAnalyzer.analyzeNormalMatrix( ...
                sim.observabilityNormalMatrix, results.state_names);
            results = BuilderFieldCopier.copyNamedFields(results, sim.history, [
                "ground_clock_true_m"
                "ground_clock_correction_m"
                "ground_clock_residual_m"]);

            results.clock_bias_truth_m = sim.history.truth(sim.idx.rxClockBias, :);
            results.clock_bias_est_m = sim.history.x(sim.idx.rxClockBias, :);

            results = BuilderFieldCopier.copyNamedFields(results, sim.history, [
                "pseudorange_by_receiver_tower_m"
                "true_range_by_receiver_tower_m"]);
            results = ResultBuilder.addLegacyErrorViews(results, sim.history);
            results.enableTowerClockEKF = towerClockEkfEnabled;

            if towerClockEkfEnabled
                results.tower_clock_bias_est_m = ...
                    sim.history.x(sim.idx.towerClockBias, :);

                results.tower_clock_bias_truth_m = ...
                    sim.history.truth(sim.idx.towerClockBias, :);

                results.tower_clock_drift_est_mps = ...
                    sim.history.x(sim.idx.towerClockDrift, :);

                results.tower_clock_drift_truth_mps = ...
                    sim.history.truth(sim.idx.towerClockDrift, :);
            end
        end
    end

    methods (Static, Access = private)
        function out = addLegacyErrorViews(out, history)
            if ~isfield(history, 'errors')
                return;
            end

            out = ResultBuilder.addAtmosphereFields(out, history);
            out = ResultBuilder.addAtmosphereView(out, history);
            out = ResultBuilder.addPropagationView(out, history);
            out = ResultBuilder.addNonAtmosphericView(out, history);
        end

        function out = addAtmosphereFields(out, history)
            errors = history.errors;
            diagnostics = history.diagnostics.atmosphere;

            out.atmosphere_truth_delay_by_receiver_tower_m = ...
                errors.atmosphere.deterministicTruth_m;
            out.atmosphere_truth_troposphere_by_receiver_tower_m = ...
                errors.troposphere.deterministicTruth_m;
            out.atmosphere_truth_ionosphere_by_receiver_tower_m = ...
                errors.ionosphere.deterministicTruth_m;
            out.atmosphere_truth_troposphere_total_by_receiver_tower_m = ...
                errors.troposphere.truth_m;
            out.atmosphere_truth_ionosphere_total_by_receiver_tower_m = ...
                errors.ionosphere.truth_m;
            out.atmosphere_truth_total_by_receiver_tower_m = ...
                errors.atmosphere.truth_m;
            out.atmosphere_truth_residual_by_tower_m = ...
                errors.atmosphere.stochasticResidualByTower_m;
            out.atmosphere_truth_troposphere_residual_by_tower_m = ...
                errors.troposphere.stochasticResidualByTower_m;
            out.atmosphere_truth_ionosphere_residual_by_tower_m = ...
                errors.ionosphere.stochasticResidualByTower_m;

            out.atmosphere_model_delay_by_receiver_tower_m = ...
                errors.atmosphere.model_m;
            out.atmosphere_model_troposphere_by_receiver_tower_m = ...
                errors.troposphere.model_m;
            out.atmosphere_model_ionosphere_by_receiver_tower_m = ...
                errors.ionosphere.model_m;

            out = ResultBuilder.copyPrefixedFields( ...
                out, diagnostics.truth.ionosphere, ...
                "atmosphere_truth_ionosphere_", ...
                ResultBuilder.ionosphereDiagnosticNames());
            out = ResultBuilder.copyPrefixedFields( ...
                out, diagnostics.model.ionosphere, ...
                "atmosphere_model_ionosphere_", ...
                ResultBuilder.ionosphereDiagnosticNames());
            out = ResultBuilder.copyPrefixedFields( ...
                out, diagnostics.truth.troposphere, ...
                "atmosphere_truth_troposphere_", ...
                ResultBuilder.troposphereDiagnosticNames());
            out = ResultBuilder.copyPrefixedFields( ...
                out, diagnostics.model.troposphere, ...
                "atmosphere_model_troposphere_", ...
                ResultBuilder.troposphereDiagnosticNames());
        end

        function out = addAtmosphereView(out, history)
            errors = history.errors;

            atmosphere = struct();
            atmosphere.truth = struct( ...
                'total_m', errors.atmosphere.truth_m, ...
                'deterministic_total_m', ...
                    errors.atmosphere.deterministicTruth_m, ...
                'troposphere_m', errors.troposphere.deterministicTruth_m, ...
                'ionosphere_m', errors.ionosphere.deterministicTruth_m, ...
                'stochastic_residual_total_m', ...
                    errors.atmosphere.stochasticResidual_m, ...
                'stochastic_residual_troposphere_m', ...
                    errors.troposphere.stochasticResidual_m, ...
                'stochastic_residual_ionosphere_m', ...
                    errors.ionosphere.stochasticResidual_m, ...
                'stochastic_residual_total_by_tower_m', ...
                    errors.atmosphere.stochasticResidualByTower_m, ...
                'stochastic_residual_troposphere_by_tower_m', ...
                    errors.troposphere.stochasticResidualByTower_m, ...
                'stochastic_residual_ionosphere_by_tower_m', ...
                    errors.ionosphere.stochasticResidualByTower_m);
            atmosphere.model = struct( ...
                'total_m', errors.atmosphere.model_m, ...
                'troposphere_m', errors.troposphere.model_m, ...
                'ionosphere_m', errors.ionosphere.model_m);
            atmosphere.residual = struct( ...
                'total_m', errors.atmosphere.residual_m, ...
                'deterministic_total_m', ...
                    errors.atmosphere.deterministicResidual_m, ...
                'troposphere_m', errors.troposphere.residual_m, ...
                'ionosphere_m', errors.ionosphere.residual_m);
            atmosphere.covariance = struct( ...
                'residualTroposphereSigma_m', errors.troposphere.sigma_m, ...
                'residualIonosphereSigma_m', errors.ionosphere.sigma_m, ...
                'sigma_m', errors.atmosphere.sigma_m, ...
                'variance_m2', errors.atmosphere.variance_m2, ...
                'totalSigma_m', errors.atmosphere.sigma_m, ...
                'totalVariance_m2', errors.atmosphere.variance_m2, ...
                'correlation_model', string(errors.atmosphere.correlationModel));
            atmosphere.diagnostics = struct( ...
                'truth_model_residual_definition', ...
                    "residual_m = truth.total_m - model.total_m", ...
                'estimator_truth_residual_access', ...
                    "sampled truth residuals are logged after measurement generation and are not used by prediction");

            out.atmosphere = atmosphere;
        end

        function out = addPropagationView(out, history)
            errors = history.errors;
            zeroClock_m = ResultBuilder.zeroWhereFinite( ...
                errors.relativity.pathTruth_m, ...
                errors.relativity.pathModel_m);

            propagation = struct();
            propagation.frame_used = history.diagnostics.propagation.frame_used;
            propagation.light_time = errors.lightTime;
            propagation.sagnac = errors.legacySagnac;
            propagation.relativity = struct();
            propagation.relativity.truth = struct( ...
                'pathDelay_m', errors.relativity.pathTruth_m, ...
                'clockCorrection_m', zeroClock_m);
            propagation.relativity.model = struct( ...
                'pathDelay_m', errors.relativity.pathModel_m, ...
                'clockCorrection_m', zeroClock_m);
            propagation.relativity.residual = struct( ...
                'total_m', errors.relativity.pathResidual_m);
            propagation.diagnostics = struct( ...
                'note', ...
                    "Propagation error terms are derived from history.errors.");

            out.propagation = propagation;
        end

        function out = addNonAtmosphericView(out, history)
            errors = history.errors;
            componentMap = ResultBuilder.nonAtmosphericComponentMap(errors);
            legacyNames = ["total", "hardware", "antenna", "multipath", ...
                "tower_survey", "legacy_sagnac"];

            nonAtmospheric = struct();
            nonAtmospheric.truth = struct();
            nonAtmospheric.model = struct();
            nonAtmospheric.residual = struct();
            nonAtmospheric.sigma = struct();
            nonAtmospheric.variance = struct();

            for idx = 1:numel(legacyNames)
                legacyName = char(legacyNames(idx));
                fieldName = [legacyName, '_m'];
                component = componentMap.(legacyName);
                nonAtmospheric.truth.(fieldName) = component.truth_m;
                nonAtmospheric.model.(fieldName) = component.model_m;
                nonAtmospheric.residual.(fieldName) = component.residual_m;
                nonAtmospheric.sigma.(fieldName) = component.sigma_m;
                nonAtmospheric.variance.(fieldName) = component.variance_m2;
            end

            nonAtmospheric.diagnostics = struct( ...
                'component_names', string(legacyNames).', ...
                'truth_model_residual_definition', ...
                    "residual_m = truth_m - model_m", ...
                'note', ...
                    "Derived non-atmospheric result view from history.errors.");
            out.non_atmospheric = nonAtmospheric;
        end

        function components = nonAtmosphericComponentMap(errors)
            components = struct();
            components.hardware = errors.hardware;
            components.antenna = errors.antenna;
            components.multipath = errors.multipath;
            components.tower_survey = errors.towerSurvey;
            components.legacy_sagnac = errors.legacySagnac;
            components.total = ResultBuilder.sumErrorComponents( ...
                [components.hardware, components.antenna, ...
                 components.multipath, components.tower_survey, ...
                 components.legacy_sagnac]);
        end

        function component = sumErrorComponents(parts)
            component = parts(1);
            component.truth_m = parts(1).truth_m + parts(2).truth_m + ...
                parts(3).truth_m + parts(4).truth_m + parts(5).truth_m;
            component.model_m = parts(1).model_m + parts(2).model_m + ...
                parts(3).model_m + parts(4).model_m + parts(5).model_m;
            component.residual_m = component.truth_m - component.model_m;
            component.sigma_m = zeros(size(component.truth_m));
            component.sigma_m(~isfinite(component.truth_m)) = NaN;
            component.variance_m2 = component.sigma_m;
        end

        function out = copyPrefixedFields(out, src, prefix, names)
            for name = string(names(:)).'
                fieldName = char(name);
                out.(char(prefix + name + "_by_receiver_tower")) = ...
                    src.(fieldName);
            end
        end

        function names = ionosphereDiagnosticNames()
            names = [
                "ipp_lat_deg"
                "ipp_lon_deg"
                "vtec_TECU"
                "stec_TECU"
                "mapping_factor"
                "frequency_Hz"];
        end

        function names = troposphereDiagnosticNames()
            names = [
                "pressure_hPa"
                "temperature_K"
                "relative_humidity_fraction"
                "water_vapor_pressure_hPa"
                "zhd_m"
                "zwd_m"
                "mapping_hydrostatic"
                "mapping_wet"
                "slant_hydrostatic_m"
                "slant_wet_m"];
        end

        function out = zeroWhereFinite(a, b)
            out = NaN(size(a));
            out(isfinite(a) | isfinite(b)) = 0.0;
        end

        function tf = towerClockEkfEnabled(sim)
            tf = logical(ResultBuilder.getFieldOrDefault( ...
                sim.cfg, 'enableTowerClockEKF', false));
        end

        function value = getFieldOrDefault(s, fieldName, defaultValue)
            if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
                value = s.(fieldName);
            else
                value = defaultValue;
            end
        end
    end
end
