classdef ResultBuilder
    %RESULTBUILDER Builds the simulation results struct.
    %
    % This class owns the mapping from completed simulation state/history into
    % the saved results struct. It does not run the simulation and does not
    % create report-specific data.

    methods (Static)

        function status = errorBudgetStatus(sim)
            mcfg = sim.cfg.measurement;

            status = struct();

            status.truth_model_residual_convention = ...
                "truth enters y; model enters yp; residual_m = truth_m - model_m; estimator gets covariance, not truth random samples";

            status.measurement_domain = ...
                "all pseudorange error-budget terms are represented in metres unless explicitly suffixed _s";

            status.enabled = struct();
            status.enabled.measurement_noise = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableMeasurementNoise', false) || ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableNoise', false);
            status.enabled.atmosphere_truth = ...
                ~isempty(sim.measurementModel.truthAtmosphere) && ...
                sim.measurementModel.truthAtmosphere.isEnabled();
            status.enabled.atmosphere_model = ...
                ~isempty(sim.measurementModel.modelAtmosphere) && ...
                sim.measurementModel.modelAtmosphere.isEnabled();
            status.enabled.hardware_delay = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableHardwareDelay', false);
            status.enabled.multipath_delay = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableMultipathDelay', false);
            status.enabled.stochastic_multipath = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableStochasticMultipath', false);
            status.enabled.antenna_delay = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableAntennaDelay', false);
            status.enabled.tower_survey_error = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableTowerSurveyError', false);
            status.enabled.legacy_sagnac_scalar = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableSagnacCorrection', false);
            status.enabled.light_time_truth = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrectionTruth', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrection', false));
            status.enabled.light_time_model = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrectionModel', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableLightTimeCorrection', false));
            status.enabled.relativistic_path_truth = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelayTruth', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelay', false));
            status.enabled.relativistic_path_model = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelayModel', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticPathDelay', false));
            status.enabled.relativistic_clock_truth = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrectionTruth', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrection', false));
            status.enabled.relativistic_clock_model = ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrectionModel', ...
                ResultBuilder.getFieldOrDefault(mcfg, 'enableRelativisticClockCorrection', false));

            clockModel = ResultBuilder.getFieldOrDefault( ...
                sim.cfg.process, 'clockModel', "brownHwang");
            clockModelKey = lower(regexprep(strtrim(string(clockModel)), ...
                '[-_]', ''));
            status.clock_model = string(clockModel);
            if clockModelKey == "coupledgaussmarkov"
                status.experimental = ...
                    "coupledGaussMarkov clock process-noise model is experimental/guarded pending dedicated derivation and regression tests";
            else
                status.experimental = strings(1, 0);
            end

            status.implemented = [ ...
                "truth/model atmosphere with same-tower residual covariance", ...
                "measurement noise as independent pseudorange variance", ...
                "hardware truth/model global TX/RX delay", ...
                "deterministic multipath truth/model correction", ...
                "stochastic multipath truth sample with independent diagonal R variance", ...
                "scalar antenna truth/model correction", ...
                "tower survey ECEF offset range-effect truth/model correction", ...
                "ECI inertial iterative light-time truth/model correction", ...
                "legacy scalar Sagnac truth/model placeholder with light-time conflict guard"];

            status.guarded_not_implemented = [ ...
                "Shapiro relativistic path delay truth/model correction", ...
                "relativistic clock correction", ...
                "carrier-phase observables", ...
                "full antenna PCO/PCV truth/model calibration chain", ...
                "tower-specific hardware model delay", ...
                "full ECEF-frame Sagnac propagation mode"];

            status.diagnostics_available = [ ...
                "history.errors", ...
                "history.diagnostics", ...
                "history.measurement_covariance_*", ...
                "prefit_residual_by_receiver_tower_m", ...
                "postfit_residual_by_receiver_tower_m"];

            status.position_error_warning = ...
                "position error alone is not sufficient; common-mode range errors can be absorbed by receiver/tower clock states, so inspect innovations, residual budgets, and R";
        end

        function results = fromSimulation(sim)
            results = struct();
            results.history = sim.history;
            results.time_s = sim.time_s;
            results.scenario_name = sim.scenarioName;
            results.receiver_names = sim.receiverNames;
            results.tower_names = sim.towerNames;
            results.error_budget_status = ...
                ResultBuilder.errorBudgetStatus(sim);
        end
    end

    methods (Static, Access = private)
        function value = getFieldOrDefault(s, fieldName, defaultValue)
            if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
                value = s.(fieldName);
            else
                value = defaultValue;
            end
        end
    end
end
