classdef GaseousAbsorption
    % GaseousAbsorption  Frozen ITU-R P.676 gaseous attenuation for the freq ladder.
    %
    % Oxygen and water vapour absorb the carrier itself. Nothing in the model carried
    % this before: the C/N0 chain is base_dBHz + elevationGain_dB*sin(el), elevation
    % only, with no frequency dependence and no atmosphere. That is harmless at L-band
    % and wrong by two orders of magnitude at 61 GHz, which sits inside the oxygen
    % absorption complex.
    %
    % WHY A FROZEN TABLE RATHER THAN A MODEL. The freq ladder visits nine carrier
    % frequencies, so a continuous function of frequency was never needed. The table is
    % reviewable, diffable and bit-stable, it cannot silently change under a refactor,
    % and it is three literals instead of 160 lines of physics needing their own tests.
    % The generator that produced it IS committed, so the numbers are reproducible
    % rather than pasted -- analysis/generate_gas_absorption_table.m, plain MATLAB, no
    % toolbox, runs in 0.2 s. Adding a frequency is a one-line edit there.
    %
    % PROVENANCE. Recommendation ITU-R P.676-13 Annex 1, the line-by-line REFERENCE
    % method (not Annex 2's approximation, which runs 4-11% low). Integrated over the
    % ITU-R P.835 mean annual global reference atmosphere in 100 m layers to 80 km.
    % analysis/compare_p676_implementations.m checks the generator against an
    % independent transcription of the same Recommendation and gets EXACTLY zero
    % relative error on the dry path.
    %
    % WHY DRY AND WET ARE SEPARATE COLUMNS. Oxygen and water vapour have genuinely
    % different scale heights, so a single total mapped one way would be wrong at low
    % elevation. Keeping them apart lets the slant composition mirror the troposphere's
    % own ZHD*m_h + ZWD*m_w (EnvironmentModel.m:443) and reuse the same Niell mapping
    % functions, and it lets the wet column follow the per-tower humidity that the
    % weather state already carries. That coupling matters at exactly one band: at
    % 24.125 GHz water vapour is 81% of the total, everywhere else it is under 8%.
    %
    % SCALE OF THE EFFECT, so nobody has to re-derive it:
    %   below 6 GHz   under 0.5% on code sigma at zenith, ~2.2% at the 10 deg mask
    %   24.125 GHz    4.6% on sigma
    %   61.25 GHz     161 dB, i.e. C/N0 51 -> -110 dB-Hz. The link does not close.
    %
    % ⚠ 915 MHz is BELOW P.676's stated 1-1000 GHz validity floor. The generator
    % evaluates there anyway and the independent reference refuses the frequency
    % outright. At 0.030 dB it changes nothing, but freq009 must carry the caveat
    % rather than imply a validated value.

    properties (Constant)
        % ---- frozen table ---------------------------------------------------
        % Generated by analysis/generate_gas_absorption_table.m
        % ITU-R P.676-13 Annex 1; P.835 mean annual global reference atmosphere,
        % 7.5 g/m^3 surface water vapour density.
        TABLE_F_HZ = [0.91500e9 1.17645e9 1.22760e9 1.57542e9 2.45000e9 ...
                      5.20000e9 5.80000e9 24.12500e9 61.25000e9];

        TABLE_A_DRY_DB = [0.030157 0.032175 0.032454 0.033786 0.035241 ...
                          0.037009 0.037373 0.073387 161.194782];

        TABLE_A_WET_DB = [0.000072 0.000119 0.000129 0.000213 0.000517 ...
                          0.002396 0.003009 0.317082 0.272657];

        % Zenith wet delay of the SAME reference atmosphere the wet column was
        % computed for. Denominator of the per-tower humidity scaling, so the two
        % cannot disagree about how much water vapour "nominal" means.
        ZWD_REF_M = 0.095669;

        % Relative tolerance for matching a requested frequency to a table entry.
        % Frequencies arrive from config as exact literals, so this only absorbs
        % float round-trips, never a genuinely different band.
        F_MATCH_RTOL = 1e-9;
    end

    methods (Static)

        function [A_dry_dB, A_wet_dB] = zenithDryWet(f_Hz)
            % zenithDryWet  Frozen zenith attenuation at a tabulated frequency.
            %
            %   [A_dry, A_wet] = zenithDryWet(f_Hz)
            %
            % HARD ERRORS off-table rather than interpolating. That is deliberate: the
            % 22.235 GHz water line and the 60 GHz oxygen complex make interpolation
            % meaningless above ~20 GHz, and a silently interpolated value would be
            % indistinguishable from a computed one. Regenerating for a new frequency
            % is a one-line edit to the generator, so refusing costs nothing.
            models.atmosphere.GaseousAbsorption.validateFrequency_(f_Hz);

            fTab = models.atmosphere.GaseousAbsorption.TABLE_F_HZ;
            rtol = models.atmosphere.GaseousAbsorption.F_MATCH_RTOL;
            idx  = find(abs(fTab - f_Hz) <= rtol * f_Hz, 1);

            if isempty(idx)
                error('GaseousAbsorption:frequencyNotTabulated', ...
                    ['No frozen P.676 entry for %.6f MHz. The table is deliberately NOT ' ...
                     'interpolated -- absorption is non-smooth near the 22.235 GHz water ' ...
                     'line and through the 54-66 GHz oxygen complex. Add the frequency to ' ...
                     'analysis/generate_gas_absorption_table.m, re-run it, and paste the ' ...
                     'result into GaseousAbsorption.TABLE_*. Tabulated [MHz]: %s.'], ...
                    f_Hz/1e6, strjoin(compose('%.2f', fTab/1e6), ', '));
            end

            A_dry_dB = models.atmosphere.GaseousAbsorption.TABLE_A_DRY_DB(idx);
            A_wet_dB = models.atmosphere.GaseousAbsorption.TABLE_A_WET_DB(idx);
        end

        function A_dB = slantAttenuation_dB(f_Hz, elevation_rad, opts)
            % slantAttenuation_dB  Gaseous attenuation along a slant path [dB].
            %
            %   A = A_dry*m_h(el) + A_wet*m_w(el)*(ZWD_tower / ZWD_ref)
            %
            % Structurally identical to the troposphere's ZHD*m_h + ZWD*m_w, and it
            % calls the same MappingFunctions, so absorption and the tropospheric delay
            % can never disagree about the obliquity of the atmosphere they share.
            %
            % opts (all optional):
            %   .mappingKind   'simple' (1/sin el, default) | 'niell'
            %   .ZWD_m         tower zenith wet delay [m]; default ZWD_REF_M, i.e. the
            %                  reference humidity, which makes the wet ratio exactly 1
            %   .latitude_rad  }
            %   .doy           }  only read when mappingKind is 'niell'
            %   .height_km     }
            if nargin < 3 || isempty(opts); opts = struct(); end

            [A_dry_dB, A_wet_dB] = models.atmosphere.GaseousAbsorption.zenithDryWet(f_Hz);

            if ~isscalar(elevation_rad) || ~isnumeric(elevation_rad) || ~isfinite(elevation_rad)
                error('GaseousAbsorption:badElevation', ...
                    'slantAttenuation_dB needs a finite scalar elevation [rad]; got %s.', ...
                    mat2str(elevation_rad));
            end

            kind = 'simple';
            if isfield(opts, 'mappingKind') && ~isempty(opts.mappingKind)
                kind = opts.mappingKind;
            end

            zwdRef = models.atmosphere.GaseousAbsorption.ZWD_REF_M;
            zwd    = zwdRef;
            if isfield(opts, 'ZWD_m') && ~isempty(opts.ZWD_m)
                zwd = opts.ZWD_m;
                if ~isscalar(zwd) || ~isnumeric(zwd) || ~isfinite(zwd) || zwd < 0
                    error('GaseousAbsorption:badZwd', ...
                        'opts.ZWD_m must be a finite non-negative scalar [m]; got %s.', ...
                        mat2str(zwd));
                end
            end

            [m_h, m_w] = models.atmosphere.GaseousAbsorption.mapping_(elevation_rad, kind, opts);

            A_dB = A_dry_dB * m_h + A_wet_dB * m_w * (zwd / zwdRef);
        end

        function tf = isTabulated(f_Hz)
            % isTabulated  True when the frozen table covers f_Hz.
            %   For callers that need to branch rather than fail, e.g. a resolve-time
            %   guard reporting every unsupported band at once instead of the first.
            models.atmosphere.GaseousAbsorption.validateFrequency_(f_Hz);
            fTab = models.atmosphere.GaseousAbsorption.TABLE_F_HZ;
            rtol = models.atmosphere.GaseousAbsorption.F_MATCH_RTOL;
            tf   = any(abs(fTab - f_Hz) <= rtol * f_Hz);
        end

    end

    methods (Static, Access = private)

        function validateFrequency_(f_Hz)
            if ~isscalar(f_Hz) || ~isnumeric(f_Hz) || ~isfinite(f_Hz) || f_Hz <= 0
                error('GaseousAbsorption:badFrequency', ...
                    'Frequency must be a finite positive scalar [Hz]; got %s.', mat2str(f_Hz));
            end
        end

        function [m_h, m_w] = mapping_(elevation_rad, kind, opts)
            % mapping_  Hydrostatic and wet obliquity, same functions the troposphere uses.
            %   Mirrors EnvironmentModel.tropMapping_, which is private to that class.
            %   The Niell coefficients themselves are NOT duplicated -- both routes call
            %   models.atmosphere.MappingFunctions.
            elvFloor = revgnss.Constants.ELEVATION_FLOOR_RAD;
            switch kind
                case 'niell'
                    lat = 0; doy = 1; hkm = 0;
                    if isfield(opts, 'latitude_rad') && ~isempty(opts.latitude_rad)
                        lat = opts.latitude_rad;
                    end
                    if isfield(opts, 'doy') && ~isempty(opts.doy); doy = opts.doy; end
                    if isfield(opts, 'height_km') && ~isempty(opts.height_km)
                        hkm = opts.height_km;
                    end
                    m_h = models.atmosphere.MappingFunctions.niellHydrostatic( ...
                        elevation_rad, lat, doy, hkm);
                    m_w = models.atmosphere.MappingFunctions.niellWet(elevation_rad, lat);

                case 'simple'
                    m   = 1 / max(sin(elevation_rad), sin(elvFloor));
                    m_h = m;
                    m_w = m;

                otherwise
                    error('GaseousAbsorption:unknownMappingKind', ...
                        ['Unknown mappingKind ''%s''. Use ''simple'' or ''niell'' -- the ' ...
                         'same two the troposphere accepts.'], kind);
            end
        end

    end
end
