function generate_gas_absorption_table()
% generate_gas_absorption_table  Freeze ITU-R P.676 zenith gaseous attenuation.
%
% GENERATOR, run by hand. Its OUTPUT is committed as a fixed table inside
% models.atmosphere.GaseousAbsorption. Nothing in the simulation calls this.
%
% PLAIN MATLAB, NO TOOLBOX -- here or at run time. Uses p676_annex1.m, the
% line-by-line REFERENCE method of Recommendation ITU-R P.676-13 Annex 1.
% Annex 2's closed-form approximation is also implemented (p676_annex2.m) and
% is retained only as a cross-check; it runs 4-11% low and is not used here.
%
% Emits the DRY-AIR and WATER-VAPOUR zenith attenuation SEPARATELY, because the
% runtime model composes them against different mapping functions:
%
%     A(f, el, tower) = A_dry(f)*m_h(el) + A_wet(f)*m_w(el)*(ZWD_tower/ZWD_ref)
%
% mirroring the troposphere's ZHD*m_h + ZWD*m_w at EnvironmentModel.m:443, so
% tropMapping_ is reused rather than inventing a second obliquity law. Oxygen
% and water vapour have genuinely different scale heights, so a single total
% mapped one way would be wrong at low elevation.
%
% PROFILE: ITU-R P.835 mean annual global reference atmosphere. Annex 1 gives a
% POINT value, so the vertical structure is integrated here -- P.676 Annex 1
% section 2.2 numerical integration, 100 m layers to 80 km.
%
% VALIDATION (see compare_p676_implementations.m):
%   - dry path, e = 0, against the independent MathWorks P.676-10 line-by-line
%     implementation: relative error EXACTLY 0.00e+00 at every ladder frequency.
%     Equations (1)-(9) and Table 1 are therefore transcribed correctly.
%   - total, rho = 7.5: -0.12% to -3.52%, entirely the P.676-13 vs -10 water
%     vapour table revision, which is a version difference and not an error.

    % ---- frequencies the freq ladder visits --------------------------------
    f_GHz = [0.915 1.17645 1.22760 1.57542 2.45000 5.20000 5.80000 24.12500 61.25000];
    label = {'915 ISM','1176.45 L5','1227.60 L2','1575.42 L1','2450 ISM', ...
             '5200 U-NII','5800 ISM','24125 ISM','61250 ISM'};

    % ---- P.835 mean annual global reference atmosphere ---------------------
    dh_m   = 100;
    hmax_m = 80e3;
    h_km   = ((0:dh_m:hmax_m-dh_m)' + dh_m/2) / 1000;

    T_K   = zeros(size(h_km));
    P_hPa = zeros(size(h_km));
    i1 = h_km <  11;               i2 = h_km >= 11 & h_km < 20;
    i3 = h_km >= 20 & h_km < 32;   i4 = h_km >= 32 & h_km < 47;
    i5 = h_km >= 47;
    T_K(i1)   = 288.15 - 6.5*h_km(i1);
    P_hPa(i1) = 1013.25 * (T_K(i1)/288.15).^5.25588;
    T_K(i2)   = 216.65;
    P_hPa(i2) = 226.321 * exp(-0.157688*(h_km(i2)-11));
    T_K(i3)   = 216.65 + 1.0*(h_km(i3)-20);
    P_hPa(i3) = 54.7489 * (216.65./T_K(i3)).^34.1626;
    T_K(i4)   = 228.65 + 2.8*(h_km(i4)-32);
    P_hPa(i4) = 8.68019 * (228.65./T_K(i4)).^12.2009;
    T_K(i5)   = 270.65;
    P_hPa(i5) = 1.10906 * exp(-0.126226*(h_km(i5)-47));

    RHO0_GM3 = 7.5;                             % P.835 surface water vapour
    rho_gm3  = RHO0_GM3 * exp(-h_km/2);
    e_hPa    = rho_gm3 .* T_K / 216.7;
    Pd_hPa   = max(P_hPa - e_hPa, 1e-9);        % Annex 1 wants DRY air pressure

    % ---- reference ZWD for the same atmosphere ------------------------------
    IWV_kgm2 = (RHO0_GM3/1000) * 2000;                       % rho0 * scale height
    Tm_K     = 70.2 + 0.72*288.15;                           % Bevis et al. (1992)
    k2p_KPa  = 22.1e-2;  k3_K2Pa = 3.776e5/100;              % Bevis et al. (1994)
    ZWD_ref  = 1e-6 * (k2p_KPa + k3_K2Pa/Tm_K) * 461.5 * IWV_kgm2;
    assert(ZWD_ref > 0.02 && ZWD_ref < 0.60, ...
        'ZWD_ref = %.4f m is outside the physical zenith wet delay range.', ZWD_ref);

    % ---- layered integration ------------------------------------------------
    n = numel(f_GHz);
    A_dry = zeros(1,n); A_wet = zeros(1,n);
    dh_km = dh_m/1000;
    for k = 1:n
        for j = 1:numel(h_km)
            [go, gw] = p676_annex1(f_GHz(k), Pd_hPa(j), T_K(j), rho_gm3(j));
            A_dry(k) = A_dry(k) + go*dh_km;
            A_wet(k) = A_wet(k) + gw*dh_km;
        end
    end
    A_tot = A_dry + A_wet;

    % ---- report -------------------------------------------------------------
    fprintf('\nITU-R P.676-13 Annex 1 (line-by-line), ZENITH gaseous attenuation\n');
    fprintf('P.835 mean annual global, %.1f g/m^3 surface WV, ZWD_ref = %.6f m\n\n', ...
        RHO0_GM3, ZWD_ref);
    fprintf('%-13s %12s %12s %12s %12s\n','band','A_dry dB','A_wet dB','total dB','sigma x');
    for k = 1:n
        fprintf('%-13s %12.6f %12.6f %12.6f %12.4g\n', ...
            label{k}, A_dry(k), A_wet(k), A_tot(k), 10^(A_tot(k)/20));
    end

    fprintf('\n%% ---- frozen table: paste into models.atmosphere.GaseousAbsorption ----\n');
    fprintf('%% Generated by analysis/generate_gas_absorption_table.m\n');
    fprintf('%% ITU-R P.676-13 Annex 1 line-by-line; P.835 mean annual global atmosphere.\n');
    fprintf('%% 915 MHz is below P.676''s stated 1 GHz floor -- see the plan''s B5.\n');
    fprintf('ZWD_REF_M      = %.6f;\n', ZWD_ref);
    fprintf('TABLE_F_HZ     = ['); fprintf('%.5fe9 ', f_GHz); fprintf('];\n');
    fprintf('TABLE_A_DRY_DB = ['); fprintf('%.6f ', A_dry);   fprintf('];\n');
    fprintf('TABLE_A_WET_DB = ['); fprintf('%.6f ', A_wet);   fprintf('];\n');
end
